test/correctness/simd_op_check.cpp

I suggest we temporarily disable these to get the buildbots clean.

Temporarily disable paddusb and paddusw due to #3281

---

src/runtime/HalideBuffer.h

These two things really need to be inlined along with all the other operator()-related methods. Otherwise they take a huge amount of the total runtime in debug builds. If they get inlined, the flag setting can be hoisted out of the inner loop over elements.

Add ALWAYS_INLINE qualifiers to fix debug mode performance

---

src/AsyncProducers.cpp

If lets is nonempty, the rewrap loop never exits. Switch to reverse iteration.

Fix rewrap in InitializeSemaphores

---

test/correctness/simd_op_check.cpp

These tests were failing because the new simplifier was converting
(rightly) select(v0 < v1, v0, v1) to min(v0, v1) thus not matching
vcmp.gt.

Fix HVX vcmp.gt tests in simd_op_check.cpp

---

src/HexagonAlignment.h

@dsharletg @pranavb-ca @dpalermo PTAL.
I was getting the following failure for scatters on hexagon: "modulus_remainder of vector".
The patch resolves the error.
test/correctness/hexagon_scatter from https://github.com/halide/Halide/pull/3309 needs this patch for successful run without hvx_v65 target feature.

Hexagon Alignment Failures - modulus_remainder of vector

---

apps/fft/Makefile

In order to resolve buildbots not recompiling the FFT app, make it depend on libHalide.
Apps that use generators depend on `GENERATOR_DEPS` so are not afflicted by the non-recompilation problem.

Rebuild FFT app when libHalide changes

---

src/runtime/device_interface.cpp
test/correctness/device_buffer_copy.cpp

Add tests for three cases and fix code to make them pass.
1) Copying from a device to the host side of a buffer with a different device interface. This could fail with an error indicating that it was trying to switch device interfaces on the destination buffer. This now works. (One test added, requires having two GPU APIS in HL_JIT_TARGET in order to run.)
2) Copying to the host side of a buffer with a null host pointer. This now returns an error instead of segfaulting. (Two tests added. One requires two GPU APIs and the other only one.)

Device buffer copy fixes

---

src/IROperator.h

The previous version of the documentation made it sound like it's the type that clamps, not the cast.

Clarify documentation for saturating_cast

---

src/Generator.cpp
src/Generator.h
test/generator/metadata_tester_aottest.cpp
test/generator/metadata_tester_generator.cpp

Our metadata format was designed to emit null fields for def/min/max of scalar values when said values aren't defined; in the case of Generators with Input<SomeScalar>, we were emitting a default of zero (rather than "no default") for the case of no-default-specified. This fixes the issue and updates the test.

Only emit default-values to metadata when defined

---

src/CodeGen_OpenGLCompute_Dev.cpp
src/runtime/mini_opengl.h
src/runtime/openglcompute.cpp

OpenGL Compute pretty much only supports 32-bit integers. Do data conversion on copy_to_device and copy_to_host. Handle conversion of 8-bit and 16-bit ints as arguments as well. Not exactly incredibly performant, but it either didn't compile or produced garbage before.

Make OpenGL Compute backend handle non-32-bit integer types.

---

src/HexagonOptimize.cpp

On simd_op_check I was seeing two failures -  Unable to match vdmpy and vrmpy. This is mainly because the new simplifier and GroupLoopInvariants reassociate some add expressions causing them to fall through the cracks in our pattern matching logic.
@dsharletg, @aankit-ca, @dpalermo, @suyogsarda  - PTAL.

fix simd op check vdmpy and vrmpy failures

---

src/Func.h

(Basically just converting a segfault into an assertion failure in a degenerate case found in a branch. Shouldn't be needed, but good hygiene.)

Stage ctor should assert that definition is defined

---

src/StorageFolding.cpp
test/correctness/storage_folding.cpp

Currently, fold_storage uses the dimension index to look up explicit folding information. However, reorder_storage changes the storage dimension ordering, leading to the explicit storage folding factor being used for the wrong dimension.

Fix fold_storage when reorder_storage is used

---

src/ExprUsesVar.h

Speeds up local laplacian lowering by 5% or so.

expr_uses_var can early-out when the var is found

---

apps/glsl/CMakeLists.txt
test/CMakeLists.txt

CMake 3.11 and above prefer to use the vendor libraries, while 3.10 and below prefer the legacy libraries. Making the preference explicit also suppresses the warning produced by `find_package(OpenGL)`. When only one is available, it uses that one, regardless of the preference set.
We can also choose to use `LEGACY` instead of `GLVND`, if that's what you all prefer, but I think the preference should be set to suppress the warning.
See the following documentation: https://cmake.org/cmake/help/git-stage/policy/CMP0072.html

Explicitly prefer using OpenGL vendor libraries when available in CMake.

---

apps/glsl/Makefile
src/Lower.cpp
test/correctness/gpu_bounds_inference_failure.cpp

Moving `canonicalize_gpu_vars` after storage flattening causes OpenGL to fail, since it relies on some transformations done during storage flattening.  This PR tries to resolve #3371 while preserving the fix to #3221 by moving canonicalization just before storage flattening.

Fix GLSL failures due to fix of #3221

---

src/CodeGen_Metal_Dev.cpp
test/error/metal_vector_too_large.cpp

(https://github.com/halide/Halide/issues/3372 ) PR turns this into an error and adds a test.

Fix for error in Metal compilation when vectors greater than four lanes are used.

---

src/Type.h
src/runtime/HalideRuntime.h

...so that halide_type_t can be used as the key for std::map, etc.

Add operator< to halide_type_t

---

tools/RunGen.h
tools/halide_image_io.h

Previously you couldn't do this; you had to call `alias()` as a workaround. Update RunGen.h to actually cast to const void when saving.

Allow halide_image_io save() methods to work on Buffer<const T>

---

tools/RunGen.h

The logic for fix_chunky_strides() was inappropriately rewriting extent[2] for this degenerate case.

RunGen: special-case 1x1 images

---

src/HexagonOptimize.cpp
test/generator/async_parallel_aottest.cpp

In libc++ under C++17, std::map, std::set, std::multimap and std::multiset require the key_compare’s operator() be const.

Make comparison functors const for C++17 compatibility

---

src/ScheduleFunctions.cpp
test/correctness/compute_at_reordered_update_stage.cpp
test/correctness/compute_at_update_stage.cpp

Also adds regression test in correctness to prevent issue from being
reintroduced. Store level can be a false positive if an earlier update
stage doesn't reference the injected function.

Remove assertion that every store level contains a compute level. Fix #3388

---

src/runtime/write_debug_image.cpp

StripByteCounts is a byte count, not an element count, thus it needs to be multiplied by bytes_per_element (so all TIFFs with > u8 size were wrong)

write_debug_image was wrong for TIFF

---

.travis.yml
test/scripts/build_travis.sh

It's not in use by anyone and the version we test against is ancient. Better to drop it entirely and save build/test time.

Drop Bazel testing from Travis

---

test/correctness/convolution.cpp
test/correctness/parallel_gpu_nested.cpp
tutorial/lesson_12_using_the_gpu.cpp

A temporary workaround for the buildbot failure which is under investigation, to prevent some known failures from failing entire builds.

Temporarily disable correctness_convolution for Feature::Metal

---

src/runtime/metal.cpp
test/correctness/convolution.cpp
test/correctness/parallel_gpu_nested.cpp
tutorial/lesson_12_using_the_gpu.cpp

Using `NSZombieEnabled=YES` points to the `MTLFunction` being freed before use; adding a `retain` appears to fix the issue.  This should fix #3395 and #3408.

Fix Metal crashes in Mojave

---

src/JITModule.cpp

If I understand correctly, this should be fixed as of https://reviews.llvm.org/rL286032, which is in LLVM7 and trunk.
(Note that this doesn't fix the outstanding JIT crash on arm32+LLVM7, but is just a change I noticed while debugging it.)

Remove work_around_llvm_bugs for LLVM >= 7.0

---

src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_D3D12Compute_Dev.h
src/CodeGen_Metal_Dev.cpp
src/CodeGen_Metal_Dev.h
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_PTX_Dev.cpp
src/CodeGen_PTX_Dev.h
src/FuseGPUThreadLoops.cpp
src/IR.cpp
src/IR.h
src/LLVM_Runtime_Linker.cpp
src/PartitionLoops.cpp
src/runtime/ptx_dev.ll
test/correctness/gpu_thread_barrier.cpp

This cleans up the code a bit and removes the requirement of a runtime
routine being inlined in GPU kernel code in order for it to be
correct.
Fixes issue: https://github.com/halide/Halide/issues/3397 .

Convert GPU thread barrier to an intrinsic.

---

test/correctness/async_copy_chain.cpp

Let see how this does in tests.

Try reenabling async_copy_chain on Windows after fix for buffer_lets.

---

src/Generator.cpp

If you pass a not-yet-defined Func (etc) as input to a GeneratorStub, you fail with an astonishingly unhelpful error message deep in the bowels of check_matching_types. Make this better.

Add more-useful error messages for GeneratorStubs

---

python_bindings/correctness/buffer.py

These were missing. Now they aren't.

Add tests for interleaved Buffers and ndarrays

---

test/correctness/simd_op_check.cpp

Appears to have been injected by https://reviews.llvm.org/rL345602

Disable psubsub/psubusw checks in simd_op_check (Issue #3281)

---

src/Buffer.h

There was no way to make a named scalar buffer that just points to existing data.

Forward a missing constructor from Runtime::Buffer

---

src/RDom.cpp
test/correctness/let_in_rdom_bound.cpp

Synthetically created RDoms (e.g. in autodiff pipelines) may have Lets.

Handle lets in rdom bounds

---

src/BoundsInference.cpp
test/correctness/compute_at_split_rvar.cpp

Computation bounds inference didn't really understand guardwithif when it comes to splitting rvars. This issue was causing schedules that overread the input and segfault due to #3036. It would be good to also fix #3036, but as the comments on #3037 show, allocation bounds inference is currently too conservative for this to be feasible.

Fix overcompute when compute_at a split rvar that doesn't divide the original extent

---

src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.h
src/CodeGen_OpenGL_Dev.cpp
src/CodeGen_OpenGL_Dev.h
src/Target.cpp
src/runtime/openglcompute.cpp
test/correctness/math.cpp

Requires refactoring a small amount of code so plain GLSL
and GLSL Compute Shaders can use different names for "trunc". (The
name "trunc" might actually work everywhere we care about now, but
there's no way to tell and I don't want to break anything that works
currently.)
Making it so Target doesn't claim GL backends support 64-bit float. It
is possible some implementations do, but our backends don't do
precision control, etc.
Modify correctness/math.cpp to work with OpenGLCompute.

Get OpenGLCompute backend to pass the math test by adding intrinsics.

---

src/Simplify_Call.cpp

The simplifier wasn't folding intrinsics applied to vector constants, because FloatImm::make requires a scalar type. Instead it was failing an assertion. For this issue trigger you have to construct an expression which manages to simplify to a constant only after it's vectorized. This was found when scheduling random pipelines randomly.
Fixed by replacing FloatImm::make with make_const, which is the more natural counterpart to as_const_float.

Use make_const when folding float intrinsics to handle vectors

---

src/CodeGen_OpenGLCompute_Dev.cpp

Loop fusion can produce code with overlapping blocks that have allocations with
the same name that shadow each other.

Add block nesting for allocate nodes in OpenGL Compute.

---

src/runtime/HalideBuffer.h

It doesn't compile for const values of T, we need to use remove_const. Since static_halide_type() already does that, use that instead.

don't use halide_type_of<T>() in HalideBuffer.h

---

src/Simplify.cpp

This makes it slightly more powerful. 
Also report the original unsimplified expression too when a proof fails so we know what original state got the simplifier stuck in a local minimum.

Make can_prove use CSE and trim dead lets

---

Makefile
src/Argument.cpp
src/Argument.h
src/CMakeLists.txt
src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/Generator.cpp
src/HexagonOffload.cpp
src/InferArguments.cpp
src/Lower.cpp
src/Module.cpp
src/Module.h
src/OutputImageParam.cpp
src/Param.h
src/Parameter.cpp
src/Parameter.h
src/Pipeline.cpp
src/WrapExternStages.cpp
test/correctness/infer_arguments.cpp

This is a refactoring of Argument to move the auto-schedule estimates into it, as preparation for adding them to the generated Metadata. (There turned out to be substantial amounts of drive-by changes, but I think they are worthwhile.)

Refactor Argument, add ArgumentEstimates

---

tools/RunGen.h

- don't fail for missing estimate metadata if dimensions = 0
- actually use the parsed result for scalar estimates instead of dropping it on the floor

Fix two mistakes in RunGen

---

src/Dimension.cpp
src/Func.cpp
test/generator/metadata_tester_aottest.cpp
test/generator/metadata_tester_generator.cpp

Suggestion from @abadams: if we have hard boundaries, we should set the autoschedule estimate values to that as well.
(Lots of drive-by churn in the test that was updated, as the old version wouldn't show the values when mismatches were found, making debugging painful.)

bound()/set_bounds() should also call estimate()/set_bounds_estimate()

---

src/CodeGen_C.cpp

Generated code rom the C++ backend tries to automatically detect when it can use clang/GCC native vector types. Apparently emscripten claims to support the via the __has_attribute machinery and then fails later in compilation. (This is a bug in emscripten in that it claims to support the vector types and does not, but making it just work seems worthwhile. Change will need to be removed at some
point.)

Change C++ backend to not use native vector types with emscripten.

---

README_rungen.md
tools/RunGen.h

- Need to ensure to set scalar inputs before running a bounds query for buffer inputs; otherwise, the results may be wrong.
- add "estimate_then_auto" as an option for buffer inputs

More RunGen fixes

---

src/AutoSchedule.cpp
test/correctness/autoschedule_small_pure_update.cpp

I encountered a bug where loads from inputs via a trivially inlined Func weren't discovered by the logic in the autoscheduler that decides if RoundUp is safe for a tail strategy.

Fix tail selection strategy in autoscheduler

---

src/runtime/HalideRuntime.h

Trivial, but confuses users.  Now that macOS/iOS use pthreads, `halide_set_num_threads()` does indeed have an effect.

Remove stale comment about halide_set_num_threads()

---

src/Pipeline.cpp
src/Pipeline.h
test/correctness/custom_auto_scheduler.cpp

The goal is to be able to apply new autoschedulers to existing generators by linking them in and having them install themselves in global constructors, or by writing a custom GenGen.cpp that installs one of your choice.

Make it possible to install an autoscheduler as a plugin

---

src/Scope.h
src/Simplify_Internal.h
src/Util.h

Classes like ScopedFact will misbehave if they are accidentally copied (rather than moved); delete the copy ctor and default the move ctor.
(Apparently VS2015 is copying ScopedFact when it could be moving it, which seems to be the cause of the debug-only crash; not sure if that's legal for C++11 or not, but this is a good fix in any event.)

Disallow copy ctor in various Scope utilities

---

apps/support/Makefile.inc
src/IRMatch.h
src/Introspection.cpp

Built and tested with -fsanitize=undefined; fixed a handful of technically-UB-but-no-big-deal issues reported:
- misaligned loads
- incorrect downcasting

Fix some UBSan warnings

---

src/Generator.cpp
src/Util.cpp

Apparently this is OK on Linux, but definitely not on OSX or elsewhere.

Don't attempt to dlopen() empty strings

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/Makefile
apps/autoscheduler/augment_sample.cpp
apps/autoscheduler/autotune_loop.sh
apps/autoscheduler/train_cost_model.cpp
apps/support/Makefile.inc
tools/RunGen.h

(These PR is a result of doing a walkthrough of apps/autoscheduler to be sure I understood the workflow, in anticipation of porting it to Google's internal build system; some of these are probably sensible changes, some are probably pointless nitpickery in code style, and some may actually be counterproductive. Happy to cherrypick any/all of these.)
- AutoSchedule: attempt listing all the env vars used. (Exact definitions needed for each.)
- AutoSchedule: dump the generated C++ schedule to HL_SCHEDULE_FILE, in addition to having it lumped in with the general log
- autotune_loop.sh and RunGen.h: make the benchmark/compile loop output a little less verbose
- autotune.sh: split insanely long lines into multilines
- autotune.sh: give each sample variant a unique function name, this allows us …

Grab bag of minor cleanups

---

apps/autoscheduler/cost_model_generator.cpp
apps/autoscheduler/cost_model_schedule.h

(Things found while bringing up in google build env)
-- revise cost_model_schedule.h to be valid C++ when compiled on its own (ie, with the proper includes, wrapped in a function), rather than relying on inclusion in the proper spot; this is good hygiene in general, and essentially required for C++ modules to work in the future. (Unless there is disagreement with this change, I intend to make a followup PR to have the C++-schedule-dumping-code do this sort of wrapping by default.)
-- remove unused lamba in cost_model_generator.cpp

Various fixes for apps/autoscheduler

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/ThroughputPredictorPipeline.h
apps/autoscheduler/train_cost_model.cpp

- avoid unused-var warning re: assert
- wrap using statements (and other internal stuff) in anon namespace
- convert the StateMap in AutoSchedule to wrap values in unique_ptr as temporary workaround for an apparent compiler bug

More minor fixes

---

apps/autoscheduler/Makefile
apps/autoscheduler/autotune_loop.sh
apps/autoscheduler/test.cpp
apps/random_pipeline/Makefile
apps/random_pipeline/autotune_loop.sh
apps/random_pipeline/bench_comparison.sh

For stupid reasons, it is much easier to build shared libs with names of the pattern libXYZ.so in google, because reasons. (I'm assuming no one else cares much about the specific name.)

Rename auto_schedule.so -> libauto_schedule.so

---

test/performance/matrix_multiplication.cpp

Takes it from 368 Gflops to 1140 Gflops on my workstation. That second number is quite noisy because I have multiple sockets and we don't do anything special in the thread pool to pin threads to cores/sockets. Doing that gives you a boost on microbenchmarks where the same thread keeps processing the same data, but isn't really meaningful in most applications where there's no strong coupling between thread id and what's likely to be in-cache.
One important caveat: I found that this workload works best without hyperthreading, so I set HL_NUM_THREADS to be my number of physical cpu cores, not the number of logical cores.
Generated inner loop:
```
vbroadcastss	-4(%r11,%r13), %ymm15
vmovups	-64(%r12,%rcx), %ymm14
vmovups	-32(%r12,%rcx), %ymm13
vmovups	(%r12,%rcx), %ymm0
vfmadd231ps	%ymm15, …
```

Reschedule test/performance/matrix_multiplication

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/ThroughputPredictorPipeline.h
apps/autoscheduler/train_cost_model.cpp

(Note that buffer_from_file() in TPP.h is commented out, as some of the weights/ files are the wrong size. Not sure of the right fix there; we should uncomment once the file is fixed.)

Add error checking for the ifstream / ofstream calls in autoscheduler

---

python_bindings/Makefile

to ensure that $CXXFLAGS are respected when compiling the Python bindings

add $CXXFLAGS to $CCFLAGS in Python bindings

---

apps/autoscheduler/train_cost_model.cpp

creating a std::string from a NULL ptr tends to be crashy

Don't crash when env vars aren't set

---

util/HalideTraceViz.cpp

HalideTraceViz makes really trippy 80's style visualizations on windows.
This is due to windows by default treating stdin/out as text files, switching them to binary fixes the issue.

Fix HalideTraceViz on windows.

---

Makefile
apps/support/Makefile.inc
halide.cmake
src/CodeGen_C.cpp
tools/RunGen.h
tools/RunGenMain.cpp
tools/RunGenStubs.cpp

Expand to allow for multiple filters to link against RunGen at once, selecting via a flag; this is of limited use for routine purposes, but should give us greater flexibility when experimenting with multiple auto-scheduler models.

Rework RunGen registration model

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/CostModel.h
apps/autoscheduler/DefaultCostModel.cpp
apps/autoscheduler/augment_sample.cpp
apps/autoscheduler/train_cost_model.cpp

- augment_sample: don't crash if file can't be opened for writing
- train_cost_model: quietly ignore empty inputs
- various: allow for optionally having a different directory for saving updated weights via the HL_WEIGHTS_OUT_DIR. (If omitted, assume out = in as is current).

Various minor fixes

---

apps/autoscheduler/Featurization.h

constexpr var declarations are a C++14 feature; a compiler constrainted to C++11 only will complain.

Remove C++14 features

---

README.md

Additional cleanups:
* added a top-level heading for the project name to make it stand out in
the README
* fixed capitalization when referring to project names rather than their
binary or directory names
* replaced / (forward slash) with \ (backward slash) for sample Windows
paths, and put them in code formatting as well
* removed escaping of underscores since code formatting avoids Markdown
interpretation

Add code formatting and other cleanups. [skip ci]

---

src/CodeGen_LLVM.cpp

Any Expr that can be constant-folded should be at that point.
cc @ongjunjie

CodeGen_LLVM::embed_constant_expr should simplify non-const exprs (Issue #3538)

---

apps/support/Makefile.inc

Augment default CXXFLAGS in apps/Makefile.inc to match those in the main Makefile, cleaning errors as needed.

Augment warning/error flags for apps/

---

apps/autoscheduler/autotune_loop.sh
apps/bilateral_grid/Makefile
apps/camera_pipe/Makefile
apps/conv_layer/Makefile
apps/interpolate_generator/Makefile
apps/interpolate_generator/interpolate_generator.cpp
apps/lens_blur/Makefile
apps/local_laplacian/Makefile
apps/mat_mul_generator/Makefile
apps/max_filter/Makefile
apps/nl_means/Makefile
apps/stencil_chain/Makefile
apps/unsharp/Makefile

NOTE: several of these reliably fail to compile within the 120-second timeout that is set by default, at least on my local machines:
- ~~interpolate_generator~~
- lens_blur
- local_laplacian
- ~~max_filter~~
- ~~stencil_chain~~
(However, those two local machines are a 12-core Linux box and a 4-core Macbook, so trying to build 32 at the same time is probably not helping. I may follow up with some tweakage to the autotune_loop.sh script to modify the number of parallel builds based on number of cores.)
UPDATE: with the tweaks just mentioned in place, now only two of them reliably time out for me; these are more complex pipelines so it might just be unavoidable for now.
I'm going to leave them in anyway (caveat emptor!) as they may be useful in helping profile speed issues in the …

Add autotune targets to other apps/ that can use it

---

src/runtime/errors.cpp

constrained_max appears to be calculated incorrectly. also, drive-by fix to emit the dimension with the error message,

halide_error_constraints_make_required_region_smaller appears to be wrong

---

src/Generator.cpp
src/Generator.h
src/Util.cpp
src/Util.h

The PR makes the function/variable names look consistent during the compilation for different targets when using the multi-target AOT flow. It is for improving the debugging experience.

Reset unique name counters before the compilation of each target.

---

src/CodeGen_Posix.cpp

We are leaking memory in some corner cases with store_in(MemoryType::Stack)

Fix a memory leak with conditional pseudostack slots

---

src/Bounds.cpp

For unsigned int multiplies in the uint16 range, we would do the overflow checking with signed integers, thus (incorrectly) assuming the bounds were neg-inf and pos-inf; changing to use unsigned math for this check allows us to correctly infer the finite bounds.

Improve Bounds calc for uint16 Mul

---

apps/resnet_50/Makefile
apps/resnet_50/Resnet50BlockGenerator.cpp
apps/resnet_50/process.cpp

Note that (unlike most other apps) this doesn't attempt to run all three in the same run; it selects one of the options via command-line flag. 'make test' runs all three in sequence.
Note also that the 'manual' schedule is known to be awful (it's just enough compute-roots added to make the runtime tractable); improvement is left as an exercise to the reader.

Add classic auto-schedule testing to apps/resnet

---

apps/autoscheduler/autotune_classic.sh
apps/bilateral_grid/Makefile
apps/camera_pipe/Makefile
apps/conv_layer/Makefile
apps/fit_and_slice_3x4/Makefile
apps/harris/Makefile
apps/hist/Makefile
apps/iir_blur_generator/Makefile
apps/interpolate_generator/Makefile
apps/lens_blur/Makefile
apps/local_laplacian/Makefile
apps/mat_mul_generator/Makefile
apps/max_filter/Makefile
apps/nl_means/Makefile
apps/stencil_chain/Makefile
apps/support/autoscheduler.inc
apps/support/benchmark_util.h
apps/unsharp/Makefile

This is a trivial script to try running 'classic' autoscheduler
with the multiple variants of MachineParams used in the original paper;
all it does is disable benchmarking of non-classic variants, and run 'make test'
in the current directory repeatedly with different values (removing
any classic artifacts from bin to ensure a rebuild occurs).

Add autotune_classic.sh and support

---

src/CodeGen_LLVM.cpp
src/LLVM_Headers.h

Reverts halide/Halide#3564; apparently the underlying LLVM change was reverted or made moot.

Revert "Update for trunk LLVM"

---

python_bindings/correctness/buffer.py
python_bindings/src/PyBuffer.cpp

Some versions of NumPy can pass 'l' (aka long) for int64 types; pybind11 doesn't handle this as an option, so add a special case to handle it.

Handle NumPy's 'l' format in PyBuffer

---

src/Bounds.cpp
src/Simplify_Call.cpp
test/correctness/fuzz_simplify.cpp

Formerly this defaulted to bounds-of-type, but that meant that widened expressions never attempted to use the known bounds of the narrow types (e.g. absd(i16(a), i16(b)) would assume [0,65535] even if a and b are known to be i8)
Also, drive-by addition of some debugging infrastructure for Bounds, disabled by default (ala EXPR_MUTATIONS in Simplify)

Add handling of absd() in Bounds.cpp

---

src/JITModule.cpp
src/LLVM_Headers.h
src/LLVM_Output.cpp

Print out LLVM passes timing statistics results when passing -time-passes to HL_LLVM_ARGS. If -time-passes isn't passed to cl::ParseCommandLineOptions this is no-op.

Print llvm -time-passes statstics when JIT or AOT compile an LLVM module

---

src/IROperator.h

These are known to produce trivially different results on different implementations of the same architecture (eg AMD vs Intel), even when strict_float is used, and should be documented as such.

Document fast_inverse and fast_inverse_sqrt variation

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

Moving buffer asserts into switch statements  blocks seems significantly speed up register allocation and coalescing. This reduces compile opt-pass time for resnet50 (autoschedule_with_convnets branch) from 268.5848 sec to 15 sec. 
$ run_performance_lots_of_inputs 
Before:
```
Compile time with 1 inputs = 0.534758 s
Compile time with 2 inputs = 0.078090 s
Compile time with 4 inputs = 0.113272 s                                                                            
Compile time with 8 inputs = 0.194721 s                                                                           
Compile time with 16 inputs = 0.401624 s                                                                             
Compile time with 32 inputs = 0.940241 s …
```

Block asserts into switch statements 

---

tools/RunGen.h

When --default_input was added, the ability to infer the output shape from the first input was lost; this is useful for many uses. Also fix rogue space.

Fix glitch in RunGen

---

src/Bounds.cpp

This is broken, I shouldn't have approved it:
- shift_right went missing entirely
- bitwise_xor is treated as shift_left
- shift_left has a special case intended for shift_right
Rather than trying to spot-fix, let's back it out entirely and fix it properly (with tests) later.

Revert "Bounds of bitwise ops"

---

src/runtime/hexagon_host.cpp

When the debug target flag is set, write the shared objects loaded by Hexagon to the current directory.
Not sure I really like this PR, but it is useful for some Hexagon profiling/debugging tools, and this is a lower impact approach than past PRs aimed at accomplishing this task.

Dump Hexagon shared objects in debug builds

---

src/Inline.cpp

For reasons that aren't yet clear, this change causes some pipelines inside Google to explode in compiletime (so much so that they timeout and never complete). Would like to revert and re-examine the change in more detail before re-landing.

Partial revert of #3612

---

src/Simplify_Call.cpp
test/correctness/simplify.cpp

- only float32 was handled
- return type for constants was int but should be bool

Fix simplification of Halide::is_nan (Issue #3624)

---

src/Simplify_Div.cpp
test/correctness/simplify.cpp

There's a path in Simplify(Div) that checks for collapsing a bounded numerator by a constant(ish) denominator, and if the result has a single-point boundary, returns that as the constant value; however, it doesn't verify that the constant value actually fits into the result type, so you can get int64 values that are simply truncated to int32 results. This PR proposes to check for this and return signed_integer_overflow() in these cases.
I'm actually a little unsure as to whether this is the right thing or not: on the one hand, this path only occurs for `no_overflow_int` types, so it's arguable that the existing behavior is just fine; that said, I'd argue that if we can trivially detect and prove that an overflow will always occur, we're better off indicating it clearly rather than …

Improve failure mode for Simplify(Div)

---

Makefile
src/Module.cpp
src/runtime/HalideRuntime.h
test/generator/registration_test.cpp
test/generator/rungen_test.cpp
tools/RunGenMain.cpp

This extends the registration mechanism for AOT-Generators to allow for a build system to add arbitrary additional text as part of the `halide_register_argv_and_metadata` call.

Extend registration mechanism to be extensible

---

src/Bounds.cpp

The boundaries didn't take into account the differing behavior of signed values, so the constant bounds signed ints was wildly wrong in some cases (eg int16 >> int16 -> [-1, 0])

Bounds for shift_right with signed-ints was incorrect

---

src/Bounds.cpp
src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/IROperator.h
src/Simplify_Call.cpp
test/correctness/popc_clz_ctz_bounds.cpp
test/correctness/simplify.cpp

- Add special-casing of these to the Simplifier, so that constant values are simplified to constants
- Improve handling of bounds-calculation for clz to allow narrower min and max when the intervals are bounded

Improve handling of clz, ctz, popcount

---

src/Lower.cpp

Only apply canonicalize_gpu_vars pass for GPU targets

Skip canonicalize_gpu_vars for non-gpu targets

---

src/runtime/cuda.cpp

I encountered segfault when calling a Halide cuda function from two threads. This is caused by `halide_cuda_initialize_kernels`, which calls the ctor of `Context`, which calls `load_libcuda` if `cuInit` is NULL. However if `Context::Context` is invoked from two threads, one thread may have resolved `cuInit` but not yet `cuCtxPushCurrent`, and another thread might skip calling `load_libcuda` because it finds `cuInit` to be non-null, and segfault follows when it calls uninitialized `cuCtxPushCurrent`.
This PR fixes this problem by adding a helper `ensure_libcuda_init`, which guards `load_libcuda` call by a spinlock.

Fix race conditions during CUDA runtime initialization

---

src/Bounds.cpp
src/Simplify_Call.cpp
test/correctness/simplify.cpp

Formerly we tried to handle negative shifts by flipping the operation, and out-of-range shifts by clipping to zero or -1. This isn't necessarily *wrong* -- these are UB in C++ (and poison-producing in LLVM) -- but I'd argue that if we can statically detect UB/poison values, we're better off producing a hard error at compile time.
See also https://github.com/halide/Halide/issues/3325

Revise Simplify for << and >> to forbid out-of-range constant shifts

---

src/Expr.h
src/Func.cpp
src/IR.h
src/Inline.cpp
src/Profiling.cpp
src/Schedule.h
src/ScheduleFunctions.cpp

This PR does a small cleanup of code that checks if a loop is parallel:
- Adds `is_unordered_parallel` and `is_parallel` helper functions
- Renames existing `is_parallel` helper functions on `For` and `Dim` and adds `is_unordered_parallel`
- Possible small bug fix in ScheduleFunctions.cpp, was this check missing `ForType::GPULane`? @abadams

Refactor is_parallel helper functions

---

src/Generator.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h

Currently, generators support compiling Halide functions for multiple platform-compatible targets and automatically selecting the "best" one (in order) via runtime checks.
This PR extends a compatible behavior to the generator's runtime generation (via `-r`). Scripts that compile multiple functions into a single static library can now pass a comma-separated list of all the function targets to the generator and a "greatest common denominator" runtime will be selected.
This is a **draft** as there are certain target features that I'm not familiar with. I'm asking for some help deciding whether a GCD target should include a feature if _either_ source target has it (eg. `cuda`), only if _both_ have it (eg. `avx2`), or if it should be dropped (eg. `no_runtime`). The behavior does not change …

Let generators compute a GCD target when multiple targets are passed to `-r`

---

src/Generator.cpp
src/runtime/windows_get_symbol.cpp
tutorial/lesson_12_using_the_gpu.cpp

Addressing issue #3682, fixes the call to `LoadLibrary` to always use `LoadLibraryW` by converting UTF-8 to UTF-16 manually before call.

Fix LoadLibrary call to use UTF-8 instead of ANSI.

---

src/HexagonOffload.cpp
src/Util.cpp
src/Util.h

Simple utility functions to slurp / spew the entire contents of a file; not much re-use in this PR but I'll need them elsewhere in the future, so this is intended to reduce future PR noise.

Add read_entire() and write_entire()

---

apps/camera_pipe/camera_pipe_generator.cpp
src/Target.cpp

We actually decided in https://github.com/halide/Halide/pull/3211 to just forbid switch fallthru in Halide; rewrote the recently injected usage to avoid.
Also, drive-by spelling fix.

Remove switch-fallthru usage in Target.cpp

---

src/Module.h
src/Target.cpp
src/runtime/HalideRuntime.h

This PR removes the explicit target feature numbers from the `halide_target_feature_t` enum:
- This ordering is well defined by the C/C++ standard (even without the first zero defined enum value).
- I don't think we support binary compatibility of this compiled code across compiler versions, so inserting/removing enum values shouldn't be an issue.
- Any edits to these features requires either painful renumbering, or 'last added' sorting, both of which are annoying.

Remove explicit target feature numbering

---

README.md

Reverts halide/Halide#3696. This change makes Target::to_string weird. It's probably not worth trying to rename the HVX_128 target feature.

Revert "Also fix README.md for deprecated HVX flags"

---

test/correctness/memoize.cpp

It emits things to stderr that aren't errors, which can confuse the quiet output.

Minor: correctness_memoize is noisy

---

src/Lower.cpp

This fixes cases where an allocation are falsely reported as heap allocations, because small dynamic allocations become stack allocations after `bound_small_allocations`.

Move inject_profiling after bound_small_allocations

---

Makefile

I decided to simply add more entries specific to 7.1, instead of fooling around with make's `findstring` and other text manipulation routines.

fixed Makefile build for the latest LLVM/clang release (7.1)

---

Makefile
src/Generator.cpp
test/CMakeLists.txt
test/generator/metadata_tester_aottest.cpp
test/generator/metadata_tester_generator.cpp

Note that this should allow for Input<Buffer<float16>> and Output<Buffer<float16>>, but *not* Input<float16> or Output<float16>; those require a bit more work (see PR #3711)

Support Buffer<float16> in Generators (Issue #3709)

---

src/LLVM_Runtime_Linker.cpp
src/LLVM_Runtime_Linker.h

Pre-emptive refactoring to make subsequent PR smaller, this pulls some logic from link_modules() into its own function, and adds handling for ExternalWeakLinkage.

Refactor: Add convert_weak_to_strong()

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

Minor hygiene; this is the cleaner C++11 way to do this sort of thing.

Use std::call_once to init LLVM

---

src/CMakeLists.txt

(I would expose the flag to all targets, but that might saturate the build since multiple projects might get built in parallel; Halide itself is a knot point of the build, so compiling multiple files in parallel will not oversubscribe the system)

added parallel build toggle for Halide when cmake generate its Visual Studio project

---

src/Func.cpp
src/Func.h
src/JITModule.cpp
src/JITModule.h
src/Pipeline.cpp
src/Pipeline.h
src/Target.h
src/Type.h
src/runtime/fake_thread_pool.cpp
test/correctness/parallel_fork.cpp
test/correctness/simd_op_check.cpp
test/error/broken_promise.cpp

These are cleanups/refactors from the wasm branch that are relatively incidental; proposing to land them in master to reduce deltas from that branch:
- compile_jit() returns void rather than a void* (since not all JITs can easily return a real fn ptr here)
- add_extern_for_export() returns the Symbol it added
- JITCallArgs use new[] / delete[]
- replaced a stray std::cerr with debug(0)
- whitespace nits
- spelling nits
- fake_thread_pool only accepts setting num_threads to exactly 1
- add Type::is_int_or_uint()
- error_broken_promise should use get_jit_target_from_environment() instead of "host"
- simd_op_check logs the host and HL_TARGET values at the start (for ease of tracking down issues later on if failures occur)

Grab Bag of minor changes

---

test/correctness/simd_op_check.cpp

If the error-check fails, dump the assembly of the error function (which also contains the vector and scalar functions); hopefully this will give some insight to the intermittent failures that we've been seeing on the buildbots here

Add error diagnositcs to simd_op_check

---

test/correctness/simd_op_check.cpp

Got simd_op_check working for skylake. Other avx512 variants make other instruction selection decisions.

Fix simd op check for avx512 skylake

---

src/runtime/tracing.cpp

Using malloc to allocate space for the TraceBuffer object doesn't call the constructor so
the member variables (including the shared spinlock) may not be initialised to zero.
It seems that new isn't allowed in the runtime so I've added some init methods to fix this.

Fix broken trace code.

---

src/HexagonOptimize.cpp

1. Need to substitute let exprs for scatter_acc matching.
2. Pointer cast for buffer addresses for scatter-gathers.
@dsharletg @pranavb-ca @dpalermo Please review.

Changes for scatter-gather instructions on Hexagon

---

.travis.yml

- Upgrade Trusty -> Xenial (14.04 -> 16.04)
- Add LLVM8 to test matrix
- Use the Travis+Xenial default of gcc5.4 instead of gcc4.8 (which we no longer build or test with anywhere else)

Upgrade of Travis, v2

---

src/Target.cpp

We emit user_warnings when returning false, which generates useless and confusing warnings from test_internal. Convert to debug(1) output; the caller should be checking the result in any event.

Silence warnings in Target::get_runtime_compatible_target()

---

src/Simplify_Div.cpp

If the div operation produces unbounded results, we can leave the bounds set with values of INT64_MAX or INT64_MIN; code downstream (eg Simplify_Add) can use these values in way that will cause overflow, and even though the resulting values are (apparently) never used, this triggers failures in UBSAN/ASAN builds. Neuter to zero for cleanliness.

Avoid possible UB in Simplify_Div

---

src/Monotonic.cpp
test/correctness/require.cpp

require() Exprs can legitimately have these. Add a test case that would catch it.

is_monotonic() should not fail for Exprs with strings

---

src/Simplify_Max.cpp
src/Simplify_Min.cpp
test/correctness/simplify.cpp

- min(min(x,y)+c,x) -> min(x, y+c) [iff c > 0]
- max(max(x,y)-c,x) -> max(x, y-c) [iff c > 0]
This eliminates some very long nested min() expressions seen in https://github.com/halide/Halide/issues/3755.

Add some min/max simplifier rules

---

src/CodeGen_C.cpp

The Cpp Vector support in Codegen_C didn't implement operator|| or operator&&. Now it does.

Add logical operators to Cpp Vectors

---

src/Simplify_And.cpp
src/Simplify_Or.cpp
test/correctness/simplify.cpp

Spotted some dumb code in vectorized if conditions of the form `(x < y && x < y + 1 && x < y + 2 ...)`
I believe Dillon has complained about this in the past. Here are some new simplifier rules to clean it up a little.

Simplify boolean combinations of inequalities using min/max

---

src/Simplify_Cast.cpp
src/Simplify_Div.cpp
test/correctness/simplify.cpp

Fixes #3764 in two ways
- Adds a missing critical point to be considered in the simplify_div bounds logic (the limit as the denominator goes to +/- infinity is zero, provided the denominator is known to be positive or negative). 
- But the denominator shouldn't have been unbounded on one side, because it was the result of constant folding. Fix this by tracking bounds through casts of constants.

Add missing critical point in Simplify_Div

---

src/Bounds.cpp

Spotted a fishy-looking early-out in the bounds of a select node. Adding a test revealed that it was in fact wrong.
As a drive-by cleanup, I also uniformly used ConciseCasts in the built-in test instead of a mix of ConciseCasts and make_const.

Fix incorrect early-out in bounds of select

---

src/CodeGen_C.cpp

Broadcast, Cast, Ramp and some Calls can synthesize types that aren't in the struct; we have to handle these to get the right C++ types predeclared

Codegen_C: TypeInfoGatherer needs a few special cases

---

src/runtime/posix_error_handler.cpp

This bug caused Halide to swallow error messages. (And, for very long error messages, crash, instead of aborting.)

Fix bug in posix_error_handler.

---

src/Simplify_Select.cpp
test/correctness/simplify.cpp

Basically, pull divide or mod with the same denominator outside of the select:
- select(a, b/d, c/d) -> select(a, b, c)/d
- select(a, b%d, c%d) -> select(a, b, c)%d

Add new simplifier rules for select()

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

Currently, all of our LLVM backends generate position-independent code (llvm::Reloc::PIC_); the WebAssembly backend will need to be able to generate Static code in at least some situations, so this PR adds a way to accomplish that. (Adding here rather than in the webassembly branch to simplify downstream diffs.)
Note: I'm not wild about the 'disable_pic' nomenclature, but having one of our virtual methods return an LLVM enum value felt weird (might complicate includes), and having the default value be 'false' (to mirror use_soft_float_abi) seemed right. Open for better suggestions, of course.

Add option to disable PIC codegen

---

src/StorageFolding.cpp

This was a merge from the autoscheduler branch, but it's not safe: there can be duplicate lets in the Expr, and CSE is known to be unsafe on such Exprs. Backing out this change to unbreak downstream users.

Don't call cse() in AttemptStorageFoldingOfFunction

---

src/CodeGen_C.cpp

When using the 'native vector' types in GCC/Clang, the sizeof(type) may be larger than what we actually requested (eg 48->64); ensure we use only the logical size when memcpy'ing.

Avoid overreads/writes in Codegen_C

---

Makefile

Cleaning up a very minor annoyance in the makefile. Running make in the root dir is not enough to get the apps to compile, you need to do "make distrib". This is silly, because the default target builds almost everything necessary for make distrib anyway.

add distrib to default make target

---

src/Interval.cpp
src/Interval.h
test/correctness/interval.cpp
test/internal.cpp

There was no reason for the test to be inside the compiler (didn't depend on things internal to the file), and the existing logic could more readably be expressed using a rewriter. It is after all an eager simplifier pass, so it should look the same.

Simplify Interval.cpp

---

CMakeLists.txt
test/CMakeLists.txt
tutorial/CMakeLists.txt

This is enough to use most CTest features and makes it easy
to parallelise tests or run only select tests.
A couple of examples:
```
cd build
ctest -N
ctest -j4 -R 'reduction'
```
Signed-off-by: Kévin Petit <kpet@free.fr>

Add basic CTest support

---

src/IRMatch.h

some of the int64 constant-fold ops warn about possible signed-integer-overflow when run under UBSAN; disable the check for these.

Disable UBSAN signed-integer-overflow warnings

---

src/CodeGen_Hexagon.cpp
src/CodeGen_Hexagon.h

We believe this is no longer necessary for recent LLVM builds. https://github.com/halide/Halide/issues/3739

Remove -hexagon-small-data-threshold=0 hack (Issue #3739)

---

src/CodeGen_LLVM.cpp

From @alinas, this can reduce compile time for some complex schedules substantially. Requires LLVM9 >= r358304.
Background: Certain Halide applications spend a very long time compiling in forgetLoop, and prefer to forget everything and rebuild SCEV (aka "Scalar Evolution") from scratch. Sample difference in compile time reduction: 21.04 to 14.78 using current ToT release build.
See also https://reviews.llvm.org/rL358304

Add LLVM SCEV option

---

python_bindings/correctness/rdom.py
python_bindings/src/PyRDom.cpp

operator[] of RDom is missing in the Python binding and I found it useful to have it.

Add operator[] to RDom in the Python binding

---

test/correctness/tracing.cpp

The local name "trace" can apparently conflict with a symbol ncurses. Wrap everything in an anonymous namespace to avoid (which is a good practice anyway).

Avoid link error in correctness_tracing

---

python_bindings/correctness/rdom.py
python_bindings/src/PyRDom.cpp

Reverts halide/Halide#3816
This has broken test_tutorial_lesson_13_tuples in the Python tests; we didn't notice it because the PR wasn't cloned and run with full tests.
(The nature of the fix required is not obvious to me, so I'm proposing to revert this to unbreak the tests; I encourage it to be re-added, but only after it's clear that `make test_python` is properly passing.)

Revert "Add operator[] to RDom in the Python binding"

---

python_bindings/src/PyVar.cpp
src/Func.cpp
src/Func.h
src/Var.h

This makes the implicit var pieces of syntax (_*) stateless static constexpr things, instead of extern object instances. Should avoid the problems associated with exposing variables in a public API.
Alternative to #3807

Give the implicit vars unique types instead of state that needs to be initialized

---

src/JITModule.cpp
src/JITModule.h

We build and save the llvm FunctionType for each Symbol, but never actually use that type information anywhere. Stop doing that.

JITModule::Symbol doesn't need llvm_type

---

src/Simplify_Shuffle.cpp
test/correctness/simplify.cpp

I think this fixes #3842. I'm not completely sure I understand this, it's just mirroring the logic in the simplifier's Load visitor.

Fix alignment of shuffled loads.

---

src/runtime/hexagon_remote/Makefile
src/runtime/hexagon_remote/dlib.cpp
src/runtime/hexagon_remote/halide_remote.cpp
src/runtime/hexagon_remote/known_symbols.cpp
src/runtime/hexagon_remote/pipeline_context.h
src/runtime/hexagon_remote/sim_host.cpp
src/runtime/hexagon_remote/sim_qurt_vtcm.cpp
src/runtime/hexagon_remote/sim_remote.cpp

Various things to make using this more flexible:
- HEXAGON_TOOLS_ROOT should be relative to HEXAGON_SDK_ROOT by default
- Fix includes that erroneously used #include<> instead of #include""
- Don't rely on halide_hexagon_remote.h being put in a specific place; instead, add to the include path
- use hexagon-ar instead of plain ar
- encapsulate the output dir into the BIN var so we can relocate it if necessary
- Add some missing deps
- Remove some commented-out stuff
- Remove some unnecessary includes

Clean up hexagon_runtime build env

---

src/CodeGen_Internal.cpp

This causes llvm to put ctors into the `.init_array` section when possible (rather than the .ctors` section.
This can dramatically improve performance for some targets (esp aarch64) when the `lld` linker is used: older linkers (eg, gold) tend to do legacy conversion of .ctors to .init_array, but lld does not.
(It's not clear to me why we default this to false -- historical reasons? mistake? ignorance? -- or if there are any downsides to making this change.)

Set llvm::TargetOptions::UseInitArray = true

---

Makefile

ld as of version 2.32 no longer prints the members of an archive with a single `-t` flag. Now it must be passed twice. In addition, the new output format precedes lines of the form `(archive)object` with the archive on a single line regardless of whether any objects therein were used. This PR adjusts the command in the Makefile to adapt to this by passing the second `-t` flag (which will be redundant on earlier versions) and dropping lines that lack a closing parenthesis (of which there are none on earlier versions).
Thanks to @alexreinking for figuring this out.

updating makefile to process newer ld trace output

---

src/CodeGen_ARM.cpp
src/CodeGen_ARM.h
test/correctness/simd_op_check.cpp

Currently, very little code except for *exact* matches to https://github.com/earl/llvm-mirror/blob/master/test/CodeGen/AArch64/aarch64-smull.ll are generating mlal instructions. This PR makes LLVM more able to generate mlal by emulating Clang's arm_neon.h.

Improve mlal codegen

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_X86.cpp
src/FastIntegerDivide.cpp
src/IROperator.cpp
src/IROperator.h
test/correctness/bitwise_ops.cpp
test/correctness/print.cpp

Our current type coercion for bitwise ops has a number of issues. It does not handle matching the number of lanes when a scalar and vector are paired and it is not commutative in terms of type width. It also did not handle mixture of signed and unsigned types well, possibly in ways that could result in errors constructing LLVM bitcode.
This PR fixes the above issues by making the operators require arguments that match in signed/unsigned sense, though constants will be made to match non-constant expressions so ```a & 127``` will get the type of ```a``` even though it may be unsigned and 127 would normally be an ```int``` or signed. Scalars are broadcasted to match a vector argument if needed. Logic for expanding bit width chooses the larger width.
Some fixes were required in the compiler …

Bitwise ops type consistency.

---

python_bindings/correctness/buffer.py
python_bindings/src/PyBuffer.cpp

Add check for ssize_t -> int32_t overflow. Add the corresponding test  to correctness/buffer.py.

Add check for the overflow in Python bindings

---

src/LowerWarpShuffles.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
test/correctness/simplify.cpp

apps/cuda_mat_mul wasn't working. The main cause is a bug in variable handling in warp shuffle lowering, but it also needs some new simplifier rules for things to work out in a way it can analyze. Lower warp shuffles is unfortunately a brittle pass.

Fix cuda mat mul

---

Makefile
README_webassembly.md

Formerly, a config file had to be edited correctly, or bad things happened. Now we set it correctly automatically.

Simplify Emscripten config requirements for wasm branch

---

src/Bounds.cpp
src/CodeGen_LLVM.cpp
src/HexagonOptimize.cpp
src/IROperator.h
src/Simplify_Call.cpp
src/Simplify_EQ.cpp
test/auto_schedule/max_filter.cpp
test/correctness/bitwise_ops.cpp
test/correctness/left_shift_negative.cpp

Per discussion with Dillon, this PR changes Halide to require shift amounts to be of unsigned type. The idea we'll added negative shifts in with defined behavior to reverse the direction of the shift.

Shift amount type change

---

src/CodeGen_OpenCL_Dev.cpp
src/IROperator.h

This makes debugging violations a bit easier.

Add types to left-shift and right-shift assertions

---

Makefile

Older versions of egrep treat ")" as
having special meaning and the change in
PR #3850 results in Halide build failure.
(Observed in Ubuntu 14.04, GNU grep 2.16)
Replacing egrep with grep as extended
regular expression is not required here.

Support older versions of grep

---

apps/linear_algebra/src/CMakeLists.txt

resolves #2742
generator args were being ignored.
fix uses unparsed args to pass on `GENERATOR_ARGS` to `halide_library_from_generator`

fix add_halide_blas_library cmake

---

Makefile
README_rungen.md
apps/bilateral_grid/bilateral_grid_generator.cpp
apps/camera_pipe/camera_pipe_generator.cpp
apps/lens_blur/lens_blur_generator.cpp
apps/local_laplacian/local_laplacian_generator.cpp
apps/nl_means/nl_means_generator.cpp
apps/stencil_chain/stencil_chain_generator.cpp
apps/support/Makefile.inc
tools/RunGen.h
tools/RunGenMain.cpp

Adds benchmarking to several of the apps, using RunGen's benchmarking capability:
- Some drive-by fixes to RunGen's code and README, which have bitrotted from underuse
- Add new output format for the benchmarks (via --parsable_output) to make output simpler to machine-parse (rather than relying on the human-readable output remaining unchanged forever)
- Ensured that all the Generators being benchmarked had proper estimates or defaults filled in, so we could use those values
- Drive-by fix to put the output of `make test_apps` into the correct build subtree when building out-of-tree

Add `make benchmarks` target

---

src/ModulusRemainder.cpp

Remainders can in fact be negative if the modulus is zero.

Fix UB in ModulusRemainder

---

apps/bilateral_grid/Makefile
apps/camera_pipe/Makefile
apps/conv_layer/Makefile
apps/cuda_mat_mul/Makefile
apps/hexagon_benchmarks/Makefile
apps/hexagon_dma/Makefile
apps/lens_blur/Makefile
apps/linear_algebra/Makefile
apps/local_laplacian/Makefile
apps/nl_means/Makefile
apps/nn_ops/Makefile
apps/onnx/Makefile
apps/resnet_50/Makefile
apps/simd_op_check/Makefile
apps/stencil_chain/Makefile
apps/support/Makefile.inc
apps/support/autoscheduler.inc

Follow the pattern of the base Makefile by:
- specifying OPTIMIZE ?= -O3
- adding that to the CXXFLAGS
- removing -O3 where CXXFLAGS is present
This allows an easy way to disable opt and/or add debug symbols for debugging the apps (just add OPTIMIZE=-g)

Add OPTIMIZE for apps/ makefiles

---

tools/halide_benchmark.h

The Emscripten implementation of std::chrono::steady_clock() and friends is broken. Use a recommended Emscripten-specific hack instead.

Fix halide_benchmark.h for Emscripten

---

Makefile

- Remove the SpiderMonkey stub definitions; they aren't in use and aren't likely to be any time soon, so it's just bitrot waiting to happen (we can restore them when we need them)
- add missing V8 deps for libHalide rules
- remove not-used-anywhere LIBHALIDE_DEPS

Makefile cleanups for V8

---

src/CodeGen_C.cpp

It returns void, which conflicts with its declared IR. (We encountered this recently with msan helpers, and fixed those by making the msan functions actually return int... but as halide_print() is overridden many times downstream, including in third-party Halide users, it's arguably cleaner to just special-case it for the C++ backend.)

Allow halide_print usage from the C++ backend

---

src/CodeGen_C.cpp

The code we generate is SSA so all declarations should (conceptually) be const; this is an experiment to see if this matters to codegen quality at all. (I would hope not, but it wouldn't be the first time a compiler has surprised me.)

Add 'const' to C++ backend var decls

---

Makefile
README_webassembly.md
apps/blur/Makefile
apps/support/Makefile.inc
tools/halide_benchmark.h

Added rules to apps/Makefile.inc to provide `benchmark_wasm` targets; the toplevel `make benchmark_apps` now knows how to sniff `HL_TARGET` and run these appropriately.

Augment apps benchmarking rules to work with wasm

---

src/Parameter.cpp
test/correctness/exception.cpp

The exceptions test had rotted because we don't have any buildbots with WITH_EXCEPTIONS on.
1) CodeGen_LLVM assumes that the min and max values for parameters are constants (they get embedded in metadata), but this was not checked, resulting in an internal error instead of a user error
2) Realizing into a too-small image is soon to be not-an-error
3) Realizing into an unbound image param is now caught as a runtime error (passing null as a buffer_t arg)

Fix exceptions test

---

Makefile

Not sure why your builds are passing but I think those changes are really needed to fix msys2/mingw windows paths.
They are copy pasted from few lines above where llvm-config is called.
Blaming this line seems that it's a relatively recent merge from wasm changes.
Cheers!

Add required sed to process msys2/mingw windows path slashes

---

test/correctness/image_io.cpp
tools/halide_image_io.h

The current Tools::save_image() function has a bug when writing .mat files, when the array's size does not end at 64-bit boundary and requires padding. It does not take the padding bytes into consideration when computing file size, causing Matlab to fail the read the file (the round trip test in Halide is working fine since we ignore the file size). This patch fixes this and adds a test to check the file size.

Take padding bytes into consideration when writing .mat files

---

Makefile
src/runtime/HalideBuffer.h

Get rungen binary size down to 1MB by optimizing for size, and moving some templated code in Runtime::Buffer into non-templated helper methods.

Rungen binary size

---

apps/support/Makefile.inc

(0) Our main Makefile already defines this, so we already rely on bash
(1) The SHELL var isn't inherited by sub-makefiles
(2) apps/Makefile.inc relies on bash (vs plain sh) syntax
(3) Some of our buildbots don't define SHELL

Explicitly set SHELL=bash in Makefile.inc

---

Makefile
README.md
test/opengl/vagrant/README.md
test/scripts/build_travis.sh

For ~ever, we've required Makefile users to define CLANG as well as LLVM_CONFIG as env vars; in practice, CLANG should always point to the the one that could be deduced by LLVM_CONFIG. This changes the CLANG default value to that one (instead of 'system clang') and removes the recommendation that it be set. (You can still override CLANG if you really want to.)
If this is accepted, the buildbots will be subsequently updated to stop setting CLANG.
Note that I skipped tests/opengl/vagrant since it seems to be deliberately using ancient LLVM versions that we don't support anyway -- is it stale?
(Note that the CMake build rules were already doing it this way)

define CLANG relative to LLVM_CONFIG

---

apps/auto_viz/Makefile
apps/bilateral_grid/Makefile
apps/blur/Makefile
apps/c_backend/Makefile
apps/camera_pipe/Makefile
apps/conv_layer/Makefile
apps/cuda_mat_mul/Makefile
apps/fft/Makefile
apps/glsl/Makefile
apps/lens_blur/Makefile
apps/local_laplacian/Makefile
apps/nl_means/Makefile
apps/stencil_chain/Makefile
apps/support/Makefile.inc

This gives a convenient bottleneck to customize the Generator output for (most) of the apps/ built via Makefiles; default to also generating .stmt and .s files, so that people examining apps/ output for benchmarking, learning, etc can see this output without having to do surgery in the Makefile.
(Note that some of the apps/ with Makefiles that are already heavily custom, e.g. the hexagon benchmarks, weren't touched by this. It would be nice to regularlize all the apps build files at some point in the future.)

Add GENERATOR_OUTPUTS var to apps/ Makefiles

---

src/CodeGen_OpenCL_Dev.cpp

There seems to be an extra print_expr in OpenCL backend when processing Store. This patch removes that line. Sorry if the extra print is intentional.

Remove extra instruction generated in OpenCL backend

---

src/WasmExecutor.cpp

LLD stopped exporting these by default, but we need them.

Explicitly export __heap_base and __data_end in WasmExecutor

---

src/IntrusivePtr.h
src/Scope.h
src/Util.h

This is a nasty C++ subtlety... custom move and copy constructors aren't `noexcept` without explicitly saying so. This means that inferred move constructors aren't `noexcept` either. Vectors of such classes will silently _copy_ upon expansion or transfer.
We should look around to see where else there might be similar issues.

Marking IntrusivePtr move copy/assign as noexcept

---

src/Var.h

These have been marked as HALIDE_ATTRIBUTE_DEPRECATED for a long time now.

Remove Var::gpu_blocks() and Var::gpu_threads()

---

src/runtime/metal.cpp

Sets the label string ivar on metal command buffers to:
- the calling halide function name for blit commands
- the entry_name arg for compute commands created from halide_metal_run
These labels can be seen at debug time in Apple's Xcode and Instrument tools.

adds labels to command buffers

---

src/runtime/opencl.cpp

device_wrap_native, without debug, just sets device field appropriately and returns, so it doesn't need a CL context and it doesn't need to load libopencl. With debug on, it also validates the pointer for you, which still doesn't need a CL context, but which does require calling clGetMemObjectInfo, which may be a null function pointer if this is the first thing you've done with Halide's OpenCL runtime in the process.

Validating a pointer requires having the OpenCL API loaded

---

src/CodeGen_C.cpp

It crashes for some of our internal tests, because computed size is incorrect and we try to access out of bounds (there is a chance that our buffers are somehow malformed and it breaks some assumptions here), but works fine when .dimensions is used.

Use dimensions to compute the size of the buffer for printout in CodeGen_C

---

halide.cmake

It emits "Emitting extra Halide output" for every registration.cpp file, but since these are now always emitted by default, this is incorrect and noisy.

Remove noise from halide.cmake output

---

test/generator/cxx_mangling_aottest.cpp
test/generator/cxx_mangling_define_extern_aottest.cpp
test/generator/mandelbrot_aottest.cpp
test/generator/memory_profiler_mandelbrot_aottest.cpp

The mangling tests were unhappy about <string> not being included.
The Mandelbrot tests were unhappy about doubles being stuffed into floats.

Fix building tests with MSVC.

---

src/CodeGen_C.cpp

This is to handle the case when lhs is signed and rhs is unsigned.

Make rhs argument of the shift operators in Codegen_C templatized

---

src/Bounds.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/DeviceArgument.cpp
src/EliminateBoolVectors.cpp
src/HexagonOptimize.cpp
src/IR.cpp
src/IR.h
src/IRMatch.h
src/VaryingAttributes.cpp

...rather than a const-char*; this is a (mostly) source-code compatible change that is intended to remove the need to dllexport data members for Windows builds.
Note that as a drive-by change I regularized various calls to is_intrinsic() to use enums consistently, and added enums for some HVX intrinsics that were previously string-only.

Revise the API for intrinsic Call nodes to use an enum

---

src/IRMatch.h

IRMatcher patterns captured referenced expressions without incrementing their ref count. This is not great for rval Exprs used in a pattern. Naively capturing them by value instead blows up runtime and code size because the SpecificExpr class, which is used to hold an Expr as a node in an IRMatcher pattern is also used by value to pass through expressions when matching. This PR uses const BaseExprNode & for that purpose instead, and converts an attempted match on a SpecificExpr to matching on the underlying const BaseExprNode & as early as possible in the matching tree using a new unwrap helper.

Capture rval exprs by value in irmatcher

---

src/Simplify_Div.cpp
test/correctness/simplify.cpp

Avoid cancelling denominators unless we know they're non-zero.

---

src/CodeGen_C.cpp
src/CodeGen_C.h
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_OpenGL_Dev.cpp

I think it should work without it most of the time, but we have some weird compiler which can't handle properly some of the generated statements, such as: 
int64_t const _200 = (int64_t)(-2147483648);
and will tell something like:
warning: this decimal constant is unsigned only in ISO C90
which means, if I understand correctly, that it treats 2147483648 as a signed int (and minus is just a unary operator), which won't fit into 32 bit and will overflow. If I add suffixes it works fine and I think it won't change anything for all other compilers (the value field in IntImm is always int64), so hopefully it's ok with you (if not maybe, we can conditionally add suffixes based on value itself?).

Add suffixes to integer constants in CodeGen_C

---

CMakeLists.txt
test/scripts/build_travis.sh

For posterity: invoking cmake on itself can force parallel builds to serialize, at least for some variants of CMake and make; this was being triggered by wrapper code that provided a `make distrib` target for CMake. It didn't seem obviously fixable, so we now just require CMake users to use `make package` instead, as that is the "magic" target that CPack provides/requires.

Fix CMake slowness for 'make distrib'

---

src/CodeGen_OpenGLCompute_Dev.cpp

GLSL "version" directive must be first statement.  "add_common_macros" added macros before the "version" directive in OpenGL compute, which causes the following error:
Could not compile shader:
0(14) : error C0204: version directive must be first statement and may not be repeated
This PR move "add_common_macros" to after generating "version" directive in OpenGLCompute.

move add_common_macros to after the version directive in OpenGL Compute

---

src/runtime/HalideBuffer.h

This isn't necessary in any of our own code, but some downstream code+compiler combinations can complain that an arg is (say) 'unsigned long' instead.

Add explicit (int) cast for rest... args

---

src/Generator.h
src/Lower.cpp
src/Lower.h
src/Pipeline.cpp
src/Pipeline.h
src/Target.cpp
src/Target.h
src/Tracing.cpp
src/Tracing.h
src/runtime/HalideRuntime.h
test/correctness/tracing.cpp
test/generator/user_context_generator.cpp

This PR adds a `Target::TracePipeline` target feature flag. The motivation for this is that I would like to get a `halide_trace` call corresponding to the beginning and end of a pipeline, but no more than this. I don't think it is possible to do this because the next possible thing to trace is realizations, but if a pipeline contains multiple compute_root stages (or even outputs), the realizations are hard to predict and may not cover the whole pipeline.
I'm throwing this out there just as a suggestion for now. This PR doesn't have a lot of time invested in it, but, I really would like to get a way to get traces at the pipeline level somehow. The motivation for this is I want to generate android traces corresponding to *most* of our pipelines.

Add Target::TracePipeline feature flag

---

apps/autoscheduler/ASLog.cpp
apps/autoscheduler/ASLog.h
apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/DefaultCostModel.cpp
apps/autoscheduler/Featurization.h
apps/autoscheduler/FunctionDAG.h
apps/support/autoscheduler.inc

This replaces the use of `debug()` in apps/autoscheduler code with its own logger (named `aslog()` for now, short for auto-scheduler-log.)
The motivation here is to allow supressing of the autoscheduler log output without also having to supress normal codegen output.
aslog() has the same semantics as debug(), except that it preferentially tries to read from HL_DEBUG_AUTOSCHEDULE for a verbosity; if that isn't set, it falls back to the same value as HL_DEBUG_CODEGEN. (Thus, the autoschedule output can be suppressed by HL_DEBUG_AUTOSCHEDULE=-1.)
Note also that all use of std::cerr that was for anything other than a fatal error was converted to aslog(0).
And yes: "aslog" isn't a very good name; I'm happy to replace it with literally anything you'd like before submitting this :-)

Give apps/autoscheduler its own logging function

---

apps/autoscheduler/ASLog.cpp
apps/autoscheduler/ASLog.h
apps/autoscheduler/train_cost_model.cpp
apps/support/autoscheduler.inc

train_cost_model needed ASLog.cpp, but since the former doesn't link to libHalide, the latter can't rely on it. (We didn't notice this because apps/autoscheduler isn't part of the normal build-and-test suite; I'll fix that in a followup PR.)
Also, drive-by fix to avoid unknown-pragma-warning-as-error in some recalcitrant compilers.

Fix bug injected by https://github.com/halide/Halide/pull/4058

---

src/CodeGen_Hexagon.cpp

@pranavb-ca @dpalermo @dsharletg I don't have a reproducer for this but seems like a trivial change.

Hexagon: Fixes the slicing bounds for the last vector in interleave_vector func

---

src/runtime/HalideBuffer.h

move is allowed to leave the moved-from item in an unspecified state; we zero out the device fields but not the host fields, so code downstream could inadvertently use a 'stale' moved-from Buffer in a flaky way. This PR is an experiment to see if fully zeroing out the moved-from Buffer's halide_buffer_t will inject any failures.

Zero out 'other' buffer in Buffer's move ctor/op=

---

CMakeLists.txt
Makefile
test/scripts/build_travis.sh

Reverts halide/Halide#4022
Apparently LLVM 7.1 is a thing, despite documentation to the contrary

Revert "Upgrade make files to understand LLVM 10+ (v2)"

---

python_bindings/src/PyPipeline.cpp

For some reason I can't figure out, #2794 forced use of the default target in Python's `Pipeline.compile_jit`, ignoring a passed-in `Target`.
This patch simplifies the wrapper to pass through a `Target`, which seems to work just fine. The code is exactly analogous to the existing wrapper code for `Func.compile_jit`.

Support Pipeline.compile_jit(target) in Python bindings

---

src/runtime/openglcompute.cpp

Minor bug fix that may crash OpenGLCompute at device release.

Minor bug fix.

---

src/Target.cpp

Oddly(?), #3732 added a compiler-conditional `bad = true` line to `Target::supported`. When `llvm-config` claims webassembly support, and the LLVM version is less than 9, `Target::supported` returns `false` for _all_ targets.
This does not seem right; in particular, the Python tests fail, because they check that the host target is supported.
This patch consolidates this case with the existing wasm check, simplifying the logic and declaring wasm targets but no others unsupported for LLVM < 9. This fixes the Python target tests for me with LLVM 7.1.

Don't declare all targets unsupported when LLVM < 9 is built with wasm

---

src/AutoSchedule.cpp
src/Pipeline.cpp

All should indicate machine generation, and record the target and machineparams used for generation. (Perhaps weights as well, someday.) Also, some minor drive-by changes to src/AutoSchedule.cpp to bring it more in line with apps/autoscheduler output.

Ensure that all .schedule files have wrapping comments

---

README_rungen.md
apps/autoscheduler/Makefile
apps/autoscheduler/autotune_loop.sh
apps/support/Makefile.inc
tools/RunGenMain.cpp

Just some syntactic sugar for the common case of using estimates for all inputs and outputs.

Add --estimate_all flag to RunGen

---

apps/support/Makefile.inc
src/runtime/HalideBuffer.h

See https://github.com/halide/Halide/issues/4080
Also: drive-by removal of `-Wno-unknown-warning-option` since no compiler seems to actually understand it

Use zero-init instead of memset for other.buf in HalideBuffer.h

---

apps/support/Makefile.inc

Apparently OSX Clang (at least) needs it to avoid complaining about -Wno-psabi

Restore -Wno-unknown-warning-option

---

src/Generator.h
test/generator/cxx_mangling_generator.cpp
test/generator/example_generator.cpp

Previouslty this didn't compile. Add a wrapper that allows it to be set (but only allow nullptr as the estimate value for now).
Also, drive-by add of set_estimates calls to two Generators.

Allow Input<SomeType*>::set_estimate()

---

src/Introspection.cpp

The debug metadata reader now uses 64-bit offsets.

Fix for llvm trunk

---

apps/autoscheduler/PerfectHashMap.h
apps/autoscheduler/test_perfect_hash_map.cpp

We don't want it to require libHalide, but including Errors.h implicitly does that. Move the 'standalone' asserter into the template class and out of the test, so that the .h file will compile standalone (regardless of what is #defined before it).

PerfectHashMap.h should be standalone

---

apps/autoscheduler/Makefile
apps/autoscheduler/autotune_loop.sh

(This was correctly bound when doing `make test_apps` at toplevel, but not if doing `make autotune` from the apps/autoscheduler folder)

Pass $HALIDE_DISTRIB_PATH to autotune_loop.sh

---

tools/RunGen.h

bounds_query_input_shapes() agressively fails if we can't complete the bounds-query, which can happen if the constraints on inputs are nontrivial. While we can (and should) improve the bounds-query logic to make this more robust, we shouldn't aggressively fail here in the first place, as the bounds-query shape(s) end up unused if we have estimates for the inputs (which we usually do). This just adds a ShapePromise type that wraps access to the resulting Shapes inside a function; if we never need the shape, the failure doesn't matter and never happens.

RunGen: bounds-query failure shouldn't matter if we use estimates anyway

---

src/Util.cpp

While handy for debugging, this means the autoscheduler currently spams stdout with timing info by default, which is puzzling to people not actually working on the autoscheduler.
(alternately: add debug-level option to HALIDE_TIC, or just comment out the calls to it in the autoscheduler)

Change halide_toc_impl to use debug(1) instead of debug(0)

---

python_bindings/src/PyTarget.cpp
src/Target.h

This is really a workaround to allow generated .schedule.h files to compile happily in all cases. A better long-term answer would be for those files to use the Target::Feature names (rather than the halide_target_feature_t names), but doing so will require an additional value->name map (which must be maintained and could get out of sync), so I'm reluctant to do that without a little more thought.

Allow Target::has_feature() to operator on halide_target_feature_t

---

src/Simplify_Add.cpp
src/Simplify_Mul.cpp
src/Simplify_Sub.cpp
test/correctness/simplify.cpp

These are no-overflow types, so treat such cases not as things that
overflow (in which an overflow in the upper bound would affect the lower
bound), but rather as things which still have upper/lower bounds that we
can no longer represent.
Fixes #4142

Avoid 64-bit overflow when tracking constant bounds in simplifier

---

apps/autoscheduler/Makefile
apps/autoscheduler/autotune_loop.sh
apps/support/autoscheduler.inc
src/IROperator.cpp
src/IROperator.h
src/PartitionLoops.cpp
src/Simplify.cpp
src/UnrollLoops.cpp

Fix an issue where UnrollLoops failed to recognize a constant extent as such, then remove HL_PERMIT_FAILED_UNROLL=1 as the default in autoscheduler. (We think this should be (mostly) unnecessary in most cases, so we'll now issue a user-warning if we trigger it.)

Smarten UnrollLoops; remove HL_PERMIT_FAILED_UNROLL=1 defaults

---

apps/autoscheduler/FunctionDAG.h

The failure mode for autoscheduling-a-func-with-a-schedule-on-it is currently inscrutable; change from an internal_assert to a user_assert with a more-helpful message.

Improve assertion in FunctionDAG

---

src/Simplify_Add.cpp
src/Simplify_Select.cpp
src/Simplify_Sub.cpp
src/UnrollLoops.cpp
test/correctness/sliding_window.cpp

Unrolling happens after sliding but before partitioning, so the extents of the unrolled loop are complex, but should have an upper bound that enables unrolling. It can be hard for the compiler to see this through all the selects. 
This PR makes things way more aggressive in the about-to-fail case in unrolling. It now exhaustively substitutes in everything for maximally aggressive simplification, and there are a bunch of new simplifier rules to help cancel things through select nodes. This exhaustive substitution is somewhat dangerous, but this is a case where the compiler is about to throw an error if it doesn't simplify down to almost a constant.

Simplifications for unrolling sliding window

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/DefaultCostModel.cpp

It was only referenced in single-shot scheduling, but we shouldn't ever be saving from that path anyway (only from the retraining loop).
Also change save_weights() to fail with abort() if you try to save with an empty output path (rather than quietly doing nothing), and upgrade save failures from assert(0) to abort(), because that's not an error we want to risk eliding based on compiler settings.

Remove HL_WEIGHTS_OUT_DIR

---

apps/autoscheduler/FunctionDAG.h

gcc will fail with -Werror=class-memaccess because PipelineFeatures is not TriviallyCopyable

Use zero-init instead of memset for PipelineFeatures

---

src/Derivative.cpp
test/error/autodiff_unbounded.cpp

This addresses https://github.com/halide/Halide/issues/4172 by emitting proper error messages when encountering unbounded access.

Add proper error message when differentiating unbounded access

---

test/correctness/float16_t.cpp

WASM needs some love for float16; disabling this test pending a fix.

Disable correctness_float16 on WASM for now.

---

apps/autoscheduler/retrain_cost_model.cpp
apps/support/autoscheduler.inc
apps/support/cmdline.h

getopt() doesn't exist for MSVC; there are ports available, but if we have to add code, let's add something that doesn't include weird extra globalvars for parsing, the way getopt does. I somewhat arbitrarily chose a simple header-only BSD/MIT-licensed library that seems to be reasonable (https://github.com/tanakh/cmdline). Thoughts?

Replace getopt() with header-only flags parser

---

src/CodeGen_LLVM.cpp
src/Func.h
src/JITModule.h

- unreachable-code warning
- unnecessary 'get' call on smart ptr
- useless forward decls

Handful of minor clang-tidy fixes

---

src/CodeGen_Hexagon.cpp

The IPICK() macro token-pastes to the end of the argument; in this case using a ternary expression inside means that the i128 suffix is pasted to one but not both. This restructures the bad use case to avoid the badness.
(Found via inspection -- I don't know if this is causing an actual problem or not.)
(I will likely follow this up with a PR that restructures the code more broadly to make this sort of error harder, as well as compressing the instruction table.)

Fix macro mis-usage in Codgen_Hexagon

---

src/IROperator.cpp
src/IROperator.h

IROperator.h has way too much code in it; this moves almost all of the non-templated inline functions into IROperator.cpp (along with some drive-by anon-namespacing of internal functions). 
This is mostly just an attempt at hygiene, as ~none of these functions really needed to be inlined; that said, this does seem to produce a small but measurable improvement in compilation performance on my Linux box (recompiling libHalide.a from scratch drops to about 97% of user time).
Note that I didn't attempt to update any calling conventions; I suspect that updating various calls to pass Expr and/or Type by const-ref (rather than value) might be profitable.

De-inline most of IROperator.h

---

src/PythonExtensionGen.cpp

It's nontrivial enough to generate a warning; use zero-init form instead

Don't call memset(0) on halide_buffer_t

---

python_bindings/apps/bilateral_grid.py
python_bindings/apps/blur.py
python_bindings/apps/erode.py
python_bindings/apps/interpolate.py
python_bindings/apps/local_laplacian.py
python_bindings/tutorial/lesson_02_input_image.py
python_bindings/tutorial/lesson_07_multi_stage_pipelines.py
python_bindings/tutorial/lesson_09_update_definitions.py
python_bindings/tutorial/lesson_12_using_the_gpu.py

imread and imsave are deprecated and not present in current versions of scipy; using equivalent functions in imageio is the recommended replacement.

Python: import imread/imsave from imageio instead of scipy.misc

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/half_native_interleave.cpp

This prevents matching interleaving hexagon patterns if the result can't be interleaved. Checks that the
op type is atleast 2 vector widths for widening ops.
Currently, compile-time assert is thrown in Codegen (see: https://github.com/halide/Halide/issues/1582) when the interleaved hexagon intrinsic op is not equal to two vector width. This is a recurring issue in widening ops, where the widening ops have to be vectorized by 2 * native vector width for valid codegen. This change lets the backend ISEL handle half-native vectors, instead of applying interleaved widening Hexagon intrinsics which the backend miscompiles.
@dsharletg PTAL

Restrict interleaving Hexagon pattern matches

---

src/IRPrinter.cpp
src/IRPrinter.h

It's currently hard to parse Halide Exprs in isolation, because the types of Vars, Loads, and similar depend on the context, which is not always present. This PR tracks which names have a type that can be inferred from the context, and prints the type too when they're not (and when they're not just Int(32) - having a default case cuts down on clutter). With this change a hypothetical parser would just need to track a Scope from strings to types.
Also as a drive-by I added prettier printing of chains of lets around store nodes. They can get large right now. 
This PR is related to #4233 
Here's a sample of the new IR printing excerpted from local laplacian. The most obvious change in the newlines, but note also that `beta` is now `(float32)beta`. All of the other types can be inferred from …

Print types when not inferrable from context

---

src/CodeGen_LLVM.cpp

Reverts halide/Halide#4221 -- unfortunately, this seems to be injecting value changes into some code downstream (despite earlier tests that seemed to indicate it did not).

Revert "Re-enable LLVM NewPassManager"

---

Makefile

This allows the -j parameter to be propagated properly to the submake, allowing much faster build times. (On my Linux box, `make -j72 test_python` goes from 6m30s -> 51s in realtime)

Use $(MAKE) instead of make for test_python

---

python_bindings/correctness/float_precision_test.py
python_bindings/src/PyExpr.cpp

always double to float cast.
----------
Test code
```python
import halide
import numpy
def run_test():
test = halide.Func("test")
x = halide.Var("x")
test[x] = x * halide.f64(0.12345678901234)
for i, val in enumerate(numpy.asarray(test.realize(10))):
print("{}: {:.20f}".format(i, val))
```
before:
```
>>> run_test()
0: 0.00000000000000000000
1: 0.12345679104328155518
2: 0.24691358208656311035
3: 0.37037037312984466553
4: 0.49382716417312622070
5: 0.61728395521640777588
6: 0.74074074625968933105
7: 0.86419753730297088623
8: 0.98765432834625244141
9: 1.11111111938953399658
```
after:
```
>>> run_test()
0: 0.00000000000000000000
1: 0.12345678901234000135
2: 0.24691357802468000271
3: 0.37037036703701997631
4: 0.49382715604936000542
5: 0.61728394506170003453
6: 0.74074073407403995262
7: …
```

fix python_bindings bad float cast

---

apps/support/autoscheduler.inc

Explicitly enable RTTI in retrain_cost_model (cmdline.h requires it)

---

python_bindings/src/PyFunc.cpp
python_bindings/tutorial/lesson_10_aot_compilation_generate.py
src/BoundaryConditions.cpp
src/CodeGen_PyTorch.cpp
src/CodeGen_PyTorch.h
src/Func.cpp
src/Func.h
src/IRPrinter.h
src/Module.cpp
src/Pipeline.cpp
src/Pipeline.h
test/correctness/python_extension_gen.cpp

- Code in Module.cpp should just require the c_header to be generated along with PyTorch (and PythonExtension) rather than trying to fake one
- Removed `compile_to_python_extension()` as a public API entirely; since you must generate at the same time as the header file, it's more sensible to just require using the `compile_to()` method for this instead
- strip the header path into 'leaf' form uniformly
- don't put 'using' into root namespace in generated header files
- fix ad-hoc .pytorch.h extension usage in favor of putting the right thing into the table (overlooked in recent Outputs overhaul)
- nuked unnecessary member vars, virtual decls, suboptimal grammar, other detritus
attn: @mgharbi

Various followup cleanups to 'Outputs' change

---

apps/autoscheduler/CMakeLists.txt

With lld, i get
```
[1/6] Linking CXX executable bin/test_apps_autoscheduler
FAILED: bin/test_apps_autoscheduler
: && /usr/bin/clang++-8  -pipe  -rdynamic apps/autoscheduler/CMakeFiles/test_apps_autoscheduler.dir/test.cpp.o  -o bin/test_apps_autoscheduler  -Wl,-rpath,/repositories/Halide/build/lib lib/libHalide.so && :
ld: error: undefined symbol: dlopen
>>> referenced by test.cpp
>>>               apps/autoscheduler/CMakeFiles/test_apps_autoscheduler.dir/test.cpp.o:(main)
ld: error: undefined symbol: dlerror
>>> referenced by test.cpp
>>>               apps/autoscheduler/CMakeFiles/test_apps_autoscheduler.dir/test.cpp.o:(main)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Explicitly linking to `dl` library fixes the issue.
I believe this is the …

Fix linking of test_apps_autoscheduler

---

.travis.yml

Previouslt it was LLVM8+7, except we deliberately skipped LLVM7 because it was known to have flaky prebuilts.  https://github.com/halide/Halide/issues/4262

Upgrade Travis builds to LLVM9+8 (Issue #4262)

---

src/CodeGen_C.cpp
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_OpenGL_Dev.cpp
src/CodeGen_PyTorch.cpp
src/Generator.cpp
src/IRPrinter.cpp
src/IRPrinter.h
src/PrintLoopNest.cpp
src/ScheduleFunctions.cpp

It's always bugged me that IRPrinter used a separate call (`do_indent()`) to indent outputs, rather than some approach that mixed into the stream flow of operator<<.
This is a completely nonessential change that nevertheless (I think) improves the code; it creates a new type, `Indentation`, which has an `operator<<` overload. This means that stream writes that begin with an indent are more obvious (since it's part of the ordinary stream syntax).

Clean IRPrinter indentation code

---

src/IRPrinter.cpp

Inadvertently left out of previous push.

Fix code style error in IRPrinter.cpp

---

apps/HelloPyTorch/setup.py

include_dirs should be an arg to the Extensions, not to setup(). (Apparently we were often getting lucky with the include path, but on my local OSX box it fails to build without this change.)

Fix HelloPyTorch/setup.py

---

apps/autoscheduler/Weights.cpp

```
Halide/apps/autoscheduler/Weights.cpp:22:34: error: implicit conversion from 'std::mersenne_twister_engine<unsigned long, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::result_type' (aka 'unsigned long') to 'float' changes value from 4294967295 to 4294967296 [-Werror,-Wimplicit-int-float-conversion]
f = ((float)rng()) / rng.max() - 0.5f;
~ ^~~~~~~~~
```
I think we should just make the cast explicit here?

Autoscheduler: Weights::randomize(): silence clang's -Wimplicit-int-float-conversion

---

CMakeLists.txt
halide.cmake
src/CMakeLists.txt

As discussed in https://github.com/halide/Halide/issues/4284
one important thing is to be able to link to shared versions
of LLVM libraries. This is off-by-default, so i don't believe
this should have any impact on existing users.
The important [existing] caveat to note is that i don't see
where those LLVM libraries-to-be-linked are specified anywhere
in the `halide_config.cmake`, so as long as you are
a. building static halide
and
b. not building halide as a cmake sub-project (via `add_subdirectory()`)
i don't see how the linking can succeed, both either with
old static LLVM libraries, and now with shared LLVM library.
The best i can tell `llvm-config --system-libs` is only needed
when linking to static libraries, to propagate their deps,
so let's not do that for shared LLVM libs.
And …

CMake: add optional LLVM_USE_SHARED_LLVM_LIBRARY option.

---

python_bindings/correctness/basics.py
python_bindings/src/PyFunc.cpp

An attempt to fix https://github.com/halide/Halide/issues/4285. As mentioned the issue is that when pybind11 is visiting all possible overloaded function for `Func.__setitem__(key, value)`, it tries to convert the key `g[1]` into a list of `Var` or `Expr`. To do this it checks whether `g[1][0]` is a Var/Expr or not, but this triggers a runtime error inside Halide, since `g` is not a Tuple.
My proposed solution to this is to define a set of overloaded functions so that the overloading test ends before it enters the list testing conversion phase. Another possible fix is to rewrite `__getitem__` in FuncRef such that it doesn't trigger runtime error even when `g` is not a Tuple.

Allowing f[g[1]] = 2 in Python bindings

---

apps/support/Makefile.inc

CXX may include absolute path to clang++ or
maybe symlinked to clang++. Detect that it points
to clang++ to check if Halide was built using libc++.

Detect clang++ as host-compiler reliably

---

apps/autoscheduler/Makefile
apps/support/Makefile.inc
apps/support/autoscheduler.inc

Passing libHalide.so as an input while building the autoscheduler
inside apps/autoscheduler is creating a dependency on libHalide for
the shared plugin library where libauto_schedule.so looks for
libHalide.so in the absolute path and fails to open if the libHalide
is not found in that path. This makes the plugin not portable, as it
warrants the libHalide.so to be present in the same location while using
the plugin.
Using readelf -d on the built libauto_schedule.so --
`(NEEDED)             Shared library: [/mnt/workspace/Halide/distrib/bin/libHalide.so]`
While using the plugin, if libHalide is loaded from other path, the
plugin fails to load as it searches for libHalide in the absolute
path used while building autoscheduler.
This change links to the built libHalide.so instead of passing it …

Link libHalide for building libauto_schedule.so

---

src/Pipeline.cpp

MSAN is well-documented as not support JIT compilers of any sort, and will report false positives in that case. We should (at least) emit a warning if the user tries to use the JIT if libHalide is compiled with MSAN enabled (regardless of whether 'msan' is in the Halide::Target).
(I'm tempted to make this a user_error instead of a warning. Thoughts?)

Warn user if using JIT + MSAN

---

src/CodeGen_LLVM.cpp

`setAlignment` now takes `MaybeAlign` objects instead of an `uint64_t`, in llvm 10. This is causing compilation failures in buildbots.

Fix deprecated LLVM function calls (setAlignment)

---

python_bindings/requirements.txt

Without it the example apps (and hence the target test_python) will fail to run, as the apps use it to load/store images.

added imageio package to dependencies

---

apps/HelloPyTorch/test.py
apps/onnx/halide_as_onnx_backend.py
apps/onnx/halide_as_onnx_backend_test.py
apps/onnx/model.py
apps/onnx/model_test.py
python_bindings/apps/bilateral_grid.py
python_bindings/apps/blur.py
python_bindings/apps/erode.py
python_bindings/apps/interpolate.py
python_bindings/apps/local_laplacian.py
python_bindings/correctness/basics.py
python_bindings/correctness/bit_test.py
python_bindings/correctness/boundary_conditions.py
python_bindings/correctness/buffer.py
python_bindings/correctness/division.py
python_bindings/correctness/iroperator.py
python_bindings/correctness/multipass_constraints.py
python_bindings/correctness/pystub.py
python_bindings/tutorial/lesson_02_input_image.py
python_bindings/tutorial/lesson_03_debugging_1.py
python_bindings/tutorial/lesson_07_multi_stage_pipelines.py
python_bindings/tutorial/lesson_09_update_definitions.py
python_bindings/tutorial/lesson_12_using_the_gpu.py
python_bindings/tutorial/lesson_13_tuples.py

- Remove all `from __future__ import`, as they are unnecessary for Python3
- restructure how imageio.imread and imageio.imsave are imported & called, to avoid warnings with some strict-import-checking tools (the previous technique could be construed as an ambiguity, apparently)

More Python Cleanup

---

apps/bilateral_grid/filter.cpp
apps/blur/test.cpp
apps/camera_pipe/process.cpp
apps/conv_layer/process.cpp
apps/cuda_mat_mul/runner.cpp
apps/lens_blur/process.cpp
apps/local_laplacian/process.cpp
apps/stencil_chain/process.cpp

Many of the apps don't have proper device_sync called when running on GPU. I also found that `halide_reuse_device_allocations` significantly improves performance on all of them consistently. Should we just make reuse allocation default to be true?

Add device_sync and halide_reuse_device_allocations to some apps

---

python_bindings/readme.md

Should be `make` instead of `bash make`

Fix Python building instruction

---

src/IROperator.cpp
src/IROperator.h
src/StrictifyFloat.cpp

Quietly wrap the arg to these functions in strict_float(), to ensure the results aren't meaningless.
(Also: drive-by cleanup of code in StrictifyFloat that was a holdover from when it was possible to have contexts in which strict-float was not allowed)

Make is_nan/is_inf/is_finite enforce strict_float() (Issue #4281)

---

apps/autoscheduler/Makefile
apps/autoscheduler/autotune_loop.sh
apps/support/autoscheduler.inc

- `make test` should ensure that the `samples` output dir is a subdir of `$(BIN)`, so that it doesn't go in-source-tree and fill up the buildbots
- autoscheduler.inc should default $(AUTOSCHED_BIN) to match $(BIN) so that the toplevel Makefile can override it properly (previously we ended up with some build products in-tree and some in-build-products-dir)

Fix apps/autoscheduler out-of-tree builds (Issue #4355)

---

Makefile
apps/gradient_autoscheduler/ASLog.cpp
apps/gradient_autoscheduler/ASLog.h
apps/gradient_autoscheduler/GradientAutoscheduler.cpp
apps/gradient_autoscheduler/Makefile

- Migrate the aslog() utility from apps/autoscheduler and use aslog(1) instead of std::cerr (schedulers need to be *absolutely silent* by default to avoid build-system spam)
- Add gradient_autoscheduler to 'make test_apps'
- build with -fvisibility=hidden to save code size
- default WITH_PYTHON to 0... as written, this requires every piece of code using to link to Python, which is definitely not what we want. (The code should be modified to either have a separate library for Python usage, or to find a way to safely lazy-load the Python extension library.)
- Use `$(PYTHON)-config --cflags` to ensure path to Python.h can be found (if WITH_PYTHON=1 is set)

gradient_autoscheduler fixes

---

apps/support/autoscheduler.inc

- Don't include debug symbols (`-g`) by default (>10x size savings); when necessary for debugging, the preferred fix here it override the value of the OPTIMIZE flag
- Add `-fvisibility=hidden -fvisibility-inlines-hidden` to save another 30k or so

Reduce binary size of of libauto_schedule.so

---

Makefile
apps/autoscheduler/test.cpp
apps/gradient_autoscheduler/GradientAutoscheduler.cpp
apps/gradient_autoscheduler/Makefile
apps/gradient_autoscheduler/test.cpp
apps/gradient_autoscheduler/test.py
apps/support/Makefile.inc
python_bindings/Makefile
python_bindings/src/PyHalide.cpp
src/Generator.cpp
src/Util.cpp
src/Util.h

Promote this to a first-class Halide API, along with Python wrapper. Remove the python-related code from apps/gradient_autoscheduler and use this instead. Also drive-by cleanup in gradient_autoscheduler to run all the tests properly.

Add Halide::load_plugin

---

src/CPlusPlusMangle.cpp

The iOS SDK defines int64 as `long long` and uint64 as `unsigned long long`, but we are currently mangling them as `long` and `unsigned long`, so we will get linker errors for compiled filters that use one of these types as an input (assuming c_plus_plus_name_mangling is enabled).

Fix name-mangling [u]int64 on IOS

---

apps/HelloPyTorch/Makefile
apps/HelloPyTorch/setup.cfg

Some combinations have a known issue and the `pip install` part of the Makefile will fail with `DistutilsOptionError: must supply either home or prefix/exec-prefix — not both`
Adding this dummy setup.cfg is (apparently) a reasonably safe solution, and works on my setup.
attn @mgharbi

Fix OSX+Homebrew+Python issue for HelloPyTorch

---

src/Module.cpp

Currently, when autoscheduler is invoked in offload mode, the
the emit options {featurization and schedule} are not working
as expected and bailing out due to auto_scheduler_results not
present in the lowered module, resulting in empty feature and
schedule files produced. This happens because, when offloaded
submodules are recursively resolved, the autoscheduler results
are not copied back into the lowered module. This change fixes
this issue by setting back the auto_scheduler_results in the
ModuleContents of the module that is lowered after resolving
submodules.

Fix offload mode autoscheduler results.

---

src/runtime/HalideBuffer.h

It's UB to compute offset-from-a-null-pointer in C++; we call size_in_bytes() from allocate() so this is technically UB. Restructure code a bit to make this moot; while we're at it, add asserts to begin() and end() if the host ptr is null (since that would also always be bad).

Fix UB in Halide::Runtime::Buffer<>::size_in_bytes()

---

test/correctness/simd_op_check.cpp
test/correctness/simd_op_check.h
test/correctness/simd_op_check_hvx.cpp

We have been calling set_host_alignment(128) on our input params for ~ever, but this has always been wrong; as the argument is in bytes (not bits), and most of our targets provide only a 32-byte guarantee at the memory allocator level (x86 does 64-bytes, see LLVM_Runtime_Linker.cpp)
(Note that I'm not sure if the _hvx variant really should be 128 bytes or not, please review carefully.)

Fix set_host_alignment() in simd_op_check

---

apps/onnx/onnx_converter.cc

Existing code will fail when compiled with -Werror=strict-aliasing

avoid reinterpret_cast in onnx_converter

---

apps/gradient_autoscheduler/GradientAutoscheduler.cpp
apps/gradient_autoscheduler/test.cpp

There is a bug in the gradient autoscheduler, that makes it taking the wrong output size estimates since it assumed the estimates have the same order as the output arguments. This PR fixes it.
Not sure how to test this. @steven-johnson any idea?

Fix gradient autoscheduler's usage of output estimates

---

README_webassembly.md
src/WasmExecutor.cpp
test/correctness/atomics.cpp

- require V8 7.5 as baseline (rather than 7.3)
- add half-float glue code
- blacklist correctness_atomics from wasm testing
- Update readme

Update WebAssembly support

---

src/Lower.cpp

**Scenario**
1. Buffer is created and filled with data.
2. CUDA is **later** added to the JIT target ```set_feature(Halide::Target::CUDA)```
3. Use buffer on the device for computation
**Observation**
Buffer is not copied to Device before use.
**Solution**
Mark buffer as ```set_host_dirty``` when device memory is allocated.
**Discussion**
In the corner case, when a buffer is created and filled on the host before CUDA is added to the JIT target, the buffer is not marked as host_dirty and thus not copied on first use. Our proposed fix is to mark the host as dirty on device memory allocation.  This one-line change fixes the issue for our use cases. Is there additional tests we should do to check is validity?

Bugfix: Empty device buffer on corner case

---

apps/autoscheduler/FunctionDAG.cpp

Avoid setting node.func in two separate locations. The second initialization is redundant and confusing
Streamlined the initialization of node.stages by avoiding extra stage creation and movements.
Also applied clang-format, which accounts for all the other code changes

Small code simplifications at the beginning of the FunctionDAG constructor

---

Makefile
apps/HelloPyTorch/Makefile
apps/HelloPyTorch/modules.py
apps/HelloPyTorch/test.py
halide.cmake
src/Derivative.cpp
src/Derivative.h
src/Generator.cpp
src/Generator.h
test/CMakeLists.txt
test/generator/autograd_aottest.cpp
test/generator/autograd_generator.cpp

This adds a new flag to Generator main (-d) that will look at the inputs and outputs of the Generator and produce a new pipeline (via propagate_adjoint) that is suitable for using as the gradient-descent stage for PyTorch, TensorFlow, etc.
A few notes:
- obviously this is lightly tested, but the heavy lifting is done by Derivative, which is in pretty good shape.
- doesn't support inputs or outputs with Tuple values; we probably could make this work with more effort, but since (AFAICT) neither PT nor TF allow tuple-valued Tensors, it's of dubious value to support
- In general the nomenclature here is dubious and may need rethinking
- Updated apps/HelloPyTorch to use this (in conjunction with the manually-written variant). Note to reviewers, there's some horrible code in the PyTorch support …

Add option to create gradient-descent variant of a Generator

---

test/generator/autograd_aottest.cpp
test/generator/autograd_generator.cpp

The classic autoscheduler can over-vectorize (e.g., on Skylake it will vectorize to width=64, which will fail for inputs of width<64). This is a somewhat-known issue; rather than try to fix it here, I am just going to widen the buffers to the autograd test to avoid failure on Skylake+ machines. (Note that autograd shouldn't be using the classic autoscheduler in the first place; it should be using the gradient autoscheduler, but packaging issues make that impractical just yet.)

Increase autograd estimates/sizes from 32 -> 64

---

python_bindings/src/PyDerivative.cpp
src/Derivative.cpp
src/Derivative.h
src/Generator.cpp

This finishes the work stated in PR#4393, converting Derivative to use Range/Region in its API rather than pair<Expr, Expr>. Note that aside from the structure change, this is also a change from {min,max} to {min,extent}.

Use Halide::Range instead of std::pair<Expr, Expr> in Derivative (Issue #4381)

---

src/Expr.h
src/IROperator.cpp

Alternative to https://github.com/halide/Halide/pull/4444: Range(min, extent) requires Exprs to be losslessly convertible to int32.

Range() requires Exprs to be losslessly convertible to int32

---

src/CodeGen_C.cpp
src/CodeGen_PyTorch.cpp
src/runtime/HalideRuntime.h

This is designed to make it easier to enforce examination of the result code of calls into Halide AOT code; by providing the HALIDE_MUST_USE_RESULT as part of the generated .h files, you can enable this by simply adding `-DHALIDE_FUNCTION_ATTRS=HALIDE_MUST_USE_RESULT` to your build options (rather than having to ensure that other dependencies ahead of other includes).
This mimics the definition used by Abseil, in which the C++17 [[nodiscard]] attribute is preferred when available.
(It's quite possible that HALIDE_MUST_USE_RESULT could be profitably applied to Halide APIs as well, both internal and external; I haven't attempted to look for candidates at this time.)

Add HALIDE_MUST_USE_RESULT macro to HalideRuntime.h and AOT .h

---

src/CodeGen_LLVM.cpp

calls to halide_print() -- including those injected by Target::Debug -- will trigger MSAN failures currently. When the target includes MSAN, we should mark the buffer as initializaed to avoid false failures.

stringify() should call halide_msan_annotate_memory_is_initialized()

---

Makefile
apps/bgu/CMakeLists.txt
apps/bgu/Makefile
apps/bgu/bgu_generator.cpp
apps/bgu/filter.cpp
apps/hist/CMakeLists.txt
apps/hist/Makefile
apps/hist/filter.cpp
apps/hist/hist_generator.cpp
apps/max_filter/CMakeLists.txt
apps/max_filter/Makefile
apps/max_filter/filter.cpp
apps/max_filter/max_filter_generator.cpp
tools/halide_benchmark.h

This batch is bilateral-guided-upsampling, max_filter, and histogram equalization. I believe this pulls over all of the apps from the autoscheduling 2018 siggraph paper into master, where they can be used as benchmarks in future papers.

Move last three autoscheduler benchmark apps into master

---

src/LLVM_Headers.h

This header file doesn't exist if llvm was compiled without hexagon support.

Add missing WITH_HEXAGON guard

---

apps/conv_layer/Makefile
apps/conv_layer/conv_layer_generator.cpp
apps/conv_layer/process.cpp
src/AutoSchedule.cpp

Our conv layer schedule was pretty tragic, for both CPU and GPU. This PR fixes them (on at least one machine). This conv schedule hits 88% of peak flops on my GPU, and 91.7% of peak flops on my CPU.

Reschedule conv layer

---

src/AddImageChecks.cpp
src/CodeGen_Internal.cpp
src/ScheduleFunctions.cpp
src/runtime/HalideRuntime.h
src/runtime/msan.cpp
src/runtime/msan_stubs.cpp
src/runtime/runtime_api.cpp
test/generator/msan_aottest.cpp
test/generator/msan_generator.cpp

Augment our MSAN support to ensure that input buffers (and the output of extern stages) are checked for uninitialized data.
Note 1: msan_aottest has become an ugly mess of code; it should probably be changed to use a table-driven state machine. Not sure if that blocks this or not.
Note 2: this should probably get checked inside Google before landing (which will probably happen post-holidays), as we have a fair number of complex pipelines that are running with msan enabled.

MSAN: check input buffers for poison (Issue #4481)

---

.clang-format

- Remove duplicate `Cpp11BracedListStyle` declaration (some tools will barf on duplicate keys, apparently)
- Sort all the entries
- Remove the misleading `BasedOnStyle` line (it was commented out and so we were really based on 'default')

Tweaks to clang-format

---

src/ScheduleFunctions.cpp

My brain was parsing this as pair.stage_2 == (0 ? ... : ...), which is a degenerate ternary operator. Added parens to avoid confusing others too.

Add parens to clarify a ternary operator

---

src/CMakeLists.txt

The munging we did for the output of `llvm-config --system-libs` in src/CMakeLists.txt was not ideal, and could trick CMake into illegal linker lines (on Unixy systems) if the system libs contained both absolute paths and `-l` directives. I think this solves the issue.
EDIT: for posterity, it only shows up for SHARED_LIBRARY=ON, and only on LLVM trunk (this latter bit is why it never shows up for Travis, which doesn't do trunk)

Fix CMake breakage for recent LLVM

---

Makefile

The additions of MAKEFLAGS is causing my local Linux box to fail:
```
$ make -j72
mkdir -p bin/build
Found a new enough version of clang
touch bin/build/rtti_ok
/usr/local/google/home/srj/GitHub/Halide/tools/binary2cpp.cpp -o bin/binary2cpp
mkdir -p bin/build
bash: /usr/local/google/home/srj/GitHub/Halide/tools/binary2cpp.cpp: Permission denied
```
Let's back this out until it can be debugged.

Remove --no-builtin-variables from MAKEFLAGS

---

.clang-format
python_bindings/src/PyBuffer.cpp
src/runtime/d3d12compute.cpp
src/runtime/hexagon_remote/sim_host.cpp
src/runtime/metal.cpp
src/runtime/opencl.cpp
src/runtime/openglcompute.cpp
src/runtime/scoped_spin_lock.h

- make our .clang-format style compatible with clang-format-9
- re-run 'make format' to bring everything back into conformance with the slightly-tweaked style

More clang-format fixes

---

src/BoundsInference.cpp
test/generator/msan_aottest.cpp

BoundsInference.cpp was missing the logic to mark newly-created buffer shapes as initialized for MSAN, so pipelines with `.define_extern()` usage could get erroneous MSAN failures.

BoundsInference needs to mark buffer shapes too

---

LICENSE.txt

apps/support/cmdline.h is BSD 3-Clause (which is different from the bulk of Halide), so call this out specifically.

Update LICENSE.txt for cmdline.h

---

.clang-format-ignore
.github/workflows/presubmit.yml
python_bindings/stub/PyStub.cpp
src/runtime/hexagon_remote/bin/.clang-format

Exclude dirs via .clang-format-ignore. Also special-case PyStub.cpp since it has a confusing structure that varies results between clang-format 9 and 10.

Followup fixes for clang-format checker

---

src/Solve.cpp

Found a silly bug in solve_expression. We were unpacking a, then swapping the sense of a and b to canonicalize things. That should happen in the other order.
@aekul

Fix solve canonicalization

---

apps/bilateral_grid/bilateral_grid_generator.cpp
apps/conv_layer/conv_layer_generator.cpp
apps/local_laplacian/local_laplacian_generator.cpp
apps/stencil_chain/stencil_chain_generator.cpp

I benchmarked a few more apps on the same machine as the recently-rescheduled ones, to get a consistent set of benchmarks for people to refer to. This is mostly useful for sanity checking numbers when doing comparisons (e.g. if it's 10x slower than the comment indicates it should be, I must be holding it wrong).
I also rescheduled stencil chain, including writing a GPU schedule. It's a very simple GPU schedule but I was unable to get a better one within an hour of messing about.

Update benchmark comments in apps

---

src/Simplify_Call.cpp

There were a number of PureExtern functions we didn't handle (notably sin and cos, but many others too); rather than add even more if-else clauses, I refactored the PureExtern case into a set of LUTs to reduce redundant code.
Note that the actual motivation for this change was to ensure that sin(CONSTANT) and cos(CONSTANT) got simplified to a real constant (rather than putting us at the mercy of LLVM).
(With more cleverness we could make it a single LUT, but my first approach involved template-fu that was overly complex to read; I suspect that this approach is a better balance of compile time vs code complexity, but would welcome someone more clever to simplify it further.)

Make the Simplifier handle PureExtern functions via LUT

---

src/HexagonOffload.cpp
src/runtime/hexagon_host.cpp
src/runtime/hexagon_remote/halide_remote.cpp
src/runtime/hexagon_remote/sim_remote.cpp

We currently use an odd subset of the classic 'buffer_t' type in the HVX arg-passing code; despite its name, it doesn't appear to ever we used as an old 'buffer_t' (which is good, since it's too small and would likely cause crashes). As far as I can tell, it's just a two-entry struct that is used exclusively to pass arg info from host->hvx (or host->sim). Since the old buffer_t type is long-deprecated (and hopefully going to go away entirely soon), let's avoid any possible confusion by renaming it to `hexagon_arg_buffer_t` in hexagon_remove and sim_remote, and by declaring and using it in hexagon_host.cpp (rather than unpacking the fields directly).
HexagonOffload.cpp could arguably use the same struct, but I didn't bother, instead just documenting the correspondence with a comment.

Rename/clarify the Hexagon argument 'buffer_t' type

---

src/FuseGPUThreadLoops.cpp
test/correctness/gpu_different_blocks_threads_dimensions.cpp

Found a bad assumption in the recent store_in support for GPUs. This PR fixes it and adds a test case that previously failed with an internal error.

Fix case where there are more threads dimensions than blocks dimensions

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/CMakeLists.txt
apps/autoscheduler/CostModel.h
apps/autoscheduler/DefaultCostModel.cpp
apps/autoscheduler/DefaultCostModel.h
apps/autoscheduler/Weights.h
apps/autoscheduler/retrain_cost_model.cpp
apps/support/autoscheduler.inc

the DefaultCostModel class. This allows custom cost models more
flexibility in modeling pipeline features.

Moved the bulk of the implementation of configure_pipeline_features() to

---

src/Simplify_Call.cpp

On at least one compiler (gcc 7.4 on arm32, see https://buildbot.halide-lang.org/master/#/builders/24/builds/47), overload resolution fails for std::function for std::isinf and some others. Convert to a plain function pointer (which is all we need here) to resolve.
(Also, drive-by LLVM API fix, identical to https://github.com/halide/Halide/pull/4544, to allow testing)

Fix arm32 compilation issue

---

src/FuseGPUThreadLoops.cpp

This PR fixes two bugs that showed up in random fuzzing of gpu schedules in the gpu autoscheduler work. 
- Register-level allocations within a GPU kernel are hoisted outwards to the top of the kernel, which may cause them to nest with other allocations of the same name (e.g. if something was unrolled). This is usually benign - the original use of these allocations was non-overlapping, so all uses just use the innermost one. Still, it's weird. If the sizes were different somehow it could cause real bugs. This PR uniquely numbers all register-level allocations to avoid collisions.
- let stmts that are necessary for size expressions are also lifted outwards when computing shared/heap memory size outside of the kernel launch. If multiple definitions of the same name exist in non-overlapping …

Fix duplicate allocation names in gpu kernels

---

src/CodeGen_X86.cpp
test/correctness/simd_op_check.cpp

The tests are:
correctness_simd_op_check pmulhrsw
correctness_simd_op_check vpmulhrsw*ymm

Add support and tests for pmulhrsw ssse3 and avx2 x86 instructions

---

test/correctness/math.cpp

Trying to track down intermittent recent failures in correctness_math; this just adds logging of the current host and JIT targets, similar to what is already done in simd_op_check.

Log Target info in correctness_math

---

Makefile
python_bindings/Makefile

used by build tools like conda-build to make sure the right flags are passed.

Makefile: support standard $LDFLAGS, $CXXFLAGS environment variables

---

test/correctness/math.cpp

Changes to LLVM's math reassociation made our `exp()` implementation slightly less accurate in some float32 cases than they already were... but not by much, so this is really just a tweak for reality.
e.g., `exp(18.125)` should be ~74402492.45; calling `std::exp()` returns 74402496.0  (on the systems I checked), for an absolute error of 4.
Prior to the LLVM change, our non-FMA code on x86 would reliably produce 74402552 (abserr: 60, relerr: ~0.806e-6); now, it produces 74402416.0 (abserr: -76, relerr: ~1.07e-06), just slightly outside our bounds.
Trying to maintain the same result in the face of compiler changes and different instruction sets is a fool's errand, and the number of values that are "worse" is small, so just bumping the error value is a fair fix.
(Though it's worth pointing …

Tweak relative_error in math.cpp (Issue #4559)

---

Makefile

Some of the tutorials need it (eg lesson-12), so we must ensure it's built before them.

Add HalideRuntime.h as a build dep for tutorials

---

tutorial/clock.h
tutorial/lesson_16_rgb_run.cpp

We have a really dodgy clock.h file in the tutorials used for timing a few thngs. We should use halide_benchmark.h instead.

Tutorials should use halide_benchmark instead of clock.h

---

src/DeviceInterface.cpp
src/DeviceInterface.h
src/Target.cpp
src/Target.h
src/runtime/opencl.cpp
tutorial/lesson_12_using_the_gpu.cpp
tutorial/lesson_19_wrapper_funcs.cpp

This adds a new call, `host_supports_device_api()`, which is intended to allow JIT callers to determine whether a given DeviceAPI is likely supported on the current host. Modified tutorial code to use it as appropriate. (Note that existing logic in e.g. lesson_12 that tries to load driver libraries isn't adequate, as a system may have the right software installed but no suitable hardware.)

Add host_supports_device_api()

---

Makefile
apps/blur/Makefile
apps/support/Makefile.inc

An attempt to address #4574.
This uses map files from the linker to determine the object files needed for
the static library,instead of the output from -t, which was being truncated on
macOS, likely due to the linker not flushing standard output.
It's possible some versions of the gnu tools require `-Map` instead of `-map`, but both seem to work on my system.
If this works for Makefiles, then a remaining todo is to apply this to cmake as well.
CC @mikewoodworth

Fix macOS static library issues

---

CMakeLists.txt

This addresses some issues with using libpng/libjpeg on OSX systems that have Mono installed.

Add set(CMAKE_FIND_FRAMEWORK LAST)

---

Makefile
python_bindings/Makefile
python_bindings/readme.md
python_bindings/requirements.txt

Up to now, we've required people to explicitly clone PyBind11 and point the build files at it via PYBIND11_PATH; as it turns out, there is a pip package for it, which is much simpler to manage.
This change removes usage of PYBIND11_PATH entirely, and assumes that there is a pip install that has all includes set up properly (which should be the case if you have used requirements.txt).
If this lands, there will be a followup to remove the explicit PYBIND11_PATH cruft from the buildbots.

Change PyBind11 build rules to rely on a pip-installed version

---

apps/onnx/onnx_converter.cc
src/Dimension.h

Looks like apps/onnx never got updated way back when Region/Range replaced pair<Expr,Expr>; this attempts to remedy that. (Also, drive-by un-deprecation of two methods in Dimension.h, because this app needs them, and I can't remember why we wanted them deprecated in the first place.)
Clearly we need to add this to test_apps, but that requires installing some prerequisites first....

Fix apps/onnx

---

src/ParallelRVar.cpp

Can't use substitute on Expr graphs. Use graph_substitute.

---

src/Associativity.cpp

The following code in `prove_associativity()` converts functions' self reference into a variable:
```
exprs[idx] = simplify(exprs[idx]);
exprs[idx] = common_subexpression_elimination(exprs[idx]);
// Calling Simplify or the original expr itself might have let exprs,
// so we should substitutes in all lets first
exprs[idx] = substitute_in_all_lets(exprs[idx]);
// Replace any self-reference to Func 'f' with a Var
ConvertSelfRef csr(f, args, idx, op_x_names);
exprs[idx] = csr.mutate(exprs[idx]);
```
Here the expression is substituted with all the lets in, however ConvertSelfRef is an IRMutator, making the replacement slow. This PR changes ConvertSelfRef to an IRGraphMutator so that it can handle large expressions.

Speedup associativitiy check by using IRGraphMutator

---

.github/workflows/llvm_builder.yml

I created this to do experimenting with using GHA as buildbots; prebuilding LLVM is essential for this task (due to time/etc constraints). At present these LLVM builds aren't being used outside my experimental branch, but I'd like to check this in to test the cron functionality (which apparently won't run as a presubmit).
Note that this only builds x86 (32 and 64) targets for osx/linux/windows; it doesn't attempt to build arm32/64 targets yet, as GHA doesn't offer native VMs for this architecture, and trying to crosscompile LLVM via qemu might be.... slow. (That said, we should probably try it.)
Some details:
- The LLVM archives are stored in a password-protected location in our GCE instance (which has 200GB of storage), so only authorized users can read or write them.
- the password is …

Add a GitHub Action that does nightly LLVM builds.

---

.github/workflows/llvm_builder.yml

This is intended to allow force rebuilding of some/all of the llvm targets via CURL

Add repository_dispatch support to llvm builder

---

Makefile

- add a `build_apps` target
- allow the Python executable to be explicitly specified via the `PYTHON` env var

Minor Makefile fixes

---

apps/autoscheduler/FunctionDAG.cpp
apps/autoscheduler/FunctionDAG.h

The node map is only used in the constructor of FunctionDAG: make it a local datastructure instead of keeping it as a class member.

Don't keep unnecessary data around.

---

Makefile
src/Module.cpp
test/correctness/compile_to_multitarget.cpp
test/generator/CMakeLists.txt
test/generator/multitarget_aottest.cpp
test/generator/multitarget_generator.cpp

Need to use a feature that doesn't need a custom runtime.
(Also, drive-by addition of ::Debug to the multitarget sniff test, which it should have been in already)

Fix test/generator_aot_multitarget (Issue #4619)

---

apps/autoscheduler/FunctionDAG.cpp
apps/autoscheduler/FunctionDAG.h

Remove the FunctionDAG::Stage::output_vector_size data member

---

Makefile

Here's my attempt at fixing scraping llvm objects when the linker is lld. Let's see if it still works with the other linkers. The sed invocations delete up to the first slash, and then delete everything after ):(
@shoaibkamil

Fix -Map output parsing for lld

---

src/CodeGen_Hexagon.cpp
src/CodeGen_Hexagon.h
src/HexagonOptimize.cpp
test/correctness/gather.cpp
test/correctness/interleave_x.cpp
test/correctness/simd_op_check_hvx.cpp

LLVM change https://reviews.llvm.org/rGb1d47467e261 made it so the Hexagon backend now expects actual bool vectors, rather than masks. This means we need to change our masks from having one bit per bit of vector data to one bit per byte. However, this is somewhat complicated to implement.
At the same time, the Hexagon LLVM backend is now better at handling standard LLVM assembly like `select`. Therefore, a workaround for the above commit is to just stop using `eliminate_bool_vectors` for the Hexagon backend, and change some uses of intrinsics over to be standard LLVM assembly (e.g. use `select` instead of `vmux` intrinsics).
This PR is currently potentially a performance regression because we can't deinterleave quite as many operations as we used to (because we can't …

Remove eliminate_bool_vectors from the Hexagon backend

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/CostModel.h
apps/autoscheduler/DefaultCostModel.cpp
apps/autoscheduler/DefaultCostModel.h

This change enables implementations of the cost model to customize the way schedule features are handled.

Updated the CostModel API to take a map of schedule features. 

---

apps/autoscheduler/LoopNest.cpp

When featurizing a schedule for a computation like
f(x, y, x) = g(x) + h(x, y, z)
the scheduler might try to attempt to vectorize on the 2nd or 3rd
dimension of f. However there is no such dimension for g.

Prevent a memory corruption when featurizing a schedule.

---

src/CodeGen_LLVM.cpp

internal_assert and user_assert are used in most of the code, and we depend on them to be able to recover from bugs (we compile halide with exception support, catch exceptions and try something else when they occur.)

Use internal_assert instead of assert

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/WasmExecutor.cpp

CodegenLLVM deliberately makes many small (register-sized) calls to alloca, on the plausible assumption that CPU-ish backends will promote these into registers. This isn't true for the WebAssembly backend, since (as a stack machine) it doesn't do registers; in degenerate cases (e.g. a func with ~everything inlined, and tracing enabled to increase stack usage), we can overflow the default wasm stack of ~64k, which crashes in amusing ways.
To mitigate this, add some code to CodegenLLVM to track the total alloca usage, then have WasmExecutor add this amount to the stack-size specified at link time.
Note 1: AFAICT there isn't a pre-baked LLVM method for "how much stack space does this Module require"; if there is a cleaner way to do this without tracking it ourself, that would be great.
Note …

Increase stack size for wasm tests as needed

---

.clang-format

Several options in our `.clang-format` are no longer recognized. See the documentation here for the version used by our GitHub Actions presubmit check.
https://releases.llvm.org/9.0.0/tools/clang/docs/ClangFormatStyleOptions.html
This PR replaces them with equivalents. Running `make format` does nothing.
Cherry picked from #4644

Fix .clang-format for newer versions.

---

test/correctness/debug_to_file_multiple_outputs.cpp
test/correctness/debug_to_file_reorder.cpp

Move side-effects out of assert()

---

src/AddImageChecks.cpp
src/AutoSchedule.cpp
src/BoundsInference.cpp
src/JITModule.cpp
src/Memoization.cpp
src/RealizationOrder.cpp
src/VaryingAttributes.cpp
test/correctness/reduction_schedule.cpp
test/correctness/unrolled_reduction.cpp

All these otherwise result in diagnostics like:
```
[1/844 0.8/sec] Building CXX object src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o
FAILED: src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o
/usr/local/bin/clang++  -DCOMPILING_HALIDE -DHalide_EXPORTS -DHalide_SHARED -DLLVM_VERSION=90 -DNDEBUG -DWITH_AARCH64 -DWITH_AMDGPU -DWITH_ARM -DWITH_D3D12 -DWITH_HEXAGON -DWITH_METAL -DWITH_MIPS -DWITH_OPENCL -DWITH_OPENGL -DWITH_POWERPC -DWITH_PTX -DWITH_RISCV -DWITH_X86 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-9/include -O2 -g  -fPIC   -Wall -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Woverloaded-virtual -Werror -std=c++11 -MD -MT src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o -MF src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o.d …
```

Fix build with clang trunk - mainly -Wrange-loop-construct issues

---

src/AddImageChecks.cpp
src/AutoSchedule.cpp
src/BoundsInference.cpp
src/JITModule.cpp
src/Memoization.cpp
src/RealizationOrder.cpp
src/VaryingAttributes.cpp
test/correctness/reduction_schedule.cpp
test/correctness/unrolled_reduction.cpp

All these otherwise result in diagnostics like:
```
[1/844 0.8/sec] Building CXX object src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o
FAILED: src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o
/usr/local/bin/clang++  -DCOMPILING_HALIDE -DHalide_EXPORTS -DHalide_SHARED -DLLVM_VERSION=90 -DNDEBUG -DWITH_AARCH64 -DWITH_AMDGPU -DWITH_ARM -DWITH_D3D12 -DWITH_HEXAGON -DWITH_METAL -DWITH_MIPS -DWITH_OPENCL -DWITH_OPENGL -DWITH_POWERPC -DWITH_PTX -DWITH_RISCV -DWITH_X86 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-9/include -O2 -g  -fPIC   -Wall -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Woverloaded-virtual -Werror -std=c++11 -MD -MT src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o -MF src/CMakeFiles/Halide.dir/AddImageChecks.cpp.o.d …
```

Test #4646 on buildbots

---

python_bindings/correctness/buffer.py
src/JITModule.cpp

This is a workaround for an odd corner case (cross-compiling + testing Python bindings x86-32 on an x86-64 system): 
`__udivdi3` is a helper function that GCC uses to do u64/u64 division on 32-bit systems; it's usually included by the linker on these systems as needed. 
When we JIT, LLVM will include references to this call; MCJIT fixes up these references by doing (essentially) `dlopen(NULL)` + `dlsym()` to look up the symbol. For normal JIT tests, this works fine, as `dlopen(NULL)` finds the test executable, which has the right lookups to locate it inside libHalide.so. 
If, however, we are running a JIT-via-Python test, `dlopen(NULL)` returns the CPython executable... which apparently *doesn't* include this as an exported function, so the lookup fails and very confusing crashiness …

Fix JIT-on-x86-32-under-CPython runtime error

---

src/CodeGen_GPU_Host.h
src/CodeGen_LLVM.h
src/Expr.h
src/Generator.h
src/IRPrinter.h

Clang's `-Winconsistent-missing-destructor-override` warning catches these; we don't use this yet, but will after #4644 lands.

Add 'override' for virtual dtors as needed

---

python_bindings/correctness/basics.py
python_bindings/correctness/float_precision_test.py
python_bindings/src/PyBinaryOperators.h
python_bindings/src/PyExpr.cpp
python_bindings/src/PyFunc.cpp
python_bindings/src/PyFuncRef.cpp
python_bindings/src/PyHalide.cpp
python_bindings/src/PyHalide.h
python_bindings/src/PyParam.cpp
python_bindings/src/PyRDom.cpp
python_bindings/src/PyVar.cpp

Fixes a subtle bug in the python bindings regarding int and float handling in binary ops.
(1) In Halide, a binary op with an integer literal and an Expr should implicitly coerce the integer literal to the same type as the Expr; in Python, this was handled correctly for the cases where one type was *really* an Expr, but not for the cases where it was merely Expr-like (e.g. a FuncRef). This cleans that up and adds tests.
(2) Adding the fix above ended up breaking our detection for double->rounding errors, because we only handled this for explicit Expr conversions, rather than when the conversion was implicit from a binary operator. Restructured the checking for this case so that it should be more uniform.

Fix incorrect int-promotion in Python bindings

---

.clang-tidy
.github/workflows/presubmit.yml
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_D3D12Compute_Dev.h
src/CodeGen_PTX_Dev.h
src/CodeGen_PyTorch.h
src/CodeGen_X86.h

This PR adds a presubmit check that validates that specific clang-tidy (version 9) checks pass. Currently this is limited to `modernize-use-override` which will let us get `-Wsuggest-override` (and equivalents) off the compiler command line. If there are other checks we want to run in the future, this will help enforce those without having to wait for a build to complete.
Will probably fiddle with this branch until I get the GitHub Workflow script right.

Use clang-tidy to check for override flags

---

python_bindings/src/PyBuffer.cpp
python_bindings/src/PyTarget.cpp
python_bindings/tutorial/lesson_01_basics.py
python_bindings/tutorial/lesson_02_input_image.py
python_bindings/tutorial/lesson_03_debugging_1.py
python_bindings/tutorial/lesson_04_debugging_2.py
python_bindings/tutorial/lesson_05_scheduling_1.py
python_bindings/tutorial/lesson_06_realizing_over_shifted_domains.py
python_bindings/tutorial/lesson_07_multi_stage_pipelines.py
python_bindings/tutorial/lesson_08_scheduling_2.py
python_bindings/tutorial/lesson_09_update_definitions.py
python_bindings/tutorial/lesson_10_aot_compilation_generate.py
python_bindings/tutorial/lesson_10_aot_compilation_run.py
python_bindings/tutorial/lesson_11_cross_compilation.py
python_bindings/tutorial/lesson_12_using_the_gpu.py
python_bindings/tutorial/lesson_13_tuples.py
python_bindings/tutorial/lesson_14_types.py

This is mostly a stylistic fix, but there is a real bugfix in lesson12 (which led to all of this):
-- the bugfix: in addition to PR #4661 (which this depends on), we needed to add an explicit call to `set_host_dirty()` for lesson12. (The C++ image loading code always does this under the hood, but in Python we just use imread.) This is an unsatisfying fix (users shouldn't have to call this), but apparently we don't bother calling copy-to-device if host-dirty isn't set... even if the buffer has no device bits. (This feels like a separate potential bug...)
The style fixes:
- remove weird leftover C++isms and commented-out dreck
- format everything according to PEP8
- ensure that all sanity checks are uniformly handled by assert-fail (rather than raising exceptions, quietly returning -1, etc) …

Fix python tutorials

---

src/Derivative.cpp
test/correctness/autodiff.cpp

The following code currently causes error during autodiff:
```
Buffer<float> input(1);
input(0) = rand();
RDom r(0, 1);
Func out;
out() += print(input(r));
Derivative d_out_d = propagate_adjoints(out);
```
This PR fixes this by propagating the derivative through the print function. It also prevents the derivatives being propagated through the `stringnify` function since the output of that is a pointer type.

Fix autodiff with print expressions

---

.github/workflows/llvm_builder.yml

Explicitly pass `-A Win32` for 32-bit builds, to ensure MSVC doesn't choose to make x64 by default

Fix LLVM Builder script for Win32

---

src/runtime/metal.cpp

As far as I can tell, this is not documented (shocking!), but the debug messages (see #4606) point to the fact that command-line apps should not use `MTLCreateSystemDefaultDevice()`.  This just uses `MTLCopyAllDevices()` as fallback when `MTLCreateSystemDefaultDevice()` fails, and selects the first device returned.

Fix Metal on macOS Catalina

---

src/runtime/metal.cpp

Use `firstObject` instead of `objectAtIndex:` so if the `NSArray` of devices is empty, it'll just return nil.
CC @steven-johnson

Alternative solution for #4668

---

Makefile

Some crosscompilers don't understand this; allow us to selectively override with (e.g.) GCC_ARCH_FOR_TESTS=armv7-a

Allow overriding `-march=native`

---

test/correctness/atomics.cpp

Cherry-picked from #4665 to unbreak the bots

Disable CudaVectorize atomics test to unbreak windows build

---

src/Function.cpp

Capture it by const-ref instead.

Don't make a pointless copy of a map

---

.clang-tidy
Makefile
src/AddImageChecks.cpp
src/Buffer.h
src/IR.cpp
src/IROperator.cpp
src/IROperator.h
src/Simplify_Add.cpp
src/Simplify_And.cpp
src/Simplify_Div.cpp
src/Simplify_EQ.cpp
src/Simplify_LT.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Mod.cpp
src/Simplify_Mul.cpp
src/Simplify_Not.cpp
src/Simplify_Or.cpp
src/Simplify_Select.cpp
src/Simplify_Sub.cpp
src/Util.h
src/runtime/HalideBuffer.h

Given the last clang-tidy PR added std::moves everywhere and was met
with a meh, how about a PR that removes pointless std::moves?
These std::move were all from const args or being passed to things that
expect a const ref arg, so they just made a copy anyway and the
std::move gave a false sense that no copy occurred.
This PR either removes the std::move, or fixes the reason that a copy
was occurring. The reasons were:
- A missing move assignment operator for Buffer<>
- some of the things in IROperator taking const-refs where most didn't,
but ~all definitions assumed things were passed by value and used
std::move internally. Just made these uniformly accept Exprs by value.
- LetStmt::make takes a string by const ref
- The simplifier cleverly passing rvalues to mutate, even though mutate …

Remove pointless std::moves, or make them not pointless

---

src/Simplify_Div.cpp

After the change to the semantics of division, this rewrite rule is incorrect when y = 0. Deleting this rule should fix issue #4638.

delete rewrite rule that is incorrect under new div by zero definition

---

src/Util.h

This const prevents the default move constructor from moving the member, because you can't move from something const. This in turns makes the noexcept a lie whenever T is something with a constructor that might throw an exception (e.g. std::string, which might allocate).

Remove const that messes up move constructor

---

src/CodeGen_ARM.cpp

Some arm-specific intrinsics got removed (in favor of portable LLVM versions) and we didn't notice because the armbots never tested on trunk.

Fix LLVM10/11 breakage on arm32 (Issue #4690)

---

apps/autoscheduler/CMakeLists.txt
src/CMakeLists.txt
test/generator/CMakeLists.txt

Some of the targets that relied on these didn't list them in their DEPENDS (so build order variance could break).
All of them should have used $<TARGET_FILE> for the COMMAND setup; the fact that it worked currently was basically luck.
(Note: the need to $<TARGET_FILE> will go away once the `cmake-modern` PR lands -- the newer CMake version used there changes the behavior -- but until then, this is needed to make some cross-compile targets work.)

Fix deps and COMMAND for binary2cpp and build_halide_h

---

.clang-tidy
src/AsyncProducers.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGL_Dev.cpp
src/CodeGen_PTX_Dev.cpp
src/Generator.h
src/RDom.cpp

This turns on a few checkers for things clang-tidy considers bugprone. They are:
- Calling a grandparent's virtual method instead of the parent 
We did this in a few places, usually when there wasn't an override in the parent class, so it was fine. I think one of them was a bug though - CodeGen of atomics in opencl probably just skipped the atomic node and went straight to the body, because it called the IRVisitor visit override instead of the CodeGen_C override.
- Constructing a string from 0 is UB 
This happened in the unevaluated contexts in the LHS of the Generator operator overrides. Was introduced when we allowed `GeneratorParam<string>`
- sizeof a pointer is considered a code smell, because often you're actually trying to take sizeof an array and failing. In this case it wasn't …

Clang tidy bugprone checkers

---

src/Bounds.cpp

Even when nothing is known about the divisor, integer division can't
produce a result larger in magnitude than the numerator.

Bounds on integer division could be a little tighter

---

test/CMakeLists.txt

cmake 3.14, which is the minimum requirement for build, accepts a single
compiler ID in the CXX_COMPILER_ID expression.

Use CXX_COMPILER_ID with a single ID in CMakeLists.txt

---

src/Simplify_LT.cpp
test/correctness/simplify.cpp

Somehow we were missing these. I found them useful in another branch. The left-hand-side is at least y, and the right-hand-side is at most y, so there's no way the LHS could be strictly less than the RHS.

Add some obviously good rules from the simplifier synthesis work

---

CMakeLists.txt

This disables the useless `parameter passing for argument of type ‘foo’ changed in GCC X.Y` warnings that pollute some build variants. (We've had this set in the Makefile for a long time already.)

Add `-Wno-psabi` to CMake builds

---

Makefile
README.md

Using a script provided by llvm. This makes it way faster to clang-tidy a branch before opening a PR.

Parallelize clang-tidy runs

---

python_bindings/Makefile

Add an rpath to the python module, to make libHalide.so easier to find.
The python test cases run much better with this on my ubuntu 18.04 machine.

Build python module with rpath on linux

---

src/Simplify.cpp
src/Simplify_Internal.h
src/Simplify_Stmts.cpp
test/correctness/simplify.cpp

First, in the following:
```
if (extent > 0) { for (x = 0; x < extent; x++) {...}}
```
The if is redundant and can be removed.
Next, we can fold away `if (likely(true/false))` in the same way we fold
away `if (true/false)`
Finally, we used to transform:
```
for (x = 0; x < min(1, foo); x++)
```
to
```
if (0 < foo)
```
Because a for loop where the extent is at most one is just an if.
However, this is not a good mutation if done in a vectorized loop,
because a for loop with an extent that varies across the vector lanes is
considered a likely-if, and an all-true vectorized case is generated.
This doesn't happen for the regular if. So I just squashed this
transformation if we're inside a vector loop.

Add simplifier rules for for/if combinations

---

apps/conv_layer/process.cpp

The current conv_layer benchmarking code doesn't initialize all of the input buffers (see the changes). This does not really matter but we should probably fix it for pedagogical purposes.

Fix conv_layer initialization

---

src/AutoSchedule.cpp
src/Derivative.cpp
src/ModulusRemainder.cpp
src/RegionCosts.cpp
src/StmtToHtml.cpp
src/Target.cpp
src/Util.cpp

Just a stylistic change. Also added Shuffle to the derivative visitor. It seemed to be missing.

Use internal_error instead of internal_assert(false)

---

.github/workflows/test.yml

It's too easy to back up the queue with multiple commits -- disabling until I get some smarts added back in

Disable automatic GHA tests for now

---

src/AddImageChecks.cpp

by pre-trimming down to the portion of the stmt that actually touches
input/output buffers.
On master, timing add_image_checks for a few apps:
local_laplacian: 16ms
lens_blur: 18ms
interpolate: 11ms
fft: 37ms
On this branch:
local_laplacian: 2.4ms
lens_blur: 11ms
interpolate: 3.5ms
fft: 3.9ms
This change was pulled from #3037

Speed up add_image_checks

---

src/Simplify.cpp
src/Simplify.h
src/Simplify_Call.cpp
src/Simplify_Let.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Select.cpp
test/correctness/simplify.cpp

Some simplifier improvements harvested from #3037. Bundled into a single PR to avoid overloading the bots, but done as separate commits to facilitate bisection. The are:
1) simplify min(x, likely(x)) -> x
I.e. the likely goes away. Augmented with better tracking of bounds of likely expressions. I believe this is more correct than the status quo, because a likely is supposed to mark which branch of the immediately containing min/max/select is the one to optimize for. This may result in fewer partitioned loops than before though.
2) The remove_dead_lets flag for the simplifier is now remove_dead_let_stmts. You always want to remove dead let exprs.
3) Two new rules to simplify select expressions

Simplifier improvements from #3037

---

src/Simplify_LT.cpp
test/correctness/simplify.cpp

In a comparison between two mins, if a term on one side dominates a term
on the other, we can drop it. Consider:
```
min(x, y) < min(z, w)
```
First we'll assume we can statically prove w <= y (e.g. because they are
equal). Then:
```
min(x, y) < min(z, w)
= (x < min(z, w)) || (y < min(z, w))
= (x < min(z, w)) || (y < z && y < w)
= (x < min(z, w)) || (y < z && false)
= (x < min(z, w)) || false
= x < min(z, w)
```
Alternatively if we can prove y < w
```
min(x, y) < min(z, w)
= (min(x, y) < z) && (min(x, y) < w)
= (min(x, y) < z) && (x < w || y < w)
= (min(x, y) < z) && (x < w || true)
= (min(x, y) < z) && true
= min(x, y) < z
```
You can do the same reasoning for max by flipping the sign on everything.
These rules were helpful #3037. Carving them out into a separate PR
here. The basic form …

Add simplifications of min(x, y) < min(x, z), and similar

---

src/runtime/hexagon_remote/Makefile

- allows specifying only SDK_ROOT in a buildbot to point
to where SDK storage is located without naming a specific
SDK revision
- needed to minimize buildbot script complexity when building
multiple release streams that use differing SDK revisions
- no change in behavior if SDK_ROOT env var is not present

Add SDK_ROOT control to hexagon_remote/Makefile

---

src/Bounds.cpp
src/BoundsInference.cpp
src/StorageFolding.cpp
test/correctness/CMakeLists.txt
test/correctness/non_nesting_extern_bounds_query.cpp

TL;DR: This is an improvement from #3037 / #4713 that can be tested and
checked in independently. It removes one type of magic name usage.
Allocation bounds inference (well, boxes_touched) relies on magic names
in its handling of getting the min/max out of a bounds query result. It
just lifts them out of their containing scope (see the deleted code in
Bounds.cpp below), assuming a bounds query buffer of the same name also
exists in the containing scope, and also assuming that the result of
that outer bounds query was a valid interval containing the result of
the inner bounds query. Yuck. I removed that special handling from
boxes_touched, and instead explicitly clamped the inner bounds query
result to be within the outer region required, which comes from the
outer bounds query. That gives …

Instead of just assuming bounds query results can be lifted, enforce nesting

---

python_bindings/correctness/iroperator.py
python_bindings/src/PyIROperator.cpp
src/IROperator.cpp
src/IROperator.h
test/correctness/mux.cpp

I had a sudden horrifying vision of someone having to write:
`mux(c, {f(x, y)[0], f(x, y)[1], f(x, y)[2]})`
So this lets mux take a tuple as the second argument. Also needed to add
an initializer list overload to prevent ambiguity.
I still think it would be a good idea to permit f(x, y)[c], for
uniformity with Tuple's existing operator[] for integers. I can imagine
people wondering why they can't just pass an Expr there.

mux accepts tuples

---

src/Associativity.cpp

The `equal` in associativity proving is operating on non-CSE'd expressions, making it exponentially slow. This PR changes it to `graph_equal`. I observed significant speedup in some huge expressions generated by autodiff when calling prove_associativity(30s -> 0.02s).

Use graph_equal instead of equal in prove_associativity

---

src/Monotonic.cpp

Currently is_monotonic treats calls with constant args as pure. But impure calls could return a different value on each call, even if they have the same args, so they shouldn't be considered constant.

Calls can't be considered constant if they are impure

---

src/AllocationBoundsInference.cpp
src/Bounds.cpp
src/IR.cpp
src/IR.h
src/ScheduleFunctions.cpp

This is another independent improvement carved off of #3037 / #4713
Allocation bounds inference for a Func foo depends on the magic names
foo.x.min/foo.x.max at the realization site. The only reason it needs
them is to ensure it knows that an extern stage is going to write to the
whole region required. We can just tell it that earlier instead with a
marker in the IR that says "you should treat this marker as a write to
this buffer over this region". Presto, no magic name dependence.
This is desirable because it will let us do more types of IR transformation
before allocation bounds inference.

Don't depend on magic names in allocation bounds inference

---

src/Scope.h
src/UniquifyVariableNames.cpp
src/UniquifyVariableNames.h
test/internal.cpp

Currently uniquify_variable_names only works on exactly the kind of
duplicate names we tend to generate in bounds inference, and only if you
run it on the entire stmt. In other circumstances it does odd things
(e.g. attach negative integer suffixes to free variables!), and we risk
introducing bugs, as I discovered in another PR.
This PR fixes uniquify_variable_names to do the right thing in the
general case, and adds tests.
Also added some needed functionality to Scope - you can now query the
number of nested definitions of the same thing, and you can move a
Scope.

Generalize uniquify_variable_names

---

tutorial/figures/generate_figures_5.sh

The generation of the row-major gif example in lesson 5 is using an old syntax which results in an error.

Fix usage of HalideTraceViz

---

tutorial/figures/generate_figures_5.sh

The `Func` name used in `tutorial/lesson_05_scheduling_1.cpp` in the row-major example is `gradient` and not `gradient_row_major`.

Fix Func name

---

src/Generator.cpp

Took me a while to figure out how to generate a Python extension from a generator. I suggest adding it to the help text.

add python_extension to generator's usage help text

---

src/BoundsInference.cpp
test/correctness/non_nesting_extern_bounds_query.cpp

This avoids generating buffers with negative extents in cases where the
reply to the inner bounds query doesn't overlap the outer bounds query
at all, and also, by giving an upper *and* lower bound to these
expressions, avoids a type of unbounded access discovered here:
https://github.com/halide/Halide/pull/3037#issuecomment-604136412

Do a full clamp of inner bounds to an outer query

---

src/AlignLoads.h
src/Argument.h
src/BoundaryConditions.h
src/Buffer.h
src/CodeGen_LLVM.h
src/Debug.cpp
src/Definition.h
src/Error.cpp
src/Expr.h
src/Float16.h
src/Function.h
src/HexagonAlignment.h
src/HexagonOptimize.h
src/IR.h
src/IRMatch.h
src/IRVisitor.h
src/Interval.h
src/Introspection.h
src/IntrusivePtr.h
src/LLVM_Output.h
src/Lambda.h
src/ParallelRVar.h
src/Param.h
src/Scope.h
src/Substitute.h
src/Target.h
src/Tuple.h

Reduce some unnecessary .h file inclusion -- this was done semi-manually, by compiling with the gcc `-H` flag, then massaging the output to find the highest-used headers, then tweaking to reduce the top scorers. (This could be repeated more, but this felt like a good stopping point.)

Simplify #include file nesting

---

src/Func.cpp
src/Introspection.cpp
src/Pipeline.cpp
src/Target.cpp
src/WasmExecutor.cpp

According to some testing with clang's `-ftime-test` flag, this is (by far) the most expensive header in terms of compiletime that we have; this removes it from files that have no apparently use for it at all.
(It may be that other files that need it could get by with a smaller subset of what it includes.)

Remove unnecessary #includes of LLVM_Headers.h

---

src/Scope.h

This method is instantiated a lot, so a couple of minor tweaks:
- skip a branch by unconditionally setting _empty=false in all cases
- use std::move for the push_back, to avoid a copy in case the type of object is movable

Minor optimization in SmallStack::push

---

src/runtime/HalideBuffer.h

Currently, if someone forgot to `copy_to_host` before accessing the Buffer in the host, this assertion would be triggered:
```
assert((!v || !device_dirty()) && "Cannot set host dirty when device is already dirty.");
```
This message is not very friendly to Halide newbies (like me). I propose changing it to
```
assert((!v || !device_dirty()) && "Cannot set host dirty when device is already dirty. Call copy_to_host before accessing the buffer from host.");
```
Ideally we also want to print out the name of the buffer, but doing it inside an assertion with zero overhead might be difficult.

Improve set_host_dirty error message

---

.gitignore
Makefile
src/CMakeLists.txt
src/Expr.cpp
src/Expr.h
src/IROperator.cpp

Expr.h is included by ~everything in Halide, so we want to minimize its complexity. There are several nontrivial function bodies in Expr.h that are likely too large to inline anyway, so add Expr.cpp and move them there. (Also move the Range ctor there since that's where it belonged anyway.)
Linux build shows a slight decrease in libHalide size (110872632 -> 110830336). Didn't try to measure performance changes.

Add Expr.cpp, move nontrivial function bodies into it

---

.gitignore
src/Debug.h
src/Error.cpp
src/Error.h
src/Function.cpp

It was included by Debug.h and Error.h (and thus ~everywhere), but is only needed in a handful of .cpp files.

Remove unnecessary includes of Introspection.h

---

src/Expr.h
src/IR.h
src/IRMatch.h
src/IntrusivePtr.h
src/ModulusRemainder.h
src/Prefetch.cpp
src/Prefetch.h
src/PrefetchDirective.h
src/Schedule.h
src/UniquifyVariableNames.cpp

Remove includes that are just plain unneeded, adding forward decls as needed.
Split PrefetchDirective.h into its own header since that's the only thing that IR.h needed from Schedule.h.
Some drive-by work on related headers too.

Reduce includes in IR.h and Expr.h

---

Makefile
src/AddImageChecks.cpp
src/AllocationBoundsInference.cpp
src/BoundsInference.cpp
src/CMakeLists.txt
src/CPlusPlusMangle.cpp
src/ExternFuncArgument.h
src/FindCalls.cpp
src/Func.cpp
src/Func.h
src/Function.cpp
src/Function.h
src/IRVisitor.cpp
src/InferArguments.cpp
src/InjectHostDevBufferCopies.cpp
src/Inline.cpp
src/Param.h
src/ParamMap.h

Most that need Function don't need ExternFuncArgument,  but putting both in Function.h adds extra includes (eg Buffer.h) in places that it isn't needed. Split it out into a separate file and forward-declared in all headers (except Param.h, which will be addressed in the future).

Add ExternFuncArgument.h

---

Makefile
src/CMakeLists.txt
src/DeviceAPI.h
src/Expr.h
src/Schedule.h
src/Target.h

Nothing in Expr.h needs it, and at least one of the few users (Target.h) didn't need anything else in Expr.h.

Move DeviceAPI into its own header file

---

src/AddImageChecks.cpp
src/BoundSmallAllocations.cpp
src/Bounds.cpp
src/Bounds.h
src/Prefetch.cpp
src/RegionCosts.cpp
src/SplitTuples.cpp

Add `empty_func_value_bounds()` instead of default-constructing; this reduces libHalide.so on x86-64-linux by about 4k. (Hey, I said it was tiny.)
Also, drive-by cleanup in Bounds.h.

Tiny size optimization in Bounds.h

---

Makefile
src/Argument.h
src/CMakeLists.txt
src/Closure.h
src/LLVM_Output.h
src/Module.h
src/RDom.h
src/Realization.cpp
src/Realization.h

Buffer.h is a heavyweight file and should only be included when forward-declarations will not suffice.
Also, a drive-by addition of Realization.cpp.
(Note, this is additive to https://github.com/halide/Halide/pull/4823 rather than master)

Remove unnecessary includes of Buffer.h

---

src/Interval.cpp
src/Interval.h

Saves ~12k from libHalide.so on x86-64-linux; timing on local_laplacian.generator doesn't show any performance impact.

Move most Interval method bodies to the .cpp file

---

src/Scope.h

pushing something onto a scope currently copies it. If we accept rvals appropriately then we can avoid those copies when pushing an rval (e.g. scope.push(name, expr_a + expr_b))
This also makes it possible to use scopes with non-copyable types as values. 
Speeds up lowering about half a percent on local laplacian. Increases the size of libHalide by two pages (8k), so I guess the speed-up is due to inlining.

Reduce number of copies in Scope::push

---

src/ParamMap.cpp
src/ParamMap.h

This is minor, but I'm not sure of correctness, so I want it considered separate from some other changes I want to make:
The set() methods don't appear to need a non-const-ref to the buffer; AFAICT the only thing they do with it is pass it to Parameter::set_buffer(), which takes a const-ref to Buffer... which then internally just copies it.
Changing to const-ref allows us to stop implying there's a possible change in-pace to the buffer (which there never was) and remove the templated overload (since Buffer<T> -> Buffer<void> automatically for const ref).

Tweak to ParamMap API

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp

The existing "support" was useless, since there was no way to construct a *useful* ParamMap in our Python bindings. Removing for now to clear the way for subsequent ParamMap work.
(Cherry-picked from https://github.com/halide/Halide/pull/4834)

Remove ParamMap from Python Bindings

---

src/Pipeline.h

Stuff that should have been private was public. Not sure how or why.

Fix visibility in Pipeline.h

---

src/Bounds.cpp

The current implementation recurses to let_bounds.size(), but a simple loop has the same result.

Remove recursion in trim_scope_pop()

---

src/Bounds.cpp

The current implementation doesn't try to avoid dupes, which can lead to size explosion in some cases (e.g. a case where ~200 unique children added ~16000 entries to the Scope).

Avoid adding duplicate children in trim_scope_push

---

src/Bounds.cpp

The error message I get (LLVM and clang from today's HEAD):
error: loop variable 'l' creates a copy from type 'const Halide::Internal::BoxesTouched::LetBound' [-Werror,-Wrange-loop-construct]

clone of #4845 for buildbots

---

src/Bounds.cpp

The error message I get (LLVM and clang from today's HEAD):
error: loop variable 'l' creates a copy from type 'const Halide::Internal::BoxesTouched::LetBound' [-Werror,-Wrange-loop-construct]

fix build (const& vs. const) with LLVM/clang 11 and -Werror

---

src/Expr.h
src/IRMatch.h
src/Simplify.cpp
src/Simplify_Add.cpp
src/Simplify_EQ.cpp
src/Simplify_LT.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Not.cpp
src/Simplify_Or.cpp
src/Simplify_Sub.cpp
test/correctness/simplify.cpp

For every commutative binary op, we know that the weaker IR node is on the right, because the simplifier does that before applying any rules using should_commute. We also normalize >= and > to <= and <. 
We should never make a right-hand-side that doesn't obey these constraints. It just makes more work for the simplifier.
This PR deletes 8 simplifier rules that could never have matched. The checks are done at compile-time using static asserts.
@jn80842

Require that rewrite rules are in canonical form

---

src/Bounds.cpp

#4839 fixed let_bounds in trim_scope_push to use topological order instead of a redundant depth-first traversal of the entire graph. However, by printing out the order of the let_bounds array before and after we made that change (something I should have done with the original PR), I discovered that we actually want *reverse* topological order.
Turns out nothing in the public test suite was sensitive to topological order, but in the add_image_checks_after_bounds_inference branch the compute_with test is.

We want reverse topological order for let bounds

---

src/SimplifyCorrelatedDifferences.cpp
src/Simplify_Add.cpp
src/Simplify_Min.cpp
src/Simplify_Sub.cpp
src/Solve.cpp
test/correctness/CMakeLists.txt
test/correctness/shadowed_bound.cpp
test/correctness/simplify.cpp

This PR carves off some independently mergeable pieces from #3037. It makes simplify_correlated_differences more aggressive, adds some new simplifier rules, and adds some division handling to solve_expression. 
Also includes #4849

Add image checks simplifier changes

---

src/AutoSchedule.cpp
src/CPlusPlusMangle.cpp
src/CodeGen_Hexagon.h
src/HexagonOptimize.cpp
src/Pipeline.h
src/RegionCosts.cpp
src/RegionCosts.h
src/Simplify_Internal.h
src/Solve.cpp

These were found with a clang-tidy checker, but the clang-tidy checker
also suggested adding const to a bunch of places where it would be
technically correct but misleading due to const not being transitive
(e.g. mutating a member via a pointer).

Add const to some methods that can be const

---

src/LLVM_Runtime_Linker.cpp
src/LLVM_Runtime_Linker.h

This addresses an issue seen when building with Clang-for-Windows (the Chrome toolchain): when building AOT code (but not the runtime), ensure that all the 'weak' llvm::Functions are remarked as non-weak. The problem this addresses is that when we generate a call to one of the external-weak functions (e.g. `halide_string_to_string`), LLVM will declare that symbol as .weak -- on Unixy systems this is fine, but on Windows (where weak symbols don't exist), you can end up with multiple non-weak references to the same symbol, causing linkage to fail.
This fix *could* be made Windows specific, but I'd argue that the caller of an extern Func shouldn't know or care about the eventual weakness of the linked-in symbol, so we just de-weakify them for all platforms (I haven't found any apparent …

Remove 'weak' from extern-Function declarations in AOT

---

src/Simplify_Add.cpp
src/Simplify_EQ.cpp
test/correctness/simplify.cpp

The deleted rules try to make negative constants positive, but don't
reduce the total op count, and replace an addition with a subtraction,
which doesn't count as a strength reduction.
Making negative constants positive may be defensible as a strength
reduction, but other rules may make positive constants negative again,
and elsewhere we treat replacing subtraction with addition as a strength
reduction. So we were unable to prove that these rules don't cause
cycles with these other rules (and hence infinite recursion). It would
be good to just delete them if possible.
In the open source tests, this required adding a few more variants of an
EQ rule on selects. These were formally verified. In the strength
ordering the new rules are cycle-free, even though they increase the op
count in two …

Delete six dubious simplifier rules

---

src/PythonExtensionGen.cpp
src/PythonExtensionGen.h

Add calls to PyBuffer_Release() where appropriate.
Add a buffer parameter to _convert_py_buffer_to_halide, so the caller can release it later.

Fix a leak in python extension wrapper code (Issue #4859)

---

python_bindings/correctness/rdom.py
python_bindings/src/PyRDom.cpp

This allows indexed access to the RVars contained by an RDom, just like the C++ API.

Add RDom[i] method to Python bindings.

---

src/Simplify_Call.cpp
test/correctness/simplify.cpp

So this should be an overflow IR node instead of being an eager user_assert.
The specific case was a can_prove(x << y) substituting in random values
for y when HL_DEBUG_CODEGEN>0 to probe for counterexamples. Some of
these random values were greater than the bit-size of x.

Internal compiler code can introduce shifts by greater than the type size

---

CMakeLists.txt

When LLVM was built with it, the -stdlib=libc++ flag would get passed to
correctness_plain_c_includes, which is (correctly) only using the clang
C compiler driver, not clang++, where this is an invalid option.
Since CMake doesn't seem to have per-language options apart from
CMAKE_CXX_FLAGS which people discourage from directly modifying,
we use a conditional instead of the string itself.
Note that passing the option to the linker is fine as is.

fix build when -stdlib=libc++ was passed into the plain C test

---

src/Simplify_Div.cpp
test/correctness/simplify.cpp

Several of these division rules weren't strength reducing - they created
more ops (or stronger ops) than they removed.
This commit tries just adjusting them to be strength-reducing. I'm a
little nervous of it because it means in (x*4 - y)/2 we no longer move
the x out of the numerator. Needs thorough testing.

Adjust simplifier rules so that they're provably cycle-free

---

src/runtime/metal.cpp

Should fix reported iOS link error-- my device still _seems_ to work fine using the previous approach, but since this API is not supposed to be on iOS, we should use this approach anyway.

Switch to using dlsym for MTLCopyAllDevices()

---

src/RDom.cpp

This is apparently a warning on some compiler versions. See: https://stackoverflow.com/questions/31555584/why-is-clang-warning-suggest-braces-around-initialization-of-subobject-wmis

Fix std::array initialization

---

Makefile
halide.cmake
python_bindings/src/PyEnums.cpp
src/CMakeLists.txt
src/CompilerLogger.cpp
src/CompilerLogger.h
src/Generator.cpp
src/Module.cpp
src/Module.h
src/Simplify.cpp
src/SimplifyCorrelatedDifferences.cpp
src/SlidingWindow.cpp

Up to now, we've typically gathered metadata about Halide compilation on an ad-hoc basis (e.g. via debug() statements); this adds a Telemetry output to Halide to allow us to gather data in a more structured way, so that we can do batch analysis of things like Simplifier rules more easily.
This is modeled as a Generator output for now (though it could be used manually with the JIT if desired); the `telemetry` output is a JSON file that contains basic information about the Generator being driven, along with information about:
- Expressions that failed `can_prove` (including a text version of the original and failed version)
- Loop vars that are non-monotonic
- Eventually, the usage rate for each Simplifier rule (this requires some additional scaffolding in the Simplifier to enable)
The …

Add basic Compiler Logging engine to Halide compiler

---

src/runtime/metal.cpp

Followup to https://github.com/halide/Halide/pull/4877 -- `halide_get_symbol` isn't defined in our iOS runtime; it might be useful to add it there, but the bottlenecking is unnecessary here, so a spot-fix should be simpler.

Call dlsym() directly in runtime/metal.cpp

---

src/Introspection.cpp

The clang-tidy presubmit didn't see it because it's conditionally compiled.

Run clang-tidy on Introspection.cpp

---

src/Bounds.cpp
src/Monotonic.cpp
test/correctness/CMakeLists.txt
test/correctness/sliding_over_guard_with_if.cpp

No effect in public Halide, but I hear it causes at least one regression
inside Google. The reason for injecting the min/max exprs in the case
where the first arg doesn't vary has since gone away now that we push
producers inside the guard-with-if if statement of a consumer.

Don't inject min/max exprs in bounds of a promise_clamped of constant

---

apps/super_simplify/find_rules.cpp
apps/super_simplify/parser.cpp

- make blacklist.txt a required arg (so it doesn't assume 'current directory'
- add error-checking to the iostream open() calls to ensure that failure to open files isn't overlooked

error-checking fixes

---

src/StorageFolding.cpp
test/warning/CMakeLists.txt
test/warning/sliding_vectors.cpp

It's generally a bad idea because loads and stores scalarize, but
there's no way in the schedule to turn it off, so you can't write an
optimal schedule for the case in the newly added warning test where you
want sliding but not folding. This PR makes folding opt-in in this case
instead.
When automatic folding is rejected due to this test, we emit a warning
that includes the schedule to use to explicitly request the folding that
used to occur.
Longer term it would be good to disable automatic folding entirely. This
PR can be seen as a trial of that in one specific case.

Don't automatically fold storage along vectorized dimensions

---

.clang-tidy
python_bindings/CMakeLists.txt
python_bindings/src/PyArgument.cpp
python_bindings/src/PyBoundaryConditions.cpp
python_bindings/src/PyBuffer.cpp
python_bindings/src/PyError.cpp
python_bindings/src/PyFunc.cpp
python_bindings/src/PyIROperator.cpp
python_bindings/src/PyInlineReductions.cpp
python_bindings/src/PyLambda.cpp
python_bindings/src/PyScheduleMethods.h
python_bindings/stub/PyStubImpl.cpp

Also, drive-by upgrade to pybind11 v2.5

Fix clang-tidy errors in python_bindings

---

apps/super_simplify/find_rules.cpp
apps/super_simplify/super_simplify.cpp

- add a sanity check in super_simplify to bail from the loop if we get too many counterexamples (preventing missed pathological cases from hanging)
- remove unnecessary lock in find_rules loop
- make BLACKLISTING logging debug(1) instead of debug(0)

minor super_simplify fixes

---

python_bindings/requirements.txt
python_bindings/tutorial/lesson_02_input_image.py
python_bindings/tutorial/lesson_07_multi_stage_pipelines.py

Ubuntu 20.04 LTS packages slightly older versions of two Python dependencies:
* `python3-imageio` **2.4.1-3**. Unfortunately this is the most recent version that conservatively rejects numpy-compatible types. This PR wraps our buffers in two tutorials with `np.asanyarray()`.
* `python3-pybind11` **2.4.3-2build2**. This version works fine for our purposes.
It would be nice to support building Halide against these versions so that building with a virtual environment is optional.
The changes to the requirements file ensure that testing is done against these versions when running in a virtual environment.

Support Ubuntu 20.04 LTS

---

src/LICM.cpp

LICM is prone to making a bit of a mess. I found it can be tamed by not
letting it sink constants to the bottom of an expression, and by running
CSE before grouping loop invariants instead of after to stop it from
reassociating things in way that break up common subexpressions.
This provides small speedups on several of the apps. The largest gain is
1-2% on local_laplacian.

Keep constants outermost in LICM

---

src/Simplify.cpp
test/correctness/simplify.cpp

Previously the simplifier understood that assert(x >= 0) meant that
future uses of x have an lower bound of 0. However it didn't realize
that it could learn the same from assert(x >= max(y, 0))
This meant that 
assert(x >= max(y, 0)) 
could generate worse code than the more complex expression:
assert(x >= y && x >= 0)

Teach the simplifier to learn bounds from non-constants

---

src/FuseGPUThreadLoops.cpp
test/correctness/dynamic_allocation_in_gpu_kernel.cpp

By making one global heap allocation per alloc group in the kernel, and then only
coalescing those allocations that have matching type.
This should also work for d3d, if someone wants to generalize the == OpenGLCompute checks.

Enable dynamic-sized allocations in kernels for openglcompute

---

src/BoundsInference.cpp
test/correctness/compute_with.cpp

Currently it always uses arg list of the parent function, which is not correct if they differ for the fused function.

Use correct arguments list in the bounds inference for fused functions

---

src/Simplify_Div.cpp
test/correctness/simplify.cpp

PR #4896 reduced a rule that triggered when a term from the numerator that was a multiple of the denominator to only triggering in the case where it was equal to the denominator. This was done to respect the reduction order and keep the simplifier cycle free. We forgot about the case where the
term is multiplied by the negative of the denominator (e.g. (x*-2 - y)/2). This can also be pulled out without breaking the reduction order, because the multiply goes away.
Z3 was unable to verify this, but it was also unable to find a counterexample, and it looks correct to me.

Restore division rule

---

src/IRMatch.h
src/Simplify.cpp
src/Simplify_Internal.h
test/correctness/simplify.cpp

This adds a simple way to disable all rules using can_prove via an env var (useful in this branch).
Also, a drive-by fix to allow correctness_simplify to pass.

add HL_DISABLE_CAN_PROVE_RULES

---

tutorial/lesson_09_update_definitions.cpp

The definition of `consumer` and `consumer_2` did not align in the Case 4 example.

Fix tutorial 9. Align function definition.

---

src/CompilerLogger.cpp
src/CompilerLogger.h

- improve record_matched_simplifier_rule() to save the Exprs matched (rather than just a count) [poached from super_simplify_v2 branch]
- properly anonymize the Exprs in matched_simplifier_rules when requested
- properly escape JSON values that contain \ or " characters (which can happen for Exprs that contain `stringify`)

Fixes/improvements for CompilerLogger

---

src/Solve.cpp

It was mutating min(x - y, x - z) to x - min(y, z), when it should be x - max(y, z). No idea how this wasn't causing crashes all over the place.
We really should be using an IR rewriter here so we can verify these
transformations.

Fix nasty bug in solver.

---

Makefile
src/Generator.cpp
test/generator/stubtest_aottest.cpp
test/generator/stubtest_generator.cpp
test/generator/stubuser_aottest.cpp
test/generator/stubuser_generator.cpp

In general, they did, but Generator Stubs were broken for statically-declare Buffers.

Generator inputs/outputs should allow float16/bfloat16

---

src/FuseGPUThreadLoops.cpp

Fix capture by reference of the temporary string.

Fix capture by reference of temporary

---

apps/c_backend/Makefile

The gcc 5.x compiler that our arm64 bots use will crater with an internal compiler error when compiling ths; upgrading gcc on the bots is tedious and error prone (especially when I can't physically access them in case something goes wrong), so as a short-term fix, just crank down the optimization for this app (since its performance isn't critical anyway)

apps/c_backend O3 -> O2

---

apps/cuda_mat_mul/mat_mul_generator.cpp
apps/iir_blur/iir_blur_generator.cpp
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_OpenGL_Dev.cpp

- Give apps/iir_blur a fallback GPU schedule so that non-cuda backends won't fail
- add more user-friendly failure messages if gpu_lanes() is requested for a backend that doesn't support it
- add check to apps/cuda_mat_mul that cuda is enabled (already done in the makefile but this makes it more obvious in the code)

gpu_lanes() cleanup

---

apps/linear_algebra/benchmarks/macros.h

If building with ENABLE_FTZ_DAZ defined, it only built on x86 systems. Add relevant code for ARM to enable the equivalent modes.

Fix apps/linear_algebra for ARM

---

test/correctness/partition_loops_bug.cpp

Verified this bug no longer occurs on 32-bit (arm, at least)

LLVM 3.6.2 isn't supported any more

---

src/JITModule.cpp

If we can't get the address of a symbol, it's likely that we're going to crash later on anyway when we try to jump to a null address, which is hard to debug; changing to an assert-fail makes the issue easier to debug.
(Note that I *think* this is always a fatal error, but it may be that this needs to be a warning instead in some cases.)

Add assert-fail in HalideJITMemoryManager::getSymbolAddress()

---

apps/cuda_mat_mul/runner.cpp

Otherwise it fails with inscrutable error messages later.
(See also: https://github.com/halide/Halide/issues/4965)

cuda_mat_mul should skip test for Cuda < 5.0

---

apps/autoscheduler/FunctionDAG.cpp
apps/autoscheduler/LoopNest.cpp
src/CodeGen_X86.cpp
src/Type.h
src/runtime/mini_qurt.h
test/correctness/gpu_large_alloc.cpp

I don't know how/why the master branch isn't clean this way. (Maybe I have a different clang-format locally?)

Fix clang-format issues

---

src/CodeGen_C.cpp
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp

This PR makes it so CodeGen_C uses some C++ trickery to avoid unused declaration warnings, but I can't find a reliable way to avoid unused variable declarations in OpenCL C. I think we should just let unused declarations be in OpenCL C. I doubt any OpenCL implementations treat them as errors, and warnings should never be visible.
Fixes #4918

More portable handling of unused declarations in CodeGen_C

---

src/AutoScheduleUtils.cpp
src/Func.cpp
src/Function.cpp
src/IRPrinter.cpp
src/IRPrinter.h
src/Schedule.h
src/ScheduleFunctions.cpp

This makes a .compute_with() error message easier to read.
Before:
`Invalid compute_with: types of dim 0 of f_intm.s1(r$z is 2) and f_intm$1.s1(r$z is 1) do not match.`
After:
`Invalid compute_with: types of dim 0 of f_intm.s1(r$z is ImpureRVar) and f_intm$1.s1(r$z is PureRVar) do not match.`

Add stringification for Dim.dim_type enum.

---

src/Solve.cpp

Over random schedules on lens blur reduces average peak memory by a full
third! No effect on the other apps.

Add two new rewrite rules to the solver

---

README.md

A fresh checkout will need to run the bootstrap script to build `vcpkg.exe`.

README: add line for booststrapping vcpkg

---

Makefile

Makefile Doxygen output now appears in `share/doc/Halide`, which removes conflict with top-level `doc` and conforms to usual Linux directory layout in `/usr`.
Clean target now removes generated Doxyfile and share directory.
Fixes #4991

Fix Doxygen config and output paths in Makefile.

---

apps/linear_algebra/tests/test_halide_blas.cpp

One of the tests is flaky on windows as-is. Hopefully increasing the error tolerance will fix it.

Increase error tolerance on blas tests

---

Makefile

Instead of assuming lines come in a specific format, looks for .a files followed by .o files in the same line.

More robust ar script for scraping object files

---

apps/linear_algebra/src/blas_l3_generators.cpp

Vectors of size 2 aren't compatible with the rest of this schedule. Set
the min vector size to 4.

Fix linear algebra schedules for old x86

---

src/SplitTuples.cpp
test/correctness/CMakeLists.txt
test/correctness/atomic_tuples.cpp
test/correctness/rfactor.cpp

If tuple components have no hazards between them, they can be computed
one after another in separate atomic blocks instead of in a single
combined atomic block. This lets us use atomic adds or CAS loops more
often and mutexes less often.
As a side-effect, this also means that update definitions that don't
modify one of the tuple components now entirely elide that store as a
no-op (see the change to the rfactor test).
This is part of the atomic_vectorization branch that can be separately merged.

Lower tuples to separate atomic nodes where possible

---

src/LowerWarpShuffles.cpp

The args to nvvm.shfl.up were wrong
This doesn't actually get buildbot coverage, because it requires a newer GPU than the buildbots have. Tested locally with llvms 9, 10, and master

Fix args to nvvm.shfl.up

---

src/runtime/d3d12compute.cpp
src/runtime/opencl.cpp
src/runtime/printer.h

This fixes several test failures on master with expected-label-after-instruction 
I tracked the error down to instances of large StackPrinter objects in the d3d12 runtime. We probably shouldn't be making large stack allocations anyway, so I avoided these by in one case using malloc, and in the other case (tracing) using a global buffer guarded by a spinlock (trace was already using globals guarded by the same spinlock).
Fixes #4996

Large stack printer objects break llvm debuginfo

---

dependencies/llvm/CMakeLists.txt

Fixes the build with -DLLVM_USE_SHARED_LLVM_LIBRARY=ON to
actually use the dynamic build (libLLVM.so). Relevant
for LLVM builds with -DLLVM_BUILD_LLVM_DYLIB=ON.
Tested with LLVM v10.0.0. I did not test on LLVM v9; this PR does not change
the path for LLVM_USE_SHARED_LLVM_LIBRARY=OFF, but if linking
against shared LLVM library did work in v9, then need to test this PR in v9
for regression).
There are two issues that prevent a build against LLVM shared lib:
1. cmake failure:
CMake Error at /usr/lib/llvm/10/lib64/cmake/llvm/LLVM-Config.cmake:145 (message):
Target NVPTX is not in the set of libraries.
Call Stack (most recent call first):
/usr/lib/llvm/10/lib64/cmake/llvm/LLVM-Config.cmake:270 (llvm_expand_pseudo_components)
dependencies/llvm/CMakeLists.txt:141 …

cmake: llvm: fix linking against LLVM shared lib

---

src/IRPrinter.cpp
src/Simplify_Add.cpp

These cancellations were necessary to get tight bounds in places. 
Also I deleted one parens too many in the previous paren-deletion PR

New simplifier rules necessary for the gpu autoscheduler

---

apps/CMakeLists.txt

Hoping this will help us track down flaky Windows failures.

Enable verbosity in apps builds

---

src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.h
src/CodeGen_OpenGL_Dev.cpp
src/CodeGen_OpenGL_Dev.h

These are the only two overrides of `visit(Cast) from GLSLBase and they both have identical implementations; combine them into one and move into GLSLBase to save code.

Combine visit(Cast) for GLSL and OpenGLCompute

---

src/CodeGen_C.cpp
src/CodeGen_OpenGL_Dev.cpp

It was emitting as a float, which is *never* correct, since absd() is only used for int or uint types. (This happened to work before because GLSL was previously also incorrectly using float for uint in some cases.)
Also did a drive-by removal of code in Codegen_C that recapitulated the logic from IROperator.cpp; maybe the type field of absd() was incorrect at some point in the past, but this calculation seems redundant and wrong now.

Fix codegen for absd() in GLSLBase

---

src/Associativity.cpp

Minimal fix for #5017 
Longer term we need to be smarter about our representation of +=, and other associative definitions.

Make it harder for the associativity test to get confused

---

src/runtime/metal.cpp
src/runtime/synchronization_common.h
src/runtime/thread_pool_common.h
src/runtime/write_debug_image.cpp
src/runtime/x86_cpu_features.cpp

Runtime code that will be instantiated for OSX/iOS needs to ensure that there are no plain 'inline' functions -- they must be either WEAK or __attribute__((always_inline)) -- otherwise, some compiler configurations can produce the error above. (Note that this also applies to member functions that are defined inline, even without an explicit 'inline' keyword).
(Note also that the vagaries of C++ mean that declaring a ctor implies that a dtor will be auto-created; in some of these we must explicitly declare the dtor so that it too is always-inlined, even if it is empty...)

Fix some "MachO doesn't support COMDAT" issues in runtime

---

src/LICM.cpp

loop invariant code motion sometimes likes to lift long chains of x + 1, x + 2, x + 3, x + 4, etc. This is silly because often those are addresses, and constant offsets are usually free on loads and stores, so all you're doing is increasing register pressure. This PR tweaks it to leave those in the innermost loop.
Mostly this just cleans up the IR, because LLVM is capable of resubstituting these constant offsets too. Might have an effect on GPU kernels where the values lifted have to be packed into a closure, but I was unable to find a case where it mattered.
branch name is a misnomer - that was another approach I was trying.

Don't lift constant integer offsets

---

Makefile
src/AddAtomicMutex.cpp
src/AssociativeOpsTable.cpp
src/CSE.cpp
src/Deinterleave.cpp
src/Func.cpp
src/IROperator.cpp

Unrelated pieces of the atomic vectorization PR which can be merged separately.
1) Make lossless_cast more aggressive. It now looks through some adds, subs, and muls too
2) You can fuse a PureRVar and an ImpureRVar now. You get an ImpureRVar.
3) Some logic in Deinterleave.cpp handling shuffles was needlessly complex
4) 16-bit floats were never added to associative ops
5) CSE had an error message that benefited from also printing the Expr
6) The Makefile wasn't passing LLVM_VERSION to tests. Some of them care (because expectations about generated code might depend on LLVM version)

atomic vectorization tweaks

---

src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_GPU_Dev.h
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_PTX_Dev.cpp
src/FuseGPUThreadLoops.cpp

This PR attempts to address #4967 by implementing a required parameter for `gpu_thread_barrier()`: a mask that determines the memory fence behavior.
Note that this PR does not increase/decrease the number of barriers inserted.  We may need to revisit the logic that determines when to insert barriers, based on other conversations with @slomp and @abadams.
I'll add or modify a test if this approach seems reasonable to everyone.

Make gpu_thread_barrier() semantics consistent

---

src/CodeGen_LLVM.cpp

Update for a recent LLVM change was incorrect; it compiled but didn't actually work properly. (We should probably run sanitizers on the buildbots...)

Fix broken TSAN code

---

src/runtime/device_interface.cpp

We currently always call copy_to_device() on buffers that need to be on device (with the understanding that it's a no-op if no copy is needed); if the `debug` feature is on, a naive reading might make someone think that needless copy-to-device operations are actually happening. This adds a bit of logging (debug mode only) to make it clearer whether the copy to device actually happened, or if it was skipped because host was not dirty.

Clarify debug logging in copy_to_device()

---

src/CodeGen_GPU_Host.cpp
src/LICM.cpp
test/correctness/CMakeLists.txt
test/correctness/lots_of_loop_invariants.cpp

buffer ids are constrained to be smaller than arbitrary scalar uniforms,
so they should go first in the closure.
Also added a stress-test for lifting out lots of loop invariants, and
disabled LICM completely for GLSL, because it uses magic names
(.varying) for some things.

Put buffers before other uniforms in gl uniform list

---

src/SimplifyCorrelatedDifferences.cpp
src/SimplifyCorrelatedDifferences.h

In particular, this makes warp shuffles much more reliable, because any
dependence of a load or store index on the block id is more likely to
get cancelled out. This PR massively simplifies the generated code for
cuda_mat_mul, and makes it about 30% faster (although it's still
mysteriously 2x slower than cublas on my card).
Also reduces the amount of IR in some other apps very slightly.
Doesn't seem to affect compile times.

It's worth cancelling correlated subexpressions in load/store indices

---

src/BoundSmallAllocations.cpp
src/Lower.cpp
src/LowerWarpShuffles.cpp
test/correctness/CMakeLists.txt
test/correctness/gpu_store_in_register_with_no_lanes_loop.cpp

Consider an allocation that has a dynamic extent, but needs to have a
constant extent because it's stored in MemoryType::Register (e.g. see
the test). We take an upper bound in these cases to get a constant
allocation size. This PR changes things to take that upper bound
*before* storage flattening instead of after. This way the individual
per-dimension extents are all constant, instead of just their product.
If you do it after storage flattening then you get dynamic strides
within a constant-sized allocation, which is silly and not compatible
with hoisting values into registers anyway (because access is at
non-constant coords).
Also fixed the assumption that MemoryType::Register on the GPU means
that there must be a GPULanes loop.
Builds on #5035

Constant extents inferred pre-storage flattening

---

src/Pipeline.cpp
src/Pipeline.h
test/correctness/c_function.cpp
test/correctness/pipeline_set_jit_externs_func.cpp

- make all single-arg ctors explicit, and add one missing explicit usage
- add an operator<< to ExternSignature to make debugging related issues easier

Minor JITExtern (& related) cleanups

---

src/LICM.cpp
src/LICM.h
src/Lower.cpp
src/LowerWarpShuffles.cpp
test/correctness/CMakeLists.txt
test/correctness/hoist_loop_invariant_if_statements.cpp
test/correctness/lots_of_loop_invariants.cpp
test/correctness/trim_no_ops.cpp

If statements can be injected by GuardWithIf, RDom predicates,
specializations, and uses of undef. There are various situations where
an if statement can end up further inside a loop nest than strictly
necessary. This PR adds a pass to hoist them.
This results in slightly better codegen for some conv layer schedules on
GPU.
Also reduced the expr count in lots_of_loop_invariants because it spends
a long time inside LLVM

Add an explicit pass to lift loop invariant if statements

---

src/Simplify_LT.cpp

Somehow we were missing these. They're useful in canceling non-linear
terms from both sides of a comparison. Pretty trivial, but formally
verified anyway to protect us from typos.

Add some missing 1 vs 3 linear comparison cancellations

---

src/PartitionLoops.cpp

We don't partition loops (e.g. to peel off tail cases) on GPU if there's
a barrier or warp synchronous thing going on, because it may result in
different threads hitting different barriers and expecting to
synchronize with each other. But this is only an issue if the loop we're
partitioning is a parallel one (i.e. a threads loop). If it's serial,
there's no change in the semantics and duplicating the barrier is fine.
In the extreme case it's legal to entirely unroll the loop, duplicating
the barrier N times.
I.e. this transformation is bad:
Before:
```
gpu_threads x in [0, 15]:
serial y in [0, 8]:
barrier
```
After:
```
gpu_threads x in [0, 7]:
serial y in [0, 8]:
barrier
gpu_threads x in [8, 15]:
serial y in [0, 8]:
barrier
```
But this is fine:
Before:
```
gpu_threads x in [0, 15]: …
```

Permit loop partitioning for serial loops on GPU

---

src/SimplifyCorrelatedDifferences.cpp

GuardWithIf conditions can include comparisons with correlated values on
each side, e.g. `((x*8) + y)*2 + z <= x*16`. It's worth cancelling them -
in one case @aekul found it avoids an if statement tree in an unrolled
block.
This would be a fairly trivial change by itself, but I did some light
refactoring while I was there to avoid blowing up the number of template
instantiations.

Apply simplify_correlated_differences to comparisons too

---

src/LLVM_Runtime_Linker.cpp

Should fix the build for win-32-trunk
Having a linkonce linkage type on windows without an associated comdat to let the linker know it can pick anything produces linker errors with missing symbols. This was not previously a problem on windows because llvm just emitted linkonce symbols as extern.

Add COMDATs to mergable symbols on windows

---

cmake/HalideTestHelpers.cmake

This breaks cross compiling on Apple Silicon and probably elsewhere, too. See PR #5073
Also removing disable-optimization flags here. @steven-johnson and I think it's unimportant and it just makes the build have more weird edge cases.

Remove march=native from tests build

---

cmake/HalideTestHelpers.cmake
src/CodeGen_ARM.cpp
src/LLVM_Runtime_Linker.cpp

Changes necessary to run successfully on Apple silicon.
If you'd like any adjustments or have feedback please let us know!
```
% xcrun cmake -DCMAKE_BUILD_TYPE=Release \
-DLLVM_DIR=/Users/deco/Documents/llvm-install/lib/cmake/llvm \
-DCMAKE_CXX_FLAGS='-arch arm64' -DCMAKE_C_FLAGS='-arch arm64' \
../Halide
% xcrun cmake --build . -- -j8
% file src/libHalide.dylib 
src/libHalide.dylib: Mach-O 64-bit dynamically linked shared library arm64
% file src/libHalide.dylib 
src/libHalide.dylib: Mach-O 64-bit dynamically linked shared library arm64
% file test/correctness/correctness_gameoflife 
test/correctness/correctness_gameoflife: Mach-O 64-bit executable arm64
% test/correctness/correctness_gameoflife     
Success!
% test/performance/performance_jit_stress 
Success!
% …
```

Add support to build and run on Apple silicon

---

src/runtime/HalideBuffer.h

This gives a better error message than a segfault if someone tries to
iterate over each value in an undefined Buffer.
Another option was just making for_each_value a no-op, but that felt
like it might hide a real error.
Fixes #5077

Check for null in for_each_value

---

tools/RunGen.h

Formerly this did weird things if the estimates were larger than the
required region in both directions, so autoscheduling of harris
frequently broke with out of bounds errors.
Tagging @steven-johnson because he wrote the original. He's away so this PR will sit for a bit. It's not urgent.

Change adapt_input_buffers to check for interval inclusion

---

src/runtime/metal.cpp
src/runtime/objc_support.h

On macOS 10.15 and later, the prototype for `objc_msgSend()` changed to force code to always cast before using, since the implementation is ABI-dependent (see [Apple's docs](https://developer.apple.com/documentation/objectivec/1456712-objc_msgsend), [Mike Ash's explanation](https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html), [Daniel Jalkut's](https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html), etc.)
This PR changes all our runtime uses to cast method calls to the right type before using, and fixes a runtime error on macOS 11 beta.  This should have no impact on previous versions of macOS and iOS; I've confirmed current iOS works as well as macOS 10.15.5; I believe the buildbot should confirm compatibility for older macOS.

Always cast objc_msgSend()

---

src/Util.cpp
src/Util.h
test/correctness/simd_op_check.cpp

LLVM_VERSION isn't exported to tests, but at least one needs this info. Add an internal API to export this info.

Add Halide::Internal::get_llvm_version() for tests

---

python_bindings/CMakeLists.txt

Fixes builds on offline hosts (common on HPC clusters), which otherwise
fail with failure to fetch pybind11 from the Internet, introduced in
c13efffcc9e282d14c21a5149e4bdee078c85a9c:
CMake Error at
pybind11-subbuild/pybind11-populate-prefix/tmp/pybind11-populate-gitclone.cmake:31
(message):
Failed to clone repository: 'https://github.com/pybind/pybind11.git'
Also, make build friendly to distribution packages.  Distribution
package recipe should be in control of (1) dependencies to build against
(e.g. some distros are on pybind11 2.5, and it should be used unless
it's incompatible), and (2) when fetching happens vs when building
happens. So, there is a need for a packager-friendly build mode where
the build system doesn't go out and fetch whatever dependencies it
chooses whenever it …

cmake: python: use system pybind11 if installed

---

cmake/HalideTestHelpers.cmake

For each test group (eg 'generator') this adds a build metatarget named 'build_$GROUP'; this allows a simpler way to rebuild everything in a test group prior to running ctest.

Add meta-targets to CMake to replicate some Make functionality

---

apps/autoscheduler/AutoSchedule.cpp

The schedule emitted by Adams2019 autoscheduler sometimes results
in a compilation error. This error is seen when the autoscheduler emits
trivial reorder (reorder of a single variable). For example, the autoscheduler
emits the following schedule snippet:
`.reorder(x1);`
There is a check inplace which prevents these reorders by verifying the
the size of vector representing the `vars` to be reorderd  is greater than 1.
https://github.com/halide/Halide/blob/master/apps/autoscheduler/AutoSchedule.cpp#L806
Though, there are some cases where this check doesn't filter out trivial reorders
(when some variables don't exist).
This patch changes the reorder() directive emitted in schedule file
by the autoscheduler.
from: .reorder(VarOrRVar x, VarOrRVar y, Args && args)
to: …

Fix autoscheduler emitted schedule for reorder

---

python_bindings/src/PyEnums.cpp
src/CodeGen_WebAssembly.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h

Cherry-picking a change from #5097 so that reviewing that PR will be simpler; this just adds another feature option for wasm that tooling wasn't ready for before, but is now (saturating float-to-int conversion).

Add Target::WasmSatFloatToInt

---

cmake/HalideTestHelpers.cmake
test/generator/CMakeLists.txt

Cherry-picking some CMake-related stuff from #5097 to make it easier to review:
- Add an optional COMMAND argument to add_halide_test(), this allows us to customize the command for execution (e.g. to run generated .wasm with a shell tool)
- Add some missing DEPENDS in a few places
- Add an optional EXTRA_LIBS argument to halide_define_aot_test(); this allows us to pass extra dependencies rather than requiring separate calls to target_link_libraries().
That last one is a little odd, so let me expand: the intent here is that (when the wasm changes land), some of the tests that aren't usable under wasm (e.g. matlab), and halide_define_aot_test() will handle these by just skipping those targets entirely. This means that we can effectively centralize the blocklist in one place, and then the …

Land some CMake revisions for wasm integration

---

src/Simplify_Max.cpp
src/Simplify_Min.cpp
test/correctness/simplify.cpp

Fixes #5100
Formally verified, but not synthesized (predicate synthesis failed, so I had to come up with predicates by hand and check them).

Add simplifier rules for some combinations of select and min/max

---

python_bindings/correctness/basics.py
python_bindings/src/PyScheduleMethods.h

PR #4898 added methods to C++; this makes them usable in Python.
Added a test case.

Add vector tile methods to the Python bindings

---

.github/workflows/presubmit.yml
Makefile

Upgrade the clang-format checks to clang-format-10, and reformat code accordingly. (Note that there aren't actually any changes necessary for 9 -> 10, but there are some for 10 -> 11 or 10 -> 12.)
Also add a way tp specify the clang-format version for `make format`; it defaults to the version of Clang for the current LLVM, but since clang-format doesn't provide stable formatting across versions, this might be wrong.

Upgrade clang-format to v10

---

README.md

The release tags should be the canonical source for that version; branches can sometimes be broken.

Update README to suggest cloning a release of LLVM, not a branch

---

tools/RunGenMain.cpp

Currently you just get a segfault if you forget to compile in a registration file and you say something like benchmarks=all

Add an error message if you forget to compile RunGenMain with a registration file

---

src/CodeGen_PTX_Dev.cpp

PrintMachineCode has been removed in LLVM 12/trunk

Fix for trunk LLVM

---

README.md

We don't use Travis anymore, so this is misleading.

Get rid of stale Travis CI build info from README.

---

src/CodeGen_Hexagon.cpp

If you try to compile HVX standalone code with HL_TARGET=hexagon-32-noos, you will die because necessary glue functions are defined in hvx_64 or hvx_128 but not 'baseline' hvx. Add an assertion check with a helpful error meesage to avoid just segfaulting deep inside LLVM.

Improve HVX codegen error reporting

---

src/runtime/HalideRuntime.h
src/runtime/HalideRuntimeHexagonDma.h
src/runtime/mini_hexagon_dma.h
src/runtime/mini_qurt.h
test/correctness/gather.cpp

Fixes warnings generated by bad Doxygen comments. Normalizes use of `/*!` vs `/**` and `//!` vs `///` to all be the non-`!` versions, which are predominant.

Fix Doxygen warnings in runtime

---

src/CodeGen_LLVM.cpp

Don't codegen asserts in blocks when noasserts is on

---

apps/CMakeLists.txt
apps/autoscheduler/CMakeLists.txt
apps/cmake/FindHalide.cmake
cmake/HalideTestHelpers.cmake
python_bindings/correctness/CMakeLists.txt
python_bindings/tutorial/CMakeLists.txt
tutorial/CMakeLists.txt

Also drive-by remove `APPS_INTERNAL` as discussed in #5132 
I'm doing that here because if I hadn't, I would have needed to change the test environment in _every_ app.

Set HL_{JIT_}TARGET from CMake Halide_TARGET variable.

---

src/CodeGen_C.cpp
src/CodeGen_C.h

Tested with HL_TARGET=host-no_asserts make -C apps/c_backend/ test

Fix 'unused variable' warning in the code generated by CodeGen_C with 'no_asserts' feature

---

apps/autoscheduler/cost_model_generator.cpp

The ordering of two feature names in the autoscheduler cost model were inconsistent with the names of those variables in the featurization. This makes the cost model confusing.
Fortunately the variables are used in exactly the same way, so just switching the variable names in the cost model clears things up without having to retrain anything. I have verified that it's producing the same schedules before and after.

Fix transposed variable names

---

.github/workflows/presubmit.yml

Need to run `sudo apt-get update` before `sudo apt-get install` to avoid possibly stale install info.

Fix clang-tidy presubmit

---

Makefile
dependencies/llvm/CMakeLists.txt
src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/LLVM_Runtime_Linker.cpp
src/Target.cpp
test/generator/CMakeLists.txt
tutorial/CMakeLists.txt

I'm in the process of making CMake bundle LLVM as part of Halide and I'm finding that I need to contort my way around these defines because one of them -- WITH_PTX -- is not named after its corresponding LLVM component, NVPTX.
This one small change drops ~60 lines of CMake while touching ~10 lines elsewhere.

Rename WITH_PTX to WITH_NVPTX so all WITH_* macros match LLVM component names

---

apps/nl_means/nl_means_generator.cpp

We run it on the parrot image, which is 5 megapixels.

Fix incorrect estimates for nl_means autoscheduler

---

apps/blur/test.cpp

Don't rely on HALIDE_RUNTIME_HEXAGON; examine the metadata to see how we were compiled

Fix apps/blur on Hexagon

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp
src/Func.cpp
src/Func.h
src/Pipeline.cpp
src/Pipeline.h
test/correctness/param_map.cpp
test/correctness/simd_op_check.h

Currently, if the code isn't already jitted (or is jitted with NoBoundsQuery enabled), infer_input_bounds() falls back to whatever is in HL_JIT_TARGET. This is suboptimal, because it hides the fact that infer_input_bounds() relies on the value of that env var. It can also cause unintentional incorrect re-jits; e.g. if simd_op_check is run for HL_TARGET=wasm-32-wasmrt (and HL_JIT_TARGET not set at all), the infer_input_bounds() call can end up re-jitting for native code instead of WebAssembly.

Add a Target to the args of infer_input_bounds()

---

tools/RunGen.h

Otherwise synthetic inputs like 'random' end up being 'zero'

Make sure to set_host_dirty in rungen

---

apps/fft/fft.cpp
src/BoundaryConditions.cpp
src/BoundaryConditions.h
test/correctness/boundary_conditions.cpp
test/correctness/likely.cpp
test/correctness/require.cpp
test/generator/blur2x2_generator.cpp

The following syntax did not work due to a lack of appropriate overload:
repeat_edge(buffer, {{0, W}, {0, H}})
The version that worked was:
repeat_edge(buffer, 0, W, 0, H)
but that syntax has fallen out of favor
This PR adds an overload to make the former syntax work, and explicitly
deprecates the latter.
Also removed inline qualifiers on some templated functions, because
they're already inline, and changed an arg to be by const ref instead of
pointlessly by value.

Add missing overload for boundary conditions on a buffer

---

src/CodeGen_Hexagon.cpp
test/correctness/simd_op_check_hvx.cpp

In the degenerate case of shuffle_vector() calling vlut() to shuffle a vector that is wider than 256 elements, the code was incorrectly using halide.hexagon.pack.vh on a vector-of-bool; this used to be necessary, but hasn't been for a while, so clearly this code path wasn't being exercised.
Remove the halide.hexagon.pack.vh and added a test case to exercise that path.
Also, drive-by removal of #include "EliminateBoolVectors.h" from CGHVX since it is no longer used there.

Remove unnecessary call to halide.hexagon.pack.vh in CG_HVX

---

apps/stencil_chain/stencil_chain_generator.cpp

It was accidentally left on the CPU, which means that benchmarking included a device copy. Oops.

Schedule last stage of stencil chain on GPU too

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp
src/Func.cpp
src/Func.h
src/Pipeline.cpp
src/Pipeline.h
test/correctness/autotune_bug.cpp
test/correctness/bounds_of_monotonic_math.cpp
test/correctness/extern_bounds_inference.cpp
test/correctness/param_map.cpp
test/correctness/simd_op_check.h
test/correctness/specialize.cpp
test/correctness/unsafe_promises.cpp
test/error/expanding_reduction.cpp
test/error/impossible_constraints.cpp

Add a variant of infer_input_bounds() that takes an explicit vector of int, rather than the up-to-4-int version that is a holdover from the buffer_t days; deprecate the old version; convert all existing code to use the new one.
~~There are two warts here, unfortunately: in theory we should be able to just wrap the ints in {braces}, but in practice that doesn't work for zero- or one-arg lists:~~
~~- zero-arg vectors are ambiguous wrt other overloads of the method, and the compiler will select a deprecated one~~
~~- one-arg vectors are broken in C++ with brace initialization, as a single-integer arg will invoke the "create a vector of this length" ctor rather than "create a vector of length one with this value" ctor.~~
~~These two warts leave me with a bad taste in my mouth; the 'new' …

Add infer_input_bounds(vector<int>)

---

src/Pipeline.cpp
src/Pipeline.h
src/Target.cpp
src/Target.h

Because WebAssembly is a special beast, the way it is 'jitted' is special, and the checks to avoid redundant jitting needed extra logic in compile_jit(). Unfortunately there was another place in Pipeline that also needed this special casing. This PR adds a `get_compiled_jit_target()` bottleneck to consolidate this.
(Also added the `Target::defined()` method as a quick way to determine "are any parts of this Target unknown" -- not sure if this is the best name for the method. `is_unknown()`? Something else?)

Clean up is-jit-compiled checks in Pipeline

---

src/FuseGPUThreadLoops.cpp
src/PartitionLoops.cpp

Partition loops shouldn't mess with serial loops containing
thread barriers, potentially causing warp divergence and deadlock (seen
in some obscure lens blur schedules).
Also we were generating too many thread barriers in a branch where the
base mutator class was accidentally always mutating something, so
there's a change to FuseGPUThreadLoops to make it more bug-resistant.
Without these additional barriers I have been unable to come up with a
case where a barrier ends up somewhere that would deadlock, so no test.

Fix a source of GPU barrier deadlocks

---

python_bindings/correctness/target.py
src/Target.cpp
src/Target.h
test/correctness/target.cpp
test/error/CMakeLists.txt
test/error/incomplete_target.cpp

We previously accepted 'incomplete' Target strings (filling in host attributes for arch-bits-os if unspecified); we thought this would be a convenience, but in practice, this is usually indicative of an error or typo. This changes to make the Target(string) ctor assert-fail if the resulting target has an unspecified arch-bits-os.
Fixes #5009

Don't allow Target strings without complete arch-bits-os

---

apps/bgu/bgu_generator.cpp

BGU on CUDA had regressed from its stated performance due to the atomic
floating point adds being compiled to CAS loops due to complex indexing
expressions diverging on the LHS and RHS of the +=. Inlining less stuff
into the += operations makes it succeed again, and the schedule was
improved with a few other tweaks.
Longer-term we need a first-class way to represent += so that we're not
sensitive to this sort of divergence.

Reschedule BGU to fix performance regression

---

src/CodeGen_Internal.cpp

Previous fix broke LLVM 11 (I was too eager to land, sorry)

fix for trunk llvm, try #2

---

tutorial/CMakeLists.txt

When not cross compiling #5186 allows CMake to bundle generated object files together into a static lib. That means the library will have "lib" prepended to it (on Unix-y systems, at least. See [`CMAKE_STATIC_LIBRARY_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_STATIC_LIBRARY_PREFIX.html)). Unfortunately, that broke the lesson 15 tutorial test, which had the names mostly hard-coded.
Thanks, @Infinoid for reporting this.
@steven-johnson -- are the tutorials not tested on CI, how did we miss this?

Fix expected files list for lesson 15 test.

---

python_bindings/src/PyExpr.cpp
python_bindings/src/PyRDom.cpp

This is a quality of life improvement for Python development.
The C++ objects know how to stringify themselves.  The python objects often stringify to a generic string that looks like `<halide.Whatever object at 0xHEXADDRESS>`, which is not very informative.  It gives you the type of object, but nothing about its contents.
This patch improves the stringification of Python Expr, RDom and RVar objects.  There are other things that can also be stringified, but this is what I needed at the moment.
Expr before:
```
<halide.Expr of type float32>
```
Expr after:
```
<halide.Expr of type float32: (float32)cos_f32(float32(my_r$x))>
```
RVar before:
```
<halide.RVar object at 0x7fce2dd83670>
```
RVar after:
```
<halide.RVar my_r$x(0, 4)>
```
RDom before:
```
<halide.RDom object at 0x7f33dfa1f9f0> …
```

Teach the python bindings how to stringify Expr, RDom, RVar.

---

src/LLVM_Runtime_Linker.cpp
test/error/metal_vector_too_large.cpp

posix_abort and windows_abort are WEAK_INLINE, so they shouldn't be included with `no_runtime`
Also a drive-by fix for a false-success error test... we should probably write down some golden outputs for these.

fix lesson_15 test by excluding posix/windows_abort

---

src/runtime/CMakeLists.txt

I noticed that incremental builds on Ninja usually fully rebuilt the runtime. Normally, this is pretty quick, but on Windows/WSL, the filesystem overhead makes this annoying.
CMake has support for scanning C/C++ sources that are processed by custom commands when using Make as a generator via the `IMPLICIT_DEPENDS [C/CXX]` argument. However, for Ninja, a custom depfile must be specified.
I thought "oh, this will be easy! I'll just add the -MD and -MF flags and point CMake to the dep-file". Not so simple. Ninja requires the target in the depfile to match the _exact_ (in this case relative) path to the output of the command. Clang doesn't provide an easy way to override this, and CMake doesn't have any helpers to make this more convenient. Sigh. All three tools conspire to make a fundamental …

Fix incremental builds with Ninja

---

src/LLVM_Output.cpp
src/Util.cpp

We should rethink the placement of the current directory code in `LLVM_Output.cpp`. That would let me reuse the code in `from_utf8` and `from_utf16`. 
Fixes #5223

Replace ANSI Win32 API calls with UTF-16; convert UTF-8 at boundary.

---

src/FuseGPUThreadLoops.cpp
test/correctness/CMakeLists.txt
test/correctness/gpu_non_monotonic_shared_mem_size.cpp

GPU kernel launches must use the same amount of shared memory per block,
and this has to be computed ahead of time on the host. The expressions
that gives the size of the allocations that are compute_at blocks are inside the
kernel though, and are a function of bounds inference. We therefore have
to take the max of these sizes over all blocks. This is extremely prone
to interval arithmetic being overconservative, because these are extents
computed from a max minus a min, and the max and min are both frequently
correlated with the block variable. This causes a lot of otherwise fine
schedules to fail at runtime with CUDA_ERROR_INVALID_VALUE.
This PR detects cases where interval arithmetic is going to be
overconservative using is_monotonic, and hoists the computation of
shared memory size to …

Exhaustively compute max allocation size on host for non-monotonic shared memory sizes

---

README_cmake.md

This PR turns `README_cmake.md` into a comprehensive guide to the three main usage stories of the Halide CMake build:
1. Compiling or packaging Halide from source.
2. Building Halide programs using the official CMake package.
3. Contributing to Halide and updating the build files.
**Direct link for easy review**: https://github.com/halide/Halide/blob/docs/cmake/README_cmake.md
Fixes #5207

Thoroughly document CMake build

---

apps/depthwise_separable_conv/depthwise_separable_conv_generator.cpp
apps/depthwise_separable_conv/tf_separable_conv.py

I got it down to 65us, and fixed the tensorflow benchmark to use the same benchmarking methodology as we do (best of a number of trials). Tensorflow is at ~130us.
@dsharletg

Reschedule depthwise separable convolution again

---

src/CodeGen_Hexagon.cpp
test/correctness/gather.cpp

**Do NOT merge.**
Lower bound for lut needs to > -1 instead of >= -1.
The bug was introduced in b7dd787c4532d759334f0a2348c993af5e21f152 commit.
@dsharletg @pranavb-ca  The lut32 test fails right now with a compilation error.

[Hexagon] Fix for LUT32 correctness.

---

test/correctness/simd_op_check.cpp

In some cases the operation could be executed with a wider type on arm64 and the test would not catch this.

Add check of types for ARM simd_op_check.

---

tools/package-windows.bat

Static archives were too large and of dubious benefit. We can revisit this if our users request it. 800MB compressed and 4GB uncompressed.

Drop static library build from Windows.

---

python_bindings/readme.md
python_bindings/src/PyFunc.cpp

The Python bindings were missing a wrapper for `Func::async`. This
change adds a wrapper called `Func.async_` to avoid clashes with the
Python `async` keyword.

Add support for Func::async in Python bindings

---

CMakeLists.txt
tools/package-unix.sh
tools/package-windows.bat

This is intended as a temporary trick; in the long run, each version will have its own release branch. This allows us to temporarily try out different 'releases' from the Halide master branch.

Allow overriding the Halide version via cmake flag

---

src/CodeGen_OpenCL_Dev.cpp

clBuildProgram returns error due to missing \n.

Missing new line causes OpenCL programs to fail to compile when targetting cl_half/cl_doubles

---

src/Simplify_Call.cpp

According to @abadams, Call::if_then_else promises to evaluate exactly one (but not both) of the true and false exprs, so we should simplify cases in which the condition is provably true or false.

Simplify Call::if_then_else

---

src/autoschedulers/adams2019/AutoSchedule.cpp
src/autoschedulers/adams2019/DefaultCostModel.cpp

Remove two unused 'using' declarations.

Appease clang-tidy

---

test/correctness/atomics.cpp

These tests were disabled in #4683 but #4628 supposedly provided a fix. This PR re-enables them.
Fixes #4554.

Re-enable CUDAVectorize tests. 

---

tutorial/figures/generate_output_snippets.sh

Some terminals treat LINES as a special var, breaking this script

Rename LINES to INTERESTING_LINES

---

dependencies/wasm/CMakeLists.txt
packaging/CMakeLists.txt
src/CMakeLists.txt

Only affects Halide 11+. No more need to package libwabt.a, just includes its objects into libHalide.a

Bundle wabt objects into libHalide

---

python_bindings/src/PyEnums.cpp
src/CMakeLists.txt
src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h

The CMake build has an option, `HALIDE_USE_CODEMODEL_LARGE` that I (re)discovered while writing documentation. I am not sure why it exists. It's not mentioned anywhere in the Makefile and it doesn't seem to be used by any of our tests.
This PR turns it into a target feature rather than a build option, but another valid approach might be to remove it outright. This is probably the appropriate venue for this discussion.

Replace large code model build option with target feature.

---

src/RDom.h
src/runtime/HalideRuntime.h

One of the armbots warned that this field could be used uninitialized; I can't replicate anywhere else, but indeed, the string-only ctor of RVar left this uninitialized. Defaulted it to -1 and added an explicit check in _var(). (Yes, the call to `at()` will fail when out of range, but explicit checking is better IMHO.)
(Also: unrelated drive-by formatting fix to HalideRuntime.h to avoid another PR just for that)

Avoid possibly-uninitialized use of RVar::_index

---

Makefile

- one of the Windows-specific runtime files had a 32-vs-64 glitch
- CMake now uses `fno-threadsafe-statics` (instead of `-std=gnu++98`) to disable thread-safe static initialization; as a result, this allowed C++11 code requirements to creep in (via d3d12compute.cpp), but we didn't notice because the Makefile wasn't properly building that file due to the 32-vs-64 glitch. Fixed by updating the Makefile to use this flag instead (which was an overdue fix anyway).

Fix runtime build rules in Makefile

---

src/DeviceInterface.cpp
src/runtime/metal.cpp

`host_supports_target_device()` was returning true if it failed to get a `DeviceAPI` corresponding to the target.
Drive-by fix: in a `-metal-debug` target, `halide_current_time_ns()` was being called in `halide_metal_device_malloc()` before timer initialization, which happens as part of context creation.

Fix host_supports_target_device()

---

src/runtime/hashmap.h
src/runtime/opengl.cpp
src/runtime/runtime_internal.h

This is the canonical form for statement-like macros in C.
Added some missing semicolons that were detected by this (and fixed formatting).

Make halide_assert() use do...while(0) idiom

---

cmake/BundleStatic.cmake
dependencies/llvm/CMakeLists.txt
src/Generator.cpp

Apparently, LLVM's own `llvm_map_components_to_libnames` function is busted if you build only the shared library version.
This PR should fix that up and avoid calling this function when shared LLVM is requested.
We should backport this to 10.0.0 for future Deb packaging, and we probably need to add buildbot testing of shared and bundled scenarios. Maybe just the x64 linux bot can run the generator tests.
Fixes #5304.

Fix linking to shared LLVM. 

---

src/Generator.cpp
src/runtime/CMakeLists.txt

Mainly, we weren't setting any of the warning flags, so CMake builds were more forgiving than Make.

Make sure the runtime compiler settings in CMake match those in Make

---

src/InjectHostDevBufferCopies.cpp

~~I haven't found a case where this is actually a problem, but I noticed from debugging a different issue that the FindInputsAndOutputs doesn't look at Call nodes at all, so it can miss Buffers/Parameters associated with them.~~
~~Not sure if this is an issue in practice. Maybe we never want buffer copies for these? (If so then we should document it as such.)~~
~~This PR just adds the logic used for this in InferArguments.~~

InjectBufferCopiesForInputsAndOutputs should check for unexpected Call nodes.

---

src/CodeGen_LLVM.cpp

Add call to TargetMachine::registerPassBuilderCallbacks to allow targets to add passes to the pass pipeline using the New Pass Manager
@alinas PTAL

Use adjustPassManager equivalent for NPM

---

README.md

`x64_x86` = build using 64-bit compiler, targeting 32-bit x86 (https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019).   We had it backwards before.

Fix 32-bit Windows vcvars command

---

src/Bounds.cpp

Bug in bounds inference engine, discussed with @abadams @shoaibkamil @alexreinking and @jn80842 . 
Maximum value possible from dividing a bounded interval (a0, a1) buy an unbounded interval is max(-a0, a1), which correspond to the cases that a0 is negative but greater in magnitude than a1 (and divided by -1), or where a1 is the maximum possible value (divided by 1).

fix bounds inference bug for bounded interval / unbounded interval

---

test/correctness/async_device_copy.cpp
test/correctness/dynamic_allocation_in_gpu_kernel.cpp
test/correctness/extern_stage_on_device.cpp

OpenCL on macOS (Mojave at least) supports a maximum workgroup size of 256.  This causes a few tests to fail that specify larger workgroup sizes when targeting OpenCL on mac.  The sizes don't seem to be substantial to any of these tests, so lower them.

Reduce GPU Tile Size in Tests

---

src/CodeGen_C.cpp
src/CodeGen_C.h
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_D3D12Compute_Dev.h
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenCL_Dev.h
src/CodeGen_OpenGLCompute_Dev.cpp
src/CodeGen_OpenGL_Dev.cpp

Modify codegen for C-like backends to just emit integer constants with the correct suffix for the backend, rather than wrapping in a giant macro; the macro approach worked but lordy was it painful to read.

Remove the ADD_[U]INT64_T_SUFFIX macros

---

src/Simplify_Add.cpp
test/correctness/fuse.cpp

This PR removes the requirement that the denominator in some simplifier rules regarding fused ramps be constant. The new rules just check if the denominator is zero at runtime. If the denominator is constant, this check will simplify away anyways, and if it isn't, this still seems cheaper than computing a mod operation at runtime.

Stronger simplification of fused ramps

---

src/runtime/HalideRuntime.h

Grand Central Dispatch isn't used anymore; this comment is outdated and a source of confusion.

Remove erroneous sentence in comment about GCD

---

src/FlattenNestedRamps.cpp

The min_lane expression could grow very large, and required simplifying
once per lane

Fix compile-time regression relating to nested vectorization change

---

src/PartitionLoops.cpp
test/correctness/CMakeLists.txt
test/correctness/partition_max_filter.cpp

Because if any likely tag at all existed on a side of the min/max, even
if captured, the other side wasn't getting mutated. This should only
happen for uncaptured likelies, where simplifications in the unlikely
path are irrelevant.
Fixes #5353

min and max in the algorithm was confusing loop partitioning

---

Makefile
src/CodeGen_C.cpp
src/CodeGen_C.h
test/generator/CMakeLists.txt
test/generator/shuffler_aottest.cpp
test/generator/shuffler_generator.cpp

The existing approach (wrapping native vectors in a helper struct) caused too many unnecessary spills. Rewrote so that the underlying Native Vector type is the value being passed around, and improved some of the specializations (with checking of generated code on x64 under clang and gcc). Clang is actually quite good at recognizing patterns and generating appropriate code (at least for x64); gcc is much less so, at least as far as I can tell.

Rewrite internal glue code for vectors in C++ backend.

---

README.md

Add vcpkg instructions to README.md

---

src/Bounds.cpp

Fix discussed with @abadams and @alexreinking . Original code takes `b = [0u, 0u]` and produces an interval of `[0, b.type().max()]` due to wrap-around. Technically correct but pessimistic/not tight. This fix removes that case and simplifies the overall generated expression `interval.max` by removing the `max()`

bounds inference (mod) pessimistic on unsigned 0 interval

---

src/VectorizeLoops.cpp
test/correctness/fuse.cpp
test/performance/nested_vectorization_gemm.cpp

With this change, in a nesting of vectorized vars in an
associative/commutative reduction (e.g. +=), we can now have a reduction
var outermost and a reduction var innermost and get good codegen. This
is still not fully general - there can only be one pure var in the
vectorized stack for it to work. In general is_interleaved_ramp should
be an is_tensor_contraction pass that knows how to do clever codegen for
those.
For the following schedule for a 16-bit large convolution:
```
prod.compute_at(result, x)
.vectorize(x)
.update()
.split(r, ro, ri, 8)
.split(ri, rio, rii, 2)
.reorder(rii, x, rio, ro)
.vectorize(x)
.atomic()
.vectorize(rio)
.vectorize(rii);
```
We get the following IR:
```
let t2262 = (int32x32)vector_reduce(Add, (int32x64(shuffle((int16x15)p10_im_global_wrapper$0[ramp(0, 1, …
```

Handle more types of nested vectorized += without scalarizing

---

src/PartitionLoops.cpp

The other visitors in FindSimplifications all use `has_likely_tag`, which searches expressions for `likely`. If did not however, which made loop partitioning brittle, e.g. in the case of `if ((uint1)likely(x))`.

Make loop partitioning a bit more robust for if statements

---

.github/workflows/presubmit.yml
python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp
python_bindings/src/PyRDom.cpp
python_bindings/stub/PyStubImpl.cpp
run-clang-tidy.sh
src/autoschedulers/.clang-tidy
src/autoschedulers/adams2019/ASLog.cpp
src/autoschedulers/adams2019/AutoSchedule.cpp
src/autoschedulers/adams2019/DefaultCostModel.cpp
src/autoschedulers/adams2019/Featurization.h
src/autoschedulers/adams2019/FunctionDAG.cpp
src/autoschedulers/adams2019/FunctionDAG.h
src/autoschedulers/adams2019/LoopNest.cpp
src/autoschedulers/adams2019/PerfectHashMap.h
src/autoschedulers/adams2019/Weights.cpp
src/autoschedulers/adams2019/cost_model_generator.cpp
src/autoschedulers/adams2019/retrain_cost_model.cpp
src/autoschedulers/common/cmdline.h
src/autoschedulers/li2018/GradientAutoscheduler.cpp
tools/RunGen.h
tools/binary2cpp.cpp
tools/build_halide_h.cpp
tools/halide_image_io.h
tools/halide_trace_config.h
util/HalideTraceUtils.cpp
util/HalideTraceViz.cpp

(and also fix the reported findings)
Note that this also extends the testing to src/autoschedulers, but *not* to src/runtime (yet). It would likely be desirable to do so at some point, but requires a bit more massaging of the build scripts.
Extending to apps/ and test/ might be nice, but would require running all Generators to produce the needed .h files.

Extend clang-tidy checks into  tools, utils, and python_bindings

---

src/runtime/.clang-tidy
src/runtime/CMakeLists.txt
src/runtime/cache.cpp
src/runtime/cpu_features.h
src/runtime/d3d12compute.cpp
src/runtime/device_buffer_utils.h
src/runtime/hexagon_dma.cpp
src/runtime/hexagon_host.cpp
src/runtime/msan.cpp
src/runtime/opencl.cpp
src/runtime/opengl.cpp
src/runtime/opengl_egl_context.cpp
src/runtime/opengl_glx_context.cpp
src/runtime/openglcompute.cpp
src/runtime/osx_opengl_context.cpp
src/runtime/profiler.cpp
src/runtime/pseudostack.cpp
src/runtime/thread_pool_common.h
src/runtime/to_string.cpp
src/runtime/write_debug_image.cpp

Extend clang-tidy checks to src/runtime

---

python_bindings/correctness/negate_test.py
python_bindings/readme.md
python_bindings/src/PyBinaryOperators.h
python_bindings/src/PyIROperator.cpp

This change introduces `logical_not` as a free function and member function
that calls `operator!`.
The reason why a new function is added is because there is no `operator!`
in Python and the `not` keyword cannot be overloaded. Hence, there was
currently no way to call the C++ `operator!` in Python.

Add `logical_not` function for Python

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyScheduleMethods.h

In the C++ API, the `.gpu_lanes(x)` scheduling method exists for both `Func` and `Stage` objects.  The Python bindings only allow calling it on `Func`; move it over so it can be used on both.

Add Stage.gpu_lanes to Python bindings.

---

src/Target.cpp

This is based on #5395.
This will fix issue #5397

Require WASM features to match

---

src/Associativity.cpp

just came across this loop and found out that `change` was always false.

Fix transitive dependencies

---

src/runtime/hexagon_remote/Makefile

HalideRuntime.h now requires at least C++11 (for C++ files), so ensure that we pass `-std=c++11` for all those when building the remote.

Upgrade hexagon_remote/Makefile  to use C++11

---

.clang-tidy
src/IntrusivePtr.h
src/autoschedulers/.clang-tidy
src/runtime/.clang-tidy
src/runtime/HalideBuffer.h

Enable all the bugprone-* checks, then disable the ones we don't want (or need code fixes for).
Made a couple of trivial changes to pacify bugprone-unhandled-self-assignment.
Some of the other disabled checks are likely worthwhile but will be done separately to ensure code review isn't confused.

More clang-tidy cleanup

---

src/CSE.cpp
src/Lower.cpp

The CSE pass tries to do CSE jointly on the index and value of store nodes.
This is to stop:
```
f[x] = f[x] + y
```
from turning into
```
f[x] = f[z] + y
```
This is because the two 'x' indices are not CSE'd together.
However, one problem with jointly CSEing the store index and vaues
is that after CSEing, the pass puts the lets
(the values that were CSE'd) before the new store. That is we get,
```
let(t0...)
let(t1...)
f[t0] = f[t0] + function_of(t1)
```
Suppose however, there was nothing to CSE between the store index and value, that is
the index was unchanged after CSE. In that case, moving lets before the store puts the
lets too far away from their uses. This is ok except, there are passes like LoopCarry
that are beneficial when they are able to see a long continuous block of stores …

Push lets near their uses (whenever possible) while CSEing +=

---

src/Bounds.cpp

Due to Halide division by 0 semantics, the precondition can be loosened for bounds inference on division by a single point, as an interval divided by the zero interval produces the zero interval.
Discussed with @abadams @shoaibkamil and @jn80842 .

loosen preconditions on div by single point in Bounds.cpp

---

python_bindings/stub/PyStubImpl.cpp
src/FindCalls.cpp
src/Profiling.cpp
util/HalideTraceViz.cpp

For some reason, these are only getting flagged under C++17 builds, but they are legit (minor) issues we want to fix.

Fix various clang-tidy issues

---

python_bindings/CMakeLists.txt
python_bindings/requirements.txt

v2.4.3 can generate a lot of compiler warnings under C++17; v2.5 fixes these.
Note 1: I am unsure about the issues with keeping in sync with Ubuntu 20.04; tagging @alexreinking for comments
Note 2: the current version of PyBind11 is actually v2.6, but it has many more changes and upgrading looks nontrivial; deliberately holding off on that upgrade for now.

Upgrade PyBind11 version in CMake to 2.5

---

README_cmake.md
run-clang-tidy.sh
src/runtime/CMakeLists.txt

Every once in a while it seems that CMAKE_EXPORT_COMPILE_COMMANDS gets enabled for me, possibly by VSCode, and the build grinds to a halt. Setting it to false in the cache gets everything working again.  It seems like there are valid applications for a compilation database even when doing normal builds (such as knowing flags for parsing with other tools).  This gives the clang-tidy behavior its own flag.

Use new flag for clang tidy behavior in cmake

---

src/Bounds.cpp

Discussed with @abadams . Many inequality and equality operators can be bounded even if their operands are not fully bounded. e.g. a = [_, a1] and b = [b0, _] with a1 <= b0 implies a <= b can be true, even when _ means unboundedness on that side of the interval. This also tightens the output of one of the test cases.

add conditions for one-sided bounds to LT/GT, LE/GE, EQ, NEQ

---

src/CSE.cpp
src/Lower.cpp

Reverts halide/Halide#5387
This change appears to be causing some of our code to crash on device. I'd like to revert it and I'll work on producing a test case to reproduce the issue.

Revert "Push lets near their uses (whenever possible) while CSEing +="

---

src/Func.h

I spotted this while grepping around to find the name of the `compile_jit` method.

Fix typo in comment: jit_compile -> compile_jit

---

src/runtime/HalideRuntime.h
src/runtime/hexagon_remote/Makefile

Building hexagon_remote with C++11 ends up inserting some unwanted C++11-related symbols (__gxx_personality_v0) that aren't present. This reverts those changes, and modifies HalideRuntime.h so that most of the `__cplusplus` checks are now `__cplusplus >= 201103L` (i.e., C++ convenience features only exist when compiled under C++11 or later).

Revert C++11 usage in hexagon_remote

---

README.md
apps/hexagon_dma/Makefile
apps/hexagon_dma/mock_dma_implementation.cpp
apps/simd_op_check/Makefile
apps/support/Makefile.inc
src/Func.h
src/runtime/hexagon_dma_pool.h

The Makefile help for apps/ assumed a fairly old version of the Android NDK (~2017). This updates to assume r19 or later:
- No need to do `make-standalone-toolchain` anymore
- Clang instead of GCC
- assume static linking of libc++ is the right default
I am limited in my ability to test on-device here (I don't have a device that will let me test HVX easily). apps/blur works fine onmy P2XL after this change, though.
This required a little tweaking to apps/hexagon_dma and related files to make it compile happily.
Also, drive-by fix to apps/simd_op_check to remove hvx_64 references.

Update Android NDK support in apps/

---

README_cmake.md

I tried to use instructions for a basic CMake project with a locally
downloaded copy of Halide, and got the following error:
```
CMake Error at CMakeLists.txt:9 (find_package):
By not providing "FindHalide.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Halide", but
CMake did not find one.
Could not find a package configuration file provided by "Halide" with any
of the following names:
HalideConfig.cmake
halide-config.cmake
Add the installation prefix of "Halide" to CMAKE_PREFIX_PATH or set
"Halide_DIR" to a directory containing one of the above files.  If "Halide"
provides a separate development package or SDK, be sure it has been
installed.
```
Changing `CMAKE_MODULE_PATH` to `CMAKE_PREFIX_PATH` worked for me.

Change "CMAKE_MODULE_PATH" to "CMAKE_PREFIX_PATH"

---

README_cmake.md
cmake/HalideGeneratorHelpers.cmake

This is just syntactic sugar for adding the namespace explicitly to the function name, but for code with long namespaces and/or function names this can make for more readable build files. (The Bazel/Blaze build rules offer a similar option and it works well there.)

Add optional NAMESPACE arg to `add_halide_library()`

---

src/CodeGen_LLVM.cpp

We were unnecessarily scalarizing the computation of ramps with non-constant stride, filling a vector by computing the elements one by one. This PR changes it to codegen it as base + stride * ramp(0, 1, lanes), so that the ramp itself is a constant and the work becomes broadcasting the base and stride, and then a single vector multiply and add.
Consider:
```
f(x, y) = x*y;
f.vectorize(x, 8);
```
Master:
```
leal	(%rax,%r13), %r11d
vmovd	%r11d, %xmm0
leal	(%r12,%r13), %esi
vpinsrd	$1, %esi, %xmm0, %xmm0
leal	(%r14,%r13), %esi
vpinsrd	$2, %esi, %xmm0, %xmm0
leal	(%r10,%r13), %esi
vpinsrd	$3, %esi, %xmm0, %xmm0
leal	(%r8,%r13), %esi
vmovd	%esi, %xmm1
leal	(%rbp,%r13), %esi
vpinsrd	$1, %esi, %xmm1, %xmm1
leal	(%rdx,%r13), %esi
vpinsrd	$2, %esi, %xmm1, %xmm1
leal	(%rcx,%r13), %esi
vpinsrd	$3, …
```

Better codegen for ramps with non-const stride

---

dependencies/llvm/CMakeLists.txt

attn @JanHett -- you might want to update your submodule when this is merged.
Fixes #5471

Fail CMake when LLVM_LINK_LLVM_DYLIB conflicts with wasm

---

src/Simplify_Call.cpp
test/correctness/simplify.cpp

Currently, things like shift_right(x4(8), x4(1)) are not constant folded. This PR fixes that.

Simplify intrinsics of broadcasts to broadcasts of intrinsics

---

src/AddImageChecks.cpp
src/CSE.cpp
src/CodeGen_ARM.cpp
src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/IR.h
src/Prefetch.cpp
src/ScheduleFunctions.cpp
src/Simplify_Cast.cpp
src/Simplify_Let.cpp
src/VectorizeLoops.cpp
test/correctness/mul_div_mod.cpp
test/correctness/simplify.cpp

There's a pretty common pattern (especially in a WIP branch) of doing something like:
```
const Call *c = e.as<Call>();
if (c && (c->is_intrinsic(Call::X) || c->is_intrinsic(Call::Y))) {
...
}
```
The call declaration can't be made part of the if, because we can't assign it and use it as part of another condition. This PR adds a helper for this:
```
if (const Call *c = Call::as_intrinsic(e, {Call::X, Call::Y}) {
...
}
```

Add as_intrinsic helper

---

src/CodeGen_LLVM.cpp
src/IROperator.cpp
test/correctness/compute_with.cpp

- Lowering of shifts in CodeGen_LLVM could generate dead code.
- Some small refactors/simplifications of type matching in IROperator.

Small cleanups/fixes

---

src/CodeGen_ARM.cpp
src/CodeGen_C.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/FastIntegerDivide.cpp
src/HexagonOptimize.cpp
src/IROperator.cpp
src/Type.h

Add helpers for widening and narrowing types. This has a little utility on master, but is mainly peeling off a change from another WIP branch.

Add Type::widen and Type::narrow helpers.

---

apps/CMakeLists.txt
apps/linear_algebra/benchmarks/CMakeLists.txt

- Skip all app tests that are labeled as 'benchmarks'
- Specify `--build-noclean` to avoid unnecessary full rebuilds

Improve speed of testing apps/

---

src/CodeGen_LLVM.cpp

When we codegen something like f[ramp(x + 1, 2, 16)], where f is an
internal allocation, we subtract the 1, do the dense load f[ramp(x, 1,
32)] and then take the odd lanes of the result. The reason for this is
that it's likely that there's an f[ramp(x, 2, 16)] nearby, and aligning
down the x+1 to x means we can share the dense loads and just
deinterleave.
This PR does the same when there's no x, just an odd constant. This
means that cases like f[ramp(64, 2, 16)] + f[ramp(65, 2, 16)] now
generate much better assembly. In one case I have it speeds up an entire
pipeline by 8%, because aligning the loads in this way causes them to
all be promoted off the stack into registers.

Align the base when doing strided loads from constant addresses

---

src/IROperator.cpp
src/Simplify_Call.cpp

This PR does two things: simplify shifts that are known to be positive or negative, and avoid creating signed shifts in the first place when the RHS is a constant.

Simplify signed shifts more strongly

---

test/correctness/image_io.cpp

I noticed that this test takes a long time on the build bots. This seems like low hanging fruit to try to speed them up a little bit.

Reduce size of test image

---

src/Bounds.cpp
src/BoundsInference.cpp

Two changes here reduce the total time of `bench_fft 24 24` from 2 minutes down to 7 seconds.

Fix compile time regression in fft

---

src/AssociativeOpsTable.cpp
src/HexagonOptimize.cpp
src/Simplify.cpp
src/Simplify_Cast.cpp
src/Simplify_Internal.h
test/correctness/simplify.cpp

Currently, things like `shift_left(x, broadcast(2))` don't get simplified, and things like `shift_right(8, broadcast(1))` don't get constant folded. This PR fixes that.

Enable constant folding of broadcasted constants

---

.gitignore
CMakePresets.json
README_cmake.md

CMake 3.19 adds a new feature called [_presets_](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) that make it easier to store, name, and use, common sets of configurations for a CMake project.
This PR adds the necessary file (and documentation!) populated with presets for the following scenarios:
| Name             | Generator          | Build type     | Target                              | Dependencies    |
| ---------------- | ------------------ | -------------- | ----------------------------------- | --------------- |
| `gcc-release`    | Ninja              | Release        | as determined by selected compiler  | system-provided |
| `gcc-debug`      | Ninja              | Debug          | as determined by selected compiler  | system-provided |
| `msvc-release`   | …

Add CMake presets for 3.19+ users

---

run-clang-format.sh
run-clang-tidy.sh

Using the 'wrong' version of the tools will produce results out of sync with our presubmit tests, so add checking to ensure the user has their env set up correctly.

Add version-checking to the clang-tidy and clang-format scripts

---

.clang-format

After #5122 and #5513 it made sense to fix up the `.clang-format` file to use the option that was formerly commented and fix the file according to the published schema (use `c++11` instead of `Cpp11`). Running `run-clang-format.sh` resulted in no further changes.

Enable commented clang-format option. Fix schema.

---

src/CodeGen_ARM.cpp
test/correctness/simd_op_check.cpp

We care about count_leading_zeros, and this PR fills in some other gaps in coverage. Also add a few patterns, I think we should have non-rounding versions of instructions we have rounding patterns for.

Add simd_op_check tests and a few more patterns

---

apps/fft/CMakeLists.txt
src/Generator.cpp

The FFT JIT tests didn't have Halide.dll in their path. This fixes that.

Point fft JIT tests to Halide binary

---

src/AlignLoads.cpp

This improves the case when a smaller vector load is fully contained inside of the aligned native vector load. In the current implementation it will be handled in two passes: firstly, a small vector will be extended to the native vector size (slice from the unaligned native vector load), followed by the second pass where it will be actually aligned, which leads to a) double slice and b) load of vector of double native width. This change combines these two passes when possible to avoid double slice and double load.

Combine align and slice for the small vectors in align_loads

---

apps/interpret_nn/Makefile
apps/interpret_nn/benchmark.cpp
apps/interpret_nn/compare_vs_tflite.cpp
apps/interpret_nn/interpreter/model.cpp
apps/interpret_nn/interpreter/model.h
apps/interpret_nn/test/fully_connected_test.cpp
apps/interpret_nn/test/op_test_helper.h
apps/interpret_nn/tflite/tflite_parser.cpp
apps/interpret_nn/util/buffer_util.h
apps/interpret_nn/util/error_util.cpp
apps/interpret_nn/util/error_util.h

To make some integration with the Delegate code easier, I upgraded our logging code to mimic their usage pattern a bit. This is a little gratuitous but will likely pay off in the Delegate code.
- Replaced LOG_FATAL with CHECK(0) everywhere
- Added LOG(INFO/WARN/ERROR), all of which are wrappers that output to stderr (and also to __android_log on android)
- Made the guts of CHECK() a little more purpose-built
- Moved guts of Logger into a cpp file to hopefully reduce code bloat from logging
- Made inclusion of __FILE__ and __LINE__ info contingent on NDEBUG, to reduce internal info of logging that might be desirable to leave in release builds.
- Converted some (but not all) usage of std::cerr to use LOG(whatever).

Upgrade logging code in interpret_nn

---

apps/interpret_nn/Makefile
apps/interpret_nn/compare_vs_tflite.cpp
apps/interpret_nn/interpreter/model.cpp
apps/interpret_nn/tflite/tflite_parser.cpp
apps/interpret_nn/tflite_exploder.cpp

Some work to enable running compare_vs_tflite on-device in subsequent PRs...
- Downgrade the TFLite version we target to 2.3.x
- Add TFLITE_VERSION define to avoid losing changes needed for 2.4.x (etc)
- Switch to relying on a shared-library build of TFLite (rather than static library), as getting static-library builds for Android is apparently ~impossible without heavy customization of TF build files

Revamp TFLite glue code and versioning

---

src/LLVM_Runtime_Linker.cpp

This removes Comdat items from LLVM IR when linking a runtime for Mac OS or iOS. This would always be a failure with the current code and it is anticipated that this will either produce one valid symbol or fail with a multiple definition error. I have tested this with the GPU context consistency changes and it does fix the error that code was running into.

Solve the COMDAT in runtime failing on Mac OS X problem once and for all.

---

test/correctness/introspection.cpp

Fixes introspection test failure on Mac OS when compiled via Makefile.

Pathnames may or may not be absolute so loosen comparison to allow for this.

---

apps/harris/CMakeLists.txt
apps/hist/CMakeLists.txt
apps/iir_blur/CMakeLists.txt
apps/lens_blur/CMakeLists.txt
apps/max_filter/CMakeLists.txt
apps/unsharp/CMakeLists.txt

Some of them weren't the same as the Make equivalents, which meant that the test diverged between the two build systems (sometimes causing failures due to too-large images).

Update images used in apps/ tests

---

apps/interpret_nn/Makefile
apps/interpret_nn/compare_vs_tflite.cpp
apps/interpret_nn/halide/common_halide.cpp
apps/interpret_nn/run_compare_on_device.sh

round_shift_right() now mimics the logic of ARM rounding-shift instructions (and should emit them once some upstream changes land). Tweaked compare_vs_tflite to try to minimize error reporting as a result.
(Note, this is  additive to the change in https://github.com/halide/Halide/pull/5537)

Fix rounding-shift, tweak compare_vs_tflite

---

src/Memoization.cpp
test/correctness/memoize.cpp

Generally references to buffers are not allowed in memoization keys without the programmer explicitly using memoize_tag as if one has to do a lot of image accesses to construct the key, memoization is unlikely to be performant. The code that enforces this also treats accesses to the min/extent/stride, etc. of the buffer as a buffer access. This seems problematic as those values are conceptually parameters to the filter, just with more complicated names. Not allowing them in memoization keys by default causes tricky to diagnose errors if one uses the extent of an input in an RDom which is then use in a memoized Func.
The code pattern here is a bit heuristic in that I can't think of a case where a Var has a buffer but the reference isn't to a field of the buffer. This is something to think …

Modify memoization code to allow using min/extent/stride of an input.

---

src/CodeGen_OpenGL_Dev.cpp

OpenGL(Compute) generates `select` IR for `pow(a, b)` function, which can be simplified when `a` or `b` is const.

Add possible simplify to GL(Compute) `pow` function

---

src/CodeGen_C.cpp

Remove <iostream> from the code generated by CodeGen_C

---

src/Expr.h

`StrongestExprNodeType` wasn't updated when `VectorReduce` was added

fix StrongestExprNodeType for rewriter

---

README.md
README_cmake.md

Hopefully this will make understanding the CMake build easier when using a custom-built LLVM.
This also adjusts `README.md` to use the same directory layout as `README_cmake.md`.

Better document how LLVM_DIR works.

---

apps/onnx/Makefile
apps/onnx/onnx_converter.cc

The protoc usage happened to work when building in the app folder but often failed when building from the toplevel Makefile. Also, drive-by silencing of noise from curl, and drive-by fix of "redundant copy" warning in onnx_converter.cc.

Fix fragile Makefile for apps/onnx

---

src/HexagonOptimize.cpp
src/IR.cpp
src/IR.h
src/IRPrinter.cpp

This reduces the volume of IR output in some cases. We get this:
```
sum$14[ramp(0, 1, 32)] = (int32x32)vector_reduce(Add, (broadcast(int32x2(int8x2(ramp(0, 1, 2))), 32)*int32x64((int16x64)in_i16[ramp((op_v__w____vdmpy_v__h__r__b__112.s0.x.x*64) - in_i16.min.0, 1, 64) aligned(64, 0)])))
```
Instead of this:
```
sum$14[ramp(0, 1, 32)] = (int32x32)vector_reduce(Add, (shuffle(int32x2(int8x2(ramp(0, 1, 2))), 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1)*int32x64((int16x64)in_i16[ramp((op_v__w____vdmpy_v__h__r__b__112.s0.x.x*64) - in_i16.min.0, 1, 64) aligned(64, 0)])))
```

Add special case for printing broadcast shuffles

---

dependencies/wasm/CMakeLists.txt
test/performance/nested_vectorization_gemm.cpp

- If wasm_threads is in the target string, be sure to launch the external shell with --experimental-wasm-threads.
- All the test/performance tests should detect wasm and explicitly skip

Fix minor wasm issues

---

src/CodeGen_Hexagon.cpp
src/CodeGen_Hexagon.h
src/CodeGen_LLVM.cpp

This PR is an alternative to #5503 to address #5559. This is similar to #5548.
It moves all of `CodeGen_Hexagon` into an internal linkage namespace, and wraps the whole thing in an `#ifdef WITH_HEXAGON`.
I wanted to do this for all of the `CodeGen_*` classes, but this only works for `CodeGen_Hexagon` because it isn't used by `CodeGen_GPU_Host` as a template parameter.
I think we should move the runtime calls generated by `CodeGen_GPU_Host` to a separate lowering pass (like how HexagonOffload does it), and then we could do this for the rest of the `CodeGen_*` classes as well. I think most of the complexity there is GLSL, which might go away soon (#5475)?

Move CodeGen_Hexagon to internal linkage and don't include it without WITH_HEXAGON

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
src/HexagonOptimize.h
src/runtime/hvx_128.ll

This PR fixes bugs:
- vmpa is not correctly interleaved after refactoring in #5424. This PR reverts the changes associated with this. This *does* have test coverage in simd_op_check, but we aren't running apps/simd_op_check on the build bots currently.
- LetStmt visitor in EliminateInterleaves is incorrect. This has been a bug for a long time, it only appears if there are dead lets in the IR, which doesn't happen in the default lowering configuration (but does happen when attempting to debug by commenting off some of the passes).
It also removes VtmpyGenerator. This has been disabled for a long time, and now we have VectorReduce. Additionally, I have a WIP pass in another branch that finds vector reductions in a target independent lowering pass. If we try to bring back automatic finding …

Fix several bugs on Hexagon and some cleanup

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

- Remove some dead code
- The make_alignment wrapper was probably to accommodate older versions of LLVM.

Remove unused wildcards and old wrappers from CodeGen_LLVM

---

apps/interpret_nn/Makefile
apps/interpret_nn/compare_vs_tflite.cpp
apps/interpret_nn/interpreter/model.cpp
apps/interpret_nn/tflite/tflite_parser.cpp
apps/interpret_nn/tflite_exploder.cpp

TFLite v2.4.0 has gone final, and there is a prebuilt version in AAR form for us to use on Android, so let's upgrade the code to assume 2.4 as a baseline.

Upgrade to TFLite 2.4.0

---

src/Target.cpp

FreeBSD doesn't use getauxval, but elf_aux_info.

Fix build on FreeBSD/powerpc64

---

src/VectorizeLoops.cpp

I discovered some code where a full 3/4 of lowering time was pointless checking if scalarized versions of vector let stmts needed constructing. Now that we have robust simplification of horizontal reductions and vector slices I believe this code has become unnecessary and can be deleted.

Delete lane extraction code in vectorization

---

apps/interpret_nn/Makefile
apps/interpret_nn/compare_vs_tflite.cpp
apps/interpret_nn/delegate/exported_symbols.linux
apps/interpret_nn/delegate/exported_symbols.osx
apps/interpret_nn/delegate/halide_delegate.cpp
apps/interpret_nn/delegate/halide_delegate.h
apps/interpret_nn/delegate/halide_delegate_adaptor.cpp
apps/interpret_nn/run_compare_on_device.sh
apps/interpret_nn/tflite/tflite_parser.cpp

This builds a TFLite delegate as a shared library, and modifies compare_vs_tflite (and run_compare_on_device) to run *three* ways by default:
- vs "plain" TFLite
- vs TFLite when using our Delegate
- calling our Halide code 'directly'
This is still very rough and has oodles of rough edges and TODOs for things that need improvement, but it does run mobilenetv2 correctly (on desktop and on android). Pushing this out as a PR to preserve work over vacation (and for Dillon to take a look if he likes) but no pressure to land this just yet -- it's still a WIP so it can wait to land if we like (or land now with the understanding that it's still very rough).

Add initial support for building a TFLite Delegate

---

Makefile

Hello,
This is referring to my Issue #5579 . All the change consist of is to fix that proper error message.
Image included was of the original cloned repo first attempting to build with Make.
Thanks!
Fixes #5579

replaced indentation in line 20 with spaces to show proper error message

---

src/CodeGen_PTX_Dev.cpp
src/Target.cpp

LLVM10 can't handle that version of Cuda; we never noticed till now because we didn't have a buildbot with a GPU that could handle it. Modify the sniffers to cap capability at 75 for LLVM10 builds, and fail with user errors if that capability is explicitly requested.

Don't allow CUDACapability80 on LLVM10

---

src/runtime/metal.cpp
test/error/CMakeLists.txt
test/error/metal_threads_too_large.cpp

Originally, this checking will be asserted by Metal API Validation
in Xcode, otherwise the program will crash or output wrong results.

Add max threads checking for Metal

---

CMakeLists.txt

Since our next release will be based on LLVM 11.0.0, we should set the master version to 11. Yes, we still support LLVM trunk which is version 12, but we'll just bump our version once that one is officially released.
Fixes #5259

Set version to 12.0.0.

---

src/IROperator.cpp

`lerp()` was checking `lanes()` instead of `bits()` for the type of the `zero_val`

fix lerp() to check bits instead of lanes

---

Makefile

Apparently 11.1 was released but our Makefile only allows for 11.0.

Add 11.1 as an acceptable LLVM version

---

apps/unsharp/unsharp_generator.cpp

As discussed on Gitter, this schedule uses tile sizes that are too large for some macs. This change shrinks the tile size to 16x16 instead of 32x32 for the Metal API.

Shrink tile size to fit in Mac Mini GPU memory.

---

python_bindings/CMakeLists.txt
python_bindings/readme.md
python_bindings/requirements.txt
python_bindings/src/CMakeLists.txt
python_bindings/src/PyHalide.cpp
python_bindings/stub/PyStubImpl.cpp
src/Generator.cpp

Users who have 2.6.0 installed system-wide run into an issue with a hack with a workaround etc. etc. in pybind11 that ultimately means it chokes on the `SYSTEM` argument to `pybind11_add_module` on v2.6 but not on v2.5.
Since we're already diverged from Ubuntu, we might as well upgrade to pybind11 2.6, which also happens to fix a bug that lets us remove one of our own awkward workarounds.

Upgrade pybind11 to 2.6.x

---

python_bindings/stub/PyStubImpl.cpp

It's built separately from the rest of the Python bindings and could get out of sync separately.

Add Python & PyBind version checking to PyStubImpl.cpp

---

Makefile
src/CMakeLists.txt
src/Lambda.cpp
src/Lambda.h

Functions/methods that are part of the Halide public API should (generally) not be inline, to ensure the function instantiation is always in libHalide.

Add Lambda.cpp

---

src/BoundaryConditions.h
src/Dimension.h
src/Func.cpp
src/Func.h
src/Generator.h
src/Pipeline.cpp
src/Pipeline.h

These were all marked as deprecated in Halide 11 (and probably Halide 10 too); let's go ahead and remove them in Halide 12.

Remove all deprecated methods for Halide 12

---

src/FindIntrinsics.cpp
test/correctness/intrinsics.cpp

Also, we weren't handling it in lower_intrinsic (because CodeGen_LLVM has a good default handler for it, and we don't have coverage of saturating arithmetic in CodeGen_C).

Lower saturating arithmetic without widening

---

python_bindings/Makefile
src/Introspection.cpp

The OSX buildbot has been crashing intermittently on some python tests; debugging showed that in some situations, Introspection's calls to `backtrace()` include bogus addresses (eg 0x08), which cause segfaults when you try to inspect memory near them. The reasons for this aren't entirely clear -- for instance, it only seems to repeat reliably when using the Makefile rather than CMake, and only when doing an 'out-of-tree' build. Rather than try to run this to ground further, this PR just checks for address fields that seem obviously unreasonable (first 256 bytes of address space) and ignore them.

FIx intermittent OSX Python crash

---

cmake/HalideTargetHelpers.cmake

User @calein in #5670 reported that `i686` was not getting detected properly as an `x86` target when our CMake code tries to translate the CMake environment into a Halide target.
This (ought to) fix that.

Fix target detection for i686

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp

The C++ versions were removed for Halide 12 already, but I missed the Python wrappers.

Remove deprecated variants of infer_input_bounds() in the Python bindings

---

test/correctness/simd_op_check.cpp

Recent changes to the final wasm-simd spec means that some instructions aren't being generated (and may not even exist in the same form). Commented out for now; we need to revisit this once the LLVM backend for wasm gets closer to up-to-date with the final spec.

Disable a few more wasm-simd ops in simd_op_check

---

src/WasmExecutor.cpp
src/runtime/fake_thread_pool.cpp

- The atomic() schedule directive ends up calling halide_mutex_array_create(); for users of fake_thread_pool, this quietly returned null, leading to misleading error messages. Instead, return a non-null (but unused pointer), and continue to have other calls ignore it, since we don't really need a mutex without threads in this case.
- Also: the WebAssembly JIT cannot handle threads due to WABT limitations; added an assert to fail right away if you request compiling with wasm_threads.

Avoid bogus out-of-memory error for multiple_scatter under wasm

---

src/runtime/write_debug_image.cpp

Specifically, don't call fclose() on a null ptr, as that can crash.
Also added some code to avoid implicit int->bool conversions.

ScopedFile in write_debug_image needs sanity check

---

src/runtime/x86.ll
src/runtime/x86_cpu_features.cpp

Some newer X86 extensions require setting ecx when calling cpuid, for
example AVX512BF16 support is queried using cpuid(eax=7, ecx=1).

Add ecx support for runtime X86 cpuid

---

test/generator/CMakeLists.txt

Re-enabled wasm testing, which revealed breakage of the generator_aot_gpu_multi_context_threaded target (the runtime isn't being linked properly). Since this test isn't useful under wasm at the present time anyway (relies on GPU support), just skipping it entirely for those targets.

Disable generator_aot_gpu_multi_context_threaded under wasm

---

src/LowerWarpShuffles.cpp
test/correctness/register_shuffle.cpp

**Backports:** Fix cuda warp shuffle issue for narrow types (#5624)
* Fix cuda warp shuffle issue for narrow types
In the case where no shuffle was necessary, we were upcasting the type to 32-bits needlessly and causing chaos.
(cherry picked from commit 57083e47d6a71f9d8864f1cce138346dcb8c9a65)

Backport #5624 to 11.0.0 (Fix cuda warp shuffle issue for narrow types)

---

apps/lens_blur/lens_blur_generator.cpp

The lens_blur app uses rgb_small.png, but had estimates for a different image. This caused autoscheduling the app with adams2019 to end with:
```
Error: Output buffer final is accessed at -192, which is before the min (0) in dimension 0
```

Update lens_blur estimates

---

src/IRMatch.h
src/Simplify_Internal.h
src/Simplify_Max.cpp
src/Simplify_Min.cpp

The bulk of the time in the simplifier is simplifying already-simple expressions, and the bulk of the time there turned out to be the ref counting required to construct the IRMatcher object (which took a copy of the expressions). This PR changes it to capture  expressions by reference instead, which had large effect on lowering time (more than 2x on local laplacian!). 
Before:
```
$ time bin/host/local_laplacian.generator -g local_laplacian -e stmt -o bin/host -f local_laplacian target=host auto_schedule=false
real	0m1.698s
user	0m1.686s
sys	0m0.012s
```
After:
```
$ time bin/host/local_laplacian.generator -g local_laplacian -e stmt -o bin/host -f local_laplacian target=host auto_schedule=false
real	0m0.765s
user	0m0.749s
sys	0m0.016s
```
Some cleverness was required to stop people from …

Capture Exprs by ref in IRMatch

---

src/CodeGen_Hexagon.cpp
src/runtime/hvx_128.ll
test/correctness/simd_op_check_hvx.cpp

The patch adds:
- Add "+hvxv6x" to mattrs
- Correct isa_version in simd_op_check_hvx
Some vsplat tests were failing with v62 and a vasl test with v65. Adding the hvx version flag in mattrs fixes the failures.
@dsharletg @pranavb-ca Please review

[HVX] Correct isa_version simd-op-check-hvx

---

src/runtime/x86_cpu_features.cpp

The Sapphire Rapids target feature controls whether BF16 and VVNI X86
instructions are emitted. Support for both of these is checked in the
Halide compiler, but BF16 is not checked in the runtime as it required
extending the cpuid functionality.
Now we have that cpuid functionality we can add the BF16 check.

Check Sapphire Rapids AVX512BF16 support in runtime

---

src/runtime/HalideBuffer.h
src/runtime/HalideRuntime.h

Without this, allocating large buffers from an application fails with a segfault.

HalideBuffer: cast offset operand to ptrdiff_t to avoid overflow

---

src/Simplify_EQ.cpp
src/Simplify_Stmts.cpp

Some statements and expressions get crafted anew each time when
repeatedly resimplified. This PR fixes all the cases I could find.
No significant changes to most pipelines. Reduces total compile time by 7% on one particularly pathological example.

Don't make new IR nodes if nothing changed when simplifying

---

src/Bounds.cpp
src/CodeGen_C.cpp
src/CodeGen_Internal.cpp
src/CodeGen_Internal.h
src/CodeGen_LLVM.cpp
src/IR.cpp
src/IR.h
src/IROperator.cpp
src/IROperator.h
src/Simplify_Call.cpp

This PR turns mux into an intrinsic, instead of immediately unpacking into a select tree. When you mux a lot of values it produces a deeply nested select tree, and this is pathological for a few different lowering stages (mostly unrolling). Turning it into an intrinsic (lowered to selects during codegen) speeds up lowering time of one big pipeline by about 3x (174s -> 57s)

Add mux intrinsic

---

src/CodeGen_X86.cpp
src/runtime/x86_avx512.ll
test/correctness/simd_op_check.cpp

The vcvtne2ps2bf16 instruction combines two f32x16 vectors and converts
them to one bf16x32 vector. We can use this to support converting a
f32x32 vector to bf16x32 vector by splitting the input vector into two.

Add support for AVX512 f32x32 to bf16x32 conversion

---

src/Generator.cpp
src/Generator.h
src/Parameter.cpp
src/Parameter.h

The "default" value for a scalar param is rarely used -- it's currently only possible to specify foran Input in a Generator, and that value only shows up in the generated metadata for AOT compilation.
This PR refactors this so that instead of being maintained solely as a hack in Generator data structures, it's moved into Parameter as its own field.
This seems like a lot of work some something of marginal use, but I'm reluctant to suggest removing it entirely (it's possible it could break someone's code), and refactoring it in this way will make some subsequent Generator refactoring easier to understand and review.

Refactor code for dealing with default values of scalar Params

---

apps/HelloPyTorch/Makefile
apps/HelloPyTorch/setup.py

(1) As of (at least) v1.7.1, PyTorch requires C++14 to compile C++ extensions
(2) As of pip 21.x, the `-b` flag is ignored (build files always use `/tmp` or the equivalent), so remove it to ignore annoying warnings

Fix apps/HelloPyTorch

---

src/runtime/HalideBuffer.h
src/runtime/device_buffer_utils.h
src/runtime/halide_buffer_t.cpp

These changes are based primarily on visual code inspection in areas identified with some simple grep'ing as potentially problematic, with a subset of them verified to fix #5713 (e.g., I have *not* tested the data copy functions).  As I am not that familiar with the codebase, I ask that the reviewer please check the runtime sources to see if I might have missed other similarly affected lines, and I'll be happy to add such additional fixes to the PR.
I will also note that there are various data types being used for offset computations, including at least `int64_t`, `uint64_t`, and `ptrdiff_t`.  It might be better to be more consistent and use the datatypes that are actually intended for pointer calculations, like `ptrdiff_t`.  The only such changes included here are to avoid overflow, not …

runtime: fix pointer calculations to avoid overflows. Fixes #5713.

---

src/RegionCosts.cpp

This pessimistically assumes the mux doesn't get unrolled.
Fixes #5723

Treat the cost of a mux as just the cost of evaluating the args.

---

src/Generator.cpp
src/Generator.h

Some code churn cherrypicked from another PR; this just changes a direct member access to a getter function in internal Generator code (to some upcoming changes simpler). Split as a separate PR to reduce churn elsewhere.

Minor refactoring in Generator code

---

python_bindings/Makefile
python_bindings/src/PyTuple.cpp

It's not necessary, and it prevents these four tests from being executed with `make test` or `make test_correctness`, etc

Remove unnecessary .PHONY from python_bindings/Makefile

---

apps/glsl/opengl_test.cpp
src/CodeGen_OpenGL_Dev.cpp
src/Target.cpp
src/runtime/mini_opengl.h
src/runtime/opengl.cpp
src/runtime/opengl_egl_context.cpp
test/opengl/float_texture.cpp
test/opengl/inline_reduction.cpp
test/opengl/lut.cpp
test/opengl/multiple_stages.cpp
test/opengl/produce.cpp
test/opengl/save_state.cpp
test/opengl/sumcolor_reduction.cpp
test/opengl/varying.cpp

I'm trying to fix the outstanding EGL bugs on the buildbots before releasing v11. But when trying to repro locally, I ran into a _new_ set of bugs!
1. I noticed that `USE_RUNTIME` is broken because the `egl` backend has to match across all runtime targets. So I added that to the `matching_features` list in Target.cpp
2. This one is more serious. Some EGL implementations can unload their libraries _before_ (or perhaps concurrently with) `__attribute__((destructor))` functions. This causes the EGL device-release to call a function in an unmapped page and segfault. I tried re-querying the location of one of the symbols, but it's apparently cached so the best I could do was explicitly release the device before main exits in the GLSL app.

Fix EGL bugs

---

src/Bounds.cpp
src/CodeGen_LLVM.cpp
src/StorageFolding.cpp

- Show predicate on `Box`es
- Don't debug(3) Stmts in codegen, this produces a quadratic amount of debug output
- Fix confusing debug output from storage folding

A few small debug output improvements

---

cmake/HalideTargetHelpers.cmake
python_bindings/CMakeLists.txt
python_bindings/readme.md
python_bindings/requirements.txt
python_bindings/src/CMakeLists.txt
python_bindings/src/PyHalide.cpp
python_bindings/stub/PyStubImpl.cpp

This backports #5644 and #5675 to version 11.0.0 ahead of release.
**This PR should be REBASED, not squashed**

Backport outstanding changes to 11.0.0

---

Makefile
apps/harris/CMakeLists.txt
apps/hist/CMakeLists.txt
apps/iir_blur/CMakeLists.txt
apps/lens_blur/CMakeLists.txt
apps/max_filter/CMakeLists.txt
apps/unsharp/CMakeLists.txt
cmake/HalideTargetHelpers.cmake
python_bindings/CMakeLists.txt
python_bindings/readme.md
python_bindings/requirements.txt
python_bindings/src/CMakeLists.txt
python_bindings/src/PyHalide.cpp
python_bindings/stub/PyStubImpl.cpp
run-clang-format.sh
src/CodeGen_C.cpp
src/CodeGen_PTX_Dev.cpp
src/Target.cpp

This backports #5388, #5403, #5538, #5617, #5640, #5644, and #5675 to release 10.0.1 (we should cut this soon, too).
**This PR should be REBASED, not squashed**

Backport outstanding changes to 10.0.1

---

src/Deinterleave.cpp
src/Simplify_Call.cpp
src/VectorizeLoops.cpp
test/performance/nested_vectorization_gemm.cpp

There was a case (illustrated in the updated performance test) where we really should do distinct vector loads and then interleave. Fortunately we have a pass for this, so I just taught it to handle this pattern.

Better handling of sparse blurs using udot/sdot

---

apps/local_laplacian/local_laplacian_generator.cpp

local laplacian's upsample used fix kernel weights and alternating kernel tap locations. This PR changes it to fixed tap locations and alternating weights, which is more typical and about 20% faster because the codegen is a lot simpler.

Fix goofy local laplacian upsample

---

apps/interpolate/Makefile
apps/interpolate/interpolate_generator.cpp

- The boundary condition on the 4th pyramid level is wrong, and results in incorrect outputs for ~half the image in each dimension.
- downsampled[0] is consumed pointwise, so just inline it. Seems to speed things up by 0-0.5ms.
- Add extra generator outputs, like other apps do.

Interpolate app improvements

---

.github/workflows/presubmit.yml
Makefile
apps/fft/funct.h
run-clang-format.sh
src/BoundaryConditions.h
src/Buffer.h
src/Func.h
src/Generator.h
src/IRMutator.h
src/IROperator.h
src/IRVisitor.h
src/ImageParam.h
src/Pipeline.h
src/RDom.h
src/Realization.h
src/Tuple.h
src/runtime/HalideBuffer.h
tools/RunGen.h

Reformat code as necessary due to trivial differences in v10 vs v11.
Motivation: (1) keep tooling up to date, (2) make it easier to drop support for LLVM10 from master.

Upgrade clang-format rules to use v11 rather than v10.

---

test/correctness/interpreter.cpp

This disables the test on the specific target for which it is failing. The test is still run under opencl, but only on linux.

Workaround for issue #5738

---

python_bindings/src/PyEnums.cpp
src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_RISCV.cpp
src/CodeGen_RISCV.h
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h

`mabi` is introduced because target triple doesn't encode ABI info,
and `HL_LLVM_ARGS="-riscv-v-vector-bits-min 128"` is required to enable fixed vectors to RVV codegen.

Add initial support for RISCV RVV features

---

src/CodeGen_RISCV.cpp

named ABIs are defined in
https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#named-abis

Fix misspelling of an ABI name

---

python_bindings/stub/PyStub.cpp
python_bindings/stub/PyStubImpl.cpp
src/Generator.cpp
src/Generator.h

Various minor code changes found during refactoring work; cherry-picking here to reduce noise later:
- de-inlining methods in Generator.h
- removing forward decls for nonexistent classes
- avoiding extern declarations that can trivially be avoided by just including Halide.h
- generator_main() should emit to the stream passed in (rather than calling user_error)
- other stuff

Grab-bag of minor Generator-related cleanups

---

python_bindings/correctness/pystub.py
python_bindings/stub/PyStubImpl.cpp

There are two calling conventions that are sensible when calling a Generator from Python:
- Inputs are specified via keyword arguments (verbose but more readable)
- Inputs are specified via positional arguments (terse but more like C++)
However, the current PyStub implementation also allows for mixing positional and keyword forms of input (as long as no input is specified multiple times). This change removes that possibility (requiring either all-keyword or all-positional for inputs). I'm not sure why I thought this was a good option originally, but upon reflection (and examination of existing code), calls written in this way tend to be a confusing mess that require too much care when reading, and I think we'd be better off just forbidding this entirely.
Note that this technically is a …

Constrain calling convention for PyStub

---

src/CodeGen_LLVM.cpp
test/correctness/simd_op_check.cpp

The final revision of the wasm simd128 spec (https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md) added some ops and tweaked some others. This just augments the wasm section of simd_op_check so that all the ops are referenced, with the new (or still-unimplemented) ops commented out with TODOs.
Most of the new ops will likely be implemented via pattern matching in Codegen_WebAssembly, but before that can happen in any efficient way, WABT needs to be updated to recognize all the ops in the final spec (it doesn't currently, and so we can't even load code with those ops without cratering). See https://github.com/WebAssembly/wabt/issues/1617 for tracking bug.
(Also: drive-by fix in CodegenLLVM to fix prettyprinting of some debug output)

Update simd_op_check for the final wasm simd128 spec

---

src/AsyncProducers.cpp
src/PartitionLoops.cpp
src/Solve.cpp
src/TrimNoOps.cpp
src/UniquifyVariableNames.cpp
src/VectorizeLoops.cpp

- Fix cloning a semaphore more than once.
- Ignore promise_clamped in solve
- Acquire is not a no-op, even if it's empty
- Handle nested vectors in bounds_of_lanes
By @abadams:
- Don't count unlikely loops as inner loops for likely_if_innermost
- Handle LE/LT in bounds_of_lanes

Various bug fixes and improvements from dsharletg/sliding-window

---

cmake/HalideTargetHelpers.cmake

A small patch to respect the `QUIET` option when a user imports Halide in cmake, e.g., with `find_package(Halide QUIET)`.

cmake: respect find_package QUIET option

---

src/Simplify_Add.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Sub.cpp

These are almost all of the rules in <= four in terms of min/max/add/sub ops leaves that simplify to something with <= three leaves. Found via brute-force enumeration of all such expressions, and then bucketing them by evaluating them on a few random values, then testing the proposed rewrites with the formal verifier.
I left out things of the form: ```max(max(x, -x), 0) -> max(x, -x)```
While correct, that transformation actually hurts our ability to analyze that expression.

Add missing min/max/+/- rules

---

src/Simplify_Add.cpp
test/correctness/simplify.cpp

This PR adds some simplifier rules for nested broadcasts that result from vectorizing multiple dimensions. We had rules for nested broadcasts, and rules for broadcasts of the same size reassociated with one other expression, but not rules for nested broadcasts of different size also reassociated.
These rules are helpful for schedules that avoid performance regressions in #5784, by simplifying multidimensional vectorization when leaving buffers interleaved (and fuse doesn't work).

Simplifier rules for nested broadcasts

---

src/CodeGen_ARM.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_PTX_Dev.cpp
src/CodeGen_PowerPC.cpp
src/CodeGen_WebAssembly.cpp
src/CodeGen_X86.cpp

Currently Halide always sets the `ReadNone` and `NoUnwind` attributes to all intrinsic calls inside `CodeGen_LLVM::call_intrin`. The AMX intrinsics introduced in #5780 do access memory, so by setting the `ReadNone` attribute LLVM can do some invalid optimizations.
Instead of setting the attributes on the call to the intrinsic, we can set the attributes on the intrinsic function itself when registering it.
There were some raw calls to `call_intrin` in the ARM and Hexagon CodeGen backends. The ARM calls have been converted to use `call_intrin_overload`, while the Hexagon calls already use a wrapper function so this has been modified to set the attributes.

Move where intrinsic function attributes are set

---

test/correctness/memoize.cpp

Conversion from a pointer to an integer is "implementation defined"; in general, conversion to `uintptr_t` is reliable, but other conversions aren't. It turns out that for our arm32 compiler, casting a pointer to a `uint64_t` sign-extends, rather than zero-extends, causing unexpected behavior in memoize cache eviction *if* the pointer is in the top half of memory. The fix here is simple (cast to `uintptr_t` directly), but it brings up the question of where else in our codebase we might be doing direct conversions elsewhere in our code without noticing the potential UB.

Fix correctness_memoize on arm32

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp

(1) Both the 'deprecated' and new, non-deprecated variants existed back to at least LLVM10, and the deprecated variant was commented as deprecated at that point as well; the change in LLVM13 is that they are now annotated with LLVM_ATTRIBUTE_DEPRECATED so we get compiler warnings (and thus errors).
(2) The fixes are simply replicating what the old, deprecated methods did internally.

Fix deprecation warnings for trunk LLVM

---

src/BoundSmallAllocations.cpp
src/LICM.cpp
src/Lower.cpp
src/SplitTuples.cpp
src/TrimNoOps.cpp
src/UnrollLoops.cpp

This PR tweaks lower to avoid printing the IR when a pass does not change it. It also fixes a few cases of reconstructing IR when it has not changed.

Avoid printing the statement when it is unchanged

---

CMakeLists.txt
README_cmake.md

This replicates the approach LLVM already has of baking a use-cache option directly into the CMake options, without having to futz with changing CC/CXX/etc.

Add Halide_CCACHE_BUILD option for CMake

---

CMakeLists.txt
src/runtime/CMakeLists.txt

Use the CMake 3.20+ depfile features when they're available (avoids throwing one warning per initmod...). This will eventually be removed when we're able to upgrade to 3.20 (maybe in a year or two).
Fixes #5373

Conform to CMP0116 when using CMake 3.20+

---

src/CodeGen_C.cpp

print_type can be overridden in derived classes if needed.

Use print_type function when printing vector type definitions in CodeGen_C

---

test/performance/fast_sine_cosine.cpp

The fast versions are under 1.5x faster on at least one platform, but they are still faster. The print had the times switched so it was quite confusing.

In fast_sine_cosine, fix message, relax threshold

---

python_bindings/CMakeLists.txt
python_bindings/requirements.txt

Released January 2021 with various bug fixes, see https://github.com/pybind/pybind11/releases/tag/v2.6.2

Upgrade pybind11 to 2.6.2

---

src/CodeGen_ARM.cpp

It's currently possible to write schedules that generate the necessary shuffles for LLVM to generate the broadcasting dot product instructions, but LLVM only recognizes these when the shuffle is the second operand argument. This PR commutes the operands of dot products to make it possible to reliably generate these instructions.

Enable targeting broadcasting dot products on ARM

---

src/FindIntrinsics.cpp
test/correctness/simd_op_check.cpp

`cast` moves broadcasts outside widening casts, which was breaking the pattern matching done by LLVM for widening subtracts.

Fix missed pattern matching due to cast optimization

---

apps/hannk/Makefile
apps/hannk/halide/convolution_generator.cpp
apps/hannk/interpreter/ops.cpp
apps/hannk/test/conv2d_test.cpp
apps/hannk/test/depthwise_conv2d_test.cpp
apps/hannk/test/fully_connected_test.cpp
apps/hannk/util/hannk_log_tflite.cpp

Mostly just removing unused-variable warnings, to avoid pain in other build systems. Also modify the Makefile to ensure that NDEBUG is actually defined if OPTIMIZE contains `-O[something]`.

Allow clean compiles when NDEBUG is defined

---

dependencies/wasm/CMakeLists.txt
src/CodeGen_WebAssembly.cpp
test/correctness/simd_op_check.cpp

This version of wabt should be pretty close to the final wasm-simd128 spec (maybe it's there already); if so, this will allow us to proceed with updating our wasm codegen for simd properly.

Upgrade WABT to 1.0.22 and do some minimal update to codegen and simd_op_check for LLVM13.

---

src/Deinterleave.cpp
test/correctness/interleave.cpp

The deinterleave stores pass has some logic that generated loads from garbage addresses. It tries to recognize this:
```
A[ramp(0, 1, 8)] = B[ramp(0, 8, 8)]
A[ramp(8, 1, 8)] = B[ramp(1, 8, 8)]
A[ramp(16, 1, 8)] = B[ramp(2, 8, 8)]
...
```
and turn it into a single interleaving store. However not enough checking of the base of the ramps is done. The left-hand-side index just gets moved to the right hand side. So it triggers on something like:
```
A[ramp(foo, 1, 8)] = B[ramp(0, 8, 8)]
A[ramp(foo + 8, 1, 8)] = B[ramp(1, 8, 8)]
A[ramp(foo + 16, 1, 8)] = B[ramp(2, 8, 8)]
...
```
and then moves "foo" over into the loads. This is totally wrong and was causing crashes for me.
I just deleted this feature. That schedule can be better expressed by switching which vars are unrolled vs vectorized. It's …

Remove buggy deinterleave misfeature

---

apps/hannk/benchmark.cpp
apps/hannk/compare_vs_tflite.cpp
apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/interpreter/interpreter.cpp
apps/hannk/interpreter/interval.h
apps/hannk/interpreter/model.cpp
apps/hannk/interpreter/model.h
apps/hannk/interpreter/ops.cpp
apps/hannk/test/add_test.cpp
apps/hannk/test/average_pool_test.cpp
apps/hannk/test/concatenation_test.cpp
apps/hannk/test/conv2d_test.cpp
apps/hannk/test/depthwise_conv2d_test.cpp
apps/hannk/test/fully_connected_test.cpp
apps/hannk/test/max_pool_test.cpp
apps/hannk/test/op_test_helper.h
apps/hannk/test/pad_test.cpp
apps/hannk/test/quantize_test.cpp
apps/hannk/test/reshape_test.cpp
apps/hannk/tflite/tflite_parser.cpp
apps/hannk/util/hannk_log_tflite.cpp

We originally used a bespoke mix of data and dimensions, wrapping Buffers around them on the fly; this just uses Buffer as the fundamental type, simplifying things. As a bonus, it allows us to avoid copying read-only data (since Buffer can just reference the external pointer directly), making #5671 obsolete.

Revise hannk::Tensor to use H::R::Buffer<>

---

python_bindings/src/PyFunc.cpp
src/AllocationBoundsInference.cpp
src/BoundsInference.cpp
src/Func.cpp
src/Func.h
src/Generator.h
src/Schedule.h
test/correctness/align_bounds.cpp

This can be handy when you have an intermediate Func that is being tiled inside an outer Func and you want to ensure that it fits an exact multiple of tiles.

Add align_extent(), to align extent but not min

---

src/Simplify_Add.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Select.cpp
src/Simplify_Stmts.cpp
test/correctness/simplify.cpp

This PR makes it easier to simplify the expressions resulting from bounds inference on funcs with specializations.

Add simplifier rules helpful for specialization

---

README.md

Reference - https://foundation.llvm.org/docs/branch-rename/

[NFC] LLVM trunk is now called main

---

src/Bounds.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_X86.cpp
src/IR.h
src/IRPrinter.cpp
src/InlineReductions.cpp
src/InlineReductions.h
src/Monotonic.cpp
src/Simplify_Exprs.cpp
src/Simplify_Internal.h
src/Simplify_Mul.cpp
src/VectorizeLoops.cpp
src/runtime/x86_avx512.ll
test/correctness/simd_op_check.cpp
test/correctness/simd_op_check.h

This commit adds support to Intel VNNI saturating dot product
instructions vpdpbuds and vpdpwssd
This was accomplished by adding a new VectorReduce operation
to perform the saturating_add and exposing a new inline reduction
saturaring_sum. Users can then write
RDom r(0, 4);
f(x) = saturating_sum(i32(0), i16(i8(g(x + r)) * u8(h(x + r))))
bool override_associativity_test = true;
int vector_width = 4;
Var xo, xi;
f.update()
.split(x, xo, xi, vector_width)
.atomic(override_associativity_test)
.vectorize(r)
.vectorize(xi);
To lower the expression into a call to vpdpbuds.
Note that override_associativity_test is set to true or halide will fail
to prove the associativity of the saturating_add operation
Add support for VectorReduce::SaturatingAdd in CodeGen_LLVM
Code is correctly generated when …

Add support for AVX-512 VNNI saturating dot products

---

src/Simplify_Not.cpp

These don't actually help performance in a case I was looking at, but they do make the IR easier to read, and it is in fact simpler.

Add some not simplification rules

---

src/CodeGen_LLVM.cpp
src/Simplify_Call.cpp
src/Simplify_Let.cpp
test/correctness/simplify.cpp

Bug injected in #5856: the change in Simplify_Let.cpp was inadvertently stripping `strict_float()` calls that wrapped the RHS of a Let-expr, which can change results nontrivially in some cases. I don't think a new test for this fix is practical -- it would be a little fragile, as it would rely on the specifics of simplification that could change over time.
As a drive-by, also added an explicit rule to Simplify_Call to ensure that strict_float(strict_float(x)) -> strict_float(x) in *all* cases. (The existing rule didn't do this in all cases.)
Also added an assertion to Codegen_LLVM.cpp that no calls of the form strict_float(strict_float(x)) should ever be seen at that point.

Don't strip strict_float() from lets

---

src/EmulateFloat16Math.cpp
src/Float16.cpp
test/correctness/float16_t.cpp
test/correctness/strict_float.cpp

In EmulateFloat16Math.cpp, conversion from 32-bit float to 16-bit float could produce a NaN value when and infinity is correct. This is because for numbers larger than the exact infinity value, the mantissa could be non zero.
Add tests to cover this case, and float16 infinities in general.
Couple small style/comment cleanups.

Fix an issue in Halide's float16 compilation support. Add tests.

---

cmake/HalideTestHelpers.cmake
src/CodeGen_LLVM.cpp
src/Lower.cpp
src/Simplify_Not.cpp
src/Util.cpp
src/Util.h
test/error/CMakeLists.txt
test/error/run_with_large_stack_throws.cpp
tutorial/CMakeLists.txt

We used to use `#pragma comment(linker, "/STACK:8388608")` to enforce an 8MB stack on Windows. Unfortunately, clang-cl and lld-link don't support this pragma. I have opened a PR with upstream LLVM to correct this<sup>[1]</sup>, but it is clear we need a more robust solution than a transitive linker flag.
This PR adds a helper, `run_with_large_stack` to execute a `std::function<void()>` in a context where it will have at least 8 MB of stack space. Currently, it merely calls the function on Linux, but on Windows it creates a new fiber with the appropriate stack size and runs it there, blocking until the fiber returns.
It is applied in two places: around `lower()` and around the call to `compile_func` in CodeGen LLVM. This was sufficient to build locally on Windows, but there might be more …

Use fibers to guarantee stack size on Windows

---

apps/hannk/halide/average_pool_generator.cpp
apps/hannk/halide/max_pool_generator.cpp
apps/hannk/interpreter/ops.cpp
apps/hannk/interpreter/ops.h

The Pool operations require padding to get the correct answer in some cases.

Add padding to PoolOp

---

test/correctness/simd_op_check.cpp

Top-of-tree LLVM is now emitting comparisons for i64x2 simd operations in wasm, so enable the checks in simd_op_check.
Also, drive-by fixes to ensure some other checks only happen for LLVM13+.

Enable i64x2 comparisons in simd_op_check

---

src/Target.cpp

In the original spec, wasm-simd128 didn't have int64 or float64; the final spec adds these types, so this bit of code is outdated and incorrect.

Fix natural_vector_size for wasm 64-bit types

---

test/error/run_with_large_stack_throws.cpp

(1) Some downstream environments compile C++ without exceptions by default; this won't compile on those.
(2) We should check that assert-fail also errors out as expected.

error_run_with_large_stack_throws should compile without exceptions

---

src/CMakeLists.txt

* Group warnings by compiler / enable / disable / language (ie. C/C++-only)
* Remove two duplicated warning-disables for MSVC
* Remove Clang-only warning-disables from GCC, introduced by #5876

[cmake] Fix and reorganize warnings for building Halide

---

tools/package-windows.bat

This is actually all of the changes to this script from #5754 
`skip_buildbots` because the PR buildbots don't run the package scripts. Maybe they should.

Require LLD_DIR in zip/package.bat

---

CMakePresets.json
README_cmake.md
src/CodeGen_PyTorch.cpp
src/EliminateBoolVectors.h
src/Schedule.h
src/autoschedulers/adams2019/autotune_loop.sh
src/autoschedulers/mullapudi2016/AutoSchedule.cpp
src/runtime/HalideBuffer.h
src/runtime/HalideRuntime.h
src/runtime/HalideRuntimeD3D12Compute.h
src/runtime/HalideRuntimeHexagonDma.h
src/runtime/HalideRuntimeHexagonHost.h
src/runtime/HalideRuntimeMetal.h

This is split out from #5754 to make it easier to review later.
* Fix spelling mistakes found by Debian's lintian tool.
* Remove `-O2` from presets, which we determined added no value
* Remove reference to `WITH_APPS` from docs, which is now fully external.
* Add shebang line to autotune_loop.sh to make it a valid executable script (ie. `chmod +x`).
Please _rebase_ this, rather than squashing it to save me some trouble updating #5754

Code cleanup for Debian packaging 

---

README_webassembly.md
apps/HelloWasm/README.md
dependencies/wasm/CMakeLists.txt
src/CodeGen_WebAssembly.cpp
src/LLVM_Runtime_Linker.cpp
src/WasmExecutor.cpp
src/runtime/HalideRuntime.h

The intent of this PR is to make the (considerably) limitations of using threads in wasm more apparent.
Background: wasm_threads  relies specifically on wasm runtime providing an implementation of the `pthreads` API; at this time, this is only (AFAICT) available in wasm when compiling with Emscripten, *and* targeting a web/browser environment. (What's happening under the hood is that Emscripten is taking great pains to use WebWorkers to implement pthreads.)
In other wasm runtime environments (e..g WASI), there is still no story for useful thread usage; in particular, WASI has no provision for creating or joining threads.

 Improve wasm_threads documentation

---

CMakeLists.txt
packaging/CMakeLists.txt

This PR allows users to override the settings for `CMAKE_INSTALL_RPATH` and `CMAKE_CXX_STANDARD` from outside `CMakeLists.txt`. There should be no negative effects since the defaults are preserved. But users that want or need to override RPATH or the C++ standard get the freedom to do so.

CMake build: Add more user control

---

src/CodeGen_ARM.cpp
src/HexagonOptimize.cpp
src/IRMatch.cpp
src/IRMatch.h
test/correctness/simd_op_check.cpp

Add tests and logic needed to generate two or more `qxtn` instructions for double or triple saturating narrows. It's best not to do this in the user code, because on targets without saturating narrow instructions, it might be slower to do this rewrite.

Rewrite double and triple narrowing on ARM

---

src/runtime/HalideRuntimeD3D12Compute.h

This allows it to compile as pure C instead of C++.

Add missing "struct" before halide_type_t.

---

src/CodeGen_WebAssembly.cpp
src/runtime/wasm_math.ll
test/correctness/simd_op_check.cpp

LLVM removed the primitives we need (so our code can't be used), but it also doesn't seem to be generating the expected instructions directly (as claimed). Commenting out to un-break tests; issue has been reported to wasm/llvm team.

Comment out specializations for f64x2.convert_low_i32x4_s/u

---

python_bindings/src/PyEnums.cpp
src/CodeGen_ARM.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h
test/correctness/simd_op_check.cpp

This PR improves instruction selection for ARM:
- Add `Target::ARMv81a`, which enables LLVM to generate `sq{r}dmlah`/`sq{r}dmlsh`.
- Use ARM's saturating add/subtract intrinsic instead of LLVM's. LLVM fails to generate sqrdmlah when using LLVM's saturating add instead of ARM's.
- Add logic to catch more kinds of signed shifts. Previously, we let some of these fall through to CodeGen_LLVM, which lowered them unnecessarily to two unsigned shifts by an absolute value and a select.

Add Target::ARMv81a and improve shift instruction selection

---

test/correctness/compute_with.cpp
test/correctness/simd_op_check.cpp
test/correctness/simd_op_check.h

This PR changes simd_op_check to compile just one pipeline, the error checking pipeline. I think the motivation for the original design was to make the assembly to read when the op failed to generate as small as possible. However, the assembly with this isn't that much bigger, and since we compile only one pipeline, there is only one version of a lowered Stmt, so HL_DEBUG_CODEGEN output is easier to read, despite the slightly larger pipeline.
This should also speed up simd_op_check, which is up to ~15 minutes(!) on the ARM buildbots. Unfortunately the speedup is only ~20% (and not ~50%) because this only saves us from doing two Halide lowerings and two compile_to_llvm_module calls, but we still run LLVM twice to generate the assembly and object file.
There's another advantage to this: …

Speed up simd_op_check by only compiling one pipeline per op

---

test/correctness/vector_reductions.cpp

LLVM13 is causing vector_reductions to hang (https://reviews.llvm.org/D100099 appears to be the injection point). Disabling this test to unbreak the buildbots.

Temporarily disable hanging test

---

src/CodeGen_ARM.cpp

This removes CodeGen_ARM's Mul visitor. The mul visitor only did one thing differently from CodeGen_LLVM, which was to rewrite multiplies of 2^n +/- 1 to shifts and adds/subtracts. However, even if this is a helpful optimization, LLVM is rewriting it back to a multiply anyways. This codegen also doesn't use CSE, so it generates quite a lot of extra code.
After removing that, the visitor doesn't do anything differently from the base class.

Remove old multiply codegen for ARM

---

test/correctness/bit_counting.cpp

We claim `count_leading_zeros` and `count_trailing_zeros` return the size of the type in bits when the argument is 0. But, the test for these treated this as undefined behavior.

Update bit_counting test to reflect behavior we expect

---

src/CodeGen_Hexagon.cpp
test/correctness/simd_op_check_hvx.cpp

The patch tries to generate vdelta/vrdelta instructions for non-ramp
shuffles. Eg:
shuffle(lut_expr,
< 0,  1,  2,  3,  4,  5,  6,  7,
9, 10, 11, 12, 13, 14, 15, 16,
18, 19, 20, 21, 22, 23, 24, 25,
27, 28, 29, 30, 31, 32, 33, 34,
36, 37, 38, 39, 40, 41, 42, 43,
45, 46, 47, 48, 49, 50, 51, 52,
54, 55, 56, 57, 58, 59, 60, 61,
63, 64, 65, 66, 67, 68, 69, 70>)
can be generated using vrdelta.
The patch also fixes a bug where we bitcast vdelta/vrdelta with 16/32
bits elements to wrong type. User would see the below error:
llvm-project/llvm/lib/IR/Instructions.cpp:2905: static llvm::CastInst
*llvm::CastInst::Create(Instruction::CastOps, llvm::Value *, llvm::Type *,
const llvm::Twine &, llvm::Instruction *):
Assertion `castIsValid(op, S, Ty) &&
"Invalid cast!"' failed.

[Hexagon] Try vdelta/vrdelta before vlut for some shuffles.

---

test/correctness/fuzz_bounds.cpp

Sometimes we get lucky and it's still valid, but it's always wrong.

Don't use as_const_int() on temporaries

---

src/FlattenNestedRamps.cpp

With Target::LargeBuffers, min_lane is int64, but stride is an int, which then triggers an assert because the ramp is of mismatched types.

Fix flattening of ramps involving 64-bit mins

---

src/runtime/profiler.cpp

It seems this started failing on the buildbots recently:
```
src/runtime/profiler.cpp:301:13: error: variable 'alloc_avg' set but not used [-Werror,-Wunused-but-set-variable]
int alloc_avg = 0;
```

Fix build issue in runtime

---

src/LLVM_Output.cpp

Replace llvm::sys::fs::F_None with llvm::sys::fs::OF_None

---

apps/hannk/Makefile
apps/hannk/run_benchmark_on_device.sh
apps/hannk/run_compare_on_device.sh
apps/hannk/tflite/tflite_parser.cpp

- upgrade default TFLite to 2.5.0-rc2
- Revise build instructions & assumptions for TFlite (use CMake for it now instead of Bazel)
- Revised Android build instructions (now assumes that tflite is built locally rather than pulled from a prebuilt)
- Remove the need for flatc/flatbuffers
- Minor fixes to the run-on-device scripts

Upgrade hannk to tf2.5 + more

---

src/runtime/HalideBuffer.h

It's not safe to reinterpret a buffer to another buffer with a different value of D, even if D is smaller, because it moves the fields declared after the shape.

Fix bugs when D != 4
