halide/Halide

src/FindIntrinsics.cpp
test/correctness/intrinsics.cpp

This version lowers it without needing to widen, which is a large win on
x86 for 16 and 32-bit types (3.8x faster and 2.8x faster respectively).
It's a very slight slowdown for 8-bit because x86 doesn't have 8-bit
shift instructions.
Also drive-by typo fix.

Non-widening lowering of rounding shifts

---

apps/hannk/README.md
apps/hannk/halide/pool_generator.cpp
apps/hannk/interpreter/transforms.cpp

- Avoid external padding with boundary conditions, but still avoiding the code explosion from partitioning.
- Implement division in average pooling with a reciprocal.
This makes the pooling ops 2-4x faster.

Optimize pooling ops

---

apps/hannk/halide/depthwise_conv_generator.cpp

This PR uses a similar strategy as conv and fully connected for depthwise to separate some of the work that does not depend on the input itself.
Unfortunately on ARM this has negligible impact, it only saves a single register (replaces usubl with ushll), which doesn't help much.
On x86 this seems to be a nice optimization.

Optimize depthwise convolution

---

README_cmake.md
cmake/HalideGeneratorHelpers.cmake
cmake/HalideTargetHelpers.cmake
dependencies/llvm/CMakeLists.txt
dependencies/wasm/CMakeLists.txt
packaging/CMakeLists.txt
src/CMakeLists.txt

1. Add HEADER output to add_halide_library.
2. Use `$<BUILD_INTERFACE:...>` in generated target include paths in add_halide_library.
3. Clean up logic (reduce nesting) in add_halide_library.
4. Use lower-case names for local variables in add_halide_library.
5. Print paths to detected Clang and LLD config scripts.
6. Honor normal variable overrides for Halide_TARGET.
7. Consistently use Halide_* prefixes in CMake.

CMake clean-up

---

apps/hannk/compare_vs_tflite.cpp
apps/hannk/interpreter/interval.h
apps/hannk/interpreter/model.h
apps/hannk/util/buffer_util.h

This prevents mallocs for some degenerate cases where we need buffers with > 4 dimensions.

HalideBuffer should use D=max_rank instead of D=4

---

apps/hannk/README.md
apps/hannk/halide/elementwise_generator.cpp
apps/hannk/interpreter/ops.cpp

One of the 3 quantized multiplications is unnecessary. This speeds up add quite a bit (close to 50% on ARM).

Optimize add generator

---

src/runtime/HalideBuffer.h

- Use a more idiomatic loop pattern that the compiler might be more likely to understand.
- Sort strides by the strides of the buffer read, not the buffer written
- Handle the scalar special case outside `for_each_value_helper`.

Optimize copy_from/for_each_value

---

src/CodeGen_Hexagon.cpp

Implementing this TODO seems to work fine and produces better assembly in the hannk Add generator for hvx.
It codegens to a reduction tree of vector max instructions. Not the best thing it could possibly do, but perfectly reasonable and way better than the status quo.

Use a VectorReduce to determine if any lanes are true for Hexagon

---

src/runtime/HalideBuffer.h

Examination of compiled output (x86-64, clang w/ optimizer) shows slightly better codegen.

advance_ptrs() should use refs, not ptrs

---

apps/fft/main.cpp

Reverts halide/Halide#5985
This breaks the OSX ARM buildbot (?!). I guess I got too used to flaky build bots and merged this too quickly.

Revert "Stack input and filter to reduce generated code in FFT app"

---

apps/hannk/halide/conv_generator.cpp
apps/hannk/halide/copy_generator.cpp
apps/hannk/halide/depthwise_conv_generator.cpp
apps/hannk/halide/fully_connected_generator.cpp

- Enable conv to compile on Hexagon
- Avoid multiply-subtract
- Remove weird copy schedule hack that doesn't seem necessary any more
- Add a crazy hack that makes fully connected on ARM 10x faster in some cases

Small per-target performance tweaks for HANNK

---

src/CodeGen_X86.cpp
src/InlineReductions.cpp
test/correctness/simd_op_check.cpp

This started out more ambitious, but here's what I was left with after a while. Probably not commonly used, but also not very much code/complexity either.
A few other minor changes:
- Potential bug fix when generating pmaddwd for subtraction (negate could overflow).
- Renamed pmaddwd to dot_product, for consistency
- Cleaned up the VectorReduce patterns a little.

Add pmaddubsw support

---

apps/CMakeLists.txt
cmake/HalideGeneratorHelpers.cmake

In #5973 I removed the code that ensures Halide is visible to the generators by setting the `PATH`. This is a new solution that plays nice with vcpkg by copying the Halide DLL that was actually found by CMake to the appropriate directory. This should fix the apps not finding Halide / crashing as a result.
Also disables Hannk on Windows by default because I tripped over that while testing this.

Fix Windows apps

---

src/Simplify_EQ.cpp

Some rewrite rules in Simplify_EQ can perform incorrect rewrites because the predicate expression can overflow. Fixes #5998

Guard against overflow in constant folding for EQ rewrite rules (Fixes #5998)

---

Makefile

Else, it eliminates reference to global offset table
for symbols to be resolved from remote library causing runtime crash
with -debug option.

Add -fpic option to debug version on non-windows .ll file

---

src/CodeGen_C.cpp

* CppVector/NativeVector object doesn't have .replace() anymore.
* Initialize vector with zero to avoid warning.

Fix CodeGen_C::print_scalarized_expr

---

apps/local_laplacian/local_laplacian_generator.cpp

@LCJebe pointed out that the local laplacian upsample indexing is not right. This PR fixes it. Here's the output on filtering a flat disk before and after:

Fix local laplacian upsample

---

apps/hannk/util/model_runner.cpp
apps/hannk/util/model_runner.h

This allows us to silence some (but not all) of the noise that TfLite logs when we disable our own verbosity.

Add an ErrorReporter hook to TfLiteModelRunner

---

src/Simplify_Cast.cpp

Invaldiate alignment info if the type can't represent it

---

CMakePresets.json
packaging/CMakeLists.txt

Skipping buildbots because the testbranch builders don't run the package scripts.

Fix Windows ZIP package script.

---

README.md

Fixes #5961 
Fixes #5154
Fixes #4216
Fixes #5633  (by not mentioning it)

Update README for Halide 12 release.

---

apps/hannk/halide/depthwise_conv_generator.cpp
apps/hannk/interpreter/ops.cpp

At least one tflite model found in the wild uses this, so we must support it.

Allow negative output shifts in depthwise_conv

---

packaging/tgz/package.sh
packaging/ubuntu/package.sh

* Use `realpath` in place of `readlink -f`
* Accept `CMAKE_TOOLCHAIN_FILE` as an environment variable.
See also halide/build_bot#184

Fix tgz/package.sh

---

dependencies/wasm/CMakeLists.txt

We were using a variant of v8.9, but various late-breaking variations in the final spec implementation didn't make it into V8 until v9.1; using top-of-tree LLVM and EMCC require v9.1+ to avoid obscure errors.

Upgrade d8 version for wasm testing

---

src/AllocationBoundsInference.cpp
src/BoundSmallAllocations.cpp

This allows more code to compile without an error about lacking constant bounds for `MemoryType::Register` by relaxing the requirements a little. We now allow non-constant bound before storage flattening as long as there are no uses of the strides of the later dimensions. This allows us to potentially find a constant upper bound later in lowering, which is more likely due to extra simplification.
This also more aggressively simplifies the bounds from allocation bounds inference.

Strengthen constant upper bound logic slightly

---

apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/interpreter/interval.h
apps/hannk/interpreter/model.cpp
apps/hannk/interpreter/model.h
apps/hannk/interpreter/transforms.cpp
apps/hannk/tflite/tflite_parser.cpp

We previously allocated duplicate memory buffers for the input and output tensors, and just copied them back and forth as needed, which wastes memory and cycles.
Now, we declare the input and output tensors to be 'external', and update the host pointer before every interpreter run.
Note that dynamic tensors are still a bit of a special case: we still do duplicate allocations there (plus memcpy), because in the most general case we can't know the final size needed until we run the pipeline, but we need to allocate that output to run the pipeline. There are ways we could finesse this -- e.g., give dynamic tensors a lambda callback to allow them to resize the TFLite tensor and then use that storage -- but since dynamic tensors don't seem to be common or large in our test cases, I'm doing it …

Allow hannk-delegate input and output tensors to share memory with tflite

---

test/integration/CMakeLists.txt
test/integration/xc/CMakeLists.txt
test/integration/xc/add/CMakeLists.txt
test/integration/xc/generators/CMakeLists.txt

ExternalProject makes me sad. This gets rid of a lot of code without really making anything harder to use or more complex.
Skipping buildbots because this is only tested on GHA

Rework cross-compiling integration test to use simpler two-stage build

---

src/HexagonOptimize.cpp

I'm not sure if this is a bug (per se) or not, but: We define an intrinsic for `Call::hvx_gather`, and at several points check for `is_intrinsic(Call::hvx_gather)`, but we never actually create such a Call. Instead, `make_gather` just uses the naked string `"gather"`, which is not the same thing. How is this working? (Is it working?)
Opening this as a PR to gather input (no pun intended) about what's going on here.

Fix dubious "gather" intrinsic for hvx

---

apps/hannk/Makefile

This improved performance at one point, but it really shouldn't, and it seems like it doesn't help now.
More generally, there is no reason for this to improve performance. So even if it does improve performance, I don't think we should do it. LLVM might change and make the large_buffers version slower, and it would take us a long time to notice.

Remove large_buffers flag from HANNK

---

src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/FuseGPUThreadLoops.cpp
src/IROperator.cpp
src/Simplify_Call.cpp
src/Tracing.cpp
test/correctness/simplify.cpp

While investigating https://github.com/halide/Halide/issues/6067, I noticed that a handful of intrinsics that should probably be called as PureIntrinsic are being called as Intrinsic, thus missing out on hoisting opportunities:
- div_round_to_zero
- mod_round_to_zero
- stringify
- mux
- if_then_else (but only sometimes)
(Note that Call::size_of_halide_buffer_t should *not* be called as pure; the only use of it is typically `alloca()`, which already special-cases it efficiently, and hoisting it into a var would just require more fiddling at codegen time, for likely no gain.)

Convert some Intrinsic calls to PureIntrinsic

---

src/CodeGen_Internal.cpp
src/CodeGen_PTX_Dev.cpp

(Note: this may cause failures with our current LLVM nightly builds, but will be necessary for tomorrow's LLVM nightlies. Just getting it ready to land when necessary.)

Fix for upstream LLVM (Fixes #6079)

---

apps/hannk/interpreter/model.cpp
apps/hannk/interpreter/model.h
apps/hannk/interpreter/ops.h

We don't call these anymore, so remove them and the related TensorMap code.

[hannk] Remove unused Op::clone() methods

---

apps/hannk/configure_cmake.sh
apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/interpreter/model.cpp
apps/hannk/interpreter/model.h
apps/hannk/interpreter/tensor.h
apps/hannk/interpreter/transforms.cpp
apps/hannk/tflite/tflite_parser.cpp

It's redundant information that can be wrong and requires the builder of the Model to set the right flags on the right Tensors. Instead, build sets of the inputs and/or outputs at the spots we care and check for membership in those. Root-level inputs and outputs should generally be small in count so performance should be a wash.
Also: drive-by change to configure_cmake.sh to allow changing the build type.

[hannk] Don't mark Tensors as input or output

---

apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/interpreter/tensor.cpp
apps/hannk/interpreter/tensor.h
apps/hannk/interpreter/transforms.cpp

This is minor hygiene: instead of dancing on the host field, require the entire buffer to be 'external'; this will make it cleaner if we need to add usage of Buffers with non-host memory in the future, and is just generally less icky.
Also, drive-by addition of typedefs to Tensor for offsets and dimensions.
(Cherry-picked from #6097)

[hannk] Replace Tensor::set_external_host with set_external_buffer

---

apps/hannk/interpreter/tensor.cpp
apps/hannk/interpreter/tensor.h
apps/hannk/interpreter/transforms.cpp
apps/hannk/util/small_vector.h

- Make small_vector.h standalone-compilable
- Move Tensor::replace_all_consumers_with() to a local function near PadForOps to dodge a circular include dep between Tensor and Model

[hannk] Fix various build glitches for Bazel/Blaze

---

apps/hannk/util/model_runner.cpp
apps/hannk/util/model_runner.h

This allows you to run a compare operation against a bunch of graphs without exiting at the first one that is out-of-spec for comparison. (Useful when you want to verify that no *new* differences are introduced by a change.)

[hannk] Add --keep_going flag to ModelRunner

---

src/Bounds.cpp

Lots of calls to `find_constant_bounds` are unsimplified Exprs / have `likely` or `likely_if_innermost` in them. This was discovered from logging while working on bounds inference.

Call simplify and remove_likelies for find_constant_bounds

---

src/IROperator.cpp
src/IROperator.h
src/Monotonic.cpp

#6083 introduced a performance regression. The old logic worked in the presence of likely and promise_clamped, but the new logic does not. This PR fixes this performance regression.

Fix performance regression in is_monotonic

---

test/correctness/extern_producer.cpp

Small changes to sinf/cosf in libc has caused this test to start failing for us. This PR changes the test to use integers instead. Addresses the immediate issue in #6108, but leaving that open because I think we should remove unnecessary float usage in the rest of the tests as well.

Remove floats from extern_producer

---

python_bindings/src/PyEnums.cpp
src/CodeGen_ARM.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/ConciseCasts.h
src/IROperator.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h
src/runtime/aarch64.ll
src/runtime/arm_cpu_features.cpp
src/runtime/posix_math.ll
test/correctness/CMakeLists.txt
test/correctness/float16_t_neon_op_check.cpp
test/correctness/simd_op_check.cpp
test/correctness/simd_op_check.h

This PR is for #5449 .
Armv8-a extension of Half-precision floating point data processing is supported by CodeGen_ARM.
- The target needs to be set as 64-bit with "arm_fp16" feature.
- 32-bit is not supported in this commit.
- Upgrading fp16 to fp32 with emulated conversion is replaced with either
- fp16 native instruction or
- fp32 operation with native type conversion of fp16-fp32
- The dedicated unit test for NEON float16 is added.

Float16 support in CodeGen_ARM

---

src/runtime/HalideRuntime.h

Previously, the Clang UndefinedBehaviorSanitizer (UBSan) complained
about potential undefined behavior in `halide_buffer_t::set_flag`
because the enum `halide_buffer_flags` is interpreted as an int32_t
and implicitly converted to a uint64_t:
```
runtime error: implicit conversion from type 'int' of value -2 (32-bit, signed) to type 'unsigned long' changed the value to 18446744073709551614 (64-bit, unsigned)
```
On most compilers and hardware, this causes no issues,
since the conversion and implementation of `set_flag` together produce
the expected behavior still. However, it is better to be on the safe
side and make the explicit conversion to a uint64_t before doing the
bitwise negation.
This change makes sure the conversion from int32_t is made before the
bitwise negation, which fixes …

Fix potential undefined behavior in `set_flag`

---

src/autoschedulers/adams2019/LoopNest.cpp

We don't allow schedules that fuse to the extent that we can no longer
vectorize. This was implemented incorrectly though. The check assumed
that something was going to be compute_at inside the innermost loop, and
neglected the possibility that we were about to tile that loop.

Relax overzealous pruning rule

---

src/Func.cpp
src/Func.h
src/Pipeline.cpp
src/Pipeline.h

These were deprecated in Halide 12. Let's remove them for Halide 13.

Remove deprecated realize() variants from Func and PIpeline

---

src/runtime/write_debug_image.cpp

This ensures SciPy will successfully read files written by debug_to_file.

Adding padding byte size to outermost header byte count in MATLAB5 file format.

---

apps/hannk/run_benchmark_on_hexagon_sim.sh
apps/support/Makefile.inc
src/CodeGen_Hexagon.cpp

Letting CodeGen_LLVM handle predicated stores for Hexagon allows us
to generate HVX predicated stores instead of scalar predicated stores.
The operators in hannk app should be able to test this patch.
@pranavb-ca @dsharletg

[Hexagon] Use LLVM masked stores.

---

src/runtime/wasm_math.ll

llvm.wasm.promote.low was removed. Calling fpext directly is the preferred approach now.

Fix wasm regression at ToT LLVM

---

src/CodeGen_LLVM.cpp

It confuses the HVX LLVM backend, and shouldn't be necessary anyway.
For a specific case I have from a research project, this Halide:
```
output_(x, y) = i16(input1_(x, y)) - i16(input1_zero_);
const int vector_size = natural_vector_size<uint8_t>();
output_.compute_root()
.vectorize(x, vector_size * 2, TailStrategy::Predicate);
```
Generates this LLVM IR in master:
```
%69 = tail call <64 x i32> @llvm.hexagon.V6.vsububh.128B(<32 x i32> %68, <32 x i32> %52)
%70 = tail call <32 x i32> @llvm.hexagon.V6.hi.128B(<64 x i32> %69)
%71 = tail call <32 x i32> @llvm.hexagon.V6.lo.128B(<64 x i32> %69)
%72 = tail call <64 x i32> @llvm.hexagon.V6.vshuffvdd.128B(<32 x i32> %70, <32 x i32> %71, i32 -2)
%73 = tail call <32 x i32> @llvm.hexagon.V6.lo.128B(<64 x i32> %65)
%74 = tail call <32 x i32> …
```

Don't reinterpret cast when codegenning vector concat

---

apps/hannk/interpreter/lower.cpp
apps/hannk/interpreter/ops.cpp
apps/hannk/interpreter/tensor.cpp
apps/hannk/interpreter/tensor.h
apps/hannk/interpreter/transforms.cpp

Previously we didn't allow this because aliased tensors had to have the same rank, which is ~never the case for Reshape. Aliasing for Reshape is a huge win because it essentially becomes a no-op rather than a memcpy. Running against standard set of models shows no regression in differences vs. tflite.

[hannk] Allow aliasing of Reshape tensors

---

apps/hannk/interpreter/ops.cpp

Some pipelines have conv layers with really weird shapes, e.g. 6 x 28. Since we tile the x dimension by things like 4 (x86) or 5 (ARM), we do a lot of redundant compute (the split in x is ShiftInwards).
Trying to optimize the tile sizes is a difficult game of whack a mole. We can avoid all of this by simply swapping the x and y dimensions, so we split 28 instead of 6 instead, making the overlapping compute much less significant.
This is probably only relevant for a very small number of corner cases, but it is also a very small amount of safe code, so it seems worth doing.

Add optimization for corner case in conv

---

apps/hannk/README.md
apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/interpreter/allocation_planner.cpp
apps/hannk/interpreter/lower.cpp
apps/hannk/interpreter/lower.h
apps/hannk/interpreter/transforms.cpp
apps/hannk/tflite/tflite_parser.cpp
apps/hannk/util/model_runner.cpp
apps/hannk/util/small_vector.h
apps/support/Makefile.inc

FullyConnected is very similar to Conv2D, so rather than maintaining multiple similar implementations, let's translate a FullyConnected node into a Conv2D node (with some Reshape nodes as necessary). Benchmarking before-and-after shows performance to be more or less a wash on x86 OSX laptop and Pixel 4a.
Note that we keep the old FC logic for int16 outputs, as Conv2D doesn't support those yet; if this PR is landed, a followup PR will add that ability to Conv2D, and the existing FC support will be removed entirely.
Also a handful of drive-by fixes.

[hannk] Rewrite FC in terms of Conv2D

---

src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_GPU_Dev.cpp
src/CodeGen_GPU_Dev.h
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
test/correctness/CMakeLists.txt
test/correctness/gpu_vectorize.cpp

Because GPU backends do not support predication, this adds a mutator that de-predicates them, and a test to exercise this.  Should fix #6157.

De-predicate loads and stores in Metal/OpenCL/D3D12 backend

---

src/Simplify_Add.cpp
src/Simplify_Div.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Mul.cpp
src/Simplify_Select.cpp
src/Simplify_Sub.cpp

All of these simplifier rules came from `find_constant_bounds` failures. Some are oddly specific and I can be convinced to remove them (i.e. in Simplify_Max.cpp and Simplify_Select.cpp), but many of them are useful for `find_constant_bounds`.

Add various bounds-related simplifier rules

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp

The C++ versions were removed in #6122, but the Python equivalents were overlooked.

Remove deprecated realize() Python wrapprs

---

run-clang-tidy.sh

Script had previously assumed CMake would generate makefiles. If Ninja is selected via the `CMAKE_GENERATOR` environment variable, the script would fail.
Fixes #6163

Use generic build command instead of make in run-clang-tidy.sh

---

src/Generator.cpp

In degenerate conditions (eg, bugs in Halide or LLVM, or pathological user code), running a Generator can take arbitrarily long times (we recently found some buildbots that had Generators that had been running for several days).
This adds a simple background thread to generator_main() to ensure that compilations don't take unreasonable lengths of time. It defaults to 15 minutes of wall-clock time, but can be customized by the -t flag.

Add a watchdog timer to Generator

---

src/WasmExecutor.cpp

Some not-yet-landed variants of the wasm toolchain+runtime environments need this.

Add memmove to WasmExecutor callbacks

---

test/generator/image_from_array_aottest.cpp

The latest Emscripten compilers will complain about this.

Fix unused-variable warning-as-error

---

src/HexagonOptimize.cpp

Resolves the compilation below compilation error while generating
hannk::upsample_channels_uint8 from hannk/depthwise_conv.generator
for HVX:
Unknown intrinsic dynamic_shuffle
The problem occurs when we pattern match hvx instrinsics inside
if_then_else nodes and try to scalarize them later. In the patch we
prevent matching these intrinsics inside if_then_else blocks.
@dsharletg @pranavb-ca PTAL

[Hexagon] Do not pattern match inside if_then_else block

---

src/IROperator.cpp

As discussed in https://github.com/halide/Halide/pull/6189, this intrinsic should probably be Pure.

unsafe_promise_clamped() should be pure

---

src/CodeGen_D3D12Compute_Dev.cpp
src/CompilerLogger.cpp
src/Deinterleave.cpp
src/IRMutator.cpp
src/IRMutator.h
src/Inline.cpp
src/ParallelRVar.cpp
src/Profiling.cpp
src/ScheduleFunctions.cpp
src/Simplify.cpp
src/Simplify_Call.cpp
src/Simplify_Internal.h
src/Simplify_Stmts.cpp
src/SplitTuples.cpp
src/StorageFlattening.cpp
src/VectorizeLoops.cpp

There's a common pattern in many IRMutators that is "mutate a vector<Expr> and optionally let me know if anything is different".
(Note, this uses C++17 structured-binding syntax, which we previously weren't using in Halide. Objections?)
This adds a shared utility method (well, two, thanks to VariadicVisitor) and plus in the usage in all the places that seemed obvious.
I doubt this moves the needle on speed in either direction, but makes for smaller code.

Add IRMutator::mutate_exprs()

---

src/autoschedulers/adams2019/FunctionDAG.cpp
src/autoschedulers/adams2019/FunctionDAG.h

Adams2019 often tries to unroll loops that are not constant-bounded due to substitution of estimates for input variables. This PR tracks which bounds depend on estimates (`BoundsInfo` now tracks `depend_on_estimate`), and removes the constant_bound tag if the calculation of a constant bound depends on an estimate.

Fix unroll failures from adams2019 when the Expr depends on estimates

---

apps/fft/fft.cpp
src/Derivative.cpp
src/FindCalls.cpp
src/FindCalls.h
src/Func.cpp
src/IRMutator.cpp
src/Lower.cpp
src/PrintLoopNest.cpp
src/RealizationOrder.cpp
src/Simplify_Stmts.cpp
src/autoschedulers/adams2019/FunctionDAG.cpp
test/generator/multitarget_aottest.cpp

Just a minor style thing, but IMHO using C++17 structured bindings is preferable in ~all cases to using std::tie(), so I'm proposing this change.
Also made a drive-by change to populate_environment (now build_environment) since literally every caller was calling it this way.

Use C++17 structured binding instead of std::tie

---

.gitignore
test/correctness/simd_op_check.cpp

- f64x2.convert_low_i32x4_s/u are now generating proerly at top-of-tree, so re-enable them
- f64x2.promote_low_f32x4 is temporarily broken for larger vector widths, so disable it for now (issue is reported and fix is underway)
Also, driveby change to .gitignore.

Fix wasm simd issues

---

src/Simplify_Min.cpp
test/correctness/fuzz_simplify.cpp

Rule is invalid if overflow wraps, which #6207 caught. Also a fly-by fix to one of the debugging functions in fuzz_simplify.cpp .

Move simplifier rule to no_overflow

---

src/CodeGen_C.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/Prefetch.cpp
src/Simplify_Call.cpp
src/SlidingWindow.cpp
src/SplitTuples.cpp
src/StorageFlattening.cpp
src/runtime/qurt_hvx.cpp
test/correctness/simplify.cpp

This is (mostly) a cleanup pass to make the flow of Prefetch injection & lowering more obvious to the reader of the code (via commenting and minor code restructuring).
Notable exception: the HVX backend processing of Call::prefetch (and relevant runtime code) was refactored to make it (IMHO) less janky.
(Also some drive-by insertions of std::move where appropriate)

Prefetch cleanup

---

src/CodeGen_Xtensa.cpp
src/InjectDmaTransfer.cpp
src/XtensaOptimize.cpp

Avoid string names for Xtensa intrinsics as strings will not be captured by closure logic.

Use Variable nodes instead of StringImm ones to pass buffer names.

---

src/IRPrinter.cpp
src/Prefetch.cpp
test/correctness/prefetch.cpp
test/error/CMakeLists.txt
test/error/bad_prefetch.cpp

In #6155, we incorrectly assume that we can qualify the 'from' prefetch var by just adding 'prefix'; this isn't true if (e.g.) there are any splits involved. Instead, we need to walk through the active loops to find a suitable match. In addition, if no match is found, we now fail with an error (rather than quietly doing something undefined), as the 'from' var is required to be from an active loop.
(Addresses some-but-not-all of #6219)

Fix bug in prefetch()

---

src/CodeGen_C.cpp
src/Prefetch.cpp
src/VectorizeLoops.cpp
test/correctness/prefetch.cpp

- Arguments to Call::prefetch() must be scalars, not vectors
- Add more testcases to correctness_prefetch

More prefetch fixes 

---

src/IR.cpp
src/Lower.cpp
src/Prefetch.cpp
src/Prefetch.h
src/PrefetchDirective.h
test/correctness/prefetch.cpp

When a loop with prefetch is unrolled, the prefetch instructions getting scattered through the loop can cause LLVM codegen issues in some cases (see https://bugs.llvm.org/show_bug.cgi?id=51172). As a partial mitigation for that issue, this PR adds a pass to hoist all prefetch instructions to the top of their loop. This is still a bit experimental; it definitely addresses the codegen issues we see, but makes the use of prefetch potentially less effective (since the hoisted prefetch may be too far from the eventual use to be effective).

Hoist unrolled prefetches to top of the block

---

.clang-tidy
.github/workflows/presubmit.yml
Makefile
run-clang-format.sh
run-clang-tidy.sh
src/Generator.cpp

Pretty minor -- no formatting changes, only one new warning needing disabling -- just keeping our tooling not too far from top of tree.

Upgrade clang-format and clang-tidy to LLVM-12

---

src/CodeGen_Hexagon.cpp
test/correctness/simd_op_check_hvx.cpp

I think LLVM handles some unknown shuffles better than we do with vlut. We could also fall through to vdelta instead, but I suspect LLVM does this anyways, and might do something smarter in some special cases.
@aankit-ca @pranavb-ca does this seem like a good thing to do?

Fall through to LLVM for unknown shuffles on Hexagon

---

apps/HelloPyTorch/Makefile
apps/HelloPyTorch/modules.py
apps/HelloPyTorch/setup.py
apps/HelloPyTorch/test.py
src/CodeGen_PyTorch.cpp
src/Generator.cpp
src/runtime/HalidePyTorchCudaHelpers.h
src/runtime/HalidePyTorchHelpers.h

1. The runtime helpers for the PyTorch extension include "torch/extension.h". This is unnecessary and creates an unnecessary dependency on "Python.h" for libraries that include PyTorch Halide extensions (e.g. a PyTorch C++ TorchScript extension does not need the Python frontend). This pull request removes this dependency.
2. The HelloPyTorch app was broken: the default autoscheduler [2016] does not work on GPU, for the automatically generated gradient. This pull request fixes it.

Remove torch/extension dependency and fix PyTorch example, adding the correct (GPU) autoscheduler

---

dependencies/llvm/CMakeLists.txt
src/CodeGen_WebAssembly.cpp
src/WasmExecutor.cpp
test/correctness/simd_op_check.cpp
test/correctness/vector_math.cpp

Update various parts of the source that still assume LLVM10 is supported. ~~(We probably need to update the buildbots as well before this lands.)~~

Remove remaining bits of LLVM10 support

---

README.md
src/CMakeLists.txt

Usage of C++ `<thread>` header requires linking to threading library
`Generator.cpp` and `ThreadPool.h` both `#include <thread>`,
but don't link to the threading implementation.
This fixes build for me on debian sid, which is failing otherwise with:
```
$ ninja
[  0% 2/1480][  0% 0:00:00 + 0:33:06] Linking CXX executable src/autoschedulers/adams2019/get_host_target
FAILED: src/autoschedulers/adams2019/get_host_target
: && /usr/local/bin/clang++ -pipe -O3 -DNDEBUG  src/autoschedulers/adams2019/CMakeFiles/get_host_target.dir/get_host_target.cpp.o -o src/autoschedulers/adams2019/get_host_target  -Wl,-rpath,/repositories/halide/build/src:  src/libHalide.so.13.0.0 && :
ld: error: /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so: undefined reference to pthread_create [--no-allow-shlib-undefined] …
```

Usage of C++ `<thread>` header requires linking to threading library

---

packaging/CMakeLists.txt

`DATA` results in those being installed directly into `${CMAKE_INSTALL_PREFIX}/share`,
while they obviously should go into `${CMAKE_INSTALL_PREFIX}/share/doc/Halide`.
Split off of #6266.

CMake: install docs into halide subdirectory of doc dir

---

src/runtime/synchronization_common.h

To work around old COMDAT issues, we allocated the table as a char array and cast it to what we want; unfortunately this doesn't guarantee the right alignment for the table and in some environments (eg wasm) we can get unaligned-access failures.
We could fix this by forcing the right alignment, but since we fixed COMDAT issues in another way a while back (adding smarts to LLVM_Runtime_Linker), let's just remove the hack and declare it normally.
Also added some drive-by changes to ensure that the hashtable size and HASH_TABLE_BITS were safe (this happened to be the case before but wasn't enforced), and also to init all the fields in hash_bucket.
(Q: do we really need `check_hash()` to exist? With the mods in place above, is it possible for addr_hash() to return a bad index?)

Fix alignment issues in synchronization_common.h

---

src/runtime/posix_threads.cpp
src/runtime/qurt_threads.cpp
src/runtime/thread_pool_common.h
src/runtime/windows_threads.cpp

Minor hygiene noticed when doing other patches:
- prefer `constexpr int` over `#define`, since we can now use C++17 in runtime code
- remove redundant def of MAX_THREADS
- use `do .. while (0)` idiom for functional macros

Minor cleanups in thread_pool_common.h

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

The external buffer host alignment should always be reflected in the Param attached to a load or store. Remove special case code for buffer parameter arguments.

Remove hopefully dead code.

---

src/RDom.h

In the example for RDom::where, the simplified case contains a free occurence of `r.x`, which should be replaced with `10` since we are in the case `r.x == 10`.

Remove unbound variable in documentation

---

apps/hannk/CMakeLists.txt
apps/hannk/Makefile

currently, random dotfiles (e.g. .DS_Store on OSX) can creep in, causing bogus failures

[hannk] tests should only process .tflite files

---

CMakeLists.txt

Bumps version to Halide 14.0.0. Release branch for 13.x has been cut.

Bump version to Halide 14.0.0

---

CMakeLists.txt
apps/hannk/.gitignore
apps/hannk/CMakeLists.txt
apps/hannk/Makefile
apps/hannk/configure_cmake.sh
apps/hannk/halide/CMakeLists.txt
apps/hannk/util/CMakeLists.txt
cmake/HalideTargetHelpers.cmake

There's a bunch of changes in here, and I thought it would be better to review them here, rather than just pushing to your branch. I took some care to make each commit self-contained and easy to interpret. The big changes are in the last two:
First, the cross-compiling strategy changed significantly. Rather than shelling out via execute_process and potentially guessing the toolchain options wrong, expect to find our host tools (i.e. generators) in a package called "hannk_tools".
The package is created by the host build via the CMake export() command. Importing this package in the cross build creates IMPORTED targets with the same names as our generators. We then use these generators rather than creating generators for the target build.
Second, the `configure_cmake.sh` script now takes …

Use explicit host build strategy for cross compiling HANNK

---

apps/hannk/interpreter/ops.cpp
apps/hannk/interpreter/ops.h
apps/hannk/interpreter/tensor.cpp
apps/hannk/interpreter/tensor.h
apps/hannk/interpreter/transforms.cpp

The code for aliasing tensors was janky. This cleans it up and makes a clear distinction between aliasing done to overlay buffers with crop-and-translate, vs the aliasing done when we reshape tensors. We no longer allow a given tensor to do both of these, and we give preference to Reshape aliasing first.
(Cherry-picked from #6321)

[hannk] Clean up aliasing (v2)

---

README.md

I just realized we forgot to bump the version number in the README... better to fix that now than never. I've added it to the [release instructions](https://github.com/halide/Halide/wiki/Cutting-a-release) for next time so we hopefully won't forget.
I also removed version number references where they aren't helpful (fewer places to patch).
I don't want to re-do the whole release process for a README typo :stuck_out_tongue:

Update README for Halide 13.

---

apps/hannk/cmake/superbuild/CMakeLists.txt
apps/hannk/configure_cmake.sh

After #6361 the cross-compiling workflow requires building HANNK twice: once for the host-run generators (with a host toolchain) and again with the cross toolchain. This PR adds an opt-in _superbuild_ that orchestrates running both builds and correctly updates the world with a single call to Ninja.
The `configure_cmake.sh` script learned how to call `get_host_target` to determine whether the given `HL_TARGET` requires cross compiling. When not cross-compiling, it invokes the build directly. When cross compiling, it invokes the super-build. It doesn't actually run the build (it's called "configure", after all) in either case. It checks a few basic sanity conditions on the env-vars it reads, now, too.
The superbuild has a few special features to make using it more convenient:
* Variables …

Add super-build for cross-compiling HANNK

---

apps/hannk/cmake/superbuild/CMakeLists.txt

Not sure why this broke, but I can confirm it works locally, now.

Fix empty INSTALL_COMMAND in hannk super-build

---

src/runtime/device_interface.cpp

This was inserted in https://github.com/halide/Halide/pull/6310, probably mistakenly, since `halide_assert()` in the Halide runtime is *not* a debug-only assertion). Instead of a controlled runtime failure, we just abort, which is not OK.

Remove halide_assert() from halide_default_device_wrap_native

---

src/runtime/d3d12compute.cpp

The type-size checks in d3d12compute.cpp don't need to be runtime checks.

Convert various halide_assert -> static_assert

---

apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/interpreter/ops.cpp
apps/hannk/interpreter/ops.h
apps/hannk/tflite/tflite_parser.cpp

The `reducing()` method didn't handle negative values for indices, and didn't reverse the value of the axis as we do elsewhere, so results were incorrect.
~~Also, we now parse and save the value of `keep_dims`, though I can't find evidence that it does much of anything: test cases pass different values for it but none of them fail (even though we ignore it), and at least one reference implementation I see doesn't seem to do anything with it.~~

[hannk] Fix MeanOp

---

src/CodeGen_OpenGLCompute_Dev.cpp

Currently, ramps are generated as a number of independent scalar
expressions that are finally gathered into a vector. For instance,
indexing in vectorized code is filled with ramps like the following:
```
int _11 = int(1) * int(1);
int _12 = _10 + _11;
int _13 = int(2) * int(1);
int _14 = _10 + _13;
int _15 = int(3) * int(1);
int _16 = _10 + _15;
ivec4 _17 = ivec4(_10, _12, _14, _16);
```
This patch simplifies the generated code using a multiply add expression
on a vector containing an arithmetic sequence, such that the code is
as follows:
```
ivec4 _11 = ivec4(0, 1, 2, 3) * int(1) + _10;
```
This is more performant due to vectorization, more compact, and more
readable because the base and the stride are easily identifiable.

Vectorize Ramp in OpenGLCompute backend

---

src/CodeGen_OpenGLCompute_Dev.cpp

This patch adds support for vector load and store operations in the
OpenGLCompute backend.
First, a pass identifies the buffers whose loads and stores are all
dense, aligned, and have the same number of lanes. Such buffers are
declared with a vector base type and accessed accordingly. Loads and
stores that do not satisfy those criteria are implemented as gathers and
scatters from buffers whose base type is scalar.
Resolves #4976.
Partially resolves #1687.

Support vectorization in OpenGLCompute backend

---

src/CodeGen_OpenGLCompute_Dev.cpp

The ternary operator in GLSL does not work with vector types. While the
mix function have overloads to boolean vectors, it is only supported in
version 4.5, so it is not exactly portable. To work around this, we use
the ternary operator on all elements of the vector type.
Necessary for #6348.

Support vectorized Select in OpenGLCompute backend

---

src/runtime/gpu_context_common.h
src/runtime/hashmap.h
src/runtime/runtime_internal.h

Also convert usage of halide_assert()/HALIDE_CHECK() in hashmap.h and gpu_context_common.h to halide_debug_assert(), as all the usages looked to be appropriate for debug-mode only.
(Rebased version of #6385, which this replaces)

Add halide_debug_assert() macro

---

apps/lens_blur/process.cpp
src/runtime/HalideBuffer.h
src/runtime/cache.cpp
src/runtime/device_interface.cpp
src/runtime/halide_buffer_t.cpp
src/runtime/matlab.cpp
src/runtime/msan.cpp
src/runtime/tracing.cpp
src/runtime/write_debug_image.cpp
test/generator/buffer_copy_aottest.cpp
test/generator/gpu_object_lifetime_aottest.cpp
test/generator/memory_profiler_mandelbrot_aottest.cpp
test/generator/user_context_insanity_aottest.cpp
tools/RunGenMain.cpp

This cherry-picks just the changes to callsites internal to Halide (and tests) from #6388. (It doesn't attempt to annotate runtime functions to enforce checking the results.)

Check results of all runtime function calls

---

src/runtime/fuchsia_clock.cpp
src/runtime/linux_clock.cpp
src/runtime/openglcompute.cpp
src/runtime/osx_clock.cpp
src/runtime/posix_clock.cpp
src/runtime/windows_clock.cpp

If you try to build and run something with `openglcompute` and `debug`, you may crash with a div-by-zero, because the openglcompute runtime never calls `halide_start_clock()`, and all implementations of `halide_current_time_ns()` assume that it has been called. On (e.g.) OSX, this results in div by zero. This fixes it by inserting the correct call into openglruntime.cpp, and also adding debug-only asserts to all the `halide_current_time_ns()` implementations.
(I was tempted to fix this by removing `halide_start_clock()` entirely and just lazily initing the initial value in `halide_current_time_ns()`, but I figured that would likely get pushback...)

Fix OGLC debug builds

---

.github/workflows/packaging.yml
Makefile
README.md
README_cmake.md
README_webassembly.md
dependencies/llvm/CMakeLists.txt
packaging/ubuntu/config.cmake
src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/CodeGen_X86.cpp
src/LLVM_Headers.h
src/LLVM_Runtime_Linker.cpp
src/Lower.cpp
src/Target.cpp
src/runtime/CMakeLists.txt
test/correctness/simd_op_check.cpp

With Halide 13 released, we should drop support for LLVM11 in Halide trunk, since we only promise to support LLVM trunk + two releases.

Drop support for LLVM11

---

src/runtime/device_interface.cpp

Found while debugging crashes with performance_async_gpu for OpenGLCompute: the 'if' tree wasn't robust enough for malformed buffers being passed, and could attempt to deref and use a null src->device_interface or dst->device_interface in some cases.
This patch just improves this function to return an error in these cases (rather than crashing); the fact that we are getting malformed buffers passed to us is likely a separate bug.

Add defensive checks to halide_buffer_copy_already_locked

---

src/runtime/metal.cpp
src/runtime/synchronization_common.h

This converts all the usage of `halide_abort_if_false()` in runtime/metal into either an explicit runtime check-and-return-error-code (if the check looks plausible), or `halide_debug_assert()` (if the check seems to be stating an invariant that shouldn't be possible in well-structured code). These changes are admittedly subjective, so feedback is especially welcome.
Also, driveby change to sync-common.h to use `halide_debug_assert()` rather than a local equivalent.

Remove halide_abort_if_false() usage in runtime/metal

---

src/CodeGen_C.cpp

round_f32/round_f64 implementations at  https://github.com/halide/Halide/blob/408a27718dd818f9b39ecdae7081dd13167066f8/src/runtime/posix_math.ll#L130 use nearbyint.

Change implementation of round_f* in CodeGen_C to use nearbyint() to match CodeGen_LLVM

---

src/runtime/x86.ll
src/runtime/x86_cpu_features.cpp

The existing code attempts to preserve ebx (since the cpuid instruction can trash it), but it only preserves the lower 32 bits; on 64-bit systems, this (amazingly) usually works OK unless you are compiling in (e.g.) ASAN mode, which can subtly change codegen such that the full 32 bits of rbx must be preserved.
I'm genuinely astonished this hasn't bitten us before now!

x86_cpuid_halide must preserve all 64 bits of rbx/rsi

---

src/CodeGen_LLVM.cpp

Various changes and merges ended up with us using multiple ASAN passes, which was pretty crashy (we just didn't notice because it isn't tested well enough on our buildbots, but is elsewhere).
I think we really only want to use the ModuleAddressSanitizerPass (not the non-Module version), which is what Clang does.

Fix broken ASAN code

---

CMakeLists.txt
README.md
src/FindIntrinsics.cpp
src/runtime/x86.ll
src/runtime/x86_cpu_features.cpp
test/correctness/intrinsics.cpp

Added fixes for [6405](https://github.com/halide/Halide/pull/6405) and [6409](https://github.com/halide/Halide/pull/6409) to cut a v13.0.1 release.
[Fix obscure bug in widening let substitution #6405](https://github.com/halide/Halide/pull/6409)
[x86_cpuid_halide must preserve all 64 bits of rbx/rsi #6409](https://github.com/halide/Halide/pull/6409)
I've left the README.md alone since it seems like v13 wasn't advertised yet, so it still mentions v12.0.0 as the latest release (since that's what is in master right now).  
Please look things over and let me know if I've missed anything!

Backport PR6409 and PR6405 for v13.0.1

---

src/Introspection.cpp

- DWARF v5 has a slightly different header; this recognizes it so we don't fail immediately
- Add support for the line_strp form
- Allow for a graceful failure if a debug abbreviation is missing; I've only seen this when compiling for TSAN, and I'm honestly not entirely sure if this is a bug in the DWARF generation for those tools vs a subtle flaw in our parsing, but bailing out early and skipping introspection seems kinder than assert-fail.

Fix Introspection issues

---

src/Lerp.cpp

Should be pretty much the same thing as before, but easier to read and maybe may produce better code.

Rewrite integer lerp using intrinsics

---

src/CodeGen_LLVM.cpp

The remapping is only intended to be used for output argument(s), not the function name; if you have an output with the same name as the function, you can get the metadata emitted with incorrect information. (And remapping the target string is just silly.)
This is almost impossible to do currently, but if you construct a Generator just right, you can make it happen.

Don't remap the function name or the target in the metadata

---

src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/HexagonOptimize.cpp
src/Lerp.cpp
src/Lerp.h

Saves instructions on x86. For the division by 255 in an 8-bit lerp we get:
Before #6426
vpaddw	%ymm0, %ymm1, %ymm1
vpsrlw	$8, %ymm1, %ymm2
vpaddw	%ymm2, %ymm1, %ymm1
vpsrlw	$8, %ymm1, %ymm1
After #6426
vpsrlw	$7, %ymm2, %ymm3
vpand	%ymm0, %ymm3, %ymm3
vpsrlw	$8, %ymm2, %ymm4
vpaddw	%ymm2, %ymm4, %ymm2
vpaddw	%ymm3, %ymm2, %ymm2
vpsrlw	$7, %ymm2, %ymm3
vpand	%ymm0, %ymm3, %ymm3
vpsrlw	$8, %ymm2, %ymm2
vpaddw	%ymm2, %ymm3, %ymm2
vpand	%ymm1, %ymm2, %ymm2
This PR:
vpaddw  %ymm0, %ymm3, %ymm3
vpmulhuw        %ymm1, %ymm3, %ymm3
vpsrlw  $7, %ymm3, %ymm3

Do target-specific lowering of lerp

---

src/CodeGen_C.cpp

The existing code will emit something like `halide_dimension_t foo_buffer_shape[] = {};` for these, which is a zero-length array, which some compilers will (justifiably) say has no effect. We should be able to just use nullptr for the shape in these cases.

Codegen_C: buffer compilation needs to special-case scalar buffers

---

src/IRPrinter.cpp
src/StmtToHtml.cpp

This works for me nicely with CUDA, OpenCL, OpenGLCompute, Direct3D12Compute, and Metal as backends. I tried collapsing the code for all of them and it works nicely. I put everything in a `<pre>` for the HTML output. Not sure if any of the backends produce non-compatible characters that might break the HTML, but for my kernels, it didn't.

Include GPU source kernels in Stmt and StmtHtml file.

---

src/IRPrinter.cpp
src/StmtToHtml.cpp

I put quite some work in this one, but the result is glorious. The string manipulations are not the most rigorous ones, but they work for me. This highlighting is only processed for PTX code, based on the buffer name being `"cuda_gpu_source_kernels"`. Here is an example of the syntax-highlighted PTX code:
Some features:
- comments
- labels
- predicates
- register matching
- numeric literals
- collapsible blocks per kernel function
- shading for vectorized instructions.
- memory accesses in red
- different colors per datatype

Syntax highlighting for embedded PTX code.

---

src/Type.h
src/runtime/HalideBuffer.h

Fixes for c++20

---

test/performance/async_gpu.cpp

It's been disabled for ~2 years because of flaky failures (#3586); we should see if the many changes since then have improved things or not.

Re-enable performance_async_gpu for D3D12Compute

---

src/CodeGen_Hexagon.cpp

Tweak Hexagon codegen output  to match the pattern in Lower.cpp more acccurately (for level 1 vs 2); also prefix the outputs so they are easier to read as Hexagon-specific when debugging

Tweak Hexagon codegen output 

---

python_bindings/src/PyEnums.cpp
src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/HexagonOffload.cpp
src/IRPrinter.cpp
src/Module.h

Allows us to skip generating metadata for offloaded hexagon funcs, which will never use it.

Add LinkageType::ExternalPlusArgv (#6452)

---

src/Closure.cpp
src/Closure.h
src/DeviceArgument.cpp
src/DeviceArgument.h
src/HexagonOffload.cpp
src/OffloadGPULoops.cpp

The current API requires calling a Visitor from the Closure ctor, which means we implicitly call virtual methods from the class ctor, which is a no-no for a non-final class (see comments on https://github.com/halide/Halide/pull/6443).

Fix Closure API

---

apps/linear_algebra/benchmarks/macros.h

This is breaking i386 build:
https://buildd.debian.org/status/fetch.php?pkg=halide&arch=i386&ver=13.0.1-3&stamp=1638786518&raw=0

`apps/linear_algebra/benchmarks/macros.h`: don't forget SSE guard

---

src/CodeGen_Internal.cpp

Hopefully we can nuke this hack. Opening as a PR to see if it's necessary, not to merge it (because it would conflict with the other PR).

Try removing optional buffer added to closure

---

src/runtime/printer.h
src/runtime/to_string.cpp

The Printer is (currently) usually inlined into every module, so this check is repeated in multiple chunks of code. Since the goal is to avoid crashing when debugging, let's move it to halide_string_to_string() (which will catch all these, and possibly more) and save some code size.
(Further improvements in Printer code size on the way; this change seems worthy of considering separately.)

Move null check from Printer to halide_string_to_string()

---

src/Target.cpp

JIT requires the use of bounds_query; disabling it will almost certainly fail in JIT mode, either with a confusing assert message, or a crash (if you also specify no_asserts). This adds a more useful failure message.

Fail if no_bounds_query specified for HL_JIT_TARGET

---

src/Lower.cpp
src/LowerParallelTasks.cpp

I think this is the right fix for this case; that said, I can't find a single instance in any of our test cases that actually triggers this.

Fix potential issue with additional LoweredFuncs

---

src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/HexagonOptimize.cpp
src/Lerp.cpp
src/Lerp.h
test/correctness/CMakeLists.txt
test/correctness/widening_lerp.cpp

This lets it save a few instructions on x86 and arm, and probably other CPU targets.
cast(UInt(16), lerp(some_u8s)) produces the following, before and after
this PR
Before:
x86:
vmovdqu	(%r15,%r13), %xmm4
vpmovzxbw	-2(%r15,%r13), %ymm5
vpxor	%xmm0, %xmm4, %xmm6
vpmovzxbw	%xmm6, %ymm6
vpmovzxbw	-1(%r15,%r13), %ymm7
vpmullw	%ymm6, %ymm5, %ymm5
vpmovzxbw	%xmm4, %ymm4
vpmullw	%ymm4, %ymm7, %ymm4
vpaddw	%ymm4, %ymm5, %ymm4
vpaddw	%ymm1, %ymm4, %ymm4
vpmulhuw	%ymm2, %ymm4, %ymm4
vpsrlw	$7, %ymm4, %ymm4
vpand	%ymm3, %ymm4, %ymm4
vmovdqu	%ymm4, (%rbx,%r13,2)
addq	$16, %r13
decq	%r10
jne	.LBB0_10
arm:
ldr	q0, [x17]
ldur	q2, [x17, #-1]
ldur	q1, [x17, #-2]
subs	x0, x0, #1                      // =1
mvn	v3.16b, v0.16b
umull	v4.8h, v2.8b, v0.8b
umull2	v0.8h, v2.16b, v0.16b
umlal	v4.8h, v1.8b, v3.8b …

Let lerp lowering incorporate a final cast.

---

src/CodeGen_PTX_Dev.cpp
src/LLVM_Output.cpp

There is some confusion about whether this usage is acceptable. TL;DR: it's not just acceptable, it's required for the forseeable future. Add comments to capture this to avoid future such questions. (With great thanks to Alina for pointing me at the relevant LLVM discussion links!)

Document the usage of llvm::legacy::PassManager

---

src/LowerParallelTasks.cpp

Basically OCD code stuff I noted down when debugging the issues, this restructures the inner loop to avoid calling a local function that has non-obvious side effects (setting just the right slot in the closure args), as well as consolidating via helper functions, hoisting common stuff used in both paths, using std::move where seemingly appropriate, adding some (hopefully correct) comments about arg expectations, and other things that aren't likely to really move the needle in terms of Halide compile speed, but (hopefully) make the code a little bit more understandable after some time away.
(There was a todo about "find a better place for generate_closure_ir()"; this PR eliminates it entirely, just inlining it into the caller, which I think is reasonable given thhe number of assumptions …

Grab Bag of minor cleanups to LowerParallelTasks

---

src/Target.cpp

https://buildd.debian.org/status/fetch.php?pkg=halide&arch=riscv64&ver=13.0.2-1&stamp=1639833165&raw=0
```
[1283/3260] /usr/bin/clang++-13 -DHALIDE_ENABLE_RTTI -DHALIDE_WITH_EXCEPTIONS -DHalide_EXPORTS -DLLVM_VERSION=130 -DWITH_AARCH64 -DWITH_AMDGPU -DWITH_ARM -DWITH_D3D12 -DWITH_HEXAGON -DWITH_INTROSPECTION -DWITH_METAL -DWITH_MIPS -DWITH_NVPTX -DWITH_OPENCL -DWITH_OPENGLCOMPUTE -DWITH_POWERPC -DWITH_RISCV -DWITH_WEBASSEMBLY -DWITH_X86 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-13/include -g -O3 -DNDEBUG -fPIC -Wall -Wcast-qual -Wignored-qualifiers -Woverloaded-virtual -Winconsistent-missing-destructor-override -Winconsistent-missing-override -Wno-deprecated-declarations -Wno-double-promotion -Wno-float-conversion -Wno-float-equal …
```

Try to fix riscv64 build

---

src/Lower.cpp
src/LowerWarpShuffles.cpp
src/LowerWarpShuffles.h
test/correctness/register_shuffle.cpp

This PR fixes #5630 
We need to add ".sync" suffix for warp shuffle intrinsics after Volta architecture:
https://docs.nvidia.com/cuda/volta-tuning-guide/index.html

Support new warp shuffle intrinsics after CUDA Volta architecture

---

src/autoschedulers/mullapudi2016/AutoSchedule.cpp

As discussed in https://github.com/halide/Halide/issues/6518,
this is a bit dubious, and e.g. prevents building on RISC-V,
because there is no way to not build autoschedulers currently.

Mullapudi2016: don't hardcode the list of supported targets

---

dependencies/llvm/CMakeLists.txt

Without this, cmake fails with:
```
CMake Error in dependencies/llvm/CMakeLists.txt:
Target "Halide_LLVM" INTERFACE_INCLUDE_DIRECTORIES property contains path:
"/repositories/halide/dependencies/llvm/"
which is prefixed in the source directory.
```
`LLVM_INCLUDE_DIRS` there is `/repositories/llvm-project/llvm/include;/builddirs/llvm-project/build-Clang13/include`,
and `INTERFACE_INCLUDE_DIRECTORIES`'s property beforehand is `` (empty),
but after this line it suddenly becomes `/repositories/halide/dependencies/llvm/$<BUILD_INTERFACE:/repositories/llvm-project/llvm/include;/builddirs/llvm-project/build-Clang13/include>`.
This is quite obscure. I don't really understand what is going on,
but with the patch it builds fine.

Fix weird CMake issue with custom LLVM

---

src/Simplify_Shuffle.cpp
test/correctness/CMakeLists.txt
test/correctness/reinterpret_vector.cpp

This is helpful for things like reinterpreting 32-bit packed rgba values
as individual components for free.

Make it possible to interpret a wide type as multiple smaller elements

---

src/CodeGen_X86.cpp
src/FindIntrinsics.cpp
test/correctness/intrinsics.cpp
test/correctness/simd_op_check.cpp

and codegen it to pmulhuw on x86

Handle mixed-width args to mul-shift-right

---

src/runtime/HalideBuffer.h

Some decref-triggered runtime methods need the shape
Fixes #6509

free shape storage last

---

src/CodeGen_LLVM.cpp

Somehow, initially i missed that there was MSan support,
so it might be good to actually mention that we don't need to run
any MSan passes here, and that we didn't forget to run them.
Secondly, it seems inconsistent not annotate the functions
with `Attribute::SanitizeMemory`, like we do for others.
I suppose it isn't strictly required, since they are used
to actually drive the instrumentation passes, and we don't
run MSan pass, but they are also used to disable some LLVM optimizations,
and that //might// be important. Or not, but then i suppose
there should be a comment about it?
Let me know if i should replace the second change with a comment too.

[NFC-ish] Finish MSAN handling (Refs. #6513)

---

src/Random.cpp
src/Simplify_Mul.cpp
test/correctness/async_device_copy.cpp
test/correctness/simplify.cpp

40% faster, and I fixed the issue where the low bits of our noise have a low period. This combined with #6506 makes it possible to generate low-bit-width-noise very cheaply for things like dithering.

Make random faster by putting the innermost var last

---

packaging/CMakeLists.txt

I know we have previously discussed that `TYPE DOC` should be used,
but unfortunately i'm not sure that will work here,
because doc/tutorial directory is already occupied by C++ tutorials,
and i don't think they should be mixed.
I'm open to alternative suggestions.

Install Python tutorials

---

python_bindings/CMakeLists.txt
python_bindings/src/PyError.cpp
python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp
src/PythonExtensionGen.cpp

As disscussed in https://github.com/halide/Halide/pull/6523#issuecomment-1003545664
and later in https://github.com/halide/Halide/issues/6524,
pybind11 v2.8.1 added some defensive checks that fail for halide,
namely in `python_tutorial_lesson_04_debugging_2`
and `python_tutorial_lesson_05_scheduling_1`.
https://github.com/halide/Halide/issues/6524#issuecomment-1003569810 notes:
> * Python calls a Halide-JIT-generated function , which runs with the GIL held.
> * Halide runtime spawns worker threads.
> * The worker threads try to call pybind11's py::print function to emit traces.
> * Pybind11 complains, correctly, that the worker thread doesn't hold the GIL.
>
> Trying to acquire the GIL hangs, because the main thread is still holding it. I tried teaching the main thread to release the GIL …

Fix Python GIL lock handling (Fixes #6524, Fixes #5631)

---

packaging/CMakeLists.txt

CMake can build the python module, but it's ignored during `make install`.  This teaches cmake to install it, if it was built.
The cmake `FindPython3` module makes some distutils calls to figure out where modules should go, and exposes those as cmake vars.  Specifically, [Python3_STDLIB, Python3_STDARCH, Python3_SITELIB, Python3_SITEARCH](https://cmake.org/cmake/help/v3.15/module/FindPython3.html#result-variables) give us the various cases of "python3/" vs "python3.x", and "dist-modules" vs "site-modules".
This patch uses `Python3_SITEARCH` by default, which maps to `/usr/lib/python3.9/site-packages/` for me on debian linux.  The var `Halide_INSTALL_PYTHONDIR` can be used to override that.  The intention is for distro packaging to point that wherever it needs to go.

If cmake built a python module, teach cmake to install the python module

---

src/Random.cpp
src/Simplify_Mul.cpp
test/correctness/async_device_copy.cpp
test/correctness/simplify.cpp

Reverts halide/Halide#6504 -- the new simplifier rules introduce `Signed integer overflow occurred during constant-folding` errors in downstream code that hasn't failed before; I'll need some time to figure out the right fix and this change isn't urgent IIUC

Revert "Make random faster by putting the innermost var last"

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp

Compilers with `-Werror` will fail with `error: moving a temporary object prevents copy elision`

Remove unnecessary `std::move` calls

---

src/CMakeLists.txt

Debian and other third-party packagers might need or want to patch our sources for a variety of reasons. In those cases, they might also need to override the SOVERSION.
See here for a practical example:
https://salsa.debian.org/pkg-llvm-team/halide/-/blob/f881de70cd83095053e13047b63f61faf6bc7a36/debian/patches/0006-Fixup-libhalide-version-soversion-for-debian-package.patch
ATTN @LebedevRI

Allow third parties to externally override SOVERSION

---

CMakeLists.txt
README_cmake.md
src/CMakeLists.txt
src/runtime/CMakeLists.txt

Depends on #6534 
Adds documentation for `add_halide_generators` and cleans up the table syntax and a few stray inaccuracies/removed features.

Update CMake documentation

---

src/Generator.h

The existing wrapper wouldn't work for Outputs that have Tuple-valued elemets.

Fix GeneratorOutput_Buffer::set_estimates()

---

CMakeLists.txt
README.md
README_cmake.md
dependencies/llvm/CMakeLists.txt
packaging/CMakeLists.txt
python_bindings/src/PyError.cpp
python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp
src/CMakeLists.txt
src/ClampUnsafeAccesses.cpp
src/CodeGen_LLVM.cpp
src/PythonExtensionGen.cpp
src/SlidingWindow.cpp
src/Target.cpp
src/autoschedulers/mullapudi2016/AutoSchedule.cpp
src/runtime/CMakeLists.txt
src/runtime/HalideBuffer.h
test/correctness/indexing_access_undef.cpp

Backport the following PRs:
* #6503 
* #6352 (dependency)
* #6508 
* #6520 
* #6519 
* #6527 
* #6511 
* #6516 
* #6530 
* #6525 
* #6523 
* #6537
* #6534
* #6535
These are the PRs requested by @LebedevRI for the sake of Debian packaging, plus a handful of small stability-related changes I thought would be nice to include.
Also bumps version number to v13.0.3

Backport build and stability changes to v13

---

src/IROperator.h

The comment refers to an older understanding which is incorrect for saturating cases, e.g. `rounding_shift_right(255, 1)` = 128 (new definition) and not 127 (old definition).

Fix description of rounding_shift_left/rounding_shift_right

---

src/CodeGen_LLVM.cpp
src/CodeGen_X86.cpp
test/correctness/simd_op_check.cpp

This produces 3 instructions on x86, whereas the previous version
produced 5.

Better default lowering of absd

---

apps/HelloWasm/CMakeLists.txt
apps/bgu/CMakeLists.txt
apps/bilateral_grid/CMakeLists.txt
apps/blur/CMakeLists.txt
apps/c_backend/CMakeLists.txt
apps/camera_pipe/CMakeLists.txt
apps/conv_layer/CMakeLists.txt
apps/cuda_mat_mul/CMakeLists.txt
apps/depthwise_separable_conv/CMakeLists.txt
apps/fft/CMakeLists.txt
apps/harris/CMakeLists.txt
apps/hist/CMakeLists.txt
apps/iir_blur/CMakeLists.txt
apps/interpolate/CMakeLists.txt
apps/lens_blur/CMakeLists.txt
apps/linear_algebra/src/CMakeLists.txt
apps/local_laplacian/CMakeLists.txt
apps/max_filter/CMakeLists.txt
apps/nl_means/CMakeLists.txt
apps/resize/CMakeLists.txt
apps/stencil_chain/CMakeLists.txt
apps/unsharp/CMakeLists.txt
apps/wavelet/CMakeLists.txt
cmake/HalideGeneratorHelpers.cmake

Existing CMake code uses add_executable + target_link_libraries to create a Generator, but the somewhat-recently-added add_halide_generator() helper is a cleaner way to do this. Move to using it everywhere in apps/ instead.
(Note that add_halide_generator()) doesn't yet work for in-tree builds, unfortunately.)

Use add_halide_generator() everywhere in apps/

---

src/Generator.h
test/generator/CMakeLists.txt
test/generator/templated_aottest.cpp
test/generator/templated_generator.cpp

Currently the macro uses the type in a way that fails if it's enclosed in parens, which is necessary if the type name contains internal commas due to template usage.

Make HALIDE_REGISTER_GENERATOR work with multiple template args

---

test/correctness/simd_op_check.cpp

LLVM does in fact generate this correctly, but only for 8x16 sized vectors

Enable simd_op_check test for wasm i8x16.popcnt

---

src/LLVM_Runtime_Linker.cpp

Reverts halide/Halide#6561
Underlying change reverted in https://reviews.llvm.org/rG0f499d1ed4a170501630d8118b4b396b07493c14

Revert "Fix for top-of-tree LLVM"

---

apps/hexagon_benchmarks/conv3x3_generator.cpp
apps/hexagon_benchmarks/dilate3x3_generator.cpp
apps/hexagon_benchmarks/gaussian5x5_generator.cpp
apps/hexagon_benchmarks/median3x3_generator.cpp
apps/hexagon_benchmarks/sobel_generator.cpp

Fix the following error when compiling `hexgaon_benchmarks` app:
```
Halide/distrib/include/Halide.h:24829:77: error: ‘Halide::Func& Halide::Func::prefetch(const T&, Halide::VarOrRVar, int, Halide::PrefetchBoundStrategy) [with T = Halide::GeneratorInput<Halide::Buffer<unsigned char> >]’ is deprecated: Call prefetch() with the two-var form instead. [-Werror=deprecated-declarations]
24829 |         return this->template as<Class>().Method(std::forward<Args>(args)...)
```

[APP] Fix `hexagon_benchmarks` build (use two-var prefetch)

---

src/CodeGen_WebAssembly.cpp
src/runtime/wasm_math.ll

- f64x2.convert_low_i32x4_s/u  is handled properly by LLVM 14, so remove the TODO stuff and leave the test special-cased for that version (don't bother trying to make it work in LLVM13)
- our `float_to_double` glue is only needed for LLVM13, so update comments and ifdefs appropriately

wasm simd cleanup

---

apps/linear_algebra/src/blas_l1_generators.cpp
apps/linear_algebra/src/blas_l2_generators.cpp
apps/linear_algebra/src/blas_l3_generators.cpp
src/Generator.h

Some are just to pacify tooling that wants single-arg ctors to be `explicit` as a matter of policy; others are to disallow variant forms of Generator input/output initialization in the name of uniformity.

Add `explicit` to a handful of Generator-related ctors.

---

src/Generator.cpp
src/Generator.h
test/generator/metadata_tester_generator.cpp

The constness of the inherited operator[] meant you couldn't call scheduling methods on array-of-output-buffer in a Generator. Fixed and added a test case.

Allow calling scheduling methods on Output<Buffer[]>

---

python_bindings/correctness/compile_to.py
python_bindings/src/PyEnums.cpp
python_bindings/src/PyModule.cpp
python_bindings/tutorial/lesson_10_aot_compilation_generate.py
src/Func.cpp
src/Func.h
src/Generator.cpp
src/Module.cpp
src/Module.h
src/Pipeline.cpp
src/Pipeline.h
test/correctness/compile_to.cpp
test/correctness/compile_to_multitarget.cpp
test/correctness/float16_t_neon_op_check.cpp
test/correctness/python_extension_gen.cpp
test/correctness/pytorch.cpp
test/correctness/simd_op_check.h

It would be nice in future if we could promote Generator::Input and
Generator::Output to the Halide namespace. For that to happen, we need
to rename the enum Output first. This PR adds a new name for it, and
deprecates the old name. 
Not married to the name OutputFile. Other suggestions welcome.

Rename Output to OutputFileType and deprecated Output

---

src/CodeGen_WebAssembly.cpp
src/runtime/wasm_math.ll
test/correctness/simd_op_check.cpp

For reasons that are still under investigation, the WebAssembly simd128 instructions to do integer widening aren't getting emitted by LLVM14. This adds explicit pattern-matching code to generate them for typical cases as a temporary workaround pending more detailed investigation.

Add support for wasm-simd ops for integer-integer widening

---

src/LLVM_Runtime_Linker.cpp

(Second attempt at this; first version was landed and rolled back because the LLVM change was rolled back)

Fix Win32-specific breakage in top-of-tree LLVM

---

src/Bounds.cpp

The bounds visitor on a let should use `unique_name()` for the introduced variables. Without this change, Halide sometimes internally generates expressions of the form `(let x = (let x = ... in ...) in ...)` which can cause failures when substituting in lets and simplifying.

Make bounds of let visitor use unique_name()

---

python_bindings/correctness/partialbuildmethod_generator.cpp
python_bindings/correctness/pystub.py
src/Generator.cpp
src/Generator.h
src/LLVM_Runtime_Linker.cpp
test/generator/buildmethod_generator.cpp

This makes the use of the `build()` method in Generators unsupported by default in Halide 14. The newer, `generate()` based approach has been preferred for quite some time, and it is believed that very few downstream users still have any code in that form. (Halide itself only has a couple of remaining uses, and they exist only to verify that the build() method still works.)
This hides all support for `build()` behind the `HALIDE_ALLOW_GENERATOR_BUILD_METHOD` preprocessor flag, which defaults to undefined -- Generators with build() methods won't compile in this state.
To allow downstream users time to adapt any remaining code, they can #define `HALIDE_ALLOW_GENERATOR_BUILD_METHOD` in their build system, which will allow the old code to compile (with deprecation warnings).
The intent here …

Deprecate the Generator::build() method

---

apps/fft/fft_aot_test.cpp
apps/hannk/util/buffer_util.h
python_bindings/src/PyBuffer.cpp
src/Argument.h
src/Buffer.h
src/Closure.h
src/Generator.cpp
src/Generator.h
src/Module.h
src/Parameter.h
src/RDom.h
src/Realization.h
src/runtime/HalideBuffer.h
test/correctness/halide_buffer.cpp
test/generator/metadata_tester_generator.cpp
tools/halide_image_io.h

Currently, `Halide::Runtime::Buffer<>`* allows you to provide a static ElementType, which allows you to enforce compile-time type checking to ensure incompatible Buffers aren't intermixed. You can also defeat this by using an ElementType of `void`, which defers all type checking to runtime.
Unfortunately, there isn't a way to do the same for the *dimensionality* of a Buffer; all checking for matching dimensionality is done at runtime. This PR proposes to extend `Halide::Runtime::Buffer<>`* to allow for optional specification of dimensionality as well, with only a slight incompatibility with existing code.
Currently, `H::R::B<>` is a template with two arguments:
- `H::R::B<typename T = void, int D = 4>`
- `T`, which is the element type; if omitted, defaults to `void`.
- `D`, which …

Expand optional static-typing for Buffer to include dimensionality

---

src/CodeGen_PyTorch.cpp
src/runtime/HalidePyTorchHelpers.h
test/correctness/pytorch.cpp

This PR does two things:
1. split the helper function that wraps PyTorch tensors into Halide buffers into 2: one for CPU tensors, one for GPU tensors. Before the PR, the wrapper may fail on CPU-only machine because `halide_cuda_device_interface` is missing.
2. add a default `__user_context = nullptr` in CPU-only ops. The auto-scheduler can create intermediate functions that have a __user_context input. This case was not handled by the CodeGen, so compilation would fail. We now create a default null context instead.

Fixes the Pytorch Wrapper Codegen for CPU-only machines.

---

src/Buffer.h
src/ExternFuncArgument.h
src/Func.h
src/Generator.h
src/ParamMap.h
src/Pipeline.h
src/runtime/HalideBuffer.h
tools/halide_image_io.h

More details that should have been in #6574:
- Buffer needed to make some methods constexpr, and also had a broken return value for `as<>()`
- Various templated methods needed to add `int Dims` as a parameter
- Generator::add_input() and add_output() needed specializations for static-buffer types
- sliced() and embedded() should use the default values for InClassDimStorage
- halide_image_io should use a named constant

Various fixes to static-dimensioned Buffer

---

src/FindIntrinsics.cpp
test/correctness/intrinsics.cpp

widening_mul handles mixed-signedness args, but mul_shift_right doesn't.
We shouldn't map a mixed-signedness widening_mul to a mul_shift_right.

Fix bug in mul_shift_right matching

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

First set of changes to remove code that recovers the target type from an LLVM ```PointerType``` as this functionality is going away with opaque pointers. I think this is the bulk of the work for this, but there is probably some needed to our .ll and it needs to be tested with LLVM's -opaque-pointers flag everywhere. (Which is not working for me yet. Not sure how much of the issue is on our side, but I get the impression this is happening right now and it isn't done yet. Ultimately the flag will be unnecessary as LLVM will just have opaque pointers.)
Couple TODOs to remove debug code before commit. It is still there to get extra info during CI runs if something fails. (The debug validation has to use the API we are removing, which is why it needs to be removed.) Maybe one other TODO …

Fixes to support LLVM with opaque pointers.

---

src/Func.cpp

Because parallelization changes the order of computation within the reduction, parallelizing associative but non-commutative reductions can result in (non-deterministically) incorrect results in the same way `reorder`ing them can.
For instance Halide currently accepts the following code, but generates non-deterministic outputs on GPU.  On CPU with `.parallel(r.x)`, OpenMP rejects the generated code (correctly) stating that the `#pragma omp atomic` is invalid for the same reasons.
```c++
#include <stdio.h>
#include "Halide.h"
using namespace Halide;
int main(int argc, char **argv) {
Halide::Func A("A"), B("B");
Halide::Var i("i");
A(i) = i;
B() = -1;
Halide::RDom r(0, 1024);
B() = A(r.x);
A.compute_root();
B.update().atomic().gpu_blocks(r.x); …
```

Only commutative reductions can be parallelized

---

dependencies/wasm/CMakeLists.txt

Commit 09c40635207d42dd30ffaca22477fd3491dd9e7d is no longer being recognized for WABT; rather than whack-a-mole, let's just use `main` temporarily (I've requested the WABT team make a new tag ASAP so we can standardize on the new API)

Unbreak WABT again by using main instead of a commit

---

src/Generator.cpp

- Clean up the Generator usage string, reformat to proper width, use a raw string for cleaner reading
- Move the main_inner() func into an anon ns
- don't use `cerr` as a var name, just in case of ambiguity wrt `std::cerr`

Minor Generator cleanup

---

Makefile
tools/halide_config.cmake.tpl

What it says on the tin. I didn't remove the pattern rules for the possibility of there eventually being _other_ build `halide_config.*.tpl` files we want to generate.

Remove halide_config.cmake from Makefile build. Fixes #6615

---

src/Generator.cpp
src/Generator.h
test/generator/stubuser_generator.cpp

This is some under-the-hood work to make experiments in implementing Generate in Python a bit more tractable. Currently, GeneratorContext is a base class for Generator, but can't really be used in standalone form (e.g. it's not copyable). For various reasons, this makes the Python code a lot more unpleasant to deal with, so this PR now moves the equivalent of a GeneratorContext inside Generator -- dispensing with the inheritance -- and makes GeneratorComplex much simpler for Python to deal with.
The change should be 100% to downstream code  ~~, *EXCEPT* for code that uses GeneratorStubs -- the first argument to the stub must now be `context()` rather than `this`. AFAIK literally no one outside Google has ever used these, so I'd rather just make the small breaking change here and fix the …

Move GeneratorContext into a standalone class

---

src/IROperator.h

The result of `widening_add` is not always signed.

Remove incorrect docs on widening_add

---

src/IREquality.cpp
test/correctness/CMakeLists.txt
test/correctness/cse_nan.cpp

Our IRComparer's `compare_scalar` believed that all floating point values are totally ordered, which is not true. NaNs always compare false in ordering comparisons.
Fixes #6624

Make IRComparer consider nans to be less than non-nans.

---

src/Type.h

Allowing these methods to create bitwidths of `2` and `4` can cause issues with `find_intrinsics`. Specifically, this fixes #6601 .
Discussed with @abadams .

Disallow `Type::narrow()` and `Type::widen()` from producing bitwidths between 1 and 8 bits

---

src/FindIntrinsics.cpp

#6622, specifically making narrowing of uint1 an error broke some of our internal tests. The simplest reproducer would be an expression like `u8(x > 0) + u8(y > 0)`, which would get replaced by `widening_add(x > 0 + y > 0)` where type of `widened_add` is `uint8`, which later at https://github.com/halide/Halide/blob/main/src/FindIntrinsics.cpp#L620 will get narrowed twice and cause u8->u1->error. 
Here I just looked for all places where narrow().narrow() happens and added a check to make sure that type has at least 16-bit, which seems to fix all failing tests I was seeing.

Avoid double narrowing in widening_add/widening_sub if type is 8-bit

---

src/IRMatch.h

`Wild` objects should not be foldable, `WildConst` should be used when matching against constants. There are no use cases of a `Wild` object being folded, so this should be removed unless there is a relevant use-case.

Wild match object should not be foldable

---

python_bindings/Makefile
python_bindings/correctness/bit_test.py

Some of the tests with Generator dependencies had deps set up in a weird way that made some downstream work painful. Cleaned up. Also vastly reduced build-time noise.

Clean up python_binding Makefile

---

python_bindings/correctness/CMakeLists.txt
python_bindings/correctness/realize_warnings.py
python_bindings/src/PyError.cpp

When I realize `g` in the snippet below, I get a SIGSEGV in `PyErr_Occurred`. This example is run with python bindings from `release/13.x` branch.
**Expected**: I see the warning
> Warning: It is meaningless to bound dimension v0 of function f to be within [0, 127] 
> because the function is scheduled inline.
**Actual**: SIGSEGV
I added a `py::gil_scoped_acquire` before printing similar to `halide_python_print()` in `PyError.cpp` and this fixes the output. Should I release the GIL?
```py
buffer = Buffer(np.arange(2048))
i = Var()
f = Func("f")
f[i] = buffer[i]
f.bound(i, 0, 127)
g = Func("g")
g[i] = f[i * i]
g.realize([16])
```
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fa43811932e in PyErr_Occurred () from /usr/lib/libpython3.9.so.1.0
(gdb) bt
#0 …
```

python_bindings: Fix SIGSEGV in HalidePythonCompileTimeErrorReporter

---

src/Simplify_Cast.cpp

When simplifying casts, if the bound's min is undefined, we need to clear the bound's max value if the type has defined overflow behavior. Likewise, if the bound's max is undefined.
Fixes #6639

Clear bounds info on casts when value bounds are undefined for overflow types

---

src/CodeGen_C.cpp

in the Load handler, we need to emit the cast in the form `TYPE const *` rather than `const TYPE *`, as TYPE could be `void *`, and the const would bind in a way we don't want.
attn @knzivid

Fix const-correctness in C/C++ backend (Issue #6636)

---

apps/hannk/util/buffer_util.h

A recent change to libc++ rejects std::uniform_int_distribution<uint8_t>
explicitly (https://reviews.llvm.org/D114920). This change prevents this file
to build with upcoming revisions of the C++ toolchain.

Fix UB in hannk FillWithRandom operation.

---

src/LLVM_Runtime_Linker.cpp

The profiler requires threads, but works fine when wasm_threads are enabled.

Allow profiler feature under wasm iff wasm_threads is enabled

---

src/WasmExecutor.cpp

The copy and move assignment operators for Store are going away; initialize ours in the traditional way to work with both old and new code.
attn: @sbc100

Update initialization of WABT `store` field to work with top-of-tree

---

dependencies/llvm/CMakeLists.txt
src/runtime/CMakeLists.txt

As far as i can tell, they are always exactly identical,
and i don't believe the claim that `LLVM_PACKAGE_VERSION`
doesn't exist in upper scopes is valid.

[CMake] Deduplicate `Halide_LLVM_VERSION` and `LLVM_PACKAGE_VERSION`

---

src/ClampUnsafeAccesses.cpp

My attempt at @abadams suggestion for a simple improvement.

Eliminate some unnecessary clamping in ClampUnsafeAccesses (#6297)

---

src/runtime/synchronization_common.h

Yes, some compilers complain about this.

Fix 'variable set but not used` warning/error

---

python_bindings/correctness/basics.py
python_bindings/src/PyExpr.cpp

It was implicitly converting to a Halide `Int(32)` literal of value 1, but we want it to match Halide's boolean type of `UInt(1)`

Python Bindings: fix Python `bool` -> `Expr` implicit conversion

---

apps/bgu/Makefile
apps/bgu/filter.cpp
src/runtime/HalideBuffer.h
test/performance/fast_pow.cpp

This adds some optional `assert()` checks to HRB's `operator()` and friends. They are only enabled if `HALIDE_RUNTIME_BUFFER_CHECK_INDICES=1` is defined at compile time.
Also fixes errors found by enabling these assertions and running tests.

Add optional runtime H::R::Buffer access checks

---

Makefile

With asan or tsan in the target, there is a space in the OPTIMIZE var, so it needs to be quoted.

Allow `make test_apps` to work with ASAN

---

python_bindings/correctness/ext/CMakeLists.txt
python_bindings/correctness/ext/ext.ldscript.apple.in
python_bindings/correctness/ext/ext.ldscript.linux.in

We added ldscripts to the Makefile for Python extensions (to restrict exported symbols to just the PyInit_foo symbol), but neglected to do so for CMake. This corrects that.

Add ldscript code for Python extensions in CMake

---

python_bindings/src/PyEnums.cpp
python_bindings/src/PyTarget.cpp
src/CodeGen_X86.cpp
src/Module.cpp
src/Target.cpp
src/Target.h

This is mainly a future proofing.
#6655 added certain `processor` fields, which specify the CPU
for which we should tune, without implying features,
but the field name is awfully generic.
Once we want to add a second processor field,
that will mean features, such a field should have a name
of `processor`/`processor_target`, yet `processor` already means `tune`...
I'm not renaming the enum, i don't see why we'd need a second one.

Future-proof 'processor` to `tune processor`

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyPipeline.cpp
src/Func.cpp
src/Pipeline.cpp
src/Realization.cpp
src/Realization.h

For vector-of-Buffers, the ctor took a non-const ref to the argument, which was weird and nonsensical. Replaced with a const-ref version and and an rvalue-ref version; it turns out that literally *all* of the internal calls were able to use the latter, trivially saving some copies.

Fix ctors for Realization

---

src/Target.cpp

Based on the base support for `-mtune=` implemented in #6655,
as discussed in https://github.com/halide/Halide/issues/6515,
this implements bare-bones CPU detection using vendor/family/model derived from CPUID,
and adds autodetection for `znver3` via that framework.
The local result is:
```
$ ./src/autoschedulers/adams2019/get_host_target
x86-64-linux-tune_znver3-avx-avx2-f16c-fma-sse41
```
Usage caveat: if you do not intend to run the code you are compiling on the host,
but `host` is part of the target string, you may want to ensure that you override the autodetected tune CPU.
Fixes https://github.com/halide/Halide/issues/6515

`-mtune=native` CPU autodetection for AMD Zen 3 CPU

---

CMakeLists.txt
README.md

As it says in the title... bump development Halide version to 15.0.0
Also changes the language in the README so we don't keep forgetting to update it.

Bump development Halide version to 15.0.0

---

python_bindings/src/PyBuffer.cpp
src/autoschedulers/adams2019/LoopNest.cpp
src/autoschedulers/adams2019/State.cpp
src/autoschedulers/li2018/GradientAutoscheduler.cpp

Apparently XCode 13.3 has smarter warnings about unused code and emits warnings/errors for these, so let's clean them up.

Fix "set but not used" warnings/errors

---

src/Module.h

It was deprecated (in favor of `OutputFileType` in Halide 14; let's remove it entirely for Halide 15.

Remove deprecated `Halide::Output` type

---

src/CodeGen_C.cpp
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGLCompute_Dev.cpp

even if asserts are enabled, since generated closure functions may not use it

Always mark _ucon as 'unused' in Codegen_C

---

src/CMakeLists.txt

Clang 13 removed the `return-std-move-in-c++11` warning entirely, so specifying it now warns that the warning is unknown.

Silence "unknown warning" in Clang 13

---

python_bindings/src/PyScheduleMethods.h
src/Func.h

These were deprecated in Halide 14; let's remove them now.

Remove deprecated versions of Func::prefetch()

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyScheduleMethods.h
python_bindings/src/PyStage.cpp

This allows for `compute_with` and `rfactor` to work more seamlessly in Python.
Also:
- Move two compute_with() variant bindings from PyFunc and PyStage to PyScheduleMethods, as they are identical between the two
- drive-by removal of redundant `py::implicitly_convertible<ImageParam, Func>();` call
attn: @apartridge

Python: make Func implicitly convertible to Stage (#6702)

---

python_bindings/src/PyFunc.cpp
python_bindings/src/PyScheduleMethods.h
python_bindings/src/PyStage.cpp

This allows for `compute_with` and `rfactor` to work more seamlessly in Python.
Also:
- Move two compute_with() variant bindings from PyFunc and PyStage to PyScheduleMethods, as they are identical between the two
- drive-by removal of redundant `py::implicitly_convertible<ImageParam, Func>();` call

[cherry-pick to 14.0.1] Python: make Func implicitly convertible to Stage (#6702)

---

src/CodeGen_ARM.cpp
src/CodeGen_X86.cpp

LLVM is moving to opaque pointers, we must have missed this one in previous work

Remove the last remaining call to getPointerElementType()

---

src/CodeGen_ARM.cpp

The fixes from last week regarding mangling of arm vst intrinsics needs to be made conditional on whether the pointer is opaque or not; this will change based on whether `-D CLANG_ENABLE_OPAQUE_POINTERS=ON|OFF` is defined when LLVM is built, but should be sniffed via this API, according to my LLVM contact.

ARM vst mangling needs to be conditional on opaque ptrs

---

src/IROperator.cpp

This is a pretty trivial optimization, but when printing (or enabling `debug`), it cuts the number of `halide_string_to_string()` calls we generate by ~half.

Combine string constants in combine_strings()

---

src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp

This was still using the LegacyPassManager for optimization, which will be going away at some point. (Code changes by @alinas; I'm just opening this PR on her behalf)
Fixes #[6710](https://github.com/halide/Halide/issues/6710)

Update CodeGen_PTX_Dev to use new PassManager

---

src/LowerParallelTasks.cpp

Closure functions for parallel tasks should be internal, not external

---

Makefile
src/LowerParallelTasks.cpp
src/Type.cpp
src/Type.h

(Fixes #2093)
This basically just adds the right type annotations to make the parallel code produced by the C backend compile properly. This could have been fixed by inserted some brute-force void* casting into the C backend, but this felt a lot cleaner.
The one thing here I'm a little unsure about is how I extended the Type code to be able to handle function-pointer types correctly; it works but doesn't feel very elegant.

Smarten type_of<> for fn ptrs; fix async_parallel for C backend

---

src/Target.cpp

I have *not* personally tested that these are detected correctly,
Cross-reference between
* https://github.com/llvm/llvm-project/blob/955cff803e081640e149fed0742f57ae1b84db7d/llvm/lib/Support/Host.cpp#L968-L1041
* https://github.com/llvm/llvm-project/blob/955cff803e081640e149fed0742f57ae1b84db7d/compiler-rt/lib/builtins/cpu_model.c#L520-L586
* https://github.com/gcc-mirror/gcc/blob/000c1b89d259fadb466e1f2e63c79da45fd17372/gcc/common/config/i386/cpuinfo.h#L111-L264

`get_amd_processor()`: implement detection for the rest of supported AMD CPU's

---

python_bindings/src/PyFunc.cpp
src/Func.cpp
src/Func.h

Basically this mirrors the existing `output_buffer()` vs `output_buffers()` call -- the singular versions assert that the Func returns an Expr and not a Tuple. Also, add assertion to output_buffer() that checks if the Func is defined, to give a gentler failure mode.

Add Func::output_type() method

---

python_bindings/src/PyConciseCasts.cpp
python_bindings/src/PyExpr.cpp
python_bindings/src/PyImageParam.cpp
python_bindings/src/PyLoopLevel.cpp
python_bindings/stub/PyStubImpl.cpp

Just a handful of minor fixes and cleanups that have accumulated from a work-in-progress branch but should go ahead and land regardless.

Grab-bag of minor Python fixes

---

src/CodeGen_ARM.cpp
src/FindIntrinsics.cpp
src/FindIntrinsics.h
src/IR.cpp
src/IR.h
src/IRMatch.h
src/IROperator.cpp
src/IROperator.h
test/correctness/intrinsics.cpp

These instructions don't seem to exist, they don't get produced when compiling for arm. https://github.com/gcc-mirror/gcc/commit/2e828dfe91a39a7a898ca6d8827048760e08b236 suggests that they were supposed to exist at some point, but were never implemented.

Remove `rounding_halving_sub` and non-existent arm rhsub instructions

---

python_bindings/correctness/basics.py
python_bindings/src/PyFunc.cpp
src/Buffer.h
src/Func.cpp
src/Func.h
src/Function.cpp
src/Function.h
src/Pipeline.cpp
test/error/CMakeLists.txt
test/error/func_expr_dim_mismatch.cpp
test/error/func_expr_type_mismatch.cpp
test/error/func_expr_update_type_mismatch.cpp
test/error/func_extern_dim_mismatch.cpp
test/error/func_extern_type_mismatch.cpp
test/error/func_tuple_dim_mismatch.cpp
test/error/func_tuple_types_mismatch.cpp
test/error/func_tuple_update_types_mismatch.cpp

This enhances Func by allowing you to (optionally) constrain the type(s) of Exprs that the Func can contain, and/or the dimensionality of the Func. (Attempting to violate either of these will assert-fail.)
There are a few goals here:
- Enhanced code readability; in cases where a Func's values may not be obvious from the code flow, this can allow an in-code way of declaring it (rather than via comments)
- Enhanced type enforcement; specifying constraints allows us to fail in type-mismatched compilations somewhat sooner, with somewhat better error messages.
- Better symmetry for AOT/JIT code generation with ImageParam, in which the inputs (ImageParam) have a way to specify the required concrete type, but the outputs (Funcs) don't.
If this is accepted, then subsequent changes will likely add …

Augment Halide::Func to allow for constraining Type and Dimensionality

---

python_bindings/correctness/basics.py
src/Func.cpp
src/Func.h
src/Function.cpp
src/Function.h
src/Generator.cpp
src/ImageParam.cpp
test/correctness/CMakeLists.txt
test/correctness/typed_func.cpp

- Allow Func output_type(s)(), outputs(), dimensions(), and output_buffer(s)() to be called on undefined Funcs if the Func has required_type and required_dimensions specified. This allows for greater flexibility in defining pipelines in which you may want to set or examine constraints on a Func that hasn't been defined yet; previously this required restructuring code or other awkwardness.
- Ensure that the Funcs that are defined for ImageParams and Generator fields define the types-and-dims when known.
- Add some tests.

More typed-Func work

---

src/Func.cpp
test/correctness/typed_func.cpp
test/error/func_expr_update_type_mismatch.cpp
test/error/func_tuple_update_types_mismatch.cpp

That change inadvertently required the RHS of an update stage that used `+=` (or similar operators) to match the LHS type, which should be required (implicit casting of the RHS is expected). Restructured to remove this, but still ensure that auto-injection of a pure definition matches the required types (if any), and updated tests.

Fix regression from #6734

---

python_bindings/Makefile
python_bindings/correctness/generators/CMakeLists.txt
python_bindings/correctness/generators/complex_generator.cpp
python_bindings/correctness/pystub.py
python_bindings/stub/PyStubImpl.cpp
src/Func.cpp
src/Generator.cpp

This is a rethink of https://github.com/halide/Halide/pull/6661, trying to make it saner in anticipation of the ongoing Python Generator work.
TL;DR: instead of mixing GeneratorParams in with the rest of the keywords, segregate them into an optional `generator_params` keyword argument, which is a plain Python dict. This neatly solves a couple of problems:
- synthetic params with funky names aren't a problem anymore.
- error reporting is simpler because before an unknown keyword could have been intended to be a GP or an Input.
- GP values are now clear and distinct from Inputs, which is IMHO a good thing.
This is technically a breaking change, but I doubt anyone will notice; this is mainly here to get a sane convention in place for use with Python Generators as well.
Also, a drive-by …

Revise PyStub calling convention for GeneratorParams

---

src/runtime/HalideBuffer.h

In at least one version of GCC (Debian 11.2.0-16+build1), an optimized build using `Buffer::for_each_element(int *pos)` will give (incorrect) compiler warnings/errors that "pos may be used uninitialized).
From inspection of the code I feel pretty sure this is a false positive -- i.e., the optimizer is confused -- and since no other compiler we've encountered issues a similar warning (nor do we see actual misbehavior), I'm inclined not to worry -- but the warning does break some build configurations.
Rather than try to fight with selectively disabling this warning, I'm going to propose inserting a memset() here to reassure the compiler that the memory really is initialized; while it's unnnecessary, it's likely to be insignificant compared to the cost of usual calls to for_each_element(). …

Silence "may be used uninitialized" in Buffer::for_each_element()

---

python_bindings/correctness/basics.py
python_bindings/correctness/extern.py
python_bindings/correctness/pystub.py
python_bindings/correctness/tuple_select.py
python_bindings/src/PyError.cpp
python_bindings/stub/PyStubImpl.cpp

Per suggestion from @alexreinking, this remaps all exceptions thrown by the Halide Python bindings to be `halide.HalideError` (or a subclass thereof), rather than plain old `RuntimeError`.

Add a `HalideError` base class to Python bindings

---

src/Generator.cpp
src/Generator.h

Minor hygiene: most getters in Halide don't have a `get_` prefix. These are very rarely used (only one instance in our test suite I could find) but, hey, cleanliness.

Deprecate GeneratorContext getters with `get_` prefix

---

src/Generator.cpp
src/Generator.h

This provides hooks to allow overriding the Generator(s) that generate_filter_main() can use; normally it defaults to the global registry of C++ Generators, but this allows for (e.g.) alternate-language-bindings to selectively override this (e.g. to enumerate only Generators that are visible in that language, etc).
(No visible change in behavior from this PR; this is just cherry-picked from work-in-progress elsewhere to simplify review & merge)

Add GeneratorFactoryProvider to generate_filter_main()

---

apps/onnx/model.cpp
python_bindings/src/PyEnums.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/HexagonOffload.cpp
src/Target.cpp
src/Target.h
src/autoschedulers/adams2019/autotune_loop.sh
src/runtime/HalideRuntime.h
test/correctness/simd_op_check.h
test/performance/const_division.cpp
test/performance/nested_vectorization_gemm.cpp

This PR proposes to (finally) deprecate disable_llvm_loop_opt:
- make LLVM codegen default to no loop optimization; you must use enable_llvm_loop_opt explicitly to enable it
- disable_llvm_loop_opt still exists, but does nothing (except issue a user_warning that the feature is deprecated)
- Remove various uses of disable_llvm_loop_opt
- Add comments everywhere that the default is different in Halide 15 and that the disable_llvm_loop_opt feature will be removed entirely in Halide 16
Note that all Halide code at Google has defaulted to having disable_llvm_loop_opt set for ~years now, so this is a well-tested codepath, and consensus on the Issue seemed to be that this was a good move.

Deprecate disable_llvm_loop_opt (#4113)

---

src/Generator.cpp
src/Module.cpp
test/correctness/compile_to_multitarget.cpp

(Harvested from #6757, which probably won't land)
- Add clarifying comment/reference in Generator
- Add assertion to compile_to_multitarget() function
- Fix misleading/wrong code in correctness_compile_to_multitarget

Minor metadata-related cleanups

---

test/correctness/vector_reductions.cpp

A recent bug in LLVM codegen was missed because it only affected x86 architectures with earlier-than-AVX2 SIMD enabled; it didn't show up for AVX2 or later. This revamps correctness_vector_reductions to re-run multiple times when multiple SIMD architectures are available on x86 systems.
(correctness_vector_reductions was chosen here because it reliably demonstrated the specific failures in this case.)

Expand the x86 SIMD variants tested in correctness_vector_reductions

---

src/Param.h
src/Util.h
test/correctness/param.cpp

The `set_estimate` method needed to specialize for T=void to do runtime checking of the correct type to test. (Previously, we'd get the confusing error that "the value can't be converted losslessly", because, technically, float <-> void is indeed not a roundtrippable conversion.)
While I was there, did drive-by updating of `Param::set`, `IsRoundtrippable`, and `StaticCast` to use the C++17 `if constexpr` mechanism instead of `enable_if`, which IMHO is vastly more readable.

Fix Param<T>::set_estimate for T=void

---

src/RealizationOrder.cpp
src/ScheduleFunctions.cpp
test/error/CMakeLists.txt
test/error/compute_with_fuse_in_specialization.cpp

Fixes https://github.com/halide/Halide/issues/6763.
From the issue above, the following program will produce incorrect code inside of the specializaiton branch:
```
Func out0, out1;
out0(x,y) = 1 * in(x,y);
out1(x,y) = 2 * in(x,y);
out0.vectorize(x, vs);
out1.vectorize(x, vs).compute_with(out0, x);
out0.specialize(in.dim(1).stride() == 128).fuse(x,y,f);
```
instead this should be an error just like in the case of the same code, but without specialization: 
```
Func out0, out1;
out0(x,y) = 1 * in(x,y);
out1(x,y) = 2 * in(x,y);
out0.vectorize(x, vs);
out1.vectorize(x, vs).compute_with(out0, x);
out0.fuse(x,y,f);
```
which will produce a following error:
```
terminate called after throwing an instance of 'Halide::CompileError'
what():  Error: Invalid compute_with: cannot find x in out0.s0 …
```

Update the list of fused_pairs and run validate_fused_group for specalization definitions too

---

src/CodeGen_ARM.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/CodeGen_Internal.h
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_MIPS.cpp
src/CodeGen_PTX_Dev.cpp
src/CodeGen_PowerPC.cpp
src/CodeGen_RISCV.cpp
src/CodeGen_WebAssembly.cpp
src/CodeGen_X86.cpp
src/JITModule.cpp

Sooo. Uh, remember when in https://github.com/halide/Halide/pull/6655
we've agreed that we want to add support to precisely specify
the CPU for which the code should be *tuned* for,
but not *targeted* for. Aka, similar to clang's `-mtune=` option,
that does not affect the ISA set selection?
So guess what, that's not what we did, apparently.
`CodeGen_LLVM::mcpu()` / `halide_mcpu` actually do specify
the *target* CPU. It was obvious in retrospect, because e.g.
`CodeGen_X86::mattrs()` does not, in fact, ever specify `+avx2`,
yet we get AVX2 :) So we've unintentionally added `-march=` support.
Oops.
While i'd like to add `-march=` support, that was not the goal here.
Fixing this is complicated by the fact that
`llvm::Target::createTargetMachine()` only takes `CPU Target` string,
you can't …

Fix fundamental confusion about target/tune CPU

---

src/Generator.cpp
src/Generator.h
src/Lower.cpp
src/Util.cpp
src/Util.h
tools/GenGen.cpp

This refactors the existing `generate_filter_main()` call in two, moving the interesting implementation of how to drive AOT into the new `execute_generator()` call (reducing `generate_filter_main()` to parsing argc/argv and error reporting).
The new `execute_generator()` is intended to be used (eventually) from Python, as a way to drive Generator compilation from a Python script more easily. The PR doesn't provide a Python wrapper for this call yet (that will come in a subsequent PR).
Also, a drive-by removal of the "error_output" arg to generate_filter_main() -- AFAICT, no one has ever used it for anything but stderr, and the refactoring now just directs all errors to `user_error` uniformly.

Add execute_generator() API

---

src/Generator.cpp
src/Generator.h

Loading plugins and setting the default autoscheduler name both change global state, which isn't a desirable fit for execute_generator(), since it's not intended to mutate global state. (Mutating the state from a main() function is of course a reasonable thing to do.)

Move some options from execute_generator back to generate_filter_main

---

src/CodeGen_LLVM.cpp

It's the default after https://reviews.llvm.org/D113210 / https://github.com/llvm/llvm-project/commit/13317286f8298eb3bafa9ddebd1c03bef4918948,
but still needs to be done for earlier LLVM's.
Refs. https://github.com/halide/Halide/issues/6783
Refs. https://github.com/halide/Halide/pull/6718
Partially reverts https://github.com/halide/Halide/pull/6718

LLVM codegen: register AA pipeline if LLVM is older than 14

---

src/Float16.h

The ones in HalideRuntime.h have been marked constexpr for a while, but the ones in Float16.h got missed

halide_type_of<>() should always be constexpr

---

test/correctness/hexagon_scatter.cpp

It will run otherwise, but is slow on some other targets; rather than trying to (e.g.) shard it, just skip it

hexagon_scatter test should run only if target has HVX

---

test/common/test_sharding.h
test/correctness/boundary_conditions.cpp
test/correctness/compute_with.cpp
test/correctness/float16_t_neon_op_check.cpp
test/correctness/mul_div_mod.cpp
test/correctness/rfactor.cpp
test/correctness/simd_op_check.cpp
test/correctness/simd_op_check.h
test/correctness/simd_op_check_hvx.cpp
test/correctness/vector_cast.cpp
test/correctness/vector_math.cpp
test/correctness/vector_reductions.cpp

The simd_op_check test suite is pretty slow (especially for wasm, where it is interpreted); at one point we tried to use ThreadPool to speed it up, but too many pieces of Halide IR aren't threadsafe and we disabled it long ago.
This removes the ThreadPool usage entirely, and instead adds support for the GoogleTest 'sharded test' protocol, which uses certain env vars to allow a test to opt in for splitting its test into smaller pieces.
At present our buildbot isn't attempting to make use of this feature, but it will be a big win for downstream usage in Google, where tests that run "too long" are problematic and splitting them into multiple shards makes various day to day activiites much more pleasant.

slow tests should support sharding

---

src/WasmExecutor.cpp

At least one compiler thinks we can use this without initialization, which isn't true, but this silences it.

Silence a "possibly uninitialized" warning

---

.gitignore
src/CodeGen_C.cpp
src/CodeGen_C.h
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/Generator.cpp
src/Generator.h
src/Module.cpp
src/Module.h
test/generator/abstractgeneratortest_generator.cpp

Add typedefs for `GeneratorParamMap` and `MetadataNameMap` to distinguish their usage from other string maps.
Also, drive-by addition to .gitignore.

Minor typedef cleanup

---

src/AlignLoads.cpp
test/correctness/simd_op_check_hvx.cpp

This is in addition to the current 1-, 2-, 3- strides. 
This change is motivated by the 4x downsample use-case where I see a significant performance improvement after enabling these.

Rewrite strided loads of 4 in AlignLoads

---

src/Bounds.cpp
src/InferArguments.cpp
test/correctness/CMakeLists.txt
test/correctness/early_out.cpp

I was trying out using a where clause in a big or reduction to get early-out behavior and found two bugs that this PR fixes.
First, if there's a param that's only used in a specialization of a wrapper func, it isn't picked up by InferArguments.
Second, a variable-free condition that feeds into bounds inference is assumed to depend only on parameters, which is a bad assumption because it could also be a scalar Func. 
Both of these manifested as compilation failures.

Fix two minor bugs triggered by an or reduction with early-out

---

.gitignore

While setting up a new development environment with VS Code, I accidentally did an in-tree build. This pumped out a bunch of files that shouldn't be checked in. Between these and the VS Code specific ignores, I went down a rabbit hole of auditing our .gitignore. Lotta stuff for OCaml builds from a decade ago in there.
The new .gitignore should be relatively robust to in-tree builds and to out-of-source builds with unexpected directory names. It's a bit hard to distinguish Halide-generated header file names in some circumstances. I wonder if we can adjust our build to improve on this (e.g. putting them all in a `_gen/` subfolder so we can match on `**/_gen/*`)
It is also grouped by reason for inclusion/exclusion and ignores files without extensions (which are presumed to be executables). …

Rework .gitignore

---

src/CodeGen_LLVM.cpp

Fixes error found in CI run of https://github.com/halide/Halide/pull/6821
Breakage caused by https://github.com/llvm/llvm-project/commit/dacfa24f75c328ae30b710ecadaa18e4ba10cdc6

Fix for top-of-tree LLVM

---

python_bindings/Makefile
python_bindings/correctness/generators/CMakeLists.txt
python_bindings/correctness/pystub.py

This is a bit finicky, but making this the default nomenclature will make some downstream usages less ambiguous and a bit easier to manage. (Yes, I realize that #6821 removes the Makefile entirely, but until it lands, it needs fixing there too.)

Change stub module names in Python to be _pystub rather than _stub

---

Makefile

Removes the last Python vestiges that were kept in place in #6821 for the buildbots' sake.

Scrub Python from Makefile after buildbot update

---

apps/linear_algebra/Makefile

This wasn't biting us before because we were disabling *all* apps/ on x86-32-linux (oops); the recent change to remove python testing under Make also re-enabled this test.
TL;DR: this can probably be made to work somehow, but it's not worth debugging, since that case is both pretty nice, and already covered under CMake. It's literally not worth the time to fix.

Disable testing for apps/linear_algebra on x86-32-linux/Make

---

src/Generator.cpp
src/Generator.h

This is an internal-to-Generator helper that is used to try to detect certain classes of errors when using GeneratorStubs. To the best of my knowledge, it has ~never found a useful error in all of its existence; combined with the very limited usage of GeneratorStubs, I think this code no longer pays for itself, and should be removed.
(Note that this was never externally visible, thus no deprecation warnings should be necessary.)

Remove Generator::value_tracker and friends

---

python_bindings/src/PyBinaryOperators.h
python_bindings/src/PyBuffer.cpp
python_bindings/test/correctness/buffer.py

This is a no-op change; I just want to mark the place(s) in the Python bindings that need attention if/when it becomes possible to support bfloat16 in Python buffers.

Add placeholder code for bfloat16 in Python (#6849)

---

Makefile
test/generator/stubtest_generator.cpp
test/generator/stubuser_aottest.cpp
test/generator/stubuser_generator.cpp

There wasn't any coverage that ensured that called stubs got autoscheduler params passed to them appropriately; now there is. Also, did a drive-by cleanup of the Makefile to make the build rules & deps for the autoscheduler plugins slightly less clunky; PTAL.

Add autoscheduling to the generator_aot_stubuser test

---

src/autoschedulers/adams2019/ASLog.cpp
src/autoschedulers/adams2019/ASLog.h
src/autoschedulers/adams2019/AutoSchedule.cpp
src/autoschedulers/adams2019/DefaultCostModel.cpp
src/autoschedulers/adams2019/Featurization.h
src/autoschedulers/adams2019/FunctionDAG.cpp
src/autoschedulers/adams2019/FunctionDAG.h
src/autoschedulers/adams2019/LoopNest.cpp
src/autoschedulers/adams2019/LoopNest.h
src/autoschedulers/adams2019/State.cpp
src/autoschedulers/adams2019/State.h
src/autoschedulers/adams2019/autotune_loop.sh

The overall goal of this PR is that when *using* the Adams2019 autoscheduler, the default behavior should be no output to stdout or stderr, period, unless a fatal error occurs: no progress, no warnings, nothing. (This can be overridden by setting `HL_DEBUG_AUTOSCHEDULE` or `HL_DEBUG_CODEGEN` as you see fit, for progressively more logging.)
This change happened in multiple steps, though:
- ~~reworked the `aslog()` class to be a proper subclass of `std::ostream` rather than a one-off templated thing~~
- reworked all the `dump()` method to output solely to an `ostream` argument rather than assuming an output level
- tweaked `aslog()` levels in various places; in particular, the *only* place right now that uses `aslog(0)` is the ScopedTimer class (which isn't in use right now and generally …

Silence Adams2019 Autoscheduler

---

src/CodeGen_LLVM.cpp

1. LLVM IR `bitcast` happily bitcasts between vectors and scalars: https://godbolt.org/z/9zqx11rna
2. `ptrtoint` already implicitly truncates/zero-extends if the int is larger than the pointer type: https://llvm.org/docs/LangRef.html#ptrtoint-to-instruction
3. `inttoptr` already implicitly truncates/zero-extends if the int is larger than the pointer type: https://llvm.org/docs/LangRef.html#inttoptr-to-instruction
So we don't need to do any of that 'special' handling.

[Codegen_LLVM] Radically simplify `visit(const Reinterpret *op)`

---

src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp

See discussion in https://github.com/halide/Halide/pull/6866.
It's not obvious if that codepath is ever hit,
let's optimistically assume that it is not.
If this turns out to be not true, we'll have to deal with
a more complicated question of the proper lowering for it,
can it be `poison`, or must it be a `freeze poison`.

[Codegen] Fail to codegen `Call::undef`, just like `Call::signed_integer_overflow`

---

src/autoschedulers/adams2019/Makefile

We erroneously link in the dylib and also dynamically load it, causing an error. We should skip the linkage and always load dynamically..

Fix error in Makefile for Adams2019 on OSX

---

cmake/BundleStatic.cmake

Fixes #6876.
This adds a check to `BundleStatic.cmake` to ensure the extension is non-empty, so we don't pick up files we shouldn't when bundling objects into libHalide.

Ensure $CMAKE_{lang}_OUTPUT_EXTENSION is set before using it

---

src/runtime/internal/block_allocator.h
src/runtime/internal/memory_arena.h
src/runtime/internal/memory_resources.h
src/runtime/internal/region_allocator.h
src/runtime/internal/string_storage.h
src/runtime/internal/string_table.h
test/runtime/block_allocator.cpp
test/runtime/common.h
test/runtime/linked_list.cpp
test/runtime/memory_arena.cpp
test/runtime/string_storage.cpp
test/runtime/string_table.cpp

This PR addresses some obvious defects detected when built under ASAN as reported by @LebedevRI in Issue #6863 :
Fixed initialization defects in StringStorage that could cause buffer overruns.
Fixed memory leaks within RegionAllocator and BlockAllocator.
Added system memory allocation tracking to all internal runtime tests.

#6863 - Fixes to make address sanitizer happy for internal runtime classes

---

src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/runtime/aarch64.ll
src/runtime/arm.ll
src/runtime/powerpc.ll
src/runtime/wasm_math.ll
src/runtime/x86.ll
src/runtime/x86_avx2.ll
src/runtime/x86_avx512.ll
src/runtime/x86_sse41.ll

Long-term plan for LLVM is to get rid of `undef`,
and replace it with zero-initialization,
err, `poison`, because it has nicer semantics.
Everywhere where we use `undef` as a placeholder in shuffle
(be it either for a second operand, or undef shuffle mask element),
or as a base 'empty' vector we are about to fully override
via insertelement, we can just switch those to poison nowadays.
The scary part is the `Call::undef` semantics/lowering,
perhaps it will need to be `freeze poison`.
For this reason, it might not be unreasonable to give this a spin downstream first.

[Codegen_LLVM] Define all the things

---

src/Module.cpp
src/PythonExtensionGen.cpp
src/PythonExtensionGen.h

This is intended as an alternative to #6885 -- this is even *more* gratuitous, but:
- We have ~always compiled Python extensions using C++ anyway
- This code is arguably terser, cleaner, and safer (the cleanups happen via dtors)
- The code size difference is negligible (~300 bytes out of 160k for addconstant.cpython-39-darwin.so)

Rewrite PythonExtensionGen to be C++ based

---

src/autoschedulers/adams2019/CMakeLists.txt
src/autoschedulers/li2018/CMakeLists.txt

These were ~never getting tested on the buildbots (and still aren't, I need to update it to run `auto_schedule` tests) but conceptually these tests should be in the same group as for Mullapudi.
Also, drive-by fix to broken test_apps_autoscheduler injected in https://github.com/halide/Halide/pull/6861.

Add `auto_schedule` label to Adams2019 and Li2018 tests in CMake

---

src/Simplify_Shuffle.cpp

This came up in #6887, happens sometimes even in `apps/`.
(and in fact i initially forgot to recurse, so it was micompiling stuff, took way to look to pinpoint..)

[Simplify] Drop no-op single-input identity shuffles

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp

My reasoning is as follows, please correct me if i'm wrong:
1. Halide-generated code never throws exceptions
2. Halide-generated code always `call`s (as opposed to `invoke`s) the functions, there is no exception-safety RAII
3. Halide loops are meant to have finite number of iterations, they aren't meant to be endless and side-effect free
4. Halide (IR) assertions *might* abort.
5. Likewise, external callees *might* abort. (???)
Therefore, when not in presence of external calls,
it is obvious that (1) no exception will be unwinded
out of the halide-generated function, (2) none of the loops
will end up being endless with no observable side-effects.
... which is the semantics that is being stated by the
LLVM IR function attributes `nounwind`+`mustprogress`.
I'm less clear as to what are the …

[Codegen_LLVM] Annotate LLVM IR functions with `nounwind`/`mustprogress` attributes

---

src/CodeGen_LLVM.cpp

We should only try to fold the pattern:
```
saturating_add(x, VectorReduce(SaturatingAdd, y))
```
Currently, we also try to fold this pattern (incorrectly):
```
saturating_sub(x, VectorReduce(SaturatingAdd, y))
```
Fixes #6883

Don't try to fold saturating_sub of VectorReduce

---

.clang-tidy
.github/workflows/presubmit.yml
run-clang-format.sh
run-clang-tidy.sh
src/BoundsInference.cpp
src/Module.cpp
src/WasmExecutor.cpp
src/runtime/internal/block_allocator.h
src/runtime/internal/block_storage.h
src/runtime/internal/linked_list.h
src/runtime/internal/pointer_table.h
src/runtime/internal/region_allocator.h
src/runtime/internal/string_storage.h
src/runtime/internal/string_table.h
test/runtime/common.h

With LLVM16 being branched off, that means we'll be dropping LLVM13 in the months ahead; this PR proposes to upgrade our required versions of clang-tidy and clang-format to those for LLVM14 (so that no one will have to build or install LLVM13 just for those).
The changes for clang-format are insignificant (it appears to be a bit more aggressive about fixing single-line if statements, which is good).
The changes for clang-tidy are mostly irrelevant, except for changes to `modernize-use-default-member-init` which don't have immediate consensus -- this PR disables that check for now, pending further consideration/investigation. (See https://github.com/halide/Halide/pull/6891 for discussion)

Upgrade clang-format and clang-tidy to v14 (v2)

---

src/ExtractTileOperations.cpp
test/correctness/tiled_matmul.cpp

Addresses #6054 
The current version of AMX can only handle K dimensions which are 4 bytes in size. This is because the way the right hand side (rhs) matrix is laid out is different from the left hand side (lhs). Where the lhs matrix is a regular MxK matrix the rhs is instead K/4xNx4 for i8/u8 and K/2xNx2 for bf16. To handle this an extra `get_3d_rhs_tile_index` function was added.
The correctness tests have been further expanded to handle a variety of cases.
* tile K dimension of 4 bytes
This tests the previous code, using 2d/1d tile index pattern matcher
* tile K dimension larger than 4 bytes but equal to the matrix's K dimension
This handles one of the 2 patterns checked for
* tile K dimension larger than 4 bytes and not equal to the matrix's K dimension
This handles the other pattern …

Allow AMX instructions with K dimension larger than 4 bytes

---

src/autoschedulers/adams2019/DefaultCostModel.cpp
src/autoschedulers/adams2019/FunctionDAG.cpp
src/autoschedulers/adams2019/test.cpp

Fixes #6899
This just forces scheduling of Funcs that wrap LUTs when they're outputs. I don't think it makes sense to expand the search space to include scheduling them other than inline if they're not outputs. This only triggers if the pipeline is a strict memcpy of an embedded buffer.

Fix autoscheduling trivial lut wrappers

---

src/Derivative.cpp
src/FuseGPUThreadLoops.cpp

- variable 'count' set but not used
- warning: use of bitwise '|' with boolean operands

Fix two warnings found with clang 16

---

src/SplitTuples.cpp
test/correctness/CMakeLists.txt
test/correctness/realize_condition_depends_on_tuple.cpp

If the realization is tuple-valued, and the condition on the realization
uses a tuple call (index != 0), then the condition wasn't getting
resolved during the split_tuples pass. The cause was a missing mutate
call.

Fix bug when realize condition depends on tuple call

---

python_bindings/src/halide/CMakeLists.txt

We were looking in a nonexistent dir, so we never copied `__init__.py` as we should have.

Fix wrong install path for *.py files

---

src/Error.cpp
src/Error.h
src/Generator.cpp

Unfortunately, the std error/exception classes aren't marked for DLLEXPORT under MSVC; we need our Error classes to be DLLEXPORT for libHalide (and python bindings). The current situation basically causes MSVC to generator another version of `std::runtime_error` marked for DLLEXPORT, which can lead to ODR violations, which are bad. AFAICT we don't really rely on this inheritance anywhere, so this just eliminates the inheritance entirely.
(Note that I can't point to a specific malfunction resulting from this, but casual googling based on the many warnings MSVC emits about the current situation has me convinced that it needs addressing.)

Halide::Error should not extend std::runtime_error

---

CMakePresets.json

Also, drive-by rename of 'default' to 'base' to better imply the inheritance

Add build & test presets for release and debug CMake builds

---

python_bindings/src/halide/__init__.py
python_bindings/src/halide/_generator_helpers.py
python_bindings/src/halide/halide_/PyGenerator.cpp
python_bindings/stub/PyStubImpl.cpp
python_bindings/test/correctness/pystub.py

This proposes to revise the Python Generator API to have GeneratorContext *never* be an explicit argument; rather, to have an *implicit* current GeneratorContext that is active. This reduces boilerplate when composing code (e.g. via Generator.call). To temporarily push a new GeneratorContext on the active stack, `with hl.set_context(ctx):` is the appropriate thing to do.

Revise PyGen API to have implicit GeneratorContext

---

README_cmake.md
README_python.md
cmake/HalideGeneratorHelpers.cmake
cmake/HalidePythonExtensionHelpers.cmake
python_bindings/test/CMakeLists.txt
python_bindings/test/generators/CMakeLists.txt

Move it into `add_halide_library` instead, as another output option.
(add_python_stub_extension will likely be moved as well, in a subsequent PR)

Remove add_python_aot_extension() rule in CMake

---

python_bindings/CMakeLists.txt
python_bindings/setup.py
src/autoschedulers/li2018/CMakeLists.txt

The `Development` component is the combination of two sub-components:
1. `Development.Module` - the parts necessary to create native Python modules
2. `Development.Embed` - the parts necessary to embed the Python interpreter into your application.
The manylinux images don't include `Development.Embed` and we don't need it anyway. So this fixes the build in that scenario. 
Also disables building tests and tutorials when building wheels because they're not needed.

Build fixes for manylinux2014

---

src/CodeGen_Internal.cpp
src/HexagonOffload.cpp
src/runtime/HalideRuntimeHexagonHost.h
src/runtime/hexagon_host.cpp
src/runtime/runtime_api.cpp

The issue in #6893 is the result of an attempt to dereference a pointer to the module_state pointer. This PR simply adds a runtime method to dereference the pointer, in order to fix that issue. I'm not necessarily sure if this is the best approach, would love feedback from anyone who knows the HVX runtime better than I do.

[HVX] Fix state_var issue

---

python_bindings/setup.py

On GNU `ld`, the directory of the module is spelled `$ORIGIN`, but on Darwin it's spelled `@loader_path`.

Fix RPATH for Python wheels on macOS

---

CMakeLists.txt

* Disables the usage warning when `CMAKE_BUILD_TYPE` is defined, but explicitly empty.
* Overrides C++ standard variables using the cache (CMake 3.21+)
* Allows including projects to build our tests, etc. but disables by default via `PROJECT_IS_TOP_LEVEL` (CMake 3.21+)
* Removes misleading `distrib` target.
* Removes deprecated `clang-format` target (use `./run-clang-format.sh` instead)
This is in preparation for some larger changes (going back to fix past mistakes) that I'm making in light of the upgrade to CMake 3.22 (#6910) and a few years' worth of extra CMake knowledge.

Some minor top-level CMakeLists.txt reorganization

---

packaging/CMakeLists.txt
packaging/common/HalideConfig.cmake

This PR makes a few fixes to our CMake package (as used by `find_package`).
* The package now includes a hint as to the location of `HalideHelpers`, so that errors regarding not being able to find it are rarer (e.g. setting `Halide_DIR` instead of `Halide_ROOT`).
* `Halide_ASAN_ENABLED` is added to the package to allow consumers to confirm that they found the right Halide when they are using ASAN in their own projects.
* The handling of optional components was fixed. Previously, it incorrectly used the `REQUIRED`-ness of the whole Halide package itself, not the individual component.
* PNG and JPEG dependencies are now optional by default. If any are missing, `find_package(Halide REQUIRED)` will still succeed. If you need a specific dependency for `Halide::ImageIO`, you can make it …

CMake packaging fixes

---

dependencies/spirv/CMakeLists.txt
src/CMakeLists.txt

I think I did a bad job communicating the expected implementation in my review of #6882, but this is what I meant. Skipping buildbots because they don't test SPIRV yet. I have tested this locally.
Pinging @derek-gerstmann in case there's something I'm missing about the way it was previously done.

Use CMake target to handle vendored SPIRV headers

---

CMakeLists.txt

`check_cxx_symbol_exists` saves its output in the cache and does not run if its destination variable is defined. This is OK when used to test something that necessitates a totally fresh configuration, like any property of the target architecture, which would require changing the toolchain file. However, the result here can change if someone just modifies `CMAKE_CXX_FLAGS`, so it can get out of sync in some cases.

Don't cache Halide_ASAN_ENABLED

---

src/Bounds.cpp
src/CodeGen_OpenGLCompute_Dev.cpp

This should revert bounds inference on `saturating_cast` to the behavior of pre - #6900 .
@steven-johnson could you test to see if this fixes things?
The issues detected were not a direct result of #6900 - before that PR, there was still `signed_integer_overflow` inside of Bounds.cpp, but it was being hidden by complex `Cast` handling inside the bounds visitor. @abadams and I are discussing a fix to the underlying issue, but it is incredibly involved and requires possibly using infinite-precision integers in some parts of the compiler.

Lower saturating_cast in bounds inference

---

src/CodeGen_ARM.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/CodeGen_Internal.h
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

Also remove ```element_count``` as it was only used in a single pattern which is now in the ```CodeGen_LLVM::get_splat``` routine.
Also allows control of vscale vs. fixed types for vector types based on state in CodeGen_LLVM.

Small refactor to remove confusion between CodeGen_LLVM and CodeGen_Internal.

---

src/autoschedulers/adams2019/CMakeLists.txt

The XCode "new build system" doesn't like generated source files to be associated with more than one target. Going through an OBJECT library like this fixes that problem, but also saves us a compilation, so it's a good thing to do anyway.
Fixes #6976

Fix XCode by wrapping weights in an OBJECT library

---

python_bindings/test/correctness/multi_method_module_test.py
src/PythonExtensionGen.cpp

Currently, Python Extensions don't make any effort to override `halide_error`, so the default (which aborts) is generally used... this is very unfriendly. This modifies the standard Python Extension glue code to hook halide_error, saving the text in a thread local, and then throwing a Python exception after the extension's AOT call is finished (if an error occurred, of course).
Also does a drive-by default hooking of `halide_print` to ensure that it goes to whatever Python thinks that `stdout` is.
(Note that it would be really nice if we could use closures of some sort for halide_error, halide_print, etc so that we could save context in the actual Python module, rather than in a thread-local global var, but this currently isn't possible without nontrivial refactoring in the Halide …

Improve error-handling in Python Extensions

---

cmake/HalideGeneratorHelpers.cmake
cmake/TargetExportScript.cmake

1. `TargetExportScript` was running into an Xcode bug with its handling of linker flags. Now using `XCODE_ATTRIBUTE_EXPORTED_SYMBOLS_LIST` as a workaround.
2. Added a missing dependency in Python module definition code.
Fixes #6987

Fixes for Xcode "new" build system.

---

src/Elf.cpp

Some versions of GCC will complain that there is a possible use of uninitialized field `Sym<>::st_info` here; that's technically true, in that it is a bitfield that we previously set via two calls, so it temporarily could use uninitialized bits, but those would immediately be overwritten by well-defined bits. That said, the API could have been misused, so I collapsed Sym::set_type and Sym::set_bindings into a single call to avoid this warning.
While I was there, I did a little hygiene on Rel<> and Rela<> as well, as there was an unused-but-similarly-dubious API there. ~~Also added some C++17 `if constexpr` love.~~

Fix compiler warnings in Elf.cpp

---

src/CodeGen_LLVM.cpp

https://github.com/llvm/llvm-project/commit/93600eb50ceeec83c488ded24fa0fd25f997fec6
renamed ModuleAddressSanitizerPass to AddressSanitizerPass.
https://github.com/llvm/llvm-project/commit/4c18670776cd6ac31099a455b2b22b38b0408006
renamed ModuleSanitizerCoveragePass.

[Codegen] Adapt ModuleAddressSanitizerPass/ModuleSanitizerCoveragePass renaming

---

packaging/CMakeLists.txt
src/autoschedulers/adams2019/CMakeLists.txt
src/autoschedulers/adams2019/DefaultCostModel.cpp
src/autoschedulers/adams2019/Makefile

This does a few things:
- The main thing it does is add a unique prefix to all the targets in Adams2019; apparently CMake has a global namespace for targets, and when they collide (as happened in #6856) you get amusing results.
- Added `add_adams2019_test` helper to clean up boilerplate. Note that setting HL_TARGET was never necessary for any of these tests.

Clean up Adams2019 CMake file

---

Makefile
src/runtime/CMakeLists.txt

AFAICT we aren't doing this in Halide at present, but some experimental code in Google runtime was doing so; this caused some issues with some experimental Clang patches, but also was never really intended to be used in the first place. Adding the flag here to be sure no unintended use creeps back in.
While I was there, took the time to ensure that the flags for runtime are unified across CMake and Make.

Prohibit C99 VLA usage in runtime code

---

src/CodeGen_RISCV.cpp

The vector extension is no longer experimental and the logic for picking the vector size and vscale was not hooked up.

Couple small fixes to update RISC V to current LLVM flags and enable vscale use.

---

python_bindings/test/correctness/bit_test.py
python_bindings/test/generators/bit_generator.cpp
src/PythonExtensionGen.cpp

The Python Extension code didn't handle boolean buffers correctly, making it impossible to construct one in Python and pass it thru to Halide-generated code. This fixes that, and also fixes the test that just expected it to fail (!).

Fix Python handling of boolean buffers

---

src/CodeGen_Internal.cpp
src/FastIntegerDivide.cpp
test/correctness/CMakeLists.txt
test/correctness/div_round_to_zero.cpp

... and fast_integer_divide_round_to_zero
These were never adequately tested, and there were a few issues.

Fix some bugs in div_round_to_zero

---

README_python.md
python_bindings/src/halide/_generator_helpers.py
python_bindings/test/generators/bitpy_generator.py
python_bindings/test/generators/complexpy_generator.py
python_bindings/test/generators/simplepy_generator.py

Per suggestion on https://github.com/halide/Halide/pull/6764, this allows these type aliases. How does it look / feel?
(Adding similar aliasing for, at least, NumPy types is probably desirable as well)

Allow use of bool|int|float for Generator type args

---

src/HexagonOptimize.cpp
test/correctness/simd_op_check_hvx.cpp

The handling of `widening_shift_left` in HexagonOptimize's `DistributeShiftsAsMuls` was not properly producing `widening_mul`s. This PR fixes that. Here's a small illustrative example:
```
ImageParam in_i8(Int(8), 1);
Func kernel("kernel");
Var x("x");
kernel(x) = i16(in_i8(x - 1)) + 2 * i16(in_i8(x)) + i16(in_i8(x + 1));
kernel.vectorize(x, 128);
```
Compiled with target="hexagon-64-noos-no_bounds_query-no_asserts-hvx_128-hvx_v66".
Before `DistributeShiftsAsMuls`:
```
kernel[ramp(kernel.s0.x.x*128, 1, 128) aligned(128, 0)] = ((int16x128)widening_shift_left(p0[ramp(t6, 1, 128)], x128((uint8)1)) + int16x128(p0[ramp(t6 + -1, 1, 128)])) + int16x128(p0[ramp(t6 + 1, 1, 128)])
```
Previously, after `DistributeShiftsAsMuls`:
```
kernel[ramp(kernel.s0.x.x*128, 1, 128) aligned(128, 0)] = …
```

[HVX] Simplify constant factor before distributing

---

cmake/HalideGeneratorHelpers.cmake
python_bindings/test/generators/user_context_generator.cpp
src/CodeGen_C.cpp
src/Module.cpp
src/PythonExtensionGen.cpp

My previous effort was too clever for itself: while it worked for Halide's build systems, some other build systems (e.g. Blaze) are much more finicky about the C++ files you build Python extensions from, and re-using the same C++ files with different preprocessor settings turns out to be too problematic there, for reasons that aren't important here.
Anyway, the important part here was to rework so that (1) All the C++ source files needed are compiled exactly once (2) All the C++ source files needed can be compiled with the same set of preprocessor definitions
To that end, I have extended GenGen's `-r` flag to allow using `-e python_extension`; this emits the bare module-registration code by itself. So now, we generate the Python Extension code as before, but define …

Rework Python Extension C++ code (again)

---

.github/workflows/presubmit.yml

This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflow using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/halide/Halide/actions/runs/3024567888/jobs/4866106064#step:1:19
After this change, the scopes will be reduced to the minimum needed for the workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_ …

Add minimum GitHub token permissions for workflow

---

src/HexagonOptimize.cpp
test/correctness/simd_op_check_hvx.cpp

Reverts halide/Halide#7009
Injected compilation failure that turns up in some Google-specific code; @vksnk and I will work to get a repro case, but for now we must revert this

Revert "[HVX] Simplify constant factor before distributing"

---

src/IRMatch.h

`SpecificExpr` should have the same min/max node types as a `Wild`, it's missing VectorReduce in the current range.

Fix SpecificExpr canonicalization

---

python_bindings/src/halide/_generator_helpers.py

Apparently it's "more Pythonic" to use "not in" vs "not ... in", etc.

Appease Python linter

---

dependencies/wasm/CMakeLists.txt
src/Error.cpp

Combining `-g` with other default EMCC flags will now emit warning/error messages regarding binaryen optimization, so, don't use that flag in the default settings.

Don't use `-g` for EMCC

---

src/Simplify_Reinterpret.cpp

Folds double-reinterprets (which can be produced in FindIntrinsics sometimes) and converts (u)int to (u)int reinterprets to casts.

Add reinterpret simplifications

---

Makefile
src/CodeGen_C.cpp
test/generator/CMakeLists.txt
test/generator/async_parallel_aottest.cpp
test/generator/async_parallel_generator.cpp

While adding a user_context to the `async_parallel` generator for other purposes, I found some subtle bugs in Codegen_C regarding possible aliasing and/or const-correctness of the internal 'ucon' arguments when calling or unpacking a closure for async usage. This fixes it.

Codegen_C for user_context

---

apps/CMakeLists.txt
apps/HelloWasm/Makefile
apps/HelloWasm/reaction_diffusion_generator.cpp
src/CodeGen_WebAssembly.cpp

- Emscripten can quietly add the 'atomics' and 'bulk-memory' features if you compile with `-pthreads` enabled; we already included `atomics` but `bulk-memory` was separate. For convenience, we should assume that enabling threads for wasm enables both of the other two.
- Also silence some "unscheduled" warnings about update stages in HelloWasm

Fix Wasm BulkMemory Codgen + Minor fixes to apps/HelloWasm

---

Makefile
apps/fft/CMakeLists.txt

This was apparently meant as a canary for stack size usage, but the necessary setting only happened in the Makefile, not the CMake file.
Also, drive-by fix in Makefile to ignore warnings about `-ObjC++` being ignored, which apparently can be the case with current AppleClang configs.

Add stack-size-canary test to apps/fft's CMake file

---

src/Bounds.cpp

It seems widen_right_add can appear in load indices and this was causing difficulties [here](https://github.com/halide/Halide/blob/main/src/HexagonOptimize.cpp#L2010), i.e. load+shuffle wasn't generated somewhere where it was happening before.

Handle widen_right_* intrinsics in bounds inference

---

apps/fft/CMakeLists.txt
apps/fft/Makefile

Reverts halide/Halide#7035 -- should be fixed in LLVM commit e664dea1821ab1277e62f0b4074fb02867636e6e

Revert "Temporarily disable testing for apps/fft (#7033)"

---

python_bindings/test/correctness/multi_method_module_test.py
src/PythonExtensionGen.cpp

The current PythonExtensionGen code attempts to provide verbose error (exception) messages by overriding halide_error and saving the message in a thread_local. This isn't safe or correct, however, and (in general) is wrong for any Halide code using multiple threads. #6994 proposes ways to mitigate this (and there are experiments in place to implement it), but unless/until those enhancements land, we can't leave the code in its current state. So:
- Don't try to save the text at all.
- Optionally log the text to stderr.
- Just throw an exception with the numeric error code. This is suboptimal, but better than the existing usually-incorrect-message behavior.
- Bonus: wrap both the error and print overloads with `PyGILState_Ensure()`, as we are supposed to, to ensure we don't die.

Fix PyExt error handling

---

python_bindings/src/halide/_generator_helpers.py
python_bindings/src/halide/halide_/PyHalide.cpp
python_bindings/src/halide/halide_/PyHalide.h
python_bindings/src/halide/halide_/PyIROperator.cpp
python_bindings/src/halide/halide_/PyPipeline.cpp
python_bindings/test/correctness/addconstant_test.py
python_bindings/test/correctness/basics.py
python_bindings/test/generators/addconstantcpp_generator.cpp
python_bindings/test/generators/addconstantpy_generator.py
src/Generator.cpp
src/Generator.h
src/IROperator.h
src/Pipeline.cpp
src/Pipeline.h

This PR started out as a quick fix to add Python bindings for the `add_requirements` methods on Pipeline and Generator (which were missing), but expanded a bit to fix other issues as well:
- The implementation of `Generator::add_requirement` was subtly wrong, in that it only worked if you called the method after everything else in your `generate()` method. Now we accumulate requirements and insert them at the end, so you can call the method anywhere.
- We had C++ methods that took both an explicit `vector<Expr>` and also a variadic-template version, but the former required a mutable vector... and fixing this to not require that ended up creating ambiguity about which overloaded call to use. Added an ugly enable_if thing to resolve this.
While working on this, also identified Issue #7044, …

add_requirement() maintenance

---

test/runtime/common.h

Latest clang is giving a use after free warning for printing a pointer value after it is freed. The compiler is not exactly wrong in that a pointer is being passed to something after it is freed, but the something is just printing the pointer's value for debugging purposes. Cast through an intptr_t to avoid the warning.

Fix false positive use after free warning.

---

src/CodeGen_LLVM.cpp

Specific use case is calling vector predicated store. Factored out of [the vector predication branch](https://github.com/halide/Halide/tree/llvm_vector_predication_intrinsics) for ease of code review and such.

Allow call_intrin to call an LLVM intrinsic with void return type.

---

python_bindings/src/halide/_generator_helpers.py

They are really only ever defined at the class level, so if you mutate the value, you are mutating the default value for all future instances. Subtle bug.

Don't mutate GeneratorParams in PythonGenerators

---

python_bindings/test/correctness/addconstant_test.py
python_bindings/test/generators/addconstantcpp_generator.cpp
python_bindings/test/generators/addconstantpy_generator.py
src/PythonExtensionGen.cpp

This PR allows you to pass `numpy.float16` buffer to Halide function.

Add support for float16 buffer in python extension

---

src/LLVM_Runtime_Linker.cpp
src/Target.cpp

Running JIT code under MSAN is (still) not officially supported, as it can (and does) give false positives; that said, this PR reduces the false positives in some cases.
Specifically:
(1) if we are building a JIT shared runtime (ie, we are jitting), and we are compiling with MSAN enabled (detected via preprocessor), we should always use the real MSAN stubs, even if the Target::MSan feature has been cleared (because JITModule::make_module() clears it). 
(2) Target::get_jit_from_environment() should add any detected sanitizer bits to the target sniffed from HL_JIT_TARGET

Improve MSAN under JIT

---

src/HexagonOptimize.cpp

Fixes the issues noted in #7079. Opening to see if the LLVM register allocation failure still happens for @steven-johnson on #7015

[HVX] Fix DistributeShiftsAsMuls

---

src/CodeGen_Metal_Dev.cpp

Basically, it will generate dot() call for vector_reduce(Add, mul(float, float)). I've tested it locally to make sure it is actually generated. It'd be nice to have something similar to simd_op_check for GPU targets, but  it doesn't exist (#7084).

Generate dot() in the Metal backend

---

python_bindings/src/halide/halide_/PyFunc.cpp
src/Func.h
src/Generator.h
src/Realization.h

These APIs were announced as being removed in Halide 16, so let's remove them.

Remove everything flagged with HALIDE_ATTRIBUTE_DEPRECATED

---

.github/workflows/pip.yml

Reverts halide/Halide#7097 -- manylinux containers for arm64 haven't added 15.0.2 yet (still on 15.0.1)

Revert "Update pip.yml to use LLVM 15.0.2"

---

CMakeLists.txt

- The `WITH_UTIL` option was relied upon inside the autoscheduler subdir, but wasn't defined until after that subdir was processed. This had the unfortunate effect of making the undefined option (effectively) always false the first time it was encountered, but appropriately true | false on subsequent runs; the upshot was that if you did a `make install` as the *FIRST* build from a build-from-scratch, you would (quietly) get an install that omitted the adams2019 tools from the installer. (This seems like a crazy misfeature on CMake's part, but I'm sure it's unfixable now...)

Fix subtle CMake Install bugs

---

README_cmake.md
README_python.md
apps/bgu/bgu_generator.cpp
python_bindings/test/correctness/extern.py
tutorial/lesson_11_cross_compilation.cpp

Fixes #7106 
I have separately pushed fixes for the dead links on the website.

Fix some dead links to the 'master' branch

---

python_bindings/src/halide/halide_/PyBuffer.cpp
python_bindings/test/correctness/buffer.py

using `()` to get or set a Buffer element wasn't being checked at runtime for Python, but it clearly should be, because Python. (Note that in C++ we don't always range-check for these operations -- it's limited to `assert()` checks -- but in Python the expectations are clearly different.)

Add range-checking to Buffer objects in Python

---

python_bindings/src/halide/halide_/PyBuffer.cpp
python_bindings/src/halide/halide_/PyBuffer.h
python_bindings/src/halide/halide_/PyCallable.cpp
python_bindings/test/correctness/buffer.py

This adds some options to the changes in #7127 to allow for easier backwards compatibility with previous versions of the Python bindings:
- The default when creating `hl.Buffer` from a Python buffer is to reverse the axes. There is now an optional named arg to that ctor that you can specify `reverse_axes = False` if you want the behavior of pre-Halide-15 (ie, don't reverse).
- The default when creating `np.array`, `np.ndarray` etc from an `hl.Buffer` is to reverse the axes. There is now a new method on `hl.Buffer`, `reverse_axes()`, which simply returns another Buffer that is a view onto the same memory, but with the order of the axes reverse. This allows you to keep the behavior of pre-Halide-15 (ie, don't reverse) by doing something like `np.array(halidebug.reverse_axes(), ...)`.

add 'reverse_axes' options to Buffer conversions

---

python_bindings/src/halide/CMakeLists.txt
python_bindings/src/halide/halide_/PyBuffer.cpp
python_bindings/src/halide/halide_/PyBuffer.h
python_bindings/src/halide/halide_/PyCallable.cpp
python_bindings/src/halide/imageio.py
python_bindings/test/apps/bilateral_grid_shell.py
python_bindings/test/apps/blur.py
python_bindings/test/apps/erode.py
python_bindings/test/apps/interpolate.py
python_bindings/test/apps/local_laplacian.py
python_bindings/test/correctness/buffer.py
python_bindings/tutorial/lesson_02_input_image.py
python_bindings/tutorial/lesson_07_multi_stage_pipelines.py
python_bindings/tutorial/lesson_09_update_definitions.py
python_bindings/tutorial/lesson_12_using_the_gpu.py

In the category of "how did this ever work"...
TL;DR: in general, Halide Buffers have the opposite axis ordering from Python/NumPy buffers; in Halide, the most-frequently-varying dimension comes first, while in Python, it comes last. This isn't surprising, though, since Halide's indexing scheme is effectively column-major while NumPy's is row-major.
Anyway: what we *should* have done was to reverse the order of dimensions when converting to/from Halide Buffers vs Python buffers; instead, we kept the same order, then jumped thru hoops to rearrange buffers to fit this setup. This PR does the appropriate axis reordering, fixing the apps and tests as needed.
It also adds some helper code for image reading and writing; by default, we use `imageio` for this, but imageio ~always wants RGB/RGBA …

Fix Python buffer handling

---

src/CodeGen_WebAssembly.cpp

Noticed that the `q15mulr_sat_s` rule didn't use the corresponding intrinsic - meaning we'd lower `rounding_mul_shift_right` just to match the rule before.

[WASM] Use rounding_mul_shift_right for q15mulr_sat_s pattern

---

.github/workflows/pip.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

python_bindings/test/correctness/addconstant_test.py
python_bindings/test/correctness/atomics.py
python_bindings/test/correctness/autodiff.py
python_bindings/test/correctness/basics.py
python_bindings/test/correctness/bit_test.py
python_bindings/test/correctness/boundary_conditions.py
python_bindings/test/correctness/buffer.py
python_bindings/test/correctness/callable.py
python_bindings/test/correctness/compile_to.py
python_bindings/test/correctness/division.py
python_bindings/test/correctness/extern.py
python_bindings/test/correctness/iroperator.py
python_bindings/test/correctness/multi_method_module_test.py
python_bindings/test/correctness/multipass_constraints.py
python_bindings/test/correctness/negate_test.py
python_bindings/test/correctness/pystub.py
python_bindings/test/correctness/rdom.py
python_bindings/test/correctness/realize_warnings.py
python_bindings/test/correctness/target.py
python_bindings/test/correctness/tuple_select.py
python_bindings/test/correctness/type.py
python_bindings/test/correctness/user_context_test.py
python_bindings/test/correctness/var.py
python_bindings/test/generators/addconstantpy_generator.py
python_bindings/test/generators/bitpy_generator.py
python_bindings/test/generators/complexpy_generator.py
python_bindings/test/generators/simplepy_generator.py

Trying to regularize all our Python code to a common style. Should be no functional changes here, just autoformatting + a few tweaks.

Apply 'Black' formatter to py/test/correctness and py/test/generators

---

python_bindings/src/halide/imageio.py

As written, the helper code assumed that everything passed in was a numpy array of some sort; this meant that passing hl.Buffer didn't work. Restructured so that we only assume that the objects passed in satisfies the Python buffer protocol, so this should now work very generically.

halide.imageio needs to support arbitrary bufferviews

---

.github/workflows/pip.yml

Looks like https://github.com/halide/Halide/pull/7136 was too restrictive, breaking wheel building

Give pip.yml permission to read packages

---

apps/hannk/delegate/hannk_delegate.cpp

TF_LITE_KERNEL_LOG was intended for TFLite Micro but usage leaked out into example code; we should use ReportError instead.

Don't use TF_LITE_KERNEL_LOG in apps/hannk

---

Makefile
src/CodeGen_ARM.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_PTX_Dev.cpp
src/CodeGen_PowerPC.cpp
src/CodeGen_RISCV.cpp
src/CodeGen_WebAssembly.cpp
src/CodeGen_X86.cpp

The readnone flag was changed to memory(none) when applied to functions. llvm-as dynamically upgrades readnone applied to functions, so our .ll is fine for now, but there were places in the compiler we were manually sticking 'readnone' on a function.
Also did a driveby makefile fix to remove some vestigial wasm stuff that was throwing errors with newer versions of llvm-config

Fix readnone attribute for llvm 16

---

src/CodeGen_C.cpp

Just assume that this is present and call it for stringify() on buffers in the C backend. (If it's missing, the user will be expected to provide an implementation, as is usual for runtime with the C backend.)

C Backend should call halide_buffer_to_string()

---

src/CodeGen_C.cpp

We didn't call cache.clear() between internal functions in the C backend, so the cache could try to re-use something declared in a previous (internal, closure) function and would fail to compile. Easy fix. (I'm surprised we haven't seen this fail before now.)

Call cache.clear between internal functions in CG_C

---

src/Expr.cpp
src/RDom.cpp
src/RDom.h

Fixes #6948 
Before: 
Extent cannot be losslessly cast to an int32: 3.400000f
After: 
RDom extent cannot be represented as an int32: 3.400000f

Slightly improve error message for non-integer RDom min/extent

---

Makefile
dependencies/llvm/CMakeLists.txt
src/JITModule.cpp
src/LLVM_Headers.h
test/correctness/c_function.cpp

resolves https://github.com/halide/Halide/issues/7161
resolves https://github.com/halide/Halide/issues/7078
* Migrate from MCJIT to ORC JIT
* Enables JIT on RISC-V (related: https://github.com/llvm/llvm-project/issues/58979)
* i386 is also on ORC JIT but fallbacks to RTDyld. Other targets uses JITLink. (track https://github.com/llvm/llvm-project/issues/58978)

Migrate from MCJIT to ORC JIT

---

src/LLVM_Headers.h
src/LLVM_Runtime_Linker.cpp

related: https://github.com/llvm/llvm-project/commit/974e2e690b4024c2677dde26cc76ec31e0047c1d
resolves https://github.com/halide/Halide/issues/7174

Use n32:64 in RISC-V data layout

---

python_bindings/apps/bilateral_grid_app.py
python_bindings/apps/blur_app.py
python_bindings/apps/blur_generator.py
python_bindings/apps/interpolate_app.py
python_bindings/apps/local_laplacian_app.py
python_bindings/test/correctness/addconstant_test.py
python_bindings/test/correctness/bit_test.py
python_bindings/test/correctness/iroperator.py
python_bindings/test/correctness/multi_method_module_test.py
python_bindings/test/correctness/realize_warnings.py
python_bindings/test/correctness/user_context_test.py
src/Generator.cpp

This change makes it a bit easier for me to transform the import paths when merging into Google: we can't set PYTHONPATH, and calling `sys.path.append()` is frowned upon. This should have no effect on the GitHub repo but will make my life easier downstream.

Tweak the import paths in Python apps & tests

---

Makefile
src/Module.cpp
src/Module.h
test/generator/CMakeLists.txt

We had a mechanism in place to ensure that Outputs that got renamed during lowering still emitted the proper names in the metadata... but this didn't work reliably for Multitarget generation. Now it does.

Fix metadata generation for multitarget Generators

---

src/Generator.cpp
src/Generator.h

This is a simple thing that just logs the path to all generated file(s) to stdout if `-v=1` is specified. It's intended for people running Generators directly from the commandline, and is intended as a more user-friendly alternative to HL_DEBUG_CODEGEN=1. No makefiles, etc specify it at present, but I anticipate using it in some tooling in the future.
Example usage:
```
$ resize_image_bilinear.generator_binary -v 1 -o /tmp -g resize_image_bilinear -n resize_image_bilinear_uint16 -f resize_image_bilinear_uint16 -e assembly,c_header,llvm_assembly,registration,static_library,stmt 'target=arm-64-android' 'input.type=uint16' 'output.type=uint16'
Generated file: /tmp/resize_image_bilinear_uint16.s
Generated file: /tmp/resize_image_bilinear_uint16.h
Generated file: …
```

Add a -v flag to generator_main()

---

src/Util.cpp

Despite being 'posixy', it doesn't actually implement these calls.

Don't attempt to use makecontext()/swapcontext() on Android

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

This is only used in the vector predication intrinsic codegen. This fixes an error denerating vector predicated strided stores.

Extend LLVM IR type mangling to handle scalars.

---

src/LLVM_Runtime_Linker.cpp
test/correctness/simd_op_check_powerpc.cpp
test/correctness/simd_op_check_x86.cpp

(See #7208)
- DataLayout was wrong (and has been for a long time)
- simd_op_check_powerpc had errors. Some were easy to fix; the rest I commented out with a TODO since this backend doesn't appear to be in active use.
(Want to fix this in preparation for fixing #7207)
(Note to reviewers: this isn't being run on the buildbots, so there shouldn't be any failures -- if you want to test right now, run locally and set HL_TARGET appropriately)

Fix bitrot in PowerPC testing

---

src/WasmExecutor.cpp

Obsolete code from early V8 work, it can trigger inappropriately in some corner-case scenarios. Remove it entirely to avoid false errors.

Remove check_jit_user_context() from V8 bindings

---

Makefile
apps/hannk/interpreter/interpreter.cpp
src/LLVM_Runtime_Linker.cpp
src/runtime/CMakeLists.txt
src/runtime/HalideBuffer.h
src/runtime/HalideRuntime.h
src/runtime/alignment_128.cpp
src/runtime/alignment_32.cpp
src/runtime/alignment_64.cpp
src/runtime/cache.cpp
src/runtime/posix_aligned_alloc.cpp
src/runtime/posix_allocator.cpp
src/runtime/qurt_allocator.cpp
src/runtime/runtime_internal.h

This makes a couple of changes to the behavior/implementation of `halide_malloc()`:
* Currently, halide_malloc must return a pointer aligned to the maximum meaningful alignment for the platform for the purpose of vector loads and stores. This PR also adds the requirement that the memory returned must be legal to access in an integral multple of alignment >= the requested size (in other words: you should be able to do vector load/stores "off the end" without causing any faults).
* Currently, the `halide_malloc_alignment()` function is used to determine the default alignment; this cannot be overridden by user code (well, it can be, but the override will have no useful effect). It is intended to be "internal only" but is used in at least one place outside the runtime (apps/hannk). This …

Tighten alignment promises for halide_malloc()

---

test/correctness/simd_op_check_arm.cpp

Interestingly, it compiles here, but in some compilers it will fail with "unexpected token".

Remove rogue string suffix in simd_op_check_arm.cpp

---

src/ModulusRemainder.cpp
src/Monotonic.cpp
src/Simplify_Add.cpp
src/Simplify_Internal.h
src/Simplify_Sub.cpp
src/Util.cpp
src/Util.h
test/correctness/intrinsics.cpp

Also, use compiler intrinsics when possible to handle overflow, as it generates faster code.
Fixes #7229

Fix some sources of signed integer overflow in the compiler

---

src/CodeGen_Xtensa.cpp
src/InjectDmaTransfer.cpp

This includes multiple related changes:
* all transactions are 2D.
* Each buffer will use a separate DMA channel.
* For the case when destination is an output buffer, we can delay the wait for completion until the beginning of it's producer.

[xtensa] DMA support improvements.

---

python_bindings/src/halide/halide_/PyEnums.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h

Was deprecated in Halide 15; let's remove in Halide 16
Also: drive-by fix to avoid "may be used uninitialized in this function" warning/error

Remove deprecated halide_target_feature_disable_llvm_loop_opt

---

src/CodeGen_C.cpp

Allocations can be conditional; if the condition evaluates to false, we end up calling `halide_malloc(0)` (or `halide_tcm_malloc(0)` in the xtensa branch). Since it's legal via spec for `malloc(0)` to return nullptr, we need to be cautious here: if we are compiling with assertions enabled, *and* have a malloc() (etc) implementation that returns nullptr for alloc(0), we need to skip the assertion check, since we know the result won't be used.
Note: a similar check will be inserted in the xtensa branch separately.
Note 2: LLVM backend already has this check via Codegen_Posix.cpp

Conditional allocations shouldn't fail for size=0 in C++ backend (#7255)

---

src/CodeGen_Xtensa.cpp

Fix was made in Codegen_C.cpp a while back; the cache must be clear and end-of-func to avoid trying to share assignments between do-par-for lambdas.

Add missing `cache.clear()` call at end of functions

---

python_bindings/test/correctness/realize_warnings.py
src/BoundsInference.cpp
test/correctness/code_explosion.cpp
test/generator/nested_externs_aottest.cpp
test/generator/nested_externs_generator.cpp

Inline into extern function args during bounds inference

---

src/CodeGen_Xtensa.cpp

Passing __user_context doesn't always get the constness right; _ucon does and is terser

Pass _ucon to halide_error for DMA check

---

src/Module.cpp

Avoid redundant `compile_to_buffer()` calls for output requests that can't possibly ever need them.

Optimize Module::compile() for some edge cases

---

Makefile
src/CodeGen_C.cpp
test/generator/CMakeLists.txt

When the CMake rules were rewritten a while back, the support for building/testing generators with the C++ backend (instead of the standard LLVM, etc) got lost. This adds it back in.
Also made some drive-by fixes to the Makefile to enable some tests there that work correctly now.
Also made a drive-by fix in in Codegen_C to fix allocation nodes that were just wrappers around buffer_get_host -- this prevented the cleanup_on_error test from building with the C++ backend.

Add CMake support for C++ backend in test/generator

---

Makefile
src/CodeGen_C.cpp
test/generator/CMakeLists.txt

We gathered up the destructors, but only emitted the prototypes if there was at least one non-C++ function declaration needed -- so if you built with cpp_name_mangling enabled, you might omit the right prototype. Fixed and added the right flag to a Generator test to tickle this behavior.

Emit prototypes for destructor functions in C Backend

---

cmake/HalideGeneratorHelpers.cmake

In case the project name is CamelCase, add_halide_generator() was not able to find the generator package, because CMake searches <name>Config.cmake or <lower-case-name>-config.cmake

Fix error of add_halide_generator in cross-compilation

---

cmake/HalideGeneratorHelpers.cmake

add_halide_runtime() tries to build generator executable, but it fails if we are working with cross-compiler toolchain. By using existing generator set as "FROM", we can work around this.

Fix issue in add_halide_runtime in cross-compilation

---

src/CodeGen_C.cpp

This is a slightly more efficient version of a popcount, which has as many iterations as many ones are in the binary representation.

Improved halide_popcount

---

Makefile
dependencies/llvm/CMakeLists.txt

(Opening as draft initially until Buildbots build the new LLVM versions)

Minimal updates to allow Halide building with LLVM17

---

src/CodeGen_C.cpp

Would not compile for Win32 or any other compiler without __builtin_popcountll available. (How did this get checked in without being tested on MSVC?)

halide_popcount<uint64_t> is broken

---

src/Callable.h

Addresses #7314.
I'm wondering, is the argv-based calling convention is documented somewhere? If so, I can add a reference to the doc string.

Make Callable::call_argv_fast public

---

src/autoschedulers/adams2019/FunctionDAG.cpp

Fix segmentation fault in Adams2019 in case the estimate or bound of Func is set to nonconstant Expr.

Fix segfault by nonconstant bound in Adams2019

---

src/runtime/CMakeLists.txt

Hi! I tried cross-compile Halide with LLVM for RISC-V host and found that imported targets `llvm-as` and `clang` ignore `CMAKE_CROSSCOMPILING_EMULATOR`. So need to use it manually in the command.
Please let me know if you're interested in the complete cross-compilation guide.

Fix Halide cross-compilation

---

Makefile
src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
test/warning/CMakeLists.txt
test/warning/emulated_float16.cpp

Improvement for the issue #7306

Warn emulated float16 equivalent is generated

---

packaging/CMakeLists.txt

find_package(HalideHelpers) allows us to use add_halide_library(). But auto scheduler libs are not available unless they are in Halide-Interfaces.cmake.
Note:
Those libraries are not actually linked to the target application, but need to be available for add_custom_command call.

Make auto scheduler libs available in HalideHelpers package

---

src/LLVM_Headers.h
src/LLVM_Output.cpp

Note that there will likely be subsequent changes/fixes to LLVM_Output.cpp; this is a quick fix to get buildbots unbroken.

Fixes for top-of-tree LLVM

---

src/Float16.cpp

IRMutator.h is not needed for the Float16.h.

Float16: Remove unused header dependency

---

python_bindings/src/halide/halide_/PyEnums.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h

This has been marked 'deprecated' for quite a while, and has no affect on codegen or, well, anything else. Let's remove it.

Remove deprecated `HVX_shared_object` feature

---

Makefile
dependencies/llvm/CMakeLists.txt

workaround for https://reviews.llvm.org/D142279

Explicitly remove -D_GLIBCXX_ASSERTIONS from LLVM definitions 

---

src/runtime/HalideBuffer.h

When we flattened dimensions in for_each_value_prep(), we would copy from one past the end, meaning the last element contained uninitialized garbage. (This wasn't noticed as an out-of-bounds read because we overallocated in structure in for_each_value_impl()). This garbage stride was later used to advance ptrs in for_each_value_helper()... but only on the final iteration, so even if the ptr was wrong, it didn't matter, as the ptr was never used again. Under certain MSAN configurations, though, the read would be (correctly) flagged as uninitialized.
This fixes the MSAN bug, and also (slightly) improves the efficiency by returning the post-flattened number of dimensions, potentially reducing the number of iterations f for_each_value_helper() needed.

Fix a subtle uninitialized-memory-read in Buffer::for_each_value()

---

README_cmake.md
apps/HelloBaremetal/cmake-external_project/CMakeLists.txt
apps/HelloBaremetal/cmake-super_build/app/CMakeLists.txt
apps/HelloBaremetal/cmake-twice/CMakeLists.txt
apps/HelloBaremetal/cmake/toolchain.noos-arm32-sample.cmake
cmake/HalideGeneratorHelpers.cmake
packaging/common/HalideHelpersConfig.cmake

When using toolchain where Threads libs are not available, which is the case in baremetal target cross-compilation, we were not able to load even HalideHelpers pacakge.

Fix issue in find_package in cross-compilation for no OS

---

src/CodeGen_Xtensa.cpp
src/CodeGen_Xtensa.h

This removes a nice chunk of redundant code (and adds some corner cases that were missing from the Xtensa version).

Remove Xtensa::compile(LoweredFunc), add Xtensa::preprocess_function_body()

---

src/CodeGen_C.cpp

(1) Emit `true` or `false` instead of `(bool)(0ull)` etc for bool literals (2) Avoid redundant temporaries in print_cast_expr(), which occur in a small but nonzero number of cases
Basically this means that code currently like
```
bool _523 = (bool)(0ull);
bool _524 = (bool)(_523);
...
foo(_524);
```
becomes
```
foo(false);
```
...I'm sure this has no output on final object code, but it makes the generated C code less weird to read.
EDIT: (2), do something similar when emitting nullptr constants.
(3), it's 2023, we no longer need to roll our own `isnan()` and `isinf()`

Tiny improvements in codegen in C backend

---

src/CodeGen_C.h

With the addition of `preprocess_function_body()`, neither of these need to be virtual, and devirtualizing them avoid `hidden overloaded virtual function` warnings in subclasses that don't override them.
(I'll follow this up with a PR to make appropriate changes in Codegen_Xtensa)

Devirtualize the protected compile() methods in Codegen_C

---

src/AddImageChecks.cpp
test/error/CMakeLists.txt
test/error/tuple_output_bounds_check.cpp

Tuple outputs weren't getting appropriate bounds checks due to overzealous culling of uninteresting code in the add_image_checks pass.
Fixes #7343

Fix tuple output bounds checks

---

python_bindings/src/halide/halide_/PyBuffer.cpp
python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyHalide.cpp
python_bindings/src/halide/halide_/PyHalide.h
python_bindings/src/halide/halide_/PyPipeline.cpp

In PyBind11, if you specify a default argument for a method, it is evaluated when the Python module is initialized, *not* when the method is called (as you might expect in C++). For defaults that are just constants/literals, this is no big deal, but when calling get_*_target_from_environment, this means it is called at module init time -- also normally not a big deal (since the values ~never change at runtime anyway), with one big exception (no pun intended): if the function throws an exception (e.g. via calling user_assert() or similar), that exception is thrown at Module-initialization time, which is a much more inscrutable crash, and one that is very hard to recover from.
This may seem unlikely, but can happen pretty easily if you set (say) HL_JIT_TARGET=host-cuda (or other gpu) and …

Change early-bound default args in Python bindings to late-bound

---

src/XtensaOptimize.cpp
test/correctness/simd_op_check_xtensa.cpp

Fix for the issue mentioned in https://github.com/halide/Halide/pull/7294

[xtensa] Generate PACKVRNR for i16(i32(i48x) >> wild_i32)

---

python_bindings/src/halide/halide_/PyBuffer.cpp
python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyHalide.cpp
python_bindings/src/halide/halide_/PyHalide.h
python_bindings/src/halide/halide_/PyPipeline.cpp

In PyBind11, if you specify a default argument for a method, it is evaluated when the Python module is initialized, *not* when the method is called (as you might expect in C++). For defaults that are just constants/literals, this is no big deal, but when calling get_*_target_from_environment, this means it is called at module init time -- also normally not a big deal (since the values ~never change at runtime anyway), with one big exception (no pun intended): if the function throws an exception (e.g. via calling user_assert() or similar), that exception is thrown at Module-initialization time, which is a much more inscrutable crash, and one that is very hard to recover from.
This may seem unlikely, but can happen pretty easily if you set (say) HL_JIT_TARGET=host-cuda (or other gpu) and …

(Backport #7347 to release/15.x) Change early-bound default args in Python bindings to late-bound

---

python_bindings/src/halide/halide_/PyError.cpp
python_bindings/src/halide/halide_/PyError.h
python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyPipeline.cpp
python_bindings/stub/PyStubImpl.cpp
src/JITModule.cpp

Error handling in the Python bindings wasn't quite right for JIT:
We previously replaced halide_error() to throw a C++ exception. Sounds good, but unfortunately, doesn't work reliably: if called from jitted code (which doesn't know about C++ exceptions), the throw statement may be unable to find the enclosing try block (which is outside jitted code), meaning it will call std::terminate. Now, instead, we just leave the JIT error handler unset, and call with an explicit JITUserContext with a custom print handler; in theory, this meant that the code in JITFuncCallContext::finalize() would check for an error after the call into jitted code, and call `halide_runtime_error` if so (which would then trigger an all-in-C++-exception). Unfortunately...
(2) JITFuncCallContext is broken by design; it …

Fix Python error handling

---

src/VectorizeLoops.cpp
test/correctness/CMakeLists.txt
test/correctness/recursive_box_filters.cpp

Pre-vectorization, the code in the included test lowers to:
```
let t16 = f0[((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) + 2] + f0[((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) + 1]
let t17 = (((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) - f1.0.min.0) + 2
atomic {
f1.0[t17] = t16
}
let t18 = ((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) - f1.0.min.0
let t19 = f0[((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) + 2] + f0[((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) + 1]
let t20 = (((f1.s3.r6$x.r6$x*16) + f1.s3.r6$x.r7) - f1.0.min.0) + 2
atomic {
f1.1[t20] = f1.0[t18] + t19
}
```
which then scalarizes, even though those atomic nodes could be vectorized just fine, because each atomic operation is non-recursive. This PR enables vectorization of such atomic nodes.
Note that the code in the test uses an unsafe override of the …

Permit vectorization of non-recursive atomic operations

---

python_bindings/src/halide/halide_/PyError.cpp
python_bindings/src/halide/halide_/PyError.h
python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyPipeline.cpp
python_bindings/stub/PyStubImpl.cpp
src/JITModule.cpp

* Fix Python error handling
Error handling in the Python bindings wasn't quite right for JIT:
We previously replaced halide_error() to throw a C++ exception. Sounds good, but unfortunately, doesn't work reliably: if called from jitted code (which doesn't know about C++ exceptions), the throw statement may be unable to find the enclosing try block (which is outside jitted code), meaning it will call std::terminate. Now, instead, we just leave the JIT error handler unset, and call with an explicit JITUserContext with a custom print handler; in theory, this meant that the code in JITFuncCallContext::finalize() would check for an error after the call into jitted code, and call `halide_runtime_error` if so (which would then trigger an all-in-C++-exception). Unfortunately...
(2) …

(Backport #7352  to release/15.x) Fix Python error handling 

---

src/Simplify_Cast.cpp
test/correctness/simplify.cpp

Overflow on casts is fine for ints < 32 bits

---

src/CodeGen_C.cpp
src/CodeGen_C.h

- Revise HalideFreeHelper to be a templated struct, to save the unnecessary stack storage for the function
- Add emit_halide_free_helper() method to consolidate usage

Clean Up HalideFreeHelper code (main) 

---

src/CodeGen_C.cpp
src/CodeGen_C.h
src/CodeGen_Xtensa.cpp

- Revise HalideFreeHelper to be a templated struct, to save the unnecessary stack storage for the function
- Add emit_halide_free_helper() method to consolidate usage
- Add a nullptr check to the `stack_is_core_private`, per comment
- Fix some minor whitespace issues
(If this PR is accepted here, I will of course backport the non-xtensa portions to main)

[xtensa] Clean up HalideFreeHelper code

---

src/CodeGen_C.cpp

The multi-char form of `unique_name` will append a `$` to the identifier, e.g. `sema$4`. This isn't really legal for a C/C++ identifier.

Use single-char form of `unique_name` for semaphores

---

test/correctness/round.cpp

This gives it proper support for new GPU backends

correctness_round should use Target::supports_type()

---

dependencies/wasm/CMakeLists.txt

The WABT upgrading is just to stay up to date.
The stack size increase is because the most recent versions of Emscripten have slightly greater stack usage in some cases, and we were close enough to the default (64k) for at least one test that the increase put us over the limit. Increased to 96k.

Update WABT to 1.0.32; Increase stack size for WASM AOT apps

---

src/Bounds.cpp

Other visitors handle this case, but it was inexplicably missing from min/max. This causes later checks to is_single_point to suboptimally return false because we get two distinct but equal Exprs.
Partially fixes #7374

Bounds visitors for min/max were missing single_point mutated case

---

test/generator/gpu_only_aottest.cpp

This test used a fake host pointer to get a pipeline to do a device allocation instead of a bounds query. Probably should just call device malloc directly instead.
Also add metal support.

Remove a gross hack from gpu_only_aottest

---

src/InjectDmaTransfer.cpp

There is a hardware limit on number of available DMA channels, so we need to make sure we don't request more than avaialble.

[xtensa] Limit the number of allowed DMA channels + allocate a separate channel for the output transactions

---

src/Callable.cpp
src/Callable.h
test/correctness/callable.cpp

This allows it to behave like other Halide IR pieces.

Add Callable default ctor + `defined()` method

---

src/Bounds.cpp

So further investigating issue I reported #7374 I found that also `Div` visit misses this case which results in not bounded loop being generated.

Bounds visitor for div was missing single_point mutated case

---

src/CodeGen_LLVM.h

This is a partial revert of https://github.com/halide/Halide/commit/32468447f761250574b1a7af5af77f1b2ad18668, otherwise I see a lot of random crashes inside LLVM in Google testing.

Specify a full type for llvm::IRBuilder

---

src/runtime/gpu_context_common.h
src/runtime/printer.h

While tracking down an apparently-unrelated threading bug in the webgpu backend, I made some tweaks to this code that I think are worth keeping. The main one of importance is that `release_hold()` and `release_context()` really should acquire the mutex -- they weren't before -- so now all public methods are properly mutexed.
The other changes are mostly cosmetic:
- Moved helper methods to be private rather than public
- Changed the id value size to be `uintptr_t` rather than `uint32_t`; the space allocated for them is sizeof(void*). (Not sure this moves the needle but it felt right.)
- Removed unused ctor for CachedCompilation
Also, drive-by change in printer.h to capture some logging improvements.

Minor cleanup of GPUCompilationCache

---

apps/hannk/interpreter/tensor.h

This method is useful to debug performance with synchronous execution.

hannk: Add device_sync method hannk::Tensor class

---

README.md

According to https://github.com/halide/Halide/pull/7093, Halide 16 no longer need to support LLVM 13, this PR makes the build instruction in README more consistent with the PR.
cc @abadams

Make README consistent on supported LLVM versions

---

src/CanonicalizeGPUVars.cpp

This new implementation takes the high-water marks of each type of GPU loop, instead of filtering using the prefix of the loop name.
Alternative to #6984

Destringify CanonicalizeGPUVars

---

src/CodeGen_C.cpp
src/CodeGen_C.h

Backported with some trivial style changes (virtual method instead of flag, since this should never changes for a given instance)

Backport changes to CodegenC from the xtensa branch

---

.github/workflows/pip.yml
.github/workflows/presubmit.yml

We need this because https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ and some our checks are warning us about it (e.g. see https://github.com/halide/Halide/actions/runs/4369855467)

Update all use of actions/checkout to v3

---

src/CodeGen_LLVM.cpp
src/CodeGen_X86.cpp

The existing code was codegenning an int32 replacement for an Expr of type uint32. One option was to cast the result to a uint32, but we want wrapping semantics on that subtract, so it's better to just do an unsigned subtraction.
This should fix the breakage with trunk llvm.

Fix overflow in x86 absd lowering

---

README_python.md

I have added the missing fix in the #7402 pull request. (i'm sorry)
Additionally, I have added assert statements. This is because the image created in the first example is of shape `[512, 512, 3]`, while the example being used to compute xor_filter is of shape `[512, 512]`. To avoid confusion for the user, I made it explicit.

docs: Use halide.imageio instead of imageio

---

Makefile
src/runtime/internal/block_allocator.h
src/runtime/internal/block_storage.h
src/runtime/internal/linked_list.h
src/runtime/internal/memory_arena.h
src/runtime/internal/memory_resources.h
src/runtime/internal/pointer_table.h
src/runtime/internal/region_allocator.h
src/runtime/internal/string_storage.h
src/runtime/internal/string_table.h
src/runtime/printer.h
src/runtime/runtime_internal.h
test/runtime/CMakeLists.txt
test/runtime/block_allocator.cpp
test/runtime/block_storage.cpp
test/runtime/common.cpp
test/runtime/common.h
test/runtime/linked_list.cpp
test/runtime/memory_arena.cpp
test/runtime/string_storage.cpp
test/runtime/string_table.cpp

- Don't include .cpp files.
- Don't use header-only "libraries" that rely on include order or being included only once (to wit: test/runtime/common.h -> common.cpp)
- All files should explicitly #include what they need, even if they think it's already included (ie, order of include files should not matter)
- In src/runtime/internal, change all `halide_abort_if_false` -> `halide_debug_assert`
- in test/runtime, add HALIDE_CHECK to common.h and use it for tests instead of `halide_abort_if_false`

Cleanup of src/runtime/internal and test/runtime

---

src/runtime/webgpu.cpp

If RequestDevice fails, make sure we exit initialization early instead of trying to create a staging buffer with a nullptr device.

Fix null device crash during WebGPU initialization

---

src/CodeGen_WebGPU_Dev.cpp

This is the approach that (e.g.) the OpenCL backend takes to assertions inside kernel code.
attn @jrprice

Ignore assertions inside WebGPU kernels

---

Makefile
README_webgpu.md
cmake/HalideGeneratorHelpers.cmake
dependencies/wasm/CMakeLists.txt
src/LLVM_Runtime_Linker.cpp
src/runtime/CMakeLists.txt
src/runtime/webgpu.cpp
src/runtime/webgpu_dawn.cpp
src/runtime/webgpu_emscripten.cpp
test/correctness/interpreter.cpp
test/generator/CMakeLists.txt

Halide promises that you can crosscompile to *any* supported target from a 'stock' build of libHalide. Unfortunately, the initial landing of WebGPU support breaks that promise: we compile the webgpu runtime support (webgpu.cpp) with code that is predicated on `WITH_DAWN_NATIVE` (for Dawn vs Emscripten, respectively).
This means that if you build Halide with `WITH_DAWN_NATIVE` defined, you can *only* target Dawn with that build of Halide; similarly, if you build with `WITH_DAWN_NATIVE` not-defined, you can only target Emscripten. (Trying to use the 'wrong' version will produce link-time errors.)
For people who build everything from source, this isn't a big deal, but for people who just pull binary builds, this is a big problem.
This PR proposes a temporary workaround until the API …

Split WebGPU runtime into two variants (#7248 workaround)

---

src/CodeGen_X86.cpp
src/FindIntrinsics.cpp
src/runtime/x86.ll
src/runtime/x86_avx2.ll
src/runtime/x86_avx512.ll
test/correctness/simd_op_check_x86.cpp

We were rewriting the following into a pmaddubsw:
```
RDom r(0, 2);
f(x) += cast<uint16_t>(g(2*x + r));
f.update().atomic().vectorize(r).vectorize(x, 8);
```
But not the equivalent unrolled version, which is more likely to be written:
```
f(x) = cast<uint16_t>(g(2*x)) + g(2*x + 1)
```
This pattern shows up in downsampling code.
This PR fixes it, and also adds support for doing horizontal widening adds of i16 to i32 using pmaddwd, and adds some missing avx512 variants of horizontal adds using pmaddubsw.

Use pmaddubsw for non-RDom horizontal widening adds

---

src/CodeGen_PyTorch.cpp
src/runtime/HalidePyTorchHelpers.h

There are several problems with the current PyTorch CodeGen.
First, the emitted `.pytorch.h` file incorrectly exposes functions with internal linkage (which is inconsistent with the C codegen), and leads to compile errors when actually compiling the header file. I added a check for internal linkage to fix this.
Next is the problems when using CUDA. Currently when using the generated `.pytorch.h` file, the linker will complain that there is undefined reference to a symbol related to `halide_cuda_device_interface` (the name is mangled when reported by the linker). This is because the forward declaration was not in a `extern "C"` block.
Moreover, there is a really subtle problem when the generated pipeline is invoked by PyTorch (which I actually have described in Matrix). The Halide pipeline …

Fix bugs in PyTorch codegen.

---

src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/IROperator.cpp
src/IROperator.h
src/InlineReductions.cpp

This PR promotes the fixed-point intrinsics out of Halide::Internal:: into Halide::. These are suitable for use in production, and I know of a bunch of production use that just refers to the Halide::Internal:: versions, which is not ideal. In one of our dev meetings we agreed we should just promote them, and I'm finally getting around to doing it.
The PR also adds deprecated wrappers for them in the Internal namespace so that we don't break any existing code.

Promote fixed-point intrinsics out of the Internal namespace

---

src/runtime/HalideRuntime.h

When compiling for 32-bit, LLVM assumes that these structs are only 4-aligned (since alignof(uint64_t) == 4 for x86-32), which means some atomic operations on these structs may require library calls. Since these structs are always malloc'ed, and malloc on all our platforms will return an 8-aligned pointer, we can improve this by telling Clang that the struct will always be at least 8-aligned.

Mark the Halide pipeline structs as aligned(8)

---

src/runtime/profiler_common.cpp
src/runtime/profiler_inlined.cpp
src/runtime/qurt_allocator.cpp
src/runtime/runtime_atomics.h
src/runtime/synchronization_common.h
src/runtime/tracing.cpp
src/runtime/webgpu.cpp

We currently have a set of wrappers around the __atomic/__sync primitives used by our threading model; for various reasons, we desire to use the (deprecated) __sync primitives for 32-bit builds instead of the __atomic primitives (see https://github.com/halide/Halide/pull/7427 for some discussion).
This PR attempts to use these abstractions everywhere else in our runtime, for consistency, so that 64-bit builds consistent use the __atomic primitives for (e.g.) profiling and tracing too. This meant:
- Splitting the wrappers into a new header (runtime_atomics.h), as synchronization_common.h can't be included into arbitrary other files, for valid reasons
- Adding wrappers for the necessary primitives
- Modifying the code elsewhere in the runtime
Where new wrappers were needed, I generally …

Use existing Halide Runtime atomic wrappers everywhere in the runtime

---

apps/hannk/halide/pool_generator.cpp
src/IROperator.h
src/InlineReductions.cpp

Using PseudoExpr as a means of bumping things down the method resolution order wasn't working well. Maybe making the internal wrappers templated will be more successful.

Alternative approach to deprecating internal fixed-point intrinsics

---

src/LLVM_Runtime_Linker.cpp
src/OffloadGPULoops.cpp

Alternative to #7464 
Currently how lerp is lowered inside cuda kernels depends on the host architecture. This was unintentional. This PR nukes the host os and arch when compiling shader kernels so that this sort of accidental dependence doesn't occur in future.

Avoiding having shader kernels depend on host arch/os by unsetting it

---

src/runtime/mini_webgpu.h

In some configurations, clang-format insists on reformatting this file, despite its presence in .clang-format-ignore; at this point it's easier to 'fix' this by inserting `// clang-format off` rather than debug further.

Disable clang-format in mini_webgpu.h

---

python_bindings/src/halide/halide_/PyEnums.cpp
src/Module.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h
test/correctness/simd_op_check_xtensa.cpp

From discussion on https://github.com/halide/Halide/pull/7464, it really makes more sense for Xtensa to be it's own Target::Arch, rather than a Feature, because we shouldn't ever consider other specific architectures in this case -- since (unlike eg GPU) we never generate any 'host' code for Xtensa, it's purely 100% C++ code to run on the DSP.
(attn @Aelphy)

Move Xtensa from Feature to Arch

---

python_bindings/CMakeLists.txt
python_bindings/src/halide/halide_/PyCallable.cpp

Same issue was present in the JIT wrappers for Python; this is the same fix, adapted for JIT.
(Should be backported to release 15.x as well)

Port #6869 to PyCallable (Fix #7213)

---

test/autoschedulers/mullapudi2016/histogram.cpp

It uses fine-grained parallelism, which has a very noisy runtime.

Increase test threshold for mullapudi histogram test

---

test/autoschedulers/adams2019/demo_generator.cpp
test/autoschedulers/adams2019/included_schedule_file_generator.cpp
test/autoschedulers/anderson2021/demo_generator.cpp
test/autoschedulers/anderson2021/included_schedule_file_generator.cpp

https://github.com/halide/Halide/pull/6856 unintentionally reverted some autoscheduler test generators to use non-static dimensions for their input/output buffers, and applied the same changes to some new generators. This changes them all to use static dimensions.

Use static dimensions in autoscheduler test generators

---

python_bindings/CMakeLists.txt
python_bindings/src/halide/halide_/PyCallable.cpp

Same issue was present in the JIT wrappers for Python; this is the same fix, adapted for JIT.

Backport #7472 to release/15.x

---

Makefile
packaging/CMakeLists.txt
src/autoschedulers/adams2019/CMakeLists.txt
src/autoschedulers/adams2019/Makefile
src/autoschedulers/adams2019/adams2019_autotune_loop.sh

The Halide 15.0.0 release inadvertently omitted all of these tools from the packaging. They are being re-added for 15.0.1. While we're doing this, let's go ahead and have the names match those proposed for Halide 16.

Revise autoscheduler tool names to match those from #7483

---

src/runtime/d3d12compute.cpp

Define all symbols with the weak linkage attribute, or as `static constexpr` when applicable. Should allow for merging runtimes together.

d3d12: enforce weak linkage

---

.github/workflows/pip.yml

This change adds a build number based on GitHub Actions' `github.run_id` to the Python wheel before uploading. This should work around the issue that causes the uploads to fail currently.
Fixes #7293

Add build number to Python wheel before uploading

---

src/Module.cpp
src/StmtToViz.cpp
src/StmtToViz.h

(1) Avoid having to guess at location by just passing in the location, since we usually already know it. (2) If we don't know it, be more cautious when constructing it: the output html filename might not match our expectations, and all file extensions must use get_output_info() to work correctly on all platforms.

Improve assembly-file finding logic in StmtToViz

---

src/Module.cpp

TL;DR: if we request `stmt_viz` without `assembly`, just generate the latter to a temp file that we dispose of later; this wasn't feasible before since we were previously requiring the assembly output to be generated with the same directory and basename as stmt_viz, but that was fixed.

Allow emitting `stmt_viz` without specifying `assembly`

---

src/Module.cpp

Don't accidentally embed .s files in .a files when emitting stmt_html

---

src/Buffer.h

Fixes #7514 by triggering a compile-time error instead of silently doing something surprising.

Forbid assigning to Buffer(Expr) by introducing an intermediate type.

---

cmake/FindHalide_WebGPU.cmake
cmake/HalideGeneratorHelpers.cmake
packaging/CMakeLists.txt
src/CodeGen_WebGPU_Dev.cpp
src/Generator.cpp

Might want to add some documentation in `README_webgpu.md` for how AOT compilation works.

Use a find-module to locate Dawn/WebGPU

---

src/XtensaOptimize.cpp

New rewrite rools for narrow_predicate in FindIntrinsics.cpp prevented Optimize to use "clamped_dense_ramp". New patterns compensate for that.

[xtensa] fixed regression due to a new pattern for narrow_predicate

---

src/runtime/device_buffer_utils.h

With MSAN enabled, we use `make_buffer_copy()` to build an efficient way to check the poison bits on buffers; unfortunately, if you are checking a buffer that has at least one dimension with zero-extent but nonzero-stride, the final while loop will never terminate. Add a trivial check so that it exits.

Avoid endless loop in msan + zero-extent buffer

---

test/CMakeLists.txt

On some system size_t isn't available under `<cstdint>`, however it is garaunteed to be available under `<cstddef>` for all systems.

Fix flag check for fuzzers

---

src/Target.cpp

The PR removes the code with workaround for GCC 4.x.x. With later version of GCC (5 and later) and Clang the problem does not exist and "movl %ebx / xchgl %ebx" hack is not needed - the compiler correctly detects the use of `ebx` and stores/restores `ebx` register. The original problem was compiler error message when compiled with `-fPIC` and now it's safe to remove.
I have complete description of the problem here: https://github.com/ispc/ispc/issues/2504 and I've fixed ISPC code as well (it's the code where this snippet was originally borrowed from).

Remove workaround for GCC 4.x.x in cpuid()

---

test/fuzz/cse.cpp
test/fuzz/fuzz_helpers.h
test/fuzz/simplify.cpp

Cleanup the fuzzers making them more readable and fix off by one errors caused by incorrect usage of
FuzzedDataProvider::ConsumeIntegralInRange.
Closes: #7546

fix(fuzz): Refactor fuzzers to fix off by 1 errors

---

test/fuzz/simplify.cpp

Non-boolean arguments to the logical ops cause runtime failures.

Fix errors in fuzz/simplify.cpp

---

test/fuzz/simplify.cpp

FuzzedDataProvider is *not* a RNG; there's no guarantee that it won't return the same data to you forever. This means that the loop to find a new subtype may never terminate (eg if the 'random' type returned always matches the input type). This "fixes" it by just adding a count to break out of the loop, in which case we just use the original type. Not sure if there's a more elegant fix?
attn @silvergasp

Avoid potentially infinite loop in fuzz/simplify.cpp

---

tools/halide_image_io.h

Fix save_tiff() PlanarConfig assignment for monochrome inputs

---

src/runtime/HalideBuffer.h
test/correctness/halide_buffer.cpp

When you are intermixing CPU and GPU calls in a single piece of code, it's preferable to pass `Buffer<>` by nonconst reference, so that lazy host<->device copies are done efficiently.
However, many callers prefer to define input Buffers as `Buffer<const T>` (as they should), but the fact that this form didn't easily allow autoconversion from caller (whihc may well have constructed the buffer as non-const) to callee (due to incompatible type references) led some users to just pass by a copy, since these autoconverted. This had a couple of undesirable effects:
- Making a copy cost a small but nonzero amount of code (managing refcounts, etc)
- More importantly, lazy copies in the callee got 'lost' to the caller, since the `halide_buffer_t` in the callee was a copy, thus any added `device` …

Allow autoconversion from `Buffer<T>` -> `Buffer<const T>&` and to `Buffer<void>&`

---

test/generator/acquire_release_aottest.cpp

There's really not an easy way to create a custom Vulkan context needed for this test.

[vulkan] Disable generator acquire_release test for Vulkan

---

test/correctness/gpu_dynamic_shared.cpp

The linux-buildbot-4 machine only supports v1.2, and that isn't enough to run this test.
Change the feature detection to require v1.3, otherwise skip the test.

[vulkan] Change the feature version requirement to v1.3 for correctness_gpu_dynamic_shared

---

src/runtime/internal/region_allocator.h
src/runtime/vulkan_memory.h

This appears to fix issues that were present on linux-buildbot-4 whereby the driver is reporting a buffer alignment constraint which is larger (??) than the offset alignment constraint for the buffer usage.  In this case, the validation layer reports that this buffer alignment constraint has to be applied to the byte offset for BindBufferMemory.
These changes fix this issue.

[vulkan] Fix subregion memory offsets to respect buffer alignment 

---

src/autoschedulers/adams2019/AutoSchedule.cpp
src/autoschedulers/adams2019/retrain_cost_model.cpp
test/correctness/float16_t_constants.cpp

Newer versions of Xcode trigger `-Wbitwise-instead-of-logical` for this usage, which we treat as an error

Fix various compilation errors with AppleClang 14.0.3

---

src/Target.cpp

only "xtensa-32-noos" allow for the base triple -- at present the bits and os are actually ignored, so let's constrain them to a single value rather than allowing random stuff to still work

Tighten Target parsing for Xtensa

---

test/correctness/simd_op_check_xtensa.cpp

Some Xtensa runtime configurations limit imported symbol name length; this tweaks the test to get under that limit.

Trim xtensa symbol names to get under 65-char limit

---

src/ModulusRemainder.cpp

It wasn't reducing the remainder modulo the modulus, which confused trim_bounds_using_alignment in the simplifier.
Fixes #7584

Fix operator/ on ModulusRemainder

---

src/runtime/hexagon_remote/Makefile
src/runtime/hexagon_remote/known_symbols.cpp

Fix for:
1. Missing include directory for pthread.h
2. Incorrect function signature for qurt_hvx_lock

[Hexagon] Fix compilation failures hexagon_remote

---

test/autoschedulers/adams2019/CMakeLists.txt
test/autoschedulers/anderson2021/CMakeLists.txt
test/autoschedulers/anderson2021/test.cpp
test/autoschedulers/li2018/CMakeLists.txt

Autoscheduler tests that rely on the relevant shared library being available at runtime need to add a dependency to ensure this is the case.

Add missing deps for some autoscheduler tests

---

src/runtime/hexagon_remote/Makefile
src/runtime/hexagon_remote/known_symbols.cpp

Reverts halide/Halide#7601
I'm reverting this because I can't see how the change to known_symbols.cpp could possibly compile anywhere (and it certainly doesn't for me); the `qurt_hvx_mode_t` enum type isn't defined and can't be forward-declared. 
@aankit-ca, please open a new PR with similar changes, but with instructions on how to properly build and test it so I can verify your fix.

Revert "[Hexagon] Fix compilation failures hexagon_remote"

---

CMakeLists.txt
test/CMakeLists.txt

(Harvested from #7604 to land separately)

Fix PCH build failures

---

pyproject.toml
python_bindings/CMakeLists.txt
requirements.txt

(Note that PyBind11 2.10.x is the first version to properly support Python 3.11)

Upgrade our PyBind11 version to 2.10.4 (#7617)

---

src/autoschedulers/adams2019/LoopNest.cpp

This was massively restricting the search space of the autoscheduler, making it faster but excluding most interesting schedules (e.g. all sliding window ones).
Fixes #7531
May also relate to #7623

Fix inverted may_subtile checks

---

src/JITModule.cpp
src/Module.cpp
src/Pipeline.cpp
src/Target.h
src/runtime/HalideRuntime.h
src/runtime/HalideRuntimeOpenGLCompute.h
src/runtime/openglcompute.cpp

This marks OpenGLCompute as deprecated, roughly modeled after the commit that did the same for OpenGL.

Deprecate OpenGLCompute for Halide 16

---

src/WasmExecutor.cpp

Landed the other one too soon :-/

Revise LLVM fix to work when no V8 or WABT available

---

src/Simplify_Internal.h

Be more careful about overflow in trim_bounds_using_alignment

---

src/CodeGen_RISCV.cpp

If you forget to add `-rvv-vector_bits_N` to your Target string, we try to codegen with a vector width of 0, which (unsurprisingly) craters in many places which assume a nonzero value. It's pretty unlikely anyone wants to use Halide to codegen to a RISCV core that lacks SIMD, so let's add a more helpful failure message for this easy-to-make error (we can revisit this later if it actually is desirable for some reason.)
(I looked briefly at trying to clean up all the places in CodegenLLVM, etc, that make that assumption, but it quickly turned into a rat's nest; it's definitely fixable if we want to support this in the future, but, again, I suspect we don't.)

Add user_assert for zero vector width in CodegenRISCV

---

src/CodeGen_RISCV.cpp

Also add a warning if you try to codegen with older versions of LLVM: many intrinsics have changed in ways that are hard to deal with both ways, and trying to support both would be painful and of dubious value.

Fix RISCV codegen for top-of-tree LLVM

---

Makefile
dependencies/llvm/CMakeLists.txt

LLVM17 is doing a lot of work on the RISCV backend, and the amount of testing done on Halide's LLVM16-based RISCV codegen is very light. It's been suggested that we should default to not enabling the RISCV backend for LLVM16 and earlier because of this (so that people attempting to use Halide for RISCV won't encounter a possible footgun).
This PR just adds the relevant mechanism; whether or not this is the correct decision is not clear. Discussion welcome.

Default RISCV backend to OFF for LLVM < 17

---

src/CodeGen_LLVM.cpp

These ops are only used for RISCV codegen at present, and this one tended to only happen for complex patterns that we don't test in our very limited crosscompilation tests.

Fix incorrect name-mangling for llvm.experimental.vp.strided.load

---

apps/onnx/Makefile
apps/onnx/model.cpp
apps/onnx/model_test.py

Fixes #7670
This app had rotted, largely because the linux bots don't have the prereqs installed so they weren't testing it. Unfortunately one of the prereqs seems to be the package python3-onnx, which isn't available on the ubuntu distribution installed on the bots (focal fossa).

Update onnx app to Adams2019 autoscheduler and new autoscheduler API

---

test/correctness/float16_t.cpp

This appears to be a glitch that has to do with changing ABI for float16 across versions of GCC; we build LLVM with gcc-9 on Linux, but the float16 ABI got changed (and unified in gcc12); since ASAN builds use Clang even on linux, there is a hiccup here.
This is an ugly monkey-patch to work around this issue.

Fix correctness_float16_t for ASAN builds

---

src/SimplifyCorrelatedDifferences.cpp

This pass called expr_uses_var in a loop while building up a potentially long let chain. This does a quadratic amount of work in the size of the let chain, which stalled compilation for a particular pathological pipeline I encountered.
This changes it to an eager algorithm that tracks the set of free variables and incrementally grows it instead of revisiting the entire expr for each new let added. It is n log(n) in the number of lets instead of n^2

Fix quadratic algorithm in simplify_correlated_differences

---

test/correctness/float16_t.cpp

Fix float16 under asan, attempt #2

---

python_bindings/src/halide/_generator_helpers.py
python_bindings/src/halide/halide_/PyGenerator.cpp
src/AbstractGenerator.h
src/Generator.cpp
src/Generator.h
src/ObjectInstanceRegistry.cpp
src/ObjectInstanceRegistry.h
src/autoschedulers/adams2019/cost_model_generator.cpp
src/autoschedulers/anderson2021/cost_model_generator.cpp
test/generator/abstractgeneratortest_generator.cpp

See https://github.com/halide/Halide/issues/7669 for details
attn @Copper280z

Add a warning if a Generator declares any Outputs before the final Input (Fixes #7669)

---

apps/bgu/bgu_generator.cpp

See discussion in #7681.
This patch simplifies the regularization. The most important takeaway is in the comment of the changed code, and a thought I had: https://github.com/halide/Halide/issues/7681#issuecomment-1638095230 :
> The only thing I'm not sure about is that I changed it to regularize towards the identity function, instead of "towards the average gain in the cell". The problem I have with "the average gain" is that you also need samples to compute the average gain, which is exactly the problem being solved.
@jiawen @abadams I don't know if you want to validate the result by running the experiment setup of your paper? I guess that will be a more formal test.

Fixed the regularization for BGU.

---

src/autoschedulers/adams2019/FunctionDAG.cpp
src/autoschedulers/adams2019/FunctionDAG.h
src/autoschedulers/adams2019/Timer.h
src/autoschedulers/anderson2021/FunctionDAG.cpp
src/autoschedulers/anderson2021/FunctionDAG.h
src/autoschedulers/anderson2021/GPULoopInfo.h
src/autoschedulers/anderson2021/GPUMemInfo.h
src/autoschedulers/anderson2021/LoopNest.h
src/autoschedulers/anderson2021/LoopNestParser.h
src/autoschedulers/anderson2021/SearchSpace.cpp
src/autoschedulers/anderson2021/SearchSpaceOptions.h
src/autoschedulers/anderson2021/State.cpp
src/autoschedulers/anderson2021/Statistics.h
src/autoschedulers/anderson2021/test/thread_info.cpp
src/autoschedulers/common/ASLog.h
src/autoschedulers/common/PerfectHashMap.h
src/autoschedulers/common/cmdline.h
src/autoschedulers/mullapudi2016/AutoSchedule.cpp

Good code hygiene, noticed while working on Anderson2021 bugs. (Done via using clang-tidy-17, which has a new check to enforce this.) Note that this also converted a couple of `push_back()` -> `emplace_back()`.

Mark all single-arg ctors in autoscheduler code as `explicit`

---

src/runtime/HalideBuffer.h
src/runtime/cuda.cpp
src/runtime/internal/memory_arena.h
src/runtime/internal/pointer_table.h
src/runtime/internal/string_storage.h
src/runtime/internal/string_table.h
src/runtime/opencl.cpp
src/runtime/profiler_common.cpp
src/runtime/scoped_mutex_lock.h
src/runtime/scoped_spin_lock.h
src/runtime/synchronization_common.h
src/runtime/vulkan_context.h
src/runtime/webgpu.cpp

Minor code hygiene fix, done as byproduct of #7704

Mark all single-arg ctors in src/runtime as explicit

---

src/Dimension.cpp
src/Dimension.h
src/Parameter.cpp
src/Parameter.h

This should fix memory leaks caused by Parameters that have constraints that refer back to the same Parameter.
Note that it *doesn't* fix leaks caused by Parameter A having a constraint that refers to Parameter B which has a constraint that refers back to Parameter A.

Fix leaks caused by self-referential parameter constraints

---

test/correctness/float16_t.cpp

This routine was missing a float cast when compiled with older clangs. Also removed the warning, because I have now tested it.

Fix float16 warning for older clangs

---

Makefile
README.md
dependencies/llvm/CMakeLists.txt

LLVM just added `release/17.x` branch and now trunk is 18 -- update our build files and docs accordingly (see also https://github.com/halide/build_bot/pull/248, which needs to land first)

Upgrade Halide main branch for LLVM18

---

src/CodeGen_ARM.cpp
test/CMakeLists.txt

Just because our compiler supports fuzzing doesn't mean we want to build the fuzz tests, because they won't really build properly without the right preset specified.
(This will be followed up with a change to the buildbot to set WITH_TEST_FUZZ to ON for fuzz tests)
attn: @TH3CHARLie

Default WITH_TEST_FUZZ to OFF

---

src/Func.cpp
test/correctness/float16_t.cpp
test/error/CMakeLists.txt
test/error/split_same_var_names.cpp

Throw an erorr if split is called with the same older and inner var name

---

test/generator/CMakeLists.txt

This test is meant to be run twice, with different env vars; the Makefile does this, but the CMake version somehow overlooked it.

Fix CMake test for generator_aot_multitarget

---

src/CodeGen_Metal_Dev.cpp

This PR is similar to https://github.com/halide/Halide/pull/7719 but the impact is much less dramatic.

Making Metal code-gen a bit faster

---

src/autoschedulers/anderson2021/LoopNest.cpp
src/autoschedulers/anderson2021/LoopNest.h
src/autoschedulers/anderson2021/State.cpp
src/autoschedulers/anderson2021/Tiling.cpp
src/autoschedulers/anderson2021/test/storage_strides.cpp
test/autoschedulers/anderson2021/test.cpp

This fixes the issue in https://github.com/halide/Halide/pull/7699. The cause is that the autoscheduler assumes that every Func is surrounded by a block loop and a thread loop, which means it assumes there is always a non-null `ThreadInfo` object when the features are computed. But in this case, the output of the generator is a single number so the autoscheduler is currently not creating a block and thread loop for it, so the ThreadInfo object ends up being null.
The main thing this PR does is add some special cases to `compute_features` for handling scalars. It was also necessary to change some function signatures to accept a `ThreadInfo*` instead of a `ThreadInfo&` so that it can test whether the passed object is null or not.

Fix handling of thread features for scalars in Anderson2021

---

src/Generator.cpp

Timeouts should really be the responsibility of the build system. Leaving the feature in because it's useful for things like autotuning loops.

Change default generator timeout to infinite

---

src/Func.cpp

When cloning a Func with an update def, the remapping map resulting from the deep copy may already contain a key for the wrapped function pointing to a strong reference to itself. The reasons are unclear to me, but it means that emplace silently does nothing and we get a memory leak because the cloned Func's update definition has a strong self-reference after the remapping is applied.
We want to replace it with a weak reference, so this PR changes things to use operator[] instead of emplace.

Fix leak on cloning functions with update defs

---

.github/workflows/presubmit.yml
run-clang-tidy.sh
src/Generator.cpp

The current macOS runners have twice the RAM and more CPU power.
Also, drive-by change to allow specifying the parallelism that the run-clang-tidy script should use (defaults to nproc)

Run clang-tidy on macOS runners instead of Linux

---

src/PartitionLoops.cpp
test/correctness/partition_loops.cpp

Fix infinite recursion in loop partitioning

---

dependencies/llvm/CMakeLists.txt

Our build instructions for windows are currently broken, because vcpkg is still on llvm 15. This PR unbreaks them. Re-enabling any testing of llvm 15 to be discussed.

Permit llvm 15 on windows

---

src/SpirvIR.cpp
src/SpirvIR.h

Removed parent/owner back references (which weren't actually needed)
Fixed ownership transfers
Explicitly destruct and clear contents

[vulkan] Fix SPIR-V IR references causing leaks

---

src/Simplify_Cast.cpp

The simplifier normalizes `reinterpret<i32>(u32)` (which has defined behavior) to `cast<i32>(u32)`, which has undefined behavior. Currently, the following code produces inconsistent output:
```
{
Expr x = UIntImm::make(UInt(32), 0xFFFFFFF0u);
Expr e = i32(x + 1);
e = simplify(e);
std::cout << e << std::endl;
e = reinterpret(Int(32), x + 1);
e = simplify(e);
std::cout << e << std::endl;
}
{
Expr x = Variable::make(UInt(32), "x");
Expr e = i32(x + 1);
e = simplify(e);
e = substitute("x", UIntImm::make(UInt(32), 0xFFFFFFF0), e);
e = simplify(e);
std::cout << e << std::endl;
e = reinterpret(Int(32), x + 1);
e = simplify(e);
e = substitute("x", UIntImm::make(UInt(32), 0xFFFFFFF0), e);
e = simplify(e);
std::cout << e << std::endl;
}
```
Output:
```
signed_integer_overflow(0)
-15 …
```

Define `cast<i32>(u32)` overflow behavior

---

src/StmtToViz.cpp

A Div can't be in a Span. HTML parsers will lift the Div out of the span and turn it into a sibling.

Fix vector reduce HTML

---

test/correctness/simd_op_check_arm.cpp

LLVM pattern matching is no longer fragile enough to need this safeguard.

Remove fragile simd_op_check test for mlal/mlsl on ARM

---

src/StmtToViz.cpp
src/irvisualizer/StmtToViz_dependencies.template.html
src/irvisualizer/StmtToViz_javascript.template.html
src/irvisualizer/StmtToViz_stylesheet.template.html

- Disabled line numbers in the syntax highlihgting of the assembly. This was a massive bottleneck upon opening the assembly tab.
- ~~Made syntax highlighting on-demand with a button.~~
- Also, inspired by @antonysigma, I replaced some of the element-grabbing in the `toggleViz` to directly take the element instead of running a selector query. This was a big speedup.
- Updated scrolling logic to deal with the lack of line number divs. 
- Prevented the last update recalculation when collapsing the assembly tab upon loading the page.
- Deleted all the tooltip JavaScript, and now just make them appear on `:hover`. This significantly lowers the amount of "listeners" in the document. (Inspired by @antonysigma as well for this).
- Finally, cleanup some dangling dependencies that were not used and …

Speedup page loading of VizStmt.

---

cmake/toolchain.linux-x64-asan.cmake
cmake/toolchain.linux-x64-fuzzer.cmake
test/correctness/skip_stages_memoize.cpp
test/generator/error_codes_aottest.cpp

This fixes all but one of the known remaining ASAN-related leaks; the remaining is in `tutorial_lesson_19_wrapper_funcs`
I can't debug that one locally because the leaks are in OpenCL and I am temporarily relegated to using a 'cloud' machine with no real GPU for linux-x64 -- if someone with access to such a machine could take a look, I'd appreciate it (examples of leakage at https://buildbot.halide-lang.org/master/#/builders/154/builds/79/steps/12/logs/tutorial_lesson_19_wrapper_funcs)
Also, drive-by change to turn off CCache for sanitizer builds in the presets files -- we are already doing this on the buildbots via config script, but doing it in the presets is good too for people who want to use it locally (for reasons that aren't entirely clear, CCache and sanitizers don't like each …

Try to fix remaining ASAN-reported leaks

---

src/autoschedulers/anderson2021/SearchSpace.cpp

This fixes https://github.com/halide/Halide/issues/7606. If an update stage has fewer pure vars than the pure definition, it can end up reading out of bounds. When reading the size of the update stage's loop, instead of using the corresponding pure dimension, it should just use its index within the update stage's loops.

Fix out of bounds access in anderson2021_test_apps_autoscheduler

---

src/FindIntrinsics.cpp
src/IR.h

As discussed with @abadams , later lowering stages expect to see int/uint reinterprets to have been normalized to casts. This PR removes the places in `find_intrinsics` and `lower_intrinsics` that introduce `reinterpret`, and use `cast` instead.

Don't introduce reinterprets in find/lower intrinsics

---

src/IRMatch.h
test/correctness/simplify.cpp

slice IRMatcher should only match on slices

---

src/CodeGen_ARM.cpp
src/FindIntrinsics.cpp
test/correctness/simd_op_check_arm.cpp

udot and sdot can still be used even if we need to interleave the arguments (and is faster than a string of `smull`/`saddw`s). This PR adds those patterns + tests (and a few fly-by FindIntrinsics fixes).

[ARM] support new udot/sdot patterns

---

src/AlignLoads.cpp
src/CodeGen_GPU_Dev.cpp
src/CodeGen_Internal.cpp
src/CodeGen_PyTorch.cpp
src/CodeGen_RISCV.cpp
src/Float16.cpp
src/OptimizeShuffles.cpp
src/PartitionLoops.cpp
src/Pipeline.cpp
src/Prefetch.cpp
src/Profiling.cpp
src/RealizationOrder.cpp
src/ScheduleFunctions.cpp
src/SimplifySpecializations.cpp

These were found with clang-tidy 18's misc-include-cleaner checker and then only taking the suggested deletions, so I believe these are truly unused, and not just transitively included or something.

Remove some unused includes

---

src/CodeGen_LLVM.cpp
src/CodeGen_WebAssembly.cpp
src/LLVM_Headers.h
src/LLVM_Output.cpp
src/Simplify_Exprs.cpp

See https://github.com/halide/Halide/issues/7796

[wasm] Enable PIC for WebAssembly on LLVM v18.x

---

src/runtime/mini_webgpu.h
src/runtime/webgpu.cpp
test/common/gpu_context.h
test/generator/gpu_object_lifetime_aottest.cpp

- Updated mini_webgpu.h to be in sync with Dawn as of commit ded6610f45a8826db37b52d73121a66b74d8aa61
- Updated the use of SetDeviceLost callbacks to be in the DeviceDescriptor instead of a separate call
- Updated a couple of fields that got renamed
- Update webgpu.cpp and gpu_context.h to always use wgpuCreateInstance() and wgpuInstanceRelease(), since the Dawn node bindings now support & require them
attn: @jrprice

Update WebGPU to latest Emscripten/Dawn API

---

src/StmtToViz.cpp

Added (blue) jump to assembly buttons immediately in the Stmt code.

Add jump-buttons to get fro Stmt directly to Assembly

---

.github/workflows/presubmit.yml
src/Generator.cpp

~`macos-latest` is actually macos-12 (macos13 is considered "beta" on the GHA runners). Hopefully this will fix the recent install snafus that are breaking clang-tidy.~
TL;DR: the GHA macOS image has junk installed that conflicts with Homebrew. Brute-force removal is apparently the workaround. 
Also, drive-by install of flatbuffers in anticipation of https://github.com/halide/Halide/pull/7794.

Update clang-tidy action to stop breaking

---

.github/workflows/presubmit.yml
src/Generator.cpp

Recent changes in the GHA runners for macOS don't play well with clang-tidy; rather than sink any more time into debugging it, I'm going to revert the relevant parts of #7746 so that it runs on the less-finicky Linux runners instead.

Move clang-tidy checks back to Linux

---

src/CodeGen_X86.cpp
test/correctness/simd_op_check_x86.cpp

Fixes #7836
Fixes #4166
These weren't enabled yet because the last time this code was touched, float16 wasn't a legal type in llvm on x86 (See https://bugs.llvm.org/show_bug.cgi?id=43065)

Enable emission of float16/32 casts on x86

---

src/VectorizeLoops.cpp
test/correctness/vectorize_nested.cpp

We need to iterate over vars in insertion order, but the Scope doesn't preserver the order.
Fixes #7779

Iterate over lets in the correct order in VectorizeLoops

---

Makefile
apps/simd_op_check/Makefile
test/correctness/simd_op_check_xtensa.cpp

This PR adds some testing for Xtensa target and requires a cstub library which can be obtained from the vendor.
Only tests/generator are supported, because Xtensa codegen is based on C++ codegen and doesn't support JIT execution. There are a few tests which fail and excluded right now, so need to be fixed later, but I don't think any of them are really critical.
To run the tests:
```
make test_aotcpp_xtensa_generator
```
In addition, apps/simd_op_check will compile and verify correctness of operations listed in test/correctness/simd_op_check_xtensa (which in turn will verify that specific intrinsic was generated for corresponding pattern).
To run the app:
```
make clean && make xtensa -j 12 && ./bin/driver-xtensa
```
Finally, this is only added for Make build, I will repeat the exercise …

Build rules for Xtensa tests with cstub library

---

src/IR.cpp
src/PartitionLoops.cpp
src/Simplify_Stmts.cpp
test/correctness/CMakeLists.txt
test/correctness/fuzz_schedule.cpp

In one place in PartitionLoops and in another place in the simplifier we were neglecting to consider nested vectorization.
I added the fuzzer output that triggered this as a new test, because I have no idea how I'd generate this error with human-readable code. It stems from an interaction of several tail strategies.
Fixes #7851

Handle nested vectorization in store predicates

---

src/AddImageChecks.cpp
test/correctness/CMakeLists.txt
test/correctness/respect_input_constraint_in_bounds_inference.cpp

Respect input buffer constraints in root-level bounds inference exprs

---

src/Bounds.cpp
src/Bounds.h
test/correctness/CMakeLists.txt
test/correctness/bounds_query_respects_specialize_fail.cpp

See https://github.com/halide/Halide/issues/7756#issuecomment-1736001570
Fixes #7756

Handle unreachable code in bounds inference

---

src/Simplify_Stmts.cpp
test/correctness/fuzz_schedule.cpp

Don't deduce unreachability from predicated out of bounds stores

---

src/Simplify_Stmts.cpp
src/SlidingWindow.cpp
test/correctness/fuzz_schedule.cpp

Even ones we've already slid over. The previous version of this code
could try to slide over a loop where multiple dimensions depend on the
loop var, because it ignored dimensions that had already been slid over.
Moving a check resolves the issue.
Fixes #7872

Consider all dimensions before deciding to slide over a new dimension

---

apps/fft/complex.h

Implement the logic: (a + bj) / (c + dj) as an `inline operator/()` function.
Use case: direct FFT method to solve linear least square problem, namely:
```math
\begin{align}
f(x) &=\Vert F^T D F x - b \Vert_2^2 \\
\arg \min_{x \in \mathbb{R}} f(x)
&= F^T \left[ D^{-1} F b \right]
\end{align}
```
where `D` is a diagonal complex-valued matrix representing image blur kernel in Fourier domain, `b` is an ordinary image in vectorized form.
See also: #7456 , #5318 .

Implement elementwise complex value division

---

src/LLVM_Runtime_Linker.cpp

They now want layouts for i128 types

Attempted fixed datalayouts for llvm trunk

---

src/Type.h
test/correctness/vector_reductions.cpp

Check for overflow in Type constructor

---

src/Deinterleave.cpp
test/correctness/fuzz_schedule.cpp

In the following code:
```
let a = b in
X
let a = c in
Y
```
If Stmt X successfully had stores interleaved, we were re-nesting it like so:
```
let a = b in
X
let a = c in
Y
```
This introduces a shadowed variable 'a', which is illegal at this stage of lowering.
Fixes #7906
Also some drive-by fixes to earlier tests that had debugging code left in.

Stop interleaver from expanding the scope of letstmts

---

src/StmtToHTML.cpp
src/irvisualizer/html_template_StmtToHTML.css
src/irvisualizer/html_template_StmtToHTML.js

While I was investigating the buffer index datatypes for #7884 myself, I added tooltips to reveal the datatype of the IR node in the Stmt file.
Another feature I wanted much, to analyze variables (especially when there is too much code to fit on the screen and you have to start scrolling, which makes the highlight-on-hover impractical) is to color matching variables by clicking them. There are 7 colors slots which will automatically recycle if you un-highlight a variable.
Also minor bugfix in the printing: Reinterpret casts were printed as normal casts before.

Highlight groups for the HTML Stmt file and tooltips to reveal types.

---

src/runtime/device_buffer_utils.h

Preventing things like:
```
Warning	C26451	Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).
```

Static analysis (MSVC) fixes for device_buffer_utils.h

---

test/correctness/bounds_query_respects_specialize_fail.cpp

Otherwise, we are getting: 
```
error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]
```

Check returned result in the test

---

src/StmtToHTML.cpp

It did work before, but only because browsers know people like me can't program correctly...

Hotfix reinterpret HTML

---

src/Deinterleave.cpp
src/IR.cpp
src/IR.h
src/SlidingWindow.cpp
src/StorageFolding.cpp
test/correctness/fuzz_schedule.cpp

Explicitly mark which loops get loop-carry-dependencies inserted by
sliding window to assist storage folding.
Storage folding needs to know about this so it doesn't try to fold in a
way that invalidates these read-after-write dependencies. It currently
tries to prove the absence of hazards with box_contains(box_provided,
box_required), but this is sometimes incorrect because box_provided
could be conservatively large, and the code it analyses might not
actually provide (store to) all the required (loaded from) values.
It's simpler for sliding window to just tell storage folding when it
inserts loop-carry-dependencies, and this is most simply done directly
in the IR itself.
Fixes #7909
Built on #7908 to avoid a merge conflict in the fuzz_schedule.cpp test

Fix read-after-write hazard analysis in storage folding

---

src/StmtToHTML.cpp

This  preserves compiling the Halide compiler without RTTI.

Remove use of dynamic_cast.

---

src/Deserialization.cpp
src/Serialization.cpp
src/halide_ir.fbs

The serialization code comes with the recent `partition` primitive misses out `Dim::partition_policy`, leading `error_bad_partition_always` to fail under serialization. This PR fixes it.

Add missing serialization of Dim::partition_policy

---

Makefile
src/Generator.cpp
src/Generator.h
test/generator/CMakeLists.txt
test/generator/all_type_names_aottest.cpp
test/generator/all_type_names_generator.cpp

Specifically adding 64-bit signed and unsigned integers and making sure float16 and bfloat16 are fully supported and documented.
Add a simple test for all the type names.

Make sure all Halide arithmetic scalar types can be named from the Generator interface.

---

src/CodeGen_LLVM.cpp

This API is removed in LLVM trunk now https://github.com/llvm/llvm-project/commit/7b9d73c2f90c0ed8497339a16fc39785349d9610.

Remove the deprecated API `llvm::Type::getInt8PtrTy` usage.

---

src/CodeGen_LLVM.h

This function is never called by the base class, so overriding it in a derived class will also do nothing.

Delete unused function

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_X86.cpp

gather being slow turned out to be a microcode mitigation on a range of intel processors
See https://github.com/llvm/llvm-project/issues/70259
Rather than turn off SLP vectorization entirely as in #7918 , this PR just turns of gather instruction emission unless we know for sure we're not on one of the affected processors.
Fixes #7917 (but in a different way)

More targeted fix for gather instructions being slow on intel processors

---

src/BoundaryConditions.cpp
src/PartitionLoops.cpp
src/PartitionLoops.h
test/correctness/likely.cpp

Fixes #7929
Improves runtime of lens_blur app by ~20%

Track likely values through lets in loop partitioning

---

src/Simplify_And.cpp
src/Simplify_Stmts.cpp
test/correctness/simplify.cpp

This triggered in practice on some oddly-structured code.
Also added a simplifier rule that seemed like it was missing I encountered while adding a test.

Add missing condition to if renesting rule

---

src/CodeGen_ARM.cpp

Always call lower_round_to_nearest_ties_to_even on arm32

---

apps/interpolate/Makefile
apps/interpolate/interpolate_generator.cpp
apps/local_laplacian/Makefile
apps/local_laplacian/local_laplacian_generator.cpp
src/Func.cpp
src/Func.h
src/Generator.h
src/LoopPartitioningDirective.h
src/PartitionLoops.cpp
test/correctness/likely.cpp

This reduces compile time for the manual local laplacian schedule from 4.9s to 2.2s, and reduces code size from 126k to 82k
It's all from avoiding loop partitioning. Most of the reduction comes from avoiding a pointless boundary condition in the output Func, which triggered partitioning. A smaller amount comes from using RoundUp and Partition::Never. The Partition::Never calls are responsible for a 3% reduction in code size and compile times by themselves.
This has basically no effect on runtime. It seems to reduce it very slightly, but it's in the noise.
There's also a drive-by fix to Generator.h, exporting the Partition enum class.

Improve code size and compile time for local laplacian app

---

src/Deserialization.cpp
src/Deserialization.h
src/Serialization.cpp
src/halide_ir.fbs
tutorial/lesson_23_serialization.cpp

Add deserialize_parameter methods to allow the user to only deserialize the mapping of external parameters (and remap them to their own user parameters) prior to deserializing the full pipeline definition.  Updated tutorial lesson 23.
See also #7849

[serialization] Serialize stub definitions of external parameters.

---

README_webgpu.md
src/runtime/mini_webgpu.h
src/runtime/webgpu.cpp

* Update mini_webgpu.h with latest version from Dawn
* Document this process
* Remove an argument from wgpuQueueOnSubmittedWorkDone
Fixes #7581

[WebGPU] Update to latest native headers

---

src/Deserialization.cpp

Needed to prevent "error: non-void function does not return a value"

Return values from stub functions in Deserialization

---

test/performance/fast_inverse.cpp

This test is currently failing on a Cortex a76 buildbot, because it's a recursive update definition so it ends up limited by instruction latencies rather than throughputs. On an a76 (which is a reasonable CPU to assume for a generic ARM target), if you multiply by a fast inverse the total latency is frecpe + frecps + fmul = 11, whereas the Cortex a76 optimization guide says the latency of an fdiv instruction is 7-10. The cycle costs (sum of inverse throughput) however, are 3 and 8 respectively, so fast_inverse is still a good idea for most imaging workloads that aren't the goofy recursive thing in the test. So hopefully if I just change the test to be thoughput-limited, it'll fix it.
Still disabled on M1, because fdiv there has a throughput of 1?!

Make the fast inverse test throughput-limited rather than latency-limited

---

test/performance/nested_vectorization_gemm.cpp

This new schedule is about the same speed as the old one on an M1, but generates much less code, spills less, and avoids the use of tbl instructions in favor of zips.

Attempt to fix nested vectorization gemm performance on new build bot

---

tutorial/lesson_21_auto_scheduler_generate.cpp

The generated schedule from the auto-scheduler can no longer be copy-n-pasted to the Generater source code. Update the tutorial to show how the generated schedules can be appled and included into Generator. Use case: version control and fine tuning of schedules.
Resolves: #7148
See also: #7900
cc'ed @derek-gerstmann .

Update instructions to include generated schedules

---

src/CodeGen_X86.cpp

All known AVX2-enabled architectures definitely have these features.

complete_x86_target() should enable F16C and FMA when AVX2 is present

---

Makefile
src/BoundConstantExtentLoops.cpp
src/BoundConstantExtentLoops.h
src/BoundsInference.cpp
src/CMakeLists.txt
src/Lower.cpp
src/Simplify.cpp
src/Simplify.h
src/UnrollLoops.cpp
src/VectorizeLoops.cpp
test/correctness/CMakeLists.txt
test/correctness/unroll_loop_with_implied_constant_bounds.cpp
test/correctness/vectorized_guard_with_if_tail.cpp

Fixes #7968
This also changes the interface to simplify() to accept a vector of boolean Exprs that can be assumed to be true, which is a change I've been meaning to make for a while. The simplifier supports it internally, but it wasn't exposed in the API.

Teach unrolling to exploit conditions in enclosing ifs

---

src/CodeGen_LLVM.cpp

startswith was deprecated in [llvm/lvm-project#75491](https://github.com/llvm/llvm-project/pull/75491), which means that Halide now fails to compile using LLVM 18 (deprecation warning).

Change startswith -> starts_with

---

test/runtime/memory_arena.cpp

There was a rogue use of VLAs (an extension we don't want to use) in one of the runtime tests. Fixed the test. I'll follow up with a separate PR to ensure this warning is enabled everywhere to flush out other usages.

Don't use variable-length arrays

---

src/runtime/HalideRuntime.h

When HalideRuntime.h is included in a C file, functions that are declared with `()` instead of `(void)` for their arguments change meaning. These may cause issues downstream because different code is generated. 
E.g., [godbolt example](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyagA%2BudTkVjVEQJDqzTAGF09AK5smIAMw9yTgAyBEzYAHKeAEbYpCAArOQADuhKxPZMrh5evv7JqXZCwaERbNGxCdbYtukiRCykRJme3n5W2DYFTLX1REXhUTHxVnUNTdmtSiO9If2lg3EAlFbo7qSonFzY6kQxTADUIUR7gugQCwCkPgBC51oAgrd3Wzuk%2B4d7kfUQAG7oBJgXa6PR7vNgsEIQd71YCWPaoJD1ABUiL20O%2BCz25wA7Dd7nt8R8voDcXcCcd0KdiY8yaRsERVvstJcSdiACJcJb0bhxfjeLg6cjobjOPZKFZrbCYgBMfn4RG0HKWAGtfD4AHQ%2BTVa7XagBshm40n4bHiWnIfIFQq4/CUIDN8v5HPIcFgKAwOHwxDIlGodEYrA43D4cmEYgknBkIcUKg0CvI%2Bilhm …

Fix -Wstrict-prototype warnings in HalideRuntime.h

---

src/LoopCarry.cpp
test/correctness/CMakeLists.txt
test/correctness/loop_carry.cpp

```can_prove``` is stronger than ```graph_equal```, because it doesn't require index expressions to be *exactly* the same, but evalutate to the same value. I kept the ``` graph_equal``` check, because it's faster and should be executed before the more expensive check.
In one of the internal workloads, I see that with this change, what was previously split into three different chains of 4-, 2-, 3- values, is correctly combined into one long chain of lenght 9-.

Stronger chain detection in LoopCarry pass

---

test/correctness/float16_t.cpp

Tweak correctness_float16_t so that it uses one of the transcendal functions (sqrt) that were missing in Metal.

Add test for #8029

---

cmake/HalideTestHelpers.cmake
src/runtime/d3d12compute.cpp
src/runtime/posix_error_handler.cpp
src/runtime/printer.h
src/runtime/runtime_internal.h
src/runtime/to_string.cpp
src/runtime/tracing.cpp

TL;DR: template expansion meant that we had more replicated code than expected from the inline expansion of code in Printer and friends. Restructured and added NEVER_INLINE to try to make the call sites as small as possible. It's a modest code-size savings but nonzero... e.g., the linux-x86-64 .o output from correct_cross_compilation drops from 164280 bytes to 162936 bytes.

Tweak the Printer code in runtime for smaller code

---

src/VectorizeLoops.cpp
test/correctness/fuzz_schedule.cpp

bounds_of_nested_lanes assumed that one layer of nested vectorization could be removed at a time. When faced with the expression:
`min(ramp(x8(a), x8(b), 5), x40(27))`
It panicked, because on the left hand side it reduced the bounds to `x8(a) ... x8(a) + x8(b) * 4`, and on the right hand side it reduced the bounds to `27`. It then attempted to take a min of mismatched types.
In general we can't assume that binary operators on nested vectors have the same nesting structure on both sides, so I just rewrote it to reduce directly to a scalar.
Fixes #8038

Fix bounds_of_nested_lanes

---

Makefile

This means we actually print error messages when using exceptions and the makefile.
This was already done for cmake a while back.

Update makefile to use test/common/terminate_handler.cpp

---

test/correctness/simd_op_check_arm.cpp
test/correctness/simd_op_check_hvx.cpp
test/correctness/simd_op_check_powerpc.cpp
test/correctness/simd_op_check_wasm.cpp
test/correctness/simd_op_check_x86.cpp

The old definitions of bool_1, bool_2, bool_3 in simd_op_check_x86 (etc) all referred to the same entry in in_f32; as of https://github.com/llvm/llvm-project/pull/76367, the LLVM optimizer is smart enough to realize that (eg) bool1 != bool2 by construction, and optimizes away the code that tests their conditions, such as the one for andps and orps. Initing them from different locations is enough to outsmart the compiler.
(bug was only noticed in the x86 test, but I updated the other tests to guard against future improvements there too.)

Outsmart the LLVM optimizer

---

src/CodeGen_Vulkan_Dev.cpp
test/correctness/CMakeLists.txt
test/correctness/bool_predicate_cast.cpp

SPIRVEmitter::convert_to_bool(...) was incorrectly passing the address of a byte vector, instead of its contents to builder.declare_constant(...)
As reported here:
https://github.com/halide/Halide/issues/8064

Fix bool conversion bug in Vulkan code generator

---

src/Debug.h

Allow wrapping vectors and vector like containers with `ConPrint` or `ConPrintLn` to pass to `operator<<` for use in Halide debug output.
Open to advice on naming. I am not aware of other idioms for this and end up writing quick loops to print values fairly frequently. There is a routine for doing this with `std::vector<Function>` in ScheduleFunctions.cpp as well.
Might need perfect forwarding support, but I don't think so.

Add an easy way to print vectors in debug output.

---

src/halide_ir.fbs

As a matter of policy, we should probably bump the version of the serialization format for every version of Halide -- even if changes are minimal-to-nonexistent -- to reinforce the fact that this isn't intended in any way as a long-term archival format.
This PR suggests that we bump the major version to match the main Halide version, but I'm open for other suggestions.

Bump serialization version to 18.0.0

---

Makefile
src/AddSplitFactorChecks.cpp
src/AddSplitFactorChecks.h
src/CMakeLists.txt
src/Callable.cpp
src/JITModule.cpp
src/JITModule.h
src/Lower.cpp
src/Pipeline.cpp
src/Pipeline.h
src/runtime/HalideRuntime.h
src/runtime/errors.cpp
src/runtime/runtime_api.cpp
test/correctness/CMakeLists.txt
test/correctness/negative_split_factors.cpp

Our analysis passes assume that loop maxes are greater than loop mins, so negative split factors cause sufficient havoc that not even output bounds queries are safe. These are therefore checked on pipeline entry.
This is a new way for output bounds queries to throw errors (in addition to the buffer pointers themselves being null, and maybe some buffer constraints). Testing this, I realized these errors were getting thrown twice, because the output buffer bounds query in Pipeline::realize was built around two recursive calls to realize, and both were calling the custom error handler. In addition to reporting errors in this class twice, this implies several other inefficiencies, e.g. jit call args were being prepped twice. I reworked it to be built around two calls to call_jit_code instead. …

Add checks to prevent people from using negative split factors

---

src/Func.cpp
test/correctness/fuzz_schedule.cpp

When you rfactor an update definition, the new update definition must use all the pure vars of the Func, even though the one you're rfactoring may not have used them all.
We also want to preserve any scheduling already done to the pure vars, so we want to preserve the dims list and splits list from the original definition.
The code accounted for this by checking the dims list for any missing pure vars and adding them at the end (just before Var::outermost()), but this didn't account for the fact that they may no longer exist in the dims list due to splits that didn't reuse the outer name. In these circumstances we could end up with too many pure loops. E.g. if x has been split into xo and xi, then the code was adding a loop for x even though there were already loops for xo and xi, which …

Fix rfactor adding too many pure loops

---

test/correctness/simd_op_check.h

simd_op_check_xtensa is not threadsafe at present (uses filesystem in a way that doesn't interact well)

Allow disabling of mutlithreading in simd op check

---

src/runtime/HalideRuntime.h

Upstreaming debian patch.
See https://github.com/halide/Halide/issues/7678

clang does not support `_Float16` when targeting i386

---

test/correctness/float16_t.cpp

```
[2336/4154] /usr/bin/clang++-17 -DHALIDE_ENABLE_RTTI -DHALIDE_VERSION_MAJOR=17 -DHALIDE_VERSION_MINOR=0 -DHALIDE_VERSION_PATCH=0 -DHALIDE_WITH_EXCEPTIONS -I/build/halide-17.0.0/test/common -I/build/halide-17.0.0/tools -I/build/halide-17.0.0/build/stage-1/halide/include -g -fdebug-default-version=4 -fprofile-use=/build/halide-17.0.0/build-profile/default.profdata -fcs-profile-generate -Xclang -mllvm -Xclang -vp-counters-per-site=100.0 -fuse-ld=lld-17 -Wl,--build-id=sha1 -std=c++17 -flto=thin -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -Winvalid-pch -Xclang -include-pch -Xclang /build/halide-17.0.0/build/stage-1/halide/test/CMakeFiles/_test_internal.dir/cmake_pch.hxx.pch -Xclang -include -Xclang /build/halide-17.0.0/build/stage-1/halide/test/CMakeFiles/_test_internal.dir/cmake_ …
```

tests: correctness/float16_t: mark `__extendhfsf2` with default visibility

---

src/runtime/internal/block_allocator.h
src/runtime/internal/memory_arena.h
src/runtime/internal/memory_resources.h
src/runtime/internal/region_allocator.h
src/runtime/vulkan_memory.h
test/runtime/block_allocator.cpp

As reported by https://github.com/halide/Halide/issues/8079
+ Add region allocator tests that check alignment, nearest_multiple and collect routines
+ Fix can_split() routine to use conformed sizes so that split allocation matches
+ Fix region size accounting so that coalesce never has zero size regions to merge
+ Fix aligned_offset() routine to check for zero alignment (which means no constraint)
+ Use Vulkan memory_requirements to determine nearest_multiple during initialization
+ Query Vulkan memory_requirements for each region, and reallocate if driver requires additional device memory

[Vulkan] Region allocator fixes for memory requirements and allocations

---

dependencies/wasm/CMakeLists.txt

Found while debugging macbot 3

Ensure string(REPLACE) is called with the right number of arguments

---

Makefile
src/AddImageChecks.cpp
src/CMakeLists.txt
src/Lower.cpp
src/ScheduleFunctions.cpp
src/StripAsserts.cpp
src/StripAsserts.h

The simplifier exploits asserts to make simplifications. When compiling with NoAsserts, certain assertions aren't ever introduced, which means that the simplifier can't exploit certain things that we know to be true. Mostly this has a negative effect on code size. E.g. tail cases get generated even though they are actually dead code.
This PR keeps all the assertions right until the end of lowering, when it strips them in a dedicated pass.
This reduces object file size for a large production blob of Halide code by ~10%, without measurably affecting runtime.

Strip asserts right at the end of lowering

---

src/FindIntrinsics.cpp
test/correctness/intrinsics.cpp

When bool types are used with e.g. widening_mul, the compiler asserts in Type::narrow as bools cannot be narrowed. This situation did not arise from user code doing this directly, but rather through some chain of lowering with float16 types. The test cases added to correctness_intrinsics exercise the issue directly. They do fail without the fix.
I did not add broader coverage for bool types and intrinsics as it would require more thinking. Most of them overflow for the true/true case and thus are of questionable use, however widening operations cannot overflow... Certainly we could define the language to forbid this, but currently the frontend does not do so. As indicated above, the use case driving this was not using bool arithmetic to begin with.

Fix an issue where the Halide compiler hits an internal error for bool types in widening intrinsics.

---

src/CodeGen_Xtensa_prologue.template.cpp
src/CodeGen_Xtensa_vectors.template.cpp

Prologue update is needed when no add_vector_typedefs are added, i.e., when no funcs are vectorized in a kernel

[xtensa] added vector extracts for floats + moved float16 and int48

---

src/Lower.cpp

I've been copy-pasting this from branch to branch, but I should just check it in. This is useful for performance optimization of the compiler itself.

Optionally print the time taken by each lowering pass

---

src/UnpackBuffers.cpp

We were redundantly creating a handle Variable every time we encountered something like foo.stride.0, instead of just the first time we encounter a Variable that refers to an input Parameter/Buffer.
Speeds up this already-fast lowering pass by 10% or so. No measurable impact on total lowering time.

Do less redundant work in UnpackBuffers

---

src/AsyncProducers.cpp
src/Lower.cpp

We were making a very large number stmt_uses_vars queries that covered the same sub-stmts. I solved it by adding a cache.
Speeds up local laplacian lowering by 10% by basically removing this pass from the profile.
Also a drive-by typo fix in Lower.cpp

Use a caching version of stmt_uses_vars in TightenProducerConsumer nodes

---

src/StorageFlattening.cpp
test/correctness/skip_stages.cpp

The allocation condition wasn't getting relaxed over the scope and loop vars like the extents were.
This fix is included in the rewrite_skip_stages PR, but it's a bug on main, so I'm opening it as a fresh PR on main in case the other branch gets stalled.

Fix hoist_storage not handling condition correctly.

---

src/runtime/HalideBuffer.h
test/correctness/halide_buffer.cpp

This uses `static inline` to use inline linkage, as suggested by @abadams, to deduplicate upon link time the storage of the struct holding the two function pointers.
**Outdated:**
>  Additionally, the struct is templated and parameterized over the `Runtime::Buffer` template argument to make sure that the storage is unique to the `Buffer<void>` struct (and thus does not gets linked in for every type/dim combo of `Buffer`.
> 
> One option is to change the setters from this:
> ```cpp
>     static void set_default_allocate_fn(void *(*allocate_fn)(size_t)) {
>         Buffer<>::default_allocator_fns.default_allocate_fn = allocate_fn;
>     }
>     static void set_default_deallocate_fn(void (*deallocate_fn)(void *)) {
>         Buffer<>::default_allocator_fns.default_deallocate_fn = …
```

Add support for setting the default allocator and deallocator functions in Halide::Runtime::Buffer.

---

src/CanonicalizeGPUVars.cpp
src/CanonicalizeGPUVars.h
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_GPU_Dev.cpp
src/CodeGen_GPU_Dev.h
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_PTX_Dev.cpp
src/CodeGen_Vulkan_Dev.cpp
src/CodeGen_WebGPU_Dev.cpp
src/DeviceArgument.cpp
src/Expr.cpp
src/Expr.h
src/FuseGPUThreadLoops.cpp
src/OffloadGPULoops.cpp
src/PartitionLoops.cpp
src/TrimNoOps.cpp
test/correctness/fuse_gpu_threads.cpp

This is one of our largest remaining type of magic name. These were explicitly constructed in lots of places and then explicitly checked for with ends_with in lots of places.
This PR makes the names opaque. Only CanonicalizeGPUVars.cpp knows what they are, and they don't have to be a single fixed thing as long as they're consistent within a process.
Also reduced the number of GPU dimensions to three more uniformly. We were already asserting this, but there was lots of dead code in lowering passes after gpu loop validation that allowed for four.
Also fixed a bug I found in is_block_uniform. It didn't consider that the dependence on a gpu thread variable in a load index could be because a let variable encountered depends on a gpu thread variable.

Make gpu thread and block for loop names opaque

---

src/runtime/internal/block_allocator.h
src/runtime/internal/memory_resources.h
src/runtime/internal/region_allocator.h
src/runtime/vulkan_memory.h
test/runtime/block_allocator.cpp

As reported in https://github.com/halide/Halide/issues/8079 ...
Vulkan's API permits any arbitrary alignment and padding on every Buffer allocation, which means that the memory requirements have to be queried for every block and region prior to binding device memory.
Previously, we were only querying the requirements on the creation of the block, and assuming that all regions (which used the same device memory pool, and physical allocation) would match.  This was an invalid assumption, and was only partially fixed in https://github.com/halide/Halide/pull/8087.
This PR introduces a new `conform` callback API which allows block and region allocations to query the memory requirements before the block allocator actually binds memory and creates/splits regions.
I also added more test cases in …

[vulkan] Add conform API methods to memory allocator to fix block allocations

---

apps/hexagon_benchmarks/CMakeLists.txt
apps/hexagon_benchmarks/process.cpp
src/HexagonOptimize.cpp

Adding sobel test back which was removed in PR #8069.  
Previously, `sobel` test was not building correctly with the target `host-hvx`. The compilation errors were caused by the eliminate interleave pass, which changed the instruction from `halide.hexagon.pack_satub.vuh` to `halide.hexagon.trunc_satub.vuh`. The latter instruction is only available in `v65` or later and `host-hvx` by default is `v62`. This commit ensures compatibility with v65 and later versions.

Add sobel in hexagon benchmarks app for CMake builds

---

apps/onnx/Makefile

One of the buildbots has gotten itself into a weird state where python-config is from python 3.12, but the python used in the venv is python 3.11, so the extension suffix on the python module in the onnx app is wrong.
virtual envs don't seem to include python-config, so rather than mess with the system this PR just changes the makefile to get the extension suffix from python itself.

Use python itself to get the extension suffix, not python-config

---

src/Deserialization.cpp
src/Func.cpp
src/Func.h
src/Function.cpp
src/Function.h
src/Lower.cpp
src/Profiling.cpp
src/Profiling.h
src/Serialization.cpp
src/halide_ir.fbs

Replaces #8136 with a cleaner implementation.
@abadams I took your suggestion, and this implementation is much better. Very small changes, and the issue I reported in the previous one is gone. The trick with the "environment" was a good lesson!
Additionally, I managed to also clean up the report by having the stack-allocated `Allocate`/`Free` nodes also have their allocation contribute to the enclosing `Func`. Doing that changed my profiling report from (`w_0`, `w_1`, `w_2`, `max_channel`, `lum`, `lum_pow3`, `r`, `g`, `b` all marked with `no_profiling()`, but still producing lines in the report):
```
neonraw_highlight_ratio_extractor
total time: 1338.695068 ms  samples: 1262  runs: 48  time/run: 27.889481 ms
average threads used: 2.657686
heap allocations: 0  peak heap usage: 0 bytes …
```

Feature: mark a Func as no_profiling, to prevent injection of profiling. (2nd implementation)

---

src/CodeGen_ARM.cpp
src/IRMatch.cpp
test/correctness/simd_op_check_arm.cpp

This change fixes the only regression from main I could find in the sve branch, and improves things on top of that.

Add support for fcvtm/p, make scalars go through pattern matching too

---

src/StorageFlattening.cpp
test/correctness/hoist_storage.cpp

This is a fix for #8141. 
As described there, the problem is that ```bound_of_expr_in_scope``` is not recursive: when the storage is hoisted, the allocation extents may depend on the loop variables, so we find a maximum bound for them using ```bound_of_expr_in_scope``` and the scope which has intervals for each of the loop variables. However, the loop variables themselves may depend on the other loop variables in which case the extent still may refer to loop variables even after calling ```bound_of_expr_in_scope```.
The fix is to apply ```bound_of_expr_in_scope``` for each loop variable separately in a reverse order. I wasn't sure if there is a more efficient way to achieve this, but hopefully it isn't so bad, because allocation extents are usually pretty small.

Bound allocation extents for hoist_storage using loop variables one-by-one

---

src/ScheduleFunctions.cpp
test/correctness/compute_with.cpp

This PR fixes a bug in compute_with, and another bug I found while fixing it (we could really use a compute_with fuzzer).
The first bug is that you can get into situations where the bounds of a producer func will refer directly to the loop variable of a consumer func, where the consumer is in a compute_with fused group. In main, that loop variable may not be defined because fused loop names have been rewritten to include the token ".fused.". This PR adds let stmts to define it just inside the fused loop body.
The second bug is that not all parent loops in compute_with fused groups were having their bounds expanded to cover the region to be computed of all children, because the logic for deciding which loops to expand only considered the non-specialized pure definition. So e.g. …

Fix two compute_with bugs.

---

src/FindIntrinsics.cpp
test/correctness/intrinsics.cpp

This is the implementation of lower_rounding_shift_right on main:
```
Expr lower_rounding_shift_right(const Expr &a, const Expr &b) {
if (is_positive_const(b)) {
...
}
// Shift right, then add one to the result if bits were dropped
// (because b > 0) and the most significant dropped bit was a one.
Expr b_positive = select(b > 0, make_one(a.type()), make_zero(a.type()));
return simplify((a >> b) + (b_positive & (a >> (b - 1))));
}
```
Consider `lower_rounding_shift_right(a, (uint8)0)`
The term b - 1 becomes 255, and now you have an out-of-range shift,
which causes the simplifier to inject a signed_integer_overflow
intrinsic, and compilation to fail.
This is a little annoying because if b == 0, b_positive is a zero mask,
so the result isn't used anyway (this is also why this change is …

fix ub in lower rounding shift right

---

dependencies/llvm/CMakeLists.txt
src/Bounds.cpp

This PR does four things:
- Drive-by update of error message regarding LLVM version.
- Tightens bounds of `abs()` on an expression that is strictly positive
- Tightens bounds of `abs()` on an ~~int32/int64~~ expression that is strictly negative
- Fixes horrendous upper bound overflow on `abs()` of an int32/int64 that could be negative. (move cast outside of the max).
~~I am struggling to come up with the right lower bound that tightens the interval for `abs()` of a strictly negative thing that is a smaller integer type, because `-a.max` could overflow.~~
Update: figured out the right expression for tightening bounds without negating something that could overflow. (updated z3 example as well)
Also, new bounds are formally verified via z3:
```
import z3
abs = lambda x: z3.If(x > 0, x, 0 - …
```

Tighten bounds of abs()

---

src/IR.h
src/IROperator.cpp
src/IRPrinter.cpp

I was poking at the Shuffle node, and checking its usage, and it seems that despite the comment, Shuffles that return true for is_broadcast are not the same as Broadcast nodes. Instead of repeating the input vector some number of times, it repeats a shuffle of the input vector. This means IRPrinter was incorrect. The other usages were fine.
This PR makes this clearer in the comment, and fixes IRPrinter.

Clarify the meaning of Shuffle::is_broadcast()

---

src/FindCalls.cpp

I was compiling with gcc-7, which reported this.
The build was successful after this one change.

Fix unused variable.

---

README.md

Addresses #8181 . 
The PR updates the Qualcomm Hexagon installation instructions.

Update Hexagon Install Instructions

---

src/LowerParallelTasks.cpp

Opened for discussion, because presumably this was added for a reason.
Fixes #8184

Don't print on parallel task entry/exit with -debug flag

---

src/Simplify_Call.cpp

Fixes the segfault reported in #8170 
I have no idea how to repro this in a test. It came about as a result of applying the adams autoscheduler to an hvx pipeline, which produced a schedule with vectors wider than tiles, which turned into predication, which was then turned into something invalid inside the hexagon lowering path.
The if_then_else intrinsic is supposed to evaluate to zero if the condition is false and there's no false value defined.

Fix corner case in if_then_else simplification

---

src/ModulusRemainder.cpp

A default-constructed ModulusRemainder means no information, which is what we want here. ModulusRemainder{0, 1} means the constant one!

Fix give-up case in ModulusRemainder

---

src/Simplify_Sub.cpp

Massively reduces compile time and peak cl.exe memory consumption on windows (from 9.5gb down to 2.3gb).
Simplify_LT.cpp has these same EVAL_IN_LAMBDAs, which is probably why it hasn't been causing build problems.

Add some EVAL_IN_LAMBDAs to Simplify_Sub.cpp

---

python_bindings/src/halide/halide_/PyEnums.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/HexagonOffload.cpp
src/HexagonOptimize.cpp
src/LLVM_Runtime_Linker.cpp
src/Target.cpp
src/Target.h
src/runtime/HalideRuntime.h
test/correctness/gather.cpp
test/correctness/hexagon_scatter.cpp
test/correctness/histogram.cpp
test/correctness/simd_op_check_hvx.cpp

Hexagon v68 or later support floating-point HVX instruction.   This CL add a new HVX_v68 target to enable code generation for floating-point HVX instruction.

Add HVX_v68 target to support Hexagon HVX v68.

---

src/runtime/HalideRuntime.h

Lost quite some time, because I needed `set_host_dirty()` instead of `host_dirty()`.

Mark host_dirty() and device_dirty() with no_discard.

---

src/autoschedulers/anderson2021/LoopNest.cpp

Remove max size assert from Anderson2021

---

python_bindings/src/halide/halide_/PyType.cpp

There are two parts to support for BFloat16 in Python:
1) Ability to define kernels and AOT compile them [fixed in this PR] 
2) Ability to call kernels from Python
This fixes part 1, which is what I need for my use case.  Part 2 is blocked on bfloat16 support in Python buffer protocols. See #6849 for more details.

Expose BFloat in Python bindings

---

src/CodeGen_Metal_Dev.cpp
test/correctness/CMakeLists.txt
test/correctness/gpu_f16_intrinsics.cpp

This adds support for Metal to correctly handle float16 literals.  Fixes #8245.

Fix Metal handling for float16 literals

---

python_bindings/src/halide/halide_/PyExpr.cpp
python_bindings/test/correctness/basics.py

This makes >32bit python integers get mapped to `hl.i64` implicitly.
Fixes #8224

Python binding support for int64 literals

---

src/IROperator.cpp
src/IRPrinter.cpp
src/IRPrinter.h

[unsafe_]promise_clamped is sort of broken in a subtle way, which I didn't fix in this PR. I didn't change its functionality, but instead of an `internal_assert()` triggering, now a useful user error is reported, which allows the user to fix it. This behavior is better than crashing IMO.
The problem is when you for example call: `unsafe_promise_clamped(<uint16_t>, 0, <Variable int32_t>)`.
I ran into the situation where I naturally would start from:
```cpp
counter_output_buf(i) = undef<int32_t>();
counter_output_buf(index_func(rdom)) += 1;
```
Where counter_output_buf (a `GeneratorOutput<Buffer<int32_t>>`) counts the amount of times a certain index is observed in `index_func`. However, `index_func` is `uint16_t` in my case.
But want to promise that the index I have is within bounds of the …

Report useful error to user if the promise_clamp all fails to losslessly cast.

---

src/Simplify_Add.cpp
src/Simplify_Min.cpp
test/correctness/simplify.cpp

Fixes #8227 but may break other things. Needs thorough testing.
Also, there are more rules like this lurking.

It's generally a bad idea for simplifier rules to multiply constants

---

src/CodeGen_C.cpp
src/CodeGen_Vulkan_Dev.cpp

Previous refactoring accidentally used the fully qualified var name rather than the categorized vulkan intrinsic name.
See also #8258.

[vulkan] Fix Vulkan SIMT mappings for GPU loop vars. 

---

src/IROperator.cpp

The full fix to lossless_cast is too complicated to backport

Backport a fix for the simpler bug in lossless_cast

---

src/RegionCosts.cpp

Now by default it will treat them as cost one, unless you tell it otherwise.

Stop region costs from complaining about new intrinsics

---

src/CodeGen_Xtensa.cpp
src/XtensaOptimize.cpp
test/correctness/simd_op_check_xtensa.cpp

This is to avoid int32->int64->int32 path for a saturated cast of widening shift right

[xtensa] Added a new optimize rule

---

src/runtime/HalideRuntimeMetal.h
src/runtime/metal.cpp
test/correctness/CMakeLists.txt
test/correctness/gpu_metal_completion_handler_error_check.cpp
test/generator/CMakeLists.txt
test/generator/metal_completion_handler_override_aottest.cpp
test/generator/metal_completion_handler_override_generator.cpp

As discussed in the dev meeting, here is an alternative approach for fixing #7780.  Now, the runtime saves an error during the callback from a failed command buffer, and reports the error back at the next opportunity for reporting.  Note that this means that a pipeline may get an error that should be attributed to the previous pipeline, but additional error information can be added (e.g. prepending the error message with the name of the kernel that caused it) if wanted.

No longer silently hide errors in Metal completion handlers (alternative approach)

---

src/Simplify_Stmts.cpp

scoped_truth for the loop variable being always less than the loop extent.

---

src/CodeGen_C.cpp
src/CodeGen_Vulkan_Dev.cpp
src/runtime/internal/block_allocator.h
src/runtime/internal/memory_arena.h
src/runtime/internal/memory_resources.h
src/runtime/internal/region_allocator.h
src/runtime/vulkan_memory.h
test/runtime/block_allocator.cpp

* Fix Vulkan SIMT mappings for GPU loop vars. Previous refactoring accidentally used the fully qualified var name rather than the categorized vulkan intrinsic name.
* Avoid formatting the GPU kernel to a string for Vulkan (since it's binary SPIR-V needs to remain intact).

Backport #8259 to release/17.x

---

src/runtime/HalideBuffer.h
test/correctness/device_slice.cpp

The device-slicing logic was broken on the C++ level, due to the fact that the buffer device-refcount for crops and slices assumes it was cropped/sliced from a buffer with an equal number of dimensions. This is incorrect for both cropping AND slicing:
- slicing from a buffer reduces the dimensionality (this is obvious)
- cropping from a sliced buffer inherits the "cropped_from" field from the sliced Buffer, which which has a higher dimensionality.
This was never tested for in the tests as they were all done with variable number of dimensions (i.e., `AnyDims`). Thus, I added a test that does a device slice on a `Buffer<int, 3>`.
The solution is to store that "cropped_from" Buffer as a generic `Buffer<T, AnyDims>`.

Fix device slices for Buffer with fixed dimensionality in template.

---

python_bindings/src/halide/halide_/PyIROperator.cpp
src/IROperator.h

tuple_select and the Internal versions of various fixed-point helpers were deprecated in Halide 17; we should remove them entirely for Halide 18.

Remove deprecated operators

---

src/LLVM_Runtime_Linker.cpp

This gives LLVM enough information to generate a "platform load-command" in the MachO object file.
Frustratingly, there is not a simple API that sets this directly; it _must_ be passed in the os name.
Fixes #7941

Provide a minimum OS version for MachO objects

---

src/DerivativeUtils.cpp

Consider *all* Exprs a func uses, not just the RHS, in Li2018

---

python_bindings/tutorial/lesson_05_scheduling_1.py

This is column-major so y should vary faster than x.
The equivalent c++ code:
https://github.com/halide/Halide/blob/a6f5ca4b34d78362ea703dcbaad5bd527efd9fb3/tutorial/lesson_05_scheduling_1.cpp#L97-L101

Fix tutorial

---

src/Profiling.cpp
test/correctness/CMakeLists.txt
test/correctness/gpu_alloc_group_profiling.cpp

When --for some reason-- an allocation group for fused storage for multiple `Func`s that originally are intended to go in `GPUShared` gets lifted out of the GPU-block loops, and sits in `Heap` memory instead, the profiling injection logic assumed that this buffer came from a function with the same name. This buffer was incorrectly determined to be on the stack, as it ignored the `custom_new` and `custom_free` attributes of the `Allocate` node.
Consider this example (also included as a new test):
```cpp
#include "Halide.h"
using namespace Halide;
int main(int argc, char *argv[]) {
Target t = get_jit_target_from_environment();
if (!t.has_gpu_feature()) {
printf("[SKIP] GPU not enabled\n");
return 0;
}
Var x{"x"}, y{"y"};
Func f1{"f1"}, f2{"f2"};
f1(x, y) = cast<float>(x + y);
f2(x, y) = …
```

Fix injection of GPU buffers that do not go by a Func name (i.e. alloc groups).

---

python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyPipeline.cpp
src/Func.cpp
src/Func.h
src/Pipeline.cpp
src/Pipeline.h
src/StmtToHTML.cpp
src/irvisualizer/generate_palettes.py
src/irvisualizer/html_template_StmtToHTML.css
src/irvisualizer/html_template_StmtToHTML.js
src/irvisualizer/html_template_StmtToHTML_dependencies.html

Colorscheme based on gruvbox-material.
[![image](https://github.com/halide/Halide/assets/845012/59956313-09e8-4039-b81f-b266c40c890b)](https://github.com/halide/Halide/assets/845012/be572828-5ddc-4f15-842d-9e0577b5029f)
Also improved assembly syntax highlighting (while reducing one HTTP fetch, as the highlight rules are now embedded in the generated file.).

Adaptive Dark colorscheme for Stmt HTML. Ability to programmatically export conceptual stmt files.

---

Makefile
src/LLVM_Runtime_Linker.cpp
src/Target.cpp
src/Type.cpp
src/Util.cpp
src/runtime/CMakeLists.txt
src/runtime/aarch64_cpu_features.cpp
src/runtime/arm_cpu_features.cpp
src/runtime/linux_aarch64_cpu_features.cpp
src/runtime/linux_arm_cpu_features.cpp
src/runtime/osx_aarch64_cpu_features.cpp
src/runtime/osx_arm_cpu_features.cpp
src/runtime/windows_aarch64_cpu_features_arm.cpp
tutorial/lesson_15_generators_usage.sh

Adds feature detection for ARM CPUs to the runtime library and to the host target feature computation. Supports Windows, macOS, Linux, iOS, and Android.
Also fix bug in Type::max() and Type::min() for float16.
Fixes #4727
Fixes #6106
Fixes #7901
Fixes #7979
Fixes #8340

Detect ARM CPU features for host target and in runtime (Backport to release/18.x)

---

Makefile
src/CodeGen_ARM.cpp
src/CodeGen_RISCV.cpp
src/JITModule.cpp
src/LLVM_Headers.h
src/LLVM_Output.cpp
src/LLVM_Runtime_Linker.cpp
src/WasmExecutor.cpp
test/correctness/simd_op_check_riscv.cpp
test/correctness/simd_op_check_sve2.cpp

Per policy, Halide 19 will support LLVM 17, 18, 19 (plus top-of-tree which is 20)

Drop support for LLVM 16 in main

---

python_bindings/CMakeLists.txt

Support not building python bindings, while running python tests against installed halide, and call `enable_testing()` there so that `ctest` can work.
Extracted from pending debian package changes.

`Python_bindings`-test-as-installed

---

CMakeLists.txt

We haven't supported building with Clang 12 or below in a _long_ time. No need to keep this in our build.

Remove warning for unsupported compilers

---

python_bindings/src/halide/halide_/PyHalide.cpp
python_bindings/stub/PyStubImpl.cpp

Concretely:
https://github.com/pybind/pybind11/blob/48f25275c44d52d0ceade122e328dc1f2e48ef44/include/pybind11/detail/common.h#L12-L14
This is needed for a Google-internal deployment, but is a useful fix regardless.

Make pybind11 minimum version check compatible with pybind11 v3.

---

CMakeLists.txt
apps/cuda_mat_mul/CMakeLists.txt
cmake/FindHalide.cmake
dependencies/wasm/CMakeLists.txt
python_bindings/src/halide/CMakeLists.txt
python_bindings/stub/CMakeLists.txt
src/CMakeLists.txt

Trying to carve out pieces of #8360 that are easy to review/land individually. Here are a few quick fixes:
1. A few inconsistent-formatting tweaks, improved comments
2. Using the package-redirects feature to disable in-tree `find_package(Halide)`, rather than polluting our source tree with a dummy file.
3. Replacing another dummy file in the Python bindings with a better cmake -E command
4. Using `find_package(CUDAToolkit)` in apps/cuda_mat_mul
5. Add `SpirvIR.h` to the list of _sources_, not public headers. This won't put it in `Halide.h`, but it will put it in IDE file lists.
6. Use `BUILD_LOCAL_INTERFACE` instead of `BUILD_INTERFACE` (this is even more private)

Quick CMake fixes enabled by 3.28

---

apps/hexagon_benchmarks/CMakeLists.txt
cmake/HalideGeneratorHelpers.cmake
cmake/MutexCopy.ps1
packaging/CMakeLists.txt
tools/CMakeLists.txt

This changes the distribution method of GenGen from distributing a `.cpp` file along with our sources to a static library that should be linked via `--whole-archive` or equivalent.
**Why didn't we do this before?**
Prior to CMake 3.24, there was no way to force a static library to be whole-archive linked. Now it's possible.
**What benefit does it confer?**
We don't have to compile GenGen.cpp so many times!
**Why can't we do this with RunGenMain?**
We know that GenGen will always be compiled for the same platform as libHalide; after all, it links to it. We can't say the same for RunGenMain, which might get baked into a cross compile.
---
This PR uncovered a race condition in the generator logic. Two generators in the same directory could try (via a `POST_BUILD` custom command) to place …

Distribute GenGen as a static library

---

packaging/CMakeLists.txt
src/CMakeLists.txt
src/autoschedulers/adams2019/CMakeLists.txt
src/autoschedulers/anderson2021/CMakeLists.txt
src/autoschedulers/common/CMakeLists.txt
src/autoschedulers/li2018/CMakeLists.txt
src/autoschedulers/mullapudi2016/CMakeLists.txt
src/runtime/CMakeLists.txt
test/generator/CMakeLists.txt
tools/CMakeLists.txt

Removes instances of `target_include_directories` and installation rules based on those directories. These are now automatically computed from the `BASE_DIRS` (defaults to current source dir) argument to `target_sources`.
This models the build more accurately and avoids accidental installation of unwanted headers. Also forces us to think about the linking relationships between components; ideally this will result in a more accurate build graph.

List headers with target_sources FILE_SETS

---

src/autoschedulers/adams2019/CMakeLists.txt
src/autoschedulers/anderson2021/CMakeLists.txt

After #8370 the `Halide::Plugin` target covers the common autoscheduler code.

Clean up autoscheduler dependencies

---

README_webassembly.md
cmake/FindV8.cmake
dependencies/wasm/CMakeLists.txt
src/CMakeLists.txt

This also adjusts the cache variable names to follow the conventions set forth in the CMake documentation, here:
https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#standard-variable-names

Use a Find module for V8

---

cmake/FindNodeJS.cmake
dependencies/wasm/CMakeLists.txt

Also renames `NODE_JS_EXECUTABLE` to `NodeJS_EXECUTABLE` with a deprecation warning.

Use a Find module for NodeJS

---

CMakeLists.txt
cmake/dependencies.cmake
packaging/CMakeLists.txt
python_bindings/CMakeLists.txt
src/CMakeLists.txt

This is the first _big_ change from #8360 
The build no longer uses `FetchContent`, instead using `find_package` always and everywhere. When Halide is the top-level project, it will (by default) inject a _dependency provider_ that overrides the `wabt`, `flatbuffers`, and `pybind11` packages with `FetchContent`. Users can opt-out by setting `Halide_USE_FETCHCONTENT=NO`.
This also bumps the required `wabt` version to the latest release (1.0.36). This version includes a patch I submitted that fixes the CMake package when `wabt` is built with OpenSSL rather than picosha2.
---
Here are relevant links to the docs:
* https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#dependency-providers
* https://cmake.org/cmake/help/latest/command/cmake_language.html#dependency-providers

Replace FetchContent with a custom dependency provider

---

src/runtime/HalideRuntime.h
test/integration/CMakeLists.txt

Without `CXX` propagation, there isn't really any way to test with any but default compiler.
In fact, that happened to be GCC, and on i386 the test didn't pass, even though the package built,
because it was built with clang. The second patch addresses the GCC failure on i386,
but there are more issues on other architectures i strongly suspect.

Two more build fixes

---

python_bindings/tutorial/lesson_10_aot_compilation_run.py

Fix Numpy 2.0 compatibility bug in lesson 10
Numpy 2.0 no longer performs narrowing conversions
automatically. We manually mask here instead.
Fixes #8380

Fix Numpy 2.0 compatibility bug in lesson 10

---

src/CMakeLists.txt

1. Move core features closer to Halide library definition.
2. Move target export script to its own section.
3. Group LLVM backends and GPU backends together.
The next four PRs are all real/functional, I promise.

Reflow src/CMakeLists.txt in logical groups

---

CMakeLists.txt
README_cmake.md
cmake/HalideFeatures.cmake
packaging/CMakeLists.txt
python_bindings/apps/CMakeLists.txt
python_bindings/test/CMakeLists.txt
src/CMakeLists.txt
src/runtime/CMakeLists.txt
test/CMakeLists.txt
test/generator/CMakeLists.txt

Previously, our `option()` declarations were scattered and not well documented. They certainly weren't self-documenting. Some of them depended on other options and used various ways to handle conflicts. Sometimes inconsistencies were handled with fatal errors, other times by silently overriding an option.
With this PR, I introduce a new `Halide_feature` function that is designed to handle interdependent options and default initialization in a much more regular way.
It behaves very much like option in its first three parameters:
```cmake
Halide_feature(CMAKE_FLAG "documentation string" DEFAULT_VALUE)
```
Only now `DEFAULT_VALUE` can be more intelligent than simply `ON` or `OFF`. It can also be `TOP_LEVEL`, which is `ON` iff `CMAKE_PROJECT_TOP_LEVEL` is true. It can also be `AUTO` which is …

Introduce HalideFeatures system for optional components

---

CMakeLists.txt
cmake/HalidePackageConfigHelpers.cmake
packaging/CMakeLists.txt
src/CMakeLists.txt

This module contains a system for declaring that an export file might depend on another CMake package that was found by find_package. Such dependencies are collected in a project-wide property (rather than a variable) along with a snippet of code that reconstructs the original call.
Then, after we have installed an export file via install(EXPORT), we can call a helper to add install rules that will read the file as-generated by CMake to check whether any of these packages could be required.
CMake does not like to expose this information, in part because generator expressions make computing the eventual link set undecidable. Even so, for our purposes if `Pkg::` appears in our link-libraries list, then we need to find_package(Pkg).
This module implements that heuristic.
So why is this hard? …

Scan generated export files to determine dependencies.

---

CMakeLists.txt
CMakePresets.json
README_cmake.md
cmake/BundleStatic.cmake
src/CMakeLists.txt

The `bundle_static` function now detects the private static dependencies on the given target (in our case, always Halide) and uses the platform librarian tool to merge static dependencies into a static library. It picks which tool to use by checking, in order:
* When targeting Windows, it looks for `lib.exe`.
* When targeting macOS, it checks if `libtool` is the Apple libtool.
* Whether `ar` is GNU ar and if so, generates an MRI script.
* Otherwise, a `FATAL_ERROR` is issued.
To mark a static library for bundling, we link privately and use the `$<BUILD_LOCAL_INTERFACE:...>` generator expression. This prevents it from being exported, too.
With this PR, imported static dependencies besides LLVM (wabt, flatbuffers) can be bundled, too. Previously, they were only bundled when vendored via …

Rewrite bundle_static to be much more efficient.

---

.gitignore
CMakeLists.txt
CMakePresets.json
cmake/vcpkg/llvm/portfile.cmake
cmake/vcpkg/llvm/vcpkg.json
cmake/vcpkg/python3/portfile.cmake
cmake/vcpkg/python3/vcpkg.json
vcpkg.json

This PR adds support for using vcpkg to acquire and build Halide's dependencies on all platforms.
It adds a top-level `vcpkg.json` file that explains the relationship between Halide's features and its dependencies. These features include the various LLVM `target-`s (which merely imply a dependency on the corresponding LLVM backend), `serialization` (flatbuffers), the `python-bindings` (pybind11), the `wasm-executor` (wabt), and a few meta-features:
* `jit`: enables LLVM targets corresponding to the host system
* `target-all`: enables all LLVM targets
* `tests`: depends on everything needed for the tests and apps
* `developer`: includes all other features
All of these are optional (since x86 and WebAssembly are forced), but `jit` and `serialization` are on by default.
vcpkg is intended to …

Support using vcpkg to build dependencies on all platforms

---

src/CodeGen_LLVM.cpp

This fixes the latest change in LLVM where the `DataLayout` constructor that accepts a `Module` is removed. https://github.com/llvm/llvm-project/commit/75c7bca740935a0cca462e28475dd6b046a6872c
CC @steven-johnson

Fix for the removed DataLayout constructor.

---

cmake/BundleStatic.cmake

LLVM as it is built on the buildbots depends on `-lrt`, which is not a target. Filter out non-target dependencies from consideration.
Skipping buildbots because this code is not tested by the PR workflows.

Fix bundling error on buildbots

---

src/runtime/HalideRuntime.h

GCC 12 only supports `_Float16` on x86. Support for ARM was added in GCC 13. This causes a build failure in the `manylinux_2_28` images.
[See Godbolt output here](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAMwArKSuADJ4DJgAcj4ARpjEegAOqAqETgwe3r4BwSlpjgLhkTEs8Ylctpj2hQxCBEzEBFk%2BfkFVNRn1jQTF0XEJegoNTS057cM9faXlEgCUtqhexMjsHAD6AGK0qEwEXABsANQsTADWmOsAXgmoEHNHJgDsFkfEmATLDEcaJv6vzwAIhwFrROIFeH5uLxUJw3NZrEcFEsVphHmZ/DxSARNCCFmcQIEuAA6A4YswATg0AA5JFwuBSzNIwRxJJDcaRYRxeAoQBpsbiFnBYDBEChUCwknQEuRKGhJdLEo0WAdJMAuJj%2BTRaAQEryILEObEIo0AJ6cLHG5jEU0AeVi2kwDgtvHlbEEtoYtHNHC0pCwsS8wDcYlovOh/swpyM4l9vHw7wceAAbphw37MKonV5dS7yIJqhzaHhYsQzR4sByCMQ8Cw86niLFUphAVHDMBi0ZBXwDMAFAA1PCYADut …

Fix _Float16 detection on ARM64 GCC<13

---

README.md
doc/HalideCMakePackage.md
python_bindings/src/halide/__init__.py

Adds a function `install_dir()` to the Python package to aid other build systems in finding the Halide install root.
Documents how to find Halide using CMake from the pip package, too.

Document how to find Halide from a pip installation

---

pyproject.toml

PyPI rejected this because of a spacing issue. Whee. Wish something would have caught this while building the wheel...

Fix classifier spelling

---

.github/workflows/presubmit.yml
run-clang-format.sh
run-clang-tidy.sh

The run-clang-tidy.sh script was written to be Linux-only. This PR extends support to macOS
Also updates the GHA runner to run the checks when the script changes and to use macos-14, which is beefier than the Ubuntu runners.

Make run-clang-tidy.sh work on macOS

---

src/MainPage.h

Add links to PyPI from the Doxygen index.html [to mark this link as Verified on PyPI](https://docs.pypi.org/project_metadata/#self-links).
Very open to suggestions for alternate copy.

Link to PyPI from Doxygen index.html

---

test/performance/matrix_multiplication.cpp

Someone was using this as a reference expert schedule, but it was stale and a bit simplistic for large matrices. I rescheduled it to get a better fraction of peak. This also now demonstrates how to use rfactor to block an sgemm over the k axis.

Reschedule the matrix multiply performance app

---

src/runtime/d3d12compute.cpp
src/runtime/runtime_atomics.h

First is just a requirement that a template be declared before use. Second is removing volatile from non-reference return types.

Some minor fixes for C++23 compilation errors.

---

src/Derivative.cpp
src/runtime/HalideBuffer.h

The cast is nasty and reinterprets the datatype template argument `T`. Simply casting that no longer works without a warning. 
https://github.com/halide/Halide/blob/e55bd6f42bcfc0420adc393c29bf052a7609e041/src/runtime/HalideBuffer.h#L1432-L1454
Being explicit about this silences the compiler.
```
/home/martijn/zec/3rd/Halide/src/runtime/HalideBuffer.h: In instantiation of ‘void Halide::Runtime::Buffer<T, Dims, InClassDimStorage>::copy_from(Halide::Runtime::Buffer<T2, D2, S2>) [with T2 = void; int D2 = -1; int S2 = 4; T = void; int Dims = -1; int InClassDimStorage = 4]’:
/home/martijn/zec/3rd/Halide/src/Buffer.h:548:32:   required from ‘void Halide::Buffer<T, Dims>::copy_from(const Halide::Buffer<T2, D2>&) [with T2 = void; int D2 = -1; T = void; int Dims = -1]’
548 | …
```

Fix two warnings on GCC 14.2.1.

---

src/Func.cpp
src/autoschedulers/adams2019/LoopNest.cpp
src/autoschedulers/adams2019/cost_model_schedule.h
src/autoschedulers/anderson2021/LoopNest.cpp
src/autoschedulers/anderson2021/cost_model_schedule.h
test/correctness/fit_function.cpp
test/correctness/multi_pass_reduction.cpp
test/error/CMakeLists.txt
test/error/treat_rvar_as_var.cpp

Don't let users disguise RVars as Vars

---

src/JITModule.cpp
src/JITModule.h
src/runtime/HalideRuntime.h
src/runtime/runtime_api.cpp
src/runtime/thread_pool_common.h
test/correctness/atomics.cpp
test/performance/CMakeLists.txt
test/performance/inner_loop_parallel.cpp
test/performance/parallel_scenarios.cpp

It tests a variety of scenarios: varying task size, the number of tasks, whether the tasks might be memory bound, and the presence of other stuff happening on the system at the same time. The output of the test should be scrapeable from buildbot logs so that we can test threadpool change performance implications on the bots.
Also adds the ability to set/get the threadpool size from JIT-land.

Add threadpool performance test

---

src/CodeGen_Vulkan_Dev.cpp
src/runtime/internal/block_allocator.h
src/runtime/internal/memory_arena.h
src/runtime/internal/region_allocator.h
src/runtime/internal/string_storage.h
src/runtime/vulkan_memory.h

- Fix ArrayStride for arrays of vectors bound to buffer blocks.
- Make a local copy of allocators to avoid dangling references during destruction
- Cleanup Vulkan Memory Allocator destruction to avoid duplicate calls to destroy block allocator
Fixes #8291
Fixes #8287 
Fixes #8293

[vulkan] Fixes to address outstanding validation failures 

---

src/CodeGen_C.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_X86.cpp
src/IR.cpp
src/IRMatch.h
src/IROperator.cpp
src/Simplify_Mod.cpp
src/Simplify_Select.cpp
src/VectorizeLoops.cpp
test/correctness/fuzz_simplify.cpp

In our Select node, I believe the ability for the condition to be a scalar while the value is a vector was a mistake that just adds complexity. It's easy enough to just check if the condition is a broadcast if you really care about that case.
One place it added a bunch of complexity is that it meant in the RHS of the simplifier rules, sometimes you needed an implicit broadcast. These checks for an implicit broadcast on every binary node construction were responsible for about a third of the code size in Simplify_Sub.o! It's also unclear if it respects the reduction order we use to prove the simplifier terminates, because those rules were turning an implicit broadcast in the IR into a new actual Broadcast node, which may increase the total number of IR nodes, which the simplifier is not …

Select condition vector lanes must match the true and false value

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp

Per comments on https://github.com/llvm/llvm-project/issues/114900, we emit the vscale_range attribute in slightly malformed fashion; this emits in the preferred fashion.

Emit `vscale_range()` fn attribute in correct syntax

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

In slice_vector(), only check for type equality after vectors have been normalized to fixed (i.e., it's ok for some original input to be vscale)

Fix #8455 (in combination with #8457)

---

test/common/halide_test_dirs.h
test/performance/parallel_scenarios.cpp

- Missing #include in halide_test_dirs.h
- ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result] in parallel_scenarios.cpp

Fix two trivial build errors

---

src/CodeGen_ARM.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/CodeGen_Posix.cpp

LLVM's `getPointerTo()` is now marked as `deprecated` and fails to compile on at least some of our build bots; `PointerType::get()` is the recommended replacement.

Replace all use of getPointerTo() with PointerType::get()

---

src/Simplify.cpp
test/correctness/CMakeLists.txt
test/correctness/specialize_trim_condition.cpp

Fixes #8443.
Teaches the simplifier to propagate some facts about inequalities where one of the sides is a min or max node.

Propagate some facts about inequalities with min/max

---

test/performance/parallel_scenarios.cpp

Note that this is not denoising the individual runtimes. The point of the test is to measure a distribution of runtimes for a variety of scenarios. This PR takes more samples for each distribution, and spreads the samples out over time to dodge transitory OS stuff by interleaving different test scenarios.
I also tweaked some of the scenarios to be more useful, and reported actual deciles so that the median is actually there.

Get more consistent distributions in parallel scenarios test

---

.lldbinit
README.md
doc/Testing.md
src/IRPrinter.cpp
src/IRPrinter.h
tools/lldbhalide.py

Pulling out changes from my rfactor work...
This PR adds some features for visualizing Halide's types in LLDB, which my IDE (CLion) uses. The IR printer supports a "summary" mode that replaces certain subexpressions / blocks with ellipses. This has greatly improved my debugging experience. I encourage others to add to this and tweak it.

Add LLDB pretty-printing

---

src/ApplySplit.cpp
src/ApplySplit.h
src/Func.cpp
src/ScheduleFunctions.cpp

Affects `apply_split` in `ApplySplit.cpp` and `build_loop_nest` in `ScheduleFunctions.cpp`. Fix callers in `Func.cpp`, too (rfactor).

Remove unused is_update argument

---

src/ApplySplit.cpp
src/ApplySplit.h
src/Func.cpp
src/Inline.cpp
src/Schedule.h
src/ScheduleFunctions.cpp

They hide bugs where a case hasn't been considered.

Remove type inspection helpers from ApplySplitResult and Split

---

packaging/CMakeLists.txt

I expect this to work, but I need to get into the armbots to test it.

Fix CPack package naming when cross-compiling

---

cmake/BundleStatic.cmake

At some point, Apple changed their `libtool -V` output to exclude the comma.
Skipping buildbots because this only runs during packaging.

Fix Apple libtool detection in bundle_static

---

test/correctness/async_copy_chain.cpp
test/correctness/gpu_allocation_cache.cpp

Skip `async_copy_chain` and `gpu_allocation_cache` correctness tests on Windows when running under Vulkan.  They'll only succeed if run on their own.

[vulkan] Skip `async_copy_chain` and `gpu_allocation_cache` correctness tests on Windows 

---

src/IRPrinter.cpp

When the absolute value of a floating point number is smaller than then default IRPrinter precision (6 decimal points), print the value in scientific format.
Use cases:
- Normalizing the 2D/3D fft image by the total pixel count.
- Algorithm problem scaling.
- SI unit conversions, i.e. from nanometer to meter.

Print constants in scientific precision

---

src/ConstantInterval.cpp
src/ConstantInterval.h

It's just zero-intialization of the (exposed) struct members, so it's silly to have to call a function in another TU for it.

Make the default constructor for ConstantInterval inlinable

---

test/fuzz/cse.cpp

This should stop the jumbo recursive select exprs being generated. Hopefully fixes #8510 and #8504

Limit depth more strictly in CSE fuzz test

---

.github/workflows/pip.yml
cmake/HalidePackageConfigHelpers.cmake
src/CMakeLists.txt

* Handle DESTDIR in HalidePackageConfigHelpers.cmake
Fixes #8521
* Fix Halide_[SO]VERSION_OVERRIDE when value is 0
Fixes #8522
* Upgrade LLVM to 19.1.6
(cherry picked from commit ac2cd23951aff9ac3b765e51938f1e576f1f0ee9)

Backport: Fix Debian packaging (#8524)

---

src/CodeGen_LLVM.cpp
src/Deinterleave.cpp
src/IRMatch.h
src/IROperator.cpp
src/Var.h

CodeGen_LLVM.cpp: opaque pointers are now standard, and that flag no longer works anyway.
Var.h: We convert strings to Vars in many places internally, and some of those Vars originated from implicit Vars, so it's not feasible to require than the version that takes an explicit string isn't allowed to be passed things of the form "_[0-9]*". You can use the explicit constructor to make collisions with other Vars, and yes this includes the implicit vars.

Handle some misc TODOs

---

src/CodeGen_X86.cpp
test/correctness/simd_op_check_x86.cpp

This takes care of a TODO. I also moved that block of code into an if statement that only considers saturating casts, to avoid wasting time on it for all other call nodes.

Use lossless_cast for saturating casts from unsigned to signed on x86

---

src/IRMutator.cpp

This speeds up lowering of local laplacian by about 5%. The biggest win is in Deinterleave.cpp, which has a big graph mutator. It gets 25% faster.

Don't cache mutations of Exprs that have only one reference to them

---

Makefile

It's redundant with the one in LLVM_Headers.h, so all it does is break every time we get a new LLVM version.

Remove llvm version check from Makefile

---

src/IROperator.h
test/performance/fast_pow.cpp
test/performance/fast_sine_cosine.cpp

Skip fast exp/log/pow/sin/cosine tests without sse 4.1

---

test/autoschedulers/mullapudi2016/reorder.cpp

This tested vectorized code against scalar code, but the scalar code was something that could be potentially be optimized by llvm quite cleverly - it was just a linear combination of the loop variables. This changes the test to be less of a weird corner case, while still preserving the important property - the evaluation of f is fine under any storage ordering. Hopefully this will make it flake less often.

Hopefully fix flaky mullapudi reorder test

---

src/BoundSmallAllocations.cpp
src/ClampUnsafeAccesses.cpp
src/Deinterleave.cpp
src/EliminateBoolVectors.cpp
src/FuseGPUThreadLoops.cpp
src/HexagonOptimize.cpp
src/LICM.cpp
src/LowerWarpShuffles.cpp
src/OptimizeShuffles.cpp
src/RemoveUndef.cpp
src/SimplifyCorrelatedDifferences.cpp
src/TrimNoOps.cpp
src/UniquifyVariableNames.cpp
src/VectorizeLoops.cpp

This is a super minor thing that has been irritating me. visit_let in the codebase uses a wide variety of template names, argument names, and ways of getting the body type. This just picks one and uses it consistently. No functional changes.

Use a consistent idiom for visit_let

---

src/FindIntrinsics.cpp
src/IROperator.cpp
src/IROperator.h
test/correctness/intrinsics.cpp

FindIntrinsics was rewriting
`i8(rounding_shift_left(i16(foo_i8), 11))`
to
`rounding_shift_left(foo_i8, 11)`
I.e. it decided it could do the shift in the narrower type. However this isn't correct, because 11 is a valid shift for a 16-bit int, but not for an 8-bit int. The former is zero, the latter gets turned into a poison value because we lower it to llvm's shl. This was discovered by a random failure in test/correctness/lossless_cast.cpp in another PR for seed 826708018.
This PR fixes this case by adding a compile-time check that the shift is in-range. For the examples in test/correctness/intrinsics.cpp the shift amount ends up in a let, so making this work on those cases required handling a TODO: tracking the constant integer bounds of variables in scope in FindIntrinsics and …

Fix UB-introducing rewrite in FindIntrinsics

---

src/LLVM_Runtime_Linker.cpp

Fixes linker errors of the form
```
ld: warning: no platform load command found in 'library.a[2](object.o)', assuming: iOS
```
If `17` is too restrictive, we can always drop it to be more permissive later.

Apply version constraints to iOS objects

---

src/LLVM_Output.cpp

Suppress warning on Windows for duplicate constant symbols.

---

src/StmtToHTML.cpp

I put this in a few years ago.

Fix CUDA HTML code printing bug.

---

CMakeLists.txt
src/CodeGen_LLVM.cpp

From [CMake documentation](https://cmake.org/cmake/help/latest/command/find_package.html#id8):
> 
> The [version] argument requests a version with which the package found should be compatible. There are two possible forms in which it may be specified:
> 
> - A single version with the format major[.minor[.patch[.tweak]]], where each component is a numeric value.
> - A version range with the format versionMin...[<]versionMax where versionMin and versionMax have the same format and constraints on components being integers as the single version. By default, both end points are included. By specifying <, the upper end point will be excluded. Version ranges are only supported with CMake 3.19 or later.
>

Fix top of LLVM, and remove upper limit of LLVM version from CMakeLists.

---

src/IROperator.cpp

I've also tagged this to be backported, because it's trivial to do so, and the logging of this Expr is confusing in production builds.

Remove debugging print left in

---

src/CodeGen_LLVM.cpp

I found a case where LLVM was generating worse code for a select on a broadcast of a scalar condition than a select on a scalar condition directly. This change just strips any broadcast around a select condition to help LLVM out.

scalarize select condition for LLVM where possible

---

src/IRVisitor.cpp
src/IRVisitor.h

This is a similar optimization to the one done in IRGraphMutator, and speeds up lowering by about 7.5%.

Only use the nodes-visited set for nodes with multiple refs

---

src/Elf.h

Fix for #8578

---

src/runtime/HalideBuffer.h
src/runtime/cuda.cpp
src/runtime/d3d12compute.cpp
src/runtime/device_buffer_utils.h
src/runtime/metal.cpp
src/runtime/opencl.cpp
src/runtime/vulkan.cpp
src/runtime/vulkan_resources.h
src/runtime/webgpu.cpp
test/correctness/device_buffer_copy.cpp

TLDR: This PR makes it possible to copy from a smaller buffer to a bigger buffer as well (i.e. blit a buffer onto another buffer). Use case: workaround for #8235: realize pipeline to a buffer that acts as a crop, and then copy the result back.
---
This PR makes it possible to copy from any buffer to any other buffer with the same number of dimensions. This is in contrast to the original functionality where it tries to copy from src to the entire number of elements in the dst buffer (even if src is smaller).
- Added a `dst_begin` in `device_copy`.
- @derek-gerstmann I modified a few things in the Vulkan backend cleaning up those multidimensional copies (the tests passed on my machine, but please have a look at what I did in that backend if you can). I also brought it more in line with the …

Support copying the overlapping region from one buffer to another.

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/JITModule.cpp
src/LLVM_Output.cpp
src/LLVM_Runtime_Linker.cpp
test/correctness/simd_op_check_sve2.cpp

Fixes for llvm trunk

---

src/CodeGen_Internal.cpp
src/CodeGen_PTX_Dev.cpp

I believe the last fix actually got things the wrong way around in CodeGen_Internal.cpp, but worked anyway because llvm temporarily reverted the change causing the issue.

Another fix for llvm trunk

---

src/FindIntrinsics.cpp

This was causing internal_assert in one of the Google internal generators, so changed it to check if b is defined before calling constant_integer_bounds.

Check if expression is defined before trying to compute its constant_integer_bounds

---

src/IROperator.cpp

This fixes an explicit type error on the WebGPU backend, where WGSL is not allowing `bool ^ bool`. Fixes #8596.

Redirect bitwise ops to logical ops in case the arguments are bool.

---

src/IREquality.h

This should fix https://github.com/halide/Halide/issues/8610
Please let me know if you want me to create a test -- it seems that the equalities are already tested inside IREquality.cpp, it is just that the wrapper functions were not tested.

In graph_equal(), call the correct implementation for comparing equalities between statements and expressions

---

python_bindings/src/halide/halide_/PyError.cpp
python_bindings/stub/PyStubImpl.cpp
src/Error.cpp
src/Error.h
src/autoschedulers/anderson2021/test/test.h
src/autoschedulers/common/Errors.h
test/correctness/custom_error_reporter.cpp

This PR splits the ErrorReport type into two types:
1. `WarningReport`, which does not throw/abort on destruction.
2. `ErrorReport`, which always throws/aborts on destruction, and is annotated with `[[noreturn]]`.
This makes `internal_error` a valid statement to use at the end of a function that would otherwise fail to return.
Also applies `HALIDE_ALWAYS_INLINE` to the `operator<<` overload because it was getting specialized for every size of `const char *` literal.

Accurately annotate Error system with [[noreturn]]

---

src/AssociativeOpsTable.cpp
src/Pipeline.h
test/correctness/rfactor.cpp

These are required to write schedules for PyTorch pipelines, whose operators use these semantics for min/max.
These rules were checked by Z3 manually.

Add rfactor patterns for NaN-propagating min/max

---

src/CodeGen_ARM.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/CodeGen_PTX_Dev.cpp
src/CodeGen_Posix.cpp
src/Func.cpp

For a long time llvm has been slowly moving to a model where pointers are an opaque type, instead of knowing the pointee type. This has been complete for a while now, so they've started deprecating the APIs for constructing a pointer with a pointee type (these APIs ignore the pointee type anyway), or doing pointer casts, which are no-ops. This PR removes use of those APIs and is a nice simplification of some code.
Hopefully this unbreaks the build for trunk llvm.

Move to opaque llvm pointers

---

README.md

We haven't been able to repro the issue, but for at least one person using a relative path here caused a build failure.

Add note about relative paths to readme

---

cmake/dependencies.cmake
doc/BuildingHalideWithCMake.md
pyproject.toml
python_bindings/CMakeLists.txt
requirements.txt

Pybind11 2.10.4's source builds "require" CMake version compatibility with 3.5, but this has been removed from the most recent versions of CMake. We take this opportunity to upgrade to the version of pybind11 that is included with Ubuntu 24.04 LTS and which fortunately does not suffer from this issue.

Upgrade pybind11 to 2.11.1

---

src/JITModule.cpp
test/performance/parallel_scenarios.cpp

This is an attempt to avoid the recent build failures we've seen related to exception-handling logic inside LLVM when jit-compiling.

Opt out of JIT exceptions

---

src/CodeGen_GPU_Dev.cpp
src/CodeGen_Vulkan_Dev.cpp
src/IR.cpp
src/IR.h
test/correctness/vector_shuffle.cpp

CodeGen wasn't handling arbitrary mixing of vectors with different lanes to form a shuffle, causing a cast instruction to be generated with mixed types which generated invalid SPIR-V and caused the driver compiler to fail to compile.
Now, we handle the extraction of each selected lane of each vector argument, and construct a new Vector from the combined composite.
Fixes https://github.com/halide/Halide/issues/8580

[vulkan] Fix vector shuffle for Vulkan CodeGen

---

src/LLVM_Runtime_Linker.cpp
src/LLVM_Runtime_Linker.h
src/StmtToHTML.cpp

I don't know if the namespace issue is a GCC bug, or actually correct language behavior, but the declarations that look like this:
```cpp
namespace Halide {
namespace { // < anonymous!!
extern "C" int something;
}
namespace Internal { // < named
extern "C" int other;
}
}
```
Yield these symbols:
```
0000000000000000         *UND*	0000000000000000        Halide::(anonymous namespace)::something
0000000001025ae0 g     O .data	0000000000000ca5        other
```
So this behavior is different for GCC when dealing with anonymous namespaces and when dealing with named namespaces. The named namespaces lift `extern "C"` declarations out to global scope, whereas the anonymous have them still in the namespace.
To be honest, I'm clueless if this `extern "C"` _inside_ a namespace makes any sense at …

Fix build on GCC 15 (Comes with Fedora 42).

---

Makefile
cmake/HalideTestHelpers.cmake
src/AddImageChecks.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/CodeGen_Vulkan_Dev.cpp
src/Debug.cpp
src/Debug.h
src/Derivative.cpp
src/DeviceArgument.cpp
src/Error.h
src/Func.cpp
src/HexagonOffload.cpp
src/LLVM_Output.cpp
src/LowerParallelTasks.cpp
src/Module.cpp
src/ParallelRVar.cpp
src/Pipeline.cpp
src/ScheduleFunctions.cpp
src/Simplify.cpp
src/SimplifyCorrelatedDifferences.cpp
src/Target.cpp
src/autoschedulers/anderson2021/AutoSchedule.cpp
src/autoschedulers/common/Errors.h
src/autoschedulers/common/HalidePlugin.h
src/autoschedulers/li2018/GradientAutoscheduler.cpp
src/autoschedulers/mullapudi2016/AutoSchedule.cpp
test/correctness/custom_error_reporter.cpp
test/correctness/simplify.cpp
tools/build_halide_h.cpp

This PR extends the `HL_DEBUG_CODEGEN` semantics with features for filtering messages only from certain files, functions, and lines. I'm opening this as a draft to invite discussion.
The _current_ syntax for `HL_DEBUG_CODEGEN` is a single number setting the verbosity level globally for all `debug(N)` streams.
The _proposed_ syntax for `HL_DEBUG_CODEGEN` is a `;`-delimited list of rules of the form:
```
verbosity[,file_suffix[:line_low[-line_high]]][@function_suffix]
```
* `verbosity` is a positive integer indicating the maximum (inclusive) verbosity level to emit. This is equivalent to the current semantics
* `file_suffix` is a maximal string of non-`:@` characters. If it is specified, the rule applies only to files ending in this string. Typically, this will be a path fragment like …

Add filtering capabilities to HL_DEBUG_CODEGEN

---

src/Simplify_Add.cpp

These mirror a bunch of distributive-law-related cancellation rules in Simplify_Sub.cpp
Formally verified (rules copy-pasted from the output of the checker tool).

Add missing addition simplifier rules

---

src/CodeGen_PTX_Dev.cpp
src/runtime/ptx_dev.ll

**Problem**: LLVM changed the name of their NPTX barrier intrinsics: https://github.com/llvm/llvm-project/pull/141143/.
**Solution**: Rely on the accompanying auto-upgrade mechanism of LLVM for these intrinsics. As such, I added an `alwaysinline` wrapper that calls the original intrinsic name, which LLVM will upgrade to the new one, if it wants to. This way, it's compatible with all versions of LLVM without relying on any runtime or compiletime checks in the Halide code.

Fix top LLVM: renamed NVPTX barrier intrinsics.

---

CMakePresets.json
cmake/FindHalide_LLVM.cmake

As of LLVM 17 or so, the `*ConfigVersion.cmake` files have been correctly shipped with Clang and LLD, not just LLVM. The `FindHalide_LLVM.cmake` module now searches for the exact matching versions of Clang and LLD. Unfortunately, neither the `LLVM_PACKAGE_VERSION` variable (which is documented as being safe to use with CMake version comparisons) nor the `LLVM_VERSION` variable (which is undocumented, but used internally) are suitable for use with CMake version comparisons. LLVM's CMake build continues to be a fractal of insanity. Instead, we reconstruct a valid version string from the major/minor/patch versions. Whee...
Fixes #8633

Constrain Clang and LLD searches to LLVM version

---

src/CodeGen_C.cpp
src/CodeGen_C.h
src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_GPU_Dev.cpp
src/CodeGen_GPU_Dev.h
src/CodeGen_Metal_Dev.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_Vulkan_Dev.cpp
src/CodeGen_WebGPU_Dev.cpp
src/runtime/opencl.cpp
test/correctness/boundary_conditions.cpp
test/correctness/math.cpp

Fixes #8594.
This clears up all the preprocessor prologues or wrapper function prologues.
Update: `pow()` for WGSL is removed from the preamble now, and its behavior is emulated during codegen in the WGSL_CodeGen backend. There is a potential for simplyfing that again if there are meaningful bounds on expressions inferred. I'd consider that future work. Removing this from the preamble and using Halide's IR to emulate this, enables support for vectorized calls. There is a caveat with this: WGSL says there are no nans. However, their own builtin pow() function returns nan for negative inputs to x and y. Emulating that was tricky, because I think the WGSL simplifier removes those? Not sure why I couldn't simply do `make_const(x.type(), std::nanf(""))`. I had to resort to …

Math functions renaming table for GPU backends to support vectorized evaluation of math functions.

---

src/CodeGen_LLVM.cpp
src/JITModule.cpp

This makes it build, but needs to be tested on the platforms covered by this if branch (windows, x86-32, arm-32)

Attempted fix for LLVM change

---

src/autoschedulers/mullapudi2016/AutoSchedule.cpp
test/autoschedulers/mullapudi2016/cost_function.cpp
test/autoschedulers/mullapudi2016/data_dependent.cpp
test/autoschedulers/mullapudi2016/extern.cpp
test/autoschedulers/mullapudi2016/fibonacci.cpp
test/autoschedulers/mullapudi2016/get_autoscheduler_params.hpp
test/autoschedulers/mullapudi2016/histogram.cpp
test/autoschedulers/mullapudi2016/large_window.cpp
test/autoschedulers/mullapudi2016/mat_mul.cpp
test/autoschedulers/mullapudi2016/max_filter.cpp
test/autoschedulers/mullapudi2016/multi_output.cpp
test/autoschedulers/mullapudi2016/overlap.cpp
test/autoschedulers/mullapudi2016/param.cpp
test/autoschedulers/mullapudi2016/reorder.cpp
test/autoschedulers/mullapudi2016/small_pure_update.cpp
test/autoschedulers/mullapudi2016/tile_vs_inline.cpp
test/autoschedulers/mullapudi2016/unused_func.cpp
test/autoschedulers/mullapudi2016/vectorize_var_in_update.cpp

**Rationale:**
1. To compare the GPU auto-scheduling performance of `Mullapudi2016` against `Li2018` and `Anderson2021`.
2. To reduce the following claims to practice, quoting the original Mullapudi2016 article:
>  **Portability to Different Architectures: GPU Performance:** The inlining, tiling, and grouping processes are otherwise similar to the CPU case. Groups resulting from merging are mapped to CUDA kernels by designating the outer tile loops as GPU block grid dimensions and the inner tile loops as GPU thread block dimensions. All intermediate buffers
within a group are allocated in GPU shared memory
3. To implement the so-call "single level tiling only" limitation in the `Mullapudi2016` and `Sioutas2020` algorithms, according to the findings in the Anderson2021 paper:
> [Mullapudi …

GPU autoscheduling with Mullapudi2016: the reference implementation

---

src/autoschedulers/mullapudi2016/AutoSchedule.cpp
test/autoschedulers/mullapudi2016/reorder.cpp

After committing `gpu_tiles`, reorder all axes such that the for-loops are inside all `gpu_blocks`.
Also limit the `gpu_blocks` count to no more than 3.
Refer to: #8640 for the list of pending actions to robustify the Mullapudi2016's experimental GPU schedules.

Mullapudi2016-GPU: Reorder to avoid for-loops to be sandwiched between `gpu_blocks`.

---

src/Func.h

The following code would fail to compile with "ambiguous overloaded function" error. This commit fixes it.
```{.cpp}
std::vector type = { UInt(8), UInt(8) };
f.define_extern("extern_func", args, type, dims,
NameMangling::CPlusPlus);
```

remove superfluous overload that causes compile errors

---

src/irvisualizer/html_template_StmtToHTML_dependencies.html

Search the first 5 lines of the device code for the keyword `using namespace metal`. If it exists, invoke the syntax highlighting for Metal/C language.
(Used to debug the `threads_budget` for Metal GPUs. https://github.com/halide/Halide/pull/8650#issuecomment-2972840243)
Screenshot:
cc'ed @mcourteaux .

Highlight Metal GPU code in stmt_html

---

apps/bilateral_grid/CMakeLists.txt
apps/iir_blur/CMakeLists.txt
apps/iir_blur/iir_blur_generator.cpp
apps/lens_blur/CMakeLists.txt
src/autoschedulers/mullapudi2016/AutoSchedule.cpp

Tile the image with `TailStrategy::GuardWithIf` whenever `can_parallelize(c, 3)` is encountered and when the split factor (3) is smaller than GPU's warp size (=32).
For 2D/3D tile schedules having mixed tail strategies, pick the most conservative one, i.e. `TailStrategy::GuardWithIf`.
Enable `iir_blur` tests on the Github Actions/Buildbot.
Before:
```
iir_blur_auto_schedule failure:
Error: Input buffer input is accessed at 5, which is beyond the max (3) in dimension 2
```
After:
```
Manually-tuned time: 4.09081ms
Auto-scheduled time: 1769.91ms
```
Note: We are not trying to compete with manual GPU schedules. We just want it to pass correctness tests.
cc'ed @alexreinking and @mcourteaux .

Always ensure gpu_threads count >= warp size of 32

---

src/WasmExecutor.cpp

WasmExecutor had its own debug macros which were only enabled by changing a `#define` in the .cpp file. Turning this on fails to compile after the addition of rule based debug filtering. The rule based filtering should provide the ability to filter output when debugging wasm test failures and Halide jit wasm execution is not widely used outside of tests. Hence the decision to remove the file specific debug support.
Moved expensive validations and such under new #ifdefs at the top of the file.
Changes some debug levels per making this part of the standard debug set.

Remove obsolete WasmExecutor specific debug macro.

---

src/RDom.cpp
test/correctness/CMakeLists.txt
test/correctness/irprinter.cpp

We were missing a check for `RDom::defined()` here. Slight tweaking of the format to make more sense in the Python repl (which is where this was discovered).
Fixes #8663

Fix segfault in RDom's operator<<

---

python_bindings/apps/CMakeLists.txt
python_bindings/apps/identity_app.py
python_bindings/apps/identity_generator.py
python_bindings/src/halide/halide_/PyBuffer.cpp
src/PythonExtensionGen.cpp

The buffer protocol (PyBuffer) does not support all the same metadata that `Halide::Runtime::Buffer` does. In particular, it does not support coordinate offsets (as in `set_min`).
When an object is passed to an AOT Python pipeline, it is now checked for a `_get_raw_halide_runtime_buffer` method. If it exists, it should return a pointer to a `halide_buffer_t` whose lifetime is at least that of the object.
I don't love this solution as passing around a `uintptr_t` smells fishy (security implications?). But my first few ideas didn't pan out:
1. I wanted to use pybind11's API to call `.cast<Halide::Buffer<>*>` to get a reference to the underlying C++ object. This has some more safety checks implemented. But the generated extension doesn't link to pybind11. Changing this would mean adding a …

Get raw Runtime::Buffer from Buffer in Python rather than use PyBuffer

---

python_bindings/src/halide/halide_/PyBinaryOperators.h
python_bindings/src/halide/halide_/PyExpr.cpp
python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyFuncRef.cpp
python_bindings/src/halide/halide_/PyFuncRef.h
python_bindings/test/correctness/basics.py
python_bindings/test/correctness/rdom.py
src/Error.h
src/Func.cpp
src/Func.h
src/Var.h

This enables inference of units (and types) for pure definitions in reduction-y update stages.
Fixes #8661

Bind in-place update operators (e.g. +=) in Python

---

src/LLVM_Runtime_Linker.cpp

**Proof of Concept**: I know that the long-term solution is more elaborate (i.e. runtime function renaming), but this 50 cent hack does the trick for me without any manual steps in my build process.
The `HL_RUNTIME_DROP_FUNCS` environment variable is checked for a comma-separated list of function names to remove from the runtime. Instead of actually deleting them, their body is removed, and their linkage is changed to extern.
@zvookin @abadams Do we want this feature? If so, do we need any changes?
This fixed my issue against which I was battling for 2 days with the Windows linker. Tested this on both Linux and Windows with success.

PoC feature: drop functions from the runtime

---

.github/workflows/pip.yml

https://github.com/halide/docker-images has already been updated.

Bump the LLVM version in the pip package to 20.1.8

---

src/CodeGen_Internal.cpp
src/LLVM_Output.cpp

Following the discussion on https://github.com/llvm/llvm-project/issues/151330, it was determined that the reason SDOT arguments were missing in the assembly output was that the AArch64InstrFormats table was missing some entries for the Apple/Darwin-specific format.
This PR uses the AArch64 format on older LLVM versions that won't receive the upstream patch.
This fix was derived by reading the upstream patch that fixes this issue: https://github.com/llvm/llvm-project/pull/152111
ATTN @rtzam 
Fixes #8697

Use AArch64 assembly syntax on macOS with LLVM<22

---

src/Bounds.cpp
src/CompilerLogger.cpp
src/Module.cpp
src/StmtToHTML.cpp
src/Target.cpp
src/Util.cpp
src/Util.h
test/correctness/pytorch.cpp

Initial changes to address #8717.
This does not address the Module deep-copy behavior copying Buffer contents. This merely addresses the string processing and avoids some copies.
Fixes [#8752](https://github.com/halide/Halide/issues/8752)
----
Drive-by optimization: Change the signature of replace_all() to take the subject-string to be passed by value. This now allows for making replace-chains in this pattern:
```cpp
std::string s = ...;
s = replace_all(std::move(s), ..., ...);
s = replace_all(std::move(s), ..., ...);
s = replace_all(std::move(s), ..., ...);
s = replace_all(std::move(s), ..., ...);
```
Without making copies in case the target string is not found in the subject string.

fix(stmt-html): Fix embedded Buffer processing performance issue.

---

CMakePresets.json
Makefile
apps/support/Makefile.inc
doc/BuildingHalideWithCMake.md

Thanks to a schism between libjpeg and libjpeg-turbo, Homebrew and many other distributions (Ubuntu, Debian, Fedora, Firefox, Chrome, etc.) refuse to use the IJG's libjpeg. Instead, the open-source world appears to have adopted libjpeg-turbo.
The buildbots have been updated to include both libraries. When and if this is merged, I'll remove libjpeg-9f.
See: https://libjpeg-turbo.org/About/Jpeg-9
See: https://github.com/Homebrew/homebrew-core/pull/107511
See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717076

Prefer to build against libjpeg-turbo and document this.

---

src/Bounds.cpp

This is adressing a following error which we started to get after updating Halide internally:
```
“Error: Min of (uint16)lerp((uint16)0, uint16((max(min((float32)scale_fine, 1.000000f), 0.000000f)*16384.000000f) + 0.500000f), (uint8)mask_im(x, y)) should have been a scalar of type uint16: (uint8)0” 
```
I *think* the issue is that when ```handle_const_arg_call``` returns ```false```, the Call visitor just exits instead of hitting the else branch. This is problematic, because ```handle_const_arg_call``` will visit each of the arguments and each of their visitors will set ```interval```, so in the end ```interval``` will be set to the interval of the last argument of the Call. In this case, it has a different type causing the error above.

Fix wrong type of the bound

---

.clang-tidy
src/BoundaryConditions.h

The original implementation of `func_like_to_func` could genuinely return a dangling reference if the function was misused. The new implementation has been renamed to `forward_as_func` and is impossible to misuse. It perfectly forwards const-references as before, but to a callback, which avoids lifetime issues.
Here's an example of a real crash from misusing `func_like_to_func`.
```c++
#include <Halide.h>
using namespace Halide;
Func get_func() {
Var x{"x"};
Func f{"f"};
f(x) = x;
return f;
}
int main() {
const Func &f = BoundaryConditions::Internal::func_like_to_func(get_func());
std::cout << f.name() << '\n'; // crash!
return 0;
}
```
The callback approach here is the only safe way I know to _perfectly_ forward the const-ref. Using an rvalue-reference with `std::forward` still invokes a …

Enable bugprone-return-const-ref-from-parameter

---

.clang-tidy
src/RealizationOrder.cpp
src/ScheduleFunctions.cpp
src/VectorizeLoops.cpp

This cleaned up a few loops and is generally a good idea. Shouldn't apply it to tutorials, though, where we have some plain-C loops that _could_ be rewritten this way, but doing so would mar the exposition. We also don't want `// NOLINT` line-noise in there.

Enable modernize-loop-convert

---

src/StorageFlattening.cpp
test/correctness/hoist_storage.cpp

No changes to any of the logic, just moving code around so that hoist storage happens in its own mutator.
The goal is to make the FlattenDimensions class easier to modify by removing a responsibility from it.

Delay storage hoisting into its own mutator

---

src/CodeGen_Hexagon.cpp
src/IRMatch.h
src/Simplify_And.cpp
src/Simplify_Or.cpp
test/correctness/simplify.cpp

This PR adds more simplification rules for nested And and Or nodes, mostly centered around cancelling terms, or a term and its already-simplified negation (e.g. x < y and y <= x). The original motivating example was that I needed a rule that says that in an implication (encoded as `!a || b`), you can assume a sub-clause of the LHS on the RHS, so:
```rewrite(!(x && y) || (x && z), !(x && y) || z)```
But there are a dizzying number of these, so in the end I just enumerated all simplifier-canonical LHS trees with up to four leaves in And, Or, and Not operators where x appears on both sides of the root node, or x appears on the left and its negation appears on the right. Each of these can be uniquely characterized by their 8-entry truth table. 
I then also enumerated all non-simplifying …

More simplifications for And and Or nodes
