halide/Halide

test/CMakeLists.txt, test/scripts/distrib_windows.ps1
I've ran into issue #586 as well. I googled about this problem (using release libraries in debug build) a little bit and it seems that: a) it's hard to make it working b) it's considered to be a bad practice. Also, it seems that the most common recommendation is to use debug libraries in debug configuration, so I've added debug version into build script.
Few things I am not sure about, please let me know, if this should be fixed:
* Separate packages are created for Debug and Release.
* Currently, tests are executed only for Release build.
=> Added debug build into distrib_windows.ps1

Makefile
Fixes an issue we have on OS X where the partially-linked object file was too large to be a mach-o object.
The fix is a bit of a hack, so other suggestions are welcome. The goal of the current and former approach is to include the necessary parts of LLVM inside libHalide.a for the convenience of users.
The LIBS vs STATIC_LIBS thing was removed because that no longer appears to be an issue with llvm >= 3.4
=> No partial linking

src/VaryingAttributes.cpp
This PR resolves bugs #595 and #596 
GLSL will only interpolate float values, previously varying attribute expressions were converted to float and the was promoted up through the expression. This change snaps and casts varying attribute variables for integer expressions from their floating point interpolated value to integers.
The test failure was caused by interpolated floating point values a few ulp less than the correct integer being cast to uint8 for output, with the cast introducing a floor operation that moved the value one integer away from the correct value.
=> Fix cast for integer varying attribute expressions

src/IRPrinter.cpp
This PR tracks a branch that I have repeatedly used to debug type issues- if it is useful to others I'm happy for it to be merged, otherwise it can remain in a branch.
It appears that a few years ago variable types were output in stmt dumps via "name.type". This PR uses "<type> name" and outputs the type of variables, let expressions, and calls.
PTAL
=> Output the type of certain expressions in stmt output for debugging

src/runtime/osx_clock.cpp
It seems that mach_absolute_time() has better precision.
=> Implemented osx HR clock using mach_absolute_time

src/Generator.h
from_string() for int and float need to ensure that the string is fully
consumed, otherwise strings like “argname=1234,something” are parsed as
1234 rather than generating an error.
=> Better error checking in GeneratorParam

Makefile, src/Error.h, src/Function.cpp, src/Generator.cpp, src/Generator.h, src/Introspection.cpp, src/Introspection.h, src/ObjectInstanceRegistry.cpp, src/ObjectInstanceRegistry.h, src/Parameter.cpp, src/Util.cpp, test/correctness/introspection.cpp
Now if you manually register a heap object Halide can figure out what
its members are called.
This is the introspection portion of the change mentioned on the mailing list.
=> Introspect heap objects

src/CodeGen.cpp
Small fix for a small bug. This only appeared when one attempted to interleave 4 vectors of a 64-bit type. Solution is to check bit width of the type and fall back to the recursive interleave if the vectors have 64-bit elements.
=> Fixed a small bug in interleave_vectors 

src/Generator.cpp
This allows a user to request that certain optional output files be generated, e.g. the stmt, assembly, or bitcode files. I've been wanting this feature for awhile now, and finally got around to providing a simple solution.
=> Added an emit options flag to the generate_main_filter function

src/Profiling.cpp, util/HalideProf.cpp
This PR contains two small changes in the profiler:
1) *-only values seem to be calculated incorrectly for inner loops, because of it's parent set to produce/update/consume instead of outer loop.
2) Profiling timer overhead of child calls should not be subtracted from ticks_only values, because ticks_only value does not contain timings of child calls already.
=> Fix ticks-only calculation in the profiler

apps/camera_pipe/camera_pipe.cpp
It got promoted to an intrinsic in 6ecdd51fe244698a54027ed98f18ac9999872af3.
Fixes #639.
=> Remove duplicate absd function after it got promoted to an intrinsic.

src/JITModule.cpp
I am getting following warnings (which are turning into errors with -Werror):
```
src/JITModule.cpp: In member function ‘void Halide::Internal::JITModule::compile_module(Halide::Internal::CodeGen*, llvm::Module*, const string&, const std::vector<Halide::Internal::JITModule>&, const std::vector<std::basic_string<char> >&)’:
src/JITModule.cpp:138:145: error: ‘wrapper_fn’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
jit_wrapper_function(jit_wrapper_function) {
^
src/JITModule.cpp:336:11: note: ‘wrapper_fn’ was declared here
int (*wrapper_fn)(const void **);
^
src/JITModule.cpp:138:145: error: ‘main_fn’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
jit_wrapper_function(jit_wrapper_function) {
^
src/JITModule.cpp:335:11: note: ‘main_fn’ …
```
=> Fixed warning in the JITModule.cpp: *_fn is not initialized

src/JITModule.h, src/runtime/posix_thread_pool.cpp, src/runtime/windows_thread_pool.cpp, test/performance/inner_loop_parallel.cpp
While working on linear algebra, which occasionally uses more threads
than there are tasks, I noticed that a ton of time was spent in the
linux kernel from contention on the mutex. Windows had the same issue.
A pathological case is:
for i from 0 to 1000000:
parallel for j from 0 to 2:
do something trivial
When a job comes in that has fewer tasks than threads, this PR puts
some of the threads to sleep on a secondary condition variable, and 
only wakes them when a new job comes in that can actually make use
of them. Seems to remove all the overhead on linux. Windows timings
are a bit more noisy.
OS X should hopefully not suffer from this due to using gcd.
=> Inner loop parallelism

src/runtime/opencl.cpp
The arguments to these `strstr()` function calls were backwards. If the user didn't specify a `HL_OCL_DEVICE_TYPE` variable, these were checking whether the empty string was present in a bunch of string literals, which is always the case. I only noticed this because some OpenCL platforms don't seem to accept the bitwise combinations of multiple device types.
=> Fixed string comparison for user-specified OpenCL device types.

apps/linear_algebra/Makefile, apps/linear_algebra/benchmarks/cblas_benchmarks.cpp, apps/linear_algebra/src/blas_l2_generators.cpp, apps/linear_algebra/tests/test_halide_blas.cpp
This PR has a few tweaks to the BLAS stuff. First, I've updated the tests so that we all correctness tests can be easily run with 'make test'. One note on this is that the gemm_transAB algorithm is currently not passing the correctness test, and I haven't been able to find the source of the problem.
I've also improved the performance of the gemv subroutines so that the L2 algorithms are apparently running as fast as the fastest BLAS implementations. I have updated the performance benchmarks to reflect the improvements:
https://docs.google.com/spreadsheets/d/15pJP-oS4l_PZNvf63wcdxUNuaKwMOiQj-IMEAaUI-gw/edit?usp=sharing
These benchmarks also use a custom built version of ATLAS, which is more appropriate as ATLAS is intended to be built on the machine it is to run on.
=> Halide blas fixed testing and added some performance improvements

apps/linear_algebra/benchmarks/macros.h, apps/linear_algebra/src/blas_l1_generators.cpp, apps/linear_algebra/src/blas_l2_generators.cpp, apps/linear_algebra/src/blas_l3_generators.cpp, apps/linear_algebra/src/halide_blas.h, apps/linear_algebra/tests/test_halide_blas.cpp
Discovered that the implemented BLAS subroutines were producing incorrect results except in the rare cases that the size of the matrices/vectors were exact multiples of the blocking and/or vectorization size. It just so happened that the only size that was being tested for correctness was 256, which satisfied these conditions. I also fixed the problem with the gemm_transAB subroutines. All tests are passing now, and I am rerunning the benchmarks to determine the effect these changes have had on performance, which I expect to be fairly small.
=> Halide blas bug fixes

src/CodeGen.cpp, src/CodeGen_PTX_Dev.cpp, src/LLVM_Headers.h
Align Halide with the effects of two following revisions in llvm trunk:
---
r229094 | chandlerc | 2015-02-13 05:01:29 -0500 (Fri, 13 Feb 2015) | 16 lines
[PM] Remove the old 'PassManager.h' header file at the top level of
LLVM's include tree and the use of using declarations to hide the
'legacy' namespace for the old pass manager.
---
r228961 | rafael | 2015-02-12 16:16:34 -0500 (Thu, 12 Feb 2015) | 3 lines
Remove mostly unused setters.
=> Fix compilation issues against latest llvm trunk(3.7)

apps/linear_algebra/Makefile, apps/linear_algebra/benchmarks/cblas_benchmarks.cpp, apps/linear_algebra/benchmarks/eigen_benchmarks.cpp, apps/linear_algebra/benchmarks/halide_benchmarks.cpp, apps/linear_algebra/src/blas_l2_generators.cpp, apps/linear_algebra/src/halide_blas.cpp, apps/linear_algebra/src/halide_blas.h, apps/linear_algebra/tests/test_halide_blas.cpp
These methods perform the generalized rank-1 update of a matrix, i.e. A += alpha * x * y^t. I've added tests and benchmarks for these methods, and updated the [performance charts](https://docs.google.com/spreadsheets/d/15pJP-oS4l_PZNvf63wcdxUNuaKwMOiQj-IMEAaUI-gw/edit#gid=625829285).
=> Added an implementation of the sger/dger BLAS methods.

Makefile, src/CMakeLists.txt, src/CodeGen_ARM.cpp, src/Target.cpp, src/Target.h, src/runtime/arm_no_neon.ll
This PR tries to enable at running Halide generated code on older devices.
When I run the HelloAndroid app on a Xoom tablet it crashes with SIGILL because the Halide generated code contains instructions incompatible with the Tegra2 processor. But, when I disable everything NEON in CodeGen_ARM.cpp I can run it and it's not too slow too.
=> Make it possible to build for ARM without NEON.

src/CodeGen.cpp, src/CodeGen_ARM.cpp, src/CodeGen_C.cpp, src/Profiling.cpp, util/HalideProf.cpp
I do not think this PR is fully ready (I apologize), but I wanted to ask about your opinion.
I've been trying to improve precision of overhead adjustment (as it sometimes leads to negative execution time values) and initially, for the overhead measurement,  it generates the following code (eight calls to profiling_timer()):
```c++
for (j, 0, 1000000) {
let begin_halide_profiler_ticks_dst_$ignore$_$ignore$_null_null = profiling_timer()
$ignore_buf$[0] = uint32(0)
ProfilerBuffer[13] = (ProfilerBuffer[13] + (profiling_timer() - begin_halide_profiler_ticks_dst_$ignore$_$ignore$_null_null))
let begin_halide_profiler_ticks_dst_$ignore$_$ignore$_null_null = profiling_timer()
$ignore_buf$[0] = uint32(0)
ProfilerBuffer[13] = (ProfilerBuffer[13] + (profiling_timer() - …
```
=> Profiler overhead measurement

src/Type.h, src/runtime/HalideRuntime.h
We need a runtime-suitable enum that corresponds to Type::TypeCode,
both for use in Metadata (Issue #664) and to add to buffer_t at some
point in the future. This defines an enum in HalideRuntime.h to pave
the way for these uses, and redefines the values of Type::TypeCode to
match them.
(It seems infeasible to replace Type::TypeCode entirely, as the runtime
version needs to be C-compatible, and preserving source compatibility
would require polluting the global namespace with (e.g.) “Int”, etc.)
=> Add halide_type_code_t

src/Type.h
(I haven’t actually found instances of using any uninitialized
instances; this is a pre-emptive strike.)
=> Add default ctor to Halide::Type

Makefile, src/Argument.h, src/CMakeLists.txt, src/Expr.h, src/Function.h, src/IR.h, src/Parameter.h, src/Schedule.h
IR.h had several weird include-along-the-way hacks, which made trying
to use Expr in additional .h files (e.g. Argument.h) painful. Note that
this still has a regrettable wart (see the For node in Expr.h) but this
is still a vast improvement over the previous situation.
=> Split IR.h into IR.h + Expr.h

src/runtime/device_interface.cpp, test/generator/gpu_only_aottest.cpp
Fixes gpu_only_aottest, and skips a pointless copy in general. The bad path was:
Start with a buffer where dev == 0 && host_dirty == 0 and call halide_copy_to_device
dev is not the right device interface, so flip buffer to new device
copy to host (no-op, because dev == 0)
mark host dirty
copy to new device (pointless, because host_dirty was zero and there was no dev, so the buffer was undefined)
The pointless copy actually segfaulted for the test, because the test sets the host field to something invalid assuming that it will never get copied from. Turns out this test also tests that no pointless copy_to_device of the output buffer takes place!
This is a complex failure path, so I'd appreciate someone sanity checking me.
=> Only flip a buffer from one device to another if dev != 0

apps/HelloAndroid/jni/native.cpp
HelloAndroid sample is broken - see below. This should fix it, hope it makes sense too.
```
Error Code:
2
Output:
/Users/aam/Documents/halide-llvm_trunk_cmake/Halide/apps/HelloAndroid/jni/native.cpp: In function 'void Java_com_example_hellohalide_CameraPreview_processFrame(JNIEnv*, jobject, jbyteArray, jint, jint, jobject)':
/Users/aam/Documents/halide-llvm_trunk_cmake/Halide/apps/HelloAndroid/jni/native.cpp:34:24: error: too few arguments to function 'int halide_start_clock(void*)'
halide_start_clock();
^
/Users/aam/Documents/halide-llvm_trunk_cmake/Halide/apps/HelloAndroid/jni/native.cpp:20:16: note: declared here
extern "C" int halide_start_clock(void *user_context);
^
make: *** [/Users/aam/Documents/halide-llvm_trunk_cmake/Halide/apps/HelloAndroid/build/intermediates/ndk/debug/obj/loca …
```
=> Fix apps/HelloAndroid sample

src/Argument.h, src/Buffer.cpp, src/CodeGen.cpp, src/CodeGen_C.cpp, src/CodeGen_GPU_Dev.h, src/CodeGen_GPU_Host.cpp, src/CodeGen_Internal.cpp, src/CodeGen_Internal.h, src/CodeGen_OpenCL_Dev.cpp, src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_PTX_Dev.cpp, src/Func.cpp, src/Generator.cpp, src/Param.cpp, src/Param.h, src/Parameter.cpp, src/Parameter.h, test/correctness/infer_arguments.cpp, test/correctness/simd_op_check.cpp, test/generator/paramtest_generator.cpp, test/generator/paramtest_jittest.cpp
Adding metadata (Issue #664) requires augmenting Argument to contain
some information previously contained only in Internal::Parameter. This
also includes some drive-by cleanup to the Argument API to make it a
bit more readable at the point of call (via use of enums rather than a
bool).
=> Add dimensions and def/min/max to Argument

src/SpecializeBranchedLoops.cpp
Fixed a subtle bug in specialize_branched_loops that had to do with improperly handling variable names for let bound variables, which we have attempted to branch, but end up with only 1 branch. This case does not seem to appear that often, which is why it wasn't caught before now.
=> Specialize branched loops bug fixed

test/HalideGenerator.cmake
BUILD_TYPE variable has blank value.
Replaced with "meta" variable CMAKE_CFG_INTDIR, which is translated into "$(Configuration)" in .vcxproj file. And that nicely does the job of being replaced with 'Release'(for example) during build time if building like this:
```
devenv /build "Release" Halide.sln
```
=> Fix test build on Windows

src/CodeGen_GPU_Dev.h, src/CodeGen_GPU_Host.cpp, src/CodeGen_OpenCL_Dev.cpp, src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_PTX_Dev.cpp
GPU_Argument should neither is-a nor has-a Halide::Argument: they are
never actually used interchangeably, and GPU_Argument requires
read+write buffer semantics for some GPU backends (which
Halide::Argument does not allow for at present).
=> Decouple GPU_Argument from Argument

src/StorageFolding.cpp, test/correctness/storage_folding.cpp
I'm pretty sure this is correct. Suggestions for further test cases welcome.
=> Allow multiple folds of an allocation when usage is non-overlapping

src/Target.cpp, test/scripts/test_all_targets.sh, test/scripts/test_target.sh
I'd like to eventually add 'ptx' as a target arch, rather than use it as a (redundant) flag for the CUDA runtime. This would let us get rid of the special case for PTX device initial modules (get_initial_module_for_ptx_device).
=> Deprecate 'ptx' flag, use 'cuda' instead

Makefile, src/CMakeLists.txt
As silly as it might seem, this really does help with merging. I ran into this often over the last few months while we've had large outstanding PRs, but I wanted to wait until they got merged to make this change.
=> Split long Make/CMake lists into multiple lines

src/CodeGen_C.cpp, src/runtime/HalideRuntime.h, src/runtime/cache.cpp
Fixes a bug where the le32-unknown-nacl target triple we now use pads
bools out to 32-bits.
Also removes a nasty wart from the cache runtime module.
Seems to work with clang and g++. Should work with msvc too.
Even though it's a bugfix, submitted as a PR because it touches the definition of buffer_t.
=> Explicitly specify the memory layout of structs in the runtime

src/BoundaryConditions.cpp, src/BoundaryConditions.h, test/correctness/boundary_conditions.cpp
I needed the ability to use a boundary condition on the middle two dimensions of a 4 dimensional Func. This PR allows you to specify undefined bounds in a BoundaryConditions call, like so:
Func bounded_y = BoundaryConditions::repeat_edge(func, Expr(), Expr(), 0, 10);
bounded_y would have a boundary condition on its second dimension, but not its first.
@zvookin in particular, you will probably want to check this out and see if you agree with the change.
=> Enable using BoundaryConditions functions on particular dimensions

src/CodeGen_GPU_Host.cpp, src/JITModule.cpp, src/LLVM_Output.cpp
— ‘using std::string’ (etc) must be inside the Halide namespace
— ‘using namespace std’ is forbidden anywhere.
=> fix 'using std' usage

src/Func.cpp, src/Func.h, src/Generator.cpp, test/correctness/compile_to_lowered_stmt.cpp
When called from Generator, it’s essential that the inputs match those
explicitly listed (which may differ from those inferred since some can
be unused).
=> compile_to_lowered_stmt() should take explicit args

src/CodeGen_GPU_Host.cpp, src/CodeGen_Internal.cpp, src/CodeGen_Internal.h, src/CodeGen_LLVM.cpp
Accommodate LLVM trunk which as of couple days ago needs pointer types for CreateConstGEP2_32, CreateInBoundsGEP, CreateConstInBoundsGEP2_32, CreateConstInBoundsGEP1_32.
=> Halide master

src/CodeGen_GPU_Host.cpp
This is follow-up to #731, which broke tutorial 12.
=> Fix typo in GEP type parameter.

test/HalideGenerator.cmake
It does ‘ar q’ every build, so multiple builds with clean produce an
archive with multiple object files embedded, making for suboptimal
debugging.
Hack fix is to just rm it each time. (There’s probably a better flag to
ar.)
=> halide_add_generator_dependency() is broken

src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/runtime/HalideRuntime.h, test/generator/metadata_tester_aottest.cpp
(Note that I’m not bumping the metadata version field for this since
~nothing is using the structure yet.)
=> Add function name to metadata.

Makefile, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/LLVM_Headers.h, src/Target.cpp, src/Target.h, src/runtime/HalideRuntime.h, src/runtime/metadata.cpp, test/CMakeLists.txt, test/generator/metadata_tester_aottest.cpp
When built with Target::RegisterMetadata (which is off by default), we
add a small amount of load-time code to build a list of information
about filter metadata and argv-style calls; this can be enumerated to
introspect/call filters.
When this Target feature is disabled, the only extra code size hit
added is the code in runtime/metadata.cpp (some trivial list
manipulation code); in particular, there are no hard references to
metadata, so it can still be dead-stripped.
When this feature is enabled, we add a trivial amount of code (a
ctor-ish function for each filter), but effectively prevent the
metadata structures from being dead-stripped, hence the opt-in nature
of this feature.
Please consider the TODO in HalideRuntime.h (i.e.: should we move
‘name’ and ‘argv_func’ into the metadata …
=> Add optional metadata registration

Makefile, apps/support/Makefile.inc, src/BoundaryConditions.h, src/CodeGen_LLVM.cpp, src/Expr.h, src/Generator.cpp, src/Generator.h, src/JITModule.cpp, src/ObjectInstanceRegistry.cpp, src/ObjectInstanceRegistry.h, src/Simplify.cpp, test/generator/example_jittest.cpp, test/generator/paramtest_jittest.cpp, test/scripts/test_target.sh
Remove all ifdef’s that conditionalize C++11 usage; remove all makefile
directives that conditionalize C++11 features. Remove makfile code for
supporting LLVM prior to 3.5.
=> Require C++11 and LLVM3.5+ (Issue #741)

src/CodeGen_GPU_Dev.cpp, src/Expr.h, src/ExprUsesVar.h, src/FindCalls.cpp, src/IR.cpp, src/IR.h, src/IREquality.cpp, src/IRMatch.cpp, src/IRMutator.h, src/IRPrinter.h, src/IRVisitor.h, src/JITModule.cpp, src/StmtToHtml.cpp
This PR moves the inclusion of IRVisitor such that it is only done where necessary. This will be the first of a series of PRs aimed at avoiding including internal headers as part of the public API. Although IRVisitor is part of the public API, this still cuts down the complexity of what gets included where.
This also seems to have made (Halide code) compile times very slightly faster (due to code size?).
=> Move #include of IRVisitor

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/runtime/HalideRuntime.h, test/correctness/buffer_t.cpp
#pragma pack is bad because it imposes alignment assumptions on the
struct itself; on some processors this can cause access violations if
the buffer_t is stack-allocated without the necessary alignment.
Instead, force the alignment of the fields we care about.
=> Replace buffer_t #pragma pack with align directives

tutorial/lesson_01_basics.cpp, tutorial/lesson_02_input_image.cpp, tutorial/lesson_03_debugging_1.cpp, tutorial/lesson_04_debugging_2.cpp, tutorial/lesson_05_scheduling_1.cpp, tutorial/lesson_06_realizing_over_shifted_domains.cpp
The new version of Halide is using the c++11 feature,but the compile command of  tutorial still use old command to compile without c++11 which will fail when use new version.
=> Fix compile command of turtorial

src/CodeGen_PTX_Dev.cpp
Remove initializations of the fields that were removed in llvm trunk.
```
r235265: Remove the JITEmitDebugInfo TargetOptions as they're only set and 
not used anywhere in llvm.
```
=> Catch up with post-r235265 llvm.

src/AddImageChecks.cpp, src/AddParameterChecks.cpp, src/BoundaryConditions.cpp, src/BoundaryConditions.h, src/BoundsInference.cpp, src/CSE.cpp, src/CodeGen_ARM.cpp, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/Func.cpp, src/Func.h, src/Generator.h, src/Introspection.cpp, src/ParallelRVar.cpp, src/PartitionLoops.cpp, src/RDom.cpp, src/RDom.h, src/RealizationOrder.cpp, src/ScheduleFunctions.cpp, src/Scope.h, src/VaryingAttributes.cpp
This is purely stylistic, but IMHO removes a longstanding C++ wart.
=> C++11: space no longer needed for nested template brackets

apps/bilateral_grid/bilateral_grid.cpp, apps/blur/halide_blur.cpp, apps/local_laplacian/local_laplacian_gen.cpp, apps/modules/generate_pipeline.cpp, apps/modules/my_library/flip.cpp, apps/modules/my_library/vignette.cpp, apps/wavelet/wavelet.cpp, src/Func.cpp, src/Func.h
Now with C++11 available, I think they're less clear than just wrapping the arguments in {}
=> Remove variadic compile to file

src/runtime/android_opengl_context.cpp
HelloAndroidGL won’t build right now, as the LLVM linker requires all
runtime module functions beginning with “halide_” to be weak, and all
other platform versions of this function are also weak
=> Add missing WEAK to android halide_opengl_get_proc_address()

apps/HelloAndroidGL/jni/android_halide_gl_native.cpp, src/runtime/HalideRuntimeOpenGL.h, src/runtime/opengl.cpp
This was pretty much completely broken. HelloAndroidGL now works
properly.
=> Fix "client-bound" buffers in OpenGL runtime

src/Generator.cpp, src/Generator.h, test/generator/paramtest_jittest.cpp
This was formerly needed for legacy reasons in at least one external
codebase, but recent changes to generate Metadata now make this
unnecessary; removing since Internal::Parameter should remain internal.
=> Remove GeneratorBase::get_filter_parameters()

src/runtime/opengl.cpp, test/opengl/shifted_domains.cpp
This PR fixes a bug in the GLSL backend and adds a test that exercises the bug.
=> Avoid shifting by min when computing memory offsets. Added test.

apps/HelloAndroidCamera2/build.gradle
Both armeabi and armeabi-v7a should map to arm-32-android; armv7s isn’t
supported on Android.
=> Fix Android targets for Camera2 app

apps/support/static_image.h
This is handy for working with code that needs interleaved aka chunky layouts (e.g. OpenGL buffers)
=> Allow apps/support/static_image.h to create interleaved buffers

src/CodeGen_OpenGL_Dev.cpp
This PR fixes a bug in the case that a type realized as e.g. vec4 is swizzled by an expression: 
vec4 v = ...
float f = v[idx];
Previously, the code assumed that the LHS was always a vec type, e.g. vec2, etc. There is a separate code path for ordinary scalar swizzling operations like float f = v.r;
=> Fix glsl codegen for assignments from certain swizzle operations

apps/renderscript/jni/rstest.cpp, apps/renderscript/test_blur_copy.cpp, src/CodeGen_LLVM.h, src/CodeGen_Renderscript_Dev.cpp, src/CodeGen_Renderscript_Dev.h, src/runtime/renderscript.cpp
This fixes problem with RS codegen support of multiple kernels, which effectively meant that only first kernel was working correctly.
Multiple(two) kernels are generated in apps/renderscript sample due to use of specialize() for planar and interleaved images. Unfortunately there is no easy way of testing planar without building your own publicly available master-copy of Android sources, because Allocation3DRead API call for handling 3d images was not released yet. So commonly only interleaved version of apps/renderscript is run.
Processing planar images is much slower, so it has very limited value besides testing.
=> Fix Renderscript codegen' so it generates multiple kernels correctly.

src/CodeGen_PTX_Dev.cpp, src/LLVM_Output.cpp
Flag removed from TargetOptions in r238244.
=> Catch up to llvm trunk. NoFramePointerElim is gone.

apps/HelloiOS/HelloiOS.xcodeproj/project.pbxproj, apps/HelloiOS/HelloiOS/reaction_diffusion_2.cpp
- Added extra -I and -L paths so it builds out of the box with cmake builds of
Halide.
- Compiler is stricter about C++11.
- Removed HelloiOSTest target which had no files and wouldn't compile.
- Removed armv7 as a valid target architecture: app is now 64-bit only.
- Allowing 32-bit armv7 would mean messing around with the shell script too
much.
=> Updated HelloiOS demo to compile on Xcode 6.1.

src/BitWriter_3_2/BitcodeWriter.cpp
Quoting the comment:
// in LLVM (3.7) r239940 bitcode format of Instruction::LandingPad instruction
// was changed where PersonalityFn was moved from LandingPad instruction to
// Function instruction.
// With no simple fix in sight to address bitcode incompatibility between
// what can be produced from LLVM IR and what Android "3.2" bitcode expects,
// it seems that LandingPad instructions simply should not happen in
// Halide-generated code because there should be no exceptions used in Halide code.
=> Catch up to llvm trunk - fix Renderscript BitWriter

src/CMakeLists.txt
VS2015 started adding C++14 features, which does not bode well with LLVM.
This PR copies feature-sniffing steps from LLVM CMakeLists.txt to identify VS2015 and disable sized allocation diagnostic.
=> Fix VS2015 Halide build.

src/BitWriter_3_2/BitcodeWriter.cpp
Turns out there is better fix for LandingPad bitcode format change than 0a52c605 :
```
$ git diff a3b13f9..HEAD src/BitWriter_3_2/BitcodeWriter.cpp
diff --git a/src/BitWriter_3_2/BitcodeWriter.cpp b/src/BitWriter_3_2/BitcodeWriter.cpp
index a4deae1..1de57b2 100644
--- a/src/BitWriter_3_2/BitcodeWriter.cpp
+++ b/src/BitWriter_3_2/BitcodeWriter.cpp
@@ -1308,7 +1308,12 @@ static void WriteInstruction(const Instruction &I, unsigned InstID,
const LandingPadInst &LP = cast<LandingPadInst>(I);
Code = bitc::FUNC_CODE_INST_LANDINGPAD;
Vals.push_back(VE.getTypeID(LP.getType()));
+#if LLVM_VERSION < 37
PushValueAndType(LP.getPersonalityFn(), InstID, Vals, VE);
+#else
+    PushValueAndType(LP.getParent()->getParent()->getPersonalityFn(), InstID,
+                     Vals, VE);
+#endif …
```
=> Better, less drastic fix for LandingPad API change.

src/Param.cpp
bool OutputImageParam::defined() => bool OutputImageParam::defined() const
Small fix to OutputImageParam constness.
=> bool OutputImageParam::defined() const

HalideGenerator.cmake
Previously the Ninja file was generated such that the generated header
file and library were in the test directory instead of the respective
scratch directory.
=> Try to fix building Halide when using Ninja as the CMake generator.

src/Simplify.cpp
This rule is a special case of an existing rule (x == 1 in the rule below the new rule), but the existing rule wasn't catching my use case.
=> Added simplification for (y + (a*b)) % b -> y % b.

src/BlockFlattening.cpp, src/Deinterleave.cpp, test/correctness/interleave.cpp, test/performance/fft.cpp
This PR enables `interleave_vectors` to be generated for Tuple-valued Funcs. To enable this, StoreCollector is now a bit more aggressive.
This enables interleave_vectors to fire in the fft2d_c2c benchmark, which makes it 15% faster on my laptop! But, somehow, it also makes it 10% slower on my desktop. Both are x86, which is surprising... Regardless, this does speed up all my real world code.
=> Deinterleave tuples

src/Simplify.cpp
These rules help simplify vectorized boundary condition selects to become scalar selects (of vector values) if the boundaries are aligned to at least a multiple of the vector width.
=> Simplify rules

src/Pipeline.cpp, src/Pipeline.h
source files because the function name to emit was allowed to be empty.
This bug was found when trying to build the glsl app.
To fix this the name given to functions when no name is given is made to
match the JIT behaviour by factoring out that code from
Pipeline::compile_jit() into Pipeline::generate_function_name().
This bug could be exposed by calling the following methods with the
default arguments (fn_name as empty string).
- Func::compile_to_c()
- Func::compile_to_header()
- Func::compile_to_module()
or by calling the overloaded versions of the following methods where
in some versions an empty string was passed as the function name
- Func::compile_to_assembly()
- Func::compile_to_bitcode()
- Func::compile_to_object()
=> Fix bug in Pipeline where it was possible to generate invalid code or

src/Deinterleave.cpp
This is maybe a bit silly, because I don't know of any code that doesn't work with the previous StoreCollector. However, I think this implementation is a little bit safer/more future proof. The old implementation requires every IR node that might have a load be explicitly handled, this implementation should be able to see loads in any kind of IR node type that isn't otherwise explicitly handled.
=> Safer implementation of StoreCollector.

HalideGenerator.cmake
Running the clean target would not remove these files because
CMake was not aware that invoking the generators produced these
files.
=> Fix ``make clean`` not removing generator object files.

src/Simplify.cpp, test/correctness/interleave.cpp
Adds some simplification rules for interleave_vectors. Should make fuse then vectorize patterns more reliably simplify.
=> Simplify interleaves

apps/linear_algebra/.gitignore, apps/linear_algebra/Makefile, apps/linear_algebra/benchmarks/macros.h, apps/support/Makefile.inc
Slightly improve build speed by building generators this way.
(Also, drive-by removal of unused-variable warnings in macros.h)
*** NOTE ***: I cannot easily do a full build-and-test on my local machine, as I don't have OpenMP or the other reference libraries installed; someone should do a full pull-and-test before merging this.
=> use -no_runtime in apps/linear_algebra

apps/simd_op_check/Makefile, apps/simd_op_check/driver.cpp, src/CodeGen_ARM.cpp, src/CodeGen_ARM.h, src/CodeGen_LLVM.cpp, src/runtime/aarch64.ll, src/runtime/arm.ll, test/correctness/simd_op_check.cpp
This PR adds aarch64 peephole optimizations for things like saturating add or interleaving store.
There are a few new things happening here:
1) A bunch of code in CodeGen_ARM.cpp and runtime/aarch64.ll to emit these 64-bit neon ops. The llvm intrinsics are similar but not the same as the 32-bit versions.
2) A bunch of code in test/simd_op_check to make sure we're generating them correctly.
3) A minimal app that you can run on a (rooted) device to make sure they all do the same thing as their unvectorized equivalents (works together with simd_op_check). The app currently passes.
I also deleted some dead code in CodeGen_ARM while I was there (LLVM_VERSION < 35 stuff)
=> Aarch64 simd peephole optimizations

.gitignore, Makefile, README.md, apps/bilateral_grid/Makefile, apps/blur/Makefile, apps/c_backend/Makefile, apps/interpolate/Makefile, apps/local_laplacian/Makefile, apps/modules/Makefile, apps/nacl_demos/Makefile, apps/support/Makefile.inc, apps/wavelet/Makefile
Addresses issue #873 as a more aggressive alternative to #875 
This makes it possible to do an out-of-tree build of Halide. e.g.:
```
abadams@femputer:~/projects
$ mkdir halide_build
abadams@femputer:~/projects
$ cd halide_build/
abadams@femputer:~/projects/halide_build
$ make -f ../Halide/Makefile run_tests
Found a new enough version of llvm
mkdir -p bin/build
touch bin/build/llvm_ok
g++-4.8 ...
```
=> Out of tree builds

.gitignore, Makefile, README.md
Move the default location of Makefile’s BUILD_DIR to be inside bin/ and
update .gitignore to no longer ignore build/ at top-level. Also change
the README to suggest a different name for camp’s build folder.
=> Move build -> bin/build (Issue #873)

src/CodeGen_LLVM.cpp, src/IROperator.h, src/Image.cpp, src/Image.h, test/correctness/handle.cpp
On 32-bit systems this implies zero-padding on store and truncate on
load. I needed to update Image.h too to support Image<foo *> properly
with this change.
This PR fixes the 32-bit issues in #871 , which seem to be caused by undefined upper bytes in string immediate pointers.
=> Make sure handles load and store as uint64_t

src/StmtToHtml.cpp
This PR flattens blocks in the HTML output, to avoid generating huge div trees. This does change the "meaning" of the IR very slightly, but it is only changed in a way that is hard to observe in a browser.
This change makes it much easier to use the browser dev tools to inspect the HTML for issues.
=> Smaller html

src/CMakeLists.txt
This should help #861 by reducing the linker memory footprint which should make it possible to build the tests under CMake in the memory constrained TravisCI environment.
=> CMake linking clean ups

.travis.yml, test/scripts/build_generic.sh, test/scripts/build_ubuntu1204.sh
The current configuration doesn't run the tests due to them failing
in various ways. So for now they are disabled and we will use TravisCI
for fast failing checks (i.e. compilation failures).
@abadams Once these files are added you need to enable TravisCI for this repository. Only admins of a repository/organisation can do this.
=> Add TravisCI build file and build scripts.

src/JITModule.cpp, src/LLVM_Output.cpp
change that happened after LLVM branched for 3.7
I'm not entirely sure if this is the best fix but it fixes compilation at least. An alternative would be to introduce a helper function that wraps getting a ``DataLayout`` from a ``TargetMachine``.
=> Fix compilation against LLVM 3.7 branch due to r243114. There was an API

src/runtime/tracing.cpp
While writes to a file descriptor opened with O_APPEND are atomic, those opened for write do not appear to share that behavior.
This can result in a malformed event stream that cannot be reliably parsed. Wrapping this call in a lock removes this subtle requirement on the fd provided to the halide_set_trace_file API.
=> Synchronize write calls to ensure atomicity.

Makefile, test/renderscript/jit_copy.cpp
This PR fixes broken renderscript test and adds test_renderscript to run_tests target to make sure that those tests always run.
Thanks to @delcypher for pointing out broken renderscript test.
=> Fix Renderscript test. Add test_renderscript to ALL_TESTS.

src/CodeGen_C.cpp
Prior to this change, including a Halide generated header in a program compiled as C (as opposed to C++) resulted in errors due to bool being an undefined type (C99 has _Bool, and bool is defined by stdbool.h) and the need to include struct as a qualifier on the type halide_filter_metadata_t.
=> Make generated headers valid for C99 inclusion.

src/Simplify.cpp
This PR makes compile time assertion failures into warnings instead of errors. This enables one to inspect the IR, which is often by far the most useful way to diagnose and fix these kinds of assertion failures.
=> Make compile time assert failures into warnings

apps/bilateral_grid/bilateral_grid.cpp, src/FuseGPUThreadLoops.cpp, test/generator/gpu_only_aottest.cpp
... and add a validation pass to prevent it from happening again
Nested copies of gpu_block for loops were causing one kernel to only run
over a few blocks, and silently produce junk output!
=> Fix buggy gpu schedule in bilateral grid

src/ScheduleFunctions.cpp, test/error/bad_compute_at.cpp
Alternative to #902
1) Don't print the distinct compute_at/store_at options - it squares the
number of things printed
2) Print the uses of the function by walking the IR
Sample error message (from bad_compute_at test):
```
Func "f" is computed at the following invalid location:
f.compute_at(h, x);
Legal locations for this function are:
f.compute_root();
f.compute_at(h, Var::outermost());
f.compute_at(h, y);
"f" is used in the following places:
...
for h.s0.y:
for g.s0.x:
g uses f
...
for h.s0.x:
...
h uses f
```
=> Better error message for bad compute_at

src/Bounds.cpp, src/Simplify.cpp
The bounds of
cast<uint16_t>(clamp(some_float_expr, 0.0f, 4096.0f))
were [0, 65535]
which surprised and annoyed a user.
This happened because Halide saw the bounds of the innermost thing as
some complex thing involving both 0/4096 and also some_float_expr. I.e.
it hadn't conservatively backed off to the clamp args, and then the
narrowing logic bailed on the nasty expressions, because it was only
designed to deal with constants.
This PR explicitly attempts to simplify the bounds of the innards
towards constants in that case, and simplifies some of the surrounding
code at the same time (I think it was written before Type::can_represent
existed).
=> Bounds of cast of clamp

CMakeLists.txt, Makefile
This came about because my build of ``llvm-config`` also emits the undocumented (AFAICT) ``-W`` flag which caused more errors to be emitted by the Makefile build compared to the CMake build. This difference is quite annoying so I've taught the Makefile to filter out warning flags from ``llvm-config``.
Whilst I was here I added ``-Wignored-qualifiers`` which was the warning that was tripping me up.
=> More warning fixes

src/runtime/HalideRuntime.h
The message now includes the filename and line number that where the
assert was written and mentions that it is an assertion failure.
Not sure if this is the cleanest approach as two extra macros had to
be declared to handle __LINE__.
=> Make halide_assert() used in runtime more verbose.

src/IROperator.cpp
An example is
a.type() == {code = Halide::Type::Float, bits = 32, width = 1}
b.type() == {code = Halide::Type::Float, bits = 32, width = 8}
After widening the types match so there is no need to add a cast
around either expression. An example application where this was observed
was when running the generator for the "bilateral_grid" app.
=> Remove an unnecessary cast after widening types in match_types()

src/BoundsInference.cpp, src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/Memoization.cpp, src/ScheduleFunctions.cpp, src/StorageFlattening.cpp
Change the second argument to create_buffer_t intrinsics from a byte
size to an Expr where the Type itself is the meaningful
information. This encodes more complete type information which is
needed immediately in the JavaScript branch and will be used
everywhere when we add complete type info to buffer_t.
I chose to replace the elem_size argument isntead of add a new one as
the information is redundant and this is a simpler code change. I
cannot think of a valid situation were elem_size should be allowed to
disagree with the byte size of the Type. In fact, I can see an
argument for elminating elem_size when the type info is added to
buffer_t.
=> Typed create buffer_t

HalideGenerator.cmake
code in the CMake build under Linux.
Previously the ``q`` flag was being used with ``ar`` which
just appends the object file to the archive without checking if it
was already present. This would lead to multiple versions of an object
file ending up in the archive. Then if an application linked against
this archive it would pick the first object file (i.e. the stale one)
rather than the latest version of the object file.
Now we use the ``r`` flag instead which is inserts object files into
the archive with **replacement**.
=> Fix bug when creating static library archives from halide generated

src/Target.cpp, src/Target.h, test/correctness/target.cpp, test/internal.cpp
This reduces the number of places information must be
edited when adding a target feature/arch/OS, and ensures the usage error
message reflects the actual target specification language.
=> Change target string parsing and printing to use maps from string to numeric value.

src/CodeGen_OpenCL_Dev.cpp, src/CodeGen_OpenCL_Dev.h
Based off of pull request #949, this adds support for the interleave_vectors intrinsic in OpenCL code generation. It also fixes in issue where vector variables did not have a leading underscore, causing compilation to fail in kernels that did vector loads.
=> Add interleave_vectors for OpenCL codegen

src/Simplify.cpp, test/correctness/likely.cpp
These are some new simplifier rules necessary for the partition loops revamp work. I'm pulling them out as a separate PR so that they can be checked for correctness in isolation. The fuzz tester seems happy with them.
I had to remove a case from the likely test that was relying on an expression that trivially simplified away.
=> New simplify rules

src/runtime/cuda.cpp
It looks like there's some incorrect copy-over references to functions from the OpenCL runtime.
=> Correct stale comment in CUDA runtime

src/runtime/cuda.cpp
The CUDA runtime uses `cuCxtPushCurrent` and `cuCtxPopCurrent` to manage its own CUDA context. The context is created with `cuCtxCreate` (https://github.com/halide/Halide/blob/master/src/runtime/cuda.cpp#L291) in `create_cuda_context` when needed.
However, creation automatically pushes the context (see https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#context, esp. Figure 19), while the runtime also pushes unconditionally (https://github.com/halide/Halide/blob/master/src/runtime/cuda.cpp#L152). The result is that the context gets pushed twice, and the final pop (https://github.com/halide/Halide/blob/master/src/runtime/cuda.cpp#L157) leaves it on the stack.
This isn't noticeable if you're only running CUDA code from Halide, since the correct context will always be active …
=> Properly release context in CUDA runtime

src/Simplify.cpp
Don't normalize x >> 31 to x / (1 << 31). It overflows.
Fixes #975
=> Fix overflow in normalization of shifts to divisions

apps/fft/Makefile, apps/fft/main.cpp
This PR adds a benchmark of FFTW along side the Halide FFT. This makes it much easier to compare performance with a known gold standard. Here is the current output using FFTW 3.3.4, on a Haswell x86 CPU using a single core:
WITH_FFTW=1 make bench_16x16 bench_32x32 bench_48x48 bench_64x64
```
./bench_fft 16 16
Halide                  FFTW     
DFT type  Time (us)    MFLOP/s  Time (us)    MFLOP/s      Ratio
c2c      0.367   27901.91      0.417   24556.35       1.14
r2c      0.288   17777.78      0.444   11531.53       1.54
c2r      0.359   14261.84      0.455   11252.75       1.27
./bench_fft 32 32
Halide                  FFTW     
DFT type  Time (us)    MFLOP/s  Time (us)    MFLOP/s      Ratio
c2c      1.821   28116.42      1.944   26337.45       1.07
r2c      1.175   21787.23      2.168 …
```
=> Added FFTW benchmark

src/runtime/renderscript.cpp
In 0feddcca I accidentally removed code that is needed to support multi-kernel Renderscript modules. This CL puts that code back.
=> Reinstate multi-kernel support in Renderscript.

src/CMakeLists.txt
When rebuilding the runtime CMake was not aware that the source files
depended on the header files included by the sources. This fixes
this issue but unfortunately only for the makefile generator.
An issue is open for using Ninja as a generator but it doesn't look like
it's been touched in a while https://cmake.org/Bug/view.php?id=13234
=> [CMake] Partially Fix #920

src/Scope.h, src/Simplify.cpp
It previously only took advantage of constant bounds, but used
bounds_of_expr_in_scope followed by simplify to try and find those
constant bounds. For things that do not have constant bounds this can
recursively call the simplifier in ways that have exponential complexity
in expression size.
This changes it to just only track constant integer bounds through a
fixed simple set of nodes. This lets us be more aggressive about where
we use it - I now also track the bounds of let expressions when they are
constant.
=> Only track bounds of things with constant bounds in simplifier

src/Function.cpp
This makes it a bit easier to track down certain types of errors that occur in big programs.
=> Add update definition index to relevant error messages.

src/Generator.h, test/generator/paramtest_generator.cpp, test/generator/paramtest_jittest.cpp
Allows GeneratorParams to be used in expressions with arithmetic
types (integers, floats, etc.) and Expr. This was removed with the
recent changes to how immediates are handled in the IR and this restores
that functionality.
It is possible to use template metaprogramming to unify this with the operator overloads in IROperator.h, and it may be a good idea to do so. I've started working on an implementation of that and am not sure how long it is going to take. Hence I'd like to get consider this approach first and the more elaborate extensible one later. There is some risk of changing the language semantics slightly doing it this way so I am open to feedback here. The generalized code is good if we anticipate there being other types that need to interoperate with Expr and the arithmetic …
=> Add operator and cast support for GeneratorParam.

apps/fft/fft.cpp
This makes the 48x48 benchmark case ~10% faster than before! Here's the current timing:
Halide                  FFTW     
DFT type  Time (us)    MFLOP/s  Time (us)    MFLOP/s      Ratio
c2c      6.077   21174.52      6.959   18490.81       1.15
r2c      3.750   17157.00      6.514    9877.00       1.74
c2r      4.102   15684.73      6.466    9950.32       1.58
=> Added dft6 implemented using prime factor FFT algorithm.

src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/CodeGen_PTX_Dev.cpp, src/CodeGen_Renderscript_Dev.cpp, src/JITModule.cpp, src/JITModule.h, src/LLVM_Output.cpp, src/LLVM_Output.h, src/LLVM_Runtime_Linker.cpp, src/LLVM_Runtime_Linker.h, src/Output.cpp, src/Pipeline.cpp
A few other C++11 cleanups as well.
=> Plumb through unique_ptr use around llvm::Module.

src/Argument.h, src/CodeGen_Hexagon.cpp, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/Param.cpp, src/Param.h, src/Parameter.cpp, src/Parameter.h, src/Pipeline.cpp, test/hexagon/include/halide-hexagon-setup.h
This PR removes the stride_multiple infrastructure, in favor of using the existing set_stride/stride mechanism.
edit: Should have pointed out, this is a pull request into the hexagon branch, not master.
=> Remove stride_multiple infrastructure.

src/runtime/fake_thread_pool.cpp
The fake thread pool was missing halide_spawn_thread, and halide_mutex_destroy needed to be renamed halide_mutex_cleanup.
=> Update fake thread pool implementation.

test/correctness/simd_op_check.cpp
This should catch codegen bugs where the vector and scalar versions of an op disagree.
=> simd_op_check also runs the routine if the target matches

src/runtime/posix_allocator.cpp
halide_malloc requires allocated memory to be aligned to
at least the natural vector width. Hexagon HVX has 128 byte
vectors. Short of defining a different halide_malloc for each
target, this patch makes halide_malloc return a pointer to a
128 byte aligned block of memory.
=> Align memory on the heap to a 128 byte boundary.

test/correctness/simd_op_check.cpp
Here are some (maybe) useful changes to simd_op_check from the hexagon branch:
- Use wildcard matching for filtering and searching for instructions. This allows testing assembly formats where instruction behavior that needs to be checked is interspersed with register names and other changing content.
- Set NoAsserts when generating text assembly, to make it easier to read.
- Add clamped variants of casts.
=> Pulling simd_op_check changes from hexagon branch

src/CodeGen_LLVM.cpp, src/CodeGen_Posix.cpp, src/CodeGen_Posix.h, src/runtime/posix_allocator.cpp, test/correctness/storage_folding.cpp
This PR moves the padding required by CodeGen_LLVM's implementation of Load out of the runtime allocator. This avoids the need for custom allocators to be aware of the requirement. This partially addresses #1044.
This also changes how stack allocations get allocated and aligned.
=> Alignment padding

apps/camera_pipe/process.cpp, tools/halide_image.h, tools/halide_image_info.h, tools/halide_malloc_trace.h
- Added several methods useful for debugging programs that operate on
the Image class supporting images with arbitrary dimensions.
Image<uint16_t> input = load_image(argv[1]);
input.info("input");  // Output the Image header info
input.dump("input");  // Dump the Image data
input.stats("input"); // Collect statistics on the Image
These can also be called through macros which automatically tag the
output with the symbol name used in the program:
Image_info(input);    // Output the Image header info
Image_dump(input);    // Dump the Image data
Image_stats(input);   // Collect statistics on the Image
- These features are off by default.  To enable, compile with the following
flags:
-DHL_MEMINFO  Produce Image info output
-DHL_MEMINIT  Produce Image info when Image is first initialized
- The …
=> [QTOOL-3157] Updates to Image & halide_malloc instrumentation

src/runtime/HalideRuntime.h, src/runtime/fake_thread_pool.cpp, src/runtime/gcd_thread_pool.cpp, src/runtime/posix_allocator.cpp, src/runtime/posix_error_handler.cpp, src/runtime/posix_print.cpp, src/runtime/posix_thread_pool.cpp, src/runtime/windows_thread_pool.cpp
This PR does some refactoring of the runtime:
- Use typedefs for function pointers.
- Rename a few halide_ things that are already inside the Halide::Runtime::Internal namespace.
=> Refactor runtime

src/Simplify.cpp
This PR splits simplify_test into several functions to avoid this warning:
/usr/local/google/home/dsharlet/GitHub/Halide/src/Simplify.cpp: In function ‘void Halide::Internal::simplify_test()’:
/usr/local/google/home/dsharlet/GitHub/Halide/src/Simplify.cpp:3428:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
Which appears to significantly increase compile time (Simplify.cpp is probably the longest compiling file, this issue appears to make it get compiled twice).
=> Split simplify_test into several functions

CMakeLists.txt, src/CMakeLists.txt
Adds a CMake option to compile with RTTI enabled, patterned after the corresponding option in LLVM.  This option makes it easier to use Halide within a code base that requires RTTI.  The option is disabled by default.
=> CMake option to compile with RTTI enabled

src/StoreForwarding.cpp
Trivial renaming of width to lanes. Also needed to change code
because of this error
"error: call to implicitly-deleted copy constructor of 'Halide::Internal::Store'"
The reason is that IntrusivePtr uses std::atomic whose copy constructed is explicitly
marked deleted.
=> Fix build problems. (Pull into loop_store_forwarding)

python_bindings/CMakeLists.txt, python_bindings/FindHalide.cmake
... this allows one to build the Python bindings against a version of the Halide binaries found outside the immediately enclosing directory, e.g. those ensconced in a Homebrew-installed Halide package (I use [this formula](https://github.com/fish2000/homebrew-praxa/blob/master/halide.rb)), a Mac OS X framework, and the like
=> FindHalide.cmake lets `find_package()` discover Halide library paths

src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h
This refactors compile_func to make it easier for derived CodeGen class implementations to change the behavior of compile_func. Currently, if a derived class wants to generate some prolog/epilog code, it can't  replace compile_func without replicating the entire implementation.
=> Refactor compile_func to enable easier customization by codegen implementers

apps/camera_pipe/camera_pipe.cpp, apps/camera_pipe/fcam/Demosaic_ARM.cpp, apps/camera_pipe/process.cpp
Previously the Halide generated image was much darker/lower-contrast
than the FCam generated image.  The reason for this was tracked down
to the following functions:
- hot_pixel_suppression
no longer does cold pixel suppression (was causing the generated
image to lose contrast)
- apply_curve
This is the old Halide LUT code (see OLD_CURVE) didn't match the LUT
computed in FCam.  The Halide code originally didn't take into
account the blacklevel (was causing the generated image to be darker)
which has been fixed (see NEW_CURVE).
=> Update Halide camera_pipe to more closely match FCam

test/correctness/simd_op_check.cpp
I am setting this up so that all future improvements that I make to HVX codegen can contain a simd_op_check check. Keeping this file clean will help. On the side though we can continue work to unXFAIL these tests.
=> XFAIL known failing hvx tests in simd_op_check.cpp

src/CodeGen_Hexagon.cpp, test/correctness/simd_op_check.cpp, test/hexagon/codegen/interleave_vectors.cpp, test/hexagon/codegen/interleave_vectors.h
Added tests to both simd_op_check.cpp and test/hexagon/codegen. We
should deprecate test/hexagon/codegen only after all tests in that
directory have been ported to simd_op_check.cpp.
=> Generate vshuff to interleave vectors.

src/Func.cpp, src/Func.h, src/Pipeline.cpp, src/Pipeline.h, src/runtime/cuda.cpp, src/runtime/cuda_functions.h
Harvested parts of #928.
Also added cuProfilerStop call as described in
http://devblogs.nvidia.com/parallelforall/pro-tip-clean-up-after-yourself-ensure-correct-profiling/.
Hopefully fixes #910.
=> compile_to_llvm_assembly convenience methods

src/CodeGen_ARM.cpp, src/CodeGen_ARM.h, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/CodeGen_X86.cpp, src/CodeGen_X86.h
This makes the optimization for fast integer division easier to share among targets that use CodeGen_LLVM.
Tested on x86 so far. ARM is passing simd_op_check (as well as master is anyways... I see the __modis3 check failing on both master and this branch), but haven't run the const_division test yet. It needs testing on ARM (and the rest of the targets too).
=> Refactor integer division optimization

src/Image.cpp, src/Image.h
I don't see why it should not be const, maybe it's good to make it const.
=> mark ImageBase.name() const

src/CodeGen_Hexagon.cpp, src/CodeGen_Hexagon.h
I was trying to add some patterns for multiply and found this simplification of the pattern infrastructure code to be useful. @pranavb-ca please review and merge if you want to make this change.
=> [Hexagon] Replace WPICK with wildcard variables

Makefile, src/CodeGen_Hexagon.cpp, src/CodeGen_Hexagon.h, src/CodeGen_Hexagon_LV.h
@pranavb-ca, I hope you don't mind, I went ahead and did some more refactoring of CodeGen_Hexagon. I'm trying to work with it to fix integer division and whatnot, this stuff helps make it easier to add patterns and call intrinsics. I keep running into things like needing to add handlers for every vector width. I'm working towards making the code work with any vector width via CodeGen_LLVM::call_intrin.
Here's the main changes:
- Add a helper for callLLVMIntrinsic that takes an Intrinsic::ID. Pretty much every single call site did the exact same thing to get the function from an ID, this just does that work for you.
- Don't mutate the arguments of callLLVMIntrinsic. This allows callLLVMIntrinsic to be used with an initializer list of operands, and IMO is also safer (lots of places in the …
=> [Hexagon] Codegen refactoring

apps/interpolate/interpolate.cpp, src/CodeGen_GPU_Host.cpp, src/FuseGPUThreadLoops.cpp, src/Simplify.cpp
This reworks and simplifies how bounds inference is done for shared memory size determination and thread block size determination for Cuda and OpenCL. Instead of building a scope of intervals as you recurse inwards (which causes combinatorial explosion and some hard-to-simplify expressions), this recurses inwards to find the relevant expressions and then expands them using containing for loops as you unwind the stack and back out of the Stmt. The expressions stay simple, and remain constant when they can. The new behavior is exploited in the interpolate app to do block-level fusion of a bunch of the stages.
Also added some new simplifier rules that help out a little with the kinds of patterns you get when you tile a pyramid upsample. Proving these rules on paper is a pain. I've …
=> Better GPU shared memory and block size determination

src/CodeGen_ARM.cpp, src/CodeGen_ARM.h, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/CodeGen_X86.cpp, src/CodeGen_X86.h
This PR causes CodeGen_LLVM to use Halide IR to realize compound expressions where appropriate, which allows it to take advantage of overriden behavior and optimizations in derived codegen class implementations.
=> Refactor CodeGen_LLVM to use codegen of Halide IR

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, test/correctness/simd_op_check.cpp
@pranavb-ca please take a look. Here are a few questions about this:
- When presented with something like `x_i16 + y_i8*2`, should we prefer an accumulating multiply, or a shift and an add?
- It seems like there's basically a random subset of the possible multiply instructions are missing. Am I missing the instructions, or do I have it right?
=> Add accumulating multiply patterns to Hexagon

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp
This PR renames the intrinsic wrappers to have a more consistent convention. Here's the convention I used:
- Sequences of operations are read in "application order", i.e. a saturate followed by a truncate would be trunc_satuh, intended to be read more like trunc(satuh(...))
- I used 'mul' for non-widening multiply, and kept 'mpy' for widening multiply, I couldn't think of anything else consistent.
- Saturations are defined by the type they saturate to, e.g. satub = saturate to unsigned bytes. However, it does not imply a truncation, so usually saturation appears with a trunc following the saturate. The reason for this is to distinguish between trunc and pack, which both only keep the saturated result, but with different interleaving behavior.
=> [Hexagon] Rename intrinsic wrappers

src/CodeGen_C.cpp, src/CodeGen_Internal.cpp, src/CodeGen_Internal.h, src/CodeGen_LLVM.cpp, src/IR.cpp, src/IR.h, src/IROperator.h
This PR uses Halide IR to define our euclidean division instructions, which makes them take advantage of CodeGen specializations (e.g. overridden handlers for shifts and bitwise ops).
=> Further refactoring of CodeGen_LLVM's Div visitor.

src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
If left to LLVM, double widening/narrowing generate long unoptimized LLVM shuffles. This change rewrites double widenings/narrowings as two stage casts, which can be lowered to optimized instructions.
@pranavb-ca , I hope you don't mind, I'm pretty sure that this generates the same code as the double narrowing saturating shift implementation you just added. Please take a look.
=> [Hexagon] Handle double widening/narrowing

src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
Although I ended up not needing this for camera pipe, I got far enough with it to see that it wouldn't be too hard to finish them.
Note that while I tested the 32 x 16 bit multiplies, there's no patterns for them currently. They're difficult to expose because they start catching lots of other multiplies that should fall through to CodeGen_Hexagon. Fixing this is going to require a refactoring at some point. But, the mul.vw.vw gets used currently.
=> [Hexagon] Add mul.vw.vw implementation

apps/camera_pipe/camera_pipe.cpp
This adds a Hexagon schedule to the camera pipe app. It is basically a clone of SCHEDULE=12 from hexagon-interleave.
Rather than port the changes to the CCM, I just changed it to 16 bit, which should work fine, and enables it to use 16 bit widening multiplies: https://github.com/halide/Halide/pull/1119/commits/5d00c6fbf91c68b0caa9d2a0afd964283805b0b1
This works, and produces the output image in a few minutes running on the simulator! I'm not even sure we need a small image version.
=> Add Hexagon schedule to camera pipe

src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h
This refactors CodeGen_LLVM's generation of shuflevector operations, which will enable backends to intercept them and replace them with more optimized instructions. It also just makes it a bit easier to do (the ConstantInt noise is moved to one place).
=> Refactor shufflevector generation

src/AllocationBoundsInference.cpp, src/BoundsInference.cpp, src/Func.cpp, src/Func.h, src/ScheduleFunctions.cpp, test/correctness/force_onto_stack.cpp
This augments Func::bound in two ways:
1) Allocation sizes respect it, so that you can force an allocation to be a constant size. This means that bound constrains the bounds allocated as well as the bounds computed, which is a change to previous behavior.
2) The min can be undefined, which makes it possible to bound things that are compute_at somewhere.
=> Stronger Func::bound

src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h
This PR rewrites interleave vectors to be simpler. The main change is to make it so interleave_vectors takes llvm::Values instead of Exprs (and doesn't take a type, which was redundant information). This enables it to be implemented recursively, which simplifies the implementation quite a bit.
This does change how interleavings of 4 vectors of types less than or equal to 32 bits get lowered to llvm IR. Previously, there was a special case for this, pairs of two adjacent vectors would get interleaved, then the results of those two interleavings would get interleaved with 2x the bit width of the type. Now, these interleavings get lowered by the general case, which interleaves the even and odd vectors independently, then interleaves those vectors.
I wasn't able to find any performance …
=> Rewrite interleave_vectors

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, test/correctness/simd_op_check.cpp
This PR adds a pattern for 16 bit vector-by-scalar widening and accumulating multiplication. This is a bit weird because this instruction Hexagon also saturates, which is unfortunate. However, 32 bit signed integer overflow is undefined in Halide, and this is such a useful pattern for so much code, I think it's worth adding.
@abadams what do you think about this?
=> [Hexagon] Add pattern for vmpyhsat_acc

tools/halide_image.h, tools/halide_image_info.h
halide_image_info.h is quietly included at the *end* of halide_image.h,
which is just an abomination. Remove this, and require clients who want
halide_image_info.h to explicitly include it instead. (Add the
appropriate include of halide_image.h to the top of
halide_image_info.h.)
=> Remove halide_image_info includes

src/Func.cpp, src/Func.h, src/Function.cpp, src/Schedule.cpp, src/Schedule.h, src/StorageFlattening.cpp, test/correctness/reorder_storage.cpp
This PR adds a scheduling directive which allows the user to pad an internal allocation up to a specified alignment. This is useful for architectures that have strong alignment requirements for efficient memory access.
=> Add align_storage directive

apps/camera_pipe/Makefile, apps/camera_pipe/camera_pipe.cpp
This PR changes the camera pipe so scheduling is controlled by the target, rather than a schedule parameter.
It also fixes an underflow issue where random white pixels were generated by unsigned arithmetic in the demosaic wrapping around 0. The fix is to convert the input data to be signed, which matches the C implementation.
=> Camera pipe fixes and schedule improvements

apps/support/Makefile.inc
This removes a large number of harmless-but-annoying warnings when building test_apps for OS X
=> Add -fvisibility=hidden flag to OS X apps/ builds

src/BoundsInference.cpp, src/Expr.h, src/Function.cpp, src/FuseGPUThreadLoops.cpp, src/IRPrinter.cpp, src/InjectHostDevBufferCopies.cpp, src/Profiling.cpp, src/ScheduleFunctions.cpp, src/SelectGPUAPI.cpp, src/Target.cpp, src/VaryingAttributes.cpp
I think that only loops that are directly involved in GPU scheduling should be explicitly marked as such, and that regular loops in the body of GPU kernels should remain "Parent" loops.
The motivation for this is that many optimizations need to respect GPU loops, and when all loops that run on a GPU are labelled GPU loops, the optimizations can't run, even though the loop has nothing to do with GPU scheduling.
=> Don't propagate device APIs to parent loops

apps/HelloHexagon/Makefile, apps/HelloHexagon/pipeline.cpp, apps/HelloHexagon/process.cpp
This also removes the boundary condition hack, so the hexagon pipeline is very slow compared to the CPU. @pranavb-ca @ronlieb please take a look.
=> [Hexagon] Add CPU benchmark of HelloHexagon pipeline

apps/HelloHexagon/Makefile, apps/HelloHexagon/pipeline.cpp, apps/HelloHexagon/process.cpp, src/AlignLoads.cpp, src/CodeGen_Hexagon.cpp, src/CodeGen_Hexagon.h, src/CodeGen_Posix.cpp, src/CodeGen_Posix.h, src/HexagonOptimize.cpp, src/HexagonOptimize.h, src/runtime/hexagon_host.cpp, test/correctness/simd_op_check.cpp
(Reopened from #1167)
This PR adds optimizations to use vlut instructions in 3 situations:
- Constant shuffles that are not otherwise handled, e.g. stride 3 loads (common when processing packed RGB images).
- "Dynamic shuffles" resulting from clamped ramp loads, which arise in boundary condition code.
- Up to 256 element lookup tables.
This cuts the runtime of HelloHexagon from 0.7 s to 0.1 s, on the simulator this reduced the number of cycles from 26e6 to 7.8e6. This is despite the boundary condition code only running on 1/8th of the image.
This required changing the schedule of HelloHexagon to avoid out of bounds reads, which is a problem I'll need to figure out how to solve.
This change also adds the ability to more easily run HelloHexagon on the simulator.
=> [Hexagon] Use vlut for shuffles, LUTs, and boundary conditions

apps/camera_pipe/camera_pipe.cpp, src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
This PR uses a 256 element LUT instead of a 1024 element LUT for the tonemap in the camera pipe app, which can use vlut instructions on Hexagon.
Unfortunately, this is currently slower than the existing implementation, because there's a dumb shuffle getting through which ends up scalarizing. It's a *really* dumb shuffle:
%967 = shufflevector <32 x i16> %966, <32 x i16> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef,
i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 …
=> [Hexagon] Use linear interpolation of 256 element LUT for camera pipe tonemap

apps/support/Makefile.inc, src/CodeGen_Internal.cpp, src/CodeGen_Internal.h, src/CodeGen_LLVM.cpp, src/LLVM_Output.cpp
For the apps, I needed the additional ldflag for local runs. Let me know if there are any issues with adding it.
Preliminary testing show no impact on apps performance.
=> Add LLVM taget-based optimization. Enable vectorization.

tutorial/lesson_09_update_definitions.cpp
lesson_09_update_definitions.cpp:
comments in Case 2 and Case 3 in the examples relating to "reduction as a consumer in a producer-consumer pair" had typos - used the word producer when consumer was needed to describe the location of the producer code with respect to consumer code
=> update comments in lesson_09_update_definitions.cpp

src/AddImageChecks.cpp, src/Bounds.cpp, src/FindCalls.cpp, src/Function.cpp, src/Function.h, src/IR.cpp, src/IR.h, src/IRVisitor.cpp, src/InjectImageIntrinsics.cpp, src/InjectImageIntrinsics.h, src/InjectOpenGLIntrinsics.cpp, src/Lower.cpp, src/Memoization.cpp, src/Pipeline.cpp, src/RDom.h, src/Reduction.cpp, src/Reduction.h, src/Solve.cpp, src/StorageFlattening.cpp, src/Tracing.cpp, test/correctness/reduction_non_rectangular.cpp
We use reference counting to track memory. This is a problem for update
definitions where a Func recursively calls itself. We used to deal with
this by reducing the reference count appropriately, but the self-
reference can now appear in other ways (e.g. the predicate of an RDom),
which makes this approach no longer work in certain deletion orders.
This PR instead allows Call nodes of call type Halide which do not
contain a pointer to a Function object. Or more precisely, they now have
a nullable pointer (an IntrusivePtr<FunctionContents>) instead of a non-
nullable one (a Function). The self-references in an update definition
have these set to null.
This makes our pipelines acyclic by construction, so reference counting
works. However this unfortunately means that the func field of a …
=> No self references in updates

src/runtime/opengl.cpp
The function was not creating a TextureInfo struct for the wrapped
texture, which would result in an error when halide_opengl_run()
looked up the TextureInfo object for the wrapped texture.
=> Fixes a bug in halide_opengl_wrap_texture().

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/MatlabWrapper.cpp, src/MatlabWrapper.h, src/runtime/metadata.cpp, src/runtime/runtime_internal.h, test/generator/metadata_tester_aottest.cpp
This is a useful precondition for fixing Issue #879: we want to ensure
that the metadata accessed at runtime also is vetted thru the
halide_can_use_features() function.
(Note that this a breaking change to the public API, but one that is
trivial to fix, and will probably affect very few users.)
=> Access metadata via getter functions, rather than as extern global vars

src/CodeGen_GPU_Host.cpp, src/Memoization.cpp, src/PartitionLoops.cpp, src/Pipeline.cpp, src/RDom.h, src/Solve.cpp, src/TrimNoOps.cpp, src/Util.cpp, src/Util.h, src/Var.cpp, test/performance/profiler.cpp
Long running processes that created many RDoms would use more and more
memory due to tracking the unique names of their RVars. Overhauled
unique_name to avoid this sort of problem using a bloom filter-style
approach. There are some fixed number of atomic counters used to
generate suffixes, and prefixes map to one of those counters via a hash
function. Hash collisions just mean that multiple prefixes may share the same
counter, so no keys are stored.
=> Simpler unique name

src/CodeGen_OpenGL_Dev.cpp, src/Util.cpp, src/Util.h
It required an lvalue as first argument, which was mutated in-place as
well as returned (as a copy) as the result. This is inconvenient (since
you may want to pass rvalues as first arg) and dangerous (since you may
not want the input arg mutated in-place).
=> Util::replace_all() shouldn't mutate source string

src/Generator.cpp, src/Generator.h
This shows up as pipelines failing a type check in matlab if the
generator's build() method changes the type of an imageparam.
=> Emit correct metadata if params are mutated during build()

src/Target.h, src/runtime/HalideRuntime.h
Work for Issue #879 requires exposing Features to a runtime function;
rather than relying on parsing Target’s string form, let’s make the
Features into supported runtime features (as we already did with
Halide::Type).
=> Move Features enum to HalideRuntime.h

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/IRPrinter.cpp, src/Module.cpp, src/Module.h, src/Pipeline.cpp, src/StmtToHtml.cpp, test/correctness/specialize.cpp, test/correctness/trim_no_ops.cpp
All existing use was possible via the accessors and mutators, so make
the public members private. Also change list iteration to use C++11
style iteration.
(Purely stylistic and maybe overkill, but it was bothering me.)
=> Minor style cleanup for Module

src/Generator.cpp, src/Output.cpp, src/Output.h, src/Pipeline.cpp, src/Pipeline.h
— Move the logic from Pipeline::compile_to into the (new)
Outputs::compile_module_to() function
— Rework the other functions in Outputs.cpp to use compile_module_to()
as appropriate, rather than replicating the logic
— Rework GeneratorBase::emit_filter() to build a Module explicitly,
then use the compile_module_xxx() calls directly (rather than going
thru the equivalent Pipeline wrappers)
The motivation for this change is primarily to make some upcoming
changes for Issue #879, but as a nice side-effect it avoids a number of
redundant compile_to_module() calls in the Generator code path.
=> consolidate Pipeline compile_to logic

tools/halide_image_io.h
- Added PGM support for reading/writing graymaps
- Improve performance of reading/writing PPM pixmaps
- Allow for building in environments that don't have libpng (define -DNOPNG)
- Allow for building in environments without full C++11 STL (define -DNOSTL11)
=> Add PGM support to load_image/save_image

Makefile, src/CMakeLists.txt, src/StaticLibrary.cpp, src/StaticLibrary.h, src/Util.cpp, src/Util.h, test/internal.cpp
Work for #879: add a way to combine .o files into .a files to simplify
downstream consumption of multi-architecture output that can’t easily
be linked directly by LLVM at this time.
=> Add utility to produce .a files

Makefile, apps/wavelet/Makefile, src/Generator.cpp, src/Module.cpp, src/Module.h, test/correctness/simd_op_check.cpp, tutorial/lesson_15_generators_usage.sh
This is a bit of hygiene: the -r parameter (for “generate the runtime
only”) should omit the .o, and have it added as appropriate downstream.
Justifications for this:
(1) That’s the pattern for other outputs of this rule
(2) on Windows, it should be .obj, not .o
(3) once static library support is finished, this will allow us to
specify the output as library via the -e format instead
=> GenGen -r param should not take .o suffix

src/CodeGen_Posix.cpp, src/CodeGen_Posix.h
This PR has some changes/cleanups to CodeGen_Posix:
- Allocate scalars without attempting to reuse a stack allocation, to help LLVM promote them to registers.
- Allow backends to customize the extra allocation padding, instead of hardcoding one extra scalar.
- Free allocations if there is no early Free, instead of asserting that a Free node existed.
=> CodeGen_Posix refactoring

src/Func.cpp, src/Func.h, src/Lower.cpp, src/Schedule.h, src/StorageFolding.cpp, src/StorageFolding.h, src/runtime/HalideRuntime.h, src/runtime/errors.cpp, src/runtime/runtime_api.cpp, test/correctness/storage_folding.cpp
This PR adds an explicit fold_storage scheduling directive, which enables storage folding on pipelines where the automatic storage folding optimization fails. The last new test is an example of such a pipeline (a stencil on a downsampled image).
=> Add fold_storage scheduling directive

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/Module.h
This PR adds LoweredArgument, which stores alignment info and passes it into LLVM.
Unfortunately, there's not a good way to directly test this change (aside from being sure it doesn't break existing functionality). I'm trying to split this off from the hexagon2 branch, it is a frequent source of merge conflicts.
=> Add LoweredArgument

HalideGenerator.cmake, apps/camera_pipe/CMakeLists.txt, apps/glsl/CMakeLists.txt
— use CMake’s detection for OpenMP instead of assuming all non-MSVC
systems provide it (recent Mac clang does not)
—  change if-not-MSVC to if-Linux in apps/glsl due to X11 link
requirements
=> Fix CMake-on-Mac builds

src/Module.cpp, src/Util.cpp, src/Util.h
The code in Module::compile() can be subject to race conditions when
building in parallel (e.g. if there are duplicate rules that attempt to
make the same file); add a utility to safely create a unique temporary
file and use it to avoid this problem.
(Note: Windows code believed to be correct but not yet compiled or
tested.)
=> Add file_make_temp() utility

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/IR.cpp, src/IR.h, src/Simplify.cpp, src/Solve.cpp, src/Util.cpp, src/Util.h, test/error/overflow_during_constant_folding.cpp
This was causing the prover to prove false things (see the new test in
Solve.cpp)
=> Catch signed integer overflow during constant folding

tutorial/lesson_15_generators_usage.sh
The documentation of the generator options was incorrect/out of date.  
In particular: 
* It said "complete" but is missing some options (including the `-r` option which is actually used later in this file)
* The description of the `-e` option said it specifies "additional" things to emit but in fact it specifies the complete set of things to emit; so using, e.g. `-e stmt`  suppresses the default outputs.
Updated  it to agree with the actual behavior, based on the source code AFAICT.
=> Update description of generator options

src/Bounds.cpp, src/IR.cpp, src/IR.h, src/IROperator.h, src/Monotonic.cpp, src/PartitionLoops.cpp, src/ScheduleFunctions.cpp, src/Solve.cpp, src/TrimNoOps.cpp
We have a heuristic in ScheduleFunctions that decides whether or not to
apply a likely on the base for the ShiftInwards tail strategy. This is
to trade off code size vs performance. It was pretty broken in a bunch
of cases. The basic problem is that you can't tell at that point what's
going to be an innermost loop. This PR defers the decision until loop
partitioning time, which is after vectorization and unrolling. This
unfortunately required a new variant of likely.
likely always partitions a loop
likely_if_innermost converts to likely if it's in an innermost loop
(after vectorization and unrolling). Otherwise it just goes away.
Note that this doesn't necessarily mean we'll partition the innermost
loop. This would be bad, e.g. if it's a small loop over a convolution
kernel inside a large …
=> Defer inject-likely on shiftinwards heuristic until loop partitioning

apps/camera_pipe/camera_pipe.cpp
Fixes/nukes x86 schedule, and improves locality by computing things at vectors of the output or by line buffering them per strip of output. On arm goes from 26ms to 21ms. Similar gains (relative to using the ARM schedule) on X86.
The old x86 schedule was just garbage.
Also uses some explicit storage folding.
The motivation for this is to both speed up the app (which is often used as a benchmark), and to both provide an example and get better testing coverage for sliding window and storage folding.
=> Reschedule camera pipe

src/runtime/mini_opengl.h, src/runtime/opengl.cpp
This commit modifies `halide_opengl_run()` to save and restore
state that's modified by the runtime.  Note that we don't know
if this is comprehensive, so further pieces of state may need
to be saved/restored.
This fixes #1165 and #1166.  PTAL.
=> Save and restore OpenGL state when running a pipeline.

src/HexagonOptimize.cpp, test/correctness/logical.cpp
When trying to move interleaves through casts, we need to skip over the boolean vector to avoid attempting to interleave it.
=> [Hexagon] Fix assert for boolean comparison simplifications

src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_OpenGL_Dev.h
Integers immediates (signed and unsigned) are cast at
variable declaration time in CodeGen_C, but GLSL requires
a constructor instead of cast.
This makes all but the `opengl_shifted_domain` test pass,
mostly resolving #1252.
=> Opengl fix immediate codegen

apps/camera_pipe/camera_pipe.cpp
This pulls Andrew's line buffer schedule from master, and adds an HVX schedule. This is pretty quick and dirty, it needs some comments at least if we want this to be an example for HVX.
It improves performance on the simulator slightly, I suspect the difference will be bigger on real hardware (where memory access patterns actually matter).
=> [Hexagon] Line buffer the camera pipe schedule

src/CodeGen_C.cpp, src/Generator.cpp, src/Generator.h, src/PartitionLoops.cpp, src/Target.cpp, src/Target.h, test/correctness/compile_to_multitarget.cpp, test/correctness/cross_compilation.cpp, test/correctness/target.cpp
Converting strings to targets always felt wonky to me. This is a proposed simplification of the API that just adds an explicit Target(string) constructor, and provides a separate way to validate target strings.
=> Simplify target <-> string API

src/Pipeline.cpp, src/Pipeline.h
This PR stops caching inferred arguments, and uses the lowered body to validate the arguments, so it can grab global images added during lowering.
This enables lowering passes to add global "images" to the function, which enables things like GPU targets to be implemented during lowering (instead of a custom codegen implementation!).
=> Infer arguments after lowering to grab new global images

src/runtime/HalideRuntime.h
Some function prototypes did not tag structs properly for compiling
with a C compiler.
=> HalideRuntime should compile as C

src/CodeGen_OpenGL_Dev.cpp, src/runtime/opengl.cpp
This fixes the rest of #1252.  Now all OpenGL tests pass, and we should consider having Travis run these if possible.
PTAL at the texture load/store code in particular, for correctness.
=> OpenGL: Fix remaining tests

Makefile, src/Module.cpp
e.g., stmt files and suchlike. This is a little awkward (since multiple
files are output for these vs. a single output for .h and .a) but
probably the least weird solution here.
Note that .o files are still forbidden here: it’s not really useful and
potentially wrong without extra effort.
=> Upgrade compile_multitarget() to output 'extra' files when requested

src/VectorizeLoops.cpp
Recent changes didn’t consider the fact that index_type could already
be a vector type, so constructing Broadcast or Ramp exprs of that type
would fail.
(Unfortunately I’m not sure how to replicate this with existing tests;
I found it while compiling some complex google-specific code. This is a
possible fix but better suggestions welcome.)
=> VectorizeLoops can attempt to broadcast/ramp vectors

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
This PR implements u32 x u16 -> u32 multiplication. It also required moving some of the logic for generating multiplications to OptimizePatterns (from CodeGen_Hexagon). 
@pranavb-ca @ronlieb @dpalermo please take a look. In particular:
- Please check my implementation of mul.vuw.vuh, maybe it could be faster. I just used two u16 x u16 -> u32 widening multiplies, shifted the higher order bits up by 16, and added the two. vw.vh has an instruction for 32 x 16 bit multiplies that works here, I didn't see something similar for vuw.vuh...
- I removed our ability to generate 32 x 8, vector x scalar multiplication, 32 x 16 will get used instead. Is 32 x 16 slower? I think it might actually be a bit faster, if the scalar isn't compile time constant, since it needs to be broadcasted to 32 bits with …
=> [Hexagon] Implement u32 x u16 -> u32 multiplication

src/Simplify.cpp, src/VectorizeLoops.cpp, test/correctness/vectorize_guard_with_if.cpp
Previously it scalarized entirely. Now it generates a likely all-true
case so that it doesn't have to.
Required a new simplification.
=> Make vectorize+GuardWithIf work

src/runtime/metal.cpp
If no device/queue is created, the destructor for releasing the device
will cause an assertion failure.  This fixes #1282.
=> Fix crash on exit in metal backend

src/HexagonOffload.cpp
If defined, use this to find the hexagon-clang tool. If not, fall back
to HL_HEXAGON_TOOLS/bin/hexagon-clang.
=> Add optional HL_HEXAGON_CLANG env var

python_bindings/python/BoundaryConditions.cpp
Hello,
as I was porting a little project from C++ to the new Python binding, I stumbled upon the problem that the boundary condition functions did not accept `Func` and bounds parameters. (And this was marked as not-yet-implemented in the source: [`BoundaryConditions.cpp:166`](https://github.com/halide/Halide/blob/d9f2d8f62173f00bde47f9971d543e26f6bdce44/python_bindings/python/BoundaryConditions.cpp#L166))
I've added the missing functions; while I have not extensively tested it, some quick tests have proven it working for me.
Best regards, Christian Sachs
=> Python: Added boundary condition functions accepting bounds parameters

src/runtime/opengl.cpp
Previously the trace listed all the values that were being saved and restored, cluttering up (IMHO) the output with info not likely to be useful for understanding/debugging halide pipelines.  E.g.:
```
Saved OpenGL state:
active texture: 33984
program: 0
viewport: (0, 0, 1340, 1060)
cull face: 0
depth test: 0
[…]
Restoring OpenGL state:
active texture: 33984
program: 0
viewport: (0, 0, 1340, 1060)
cull face: 0
depth test: 0
```
This PR reduces the trace to just
```
Saved OpenGL state
[…]
Restoring OpenGL state
```
=> Reduce trace output for Save/Restore OpenGL state.

src/CodeGen_X86.cpp, src/runtime/x86_avx.ll, src/runtime/x86_sse41.ll
This hopefully fixes the tests for trunk llvm (some intrinsics were removed).
It turned out to be simplest to consolidate a bunch of code into select handling logic.
=> Fix min/max handling for llvm trunk

src/HexagonOptimize.cpp
@dsharletg PTAL
Globals that depended on other globals (the small int cache, which I have deleted) were causing static initialization order woes.
=> Avoid static initialization order problems

src/SlidingWindow.cpp
This is a change @abadams suggested a while back, I'm now finding it necessary. This reduces the amount of code generated by Halide quite significantly (and improves compile times) while not significantly impacting performance.
=> Use likely_if_innermost for sliding window warmup branch

src/HexagonOffload.cpp
Reduces compile time of app of interest from 4.5 minutes to
less than 10 seconds.
Note:
- The llvm default for LSR complexity is UINT16_MAX
- When compiling for Hexagon, this is changed to UINT16_MAX*10
- The exact setting of this limit could be increased if
performance is not sufficient with the llvm default setting
=> Set LSR complexity limit back to the LLVM default

src/Simplify.cpp
Simplify mins and maxes of ramps where the base has constant bounds, e.g:
for x from 0 to 4:
min(ramp(x, 1, 4), broadcast(0, 4))
=> Simplify more clamped ramps

src/CodeGen_Hexagon.cpp, test/correctness/interleave_rgb.cpp
This improves codegen for 3 way interleaves significantly. This required supporting > 256 element vluts for static indices.
This also adds a correctness test specifically for 8 bit RGB interleaves (in addition to the existing interleave test), since it is such a common use case.
=> Use vlut for 3 way interleaves in Hexagon

apps/HelloHexagon/Makefile, src/HexagonOffload.cpp, src/runtime/HalideRuntimeHexagonHost.h, src/runtime/hexagon_host.cpp
Running make didn't work. Mostly because HexagonOffload.cpp makes uint64
expressions, but the runtime expects size_ts.
=> Fix HelloHexagon 32-bit build

src/HexagonOffload.cpp
This reverts commit 6468f065fb3f2e4f0e0ba566b3543a94d6f6f7b4.
=> Revert "Set LSR complexity limit back to the LLVM default"

src/HexagonOffload.cpp
llvm.org's build of hexagon-clang does not have hvx enabled by default, so in 64 byte mode we need to ask for the hvx feature, much like we ask for the hvx-double feature for 128 byte mode.
This allows 64 byte toyCamera to compile vector IR properly.
=> pass -mhvx as its not the default on tip

src/Expr.h, src/Func.cpp, src/Target.cpp
Added Hexagon handler to supports_device_api and all_device_apis + invalidates caches when hexagon scheduling directive is called. 
@dsharletg  Could you please take a look at this PR? I'm not sure if you're intentionally skip to add the Hexagon.
=> add Hexagon to supports_device_api and all_device_apis

src/PartitionLoops.cpp, test/correctness/specialize.cpp
This PR fixed bugs in PartitionLoops where epilogue runs before start of the loop. However,
the fix makes some cases that was simplifiable previously not simplifiable due to the additional `max(..., loop_min)`, e.g. `for (out.s0.x.x, max((out.extent.0/4), 0), (((out.extent.0 + 3)/4) - max((out.extent.0/4), 0)))`
=> fixed bugs in PartitionLoops epilogue runs before start of the loop

src/runtime/HalideRuntime.h, src/runtime/can_use_target.cpp, test/generator/multitarget_aottest.cpp
weak-symbol-based overriding doesn't work well on Windows or mingw, so
the generator tests all use function-pointer-setting instead.
This is part of my ongoing quest to get mingw working again.
@steven-johnson ptal
=> Add a setter for a can_use_target_features function pointer

src/PartitionLoops.cpp, test/correctness/partition_loops.cpp
This PR fixed bugs in partition loops to ignore condition that refer to unallocated buffer as in correctness/partition_loops.cpp. One of the conditions for partitioning `f.s0.x` depends on `g[0]` (e.g. `((f.s0.x + g[0]) <= 1023)`) which is only allocated inside `f.s0.x`. The original code will use this condition as part of the epilogue/prologue which causes symbol not found error.
=> bugs fixed partition loops should ignore ref to unallocated buf

src/AllocationBoundsInference.cpp, src/Func.cpp, src/IROperator.h
Bug fixes: added user asserts in Func::bound and bitwise ops to check that they should take integers as arguments
=> func bound and bitwise ops should only take integers

src/CodeGen_Hexagon.cpp
In HVX 128 mode, the vlut instruction requires 4 vlut calls per LUT vector: the even/odd elements of the lower half of the vector, and the even/odd elements of the upper half of the vector. Prior to this PR, if the LUT used any of the vector, we called vlut all 4 times, even if the LUT only needed the 2 vlut instructions for the lower half of the vector.
=> Reduce the number of vlut instructions

src/runtime/mini_opengl.h, src/runtime/opengl.cpp, test/opengl/save_state.cpp
Avoid clobbering the client's OpenGL state.  This is particularly important when the client wraps textures, to use the Halide filter in the context of a larger OpenGL application.
This PR extends the work done in #1257:
* It saves and restores more state (including: framebuffer binding, array buffer binding, texture binding, active texture, vertex attribute array status)
* It includes a test case
* The implementation now uses RAII style for cleanliness and simplicity
* It replaces previous ad-hoc "cleanups" which bound things to 0 rather than restoring the original values.
The first commit (ec7a096) is a cherry-pick and squash of the commits from #1374 that add linking with OpenGL to the `test_opengl` suite tests and disable building them on travis.
=> Save & restore OpenGL state

src/runtime/HalideRuntime.h, src/runtime/fake_thread_pool.cpp, src/runtime/gcd_thread_pool.cpp, src/runtime/thread_pool_common.h
If n < 0, call halide_error() everywhere.
if n == 0, use a “system-determined” number of threads.
if n == 1, ensure that there is no thread parallelism anywhere (by
special-casing the iOS/OSX GCD threadpool).
if n > 1, use a thread pool of size n (except on iOS and OSX).
This allows testing/benchmarking to ensure single-CPU-core behavior by
calling halide_set_num_threads(1) regardless of platform.
=> enforce halide_set_num_threads(n) behavior for n <= 1 (Issue #1371)

src/LoopCarry.cpp
Suppose we have more than one identical load in a for loop that
are identical, then we should group them together so that if we
ecide to replace them with a load from a scratch buffer, we'll be
able to replace all of these identical loads.
@abadams @dsharletg : PTAL.
=> Handle the rewrite of multiple identical loads in Loop Carry.

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, test/correctness/simd_op_check.cpp
This PR adds patterns for Hexagon to use vpacko, which take the upper half of a wider type, without interleaving. The deinterleaving versions are still generated when it is more efficient to do so (it can cancel out an interleave).
=> Add more non-interleaving versions of downcasts

src/Simplify.cpp
This PR adds simplification rules to pull terms that are a multiple of the divisor out of a ternary expression, namely the following cases:
```
check(((x*4 + y) + z) / 2, x*2 + (y + z)/2);
check(((x*4 - y) + z) / 2, x*2 + (z - y)/2);
check(((x*4 + y) - z) / 2, x*2 + (y - z)/2);
check(((x*4 - y) - z) / 2, x*2 + (0 - y - z)/2);
check((x + (y*4 + z)) / 2, y*2 + (x + z)/2);
check((x + (y*4 - z)) / 2, y*2 + (x - z)/2);
check((x - (y*4 + z)) / 2, (x - z)/2 - y*2);
check((x - (y*4 - z)) / 2, (x + z)/2 - y*2);
```
=> Simplify const division of a ternary expression

src/AllocationBoundsInference.cpp, src/BoundsInference.cpp, src/Func.cpp, src/Func.h, src/Inline.cpp, src/Schedule.cpp, src/Schedule.h, src/ScheduleFunctions.cpp, test/correctness/align_bounds.cpp
Add a much-discussed directive to forcibly align or misalign the bounds of a computation/realization. See the test for an example. This useful for code that does interleaving. If you want a select(x%2==0, a, b) to simplify away, you can say:
f.align_bounds(x, 2).unroll(x, 2);
This forces the min and the max-plus-one of the computation to a multiple of the argument.
This is also probably useful to help generate code that does aligned loads and stores.
=> Align bounds

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, src/HexagonOptimize.h, src/Simplify.cpp
When writing an algorithm that performs multiple similar but slightly different lookups on a LUT, the code has two issues:
- The index has a redundant widening/narrowing cast
- We generate different LUT vectors for the LUT, e.g. x[ramp(0, 1, 256)] and x[ramp(1, 1, 256)]. The latter generates slice_vectors, and can't be re-used for both lookups.
This PR fixes these issues.
=> Fix redundant work in vlut lookups on Hexagon

src/Func.cpp, src/Func.h, test/correctness/implicit_args_tests.cpp, test/error/implicit_args.cpp
Fixed bugs in args_with_implicit_vars: implicit vars are not properly inserted for update definition. 
This PR also allows usage of implicit vars for update definition of a function which does not already have a pure definition, like in the following:
```
h(x, y) = x + y;
f(x, _) += h(_) + 2;
```
This is equivalent to:
```
f(x, _0, _1) = 0
f(x, _0, _1) += h(_0, _1) + 2
```
=> fixed bugs in implicit_args

src/HexagonOptimize.cpp
It's better to generate a widening multiply accumulate than an explicit widen followed by a shift-accumulate.
=> Reorder multiply and shift accumulate patterns for HVX

src/runtime/printer.h, src/runtime/to_string.cpp
Fixed off by one error in halide_int64_to_string that could result in
writing a byte to the end location, which does not seem to be
correct. (And caused a crash in testing this.)
Tested change by turning on CACHE_DEBUGGING in src/runtime/cache.cpp then
running the command:
HL_JIT_TARGET=host-debug make correctness_memoize
=> Fix printer.h to not crash when malloc returns nullptr.

src/Module.cpp, src/Util.cpp, src/Util.h
This embeds randomness into the contents of the output from build to
build, which is bad for hermeticity of build products. Instead, create
a unique directory for the temporary files; the directory name isn’t
reflected in the final .a output.
=> Don't use temporary-file names for archive members

src/Module.cpp, test/generator/multitarget_aottest.cpp
Building with NoAsserts doesn’t allow propagation of nonzero results.
Also add a test for this to multitarget_aottest.cpp
=> Multitarget wrapper should build with Asserts enabled

src/Bounds.cpp, src/Simplify.cpp, test/correctness/cascaded_filters.cpp
In merge_boxes(), keep min and max simplified as we go along.
Add new simplifier rules that targets patterns often emitted by
specialize() conditions.
Don’t consider NaN a “simple const”.
=> Improve simplification

src/Param.h, src/Parameter.cpp, src/Parameter.h
— remove initialized and default_val, which were totally unused (except
with also-unused accessor methods for the latter, which are now also
gone)
— group the bool fields together at the end of the struct for trivial
memory savings
— drive-by constification of fields that are const after construction
=> Parameter cleanup

src/CodeGen_OpenGL_Dev.cpp, src/InjectOpenGLIntrinsics.cpp, src/VectorizeLoops.cpp
OpenGL used vector texture loads followed by shufflevectors to extract
lanes. This made the vectorize pass very difficult. This PR changes
texture loads to look more like a multi-dimensional scalar load, and
makes codegen handle the various cases instead.
@shoaibkamil
=> Don't use vectors before Vectorize

test/correctness/fuzz_simplify.cpp
Otherwise, failures are hard to reproduce across different systems
=> Use std::mt19937 instead of rand() in fuzz tester

Makefile, src/CMakeLists.txt, src/FuzzFloatStores.cpp, src/FuzzFloatStores.h, src/Lower.cpp, src/Target.cpp, src/Target.h, src/runtime/HalideRuntime.h, test/correctness/fuzz_float_stores.cpp
When the FuzzFloatStores target feature is on, the LSB of all floating
point stores is set to zero before storing.
Because we apply (and tell LLVM to apply) -ffast-math style floating
point optimizations in a target-specific way, you can't rely on Halide
code producing exactly the same outputs on every platform for code that
uses floats. This new target features is intended to flush out tests
that make this bad assumption. If a test passes with FuzzFloatStores
off, but fails with it on, it's likely to also fail on different
architectures.
There are probably all sorts of more elaborate ways to fuzz floating
point computations, but we've found that this surprisingly simple method
works well for finding the bad tests and has few false positives.
=> Add a target feature that fuzzes floating point stores

src/CodeGen_Hexagon.cpp, src/CodeGen_Internal.cpp, src/CodeGen_LLVM.cpp, src/CodeGen_OpenCL_Dev.cpp, src/EliminateBoolVectors.cpp, src/EliminateBoolVectors.h, src/HexagonOptimize.cpp, src/IR.cpp, src/IR.h
... so that the intermediate IR is well-formed and produces the same
results on every platform. Now on Hexagon and OpenCL we promote bool
vectors to multi-bit "masks" immediately after creating them (with a
comparison). This is codegenned as a no-op, because that's what the
comparisons do natively. All of the bits of a mask must be zero when it
represents a false value. True values are represented by architecture-
specific values (0x01 in every byte on hexagon, 0xff in every byte on
opencl). There is a cast and a select equivalent that work on these
masks. They must be implemented per-backend in a way that works with
that backend's representation. Logical operators are handled with
bitwise operators.
Storing a mask, or casting it to an actual int, forces it to be zero or
one, because at …
=> Rework EliminateBoolVectors

src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_OpenGL_Dev.h, src/InjectImageIntrinsics.cpp, src/VaryingAttributes.cpp, test/opengl/inline_reduction.cpp
This adds some level of support for Allocate/Load/Store nodes (e.g. due to an inline reduction) inside GLSL kernels. It doesn't generate amazing GLSL, but it seems to work for some simple cases.
@shoaibkamil @ronen PTAL
=> Support allocations (arrays) inside GL kernels

src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_OpenGL_Dev.h, src/InjectImageIntrinsics.cpp, src/PartitionLoops.cpp, src/VaryingAttributes.cpp, test/opengl/inline_reduction.cpp
Builds on #1427 
This PR just turns off the loop partitioner for GLSL loops. It's not clear loop partitioning is a good idea, given gl control flow constraints. The underlying issue here that made things break was that the loop partitioner expects a loop over threads inside the loop over blocks, and there isn't one with GLSL. GLSL should probably represent its magic loops in some other way, instead of using our block variables for Cuda/OpenCL.
=> Glsl loop partitioning

src/CodeGen_LLVM.cpp, src/CodeGen_X86.cpp, src/FastIntegerDivide.cpp, src/FastIntegerDivide.h, test/performance/const_division.cpp
Uses the support for fast vectorized division by small constants and the
Euclidean identity to make a fast vector modulus. Should speed up
storage folding by non-power-of-two factors.
@dsharletg
=> Add support for fast vectorized modulus

src/Func.cpp, src/Func.h, src/Function.h, src/Generator.h, src/Schedule.cpp, src/Schedule.h, src/ScheduleFunctions.cpp
LoopLevel will be useful for some upcoming scheduling work (e.g. where
you need to specify compute_at or store_at via a lambda), so promote it
out of Internal namespace and:
— give it properly typed ctors and hide the data members
— add compute_at() and store_at() overloads that accept one
— reimplement all other
compute_at()/store_at()/compute_root()/store_root() implements to use
the LoopLevel-based one
=> Promote LoopLevel to public type

src/Generator.cpp, src/Generator.h, test/generator/nested_externs_generator.cpp, test/generator/tiled_blur_generator.cpp
These have never been used outside of Halide test code, and are never
likely to be. Remove them and replace with define_extern() usage for
now. (We’re need a better syntax than define_extern(), but this isn’t
it.)
=> Remove Generator::call_extern() and call_extern_by_name()

python_bindings/python/Image.cpp, python_bindings/python/Param.cpp, src/Func.h, src/IROperator.cpp, src/IROperator.h, src/RDom.h, src/Tuple.h, src/Util.h, tools/halide_image.h
Using this approach is more verbose but more robust. See (e.g.)
http://eli.thegreenplace.net/2014/perfect-forwarding-and-universal-refer
ences-in-c/
=> Revise PR#1448 to use C++11 Perfect Forwarding

src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_OpenGL_Dev.h, test/opengl/sumcolor_reduction.cpp
by inlining IntImms where possible, by being more clever about how we scalarize access to a vector, and by using variables for small allocations that are always accessed at constant offsets.
Also allows non-const access to the channels of a loaded vector (via []).
=> Generate less openGL source

src/CodeGen_OpenGL_Dev.cpp, src/CodeGen_OpenGL_Dev.h, test/opengl/conv_select.cpp
GLSL uses functions for vector comparisons, so this PR implements them for the supported operations in GLSL.  Fixes the bug reported by Lee Yuguang ("Can't do color channel synthesis using select after convolution").
=> Generate proper GLSL for vector comparisons.

HalideGenerator.cmake, Makefile, test/CMakeLists.txt
Only nested_externs actually needed it. (Ditto GENERATOR_NAME in CMake.)
=> remove unnecessary -g arg from most generator calls

src/runtime/opengl.cpp, test/opengl/user_state_check.cpp
It comes up reasonably often that a user gets tripped up when Halide reports a mystery OpenGL error, such as: `Error: OpenGL error GL_INVALID_ENUM(1280) at halide_opengl_init GenFramebuffers.`.  It seems like an internal error in Halide, and in some cases it can be extra mysterious because of things like (as in this case) `GL_ENVALID_ENUM` isn't even a documented error for `glGenFramebuffers`.
Those cases often turn out that the user made an OpenGL error and didn't check it using `glGetError()` -- so the OpenGL error flag remains set, and next time Halide performs an operation (which doesn't fail) then calls `glGetError()`, Halide gets the user's error and reports it as its own.
This PR addresses that by having Halide call glGetError() on initial entry, and report the error as "user …
=> User OpenGL state check

src/Associativity.cpp, src/Simplify.cpp, src/Solve.cpp, src/Solve.h, src/TrimNoOps.cpp
This PR changes solve_expression to return a pair of boolean indicating whether the solve is successful and a partially solved expression, instead of returning undefined Expr if it can't solve the expression. For example, `max(min(y, x), x)` will return {false, `max(min(x, y), x)`} instead of `Expr()`. 
This also adds new simplification rules for: 
```
min(x, y)*max(x, y) -> x*y
min(x, y) + max(x, y) -> x + y
```
=> Return partially solved expr instead of undefined

test/opengl/save_state.cpp
Vertex array objects are only present (and used by Halide) on OpenGL >= 3.0.  This uses logic from the runtime to only check state saving/restore for VAOs for OpenGL versions that support them.
Also fix formatting: tabs-> 4 spaces.
CC: @ronen
=> OpenGL: fix state save test

src/Module.cpp
This PR adds support for Matlab in multitarget builds. It continues to require that all of the targets have the Matlab feature. However, it then removes the Matlab feature from the subobjects, and then adds the Matlab feature to the wrapper pipeline. This way, we only generate one mexFunction, that properly dispatches to the appropriate subobject.
=> Add Matlab support for multitarget builds

src/runtime/hvx_128.ll, src/runtime/hvx_64.ll
There are a bunch of multiply-adds and shift-adds that Hexagon has instructions for that we can use to optimize 32 bit multiplications. These helped by quite a lot, performance taken from the mul_div_mod_test with HVX64 (HVX128 sees a similar proportional reduction in cycles):
u32 x u32: 482k -> 417k simulated cycles
u16 x u32: 708k -> 578k simulated cycles
=> Use accumulating shifts and multiplies to optimize 32 bit multiplications

src/Simplify.cpp
Add simplification rules for:
```
select(c, min(a, b), min(a, d)) -> min(a, select(x, b, d))
select(c, max(a, b), max(a, d)) -> max(a, select(x, b, d))
etc.
```
=> Add simplification rules for select(c, min(a, b), min(a, d))

src/CMakeLists.txt
If it fails, crater with a fatal error; otherwise, we can fail much
later in the build process with inscrutable-seeming link errors.
=> Check result of llvm-config call in CMake build

src/HexagonOptimize.cpp, src/Simplify.cpp
Reverts halide/Halide#1435.
I don't think there's actually a bug in this code, but it is triggering a very difficult to debug codegen bug that is blocking updating Halide. We need to revert this temporarily so we can move forward with other work, and I'll need to try to diagnose the codegen issue in parallel.
=> Revert "Lazy slice vectors"

src/Solve.cpp
Bug fixes for solver: a_failed/b_failed flags are not swapped when the variables are
=> Fixed bugs where failed flags are not swapped when the variables are

src/Target.cpp, src/Target.h, test/correctness/target.cpp
Target.h promises that Target(t1.to_string()) == t1, but this fails if
t1 == Target(), sinces bits == 0. Add just enough special-casing to
allow this to roundtrip as well.
=> Allow roundtripping of default Target() strings

src/Target.cpp
Also tweaked some formatting.
It now looks like:
$ ./lesson_15_generate -g my_first_generator -o . target=foo
Error at ../tools/GenGen.cpp:4:
Did not understand Halide target foo
Expected format is arch-bits-os-feature1-feature2-...
Where arch is: arch_unknown, arm, hexagon, mips, pnacl, powerpc, x86.
bits is either 32 or 64.
os is: android, ios, linux, nacl, noos, os_unknown, osx, qurt, windows.
If arch, bits, or os are omitted, they default to the host.
Features are: armv7s, avx, avx2, c_plus_plus_name_mangling, cl_doubles, cuda
cuda_capability_30, cuda_capability_32, cuda_capability_35, cuda_capability_50
debug, f16c, fma, fma4, fuzz_float_stores, hvx_128, hvx_64, hvx_v62, jit
large_buffers, matlab, metal, mingw, no_asserts, no_bounds_query, no_neon
no_runtime, opencl, opengl, …
=> Add missing "bits" field to invalid Target error message.

src/Util.cpp
Uses `_NSGetExecutablePath()` from `mach-o/dyld.h` and preprocessor conditionals
=> Enable Halide::Internal::running_program_name() on Apple

src/LLVM_Headers.h, src/LLVM_Output.cpp
LLVM has a symbol rewriter pass which enables symbol interpositioning.
Enable this pass in Halide, to allow code generation to use it.
=> Enable symbol rewriter pass

src/CodeGen_ARM.cpp, src/Target.cpp, src/Target.h, src/runtime/HalideRuntime.h
It's useful to be able to explicitly specify that we want to target a
soft float ABI.
=> Add explicit soft float target feature

src/Type.h
RIght now, type_of<>() is in an anon namespace inside the Halide
namespace. Move directly into Halide namespace and explicitly inline.
=> move type_of<>() out of anon namespace

src/Generator.cpp, src/Generator.h, test/generator/pyramid_aottest.cpp
Existing version relied on enable_if’s everywhere; this splits it into
helper classes, so adding methods will be less horribly wordy.
=> Rework GeneratorParam implementation

src/BoundsInference.cpp, src/BoundsInference.h, src/Lower.cpp, src/ScheduleFunctions.cpp, test/generator/msan_aottest.cpp
Specifically, we need to mark the synthesized buffer_t inputs as
initialized
=> MSAN needs to handle bound-inference too

src/Func.cpp, test/correctness/rfactor.cpp
This PR fixes a bug where the key of `substitution_map` should use the full name of the `RVar`. The bug can be reproduced using `multi_split_rfactor_test()` in `test/correctness/rfactor.cpp `. In the following statement,
```
intm2 = g.update(0).rfactor({{rxo, u}, {ryo, v}});
```
`rxo` can pass the initial check in `rfactor()` API, but the variable won't be substituted successfully when creating the update definition of the intermediate function as `substitute()` works based on exact string matching.
=> Fixed a bug in Stage::rfactor()

Makefile, test/CMakeLists.txt, test/generator/pyramid_generator.cpp
— restructure the Makefile to give a little more flexibility for
upcoming Generator changes: pre-generator GenGen.o, filter-in instead
of filter-out in rules. (No-op for current code, but will reduce the
diff noise for upcoming changes)
— update the Pyramid generator test to require that a param is set
correctly
=> Generator Makefile fixes

src/CodeGen_ARM.cpp
LLVM >=3.7 lowers this to the correct intrinsics in the interleave access pass.
=> Update ARM code generation of strided loads to generic vector code.

src/Generator.cpp, src/Generator.h, src/Module.cpp, src/Module.h
In addition to replacing the extensions used (e.g., ".txt" instead of
".s"), it's useful to be able to replace the default suffixes of
auxiliary files (rather than using the target string) in certain build
environments.
=> Upgrade GenGen's -x argument

src/Simplify.cpp
Fixed the issues described in #1524.
One of the simplification passes in LT, `(c1 < c2 - x) -> (x < c2 - c1)`, does not check if "x" is actually a constant, hence causing the infinite ping-ponging between `c1` and `x` as seen in the following example:
`x2(-16) < (ramp(uint16(7), uint16(11), 2) - x2(1)) -> x2(-1) < (ramp(uint16(7), uint16(11), 2) - x2(16)) -> x2(-16) < (ramp(uint16(7), uint16(11), 2) - x2(1)) -> etc`
=> Lt simplify bugs

Makefile, test/opengl/conv_select.cpp, test/opengl/copy_pixels.cpp, test/opengl/copy_to_device.cpp, test/opengl/copy_to_host.cpp, test/opengl/float_texture.cpp, test/opengl/inline_reduction.cpp, test/opengl/lut.cpp, test/opengl/multiple_stages.cpp, test/opengl/produce.cpp, test/opengl/rewrap_texture.cpp, test/opengl/save_state.cpp, test/opengl/select.cpp, test/opengl/set_pixels.cpp, test/opengl/shifted_domains.cpp, test/opengl/special_funcs.cpp, test/opengl/sum_reduction.cpp, test/opengl/sumcolor_reduction.cpp, test/opengl/varying.cpp, test/renderscript/aot_copy.cpp, test/renderscript/aot_copy_error.cpp, test/renderscript/jit_copy.cpp
test/opengl and test/renderscript requires the build system to set
HL_TARGET and/or HL_JIT_TARGET correctly; it’s simpler and more robust
to set the Target features we need inside the tests, and not require
the build/test harness to do it. (Makefile did set them correctly, but
CMake never did.)
Also loosen error on sum_reduction a bit.
=> make OpenGL and RenderScript tests less env-var dependent

src/Func.h
Just a code-replication detail that was bothering me.
=> Rewrite evaluate() Tuple variants using parameter-pack expansion

Makefile
AFAICT, this is never used, and doesn’t work with standard build
instructions for LLVM. (If this *is* used by some code somewhere, let’s
ignore this and add appropriate comments and build instructions.)
Also, driveby removal of LLVM_OLD_JIT_COMPONENT.
=> Remove USE_LLVM_SHARED_LIB from Makefile

tools/build_halide_h.cpp
Currently it inlines runtime_internal.h into Halide.h… but this code
should never be used since it’s only ifdef COMPILING_HALIDE_RUNTIME.
Let’s not tempt users by exposing stuff that we don’t want exposed.
=> build_halide_h should skip runtime_internal.h

src/IRPrinter.cpp
Fix for ProducerConsumer IRPrinter: consumer should not be indented
=> Fixed indentation in ProducerConsumer IRPrinter

src/CodeGen_OpenCL_Dev.cpp
- Similar to PTX, where 'noalias' is added to help alias analysis. In OpenCL,
'restrict' is used instead.
=> [OpenCL] Add `restrict` modifier on buffer arguments

Makefile, test/CMakeLists.txt, test/generator/matlab_generator.cpp
Dancing on the target inside the Generator is a Bad Idea and hard to
support in Bazel; set the target flag in the build file(s) instead
=> Revise matlab_generator test

src/runtime/HalideBuffer.h
Add a deallocate method matching allocate that makes it possible to drop the memory associated with a Buffer without losing its shape.
Also added a way to add a new extent-1 dimension with a user-specified stride. This lets you do crazy things like interpret a grayscale image as if it were an interleaved-format color image that just happens to have only one channel.
=> Add two new methods to Halide::Buffer

src/Lower.cpp, src/Pipeline.cpp, test/correctness/set_custom_trace.cpp
`output.compute_root().store_root()` should not be done in Pipeline constructor; otherwise, it will mess up with the compute_at/store_at. Consider the following example: 
```
f(x) = x;
g(x) += f(x);
f.compute_at(g, x);
f.set_custom_trace(allocation_bound_test_trace);
g.realize(10);
```
`f.set_custom_trace()` creates a new pipeline that will nuke `f.compute_at(g, x)` causing `f` to be computed at root. 
In this PR, the `compute_root()`/`store_root()` reset on output functions is done after `deep_copy()` inside lowering.
=> Compute root reset at lowering

src/Generator.cpp, src/Generator.h
I tried to be clever and make an enhanced RegisterGeneratorAndStub
class that would fail at linktime (rather than runtime) if the
necessary Generator wasn’t present; this was overly complicated and (as
it turns out) error prone, since multiple instantiations of the same
templated class may not behave as I expected. Switch back to the
simpler-to-understand runtime-failing code.
=> Simplify overly-clever Stub registration code

src/CodeGen_Hexagon.cpp
It's a bit more efficient to interleave the indices of a vlut (a single uint8 vector) instead of the results (a uint16 double vector). This only applies to LUTs with uint16 elements, uint8 elements don't have any interleaving/deinterleaving.
=> Interleave vlut indices instead of the results.

HalideGenerator.cmake, test/CMakeLists.txt
the aot test for stubuser had been omitted; adding it revealed that
CMake builds for stubs were broken (not linking in the dependent
generator libs)
=> Fix CMake for Stubs

apps/camera_pipe/camera_pipe_generator.cpp
No impact on x86, did not measure ARM.
On Hexagon, simulated cycles go from 13.84e6 to 11.77e6. I'm guessing this is due to improved instruction level parallelism (I started doing this because I happened to notice bad instruction pipelining here) and reduced loop overhead.
=> Improve camera pipe schedule

src/Generator.cpp, src/Generator.h
If you try to create a nonexistent Generator, list the ones we know
about as part of the error. Also document that the create() methods
never return null and remove redundant null checks at a couple of call
sites.
=> Improve generator-not-found error

CMakeLists.txt, HalideGenerator.cmake, src/CMakeLists.txt, test/CMakeLists.txt
Disable a grab bag of compiler/linker warnings that are irrelevant
=> Reduce CMake-on-Windows noise

CMakeLists.txt, src/Util.h
Our stack size flag was lost at some point resulting in stack overflows
on windows. Given that this is also a frequent user question, it seems
better to force the linker flag on inside something that ends up in
Halide.h
=> Fix windows stack size

src/DeviceInterface.cpp, src/runtime/HalideBuffer.h, src/runtime/HalideRuntime.h, src/runtime/device_interface.cpp
using the magic of extern_weak, symbols become null rather than
undefined references
=> Make it possible to use Halide::Buffer without a runtime linked

src/Associativity.cpp, src/Associativity.h, src/Func.cpp, src/Func.h, test/correctness/rfactor.cpp, test/error/rfactor_inner_dim_non_commutative.cpp
Added a pass to check for commutativity of an operator in rfactor. When rfactoring an inner dimension of a non-commutative operator (e.g. subtraction), it is required for the containing outer dimensions to be rfactored as well; otherwise, it will change the order of operation. 
For example, for the following definition:
```
g(x, y) = 40;
g(x, y) -= f(r.x, r.y);
RVar rxi("rxi"), rxo("rxo");
g.update(0).split(r.x, rxo, rxi, 2);
```
The following schedule is okay:
```
Var u("u");
g.update(0).rfactor(rxo, u);
```
But not the following:
```
Var u("u");
g.update(0).rfactor(rxi, u);
```
If it had been `g(x, y) += f(r.x, r.y)` instead, then the second schedule is okay.
=> Rfactor on inner dims should check for commutativity

test/correctness/simd_op_check.cpp
This is needed to generated code patterns such as:
check("v*.ub = vpack(v*.h,v*.h):sat", hvx_width/1, u8_sat(i16_1));
The upcoming LLVM Hexagon 8.1 release assembly generation has removed
spaces around assignments.  This change allows simd_opt_check to correctly
work when run against 8.0, 8.1, or llvm.org tip (which is closest to 8.0
at the moment but will soon be picking up 8.1 functionality).
=> Have simd_op_check wildcard_match also ignore spaces in patterns or strings

src/Func.cpp, test/error/init_def_should_be_all_vars.cpp
The previous Func value assignment only checked for whether the args are all variables, but it didn't check if the variables refer to RVar or not.
=> Func value assignment should check for RVar

src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
This patch adds the ability to generate vmpa instructions. So, for the following
3 * vector0 + 4 * vector1
we generate
vmpa(vcombine(vector0, vector1), 0x34343434)
@dsharletg, @ronlieb, @dpalermo : PTAL
=> Vmpa for hvx

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
We really need the 16 bit version of vmpa more than the 8 bit version. This adds the 16 bit version of the instruction. Rather than add a new pattern matching flag that is only used by this instruction, I just matched it manually instead, and did the same thing for the 8 bit instruction (for consistency).
I also thought we could do away with the post process adds (and handle them normally), but that is the easier way to do it.
=> Add support for vmpa for 16 bit vector operands.

.gitignore, apps/HelloAndroid/.gitignore, apps/HelloAndroid/build.gradle, apps/HelloAndroid/build.sh, apps/HelloAndroid/jni/Android.mk, apps/HelloAndroid/jni/native.cpp, src/LLVM_Runtime_Linker.cpp
build.sh is broken and has been for a while:
— Minor syntactic errors in native.cpp prevent any build from working
— Profiler runtime doesn’t work on MIPS; rework linker code to only
attempt to link it in for non-MIPS, non-NoOS cases
(Note that the Android Studio/Gradle support is still broken, and I
don’t know how to fix it; support for JNI in AS/G has changed and I
don’t know what the status quo is. IMHO we’d be better off scrapping it
entirely in favor of a Bazel-based solution.)
=> Fix HelloAndroid MIPS build

src/runtime/osx_opengl_context.cpp
Having extern “C” wrapped around the definition of the internal symbols meant that their unmangled names were visibile at global scope.  
In particular, that meant these symbols intending to hold function pointers to the corresponding functions when looked up dynamically:
`Halide::Runtime::Internal::OpenGL::CGLChoosePixelFormat`
`Halide::Runtime::Internal::OpenGL::CGLCreateContext`
`Halide::Runtime::Internal::OpenGL::CGLDestroyPixelFormat`
`Halide::Runtime::Internal::OpenGL::CGLSetCurrentContext`
Were actually shadowing the symbols of the functions themselves, causing trouble for programs that directly call those functions outside Halide.
Fixes #1635
=> Remove extern “C” from symbols in  Halide::Runtime::Internal::OpenGL

apps/HelloAndroid/build.gradle, apps/HelloAndroid/jni/Android.mk, apps/HelloAndroid/src/com/example/hellohalide/CameraPreview.java, apps/HelloAndroidCamera2/HelloAndroidCamera2.iml
renaming the native module to match the apk name (“libHelloAndroid.so”
instead of “libnative.so”) turns out to be easier to support in Bazel
at the present time; since it’s abitrary elsewhere, just use that
convention everywhere. (Also some driveby fixes to ndk-build calls in
Gradle which were just happening to work before.)
=> Rename HelloAndroid native module

src/runtime/HalideRuntimeMetal.h, src/runtime/metal.cpp
ObjC “.m” files don’t have C++ enabled in all compiler configs, so we
should restrict this API to use plain C conventions to maximize
compatibility.
=> halide_metal_acquire_context() decl should be plain C, not C++

src/ApplySplit.cpp, src/Func.cpp, test/correctness/bounds_inference_outer_split.cpp
Changes the behavior of TailStrategy::Auto in some cases. See issue #1618 for the full discussion. Also moves error handling for bad tailstrategies earlier (scheduling time, instead of lowering time).
=> Select tail strategy

src/BoundaryConditions.h
In most cases, it doesn’t matter; however, Input<> and Output<> types
(deliberately) don’t have copy ctors, but are convertible to Func or
Expr. Converting usage to const-ref lets them participate without overt
casting required.
=> BoundaryConditions should take args by const-ref

src/Expr.h, src/IR.cpp, src/IR.h, src/IntegerDivisionTable.cpp, src/IntegerDivisionTable.h, src/Reduction.h, src/Schedule.h
Compiling in a stricter mode revealed a few minor things:
— virtual functions but no virtual dtor
— missing #includes
— classes should not be only-forward-declared class if they are used in
inline code in a way that could invoke ctors/dtors
=> Fix grab-bag of minor bugs found by Blaze

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, test/correctness/simd_op_check.cpp
This PR adds support for vmpyh instructions that also multiply by 2, keep the high half, and optionally round.
=> Add patterns for some more multiply instructions on Hexagon.

Makefile, test/CMakeLists.txt, test/generator/stubtest_aottest.cpp, test/generator/stubtest_generator.cpp, test/generator/stubtest_jittest.cpp, test/generator/stubuser_generator.cpp
We had testcases for tuple-outputs and array-outputs, but not for the
common case of neither. Add that, update tests, and rationalize names.
=> Add simple output to StubTest, rationalize names

src/HexagonOffload.cpp, src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
Several enhancements to Halide::Buffer motivated by real-world usage.
Most notably there's a for_each_value that iterates over the values
without tracking coordinates. This produces very efficient inner loops,
and copy and fill are now implemented using this.
Also added a method for testing if a coordinate is contained within the
region of a buffer, added a method to cast a Buffer reference to a
buffer reference of another type, and added a static method to create a
buffer with the same shape as another buffer.
=> Buffer enhancements

src/LLVM_Runtime_Linker.cpp
LLVM >= 4.0 should prefer explicit llvm::expectedToErrorOr().
=> Update llvm error handling

src/CodeGen_LLVM.cpp, src/IROperator.cpp, src/IROperator.h, src/runtime/HalideRuntime.h, src/runtime/errors.cpp, src/runtime/runtime_api.cpp, test/correctness/require.cpp
require() is essentially a runtime assertion; it verifies that an Expr
satisfies a precondition (terminating via halide_error() if it does
not).
Since this inserts runtime checks, it needs to be used with caution:
inserting into an inner loop could severely degrade performance.
The intended use is for:
— preconditions on Param<> inputs that need failure rather than silent
clamping
— debugging, in situations where print()/print_when() aren’t adequate
— in the future: unit testing, via enhancements to Generator
=> Add require() operator

src/runtime/HalideBuffer.h
Otherwise explicitly calling deallocate() could lead to double-frees
later.
(Note: do we need a similar fix in device_deallocate()?)
=> Buffer::decref()/decref_dev() need to null alloc and buf.host

Makefile, src/CodeGen_GPU_Host.cpp, test/CMakeLists.txt, test/generator/acquire_release_generator.cpp, test/generator/cxx_mangling_aottest.cpp
We never name-mangled the external functions if the target had a GPU
feature; we never noticed this because we didn’t attempt to test it.
=> fix C++ name-mangling for GPU targets

Makefile, tutorial/lesson_10_aot_compilation_generate.cpp, tutorial/lesson_10_aot_compilation_run.cpp, tutorial/lesson_16_rgb_run.cpp, tutorial/todo.txt
We now want people to always just use Halide::Buffer. Encouraging people
to use naked buffer_t was a mistake - everyone just wrote their own
wrapper classes.
=> Remove buffer_t from tutorials

src/runtime/HalideBuffer.h
Astonishingly, this was caught by nvcc, of all compilers.
/attn @abadams
=> Set correct return type for Buffer::translated

src/OutputImageParam.cpp, src/OutputImageParam.h, src/Parameter.cpp, src/Parameter.h
I need to re-use it for Generator purposes; mostly-decoupling it from
OutputImageParam makes that less weird. (“Mostly” because we still
grant friend access for ctors, though frankly, we could probably just
make them public)
=> Move Dimension from OutputImageParam into Parameter.h

src/Func.cpp, src/Func.h, src/Pipeline.cpp, src/Pipeline.h, src/Tuple.h, test/correctness/multiple_outputs.cpp
The natural way to realize into multiple existing buffers currently is
to put them in a temporary Realization:
f.realize({im1, im2});
This doesn't do precisely you want (it used to, before the Buffer
change). The Realization constructor makes a copy of those buffer
objects that it can own, so you'll lose any mutation of the metadata
(e.g. device allocations). It's also different to this:
f.realize(im1);
which takes im1 by reference and updates the metadata
This PR adds a new realization-like class that collects an array of
mutable references to existing buffers. It's a temporary type solely
used for passing groups of buffers to realize and infer_input_bounds. It
changes the meaning of
f.realize({im1, im2})
to take im1 and im2 by reference, the way it used to be.
=> Fix realizing into multiple existing buffers

apps/openglcompute/Makefile, apps/openglcompute/jni/Application.mk, apps/openglcompute/jni/oglc_run.cpp, apps/openglcompute/jni/oglc_two_kernels_run.cpp, apps/openglcompute/test_oglc_avg.cpp, apps/openglcompute/test_two_kernels.cpp, apps/simd_op_check/Makefile, src/CodeGen_OpenGLCompute_Dev.cpp
Made it use Halide::Buffer.
While doing this I discovered that the vector support in OpenGLCompute
codegen was broken, and made a dangerous assumption anyway (all vector
access is aligned), so I neutered it for now. It needs a pass that
actually detects if all buffer access is aligned dense vectors, and if
so, declares the buffer as an array of vectors.
=> Fix openglcompute app

Makefile
We compile the runtime modules to .ll for a "generic" target at -O3.
Apparently in some circumstances this autovectorizes to 128-bits. Not
all vector types are supported by all targets (hexagon), so this is bad,
and can cause assertion failures inside LLVM during instruction
selection. This PR turns this off.
The .ll gets a second chance to autovectorize later in codegen once the
module is assembled and has a concrete target.
=> Disable early autovectorization of runtime

apps/blur/halide_blur_generator.cpp, apps/blur/test.cpp
Add GPU schedules based on different strategy for blur.
=> Add GPU schedule for Blur (targeted GTX 970)

src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/widening_reduction.cpp
This PR has a number of improvements to the eliminate interleaves optimization in Hexagon:
- The old optimization was a bit too conservative about when it removed interleaves, it would fail to see opportunities to remove interleaves through Let and LetStmt.
- Simplified the logic around dealing with boolean/mask vectors.
- The optimization now attempts to deinterleave buffers which are only stored interleaved and deinterleaved upon being loaded from. This means that reductions which widen, followed by usages that narrow the result, will be deinterleaved. 
- To make it easier to implement, moved some crufty logic to implement trunc_satuh(vw) to the runtime.
This significantly impacts some workloads, the widening reduction test drops in simulated cycles by ~1/3.
=> Deinterleave storage

src/HexagonOptimize.cpp, src/runtime/hvx_128.ll, src/runtime/hvx_64.ll, test/correctness/simd_op_check.cpp
This PR adds support for the 32 bit doubling multiply keep high half instructions on Hexagon.
@ronlieb @dpalermo please take a look. Do you know of a way to implement the non-doubling multiply without an extra shift? I didn't see the relevant instructions.
=> Add 32 bit multiply-keep-high-half instructions for Hexagon

src/CSE.cpp, test/correctness/cse_load_in_predicated_store.cpp
Previously, if a Let with a value that was a Load was encountered
in one of the intrinsics related to predication, it would cause
an assertion to be raised in CSE. (See #1704).
=> CSE: Let inside predicated intrinsics when value is a Load

Makefile, apps/HelloAndroid/jni/hello_generator.cpp, apps/fft/fft_generator.cpp, src/Generator.cpp, src/Generator.h, src/Parameter.h, src/runtime/HalideBuffer.h, test/CMakeLists.txt, test/generator/metadata_tester_aottest.cpp, test/generator/metadata_tester_generator.cpp, test/generator/msan_generator.cpp, test/generator/nested_externs_generator.cpp, test/generator/stubtest_aottest.cpp, test/generator/stubtest_generator.cpp, test/generator/stubtest_jittest.cpp, test/generator/stubuser_aottest.cpp, test/generator/stubuser_generator.cpp, test/generator/tiled_blur_blur_generator.cpp, test/generator/tiled_blur_generator.cpp
Currently, you are disallowed from using `ImageParam` with new-style Generators; this is problematic for Generators that need to make scheduling decisions based on attributes of the underlying Buffer. 
We could just allow ImageParams back in, but:
- syntactically this is weird
- we need something for `Output<>` as well, and using `OutputImageParam` for this is even weirder syntactically
This PR proposes to add `Input<Buffer<>>` and `Output<Buffer<>>` to new-style Generators:
- `Input<Buffer<>>` and `Output<Buffer<>>` autoconvert to `Func` (just like `ImageParam`), but also provide methods to set constraints on the required min/extent/stride of the underlying Buffer, and to get the actual min/extent/stride from the underlying Buffer.
- Buffer type can be specified either statically (via …
=> Add Input<Buffer> and Output<Buffer> to Generator

src/Float16.cpp, src/LLVM_Headers.h
All LLVM includes should go via that route, to suppress warnings. Also
added a missing cast-to-uint16.
=> Move llvm #includes out of Float16.cpp and into LLVM_Headers.h

src/Type.h
Currently there is a mixture of ‘int’ and ‘uint8/uint16’; compiling
with -Wconversion or equivalent can generate lots of spurious warnings.
Standardize on ‘int’ for the argument type and return value.
=> Type should use consistent types for bits, lanes params

test/correctness/constant_expr.cpp, test/correctness/lerp.cpp, test/correctness/math.cpp, test/generator/embed_image_aottest.cpp, test/generator/float16_t_aottest.cpp, test/generator/mandelbrot_aottest.cpp, test/generator/matlab_aottest.cpp, test/generator/pyramid_aottest.cpp, test/generator/user_context_insanity_aottest.cpp
Mostly double-to-float and int-to-float “possible loss of precision” —
fixed by changing constants to be float or inserting explicit casts.
None look at risk of meaningful failure, except for the
float_16_t_aottest, which was actually just wrong.
=> Grab-bag of MSVC conversion warning fixes

src/Argument.h
Convention elsewhere (e.g. Param) is to use int for dimensions, rather
than uint8; using int avoids conversion-warnings at point of call in
some compile configs
=> Argument ctor should use int for dimensions

src/CodeGen_Internal.cpp, src/CodeGen_Internal.h
All call sites were passing it an int64; truncating to int32 can
generate conversion warnings in some compiler configurations.
=> can_allocation_fit_on_stack() should accept an int64

src/CodeGen_X86.cpp
Remove a workaround which is no longer needed starting from LLVM 4.0.
=> [X86] Disable workaround for LLVM bug which was fixed in LLVM 4.0

Makefile
Two changes to the makefile:
1) When building the static library, only re-extract objects from libLLVM if the list has changed since last build. This reduces linking time from 52 seconds down to 12 seconds on mingw (there are nearly a thousand of them, and extracting them is slow)
2) The shared library doesn't depend on the static library. When building the tests, you shouldn't need to rebuild the static library. Reduces time spent linking the static library from 12 seconds down to zero if you're just running a JIT test.
=> Faster build

src/JITModule.cpp, src/JITModule.h, src/Pipeline.cpp, src/Pipeline.h
Move the variant that is always an
extern-c-function-address-and-signature into its own class; this will
be useful in subsequent revisions to SharedJITRuntime code, but is
being split into a separate PR for easier review
=> Split JITExtern into two classes

src/CodeGen_Internal.cpp, src/runtime/HalideRuntimeHexagonHost.h, src/runtime/hexagon_host.cpp, src/runtime/runtime_api.cpp
It was intended as a convenience for certain Hexagon testing tasks, but
it turns out to be simpler to override halide_load_library() +
halide_get_library_symbol() for those purposes.
=> Remove halide_hexagon_host_get_symbol()

src/Type.h
made from other types via methods on the Type class when it make
sense to do so. This fixes a bug that broke the JavaScript support and
likely makes C++ name mangling unreliable.
(Could just have checked in the fix, but going through a PR to get the Travis run.)
=> Ensure that the handle type info is propagated to variants of types

src/runtime/posix_error_handler.cpp, src/runtime/printer.h, test/generator/msan_aottest.cpp
Stack memory used for logging/errors is unknown to MSAN, which can flag
false-positive failures inside (e.g.) the halide_print() callback.
Since MSAN intercepts memset(), using that to initialize the stack
memory in these case corrects these false positives.
=> Add memset() calls to fix MSAN failures

src/AddImageChecks.cpp, src/runtime/HalideRuntime.h, src/runtime/errors.cpp, src/runtime/runtime_api.cpp, test/generator/error_codes_aottest.cpp
This is never legal, but can cause surprisingly hard-to-track-down
errors.
=> Add assertion check for negative buffer extents

src/runtime/printer.h, src/runtime/tracing.cpp
It's a very minor speed-up to text-based tracing of local laplacian (2%)
This function was already allocating a page on the stack for the binary
case, and then not even using it in the text branch. May as well use it
and skip the halide_malloc call inside the printer.
=> avoid halide_malloc when tracing

src/Util.cpp, src/Util.h, test/correctness/compile_to.cpp, test/correctness/compile_to_bitcode.cpp, test/correctness/compile_to_lowered_stmt.cpp, test/correctness/compile_to_multitarget.cpp, test/correctness/constraints.cpp, test/correctness/cross_compilation.cpp, test/correctness/stmt_to_html.cpp
— Add “or_die” variations for file_exists and file_unlink
— convert several existing tests to use these instead of #ifdef for
WIN32
— ensure that all of these reliably delete the files before trying to
generate them
— stmt_to_html was just wrong for the final case
=> Cleanup tests that write tmp files (Part 1)

test/correctness/boundary_conditions.cpp
Borrow the technique from simd_op_check to improve test throughput on
typical multicore desktop machines; this reduces test runtime on my
laptop from ~30s to ~6s. Also, ensure that test functions correctly
even if assert() is disabled.
=> Improve speed of boundary_conditions on multicore machines

src/runtime/HalideBuffer.h, src/runtime/HalideRuntime.h
This is needed to fix the dreaded “MachO doesn't support COMDATs”
problem on iOS builds. Moved ALWAYS_INLINE definition to
HalideRuntime.h to accomodate.
=> Mark various methods ALWAYS_INLINE

src/CSE.cpp
Bug fix for Codegen OpenCL correctness_mul_div_mod test. If the load/store predicate is trivially true, CSE shouldn't lift it out from the expr.
=> CSE should not lift out all true predicate from load/store

src/Param.h, src/Parameter.cpp
If the Expr has no defined value, we should skip the type cast / check.
=> set_min_value() and set_max_value() should allow Expr()

test/common/halide_test_dirs.h
Putting it under /tmp/ causes race conditions in Travis (etc), as
multiple tests contend for the same dir. Instead:
— If the TEST_TMPDIR env var is defined, use it. (Bazel defines this
env var automatically.)
— Otherwise, use the current working directory (essentially reverting
to the same behavior as we used to have, but via absolute path rather
than relative).
Assert that paths must be absolute.
(Pushing out for review, but I’m going to test this locally on Windows
before committing.)
=> Revise get_test_tmp_dir()

src/Simplify.cpp
Also, driveby change to add logging for Stmt mutations as well as Expr
mutations to SImplify, and to enable/disable them via ifdef. (Fixes Issue #1760)
=> Fix simplifier bug (Issue #1760)

src/CodeGen_LLVM.cpp, src/Debug.h, src/Pipeline.cpp, src/Target.cpp, src/Util.cpp, src/Util.h, test/generator/multitarget_aottest.cpp
Checking the out-param “read” is probably fine, but better form to
(also) check the result code (which is nonzero if the var doesn’t exist
or an error occurs).
=> calls to getenv_s() should check the result code

Makefile, src/BoundsInference.cpp, src/CodeGen_C.cpp, src/CodeGen_C.h, src/Func.cpp, src/Func.h, src/Function.cpp, src/Function.h, src/Generator.h, src/ScheduleFunctions.cpp, test/generator/cxx_mangling_define_extern_aottest.cpp, test/generator/cxx_mangling_define_extern_generator.cpp
For name mangling, define_extern currently requires you to specify C
(the default) or C++ via a boolean arg. This PR makes the name mangling
setting on a define_extern stage a three-state enum:
CPlusPlus - Uses c++ mangling
C - Uses C mangling (i.e. no mangling)
Default - Use the same mangling as the pipeline being compiled (switches
based on target.has_feature(Target::CPlusPlusMangling))
The default value is "Default". This will change the default linkage on
extern stages for codebases with Target::CPlusPlusMangling on. It should
not affect any other code.
=> Make extern stage name mangling match the target by default

Makefile, src/Generator.h, test/CMakeLists.txt, test/generator/metadata_tester_aottest.cpp, test/generator/metadata_tester_generator.cpp
Specifying an Input<Buffer> or Output<Buffer> with one of type or dim
(but not both) should have worked, but didn’t. Now it does.
=> IO<Buffer> should have allowed for dim-only and type-only

src/Lerp.cpp
Just by moving some casts around. For int -> uint casts, it doesn't matter whether you do addition or subtraction before or after the casts (yay for homomorphisms), but it counts as UB if you let the overflow happen when it's signed.
=> Fix signed integer overflow in lerp

src/Simplify.cpp, src/VaryingAttributes.cpp, test/opengl/select.cpp
This change includes test cases that were failing because of issue #1781: Internal assertion failures when compiling certain select expressions for OpenGL target.
In VaryingAttributes.cpp, `CastVariablesToFloatAndOffset` was mutating the true and false branches of a select expression but neglecting to mutate the condition. And for ramp expressions, if either base or stride mutates into a float, a cast may be require to make their types match.
Also added a diagnostic message to one of the assertions that was failing.
=> Test cases and fix for issue #1781

Makefile, src/CodeGen_LLVM.cpp, src/Generator.cpp, src/Module.cpp
The code path for Generators formerly went thru compile_multitarget()
only for cases where there were multitargets; this meant that the
contents of static libraries (and the patterns of filename
substitution) could be subtly different for single- vs multi-target,
making some bugs hard to track down (since some Generator tests use
single and some use multi). Now, the code uniformly goes thru the
multitarget case; this means that a ‘wrapper’ function is now generated
for the single-target case where none was before, but in terms of code
size and speed, it’s essentially a wash (the wrapper is just the an
unconditional branch to the underlying function). This will make
subsequent changes to this code much easier to verify across all usages.
=> Remove Generator multitarget special-cases

Makefile, src/CodeGen_LLVM.cpp, src/Generator.cpp, src/Module.cpp
Reverts halide/Halide#1777
Broken Tutorial #15, and while I can fix that, there are now more special-case to this than I'd like. Reverting and rethinking.
=> Revert "Remove Generator multitarget special-cases"

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/Type.h, test/generator/cxx_mangling_aottest.cpp, test/generator/cxx_mangling_define_extern_aottest.cpp, test/generator/cxx_mangling_generator.cpp
Helps with name mangling in code using define_extern that passes
pointers to user types as arguments.
=> Add convenience macro for declaring types

src/Extern.h
The extern macros define functions in user code, where overzealous
clang-tidy linter passes are free to complain about it. We can hopefully
shut it up by just following its advice for the macro bodies.
=> Pacify clang-tidy

test/CMakeLists.txt, test/common/halide_test_dirs.h, test/correctness/simd_op_check.cpp
— use std::async instead of fork(), so we can now usefully test on
Windows. (On my Mac laptop, this runs slightly faster than the previous
fork() solution.)
— Refactor the code to be class-based, and move all globals into member
vars; this makes it much easier to reason about what is read-only vs
read-write during test execution vs test initialization
— add an extra, optional cmd line arg to allow the temp files to be
output to a particular directory; default this directory to
Internal::get_test_tmp_dir().
=> Rework simd_op_check test

test/correctness/thread_safety.cpp
OMP isn’t available on all interesting targets, so this test serializes
(and effectively hangs) on those. Explicitly spawn threads instead.
=> thread_safety test should use std::thread instead of OMP

test/correctness/mul_div_mod.cpp
Running tests in parallel speeds up wall-clock execution time of this
text ~4x on my laptop. (Driveby: denoise output, re-route errors to
stderr)
=> Use std::async to speed mul_div_mod test

test/correctness/boundary_conditions.cpp
Allows Windows usage of this test; also cleans up code a bit. (Further
de-duping is possible but unsure if worthwhile.)
=> Convert boundary_conditions test to use std::async instead of fork()

src/Module.cpp, src/Module.h, src/Pipeline.cpp
Some code assumes that functions().back() is the ‘public’ fn in a
Module, but this isn’t guaranteed and will change soon. Add a function
to look up by name and use it in a few relevant places.
=> Add Module::get_function_by_name()

src/Module.cpp, test/correctness/compile_to_multitarget.cpp
compile_to_target() now executes all calls to Module::compile() via
std::async. Speedup depends on machine, OS, number of targets, etc.,
but the compile_to_multitarget (with two targets) test goes from ~600ms
-> ~400ms on my four-core Mac. If I bump that test from 2->5 targets,
test goes from ~900ms -> ~425ms.
I tried to keep the async usage as conservative as possible, but the
possibility for thread-related bugs exists, of course. A torture-test inside Google didn’t show any problems.
=> Use std::async to speed multitarget builds

src/Generator.h, test/generator/pyramid_generator.cpp
The static_assert logic in Generator required schedule() to be an
actual member method; now it can also be a member variable (e.g.
std::function) that is filled in by the generate() method, to support
lambdas for scheduling. Modified pyramid_generator.cpp to use this
approach.
=> Allow Generator::schedule() to be a std::function member var

src/runtime/HalideBuffer.h
Otherwise, a T is implicitly convertible to a Buffer<T> (for T !=
void), e.g.:
Buffer<uint8_t> b;
const uint8_t u = 0x42;
b = u;  // this works, but is unlikely to be what you wanted
=> Add "explicit" to Buffer ctor

test/correctness/simd_op_check.cpp
simd op check was spinning up a thread for every test. This caused the OS X buildbot to barf with too many open files. I applied a similar strategy to the thread-safety test.
https://buildbot.halide-lang.org/master/builders/mac-64-391/builds/52/steps/make%20test_correctness_2/logs/stdio
=> Limit max threads in simd_op_check

test/correctness/print.cpp
AFAIK, “-nan” is not actually a thing in IEEE754, and the fact that
some printf implementations can emit this string for some bit patterns
is a bug. The test here was special-casing it for __APPLE__, but I am
seeing it in other builds too.
(Note the old comment was wrong, and should have read “OSX prints some
nan values as -nan”)
=> print test should tread "-nan" output as "nan"

src/Expr.h, src/IR.cpp, src/IR.h, src/IROperator.cpp, src/IROperator.h, src/Substitute.cpp, src/Substitute.h, test/correctness/fuzz_simplify.cpp
Convert Expr-by-value args to Expr-by-const-ref in IROperator.h; this
is motivated by reducing of temporaries (and thus stack space) for
debug/non-opt builds of Halide.
This is a very conservative change: only functions that could continue
to work unmodified were changed (if the args were mutated in any way,
pass-by-value is retained).
(It’s arguably preferable to be consistent within a file and convert
100% of the calls to const-ref, even if it means minor cleanup to the
interior code of a few methods; if reviewers prefer this be done here,
LMK)
=> Convert IROperator.h args to const-ref where trivial

tools/halide_image_info.h
— variable-length arrays are not supported by all compilers; use
std::vector instead
— The “Buffer<>” type used must be a Halide::Runtime::Buffer, but the
Runtime namespace isn’t necessarily opened; add explicitly Runtime:: to
clarify this.
=> Fix portability concerns in halide_image_info.h

test/correctness/image_io.cpp, tools/halide_image_io.h
It only tested jpg, not png or ppm, due to a misplaced return. Fixing
this revealed that the luma case can’t work for ppm (since ppm is
RGB-only); skipped it in the test and added assertion to save_ppm() to
avoid pain for future users.
=> correctness_image_io was broken

tools/halide_image_io.h
Otherwise, downstream code that assumes these calls check-fail will
break.
=> halide_image_io needs to check-fail for NO_PNG/NO_JPEG paths

src/Generator.cpp, src/Generator.h
Due to operator overloading, you could do something like
GeneratorParam<int> foo{“foo”, 1};
Input<Int> bar{“bar”, 3*foo};
This happened to compile, but was never intended to work, and probably didn’t do what you wanted (it always used the default-contructed value of the GP, rather than the possibly-different value specified in a build file).
Now we force a compile-time error if you attempt to read from a GeneratorParam before the build()/generate() method is called.
=> Prevent GeneratorParam values from being examined by Inputs/Outputs

src/IREquality.cpp, src/IREquality.h, src/Simplify.cpp
Removes another slew of temporaries in deeply-nested unoptimized
Simplify usage (Issue #1805)
=> Add a few more pass-by-ref for Expr/Stmt calls in Simplify callpaths

src/Generator.h
As of now, these fields are not intended to be settable; this was
enforced for non-Array variants, but the Array variants allowed you to
attempt this, causing a confusing compile-time message:
Output<Func[]> out{…};
….
out[0] = Func();
Previously this gave a confusing message at Generation time about
“out_1 not defined”; now this fails at C++ compile time with “no viable
overloaded ‘=‘”.
(Note that while Input<> values are always read-only, for obvious
reasons, re-assigning the Funcs for Output<> should be made legal in
general. That will happen in a subsequent PR.)
=> Array variants of Input<>/Output<> should make operator[] and at() return const refs

src/Error.cpp, src/Error.h, test/correctness/custom_error_reporter.cpp
Use a time-honored operator-precedence trick to avoid evaluating any of
the stream output for these assertions when the assertion is true. On
my four-core laptop, this gives a pretty consistent reduction in the
fuzz_simplify test from ~6.0s -> 5.6s.
(Note that if any code was previously relying on side-effects from
assertion args always being evaluated, it will break; hopefully that’s
not the case…)
Note the two TODO comments in the code; both should be resolved before
possibly landing this, so comments welcome.
=> Reduce overhead of internal_assert and user_assert

Makefile, src/CMakeLists.txt, src/Module.cpp, src/ThreadPool.h, test/correctness/boundary_conditions.cpp, test/correctness/mul_div_mod.cpp, test/correctness/simd_op_check.cpp, test/correctness/vector_cast.cpp, test/correctness/vector_math.cpp
std::async() is problematic because details are too implementation-defined. This introduces a simple ThreadPool class that provides essentially the same API as std::async, but implemented as a fixed-size pool of std::thread.
=> Add ThreadPool utility for testing & output

src/Buffer.h
Just a minor nit, but this is really what std::declval<> is intended
for, and is arguably cleaner than the declared-but-undefined static
methods.
=> use std::declval<> instead of dummy_runtime_buffer()

src/Prefetch.cpp, src/TrimNoOps.cpp, src/runtime/qurt_hvx.cpp
This PR has a few fixes for prefetching:
- Trim no-ops was removing loops that did prefetching, because prefetch was marked as a pure function.
- The Hexagon runtime function should always be inlined, otherwise, the call with the pointer parameter breaks a lot of important optimizations. Inlining also often enables the l2fetch argument to be lifted out of a loop.
- Added a (currently disabled) block of code that causes Halide to partition the loops for the prefetching bounds checking. It seemed to only have a small impact on the workload I was benchmarking. I'm considering removing this since it's dead code...
=> Prefetch fixes, avoid trimming loops that only prefetch

src/Generator.cpp, src/Generator.h
Clang and GCC can disagree about name-mangling conventions for inlined
delegating ctors (C1 , “complete object constructor” vs C2, “base
object constructor”); move the two important cases from Generator info
.cpp to avoid weird linker errors.
=> Move delegating ctors to .cpp instead of .h

src/CSE.cpp, src/IRMutator.cpp, src/IRMutator.h, src/PartitionLoops.cpp, src/Simplify.cpp, src/SimplifySpecializations.cpp, src/Solve.cpp, src/Substitute.cpp, src/UnifyDuplicateLets.cpp, src/VaryingAttributes.cpp, test/correctness/gpu_thread_barrier.cpp, test/correctness/likely.cpp, test/correctness/predicated_store_load.cpp, test/correctness/tuple_undef.cpp
On my four-core laptop, this consistently increases speed of
correctness_fuzz_simplify (seed=1486437125) by ~4%, from ~4.2s to
~4.05s when built with default (-O3) optimization.
=> Convert IRMutator::mutate methods to pass-by-ref

src/CSE.cpp, src/IRMutator.cpp, src/IRMutator.h, src/PartitionLoops.cpp, src/Simplify.cpp, src/SimplifySpecializations.cpp, src/Solve.cpp, src/Substitute.cpp, src/UnifyDuplicateLets.cpp, src/VaryingAttributes.cpp, test/correctness/gpu_thread_barrier.cpp, test/correctness/likely.cpp, test/correctness/predicated_store_load.cpp, test/correctness/tuple_undef.cpp
Reverts halide/Halide#1844, which could cause correctness problems in existing code.
dsharletg@: "When a mutator assigns expr, it may invalidate the 'op' parameter to visit (because the old value of 'expr' was the only thing holding a reference to 'op')."
The speedup is nice, but unless/until I can find a way to ensure no correctness issues occur (or can easily creep in), it's not worth the risk.
=> Revert "Convert IRMutator::mutate methods to pass-by-ref"

src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
Most of the work was moving for_each_element into the class.
I've seen this functionality desired several times internally, and now PR #1842 wants it too.
=> Add a Buffer::fill that takes a callable

Makefile, test/opengl/conv_select.cpp, test/opengl/copy_pixels.cpp, test/opengl/copy_to_device.cpp, test/opengl/copy_to_host.cpp, test/opengl/float_texture.cpp, test/opengl/inline_reduction.cpp, test/opengl/lut.cpp, test/opengl/multiple_stages.cpp, test/opengl/produce.cpp, test/opengl/rewrap_texture.cpp, test/opengl/save_state.cpp, test/opengl/select.cpp, test/opengl/set_pixels.cpp, test/opengl/shifted_domains.cpp, test/opengl/special_funcs.cpp, test/opengl/sum_reduction.cpp, test/opengl/sumcolor_reduction.cpp, test/opengl/testing.h, test/opengl/tuples.cpp, test/opengl/vagrant/Vagrantfile, test/opengl/varying.cpp
DRY up the OpenGL test suite by adding helpers `Testing::fill` and `Testing::check_result`, which are themselves wrappers around `Buffer.for_each_element`.
Also along the way cleaned up some of the tests themselves.  In particular, `shifted_domains.cpp` didn't exit with 1 in case of failure.
cc: @estollnitz @shoaibkamil
=> Opengl tests cleanup

test/correctness/loop_invariant_extern_calls.cpp
Looks like LLVM got a little more clever with LICM
=> Fix loop invariant test

src/runtime/device_interface.cpp
In the new_buffer_t_v2 branch, aot-generated files are failing to link with this error when not linking with libHalide (e.g. this is from `make test_generators`):
```
Undefined symbols for architecture x86_64:
"_halide_weak_device_free", referenced from:
_halide_get_device_free_fn in acquire_release_aottest-99d32d.o
```
This is because `halide_weak_device_free` is missing from device_interface.cpp in the new_buffer_t_v2 branch (it is present in master).
=> new_buffer_t_v2: Fix missing halide_weak_device_free function in runtime

apps/camera_pipe/Makefile, apps/camera_pipe/camera_pipe_generator.cpp, apps/camera_pipe/viz.sh, util/HalideTraceViz.cpp
Fix the camera pipe visualization. It was using an old version of the arguments to trace viz, and some of the function names were messed up.
There's still a minor problem with viz: sometimes Halide intentionally
loads out of bounds memory, and uses it to compute and store garbage
values, when it knows those values can't affect the output. These show
up as noise in the viz. This is true to what's going on, but looks
pretty distracting. The visualizer doesn't track bounds in a detailed
enough way to detect these things.
Also, tracing should be in the target, not an env var. This would let us
use the convention of ./bin/$(TARGET) for generator outputs instead of
repeating makefile rules for viz targets.
=> Fix camera_pipe viz script

src/Error.cpp
Minor, but it means that all assertion failures are uniformly printed
with newlines at end (vs the some-that-are, some-that-aren’t right now)
=> ErrorReport::explode should append a newline if needed

apps/camera_pipe/camera_pipe_generator.cpp
Small improvement in camera_pipe performance.
should the  strip_size only be set for the hexagon_target?
=> Tweak schedule for camera_pipe, ~4% improvement in hexagon cycles

src/Pipeline.cpp, test/correctness/multiple_outputs.cpp
A Pipeline with multiple outputs would always fail:
Realization contains wrong number of Images (1) for realizing
pipeline with $COUNT outputs
since this method only considered the first output.
=> Pipeline::realize() infers incorrect size for Realization

src/runtime/device_interface.cpp
seeing segv on a few tests, i think you might have to be running hexagon() to see the failures
Camera_pipe
Received archstring from environment=--l2cache_perfect 1
ARCHSTRING set l2cache_perfect = 1
make: *** [bin/out.png] Segmentation fault
a few correctness tests as well
bash: line 1: 47448 Segmentation fault      /local/mnt/workspace/bots/hexbotmaster-aus-perses-10-2/halide-82/src/halide/bin/correctness_argmax
make: *** [correctness_argmax] Error 139
=> Fix segv while running camera_pipe

src/Generator.h
As it is, this overloads won’t work with noncopyable types (e.g.,
Input<>); changing to const-ref allows this (desirable) operation.
=> binop overloads in Generator.h should use const-ref for 'Other'

Makefile
Fixes #1873 
With this PR, when using the Makefile, the folders produced are:
bin/   
jit tests, libHalide, generators
bin/build/
Build intermediates that don't depend on HL_TARGET. I.e. build intermediates for the above. 
bin/$(HL_TARGET)/
compiled aot tests that do depend on HL_TARGET (e.g. generator_aot_example), standalone runtimes
bin/$(HL_TARGET)/build
object files and build intermediates for the above (i.e. generator outputs)
=> Generator outputs and things that depend on them go into target-specific dirs

src/Generator.cpp, src/Generator.h
Some of the functionality in GeneratorStub really belonged in
GeneratorBase (e.g., GeneratorContext usage); moved code around to make
some upcoming functional changes easier to review.
=> Refactor some code from GeneratorStub->GeneratorBase

src/Generator.cpp, src/Generator.h
Formerly, several internal data structures were (theoretically)
lazily-inited based on an internal flag and explicit calls where
needed; in practice, this wasn’t actually enforced everywhere and
current usage is correct only by coincidence. Moved to a lazily created
data structure to encapsulate these to ensure the usage is predictable
and correct and to allow for some additional lazily-created structures
to be added painlessly.
=> Refactor Generator internal  Param-info lists creation

src/Generator.cpp, src/Generator.h
(Additive to PR #1876) Previously we had a very ad-hoc approach to the necessary phases that a
Generator had to go thru, with various fields attempting to minimize
misbehavior; this moves to a simple state machine to ensure Generators
aren't misused, also enabling stronger logic constraining what field can
be read/written at what point.
=> Make Generate phases explicit

src/Float16.h, src/runtime/HalideRuntime.h
The struct-based solution was giving me cross-translation-unit template
instantiation nightmares (function calls jumping to junk code and
returning an invalid halide_type_t in a complex project). I don't think
we actually need partial specialization here, so I changed it to just a
generic function and then full specializations of the function, and
force-inlined absolutely everything. That fixed my problem and seems
simpler.
=> Simplify halide_type_of

src/Generator.cpp, src/Generator.h
Implementation of ‘synthetic’ GPs (e.g., .type and .dim for
Input<Buffer>) was previously done by special-case hackery in
set_generator_param_values(); instead, create new dynamic instances of
GeneratorParam for these that are connected with the underlying Input
or Output; this makes some upcoming changes to GP/SP API much easier
and more regular.
=> Make "real" GeneratorParam instances for synthetic GeneratorParams

src/VectorizeLoops.cpp, test/correctness/tracing_broadcast.cpp
Vectorize trace call handler didn't widen the call args (for broadcast) causing garbage to be traced.
=> Tracing call should widen its call args

src/Generator.cpp, src/Generator.h
(Branched/Additive to PR#1880)
This PR improves the ability to set GP/SP values in C++, even when the
specific C++ class of the underlying Generator isn’t known in the given
C++ translation unit:
— Upgrades the GeneratorParam::set() method to take well-typed variants
of all supported C++ types; attempts to set a GP/SP with a type that
cannot be losslessly converted to the GP’s declared type will
assert-fail at Halide compilation time. This means you no longer have
to "stringly-type” when setting these programmatically, e.g.
GeneratorParam<int> foo{"foo”};
GeneratorParam<int> bar{"bar”};
…
foo.set("1”); // still works
foo.set(1); // also works!
foo.set(1.3f); // assert-fails since not valid int
— Adds GeneratorBase:set_generator_param() and
GeneratorBase:set_schedule_param(), which allows …
=> Improve ability to set GeneratorParams by C++ types

src/Generator.cpp, src/Generator.h, src/Util.h
GeneratorBase::set_inputs() is a variadic wrapper around
set_inputs_vector(), which infers the C++ type of each argument and
builds up a wrapper of StubInputs appropriately. This makes for much
more idiomatic C++ code, and also makes some of the relevant
error-checking for type much clearer.
=> Add Generator set_inputs() convenience wrapper

src/Generator.h
Recent changes make using move semantics unsafe without extra work;
forbidding these in lieu of attempting to fix them.
=> Make Generator/GeneratorBase unmovable in addition to uncopyable

src/Closure.cpp, src/Closure.h
This PR fixes a bug where buffers captured by Closure might be incorrectly marked as read only, when the use of the buffer is in a Load inside an address_of that is used to modify the buffer (e.g. copy_memory).
This corrects a bug that can't actually be triggered by the Halide front end as it exists today, so there is no test for this. The only possible test would be brittle and not cover very much.
=> Fix incorrect closure data for loads in address_of

Makefile, test/generator/acquire_release_aottest.cpp
If "cuda" is in the target, we want to run the gpu generator tests. One
of the two tests for which this applies uses the #define TEST_CUDA, and
the other uses TEST_PTX. The Makefile only defines TEST_PTX.
I just switched everything to TEST_CUDA
=> Make gpu_only test actually run on CUDA

Makefile, python_bindings/Makefile, python_bindings/python/Argument.cpp, python_bindings/python/BoundaryConditions.cpp, python_bindings/python/Error.cpp, python_bindings/python/Expr.cpp, python_bindings/python/Func.cpp, python_bindings/python/Func_Ref.cpp, python_bindings/python/Func_Stage.cpp, python_bindings/python/Func_VarOrRVar.cpp, python_bindings/python/Func_gpu.cpp, python_bindings/python/Function.cpp, python_bindings/python/Halide.h, python_bindings/python/IROperator.cpp, python_bindings/python/InlineReductions.cpp, python_bindings/python/Lambda.cpp, python_bindings/python/Param.cpp, python_bindings/python/RDom.cpp, python_bindings/python/Target.cpp, python_bindings/python/Type.cpp, python_bindings/python/Var.cpp
You should be able to compile them using an installed libHalide.
Occurred to me while getting #1904 to work on my system.
=> The python bindings shouldn't include internal libHalide headers

src/LLVM_Runtime_Linker.cpp
This warning hasn’t really been true for quite a long time now, and
just introduces noise into builds.
=> Remove defunct Android x86-64 warning

src/runtime/cache.cpp
Otherwise they can point to dangling memory and fun ensues
=> halide_memoization_cache_cleanup() needs to null the MRU and LRU globals

src/Inline.cpp, src/Inline.h, src/ScheduleFunctions.cpp, test/error/cannot_schedule_inlined_stages.cpp
The following is used to be allowed in Halide even though `f` is not scheduled to be computed at root or at some consumer's level:
```
f(x) = 10;
f(x) += x;
g(x) = 2 * f(x);
f.parallelize(x);
```
This PR adds a pass that validates all functions scheduled 'inline' can't be parallelized, vectorized, etc.
=> Validate schedule of inlined function with multiple update stages

src/Func.cpp, src/Func.h, src/runtime/HalideBuffer.h, src/runtime/HalideRuntime.h
Adds a useless extra flag to define_extern, and adds halide_buffer_t as a typedef of buffer_t.
If we land #1899, we should land this first so that it's possible to syntactically update some of the user code before the body of the change lands. I'm assuming that companies that use Halide have some process where they pick a Halide revision to pull into their source tree. The intended procedure is to merge in Halide just after this PR, then update internal user code as much as possible, using these features, and also by using Halide::Runtime::Buffer instead of buffer_t wherever possible, then merge in Halide just after PR #1899.
The idea is that for many users this will decouple updating user code from updating Halide, so that the whole thing can be staged per user project instead of one …
=> Affordances to upgrade code in anticipation of #1899

src/runtime/hvx_128.ll, src/runtime/hvx_64.ll
Since hexagon llvm backend can't figure it out yet, replace zext/shift/or
instruction sequence with dedicated byte splat:
R32 = vsplatb(R32)
in hvx{64,128}.ll
This reduces number of packets generated for
@halide.hexagon.splat.b to 2 from previous 4, which is on par with .h variant.
=> Small tweak of vector byte broadcast for Hexagon

src/IROperator.h
Fixes an oversight noticed by @steven-johnson in #1891
=> Fix variadic min() not coercing types.

src/CodeGen_Hexagon.cpp, src/HexagonOptimize.cpp, src/HexagonOptimize.h, src/Simplify.cpp
Previously, we avoided some simplifications of loads because the Hexagon backend simplified between running align_loads and loop_carry. I don't think simplification is necessary between these passes (CSE yes, simplify no), @abadams can you confirm?
This PR removes that simplification, which makes things less fragile, and allows other logic to be simpler. This also rather significantly reduces the size of the IR we pass to LLVM for some workloads. At the very least, it's much easier to read.
I've tested this for performance regressions on a number of workloads, I see identical performance.
=> Simplify concatenated loads

apps/camera_pipe/camera_pipe_generator.cpp, src/IROperator.h, src/Simplify.cpp, test/correctness/dilate3x3.cpp, test/correctness/median3x3.cpp, test/correctness/reduction_schedule.cpp
The real motivation here is that this allows a uniform syntax for
multiple -arg calls to min() and max(); the >2 arg version no longer
requires wrapper.
Additionally, by adding a variadic template function version of min()
and max(), we can preserve the proper behavior for arguments which are
ints (rather than Expr), which should be coerced to match the paired
Expr, rather than promoted to Expr first.
=> Use variadic templates to improve min/max for > 2 args

src/Func.cpp, src/Func.h, test/correctness/interleave_rgb.cpp
The underlying implementations converted the int into Expr immediately
(and would fail later on if the Expr wasn’t convertible to int); this
just makes the Func/Stage schedule API a bit more consistent.
=> Convert int->Expr in vectorize(), unroll(), gpu_tile() calls

apps/blur/halide_blur_generator.cpp, src/Func.h, src/Var.h, test/correctness/gpu_give_input_buffers_device_allocations.cpp, test/correctness/gpu_jit_explicit_copy_to_device.cpp, test/correctness/load_library.cpp, test/correctness/logical.cpp, test/correctness/multiple_outputs.cpp, test/correctness/widening_reduction.cpp
These have been deprecated for ~3 years now; I think we should let them
go now.
(Side note: three variants of gpu_tile() in this file are marked as
“will be deprecated” — we should mark them as such if they really are)
=> Remove deprecated "cuda_xxx" APIs

apps/HelloAndroid/jni/hello_generator.cpp, apps/HelloHexagon/pipeline.cpp, apps/HelloiOS/HelloiOS/reaction_diffusion_2_generator.cpp, apps/hexagon_benchmarks/conv3x3_generator.cpp, apps/hexagon_benchmarks/dilate3x3_generator.cpp, apps/hexagon_benchmarks/gaussian5x5_generator.cpp, apps/hexagon_benchmarks/median3x3_generator.cpp, apps/hexagon_benchmarks/sobel_generator.cpp, apps/hexagon_matmul/pipeline.cpp, src/Generator.h, test/generator/example_generator.cpp, test/generator/msan_generator.cpp, test/generator/nested_externs_generator.cpp, test/generator/tiled_blur_blur_generator.cpp, test/generator/tiled_blur_generator.cpp
Uses the same technique as Buffer -> Runtime::Buffer. Fixed/removed all
of the unnecessary explicit-cast-to-Func that I could find.
=> Add forwarding methods for scheduling for Output<> types

src/Func.cpp, src/Generator.cpp, src/Generator.h, src/Schedule.cpp, src/Schedule.h
The motivation here is to make it easier to implement
ScheduleParam<LoopLevel> in a way that allows deferred setting of
values. Note that the default ctor for LoopLevel now produces an
*undefined* LoopLevel (which didn’t exist before); to get an “inline”
LoopLevel you must now use the LoopLevel::inlined() method (similar to
the previous LoopLevel::root() method).
=> Make LoopLevel a refcounted-contents type

src/runtime/runtime_internal.h, src/runtime/tracing.cpp, src/runtime/write_debug_image.cpp
This PR changes write_debug_image to use open instead of fopen. It appears that open is available on Hexagon on 8998, but fopen is not.
=> Use open instead of fopen in write_debug_image.

src/LLVM_Runtime_Linker.cpp, src/runtime/runtime_internal.h, src/runtime/tracing.cpp, src/runtime/write_debug_image.cpp
binary tracing to a file was broken on other platforms. It's only used for generating visualizations, so I didn't notice until #1957
=> Our open flags were linux-specific. Use the more portable fopen instead

src/ScheduleFunctions.cpp, test/generator/msan_aottest.cpp
Everywhere we used to make the buffer_t struct as initialized now also needs to mark the shape as initialized
=> Mark buffer shape as initialized in extern calls

test/correctness/param.cpp
This was always implicitly supported, but never tested. (I’m assuming
this is desired behavior.)
=> Add test to verify that Param<> copies refer to the same Parameter

src/runtime/HalideBuffer.h
The Buffer move constructors partially used swap (for alloc and
dev_ref_count) and partially used direct copying (for buf). This is
fishy in the case where the buffer being moved into already owns a
device allocation. The ownership may get swapped to the dying buffer but
the dev field may not.
=> Don't use swap in our move constructors

test/generator/msan_generator.cpp
NameMangling::Default leaves it at the mercy of what’s in the Target,
which can differ between Makefile and Bazel (the latter defaults to c++
mangling on).
=> msan_generator should specify NameMangling::C

tools/halide_image_io.h
Saved result is amusingly wrong. Don’t try to optimize, just use the
Buffer operator().
=> save_png() writes interleaved images incorrectly

src/CodeGen_Hexagon.cpp
This is sort of a latent bug; the reason this piece of code has worked
for so long is that when mcpu is hexagonv60 it has _always_ implied
hvx support. This may not always be true going forward.
The std::stringstream constructor puts the "put" pointer at the start
or 0. So, the very next call to "<<" will overwrite the contents that
the stream was constructed with. However, subsequent calls to "<<" will
work fine.
=> Fix a bug that overwrote a part of the mattrs string on Hexagon.

Makefile, src/CMakeLists.txt, tools/binary2cpp.cpp
— remove the implicit “halide_internal_” prefix so this tool can be
used for other purposes (callers must now prepend that prefix)
— add option to emit a .h file, for clients that would prefer to avoid
explicit extern decls
— add line breaks so that dump isn’t a single enormous line
=> Upgrade binary2cpp

tools/halide_image_io.h
Fixes mingw build bot, which was the only one that caught the out-of-bounds reads.
@srj I did it this way to avoid requiring a dim(int).min() method on the image type. Is that silly? I doubt anyone is using this for anything other than Halide::Buffer or Halide::Runtime::Buffer.
=> Alternative fix for interleaved pngs

src/Definition.h, src/SimplifySpecializations.cpp, src/SimplifySpecializations.h, test/correctness/specialize.cpp, test/internal.cpp
When a specialize() condition is const-false, we should always prune it
away before lowering.
When a specialize() condition is const-true, we should always prune
away all subsequent specializations (except for those that are also
const-true).
(Note that this pruning already effectively happened later during
simplification, but pruning earlier removes a nontrivial amount of
work.)
=> Aggressively prune specialize() branches

src/DebugArguments.cpp
I forgot about print(Exprs...) when writing this code. I should have just used it.
=> Simplify DebugArguments using print from IROperator

apps/hexagon_benchmarks/conv3x3_generator.cpp, apps/hexagon_benchmarks/dilate3x3_generator.cpp, apps/hexagon_benchmarks/gaussian5x5_generator.cpp, apps/hexagon_benchmarks/median3x3_generator.cpp, apps/hexagon_benchmarks/sobel_generator.cpp
Before:
Done, time (conv3x3a16): 0.0049175 s (128 byte mode)
Done, time (dilate3x3): 0.0042597 s (128 byte mode)
Done, time (median3x3): 0.0050552 s (128 byte mode)
Done, time (gaussian5x5): 0.0042595 s (128 byte mode)
Done, time (sobel): 0.0054079 s (128 byte mode)
Done, time (conv3x3a32): 0.0051582 s (128 byte mode)
After:
Done, time (conv3x3a16): 0.0017923 s (128 byte mode)
Done, time (dilate3x3): 0.0019679 s (128 byte mode)
Done, time (median3x3): 0.0021045 s (128 byte mode)
Done, time (gaussian5x5): 0.0021509 s (128 byte mode)
Done, time (sobel): 0.0019982 s (128 byte mode)
Done, time (conv3x3a32): 0.0021427 s (128 byte mode)
@dsharletg, @dpalermo, @ronlieb - There may be better schedules out there that we can explore over time. These are the best I have *so far*.
=> Hexagon benchmarks new schedules

apps/fft/fft_generator.cpp
The FFT generator schedule had a few problems:
- For complex outputs, the FFT was getting computed redundantly for each re, im result of the output.
- For real results, the FFT was getting redundantly computed for each *line* of the result. Our FFT had `N1*N2*N2*log(N1*N2)` complexity!
This should partially fix #2002. There are still some issues here, it seems hardcoded to produce interleaved complex data, which is sub-optical, we should steer people towards using planar complex data.
=> Fix some scheduling bugs in the FFT generator

src/HexagonOffload.cpp
we want buffer_get_extent(), not buffer_get_max(), to get the size of
the code buffer
=> Fix off-by-one error in HexagonOffload

src/Lower.cpp
Prefetch should be injected after storage folding; otherwise, it may prefetch region outside of bounds when the prefetched region is being storage folded. When the region being prefetched is storage folded, this will prefetch everything in the dimension being storage folded.
=> Inject prefetch should be done after storage folding

src/ScheduleFunctions.cpp, test/correctness/reduction_non_rectangular.cpp
We should also sort all ifs introduced by apply splits so that we can get tighter bounds by BoxesTouched. This also fixes the bugs when rdom's predicate depends on let-stmt inside the ifs and is injected at the wrong level.
=> Also sort all ifs introduced by apply_splits

src/runtime/HalideRuntime.h
Restoring this flag would be an enormous help to those of us who are updating our embarrassingly Australopithecine codebases to work with the new `halide_buffer_t` and other modern Halide runtime things, and I don’t believe it would break anything, nor would it exacerbate anyones’ reliance on legacy `buffer_t` use.
=> Restore BUFFER_T_DEFINED legacy check flag in HalideRuntime.h

src/Lower.cpp, src/Prefetch.cpp
Blindly substituting the let/let_stmt value when calling the bounds_expr_in_scope causes combinatorial expansion of the lets which takes forever to compile. Instead, we introduce a dummy variable and push it onto the scope and re-wrap the let on the way out. Also, move the inject_prefetch after the first simplify; hopefully the simplifier would have simplified lets.
=> Wrap let value to prevent code explosion in prefetch

src/Module.cpp
Hexagon should be unaffected. This is not exercised at the
moment, but it will be as soon as we move PTX over to the new
submodules archiecture.
Small fix to restore original functionality after Hexagon linker change. Should be an easy review, but wanted to make sure others see it and to get buildbot checks.
=> Add code to compile_to_buffer to handle general LLVM compilation.

src/BoundsInference.cpp, src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/IR.cpp, src/IR.h, src/IROperator.cpp, src/ScheduleFunctions.cpp, test/correctness/buffer_t.cpp
via an intrinsic handled in codegen
fixes #1991
=> Use the Target for sizeof(halide_buffer_t) instead of the host system

src/runtime/HalideRuntime.h, src/runtime/android_io.cpp, src/runtime/fake_thread_pool.cpp, src/runtime/gcd_thread_pool.cpp, src/runtime/ios_io.cpp, src/runtime/osx_get_symbol.cpp, src/runtime/posix_allocator.cpp, src/runtime/posix_error_handler.cpp, src/runtime/posix_get_symbol.cpp, src/runtime/posix_io.cpp, src/runtime/posix_print.cpp, src/runtime/qurt_allocator.cpp, src/runtime/thread_pool.cpp, src/runtime/thread_pool_common.h, src/runtime/tracing.cpp, src/runtime/windows_get_symbol.cpp, src/runtime/windows_io.cpp
So that custom overrides can build on top of the default implementations (e.g. add logging), instead of having to replace them completely.
=> expose default implementations of replaceable runtime functions

test/generator/msan_aottest.cpp
(1) overriding the msan hooks requires weak linkage or /FORCE usage;
the former isn’t available and the latter we want to turn down
(2) MSAN isn’t supported on Windows targets anyway
=> msan_aottest should be skipped for MSVC as well as MinGW

src/Func.cpp, src/RealizationOrder.cpp
Replace map/set in realization_order with vector so that the realization order doesn't depend on the function names.
=> Replace map/set in realization_order with vector

apps/fft/main.cpp
Defining our own causes link errors in some configurations.
=> Use log2 from <cmath>

src/CMakeLists.txt
It allows get output string of internal `print_loop_nest`.
=> Added PrintLoopNest.h into CMakeLists.txt

python_bindings/python/IROperator.cpp, src/CSE.cpp, src/Expr.h, src/IR.cpp, src/IR.h, src/IREquality.cpp, src/IRMutator.cpp, src/IRMutator.h, src/IROperator.cpp, src/IROperator.h, src/PartitionLoops.cpp, src/RemoveUndef.cpp, src/Simplify.cpp, src/SimplifySpecializations.cpp, src/Solve.cpp, src/Substitute.cpp, src/UnifyDuplicateLets.cpp, test/correctness/fuzz_simplify.cpp
Two changes:
1) Use 32 free bits in the IRNode to store the IRNodeType, so that it
can be gotten at by a load instead of having to call a virtual function
2) Change things to a style where any function that's going to make a
copy of an Expr takes it by value, and then does a std::move internally
at its last use. This avoids a bunch of atomic ops and conditional
branches in caller code in the case where you're passing in an rvalue.
With these changes, lowering local laplacian gets about 12% faster (1.5s
-> 1.33s). Most of the win is from change 1
These are being done in advance of a planned change to simplify the
simplifier to be more concise and use less stack space, so hopefully the
fact that this represents a partial reversion of #1810 won't bite us.
=> Compiler performance penny-pinching

apps/opengl_demo/main.cpp, apps/openglcompute/Makefile, apps/openglcompute/jni/oglc_two_kernels_run.cpp, apps/openglcompute/test_two_kernels.cpp, src/CodeGen_GPU_Host.cpp, src/runtime/cuda.cpp, src/runtime/hexagon_host.cpp, src/runtime/metal.cpp, src/runtime/opencl.cpp, src/runtime/opengl.cpp, src/runtime/openglcompute.cpp
@ronen @estollnitz @shoaibkamil PTAL
Builds on #2039 , so this includes the commits from that.
I'm working on a minor cleanup of the device_interface API (see #2036 )
As part of that, I want to promote the idea of wrapping non-owned native handles into the device_interface_t struct, and unifying the semantics across the backends. This PR makes the gl backend behave the same way as the other GPU backends w.r.t what happens when you mess with device field manually.
=> Nuke the texture-metadata tracking in opengl

apps/opengl_demo/main.cpp, apps/openglcompute/Makefile, apps/openglcompute/jni/oglc_two_kernels_run.cpp, apps/openglcompute/test_two_kernels.cpp, src/CodeGen_GPU_Host.cpp, src/runtime/cuda.cpp, src/runtime/hexagon_host.cpp, src/runtime/metal.cpp, src/runtime/opencl.cpp, src/runtime/opengl.cpp, src/runtime/openglcompute.cpp
instead of just the device handle
The opengl backend could be simplified if it knew the dimensions of the
output buffer.
=> Pass entire buffers to dev_run

src/Generator.cpp, test/generator/example_generator.cpp, test/generator/example_jittest.cpp
This is purely an optional stylistic choice; I personally prefer this
because of the symmetry with scheduling calls, and the overhead for
supporting it is pretty close to nil.
(I’m cherry-picking some pieces from other not-ready-to-land PRs I have
that I think are worthwhile on their own.)
=> Add chainable setters for ScheduleParams in stubs

src/Generator.cpp, src/Generator.h
Previously, the Generator class sorta-assumed it could be created with
a GeneratorContext (thus lazy-initing value_tracker and externs_map,
and defaulting Target to host); in practice, this is never the case
(aside from some internal-testing code inside Generator itself), and
attempting to use a Generator in this way is untested and possibly
buggy. This removes code for lazy-initing and adds asserts that verify
that a Generator always is created with a GeneratorContext.
=> Tighten up some Generator assumptions

src/CodeGen_LLVM.cpp
Presently, only Hexagon, AMDGPU & NVPTX implement the adjustPassManager method of LLVMTargetMachine
=> Allow LLVM targets to run custom bitcode optimization passes.

src/CodeGen_C.cpp
It's only safe for types where the sizes are identical, but on 32-bit builds, a "Handle" type that is a function argument is only 32 bits in size. Tweak the casting in print_reinterpret() and add a static_assert to ensure unsafe code won't compile.
=> C++ backend: reinterpret<> is not safe for Handle types

src/CodeGen_C.cpp, src/CodeGen_C.h
A bit more cleanup than strictly necessary, but we now gather all necessary functions once per module, and emit all the prototypes at the start, rather than scattershot as we go.
=> Clean up C++ backend prototype emission (Issue #2077)

Makefile
It had atrophied and no longer worked; the expected way now is to redefine CC and CXX.
=> Remove BUILD_BIT_SIZE

src/CodeGen_C.cpp, src/CodeGen_C.h, src/CodeGen_OpenGLCompute_Dev.cpp
-- dynamic allocations are allowed to return null; we must check and fail
-- if we fail early, we must clean up intermediate stuff (see new RAII class that does this for us)
Drive-By changes:
-- change the "globals" string to a C++11 style literal string
-- move guts of AssertStmt handling into helpers
=> Fix malloc/free in C++ backend

Makefile, src/CodeGen_C.cpp, src/CodeGen_C.h, src/Type.h, test/generator/define_extern_opencl_aottest.cpp
The C++ AOT backend is almost completely untested. This attempts to add test/generators to test using this backend in addition to the normal one. Caveats:
-- Previously, attempting to use this backend for vectorized code failed at compile time; now, if any vectorized types are found, we fail at runtime. (This is really a short-term workaround to simplify build rules.)
-- Extended Makefile to attempt to build all the Generator tests this way, then add extensive blacklists for the many that won't yet compile/link/run correctly.
Note that I didn't even attempt to get this working for CMake; IMHO we should postpone that until (at least) the blacklist of AOTCPP tests goes away.
=> Add testing for C++ AOT backend

src/CodeGen_C.cpp
Emitting as (a, b) using the comma operator does what we want, but triggers the "unused-value" warning under common GCC settings. Adding a templated helper function to explicitly evaluate-but-ignore the first arg allows us to avoid requiring consumers to disable warnings.
=> C++Backend return_second() impl should avoid warnings

Makefile, src/CodeGen_C.cpp
Partial fix for #2075:
-- The identifier should be a pointer-to-storage, not storage.
-- mark data, shape, and buffer itself as const (except for scalar buffers)
-- Note special-case for https://github.com/halide/Halide/issues/2099
-- drive-by prettyprint improvement (don't put all data on a single line)
=> Fix C++ backend embedded-buffer generation

src/IROperator.h
In master, count_leading_zeros on a float becomes an obscure llvm verification failure. I think we want to force people to reinterpret cast to int first if they really want the number of leading zeros on an IEEE float.
=> ctlz, clz, and popcount must take integers

Makefile, src/CodeGen_C.cpp, src/CodeGen_C.h
Partial fix for https://github.com/halide/Halide/issues/2075, also fixes generator_aotcpp_cxx_mangling_define_extern
=> Forward-declare all handle types before any function prototypes

apps/camera_pipe/camera_pipe_generator.cpp, src/Generator.h, test/correctness/inlined_generator.cpp
This PR adds the minimal API necessary to allow for using Generators in
the same C++ translation unit as subcomponents of another pipeline,
without requiring the use of Stubs. This PR is not expected to be
accepted as-is, but rather as a proof-of-concept for adding this
functionality.
The major additions are Generator<T>::apply, which creates the
Generator, sets the Inputs, and calls the generate()/schedule()
methods; for cases where GeneratorParams need to be set, you can
instead use Generator<T>::create followed by
Generator<T>::generate_with_inputs.
Added a simple test (inlined_generator) for testing and as an example;
as a demonstration of the usefulness of this approach, also converted
the demosaic code in apps/camera_pipe to be in the form of a local
Generator (based largely on code …
=> Allow creating & using Generators directly

test/correctness/vector_math.cpp
It's unlikely the values will trigger bugs, but if they do, repeatability would be nice. Also, follow the lead of fuzz_simplify by varying (and printing) the seed using time(), just in case there are value-specific failures.
=> vector_math: use std::mt19937 instead of rand()

apps/linear_algebra/src/blas_l3_generators.cpp
before changes, was failing with
```
Error:
The GeneratorParam transpose_A cannot be written after build() or generate() is called.
Aborted
```
looks like this was added 2 months ago
https://github.com/halide/Halide/blob/df0d2b89aaa45e5b15f82dfd9376b2fe9789e843/src/Generator.cpp#L992
builds fine now and `blas_test` passes for me.
=> update GEMMGenerator to not modify GeneratorParam after build() (hitting a recent user_assert in Generator)

apps/CMakeLists.txt
I had to add this in order to get apps to build.
I can see this possibly being included by each individual app instead. Thoughts?
=> include HalideGenerator.cmake needed by various apps

src/IROperator.h
It should first and foremost tell people how to fix their code, not just
why we are flagging an error without any context.
=> The clamp error message was unhelpful

src/CodeGen_C.cpp, src/CodeGen_C.h
-- Add a generic "scalarize" function and use it for print_extern_call
-- always use temporaries for float constants
-- Shuffle has wrong assertion test for max-index upper bound
-- Shuffle didn't handle the result-is-scalar case correctly
=> More C++ Backend Fixes

apps/HelloHexagon/Makefile, apps/hexagon_matmul/Makefile
This PR makes it so testsigs (which are necessary on later Hexagon devices) still work after #2119.
=> Copy testsig* from /system/lib/rfsa/adsp to the app's device path

src/Bounds.cpp, src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/IR.cpp, src/IR.h, src/IROperator.cpp, src/IROperator.h, test/correctness/require.cpp, test/error/require_fail.cpp
require() assumed that calls to halide_error() would never return; this is false, and as a result, 'failing' requires didn't actually fail when used in JIT mode without custom error handler. To accomplish this, Call:require was added as an intrinsic, so Codegen could do the right thing.
Note to reviewers: I modeled the handling of Call:require after Call::if_then_else, but I'm not sure about the usage in Bounds.cpp, nor am I sure whether there are other visitors/mutators that need attention.
=> require() should emit assertions

src/runtime/thread_pool_common.h
In our default thread-pool, the thread that claims the last loop
iteration from a job is responsible for popping it off the global work
queue. I found a case in the wild of a parallelized reduction over 0
things.
A job with zero things in it has no last loop iteration, so nobody was
popping it. The main thread thinks that the job was completed by someone
else and returns, and then a worker sees the job, which is now described
by a clobbered stack frame, so the worker then does arbitrary nonsense.
Our serial for loop codegen handles extents <= 0 gracefully, so I just
changed the parallel for loop handler to do that too.
=> Fix size-zero parallel for loops

src/Associativity.cpp, src/Associativity.h, src/Func.cpp, test/correctness/rfactor.cpp
Enable rfactor on self assignment, `f(x) = f(x)`, to support partial reduction.
=> Enable rfactor on self-assignment

tools/halide_image_io.h
-- JPEG case needed to use convert(), otherwise saving  non-uint8 images as JPEG produced garbage
-- improved rounding of the convert() functions (e.g. mul or div by 257 instead of 256); this may be overthinking it, but the extra overhead is unlikely to be meaningful here
-- added convert functions for bool and int64 types; these aren't likely to be very useful in practice, but it means we can instantiate compilable code for all of the supported Halide::Type C++ equivalents, and doesn't really cost us anything
=> Fixes to halide_image_io.h

src/ScheduleParam.h
When using int based parameters I'm getting:
```
warning C4244: 'return': conversion from 'const double' to 'int32_t', possible loss of data
```
=> Fixes C4244 warning in MSVC

tools/halide_image_io.h
Complete the type-to-type conversion matrix to make implementing Tmp file IO easier.
=> Rework convert functions in halide_image_io.h

HalideGenerator.cmake
halide_add_aot_library_dependency applied to a static library didn't propagate the flags
=> Propagates link flags in static libraries

apps/c_backend/pipeline_generator.cpp, src/CodeGen_C.cpp, src/CodeGen_Metal_Dev.cpp, src/CodeGen_Metal_Dev.h, test/correctness/boundary_conditions.cpp
Some C++ environments will do "using std::min (or max)" in common headers; rename the custom version the C++ backend emits to thwart errors.
Also, drive-by fix to the Metal backend for extern calls, which was broken by the recent vector change. (Apparently we don't test Metal on the buildbots?)
=> Ensure min() and max() are unambiguous in C++ backend

HalideGenerator.cmake
Reverts halide/Halide#2147 -- testing to see if this clears up Windows buildbots
=> Revert "Propagates link flags in static libraries"

src/Function.cpp
We weren't visiting constraints on dimensions beyond the fourth,
probably because that used to be the limit on a buffer_t. Removed. Done
as a PR for testing in case I'm missing something.
=> Remove function visitor dimension check

src/Func.h
Avoids problems when people do:
using std::min;
using Halide::min;
It looks dumb when I write it like that, but the using std::min can be
buried in a header dependency somewhere.
This only happens because the stl has a templated min. Fortunately it
requires both template arguments to match, so we only have ambiguities
in cases where we call min/max on matching types that can both be cast
to Expr.
Note that this is mostly unrelated to the C-backend min/max namespace issues. This is a problem in the Halide source, not in the generated code.
=> avoid ambiguity between std::min and Halide::min

tools/halide_image_io.h
Mostly just stylistic and terseness.
-- change the load and save methods to be table-driven, to simplify future format support additions
-- all if statements are { enclosed in braces}, no single-liners
-- helper methods added to FileOpener to reduce error-prone boilerplate
-- some constant-at-compile-time code restructured to make it more obvious (eg constexpr)
-- swap_endian_16 returns result rather thanout-by-ref
(Side note: do we have any unit tests for PPM and/or PGM?)
=> Grab-bag of halide_image_io cleanups

apps/local_laplacian/local_laplacian_generator.cpp
cascades the sliding window pyramid collapse instead of computing them
all at (output,y). Reduces runtime from 27ms to 21ms on my machine.
=> Schedule tweak for more locality

src/CodeGen_C.cpp, src/EarlyFree.cpp, src/InjectHostDevBufferCopies.cpp, test/generator/define_extern_opencl_aottest.cpp
No functional changes intended, though where exactly the device calls go
has probably changed a bit.
Responsibility for device frees was moved from EarlyFree.cpp into
InjectHostDevBufferCopies.cpp. In master combined host-dev allocations
were never freed early.
=> Rewrite InjectHostDevBufferCopies

src/Buffer.h, src/Generator.h, src/runtime/HalideBuffer.h, test/correctness/image_io.cpp, tools/halide_image_io.h
Add a suite of type-to-type conversion utilities to halide_image_io.h; this is an explicit variant of what is currently done implicitly inside the existing halide_image_io load/save functions, and is intended to allow for more future flexibility in the load/save functions.
=> Add Tools::ImageTypeConversion

src/Simplify.cpp
`const_int_bounds` of vector mod should take max of abs of the vector lane values for the upper bound.
=> Fix bugs in const int bounds vector mod

src/runtime/HalideBuffer.h
It made an illegal call to transpose() with no args. Mimic slice/sliced() and just call embed() instead.
=> Fix Buffer<>::embedded()

Makefile
Currently we delete contents-of-dirs but not the dirs themselves.
=> 'make clean' should delete distrib/, as well as all directories

apps/bilateral_grid/filter.cpp, apps/interpolate/interpolate.cpp, apps/local_laplacian/process.cpp, apps/wavelet/wavelet.cpp, test/correctness/image_io.cpp, tools/halide_image_io.h
This is a fairly substantial rewrite of halide_image_io.
Previously, every load and save function did its best to satisfy the request: if the loaded file wasn't the type we needed, we quietly converted on the fly; similarly, if the saved format didn't support the type we used, we quietly converted on the fly. In both cases, we blithely discarded data without warning.
This changes the existing API to assume that Data Loss Is Bad, and thus, the existing load()/save()/load_image()/save_image() calls now fail if data loss is possible:
-- When loading, if the Buffer being loaded into has a static data type, we fail at runtime if that data type can't exactly represent the source file (e.g., loading a 16-bit PNG into Buffer<uint8_t>, or even an 8-bit PNG into a Buffer<uint16_t>); we don't …
=> Rewrite halide_image_io

.travis.yml
AFAICT, the Makefile build completely ignores this symbol, so this step is 100% redundant.
=> Travis: remove Makefile+HALIDE_SHARED_LIBRARY=1 combination

HalideGenerator.cmake, Makefile, apps/support/Makefile.inc, test/generator/blur2x2_generator.cpp, tools/CMakeLists.txt, tools/RunGen.cpp, tools/RunGenStubs.cpp
*Disclaimer:* this is very much a work-in-progress right now, but looks interesting enough that I'd like some feedback; it is definitely not ready to land as-is.
This PR adds a simple(ish) wrapper that allows arbitrary Generators to be built into a single executable that can be run directly from a shell, without needing to wrap them in your own custom main() driver. It also implements a rudimentary benchmarking functionality.
This adds a new executable target, `$(GENERATOR).rungen`, for every generator in test/generators (and also for all generators in test/apps that make use of the standard support/Makefile.inc); these allows you to pipe arguments from the command line into the Generator's Inputs, and specify Outputs.
Let's demonstrate usage with apps/bilateral_grid (with irrelevant …
=> Add a generic "Run-or-Benchmark-A-Generator" shell

Makefile, test/CMakeLists.txt, test/generator/cxx_mangling_aottest.cpp, test/generator/cxx_mangling_define_extern_aottest.cpp, test/generator/cxx_mangling_define_extern_externs.cpp, test/generator/cxx_mangling_externs.cpp
This makes it tractable to use Generators-with-extern-deps with the RunGen tool.
=> Move test/generator externs into separate libs (vs aot_test code)

apps/HelloHexagon/Makefile, apps/bilateral_grid/Makefile, apps/blur/Makefile, apps/c_backend/Makefile, apps/camera_pipe/Makefile, apps/cuda_mat_mul/Makefile, apps/fft/Makefile, apps/glsl/Makefile, apps/hexagon_benchmarks/Makefile, apps/hexagon_matmul/Makefile, apps/interpolate/Makefile, apps/local_laplacian/Makefile, apps/opengl_demo/Makefile, apps/openglcompute/Makefile, apps/resize/Makefile, apps/simd_op_check/Makefile, apps/support/Makefile.inc, apps/wavelet/Makefile
Regarding Issues:
#1112 
#2156 
This is not a complete fix: only the app Makefiles have been patched. Cmake should be done as well. I don't have a working CMake build to do and test that on.
=> Fixed Makefiles manually to get around linking errors when using an LLVM with terminfo.

tools/halide_image_io.h
-- Add explicit #include of HalideRuntime.h
-- avoid !"string-literal" as some compilers will complain about coercion-to-bool
=> Fix minor portability issues in halide_image_io.h

CMakeLists.txt, apps/bilateral_grid/CMakeLists.txt, apps/blur/CMakeLists.txt, apps/c_backend/CMakeLists.txt, apps/camera_pipe/CMakeLists.txt, apps/glsl/CMakeLists.txt, apps/linear_algebra/benchmarks/CMakeLists.txt, apps/linear_algebra/src/CMakeLists.txt, apps/local_laplacian/CMakeLists.txt, apps/wavelet/CMakeLists.txt, src/CMakeLists.txt, test/CMakeLists.txt, tools/CMakeLists.txt, tutorial/CMakeLists.txt
...rather than the scattered -std=c++11 (bracketed with MSVC checks) we used before. Note that this increases the CMake min version to 3.1.3.
=> Use CMake 3.1x's standard for requesting C++11

HalideGenerator.cmake, Makefile, src/CodeGen_C.cpp, test/CMakeLists.txt, tools/RunGenStubs.cpp
Emitting a namespaced call in a way that is easy to both forward-declare and call properly is a bit painful; instead, have the header generation code emit optional getters for the argv and metadata function. Enable the cxx_mangling test rungen as proof of concept.
(This is a slightly modified version of an earlier PR, which was abandoned because it was unclear whether the approach would work well for Bazel/Blaze; I've satisfied myself that the approach will work adequately in that scenario, and also fixed some CMake issues that crept in.)
=> Rework RunGetStubs mechanism to be C++-name-mangling-friendly (Take 2)

tools/RunGen.cpp
Main change is to add smarts to run inputs thru BoundsQuery as well, and copy them to a different-layout Buffer if necessary. Also a bit of drive-by cleanup to move more code out of main(), and add a flag to allow customizing the number of warmup iterations for benchmarking.
=> RunGen: allow for chunky/interleaved inputs

src/Generator.h
I don't know whether it was an intentional decision to not enable "print_loop_nest()" on Generator outputs, but it seemed like an oversight.
=> Added print_loop_nest() to the supported calls on Generator outputs

src/runtime/HalideBuffer.h
when it is passed in to the constructor.
(Opening a PR as I want the automated tests to run.)
=> Do not have Buffer take ownership of dev field from a halide_buffer_t

Makefile, apps/support/Makefile.inc, test/correctness/gpu_mixed_dimensionality.cpp, test/generator/cleanup_on_error_aottest.cpp, test/generator/cleanup_on_error_generator.cpp, test/generator/define_extern_opencl_generator.cpp, test/generator/gpu_object_lifetime_aottest.cpp
OpenCL on OS X is pretty flaky these days, and we have no metal testing coverage. I want to switch the mac buildbot to test metal instead of OpenCL. To do this, first I need to fix make run_tests to actually pass with metal enabled.
=> Fix metal tests

src/IROperator.cpp, src/IROperator.h, src/ScheduleFunctions.cpp, src/Simplify.cpp, test/correctness/extern_consumer.cpp
This allows scheduling other Funcs alongside them, and theoretically would let us specify that an extern stage should run on the other side of a device transition (e.g. Hexagon).
Most of the changed lines are code motion, because I needed to test if an Expr is pure outside of Simplify to fix an issue in ScheduleFunctions.
=> Give extern stages a Var::outermost loop

src/runtime/opencl.cpp
My halide_print accumulates characters until it sees a LF and then logs the accumulated characters at once. If it doesn’t get a trailing LF, the (potentially crucial) last reported line is not logged before halide_error aborts.
=> Opencl build error whitespace

Makefile, test/error/undefined_func_compile.cpp, test/error/undefined_func_realize.cpp, test/error/undefined_pipeline_compile.cpp
Bazel doesn't like relative include paths.
=> Fix include paths for Bazel

src/LLVM_Output.cpp
llvm::writeArchive() will happily create .a files with absolute paths if you pass it files specified that way; some versions of 'ar' can't reliably deal with these (e.g. 'ar x' on OS X will refuse to extract these files in most cases). Work around this to ensure that we always produce canonically useful archives.
=> Ensure that LLVM-created .a files don't contain absolute paths

Makefile, apps/HelloHexagon/Makefile, apps/bilateral_grid/Makefile, apps/blur/Makefile, apps/c_backend/Makefile, apps/camera_pipe/Makefile, apps/cuda_mat_mul/Makefile, apps/fft/Makefile, apps/glsl/Makefile, apps/hexagon_benchmarks/Makefile, apps/hexagon_matmul/Makefile, apps/interpolate/Makefile, apps/linear_algebra/Makefile, apps/local_laplacian/Makefile, apps/opengl_demo/Makefile, apps/resize/Makefile, apps/simd_op_check/Makefile, apps/support/Makefile.inc, apps/wavelet/Makefile
(1)  use `$(@D)` instead of an explicit variable in most cases of 'mkdir -p', since it's always the directory of the target (terser and less error-prone)
(2) Generators and RunGen never use the current directory, so there's no need to cd to a TMP dir prior to running them
=> Makefile hygiene

CMakeLists.txt
Solve some link errors when compiling with gcc 6.3 (correctness tests cannot find pthread and lesson03 cannot find dlopen). May solve #1605.
=> update cmake config

Makefile, tools/makelib.sh
Some Generator-related rules could be made simpler if we could reliably combine .a files; libtool does this, but is not reliably available on all systems. This adds a simple bash script that allows combining of an arbitrary list of .a and .o files into a single .a file, and modifies the Makefile to make use of it in a few places.
Also, drive-by fix to the clean_generators target.
=> Add "makelib.sh" utility script

src/runtime/cuda.cpp
when Halide cuda internals are being modified.
=> Move pointer validation to be under an ifdef intended to be used only

src/runtime/HalideBuffer.h
device_interface as well as device.
=> Another fix (mostly) for move constructors. Have them null out

src/AddImageChecks.cpp, src/runtime/HalideRuntime.h, src/runtime/errors.cpp, src/runtime/runtime_api.cpp, test/error/null_host_field.cpp
Currently if the device field is non-zero but the host field is null,
and the pipeline gets used on the host at all, then we just segfault
nastily.
=> Add an assert that catches null host fields

src/SlidingWindow.cpp
In practice this means that in line-buffered pipelines loops over y
don't get partitioned on the y axis, which has two key benefits:
- The warm-up code in the y axis now gets partitioned in x, making
boundary conditions cost less.
- smaller binaries
- faster compile times
On local_laplacian and HDR+ this saves a bunch of code size and compile
time with no measurable performance difference. On camera_pipe this
seems to be a minor performance win.
=> Change sliding window to use likely_if_innermost

tools/halide_image_io.h
Calling convert_image with an explicit destination type is ambiguous (ie. `convert_image<float>(img)` )
=> disambiguate overloaded functions

tutorial/lesson_09_update_definitions.cpp
Directly casting from __m128 to __m128i triggers a compile error in msvc. One option is to use _mm_castps_si128(), the other is to use the correct integer intrinsics from the get go.
=> use correctly typed sse intrinsics in tutorial

src/Elf.cpp, test/common/check_call_graphs.h, test/opengl/testing.h
These features are only available from C++14 onwards:
1. Default argument in lambda expression.
2. `std::function` constructor checks function signature.
Since Halide makefiles explicitly selects C++11 as standard, C++14 elements ought to be removed.
=> replace code that relies on cpp14 features

src/Function.cpp, test/error/extern_func_self_argument.cpp
Patched from PR#2263: This is a bit of an an edge case, but I found that if an extern Func definition includes itself as one of the ExternFuncArguments (e.g. f.define_extern("extern_func", {f}, Int(32), 2);), it goes into infinite recusion in infer_arguments() and segfaults from stack overflow. This PR avoids that by showing an error message instead.
=> Error if an extern func has itself as an argument

src/Util.cpp
This is a Windows-specific env var to allow overriding the /tmp-equivalent directory. (Issue #2262)
=> Add HL_WINDOWS_TMP_DIR env var

Makefile, bazel/create_halide_config.sh, bazel/halide.bzl
Generalize it a bit to allow for emitting a similar helper for CMake; rename the Bazel helper function to be more accurate.
=> Refactor create_halide_config

src/runtime/metal.cpp
Instead of allocating a temporary `MTLBuffer`, if the arguments
size is less than 4KB, use `setBytes:length:atIndex`.  
See https://developer.apple.com/reference/metal/mtlcomputecommandencoder/1443159-setbytes?language=objc#discussion for more information.
This change should never be slower than the existing approach, and helps remove one source of overhead for small pipelines.
CC @estollnitz
=> Metal: Use setBytes:length:atIndex for arguments

src/runtime/HalideRuntime.h, src/runtime/device_interface.cpp, src/runtime/errors.cpp
This is fairly easy to do and seems worthwhile to more quickly isolate crashes in the wild. (There's an argument that a null pointer SEGV is easier to debug if there's a good stack trace but that seems rare relative to reporting an error message.)
Remove extraneous null buffer handling code from halide_device_sync as
it did not work anyway. (Making it sync all devices requires
registering each device_interface which has been used, which is
perhaps possible, though seems like too much work for something noone
uses.)
=> Check for null buffer pointers and report a better error.

CMakeLists.txt
As of right now, the tree builds cleanly on Windows this way (pending buildbot verification): let's flip this switch to keep it that way.
=> Enable warnings-as-errors by default on Windows builds

src/Tuple.h, src/runtime/HalideRuntime.h, tools/halide_benchmark.h
Add warning about using the benchmark() function for GPU code, as naive use can give misleading results. Also add convenience wrappers to halide_buffer_t and Realization.
=> Add caveat to halide_benchmark.h, plus device_sync() wrappers

Makefile, test/CMakeLists.txt, test/generator/cxx_mangling_aottest.cpp, test/generator/gpu_object_lifetime_aottest.cpp
-- Only build/link cxx_mangling_gpu in Makefile if TEST_CUDA is enabled
-- gpu_object_lifetime in CMake should allow for multiple GPU backends
-- cxx_mangling_aottest.cpp should use TEST_CUDA rather than WITH_PTX
-- Add status messages to cxx_mangling_aottest and gpu_object_lifetime to indicate which (if any) GPU backend is being tested
(attn: @mkbosmans)
=> More/better fixes for disabled GPU targets

src/Type.cpp, src/Type.h, test/correctness/inline_reduction.cpp, test/correctness/saturating_casts.cpp
This bug hit someone using infinity in a meaningful way in a float
pipeline.
=> A min reduction over infinities should be infinity

src/runtime/HalideBuffer.h, src/runtime/hexagon_remote/sim_host.cpp, test/generator/matlab_aottest.cpp, test/performance/fast_pow.cpp
Minor changes to achieve consistency:
-- Remove apparently-unsed #define EXPORT in HalideBuffer.h
-- Rename HALIDE_EXPORT -> DLLEXPORT macro in sim_host.cpp to match convention used elsewhere
-- Rename EXPORT -> DLLEXPORT macro in matlab_aottest.cpp to match convention used elsewhere
=> EXPORT macro hygiene

src/Generator.cpp, src/Generator.h
-- replace the GeneratorFactory interface-object with a std::function
-- HALIDE_REGISTER_GENERATOR now implements the (now-simplified) GeneratorFactory function
-- move the GeneratorParam stuff out of the factory (it can always be applied aftr creation)
-- have Stubs bind directly to a GeneratorFactory via extern reference, rather than looking up in the registry (this simplifies some linkage issues in obscure cases with Stubs in some build systems)
=> Rework and simplify the Generator creation code

Makefile
Add `-luuid` and `-lole32` to the Windows linker flags in Makefile to bring in the libraries that define several symbols including `FOLDERID_LocalAppData` and `_imp__CoTaskMemFree`.
Addresses issue https://github.com/halide/Halide/issues/2306
=> Fix mingw linking errors on Windows

CMakeLists.txt, src/CMakeLists.txt, test/CMakeLists.txt
Revised attempt at PR#2302 that shouldn't cause Windows build failures.
=> Add missing test/generator tests to CMake (v2)

src/runtime/HalideRuntime.h
(host == NULL && device != 0) doesn't currently have specified behavior in the Halide calling convention. Internal allocations can end up in this state sometimes, but not ones passed to extern stages. Internally
Halide uses host == NULL && device == 0 for its bounds query check, so change the getter to use that.
Given the UB, the tests with extern stages were correct to just check the host, but IMO it's really better to check both to mirror what Halide does in compiled pipelines.
=> Tweak is_bounds_query definition

test/auto_schedule/interpolate.cpp
Add Interpolate benchmark under auto schedule tests. Manual and auto-scheduled code take the same amount of time roughly (~23ms on a 16-core Xeon Haswell 2.40 GHz).
Signed-off-by: Uday Bondhugula <udayb@iisc.ac.in>
=> Add interpolate benchmark for auto schedule

Makefile, src/CMakeLists.txt, src/IR.cpp, src/IRMutator.cpp, src/IRMutator.h, src/IRPrinter.cpp, src/IRPrinter.h, src/Util.h, test/correctness/c_function.cpp
At present we only define EXPORT for Win32 (because we have to); this PR proposes to also define it for GCC/Clang and default visibility to hidden; the motivation here is to catch missing/wrong EXPORT settings on ~all systems, rather than waiting for Windows buildbots to catch them.  
(In theory, this could also make libHalide.so load faster; in practice, that's not likely important, and even if it was, we'd probably also have to hide all the exported LLVM symbols for that to matter.)  
(Added some EXPORT cruft that Clang really wanted.)
=> Define and enforce EXPORT for gcc/clang

src/CodeGen_X86.cpp, src/runtime/x86.ll, test/correctness/simd_op_check.cpp
Report: "LLVM removed some intrinsics in order for them to be lowered to LLVM IR instead (which seems to natively support it now)"
=> Work around LLVM breakage

tutorial/CMakeLists.txt
This eliminates redundant copies at CMake configure time.
=> CMake: prefer configure_file() to file(COPY)

src/LLVM_Runtime_Linker.cpp
When the chosen os is "noos" and we are compiling for Hexagon then we need an allocator. Use qurt_allocator.
@dsharletg : PTAL
=> Fix simulator-standalone mode on Hexagon

src/Simplify.cpp, test/warning/require_const_false.cpp
Changes:
- Simplify !likely(e) -> likely(!e)
- can_prove(likely(1)) now returns true
- require(1, a, b) -> a
- require(0, a, b) -> emits "Warning, this will always fail at runtime"
=> Improve simplify for likely() and require()

src/AutoSchedule.cpp
Originally `DimBounds` (which is a map of dimension name to its interval) was part of `RegionsRequiredQuery`; however, this caused a bug when `RegionsRequiredQuery` used as a key in `regions_required_cache`, where two `RegionsRequiredQuerys` with identical fields except `bounds` (both `bounds` sizes and keys were the same but with different interval values) pointed to the same cache value. That's why, I made `bounds` as part of the cache value (`RegionsRequired`) and do the equality comparison to get the corresponding regions required.
=> Fix bug in regions required cache

src/PartitionLoops.cpp
Showed up in a complex production pipeline. I have been unable to repro
with a small test. The bug is that thread_id_x doesn't get added to
gpu_vars, so lets that depend on it can get lifted outwards.
=> Fix minor bug in renormalize gpu loops

.travis.yml, CMakeLists.txt, Makefile, README.md, src/CodeGen_ARM.cpp, src/CodeGen_Internal.cpp, src/CodeGen_LLVM.h, src/CodeGen_PTX_Dev.cpp, src/CodeGen_X86.cpp, src/CodeGen_X86.h, src/Float16.cpp, src/Introspection.cpp, src/JITModule.cpp, src/LLVM_Headers.h, src/LLVM_Output.cpp, src/LLVM_Runtime_Linker.cpp
With final release of LLVM 5.0, we should drop support for older versions to simplify internal code; with this PR, we would support 3.9, 4.0, 5.0, trunk.
This revises Travis to test 3.9 and 4.0. (Note that buildbot will need https://github.com/halide/build_bot/pull/3 to land to remove testing of 3.8; this PR is guaranteed to fail until then.)
https://github.com/halide/Halide/issues/2356
=> Drop support for LLVM 3.7 and 3.8

src/OutputImageParam.h
These methods have been deprecated since Dec 2016; time for them to go.
=> Remove long-deprecated OutputImageParam methods

src/Generator.cpp, src/Generator.h
This allows us to add the dimensions() method to Constrainable, to mimic ImageParam and Buffer<> API.
=> Rename some internal Generator methods

src/Func.cpp, test/error/wrong_dimensionality_extern_stage.cpp
Previously produced an inscrutable error from the middle of bounds
inference. Now caught in the front-end.
=> Catch mismatched dimensionality call to extern Funcs

README.md
This is actually ignored for all currently supported LLVM versions; we detect the actual version via the config read from LLVM_DIR.
=> Remove -DLLVM_VERSION from CMake README

src/WrapCalls.cpp, test/error/wrapper_never_used.cpp
If `f.in(g)` is called, but `f` is never actually called inside `g`, this will throw user error.
=> Throw an assertion for unused custom wrapper

src/Buffer.h, test/opengl/rewrap_texture.cpp
Old signature:
```cpp
int device_wrap_native(const DeviceAPI &d, uint64_t handle)
```
New signature:
```cpp
int device_wrap_native(const DeviceAPI &d, uint64_t handle, const Target &t = get_jit_target_from_environment())
```
This parallels the existing optional `target` parameter of `Buffer::device_malloc` and `Buffer::copy_to_device`: https://github.com/halide/Halide/blob/5345ec10554ed1cbda0dd0916e207eb1490d7e76/src/Buffer.h#L460 https://github.com/halide/Halide/blob/5345ec10554ed1cbda0dd0916e207eb1490d7e76/src/Buffer.h#L470
This of course makes it possible to use a target defined in the application rather than only the environment target.
...which makes it possible to modify the `opengl_rewrap_target` test so that it doesn't fail mysteriously even though all other opengl tests pass even …
=> Add optional `target` parameter to `Buffer::device_wrap_native`.

apps/bilateral_grid/bilateral_grid_generator.cpp, apps/camera_pipe/camera_pipe_generator.cpp, apps/conv_layer/conv_layer_generator.cpp, apps/lens_blur/lens_blur_generator.cpp, apps/local_laplacian/local_laplacian_generator.cpp, apps/nl_means/nl_means_generator.cpp, src/Generator.cpp, src/Generator.h
This is cleaner and less error-prone for Generators that use Output<> (rather than unnamed outputs from a build() method), as no outputs can be inadvertently left out.
=> Add auto_schedule_outputs() wrapper method to Generator

src/WrapCalls.cpp
Display the directly-called-functions as part of the user error, to aid in debugging confusing pipelines.
=> Enhance wrap-call error message

apps/HelloMatlab/run_blur.m
This has been broken since we made '-g' required as an argument to Generators a while ago...
=> Fix HelloMatlab

src/LICM.cpp
Alternative to #2393.  This disables LICM only for loops that will run in OpenGL (as opposed to turning it off anytime the target includes OpenGL).
CC @ronen
=> Disable LICM for OpenGL loops

src/AutoSchedule.cpp
If a var/rvar is not actually used in schedule, don't declare it. For example,
```
{
Var x = f0.args()[0];
Var y = f0.args()[1];
Var z = f0.args()[2];
Var n = f0.args()[3];
RVar r$x(f0.update(0).get_schedule().rvars()[0].var);
RVar r$y(f0.update(0).get_schedule().rvars()[1].var);
RVar r$z(f0.update(0).get_schedule().rvars()[2].var);
f0
.compute_root()
.split(x, x_vo, x_vi, 8)
.vectorize(x_vi)
.parallel(n)
.parallel(z);
f0.update(0)
.split(x, x_vo, x_vi, 8)
.vectorize(x_vi)
.parallel(n)
.parallel(z);
}
```
should be this instead:
```
{
Var x = f0.args()[0];
Var z = f0.args()[2];
Var n = f0.args()[3];
f0
.compute_root()
.split(x, x_vo, x_vi, 8)
.vectorize(x_vi)
.parallel(n)
.parallel(z);
f0.update(0)
.split(x, x_vo, x_vi, 8)
.vectorize(x_vi)
.parallel(n)
.parallel(z);
}
```
since the rvars …
=> Remove unncessary vars/rvars declaration in Autoschedule

src/AddImageChecks.cpp, src/CodeGen_Posix.cpp, src/StorageFlattening.cpp, src/Target.h, src/runtime/HalideRuntime.h
Uniformly ignore LargeBuffers if target's bit depth != 64 (only offender was StorageFlattening.cpp). Add use_large_buffers() as helper function to make this easier.
=> Ignore LargeBuffers for non-64-bit targets

Makefile, apps/linear_algebra/Makefile, apps/linear_algebra/src/blas_l1_generators.cpp, apps/linear_algebra/src/blas_l2_generators.cpp, src/Generator.cpp, test/CMakeLists.txt, test/generator/error_codes_generator.cpp, test/generator/memory_profiler_mandelbrot_generator.cpp, test/generator/user_context_generator.cpp
We had grandfathered in the ability to mutate the 'target' GeneratorParam at the start of build()/generate() because of some pre-existing usage; we're removing that ability because downstream usage is getting fixed, and allowing target to mutate is weird and bad; in essentially every case, setting the correct target in the build files is appropriate.
=> Disallow target mutation in generate()

src/runtime/write_debug_image.cpp, test/correctness/debug_to_file.cpp, test/correctness/image_io.cpp, tools/halide_image_io.h
This is the matlab level 5 format. It's not what matlab currently writes
(unless you set a flag), but matlab (and octave, and scipy, and
imagestack, ...) will be able to read it for the forseeable future, so
it's a good format for dumping things.
It's a fairly simple format, and it has also been added to ImageStack
already, so we should be able to just deprecate .tmp at some point if we
merge this.
TODO: Once HalideTraceDump is in, add .mat as a format option
=> Add .mat support

Makefile, src/CMakeLists.txt, src/LLVM_Runtime_Linker.cpp, src/runtime/alignment_128.cpp, src/runtime/alignment_32.cpp, src/runtime/cache.cpp, src/runtime/posix_allocator.cpp, src/runtime/runtime_internal.h
and make is possible to vary aligmnent per target
Alignment is selected via a runtime module containing an always-inline
function that returns the alignment. It gets constant-folded into its
uses.
Should fix #2422
=> Respect minimum alignment in the cache

src/Generator.cpp, src/Generator.h, test/generator/metadata_tester_generator.cpp
-- only provide synthetic generatorparams for values that aren't explicitly defined
-- add static_assert for Input/Output<Buffer<>[]>; it's not currently supported but failed in weird ways
-- drive-by cleanup of Input/Output<Buffer<>> T -> TBase checking which wasn't really right
-- allow declaring Output<Func> without a type or dim
=> Generator cleanup

src/runtime/HalideBuffer.h
The description refers to `buffer_t`, but the method now returns `halide_buffer_t`.
=> Documentation fix:  buffer_t -> halide_buffer_t

src/AutoSchedule.cpp, test/auto_schedule/extern.cpp
The autoscheduler can fail if it encounters a "trivial func" (func for which inlining is equal or cheaper than the lowest possible memory cost) which is consumed by an extern func. It will try to inline the trivial Func into the extern Func, which is illegal.
This PR adds a test exposing the problem, and consecutively a fix.
=> Autoscheduler bugfix: inlining trivial Funcs into extern Funcs.

src/Generator.cpp, src/Generator.h, src/ImageParam.h, src/Parameter.h, src/RDom.cpp, src/RDom.h, test/generator/rdom_input_generator.cpp
Instead of promoting Constrainable to a public interface (https://github.com/halide/Halide/pull/2394), let's just add conversion operators for `Input<Buffer> -> ImageParam` and `Output<Buffer> -> OutputImageParam`, as well as forwarding method stubs.
=> Remove Constrainable; add ImageParam casting

apps/bazeldemo/BUILD, apps/bilateral_grid/CMakeLists.txt, bazel/halide.bzl, halide.cmake, test/CMakeLists.txt
This makes it easier for newcomers to find the extra build artifacts (e.g. .stmt, .schedule). Also add some usage.
=> In Bazel+CMake rules, log extra_output locations

src/Generator.cpp, src/Generator.h
It's not tested (!), it's never been used, and it never seems likely to be used.
=> Remove Stub's templated construction method and related code

test/correctness/func_clone.cpp, test/correctness/func_wrapper.cpp, test/correctness/host_alignment.cpp, test/correctness/image_wrapper.cpp, test/correctness/likely.cpp, test/correctness/predicated_store_load.cpp, test/correctness/rfactor.cpp, test/correctness/simd_op_check.cpp, test/correctness/tracing_stack.cpp, test/generator/memory_profiler_mandelbrot_aottest.cpp
Putting "use std::string" in the global namespace can cause compilation problems in some *cough* environments. Wrap the uses inside test/ in namespace to mitigate this.
=> Wrap "use std::string" in namespaces

apps/linear_algebra/benchmarks/CMakeLists.txt
we previously failed if one-but-not-all entries in BLAS_VENDORS was found.
=> Smarten BLAS_VENDOR detection in linear_algebra benchmarks

bazel/halide.bzl
- allow generator_args to be an array-of-string instead of a string
- rework the way .h files are generated to be a bit more compile-time-efficient
=> halide.bzl improvements

src/Buffer.h, src/DeviceInterface.cpp, src/DeviceInterface.h, test/error/bad_device_api.cpp, test/error/device_target_mismatch.cpp, test/error/implicit_args.cpp, test/error/no_default_device.cpp
This will help users recognize and fix argument errors around device
API and the target it is paired with. In particular, requesting a
default GPU without specifying one in the target is a common
error. This is currently only wired up to report errors when used
through Halide::Buffer, but that is the common case. (Use of
error_site is both to help pin down where the error occurred and to give
a parameter that preserves the current behavior of returning nullptr
as it is likely some code depends on that.)
Add tests for errors. (Couldn't figure out an easy way to test missing
the runtime so that is not covered.)
Tab cleanup in unrelated file (implicit_args.cpp)
(This is an alternative to https://github.com/halide/Halide/pull/2392 .)
=> Better error messages for device_api to device interface failures.

src/CSE.cpp, src/IRVisitor.cpp, src/IRVisitor.h
- "visited" should be private
- restructure conditionals in include() to be less weird
- ComputeUseCounts should just call IRGraphVisitor::include() rather than duplicating it inline
=> IRGraphVisitor cleanup

test/scripts/build_travis.sh
- Set WITH_APPS=OFF since Make doesn't build them either (leave that to buildbot)
- use 'make Halide' + 'make test_internal' to match Makefile's 'make all' defaults
=> Tweak Travis CMake rules to reduce timeouts

apps/hexagon_benchmarks/Makefile, apps/hexagon_benchmarks/conv3x3_generator.cpp, apps/hexagon_benchmarks/dilate3x3_generator.cpp, apps/hexagon_benchmarks/gaussian5x5_generator.cpp, apps/hexagon_benchmarks/median3x3_generator.cpp, apps/hexagon_benchmarks/sobel_generator.cpp
Parallel and prefetch are off by default, and constructed to be
easily runnable with environment variables.
PARALLEL_SCHED=true PREFETCH_SCHED=true make run-arm-64-android
=> Add parallel and prefetch scheduling options to hexagon_benchmarks

apps/nl_means/process.cpp
This makes the non-local means benchmark take <10 seconds, down from about a minute. Hopefully this will noticeably speed up the build bots (test_apps is currently one of the longest steps, taking around 20 minutes).
=> Change non-local means benchmark to use one iteration instead of 10

src/Generator.h
The method-forwarding code in Generator could blithely return references to temporary objects on the stack. This was bad. Fix, and consolidate redundant method-forwarding macros while we're at it.
=> Don't return references to temporary objects

src/IRMutator.cpp, src/IRMutator.h, src/IRVisitor.h
- IRVisitor / IRMutator visit() methods should be protected, not public
- IRGraphVisitor is completely unused and not part of the public or internal interface to Halide, so just delete it
- add some 'override' annotation where appropriate
=> Minor Visitor/Mutator cleanup

CMakeLists.txt, halide.cmake
Changed .cmake files since newer versions of llvm appear to normally have the --system-libs option empty which prevented me from proceeding with the build. Works for llvm-4.0.
=> allow build to proceed when llvm-config --system-libs is empty

src/IRPrinter.cpp, src/IRPrinter.h, src/Module.cpp, src/StmtToHtml.cpp
Currently, when outputting a stmt or HTML file, submodules are gone, having been resolved to the appropriate blobs. This PR fixes that, so the stmt and HTML file have the contents of the submodules prior to resolving them.
=> Print submodules in stmt and HTML files

src/CodeGen_C.cpp
Fixes `error C3014: expected a for loop following OpenMP 'parallel for' directive`
=> Compilation error in MSCV

src/HalideFooter.h, src/Prefetch.cpp, src/SkipStages.cpp, src/Util.cpp, src/Util.h
Mostly in the case where no stages are skipped. It does a single pass
over the IR looking for candidates instead of one pass per Func.
On local laplacian this reduces stage skipping from 11ms to 0.13ms
Also included the timing helpers I wrote to make timing this sort of
thing inside the compiler easier.
Built on top of PR #2528
=> Faster skip stages2

halide.cmake
Typo prevents the usage of non-make generators, like ninja.
=> Fix typo in halide.cmake

CMakeLists.txt, Makefile
`llvm-config` returns nothing if `--system-libs` is called without `--link-static`.
https://reviews.llvm.org/rL291285
=> Append `--link-static` to `llvm-config` command

src/BoundsInference.cpp, src/Definition.cpp, src/Definition.h, src/Func.cpp, src/Func.h, src/Function.cpp, src/Function.h, src/ScheduleFunctions.cpp, src/SimplifySpecializations.cpp, test/correctness/extern_producer.cpp, test/correctness/introspection.cpp
Feature request from some Stanford hardware folks, in order to be able
to report better debug info from their backends. The task of actually
plumbing the source location from the Definition object down to their
backend is yet to be done. It can be accessed via the FunctionPtr on a
Call node. We should possibly preserve it in some other way after
storage flattening (Maybe on ProducerConsumer nodes?)
It may also be interesting to expose this to tracing or the profiler.
@rdaly525 @jeffsetter
=> Expose source code locations for Func definitions

src/Target.cpp
This PR makes calculate_host_target include Target::MSAN when the memory_sanitizer feature is available per the documentation at http://releases.llvm.org/3.5.0/tools/clang/docs/MemorySanitizer.html#has-feature-memory-sanitizer
=> Add Target::MSAN when the memory_sanitizer feature is available.

src/CodeGen_LLVM.cpp, test/correctness/non_vector_aligned_embeded_buffer.cpp
Fixes issue https://github.com/halide/Halide/issues/2478 .
Add a test for non-vector aligned embdedded buffers.
(Open question as to whether this works correctly for AOT embedded
buffers for sufficiently long vectors, but there are no bug reports as
yet.)
=> Handle case where an embedded buffer in JIT compilation is not vector aligned.

Makefile
If a precompiled header of the form Halide.h.gch exists in the same place as Halide.h, g++ will prefer it, provided all warning and optimization flags match. This speeds up building correctness argmax by 1 second (from 3s to 2s at O3, from 2s to 1s at O0).
clang will silently ignore it. It needs a more invasive set of flags to use PCH (the consumers have to opt-in).
=> Turn on PCH for g++ builds

src/Generator.cpp, src/Generator.h
Groundwork to make subsequent PRs easier to review:
- refactor two intertwined methods to be just one
- introduce some typedefs
- remove some dangling legacy unused methods
=> Cleanup some Generator internals

CMakeLists.txt, test/CMakeLists.txt, tutorial/CMakeLists.txt
As it turns out, the equivalence of certain CMake features between Makefile targets and MSVC targets is not exactly as advertised.
(Note that test_error still doesn't work properly for MSVC since it relies on a bash script; that will be fixed separately)
=> Revise the run_tests, test_correctness, etc targets in CMake for MSVC

src/IRMutator.cpp, src/IRMutator.h, src/IRVisitor.cpp, src/IRVisitor.h
When building against gcc 5.4. link error occurs:
CMakeFiles/build_correctness_func_clone.dir/correctness/func_clone.cpp.o:
In function `Halide::Internal::IRVisitor::IRVisitor()':
func_clone.cpp:(.text._ZN6Halide8Internal9IRVisitorC2Ev[_ZN6Halide8Internal9IRVisitorC5Ev]+0x9):
undefined reference to `vtable for Halide::Internal::IRVisitor'
The reason is the compiler selected to generate a default constructor of
IRVisitor/... inside func_clone.cpp.o because we did not provide one.
But it does not generates a vtable for IRVisitor/... in func_clone.cpp.o
I don't know why the compiler optimize away the vtable.
The way to fix the issue is to explicitly define the constructor.
So there will be only one constructor inside libHalide.so and
func_clone.cpp.o will not contain IRVisitor::IRVisitor(), …
=> Fix build against gcc 5.4

Makefile, apps/HelloMatlab/Makefile, apps/bilateral_grid/Makefile, apps/blur/Makefile, apps/conv_layer/Makefile, apps/fft/Makefile, apps/interpolate/Makefile, apps/lens_blur/Makefile, apps/linear_algebra/Makefile, apps/local_laplacian/Makefile, apps/nl_means/Makefile, apps/resize/Makefile
- Ensure that all of the apps have a 'test' build rule and just use it in a data driven loop.
- We don't need to make a local copy of the apps folder: ever since the apps Makefiles were revised to uniformly go into a bin/ folder, we can support in-tree builds by just prepending ROOT_DIR and setting BIN appropriately. (Note that we build into a subdir of the toplevel 'bin' directory rather than the per-directory bin dirs in this case.)
- Don't use 'make clean' for all of these targets; when testing on the buildbots, there is nothing to clean
=> Simplify test_apps rule

apps/linear_algebra/CMakeLists.txt
A Mac build environment may have `openblas` installed through Homebrew; if it does, the Homebrew installation is by default “unlinked,” due to [conflicts with Apple’s headers](https://github.com/Homebrew/homebrew-core/blob/30abddeed8f2b8d6e3d7b5ee313ddcd2c8ff1671/Formula/openblas.rb#L16-L17). Adding an explicit search path for the unlinked `openblas` installation allows it to be picked up by `cmake` and used accordingly.
=> CMake finds unlinked Homebrew `openblas` installs

python_bindings/python/RDom.cpp
RDom(ImageParam) was changed to RDom(OutputImageParam) a while back
=> Update RDom python binding

src/runtime/cuda.cpp, src/runtime/opencl.cpp
This makes the cuda and opencl overrides of buffer_copy match the semantics of the default buffer copy.
I found some cases where device_dirty was not set, but there was no host pointer. 
Also added a comment regarding streams that may be useful in the future.
=> Don't try to copy from null host pointers

Makefile, apps/camera_pipe/Makefile, apps/camera_pipe/camera_pipe_generator.cpp, src/Generator.h
- GeneratorParam<LoopLevel>::set() was wrong
- GeneratorParam<LoopLevel> instances need default values
- remove spurious Pipeline declarations that were holdover from the before-time
- Add camera_pipe to test_apps
=> Fix camera_pipe

python_bindings/python/Func_gpu.h, python_bindings/python/Var.cpp
We haven't decided to remove them from C++ yet, but we should go ahead and remove them from Python since usage is small
=> Remove python bindings for long-deprecated gpu functions

src/InjectHostDevBufferCopies.cpp
I encountered a bad schedule that didn't throw an error due to this continue. I can't see why this continue statement is there. Opening a PR to see if the buildbots agree with me.
=> Remove dubious lack-of-assert

python_bindings/Makefile, python_bindings/requirements.txt
- dependencies on /opt/local/* should be checked (won't exist unless MacPorts was used)
- always use python3 on Mac, to match Linux behavior (this may require an install of python3)
- add pillow to requirements.txt (scipy.misc won't run without it)
=> Tweaks to python_bindings/Makefile to allow OSX usage w/ Homebrew

apps/camera_pipe/Makefile, apps/camera_pipe/camera_pipe_generator.cpp, apps/camera_pipe/process.cpp
This PR adds a simple unsharp mask to the end of the camera pipe, which makes it a much more interesting pipeline to schedule due to an extra sliding window optimization required.
=> Add sharpening to camera pipe.

CMakeLists.txt, Makefile, test/CMakeLists.txt, test/scripts/build_travis.sh, tutorial/CMakeLists.txt
Settle on the convention of "test_{DIRNAME}" to avoid divergence between Make and CMake. (Note that this requires a change to buildbot as well.)
(Also, drive-by addition of missing dep for binary2cpp tool)
=> test_generators -> test_generator everywhere

src/Expr.h
left-shift-of-negative-value is UB in C++
=> Avoid UBSan failure

src/Func.h
A large class of scheduling operations would previously just segfault if you called them on undefined Funcs, eg
Func f;
f.parallel(x);   // crash!
This inserts a couple of assertions to make the failure much kinder and more helpful.
=> Add assert failures for scheduling undefined Funcs

src/Func.cpp, src/Func.h, src/Var.cpp, src/Var.h, test/correctness/extern_producer.cpp, test/correctness/extern_reorder_storage.cpp
This PR makes it possible to name the dimensions of extern stages, which makes it easier to use storage scheduling directives on them.
=> Enable naming dimensions of extern stages

python_bindings/Makefile, python_bindings/correctness/basics.py, python_bindings/python/Error.cpp, python_bindings/python/IROperator.cpp
- Halide errors turn into Python exceptions (both compile and runtime)
- properly implement print and print_when and connect them to Python stdout
- add tests as appropriate
=> Fix python errors and logging

src/runtime/write_debug_image.cpp
… this is another instance of the bug addressed in https://github.com/halide/Halide/commit/b1cfc23db88d230e914bd9624ab3523b8dc85a77
=> Insert one more explicit cast to deal with “int-> uint32_t” issue

python_bindings/Makefile, python_bindings/correctness/basics.py, python_bindings/python/Error.cpp, python_bindings/python/IROperator.cpp
Reverts halide/Halide#2620
Apparently `raw_function()` isn't available in all versions of boost.python we are compiling under (I foolishly landed this during our buildbot outage thinking it was low risk); reverting to unblock buildbots.
=> Revert "Fix python errors and logging"

python_bindings/Makefile, python_bindings/correctness/basics.py, python_bindings/python/Error.cpp, python_bindings/python/IROperator.cpp
- Halide errors turn into Python exceptions (both compile and runtime)
- properly implement print and print_when and connect them to Python stdout
- add tests as appropriate
=> Fix python errors and logging (take 2)

src/HexagonOffload.cpp, src/LLVM_Output.h
This is not something that will really work in very many use cases, but it's enough to help debug many of the correctness tests, and not having this has caused a lot of pain.
=> Add HL_HEXAGON_DUMP_BITCODE environment variable

python_bindings/apps/bilateral_grid.py, python_bindings/apps/blur.py, python_bindings/apps/erode.py, python_bindings/apps/interpolate.py, python_bindings/apps/local_laplacian.py, python_bindings/correctness/basics.py, python_bindings/correctness/compile_to.py, python_bindings/correctness/extern.py, python_bindings/correctness/rdom.py, python_bindings/src/PyIROperator.cpp, python_bindings/tutorial/lesson_01_basics.py, python_bindings/tutorial/lesson_02_input_image.py, python_bindings/tutorial/lesson_03_debugging_1.py, python_bindings/tutorial/lesson_04_debugging_2.py, python_bindings/tutorial/lesson_05_scheduling_1.py, python_bindings/tutorial/lesson_06_realizing_over_shifted_domains.py, python_bindings/tutorial/lesson_07_multi_stage_pipelines.py, python_bindings/tutorial/lesson_08_scheduling_2.py, python_bindings/tutorial/lesson_09_update_definitions.py, python_bindings/tutorial/lesson_10_aot_compilation_generate.py, python_bindings/tutorial/lesson_10_aot_compilation_run.py, python_bindings/tutorial/lesson_11_cross_compilation.py, python_bindings/tutorial/lesson_12_using_the_gpu.py, python_bindings/tutorial/lesson_13_tuples.py, python_bindings/tutorial/lesson_14_types.py
Previously we used a mix of importing everything into the global namespace, or using 'h' or 'halide' as aliases for the module; we now settle on the two-letter convention common in Python, using 'hl' for our alias.
=> Update import/naming convention for Python bindings

src/Buffer.h, src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
Adds a method to the Buffer class to easily check if all elements in a buffer are set to a specific value. 
The motivation for the change is that I often find myself checking the contents of a Halide buffer in tests. I have a helper function to do the comparison but it would be cleaner/easier to just have a method on the buffer.
=> Adds new helper method to a Halide buffer

src/HexagonOffload.cpp
Otherwise, an LLVM crash will prevent the bitcode from being written.
=> Dump Hexagon bitcode before trying to compile it.

src/Buffer.h, src/runtime/HalideBuffer.h
Makes all_equal a const method.
The lack of const did not sit well with me, this changes that method to const by using the `for_each_element` method instead of `for_each_value`.
=> Make all_equal a const method.

src/RealizationOrder.h, src/Schedule.h, src/ScheduleFunctions.cpp
- Mismatched prototype arg names
- prefer .empty() to .size() == 0
=> Fix a few minor ClangTidy warnings

src/runtime/HalideRuntimeCuda.h, src/runtime/HalideRuntimeHexagonHost.h, src/runtime/HalideRuntimeMetal.h, src/runtime/HalideRuntimeOpenCL.h, src/runtime/HalideRuntimeOpenGL.h, src/runtime/HalideRuntimeOpenGLCompute.h, test/generator/gpu_only_aottest.cpp
This allows code including a pipeline to determine if the runtime is present at compile time.
=> Add #defines indicating the header is present

src/Simplify.cpp
We had a user encounter this warning when shifting a 16-bit integer by 15. This seems like it should be fine to do, and the code works as intended (even though we can't rewrite to a mul/div like we want to here).
We should maybe warn when the shift is >= bits (rather than >= bits - 1) instead of removing the warning entirely. However, this same user also had a case that did exactly this, and this warning did *not* fire, so something else is going on there.
=> Remove spurious warning when shifting by (bits - 1).

python_bindings/correctness/type.py, python_bindings/src/PyExpr.cpp, python_bindings/src/PyParam.cpp, python_bindings/src/PyType.cpp, python_bindings/src/PyType.h
Bring Python bindings for Halide::Type 100% up to date, with complete tests for all binding bits.
=> Update Python bindings for Type

python_bindings/correctness/var.py, python_bindings/src/PyVar.cpp
Boost.Python has different constraints for Py2 vs Py3.
=> Fix Python 2.7 incompatibility in Python Bindings

python_bindings/src/PyTarget.cpp, src/CodeGen_OpenCL_Dev.cpp, src/IROperator.h, src/Target.cpp, src/Target.h, src/runtime/HalideRuntime.h
- Add a new 'cl_half' target feature to enable OCL half support.
- Define math functions for f16.
- Fix a minor issue in is_nan implementation on half.
- Enable python support as well.
=> Enable OpenCL half support

src/Bounds.h, src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
make_with_shape_of() required the src and dst to be strongly typed, but there's no reason to do so; being able to copy to/from a Buffer<void> is fine as long as runtime types match.
Also, did unrelated drive-by fix in Bounds.h to fix an int-vs-size_t compiler warning for some configurations.
=> Allow Buffer::copy() to work to/from Buffer<void>

Makefile, src/CMakeLists.txt, src/CodeGen_X86.cpp, src/LLVM_Runtime_Linker.cpp, src/runtime/x86_avx2.ll, test/correctness/simd_op_check.cpp
Create the AVX2 runtime container and add implementations of saturated
truncate functions.
=> X86 Runtime: AVX2 implementation of saturated truncate functions

src/runtime/HalideBuffer.h
This makes Python bindings much easier to write.
=> Add non-variadic versions of Buffer::set_min() and Buffer::contains()

src/runtime/HalideBuffer.h
We allocate this via calling alloc-fn, casting to the right type, then setting the field values; if std::atomic<int> has internal fields other than the `int`, they might not get inited properly. Use placement-new to fix this.
(I don't know of any actual malfunction this is causing, it was just potentially-wrong by inspection)
=> Ensure that Buffer::AllocationHeader runs all ctors

src/Func.cpp, src/Func.h
Reverts halide/Halide#2697 -- some downstream usage of these needs to be cleaned up. Reverting for now, will resubmit in a few days.
=> Revert "Remove long-deprecated variants of gpu_tile()"

python_bindings/correctness/buffer.py, python_bindings/src/PyBuffer.cpp, src/Buffer.h
The previous pybind code didn't properly manage the lifetime of Python buffer objects when used to construct a Buffer in a shared way. We now use a PyBind alias object for buffers to ensure the lifetime is managed properly.
=> Fix pybind's buffer-info lifetime management

python_bindings/src/PyScheduleMethods.h, src/Func.cpp, src/Func.h
Removing them once again, and also updating the other variants that were split into multiple versions as a result.
=> Remove long-deprecated gpu_tile() methods, Take 2

src/runtime/posix_io.cpp
Attempt to unify halide_print() output to stdout (or equivalent) everywhere.
=> posix_io outputs to stdout instead of stderr (Issue #2686)

src/Buffer.h
Initing a Buffer<> field to an undef Buffer<> value (e.g. from calling Variable::make) triggers UBSan failures (referencing to an offset of a null contents ptr).
=> Avoid UBSan failures

src/LICM.cpp
This PR allows substituting reinterpret calls back in the LICM pass by setting the cost of a reinterpret call to zero.
=> Allow substituting reinterpret calls back in LICM.

src/Generator.h, src/Parameter.cpp, src/Parameter.h
The implicitly-define move ctor for Parameter didn't handle object instance registry tracking, which is must do. (Other usages should never be copyable or movable; move ops were deleted to ensure this.)
=> Add move ctor/op= for Parameter

src/Expr.h, src/Generator.cpp, src/Module.cpp, src/Module.h
Various declaration-vs-definition-names-differ warnings to silence downstream nags
=> Fix minor clang-tidy warnings

src/Generator.h, test/correctness/loop_level_generator_param.cpp
A much-simpler alternative to PR#2720. Note that the interesting change is really all in the override to set() in GeneratorParam_LoopLevel (the changes to the base class implementation are just drive-by simplification to make that override a bit easier to reason about).
=> Revise GeneratorParam<LoopLevel>::set() work for both before-and-after generate() usage

apps/linear_algebra/Makefile, apps/linear_algebra/src/blas_l2_generators.cpp, apps/linear_algebra/src/halide_blas.h
Change ger to be in-place, and simplify the schedule.
Performance now closer to openblas for me on the larger sizes, and is
much faster on the smaller sizes. Rightmost column is proportional to
flops
```
Halide      sger      32            0.081833             13.2953
Halide      sger      64            0.226842             18.6209
Halide      sger     128            1.073608             15.4991
Halide      sger     288            7.498786             11.1378
Halide      sger     544           29.680935             10.0072
Halide      sger    1056          121.922739             9.16357
Halide      sger    2080         1147.310148             3.77453
OpenBLAS      sger      32           35.603869           0.0305585
OpenBLAS      sger      64           68.888618           0.0613164 …
```
=> reschedule ger

python_bindings/Makefile
Fixes compatibility with various Python environments (seen in several Mac Anaconda Python 3.6 distributions), following the [PyBind11 build instructions](https://github.com/pybind/pybind11/blob/master/docs/compiling.rst#building-manually) more carefully. In particular, don’t pre-link libpython, but rely on lazy linking at load time of the module in a given interpreter.
Includes some related cleanup of the bindings Makefile.
=> Fix python_bindings build

python_bindings/Makefile, python_bindings/correctness/buildmethod_generator.cpp, python_bindings/correctness/nobuildmethod_generator.cpp, python_bindings/correctness/partialbuildmethod_generator.cpp, python_bindings/correctness/pystub.py, python_bindings/stub/PyStubImpl.cpp, src/Generator.cpp, src/Generator.h
Revised version of https://github.com/halide/Halide/pull/2768, but explicitly forbidding 'old' and 'partial-new' Generators for now.
=> Verify that Python stubs work only with new-style Generators

tools/halide_image_io.h
Fun fact: when compiling for 32-bit, most GCC versions will emit x87 rather than sse2 -- even with -march=native -- unless you also specify -mfpmath=sse; this fact makes the previously happened-to-roundtrip functions round incorrectly in some cases. (The adding-one-half should have been present anyway.)
=> Add rounding to halide_image_io conversion functions

python_bindings/stub/PyStubImpl.cpp
If a client doesn't use halide.so as a shared runtime, the stubs won't have any error handlers, and will simply crash. This ensures that the stubs always have errors properly hooked.
=> Add error-handling code to PyStubImpl.cpp

python_bindings/correctness/compile_to.py, python_bindings/src/PyEnums.cpp, python_bindings/src/PyExternFuncArgument.cpp, python_bindings/src/PyFunc.cpp, python_bindings/src/PyHalide.cpp, python_bindings/src/PyOutputs.cpp, python_bindings/src/PyOutputs.h, python_bindings/todo.txt
- Note that this implements ~all of the public Func methods but leaves them largely untested
- Things that seemed inappropriate for a Python API (e.g. custom malloc handlers) were omitted and noted
- A few things that override runtime functionality were deliberately left out for now (e.g. custom error handler), even though the implementation is simple, mainly because I want us to think a bit more about whether 'runtime' functions in Python need to be handled specially.
=> Finish the Python bindings for Func

src/CodeGen_C.cpp, src/CodeGen_LLVM.cpp, src/CodeGen_LLVM.h, src/Generator.cpp, src/Generator.h, src/HexagonOffload.cpp, src/IRPrinter.cpp, src/IRPrinter.h, src/Lower.cpp, src/Lower.h, src/Module.cpp, src/Module.h, src/Pipeline.cpp, src/Pipeline.h, src/WrapExternStages.cpp
Since it's necessary for a public API (Pipeline::compile_to_module), it should be in a public namespace rather than Internal.
=> Move LinkageType into public Halide namespace

CMakeLists.txt
This is the infamous "forcing value to bool 'true' or 'false' (performance warning)" oddness.
This warning is no longer emitted by VC2017, so by leaving it in, we're getting warnings (-as-errors) that only repeat in VC2015. Even in VC2015, it's basically a giant pile of low-information noise that only causes weird Windows-specific breakages.
See https://developercommunity.visualstudio.com/content/problem/78259/visual-studio-2017-no-longer-generates-a-c4800-war.html for more info.
=> Disable Warning C4800 in MSVC

src/Generator.cpp, src/Generator.h
Setting these from a Build/Make file parsed the input string as a single char, not int, leading to amusing failures.
=> GeneratorParam<int8|uint8> should be parsed as ints, not chars

.travis.yml, CMakeLists.txt, Makefile
Also:
- make permanent a change that was "LLVM4 or newer"
- add "no longer tested" warning when LLVM4 is detected
=> Travis: stop testing with LLVM4, start testing with LLVM6

Makefile, src/Generator.cpp, src/Generator.h, test/CMakeLists.txt, test/generator/metadata_tester_aottest.cpp, test/generator/metadata_tester_generator.cpp, test/generator/stubtest_aottest.cpp, test/generator/stubtest_generator.cpp, test/generator/stubtest_jittest.cpp, test/generator/stubuser_aottest.cpp, test/generator/stubuser_generator.cpp
This had been unsupported in new-style Generators, mainly because it wasn't clear there was demand for it, so we never got around to implementing it; now it's clear there is demand for it, and support is pretty simple, so we're adding it.
=> Add support for array-of-Buffer in Input<> and Output<>

python_bindings/src/PyHalide.cpp
At least one downstream environment may want us to wrap Python .so files with a .py file; this allows us to rename the extension module at build time, to avoid module name collisions.
=> Allow the Python module name to be customized via preprocessor

apps/bilateral_grid/Makefile, apps/camera_pipe/Makefile, apps/camera_pipe/viz.sh, apps/local_laplacian/Makefile, util/HalideTraceViz.cpp
- don't crash if a label's framecount is <= 0
- better parsing of int and float values for fast-failure, plus recognizing hex ints
- use std::vector<> instead of new[] for buffer allocations and for stride arrays
- printf -> iostream
- minor code style fixes
- add 'make viz' targets to the apps that use HalideTraceViz
Note to reviewers: camera_pipe.mp4 seems to be empty and useless (at least on my OSX machine) both before and after this PR, so something is amiss there. Since the brokenness seems unchanged, it should probably be investigated separately.
=> HalideTraceViz cleanup

src/IRVisitor.cpp
Don't call count(); instead, just call insert(), and check the function result see if the insertion was new. On an extremely gnarly case inside Google (where the set could get into hundreds-of-thousands) this shaved over 1% off of the entire pipeline compile time.
(Interestingly, moving from set to unordered_set didn't make any difference; it may be that an unordered_set using a carefully chosen hash function might be a further win.)
=> Speed up IRGraphVisitor

python_bindings/stub/PyStubImpl.cpp
Prefer `empty()` to `size() == 0` (and inverse)
=> Minor clang-tidy fixes

CMakeLists.txt, apps/CMakeLists.txt
Tried adding Halide as a CMake subdirectory, 
```
add_subdirectory(thirdparty/Halide)
```
it ended up looking for files in the wrong places! It was using [${CMAKE_SOURCE_DIR}](https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html), which is the path to the top level of the current CMake source tree. 
It should be using [${CMAKE_CURRENT_SOURCE_DIR}](https://cmake.org/cmake/help/latest/variable/CMAKE_CURRENT_SOURCE_DIR.html) which is the directory containing the CMakeLists.txt thats currently being processed.
=> swap from CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR

util/HalideTraceViz.cpp
Allow for shrinking as well as growing, and fractional zooms as well, for tweaking output.
=> HalideTraceViz should allow fractional --zoom

apps/local_laplacian/viz.sh, util/HalideTraceViz.cpp
These are all minor but worthwhile; offering as a separate PR in order to make some future PRs less noisy. Changes:
-- Labels use std::string instead of char*
-- keep strides as a single vector<pair<int, int>> instead of two separate vectors
-- some extra assertions and error checking
-- The Config struct now initializes to the proper default values rather than useless values which we immediately replace
-- local_laplacian doesn't fail if the mp4 already exists
(Note that this is built on top of https://github.com/halide/Halide/pull/2826 and includes those changes)
=> Various minor TraceViz code tweaks

src/runtime/printer.h
When using printer in stringstream mode, we never marked the data as inited-for-msan when just grabbing the str; this could lead to erroneous MSAN failures when profiling is enabled.
=> Add msan_annotate_is_initialized() to printer::str()

test/correctness/compute_with.cpp, test/correctness/interleave.cpp, test/correctness/mul_div_mod.cpp, test/correctness/oddly_sized_output.cpp, test/correctness/partition_loops.cpp, test/correctness/vector_math.cpp
From getting them building elsewhere, some of which are UBSan failures:
- ensure that 'using std::whatever' is always in a namespace, never at global scope
- doing an out-of-range float->char cast is UB, and the compiler is allowed to generate wrong code in that case. (Ask me how I know.)
- Fill in some Buffers to avoid random data causing signed-int-overflow errors
- Avoid float-divide-by-zero in some test data; even though it's legal, our handling of non-finite numbers makes it problematic
- Accessing Buffers out of bounds is bad. Don't do that.
- Tweak muldivmod to avoid integer overflow.
=> Various test fixes

src/Func.cpp, src/Func.h, src/Pipeline.cpp, src/Pipeline.h
Casting the deleter function to a different function type, then calling it, produces UB warnings from UBSan. Rework to use a no-arg std::function for the deleter, and wrap up the necessary deletion in a lambda to avoid the casting.
(Why aren't the custom lowering passes just passed in via unique_ptr or shared_ptr?)
=> Remove UB from add_custom_lowering_pass

Makefile, test/performance/block_transpose.cpp, test/performance/clamped_vector_load.cpp, test/performance/memcpy.cpp
This allows us to run more easily in Blaze/Bazel environments, where working directories are not writable, and running with a custom working directory is inconvenient. (It also conforms with all other tests which made this change long ago)
=> Modify test/performance to use get_test_tmp_dir()

test/correctness/image_io.cpp, tools/halide_image_io.h
this can happen when artificially adding dimension(s) of extent 1, e.g. to write a .tmp file, which requires exactly 4 dimensions
=> Allow for compact-planar images with non-increasing strides

src/Type.cpp, src/Util.h, test/correctness/saturating_casts.cpp, test/performance/const_division.cpp, test/performance/thread_safe_jit.cpp, test/performance/vectorize.cpp
- Casting float->int is UB if the value won't fit in the destination; this fixes more cases found by running under UBSan.
- const_division had a left-shift-out-of-bounds UB to generated random numbers; 'fixed' by replacing with std::mt19937, which is more stable for tests anyway
- thread_safe_jit can overflow the int32 used for some calculations; int64 needed for intermediates
=> Fix more UB

python_bindings/src/PyScheduleMethods.h, src/BoundaryConditions.h, src/Error.h, src/Func.h, src/Generator.cpp, src/Generator.h, src/IROperator.h, src/ImageParam.h, src/Param.h, src/Parameter.h, src/Pipeline.h, src/RDom.h, src/Tuple.h, src/Util.h, src/runtime/HalideRuntime.h
The current NO_INLINE macro actually means "don't inline if we are in user code, but if we are compiling Halide, do whatever".
This PR adds a new HALIDE_NEVER_INLINE macro, which is the opposite of HALIDE_ALWAYS_INLINE: it never inlines code, period. (It is meant to be useful in header-only libraries like halide_image_io.h, where being able to specify some functions as never-inline can be a useful hint to the compiler.)
The existing NO_INLINE macro is renamed to HALIDE_NO_USER_CODE_INLINE to more accurately reflect its meaning (and to give a HALIDE_ prefix to it, which it should have always had).
=> Split NO_INLINE in two

src/Closure.cpp
At least one user of this class assumes that it's possible for a buffer
in the scope to be both read and written:
https://github.com/halide/Halide/blob/80a48bf501e53f6f6e6b419ba60dc4839f2862e1/src/HexagonOffload.cpp#L821
However, currently the last access always wins.
=> Handle buffers that are both read and written.

src/Generator.h, src/ImageParam.cpp, src/ImageParam.h, src/Tracing.cpp, util/HalideTraceViz.cpp
- ImageParam and Input<Buffer> need forwarding methods
- Tracing.cpp didn't handle trace_all_loads and could have duplicates emitted, and didn't handle all Call nodes correctly
- HalideTraceViz: process (but ignore) trace_tag nodes; dump the trace_tag to output; drive-by cleanup to emit Labels in verbose mode; drive-by fix to text fade-in calculation time
(split from #2838 as some of the details of that are still under debate)
=> Add a few missing pieces for add_trace_tag()

Makefile, apps/support/Makefile.inc
I have an ubuntu system with system-installed llvm-6 which requires tinfo but doesn't report that fact anywhere in llvm-config output. Annoying. This PR adds detection for that scenario to the Makefile.
The cmake build doesn't have the same problem - the installed LLVM cmake package adds -ltinfo unconditionally
=> libtinfo fix for some ubuntu systems

src/AlignLoads.cpp, src/AlignLoads.h, src/CodeGen_Hexagon.cpp
This helps more things align. This always would have been helpful, but it's more important now that LICM often lifts strides into lets outside of device loops.
=> Plumb alignment of closure params to AlignLoads

src/Bounds.cpp, test/correctness/strict_float_bounds.cpp
Bounds(Call) assumes the worst for calls it doesn't know about, so strict_float(foo) becomes (neg_inf, pos_inf) rather than (foo, foo) (a la 'likely'), exploding bounds checking.
Note 1: this needs a test to be written; I haven't done so yet because I'm puzzled as to how this isn't covered in our existing tests (it was found inside Google code).
Note 2: it's possible that some of the other 'likely' special cases need special-casing here too; I'm not familiar enough with the Bounds code to have decided whether that's the case or not. (The fix "as-is" here fixes the cases I know about.)
=> Bounds calculations needs to understand strict_float

apps/hexagon_benchmarks/adb_run_on_device.sh, src/runtime/synchronization_common.h
apps/hexagon_benchmarks puts multiple filters together into one archive before linking. This results in a "multiple definitions" problem affecting functions in synchronization_common.h (fast synchronization) because they aren't weak.
=> Fix multiple definitions in fast synchronization

apps/camera_pipe/viz.sh, apps/local_laplacian/local_laplacian_generator.cpp, util/HalideTraceViz.cpp
Add a visualization for the remap LUT in local_laplacian to test/demonstrate. (I verified locally the 0d Funcs also work, but am not including a demonstration.)
=> Tweak HTV to render 1d and 0d Funcs properly

apps/bilateral_grid/bilateral_grid_generator.cpp, apps/bilateral_grid/viz.sh, tools/halide_trace_config.h, util/HalideTraceViz.cpp
This allows us to set (e.g.) timestep or framesize via trace_tags in the code, rather than command-line flags.
Note that this is of limited use at present, as the existing flags tend to be sensitive to input data and thus may be better specified on the command line; however, this provides a good mechanism to specify future params related to automatic layout.
=> Add trace_tag for 'global' visualization params

src/Util.cpp
If I read the spec correctly, std::atomic<> default ctor doesn't promise any initialization; if we leave these as-is, we can get different uniquenames from build to build, leading to trivially differing build results that upset some build correctness checks.
=> initialize unique_name_counters to zero

src/Module.cpp
This helped build throughput a little bit, but can introduce a subtle nondeterminism in multitarget builds: different unique_names can be chosen if the modules are built in different order, since the unique_name_counters global is never reset; build tooling that looks for nondeterminism in builds will (rightly) occasionally find it here. Since the performance improvement from this threading was modest in the first place, just remove it entirely.
=> Remove threading from compile_multitarget

apps/camera_pipe/camera_pipe_generator.cpp, apps/camera_pipe/viz.sh, apps/local_laplacian/local_laplacian_generator.cpp, tools/halide_trace_config.h, util/HalideTraceViz.cpp
The goal here is to allow some-but-not-all fields in FuncConfig to be specified, so that we can override some-but-not-all aspects of a visualization.
As it is, this means you can specify a FuncConfig via a trace-tag, then tweak/override values via --flag values without having to rebuild/rerun the Halide generation code.
This will become especially useful after auto-layout for visualizers is put into place, as that will allow you to just use auto-layout to get a rough visualization, and then (if desired) tweak it piece-by-piece (by adding trace-tag and/or --flags) to get a pleasing layout.
Note that I implemented the structs by using 'magic invalid values'; a perhaps-cleaner-but-more-expensive approach would be to have each field allocated by std::unique_ptr, with nullptr meaning "not …
=> Rework FuncConfig to allow merging/optional fields

util/HalideTraceUtils.h
UBSan (etc) will rightly complain that value_as<>() does unaligned loads from the scalar union; have the caller memcpy to a local to avoid this. Also, drive-by change from const-ptr to const-ref.
=> Remove unaligned-access in HalideTraceUtils

src/runtime/tracing.cpp
If multiple threads requested packets at the end of the buffer, you could end up with a bad packet if the back-out was ordered in a certain way. Instead, don't try to back out, just let all requests fail till the next flush(), but record the total overage so we know how much to ignore.
=> Fix race condition in tracing runtime

src/Util.h
don't apply __declspec(dllexport) to all exports when building halide with HALIDE_SHARED_LIBRARY=OFF.
=> msvc: fix static build.

src/Util.h
Reverts halide/Halide#2902
This has broken the Win64 builds; we didn't notice because the Windows buildbots were down. Please feel free to re-submit after testing.
=> Revert "msvc: fix static build."

src/Tracing.cpp, src/VectorizeLoops.cpp, src/runtime/tracing.cpp
In theory these should be equivalent, but moving the adjustment to where the rest of the call the trace is mutated is more sensible
=> widen trace-packet dimensions in VectorizeLoops, not trace_helper

apps/nl_means/nl_means_generator.cpp
This bug manifests more subtly than one might expect, it only produces a clearly visible artifact for patch_size=1 (makes sense in hindsight).
=> Fix bug: patches and searches weren't centered

src/Tracing.cpp, src/VectorizeLoops.cpp
begin/end_realization events got vectorized in a way that increased the number of dimensions by the vector width in a bizarre way, e.g. if the realization was sum(vectorize(4)), a 1-dimensional realization would emit a 4d begin_realization, with the data in the form (min0..3, extent...3). Code downstream (e.g. HTV) could probably recognize and deal with this situation but it seems better to try to handle it here.
=> VectorizeLoops needs to specialize Call::trace even more

python_bindings/correctness/pystub.py, src/Generator.cpp, src/Generator.h, test/generator/stubtest_generator.cpp
- If a bad GeneratorParam is specified, name the Generator for which it failed
- if a synthetic param is specified that isn't settable (ie a .type for which one is concretely specified), give an error message indicating it isn't settable, rather than that it is "missing"
=> Improve Generator error messages

src/Generator.cpp, src/Generator.h
These were de-constifying recently, but downstream code relies on them being const. Use mutable fields instead.
=> Make types(), dim(), etc const again

src/Bounds.cpp, test/correctness/popc_clz_ctz_bounds.cpp
Downstream code will fail if it encounters vector values in Intervals (eg BoundSmallAllocations); the code added in https://github.com/halide/Halide/pull/2896 needs to ensure the interval created is scalar.
=> Bounds for popc/clz/ctz needs to be scalar

Makefile
Potential workaround for #2940.  Creating a PR to get build coverage.
=> Use system libraries when creating LLVM object list

apps/auto_viz/Makefile, apps/bilateral_grid/Makefile, apps/bilateral_grid/viz.sh, apps/camera_pipe/Makefile, apps/camera_pipe/viz.sh, apps/local_laplacian/Makefile, apps/local_laplacian/viz.sh, apps/resize/Makefile, apps/support/Makefile.inc, apps/support/viz_auto.sh, tools/halide_trace_config.h, util/HalideTraceViz.cpp
- include <cstring> for memcpy
- std::istream doesn't always understand 'nan'
- Use env vars to allow redirecting avconv and mplayer to other similar utilities (e.g. ffmpeg/mpv)
=>  Fix portability issues in HTV

apps/auto_viz/Makefile, apps/bilateral_grid/Makefile, apps/camera_pipe/Makefile, apps/local_laplacian/Makefile, src/Target.cpp, test/correctness/target.cpp, tutorial/figures/generate_figures_17.sh, tutorial/figures/generate_figures_18.sh, tutorial/figures/generate_figures_19.sh, tutorial/figures/generate_figures_5.sh, tutorial/figures/generate_figures_8.sh, tutorial/figures/generate_figures_9.sh, util/HalideTraceViz.cpp
It's common to set all three in tandem, so, for terseness:
- when creating Target from string, if "trace_all" is a feature, apply trace_loads|trace_stores|trace_realizations
- when creating string from Target, if trace_loads|trace_stores|trace_realizations are all set, replace with "trace_all"
(Should we be terser and just use "trace" instead of "trace_all"?)
=> Allow "trace_all" as synonym for trace_loads|trace_stores|trace_realizations (Issue #2914)

src/WrapExternStages.cpp, src/runtime/HalideRuntime.h, src/runtime/old_buffer_t.cpp
If you have a define_extern that uses the legacy_buffer_t wrappers, and that extern is inside a parallel loop, there is a benign race condition: the input buffer(s) are always 'upgraded' at the end (in case the call is a bounds query). This causes a benign data race in the non-bounds-query case since another thread can be reading from the input buffer at the same time. The fix: when generating the wrapper for define_extern, only upgrade input buffers if it is known to be a bounds query.
=> Fix benign race in halide_upgrade_buffer_t

src/LLVM_Output.cpp
addPassesToEmitFile has an extra parameter now for DWO output.  Adjust the call
accordingly.
=> adjust for API changes in LLVM

tools/halide_trace_config.h, util/HalideTraceViz.cpp
- do_auto_layout should process funcs that have config_valid set, to allow for partial specification of tags
- add a default-unit-color option that is used when there is no func-specific uninit color.
- add a 'magic' uninit color value (0x010101) that means "render in checkerboard"; this is the default for auto-layout.
=> Various HTV fixes

src/HexagonOptimize.cpp, src/Simplify.cpp, test/correctness/simd_op_check.cpp
These rules were brittle, expressions of the form `((x*2*N) + 16384) / 32768)` would fail to match the intended pattern because the simplifier would cancel the factor of 2 from the expression. These new rules are more robust. 
This should enable fixing some issues with simplifier rules in #2845.
This PR also adds simplifications for shifts by zero.
=> Better pattern matching of truncating multiplies on Hexagon

src/runtime/HalideBuffer.h
I've needed this several times now.
=> Add a variant of Buffer::make_scalar for non-owned data

python_bindings/src/PyBuffer.cpp, src/runtime/HalideBuffer.h, test/correctness/image_io.cpp, tools/RunGen.cpp
- Add overloads for slice()/sliced() that default 'pos' to min-of-that-dimension
- Add overloads for embed()/embedded() that default 'pos' to zero
- slice() now asserts that the pos is within that dimensions valid range [the lack of this assert did actually bite me in real code]
- Adjust a few uses of these calls to skip the now-defaulted arg where it makes sense
=> Fixed to embed()/slice() and friends

src/CodeGen_ARM.cpp, src/CodeGen_ARM.h
These are changes in CodeGen_ARM.cpp to catch the pattern `broadcast(widen(scalar))` and flip their order to `widen(broadcast(scalar))` so that LLVM generate the correct `vmlal.*` instructions. 
Please refer to https://github.com/halide/Halide/issues/2997
=> Changes to make vmlal.* work

src/CodeGen_Internal.cpp
This is more likely to work in every compilation environment. Makes zero difference to the assembly generated by local laplacian, and thus no performance difference. Similarly makes zero performance difference in other performance canaries I've tested (fft, performance_inner_loop_parallel).
=> Switch to the large code model (fPIC vs fpic)

src/Buffer.h, src/Func.cpp, src/runtime/HalideBuffer.h
Previously we explicitly allowed crop() calls that expanded the Buffer, as the implementation of Func::infer_input_bounds() relied upon it. This is a dangerous and bad idea. Add assertion-checks that require crop() goes inward, and fix the implementation of Func::infer_input_bounds() to not rely upon the previous behavior.
=> Disallow unsafe Buffer::crop calls()

Makefile
This is necessary to appease install_name_tool in some situations by ensuring there is plenty of padding in the built file (which is causing build failures on some mac-32 systems)
=> Add -headerpad_max_install_names when linking shared libs on Mac

python_bindings/Makefile, python_bindings/correctness/bit_generator.cpp, python_bindings/correctness/bit_test.py
Test that if we try to call a function that operates on bit arrays, we always get NotImplementedError.
This is based on https://github.com/halide/Halide/pull/2975 and won't work without it. Also it's currently disabled on Mac, because of https://github.com/halide/Halide/pull/3010#issuecomment-393945790
=> Add unit test for NotImplementedError from Python extension.

src/InjectHostDevBufferCopies.cpp, test/correctness/extern_producer.cpp, test/correctness/extern_stage_on_device.cpp
The `!finder.touched_by_extern` clause seem unnecessary now because `finder.devices_touched` already tracks DeviceAPI of the extern definition. This clause now prevents the host allocation elimination if a buffer is only touched an extern definition and a normal definition with the same DeviceAPI.
=> Relax the condition for eliminating host allocation in inject_host_dev_buffer_copies.

src/Prefetch.cpp, src/ScheduleFunctions.cpp, src/Simplify.cpp, test/correctness/prefetch.cpp
Add simplifier to remove Prefetch IR when the predicate is always false. Also remove the Prefetch IR, if during `inject_prefetch`, the region being prefetched is empty. 
During `schedule_functions`, placeholder prefetches need to be peeled off; otherwise, the prefetch will end fail to account of function calls by the producer computed within that loop level.
=> Fixing prefetch bugs

src/CodeGen_Internal.cpp
Using Large is breaking many downstream users; propose reverting to unbreak things while we figure out the proper way to enable Large model for the users that need it.
=> Proposal: Revert https://github.com/halide/Halide/pull/3008

test/correctness/prefetch.cpp
Fixed bug in the prefetch test. The stride size for Hexagon should be different from other targets. Also, simplified the test so the prefetch extent size is always one for all architectures.
=> Fix bug in prefetch test

src/runtime/HalideBuffer.h
Buffer(buffer_t) and Buffer(halide_buffer_t) should be marked 'explicit' to avoid quiet auto-conversion; since these can fail with a runtime error if the argument's size/type is a mismatch with the Buffer<> static type declaration, this can quietly inject runtime failures when converting code to use Buffer<>.
=> Mark some Halider::Buffer() ctors explicit

util/HalideTraceViz.cpp
I get build errors on lines 820 and 821 of HalideTraceViz.cpp, pertaining to the loss of `const` qualifiers during the casts on [the relevant lines](https://github.com/halide/Halide/blob/6d246d9f6c0ab6e9b27a80d98452de96cc752a39/util/HalideTraceViz.cpp#L820-L821):
This change preserves the const-ness from the function’s parameters – making these pointers `const` should not have any effect on the functions’ operation as they are only read from and not written to.
[These additions](https://github.com/halide/Halide/pull/2901/files#diff-c331568fea1d179a7f31a0d643a48c8bR804) were part of [a recent overhaul of HalideTraceViz.cpp](https://github.com/halide/Halide/pull/2901).
=> Preserve const-ness when casting pointers in HalideTraceViz.cpp

src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
Convenience, a lot of downstream usage could use this more simply where the overhead of temporary-vector-construction isn't important.
(Tempted to also add variants that elide the pointer and do the allocate() call implicitly, but we already have sooooo many ctors I'm gonna hold off for now.)
=> Add a vector<halide_dimension_t> ctor to Buffer

util/HalideTraceViz.cpp
GCC 5.4.0, Ubuntu 16.04
```
Halide/util/HalideTraceViz.cpp:401:27: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
if (current_dimension == dims.size()) {
^
Halide/util/HalideTraceViz.cpp: In static member function ‘static void {anonymous}::Surface::composite_one(const uint32_t*, const uint32_t*, uint32_t*)’:
Halide/util/HalideTraceViz.cpp:820:36: error: cast from type ‘const uint32_t* {aka const unsigned int*}’ to type ‘uint8_t* {aka unsigned char*}’ casts away qualifiers [-Werror=cast-qual]
uint8_t *a = (uint8_t*)under;
^
Halide/util/HalideTraceViz.cpp:821:36: error: cast from type ‘const uint32_t* {aka const unsigned int*}’ to type ‘uint8_t* {aka unsigned char*}’ casts away qualifiers [-Werror=cast-qual]
uint8_t *b = (uint8_t*)over;
^ …
```
=> Fix some compiler errors

src/AutoSchedule.cpp
On line 2583, the entry is pair<string, int>, but it gets pushed into a vector of pair<string, bool>.
The implicit conversion won't be caught by compiler.
On the other hand, using bool here is correct if there are only two variables, since bool can at least hold two different values.
=> Fix the type of an index variable

python_bindings/Makefile, python_bindings/correctness/user_context_generator.cpp, python_bindings/correctness/user_context_test.py, src/PythonExtensionGen.cpp
This adds support for the implicit `__user_context` argument that gets added by Halide if "user_context" appears in target_features.
Since this adds a second handle type, we can now also add some testing for the legacy_buffer_wrappers disambiguation code, so do that, too.
=> Support user_context in Python extensions

src/runtime/printer.h
Having to protect against them is a hassle and I can't think of any case where the performance hit is worth worrying about.
=> Protect against NULL strings in printer as these occur in debugging.

src/Generator.cpp, src/Generator.h, test/generator/metadata_tester_aottest.cpp, test/generator/metadata_tester_generator.cpp, test/generator/stubtest_aottest.cpp, test/generator/stubtest_generator.cpp, test/generator/stubuser_aottest.cpp, test/generator/stubuser_generator.cpp
For AOT, this produces an output buffer for each tuple element.
=> Allow declaring Output<Buffer<>> with tuples (Issue #2980)

src/CodeGen_OpenGLCompute_Dev.cpp, src/CodeGen_OpenGL_Dev.cpp, src/Pipeline.h
Previously this resulted in a "BAD ID" being generated.
Unrelated tab fix.
=> Fix cast that does not result in a type change in OpenGL Compute backend.

src/AutoSchedule.cpp
Added call to get_pipeline() to the str version since auto-sched is mostly called on a Generator. Fixed bugs in stage indexing when declaring the RVars used. (Fix bugs in #2824)
=> Fix bugs in auto-scheduler string generator

src/CodeGen_D3D12Compute_Dev.cpp, src/LLVM_Runtime_Linker.cpp
- avoid the use of fallthru-without-break in CodeGen_D3D12Compute_Dev.cpp (some compiler settings assume this is an error, and the conventional equivalent is fine here)
- allow runtime linker to compile when WITH_D3D12 is not defined
=> Fix D3D12 issues

test/correctness/cascaded_filters.cpp
The cascaded filters test is designed to be a canary for compile-time issues. That's great and all, but currently it spends two thirds of its ~1.5min runtime inside llvm, which is not particularly helpful for us. This PR reduces the runtime to 12s by using fewer stages.
If we have code in the future that causes a combinatorial blowup of some sort, this test should still catch it.
=> Speed up cascaded filters test

Makefile
Make test_correctness output only a . character for successful tests. Makes it easier to find failures when running at -j:
```
$ make test_correctness -j
...........................................................................................................................................................................................................................................................
FAILED TEST: chunk
Defining function...
Realizing function...
Success!
Makefile:1502: recipe for target 'quiet_correctness_chunk' failed
make: *** [quiet_correctness_chunk] Error 1
make: *** Waiting for unfinished jobs....
...............
```
I've found myself running a -j4 on an 80-thread machine just so I can find failures more easily, which is ridiculous.
=> only report failures in test_correctness

src/LowerWarpShuffles.cpp, src/UnifyDuplicateLets.cpp, test/correctness/register_shuffle.cpp
There was a combinatorial explosion caused by an unconditional substitution of gpu lane variables.
=> Fix some pathological behavior in warp shuffles

src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
- augment copy() to allow copying-to-a-different-type
- add nonstatic variant of make_with_shape_of()
- add reset()
=> Add some HalideBuffer convenience methods (Issue #3113)

src/OutputImageParam.h
Coverity (semi-rightly) complains that `kind` is not initialized by this constructor.  Setting it to the kind that is used for the default `Argument` constructor seems.
=> Appease Coverity

Makefile, src/CMakeLists.txt
We don't want c++11, as we don't want static locals to get thread-sync helper code (which c++11 mandates); previously, we didn't specify any version, which left us at the mercy of the system compiler (which might have defaulted to c++11). Choosing gnu++98 is arbitrary but gives us a predictable baseline across common build environments.
=> Explicitly specify -std=gnu++98 for runtime .cpp building

src/CodeGen_LLVM.cpp
LLVM circa v3.2 or so had a bug wherein complex pipeline would compile extremely slowly, so a workaround was inserted; I can't replicate this as of LLVM5 or later (which is all we are supporting now), so let's consider backing out this workaround.
=> Remove special-case for int32 from CodeGen_LLVM::visit(const Select *op)

python_bindings/src/PyTarget.cpp, src/Target.cpp, src/Target.h
Not at all important, but some of these methods have grown pretty long over the years.
=> Hygiene: move nontrivial Target method bodies into .cpp file

src/CodeGen_ARM.cpp, src/CodeGen_GPU_Host.cpp, src/CodeGen_LLVM.cpp
C++11 doesn't guarantee that function arguments are evaluated in a particular order, thus calls of the form `builder->CreateFoo(codegen(a), codegen(b))` might generate LLVM IR with either a-then-b or b-then-a; at best, this makes comparing IR between compilers a nuisance; at worst, it can trigger subtle bugs and make them harder to find (see https://github.com/halide/Halide/issues/3203). This PR looks for all calls that evalutate codegen() more than once as a function arg and rearranges code to use temporaries to ensure a well-defined order.
(Note that a few with only a single call to codegen() were also pulled into temporaries where I thought it improved clarity or helped forestall reinsertion of the bad code pattern by future edits.)
=> Ensure calls to codegen() are well-ordered

src/CodeGen_ARM.cpp, src/CodeGen_GPU_Host.cpp, src/CodeGen_LLVM.cpp
Reverts halide/Halide#3212; we don't want it to land until Issue #3203 is resolved
=> Revert "Ensure calls to codegen() are well-ordered"

src/Scope.h
Adds a constructor that allows to skip binding the name, which is
already present for other types, but not in the specialization for
void.
=> Sync ScopedBinding<void> to the main template.

src/AutoSchedule.cpp
Fixing bug in `inline_unbounded`. The old logic failed to take into account the case where an output is calling the unbounded function. The unbounded function should also check uses by output, and should inline itself within the output instead of skipping it.
=> Fix inlining unbounded functions

test/generator/acquire_release_aottest.cpp
In `test/generator/acquire_release_aottest.cpp`, there are two functions:
1 - `halide_acquire_cuda_context(void *user_context, CUcontext *ctx)`
2 - `halide_release_cuda_context(void *user_context)`
I believe the purpose of these functions is to overwrite the behavior of functions with the same identifier defined in `src/runtime/cuda.cpp`. However, the functions in `cuda.cpp` differ in function name and arguments:
1 - `halide_cuda_acquire_context(void *user_context, CUcontext *ctx, bool create = true)`
2 - `halide_cuda_release_context(void *user_context)`
The problem should be fixed simply by changing the functions name and arguments in `acquire_release_aottest.cpp` to match those defined in `cuda.cpp`.
=> Incorrect acquire_context and release_context function names in test script

Makefile, src/CMakeLists.txt, src/LLVM_Runtime_Linker.cpp, src/runtime/alignment_64.cpp
The comment in LLVM_Runtime_Linker.cpp explains the rationale. I'm open to discussion on trying to somehow dynamically decide the alignment size for x86, but chose to start with the simple reliable solution to prevent AVX 512 from crashing.
On my AVX 512 system, correctness_vectorized_reduction_bug crashes more than half the time without this fix. (And doesn't in 10 or 15 trials with the fix.)
=> Move x86 to 64-byte alignment because of AVX-512.

src/AutoSchedule.cpp, test/auto_schedule/unused_func.cpp
For cases, when it can be statically proven that a function will never be accessed, the pipeline bound of that function computed by the auto-scheduler will be empty. This will throw assertion errors, since the auto-scheduler assumes that each function within the environment should have a pipeline bound.  To fix this problem, during Partitioner creation, if it encounters function with no existing pipeline bounds, it will ignore the function since the function doesn't effect the grouping decision.
=> Ignore function with empty pipeline bounds when creating partitioner

src/Func.cpp
proof if it is not needed for a particular reordering. The proof is
somewhat expensive and also results in possibly infinite loops on some
pieces of code so running it all the time is problematic.
=> Change RVar reordering code to not do associativity/commutativity

src/SkipStages.cpp, test/correctness/skip_stages.cpp
When determining whether it's safe to skip producing a func, consider
stores to non-local buffers of other funcs inside the Producer stage.
The predicate for skipping the computation must imply that conditions
around those stores are false.
=> Don't skip stages that produce values of some other func.

src/CodeGen_X86.cpp, src/runtime/x86.ll, src/runtime/x86_avx2.ll, test/correctness/simd_op_check.cpp
Needed to work properly with https://reviews.llvm.org/D46179#1211902; unfortunately this patch is (still) broken by https://bugs.llvm.org/show_bug.cgi?id=38691, and probably shouldn't land until that is resolved. Posting here as a PR to capture the work-in-progress, but not really ready to review yet.
=> Add LL helpers for paddus/psubus on LLVM8.0+

src/runtime/HalideBuffer.h
It should not be legal to call copy_from() on a Buffer with a const value type, but (thanks to explicit casting in the implementation which subverts the usual checks), it is. Added a static_cast() to prevent this.
Also, a drive-by fix to make is_bounds_query() a const method.
=> Buffer<const T>::copy_from() should be illegal

src/runtime/HalideBuffer.h
Per discussion in https://github.com/halide/Halide/pull/3253, add an alias() method as syntactic sugar to make a shallow Buffer copy. (Not sure if ready to land or not; putting it out for reference.)
=> Add Buffer<>::alias()

src/runtime/HalideBuffer.h
This is just syntactic sugar for `as<const T>()`, for the case of having a Buffer<T>& (or Buffer<T>*) and needing the const variation; it avoid needing to recapitulate the type.
(Looks likely to be used commonly enough in my use case to be worthwhile, but if there is pushback as too-much-sugar, LMK.)
Also, drive-by addition of HALIDE_ALWAYS_INLINE.
=> Add Buffer::as_const()

src/Buffer.h, src/runtime/HalideBuffer.h, test/correctness/halide_buffer.cpp
This allows for somewhat easier initializing of `Buffer<const T>` via use of fill(), for_each_value(), etc while minimizing the use of named temporaries.
(Related: would it make sense to add a reference-to-self as a final argument to the callback for `for_each_element`?)
=> Buffer::fill() and similar should return ref-to-self

test/correctness/simd_op_check.cpp
Underlying bug in LLVM fixed in trunk.
Note that pcmp is still disabled due to related bug which is not yet fixed.
=> Re-enable addus/subus in simd_op_check
