halide/Halide

src/SpecializeBranchedLoops.cpp

When the branching limit was hit we were not always exiting gracefully from the branching and in certain cases not generating an equivalent stmt. This PR should fix this issue.

Fixed a bug in specialize_branched_loops 

---

src/FuseGPUThreadLoops.cpp
src/IROperator.cpp
src/IROperator.h
src/Lower.cpp
src/RemoveUndef.cpp
src/Simplify.cpp
test/correctness/branch_visitors.cpp
test/correctness/gpu_thread_barrier.cpp

Fewer redundant thread barriers

---

src/CodeGen_C.cpp
test/correctness/math.cpp
test/correctness/vector_math.cpp

absd support in C backend, more tests of absd

---

src/Profiling.cpp
util/HalideProf.cpp

This PR adds two simple options into profiler:
1) Possibility to set a maximum loop level for profiling (through HL_PROFILE_LOOP_LEVEL env. variable)
2) Option to accumulate statistics over more than one run.

Some additional options for profiler

---

src/Bounds.cpp
src/BranchVisitors.cpp
src/LinearSolve.h
src/SpecializeBranchedLoops.cpp

This PR fixes issue #645. Basic changes revolve around better simplification of min/max and inequality exprs.

Specialize branched loops bug fixes

---

apps/linear_algebra/Makefile
apps/linear_algebra/benchmarks/cblas_benchmarks.cpp
apps/linear_algebra/benchmarks/eigen_benchmarks.cpp
apps/linear_algebra/benchmarks/halide_benchmarks.cpp
apps/linear_algebra/benchmarks/macros.h
apps/linear_algebra/src/blas_l3_generators.cpp
apps/linear_algebra/src/halide_blas.h

With this change we beat Eigen by a substantial amount for large
matrices (>2x on my machine). transA is the fast one (for us and for
eigen)
@kree-colemcalughlin PTAL

Modified gemm, including transposed versions

---

tutorial/lesson_05_scheduling_1.cpp

Clean up outdated comment.
trace_stores() handles vectorized stores pretty nicely.

Removed reference to long-gone snoopx4 from lesson05 comment.

---

src/CodeGen.cpp
src/CodeGen_C.cpp
src/Func.cpp
src/JITModule.cpp
src/JITModule.h
test/generator/argvcall_aottest.cpp
test/generator/argvcall_generator.cpp
test/generator/example_aottest.cpp
test/generator/user_context_aottest.cpp

Add to example_aottest and user_context_aottest. (Issue #667)

Add tests for the _jit_wrapper entry point

---

src/Bounds.cpp
src/BoundsInference.cpp
src/CodeGen.cpp
src/CodeGen_C.cpp
src/CodeGen_GPU_Host.cpp
src/CodeGen_OpenCL_Dev.cpp
src/CodeGen_OpenGL_Dev.cpp
src/Expr.h
src/Func.cpp
src/Func.h
src/Function.cpp
src/FuseGPUThreadLoops.cpp
src/IR.h
src/IRPrinter.cpp
src/IRPrinter.h
src/InjectOpenGLIntrinsics.cpp
src/Inline.cpp
src/Lower.cpp
src/Profiling.cpp
src/RemoveTrivialForLoops.cpp
src/Schedule.h
src/SkipStages.cpp
src/SlidingWindow.cpp
src/SpecializeBranchedLoops.cpp
src/StmtToHtml.cpp
src/StorageFolding.cpp
src/UnrollLoops.cpp
src/VaryingAttributes.cpp
src/VectorizeLoops.cpp
test/correctness/branch_visitors.cpp

Required extracting ForType out of For
This seems OK, because ForType also applies to parts of a schedule. It's not just for For nodes.

Move For into IR.h

---

src/CodeGen_LLVM.cpp
src/CodeGen_PTX_Dev.cpp
src/LLVM_Runtime_Linker.cpp

Link to LLVM change: http://llvm.org/viewvc/llvm-project?view=revision&revision=231270

Fix build breakage caused by change r231270 in LLVM trunk.

---

src/SpecializeBranchedLoops.cpp
test/correctness/specialize_branched_loops.cpp

There is a little used code path where branches are merged recursively, in which the branch points were not being computed correctly.

Fixed a small but important bug in specialize_branched_loops. 

---

src/Argument.h
src/Buffer.cpp
src/CodeGen_C.cpp
src/Func.cpp
src/Generator.cpp
src/Param.cpp
src/Param.h
test/correctness/simd_op_check.cpp
test/generator/paramtest_jittest.cpp

(revised version of PR#695, offering for consideration now that Modules
have landed)

Argument should distinguish Input and Output Buffers

---

Makefile
src/Argument.h
src/CMakeLists.txt
src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/LLVM_Runtime_Linker.cpp
src/runtime/HalideRuntime.h
src/runtime/metadata.cpp
test/generator/metadata_tester_aottest.cpp
test/generator/metadata_tester_generator.cpp

Not sure if this is ready to land as-is (look for some TODO issues),
but take a look-see to see if this looks like the right direction.

Define and emit filter metadata for AOT (Issue #664)

---

src/Simplify.cpp
src/SlidingWindow.cpp
src/StorageFolding.cpp
test/correctness/storage_folding.cpp

Partially addresses issue #738

Storage folding improvements

---

tutorial/lesson_07_multi_stage_pipelines.cpp
tutorial/lesson_08_scheduling_2.cpp
tutorial/lesson_09_update_definitions.cpp
tutorial/lesson_10_aot_compilation_generate.cpp
tutorial/lesson_11_cross_compilation.cpp
tutorial/lesson_12_using_the_gpu.cpp

tutorial lessons missing compiler flag std causing compile errors

fix tutorial lesson 7 to 12 missing compiler flag std

---

apps/HelloAndroid/build.sh
apps/HelloAndroidGL/build.sh

We currently require android-17; allowing newer versions would be nice

Allow custom android target versions

---

src/runtime/opengl.cpp

GL_LUMINANCE and GL_LUMINANCE_ALPHA aren't color-renderable in ES2, period, thus can't be read back via ReadPixels, thus are nearly useless to us. GL_RED and GL_RG are technically optional in ES2 (required in ES3), but as a practical matter, they are supported on pretty much every recent device (iOS: everything >= iPhone 4s; Android: everything >= 4.3 plus various older devices). This is definitely suboptimal; the only real alternative would be to implement these as GL_RGB or GL_RGBA, ignoring the extra channels.
Also, minor drive-by formatting and unused-code cleanups.

Require EXT_texture_rg for ES2 devices using <=2 channels.

---

src/AddImageChecks.cpp
src/BoundsInference.cpp
src/CSE.cpp
src/CodeGen_LLVM.cpp
src/CodeGen_Renderscript_Dev.cpp
src/DebugToFile.cpp
src/Func.cpp
src/Function.cpp
src/InjectImageIntrinsics.cpp
src/Introspection.h
src/Memoization.cpp
src/RDom.cpp
src/ScheduleFunctions.cpp
src/SlidingWindow.cpp
src/StorageFlattening.cpp
src/Target.cpp
src/Tracing.cpp
src/Util.cpp
src/Util.h
src/Var.cpp
src/VectorizeLoops.cpp
test/correctness/cascaded_filters.cpp
test/correctness/introspection.cpp

Another C++11 PR. This one's simpler.

Replace int_to_string with std::to_string

---

src/Func.h

Flip FuncRefExpr += and -= documentation

---

src/Simplify.cpp

Fix simplification of blocks/ifs when the second if statement does not have an else case.

Fix simplification of blocks/ifs

---

.gitignore
CMakeLists.txt
Doxyfile
HalideGenerator.cmake
Makefile
README.md
apps/CMakeLists.txt
src/CMakeLists.txt
test/CMakeLists.txt
test/scripts/distrib_windows.ps1
tutorial/CMakeLists.txt
tutorial/clock.h
tutorial/lesson_05_scheduling_1.cpp
tutorial/lesson_13_tuples.cpp

Revert "CMake build system fixes"

---

.gitignore
CMakeLists.txt
Doxyfile.in
Makefile

These are modified commits that were originally part of an older PR (#825) that was rejected.

CMake Doxygen support

---

Makefile
src/Introspection.cpp
src/MainPage.h
tutorial/lesson_15_generators.cpp
tutorial/lesson_15_generators_usage.sh

A tutorial for generators.  One cpp file containing a pair of generators, and a shell script that tests the resulting object files and demonstrates a bunch of ways to use generators on the command line. Integrating it into a build system is left as an exercise for the reader.
Also contains a minor introspection fix.

Generators tutorial

---

src/Bounds.cpp

Deeply nested let expressions were causing problems in the same way let
statements used to because we were effectively substituting them in. The
fix was similar.

Fix exponential behavior in bounds inference

---

python_bindings/python/Target.cpp

This file was out of sync with the C++ Features. Just added Metal. Verified to work locally.

Update Target.cpp with Apple's Metal feature

---

apps/HelloAndroid/jni/halide.cpp
apps/HelloAndroid/jni/native.cpp
apps/HelloAndroid/src/com/example/hellohalide/CameraPreview.java
apps/HelloAndroidCamera2/jni/AndroidBufferUtilities.cpp
apps/HelloAndroidCamera2/jni/YuvBufferT.cpp
apps/HelloAndroidCamera2/jni/YuvBufferT.h
apps/HelloAndroidCamera2/jni/deinterleave_generator.cpp
apps/HelloAndroidCamera2/jni/edge_detect_generator.cpp
apps/HelloAndroidCamera2/src/com/example/helloandroidcamera2/AndroidBufferUtilities.java
apps/HelloAndroidCamera2/src/com/example/helloandroidcamera2/Camera2BasicFragment.java
apps/HelloAndroidCamera2/src/com/example/helloandroidcamera2/HalideFilters.java
apps/HelloAndroidCamera2/src/com/example/helloandroidcamera2/HalideYuvBufferT.java

Fix android samples for nexus 5x

---

src/LLVM_Runtime_Linker.cpp

http://reviews.llvm.org/rL254449 is the change.

Accomodate Linker::LinkModules llvm api change in trunk.

---

Makefile
tutorial/figures/generate_output_snippets.sh
tutorial/lesson_16_rgb_generate.cpp
tutorial/lesson_16_rgb_generator.cpp
tutorial/lesson_16_rgb_run.cpp

This tutorial covers the ways of handling RGB images, and uses it as an entry to stride constraints and specialization. Comments welcome.

Add tutorial on RGB images, constraints, specialization

---

src/Generator.h

at least one thing.
Going through a PR here to take advantage of the continuous integration testing. Will likely merge later if tests pass and no one objects.

Remove include of <algorithm> as it appears to not be needed and breaks

---

src/Generator.h

Revert "Remove include of <algorithm> as it appears to not be needed and breaks"

---

src/runtime/cuda.cpp
src/runtime/opencl.cpp

We used to just take the last thing in the list, but I've found that
different driver versions order the list differently.

Autoselect GPU device by core count

---

apps/camera_pipe/Makefile
apps/camera_pipe/fcam/Demosaic.cpp
apps/camera_pipe/fcam/Demosaic.h
apps/camera_pipe/fcam/Demosaic_ARM.cpp
apps/camera_pipe/fcam/Demosaic_ARM.h
apps/camera_pipe/process.cpp

Made a quick pass to fix up the camera pipe:
- Removed dead code
- Fixed reference code to write to the output image
- Used 10 bit instead of 12 bit LUT
- Use different output buffers for each reference result, to avoid being tricked into believing the output is valid.
It needs more work, but this is just to get things working again.

Camera pipe fixes

---

src/CodeGen_LLVM.cpp
src/Deinterleave.cpp
src/Expr.h
src/FastIntegerDivide.cpp
src/Function.cpp
src/IR.cpp
src/IROperator.h
src/IntrusivePtr.h
src/JITModule.cpp
src/Memoization.cpp
src/Schedule.cpp
src/Scope.h
src/Util.cpp
test/correctness/thread_safety.cpp

I believe these are the changes required to make the whole compiler thread-safe. Unfortunately it comes with a 5% slowdown (in compile times) due to the atomic increment/decrement in the shared pointer.
Is a thread-safe compiler worth a 5% slowdown?

Attempt to make the compiler thread-safe.

---

python_bindings/CMakeLists.txt

Fix bugs in python_bindings CMakeLists.txt

---

src/CodeGen_Hexagon.cpp

I noticed that sequences like this:
v2 = vcombine(v0, v1)
v3 = lo(v2)
v4 = hi(v2)
Were not getting optimized, so I manually optimized this in concat_vectors/slice_vector. In particular, I noticed that in the correctness_param test, it was generating this sequence as part of a broadcast:
v1 = vcombine(v0, v0)
v2 = lo(v1)
v3 = hi(v1)
Instead of simply using v0. @pranavb-ca please take a look and decide if we should use this change or not.

Optimize redundant vcombine/lo/hi sequences

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check.cpp

Add patterns for vround. Also, rename DeinterleaveOperands to DeinterleaveOps. @pranavb-ca please take a look.

Hexagon vround

---

src/CodeGen_Hexagon.cpp
test/correctness/bit_counting.cpp
test/correctness/simd_op_check.cpp

This PR adds support for the HVX bit counting intrinsics. @pranavb-ca please take a look.

Add vectorized bit counting to Hexagon

---

src/EliminateBoolVectors.cpp
test/correctness/logical.cpp

This PR fixes a bug where vectorized conditions with let expressions don't get properly converted to integer vectors.

Eliminate bool vectors lets

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check.cpp

Implements shift and adds in Hexagon, and also optimizes narrowing casts for widening and non-widening pipelines. @pranavb-ca please take a look.

[Hexagon] Implement shift-accumulates

---

src/HexagonOptimize.cpp
src/runtime/hvx_128.ll
src/runtime/hvx_64.ll
test/correctness/simd_op_check.cpp
test/hexagon/apps/conv3x3a32/Makefile
test/hexagon/apps/conv3x3a32/conv3x3a32.cpp

@dsharletg: Please take a look.

Fix conv3x3a32 hexagon

---

src/Target.h
test/hexagon/apps/conv3x3a16/conv3x3a16.cpp
test/hexagon/apps/dilate3x3/dilate3x3.cpp
test/hexagon/apps/gaussian3x3_update_functions/gaussian3x3.cpp
test/hexagon/apps/gaussian5x5/gaussian5x5.cpp
test/hexagon/apps/histogram/histogram.cpp
test/hexagon/apps/median/median.cpp
test/hexagon/apps/sobel/sobel.cpp

@dsharletg : Straight-forward merge?

Use set_host_alignment and remove cgoption infrastructure

---

src/Pipeline.cpp
src/Pipeline.h

Add 'const' to Pipeline::outputs() signature

Const sigs

---

src/Func.h

Preparation for enabling serialization of scheduled pipelines.

Add 'get_schedule() const' to Stage class.

---

test/correctness/median3x3.cpp

@dsharletg : Please merge if ok.

Add median3x3 filter as a correctness test.

---

apps/HelloHexagon/Makefile
apps/HelloHexagon/pipeline.cpp
apps/HelloHexagon/process.cpp

Add an example app using Hexagon, which performs a 5x5 Gaussian blur.
You can run this with the command:
ANDROID_NDK_HOME=path_to_android_ndk make run-arm-64-android

[Hexagon] Add HelloHexagon example app.

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check.cpp

Add pattern for this instruction, useful for approximating log2(abs(x))

[Hexagon] Add patterns for vnormamt.

---

src/HexagonOffload.cpp

Works around the issue of hexagon-clang explicitly turning off hvx_128 byyte mode, which prevents us from enabeling it within bitcode.

Add -mhvx-double to invocaiton of clang for 128 byte mode compiles

---

src/CodeGen_Hexagon.cpp

@pranavb-ca @ronlieb @dpalermo

[Hexagon] Fix vlut for HVX 128

---

src/Buffer.cpp
src/CSE.cpp
src/Expr.h
src/Function.cpp
src/IREquality.cpp
src/IREquality.h
src/IRVisitor.cpp
src/IntrusivePtr.h
src/JITModule.cpp
src/Module.cpp
src/Parameter.cpp
src/Pipeline.cpp
src/Reduction.cpp
src/Schedule.cpp

The main effect is to replace contents.ptr-> with contents-> in lots of places.
Opinions?

Make the IntrusivePtr interface more similar to std::shared_ptr

---

apps/camera_pipe/Makefile

rev2, minus the libraries which were inadvertently in a previous branch.

Parameterize camera_pipe number of iterations

---

src/LLVM_Output.cpp
src/LLVM_Output.h

This will allow upcoming StaticLibrary work to be done more seamlessly.

Convert LLVM_Output to expose streams rather than files

---

src/EliminateBoolVectors.cpp
src/EliminateBoolVectors.h
src/ModulusRemainder.cpp
src/ModulusRemainder.h
src/PartitionLoops.cpp
src/Util.h

This PR adds a few small random helper functions that can be useful...

Small helper function refactoring

---

Makefile
src/CMakeLists.txt
src/LLVM_Runtime_Linker.cpp
src/runtime/HalideRuntime.h
src/runtime/android_tempfile.cpp
src/runtime/posix_tempfile.cpp
src/runtime/runtime_api.cpp
src/runtime/windows_tempfile.cpp

This will be useful/necessary for the hexagon2 branch; it’s being offered for separate review here to reduce review noise

Add halide_create_temp_file runtime function

---

src/runtime/hexagon_host.cpp

@steven-johnson please take a look

[Hexagon] Use halide_create_temp_file instead of trial and error

---

src/LoopCarry.cpp

[Hexagon] Fix loop carry type

---

src/runtime/hexagon_remote/Makefile

One less dependency... @steven-johnson please take a look.

[Hexagon] Use NDK from Hexagon SDK

---

src/LLVM_Output.cpp
src/ParallelRVar.cpp
src/RemoveTrivialForLoops.cpp
src/RemoveTrivialForLoops.h
src/ScheduleFunctions.cpp

This pulls in a few small changes from the Hexagon branch that should be pretty harmless. Some of these were a source of recent merge conflicts.

A few small changes from the Hexagon branch.

---

README.md

Initial additions for hexagon target added to README.md

Update README.md for Hexagon target

---

Makefile
src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
test/CMakeLists.txt
test/generator/multitarget_aottest.cpp

Add C++ mangling support for multitarget

---

src/Simplify.cpp

Implemented the same way as those for log_f32 and exp_f32 in Simplify.cpp.

Constant propagations across pow_f32 and sqrt_f32

---

src/Profiling.cpp
src/runtime/HalideRuntime.h
src/runtime/profiler.cpp
src/runtime/runtime_internal.h
test/generator/memory_profiler_mandelbrot_aottest.cpp

by tracking allocation sizes as uint64
@psuriana please take a look

Fix overflow in the memory profiler

---

src/runtime/hexagon_host.cpp

This PR changes the hexagon device allocations to just use halide_malloc if the allocation is not at least one page in size. FastRPC can probably do better than just mapping all the pages, and allocating a whole page for a tiny allocation is wasteful.

Don't use ion_alloc for small buffers

---

src/Expr.h
src/IR.cpp

Revert "Make type_info not depend on addresses of template instantiations"

---

src/runtime/HalideRuntimeHexagonHost.h
src/runtime/hexagon_host.cpp

This adds a function that determines if Hexagon is available for use.

Add halide_is_hexagon_available

---

src/LLVM_Output.cpp

@steven-johnson LLVM changed this API. This compiles but I'm not sure it is right.

Track LLVM API change. Not sure if this is the right way to do this.

---

Makefile

i noticed llvm moved to 40 from 39, this weemed to work for me.

Add clang 40 to Makefile

---

src/Func.cpp
src/Func.h
test/correctness/implicit_args_tests.cpp
test/error/implicit_args.cpp

Reopen #1396 since it was merged into func_ref_cleanup instead of master

Bug fixes for implicit vars

---

src/Simplify.cpp

Add more simplification rules for min/max clamp, like in the following:
```
min(max(min(x, 4), -4), 4) -> max(min(x, 4), -4)
max(min(max(min(x, 4), -4), 4), -4) -> max(min(x, 4), -4)
min(max(min(x, 4), -4) + 1, 5) -> max(min(x, 4), -4) + 1
max(min(max(min(x, 4), -4) + 1, 4), -4) -> min(max(min(x, 4), -4) + 1, 4)
```
It also attempts to re-associate ternary min/max of broadcasts, like in the following:
```
min(min(x, broadcast(y, n)), broadcast(z, n))) -> min(x, broadcast(min(y, z), n))
max(max(x, broadcast(y, n)), broadcast(z, n))) -> max(x, broadcast(max(y, z), n))
max(max(broadcast(x, n), y), broadcast(z, n))) -> max(y, broadcast(max(x, z), n))
```
This PR also changes the behavior of `const_int_bounds` for int type less than 32 bits. Instead of bailing out early, it will attempt to …

Add new simplification rules for chain of min/max

---

src/CodeGen_ARM.cpp
test/correctness/simd_op_check.cpp

and some more shift patterns, when the shift amount is not known at
compile time.

Add support for vqrdmulh

---

python_bindings/doc/index.rst
python_bindings/python/Func_Ref.cpp
python_bindings/python/Tuple.cpp
python_bindings/tutorial/lesson_13_tuples.py
src/Func.h

Python binding for FuncTupleElementRef

Python binding for FuncTupleElementRef

---

src/Generator.cpp
src/Generator.h

— remove generator_name(); it’s clunky and hasn’t been used in a long
time.
— generator_params should be kept in a vector, not a map (the map-ness
is only needed once per instance, at initialization)
— enforce unique names across all params + generatorparams

Minor Generator cleanup

---

src/runtime/hvx_128.ll
src/runtime/hvx_64.ll
test/correctness/mul_div_mod.cpp

Add support for u32 x u32 -> u32 multiplication on Hexagon

---

src/Solve.cpp

Solver should not negate an unsigned, e.g. a - (f(x) - b) -> -f(x) + (a + b) is not legal. Instead, we will leave it as it as and since it's not possible to re-order the "x" to the left-most part, declare it as "fail".

Fix negation of unsigned bugs in solver

---

src/Simplify.cpp

Add simplification rules for:
```
min(max(x, y), x) -> x
max(min(x, y), x) -> x
```

Min max point simplify

---

src/Simplify.cpp

Revert "Add simplification rules for select(c, min(a, b), min(a, d))"

---

src/AutoSchedule.cpp
src/RegionCosts.cpp

Fix compile error Buffer -> BufferPtr

---

tools/halide_image_info.h

Fix the image info utilities to work with HalideBuffer.h

Update halide_image_info.h to use HalideBuffer.h

---

test/correctness/fuzz_simplify.cpp

C++ doesn’t guarantee that function arguments are evaluated in a
specific order, so calling rng() [or any of the random_xxx functions]
means that our expressions can vary between compilers. Pull all random
expressions out into separate statements to ensure that the sequence
for a given seed is reliably predictable across compilers.
(Naturally, this might break the behavior of existing seeds on some
compilers.)

Don't invoke rng() via func arg evaluation

---

src/BitWriter_3_2/BitcodeWriterPass.cpp
src/CodeGen_LLVM.cpp

This one has ifdefs for LLVM version 40 :-)

StringRef fix for 40

---

.gitignore
apps/fft/Makefile
apps/fft/fft_aot_test.cpp
apps/fft/main.cpp

(All intermediate product to bin/ dir, don’t use gengen.sh)
Also, driveby removal of old detritus from toplevel .gitignore

Convert apps/fft to same Generator style as other apps

---

src/runtime/HalideBuffer.h
test/correctness/halide_buffer.cpp

Also added a place to test Buffer
In general I'm adding methods to Buffer when I see these things hand-
rolled in user code multiple times.

Add Buffer::copy_from

---

src/CodeGen_Hexagon.cpp

Until we have a real fix for #1582

Add assert to avoid miscompilation

---

src/Lower.cpp
src/Lower.h
src/PrintLoopNest.cpp
src/PrintLoopNest.h

Added deep copy, wrap functions, and output compute/store root reset in PrintLoopNest.

Print loopness should deep copy

---

src/HexagonOptimize.cpp
src/Simplify.cpp

Reverts halide/Halide#1490
Tested this locally, it seems to work, let's try it again.

Revert "Revert "Lazy slice vectors""

---

src/Simplify.cpp

Bug fixed for #1601. is_zero() false doesn't necessarily mean the expr is always non-zero; need to call is_positive_const(expr) || is_negative_const(expr) instead.

Fixed bugs in EQ simplify select(c, 4, f) == 0

---

src/LLVM_Headers.h

sync up with latest llvm change

Split ReaderWrite.h into BitcodeReader.h and BitcodeWriter.h

---

src/LLVM_Runtime_Linker.cpp

Move from ErrorOr to Expected interface.

Catch up to LLVM change.

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check.cpp

This PR adds widening add & subtract instructions to the HVX backend.
@dsharletg : PTAL

Widening add sub hvx

---

apps/fft/Makefile
apps/fft/fft_aot_test.cpp

Convert fft_aot_test to use Halide::Buffer

---

Makefile
test/CMakeLists.txt
test/generator/stubtest_aottest.cpp
test/generator/stubtest_generator.cpp
test/generator/stubtest_jittest.cpp
test/generator/stubuser_generator.cpp

Add both simple and array inputs; rationalize names accordingly.

Add more variants to stubtest

---

src/CMakeLists.txt

Using macro for runtime module generation.

Refactoring src/CMakeLists.txt

---

src/runtime/HalideBuffer.h

The logic in assert_can_convert_from() is useful, and desirable to
avoid repeating outside this class; however, it’s only reliable if
assert() is not disabled at compile time, and I’d like to use it in a
context (Generator stubs) where that might be the case.
Therefore: split the main logic into Buffer::can_convert_from(),
allowing a caller to detect-and-fail as it sees fit (e.g., using
Halide’s internal_assert or user_assert).

Split Buffer::assert_can_convert_from() into two methods.

---

src/Simplify.cpp
src/UnifyDuplicateLets.cpp
test/correctness/unsafe_dedup_lets.cpp

Fix a bug where we incorrectly unify certains ifs and lets

---

src/Generator.cpp
src/Generator.h

Refactoring of some internal Generator method structure; no real impact
on functionality, just laying the groundwork for a subsequent PR with
less-confusing diffs

Generator refactoring

---

src/Generator.cpp
src/Generator.h

(More) refactoring of some internal Generator method structure; no real
impact on functionality, just laying the groundwork for a subsequent PR
with less-confusing diffs

Generator refactoring (Pt 2)

---

src/CMakeLists.txt

- setting INCLUDE_DIRS var
- Support building in a directory name with space

Further refactoring for runtime build

---

src/CMakeLists.txt

Revert "Further refactoring for runtime build"

---

Makefile
src/CMakeLists.txt
src/runtime/printer.h
test/correctness/extern_bounds_inference.cpp
test/correctness/float16_t_image_type.cpp
test/correctness/float16_t_realize_constant.cpp
test/correctness/gpu_non_contiguous_copy.cpp
test/correctness/input_larger_than_two_gigs.cpp
test/correctness/memoize.cpp
test/generator/msan_aottest.cpp
test/generator/tiled_blur_blur_generator.cpp
test/generator/user_context_aottest.cpp
test/generator/user_context_generator.cpp
tools/binary2cpp.cpp

Here are some minor changes pulled over from the new_buffer_t_v2 branch. The intent of this PR is to make that diff smaller.

A grab-bag of minor fixes from the new_buffer_t_v2 branch

---

src/CSE.cpp
src/IREquality.cpp

Was happening for null handles

Handles of different types can't be CSE'd

---

README.md

Update build instructions to include a Windows section

Better windows build instructions

---

src/Deinterleave.cpp

#1754 caused loads to stop deinterleaving. @psuriana PTAL

Fix deinterleaving of loads from #1754

---

src/Buffer.h

Remove pointless type check

---

src/CPlusPlusMangle.cpp
test/generator/cxx_mangling_define_extern_aottest.cpp
test/generator/cxx_mangling_define_extern_generator.cpp

Fixes for mangling of "void *" argument type on all platforms.

Mangling issue

---

test/correctness/vector_math.cpp

~4x wall-clock improvement on my laptop.

Speed up vector_math test by using std::async

---

test/correctness/vector_cast.cpp

~4x wall-clock improvement on my laptop.

Speed up vector_cast test by using std::async

---

src/Error.h
src/runtime/HalideBuffer.h
src/runtime/HalideRuntime.h

Also remove the #undef in HalideBuffer.h and remove
HALIDE_ERROR_ALWAYS_INLINE.

ALWAYS_INLINE -> HALIDE_ALWAYS_INLINE (#1829)

---

test/correctness/tuple_undef.cpp

This fixes the issue in which some runtime environments will make this
fail, due to differences in initial contents of empty Buffer<>s.
The behavior of undef<>() is still a bit unsatisfying, though; although
this test accurately verifies the current behavior, it seems to me that
any Expr containing undef() that ‘escapes’ to evaluation should be
illegal; i.e., it’s fine to use undef() for values that will be
overwritten in later update stages, but it should be forbidden to use
“foo + undef()” as part of an evaluated expression. The latter *is*
legal and apparently the undef() part of the expression is simply
dropped.
(Minimal fix for #1845)

Fix undefined behavior in tuple_undef

---

tutorial/lesson_15_generators_usage.sh

The current comment lists the wrong filename for calling the script

update tutorial 15 bash script comment

---

src/runtime/metal.cpp

If buf->host is set here, it should be a pointer we obtained from the
mtl_buffer we’re releasing, and thus isn’t valid any more; generic code
in halide_device_and_host_free() will pass this pointer to
halide_free() if it’s not null, which will at best be useless, or at
worst, crater in amusing ways. (Issue #1882)

halide_metal_device_free() needs to clear buf->host (Issue #1882)

---

apps/camera_pipe/camera_pipe_generator.cpp
src/IROperator.h
test/correctness/dilate3x3.cpp
test/correctness/median3x3.cpp
test/correctness/reduction_schedule.cpp

Operators are folded right.
Add lighter version of a left and right folds helpers,
where doing copies is not necessary.

Add variadic version of min/max operators.

---

apps/HelloAndroid/jni/hello_wrapper.cpp

Wasn’t compiling properly after the new_buffer_t branch landed.

Upgrade HelloAndroid to build with new halide_buffer_t code

---

apps/hexagon_benchmarks/process.h

Fix brain-dead copy paste error in hexagon_benchmarks

---

apps/hexagon_benchmarks/conv3x3_generator.cpp

Patch needed to compile conv3x3

update output_buffer -> output  usage

---

src/runtime/runtime_internal.h
src/runtime/tracing.cpp
src/runtime/write_debug_image.cpp

Revert "Use open instead of fopen in write_debug_image."

---

src/InjectHostDevBufferCopies.cpp
src/LLVM_Runtime_Linker.cpp
src/runtime/metal.cpp
test/correctness/gpu_multi_device.cpp

This test wasn't actually ever running, and was broken. I will separately enable it on the buildbots

Fix for using many gpu apis at once.

---

apps/hexagon_benchmarks/process.cpp

i missed this file needing the change , hopefully last instance.

Fix process.cpp in new hexagon_benchmark

---

tools/halide_image_io.h

Revert "save_png() writes interleaved images incorrectly"

---

apps/hexagon_matmul/process.cpp

last one, i think, sorry forgot I about this one.

Fix matmul process.cpp Halide::Tools::

---

src/Pipeline.h

Remove stale function declarations in Pipeline

---

src/runtime/write_debug_image.cpp

This bug was introduced with the halide_buffer_t changeover.

Fix debug_to_file for non-zero mins

---

src/HexagonOffload.cpp

This allows a build tool to define an env var (HL_HEXAGON_CODE_SIGNER)
to sign Hexagon code; since Hexagon code is typically embedded as data,
it’s nontrivial to extract/sign/replace the code at a higher level in
the build system.

Add hook to allowing signing of Hexagon code

---

tutorial/lesson_13_tuples.cpp

Fix tutorial on Tuples; arg_max should save index if old_max is less than value of input

---

src/CodeGen_OpenCL_Dev.cpp

. Not sure if there was something controversial here, hence the PR.

Trivial fix for issue https://github.com/halide/Halide/issues/1903

---

src/Buffer.h
test/error/forward_on_undefined_buffer.cpp

Addresses issue: https://github.com/halide/Halide/issues/1815

Add a user_assert against forwarded methods on an undefined Buffer.

---

Makefile
src/AssociativeOpsTable.cpp
src/AssociativeOpsTable.h
src/Associativity.cpp
src/Associativity.h
src/CMakeLists.txt
src/Func.cpp
src/IRMatch.h
src/IRPrinter.cpp
src/IRPrinter.h
test/correctness/rfactor.cpp
test/performance/rfactor.cpp

Made rfactor more general with LUT of associative ops and added subgraph decomposition in associativity prover.

Added LUT for associative ops and rfactor subgraph decomposition

---

src/Bounds.cpp

Get epsilon more aggressive about the bounds of narrowing casts

---

src/Definition.cpp
src/Definition.h
src/Func.cpp
src/Func.h
src/Function.cpp
src/Function.h
src/Inline.cpp
src/Schedule.cpp
src/Schedule.h
src/ScheduleFunctions.cpp
src/SimplifySpecializations.cpp
src/SlidingWindow.cpp

Split schedule into FuncSchedule and StageSchedule. FuncSchedule contains all function-specific schedule, while StageSchedule contains per-stage-specific schedule.

Split Schedule into FuncSchedule and StageSchedule

---

src/CSE.cpp

This is just a re-open of #2055. I did the pull request using the master branch of my fork, which was dumb. The only difference is the target branch.

(moved) Fixed bug in CSE: will now ignore non-pure (side-effecty) Calls.

---

Makefile

(Hygiene to make some upcoming changes cleaner)
-- Put the default case before all specializations
-- add comments on why specializations are necessary
-- remove an unnecessary specialization
-- collect includes and ldflags into vars for cleanliness

Clean generator aot makefile rules

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check.cpp

Converting widening subtracts of form i16(u8) - i16(u8) to vmpa's

Widening Subtracts of form i16(u8) - i16(u8)

---

src/CodeGen_C.cpp

Otherwise, different types can cache to the same (incompatible) value of null (e.g. void* and int32*). This is at least a partial fix for Issue #2075.
Also, drive-by improvement to prettyprinting of the struct defs we emit.

Ensure NULL struct values include typecast (Issue #2075)

---

Makefile
src/CodeGen_C.cpp
test/generator/external_code_generator.cpp

Update external_code_generator test and Makefile appropriately. Fixes Issue #2102

C++ Backend should emit C++ external-code blobs into output

---

src/EliminateBoolVectors.cpp

If a two bool vectors are used in a select() statement, they can get promoted to different-sized masks depending on how they were calculated. Widen the final types as necessary for harmony.

EliminateBoolVectors can fail on correct code

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check.cpp

This code is extremely slow for some programs. Reverting #2050 automatically is not possible.

Disable vtmpy

---

src/Simplify.cpp

Should only simplify (c1 < b * c2) into ((c1 / c2) < b) if both c1 and c2 are simple constants; otherwise, it may create cycle with the other simplification rule when b is also constant.

Fix infinite recursion bug in LT constant ramp/broadcast simplifier

---

src/Bounds.cpp

Kgnk kgnk bounds visit compare

---

src/LLVM_Runtime_Linker.cpp

This pull request fixes issue #2207

fix ios simulator generation

---

src/SlidingWindow.cpp
test/correctness/sliding_window.cpp

Support sliding where there's no dependence of the footprint on the loop var

---

src/CodeGen_C.cpp

Avoid ever returning a native vector

---

src/Target.cpp
src/Target.h
test/correctness/vector_cast.cpp

And a new Target::supports_type method which takes a DeviceAPI to give

---

src/StorageFolding.cpp

The assertions produced by storage folding when the compiler can't
statically prove safety were huge. This was mostly because they had to
be immediately inside the loop body (because they predicted the
footprint of the next loop iteration with a simple substitute, so you
can't let the loop var get hidden in any lets). Putting them there
forces them to include a copy of all the relevant letstmts that come
between them and the actual produce node.
By dynamically tracking what logical coordinates are currently
represented in the folded buffer, we can produce simpler asserts and
place them further in, immediately outside of the produce/consume nodes.
Moving the asserts further in is essential for getting storage folding
working for extern stages - they have to come after the dynamic bounds …

Dynamic tracking of folded coordinates

---

.gitignore
HalideGenerator.cmake
apps/wavelet/CMakeLists.txt

It had bit-rotted; get it working in in preparation for possible improvements to CMake generator rules.

Fix apps/wavelet for CMake

---

Makefile

Add link-static to llvm-config

---

src/runtime/cuda.cpp
src/runtime/cuda_functions.h

a cuda context.
(Hoping to get test coverage on build bots. Would be great if someone well steeped in cuda could verify this is sensible.)

Add support for putting Halide operations on a specific stream within

---

src/Elf.cpp
test/common/check_call_graphs.h
test/opengl/testing.h

Ongjunjie not use cpp14

---

src/Simplify.cpp

@psuriana ptal
A canonicalization was fighting itself. Putting it after the thing it was trying to hit post-canonicalization fixes it.

Fix simplifier loop

---

src/CodeGen_C.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_LLVM.cpp
src/IR.h
src/InjectHostDevBufferCopies.cpp
src/RegionCosts.cpp
src/RemoveDeadAllocations.cpp
src/SkipStages.cpp
src/WrapExternStages.cpp

InjectHostDevBufferCopies was not seeing buffers passed to
ExternCPlusPlus stages due to this.

Use helpers for is_extern and is_intrinsic

---

src/runtime/qurt_allocator.cpp

This PR fixes halide_malloc on 8996.

Work around issue with non-zero-initialized globals.

---

Makefile
src/runtime/write_debug_image.cpp
tools/halide_image_io.h
util/CMakeLists.txt
util/HalideTraceDump.cpp
util/HalideTraceUtils.cpp
util/HalideTraceUtils.h
util/HalideTraceViz.cpp

Picked up Sander's PR, rebased and squashed onto master to get rid of all the extraneous commits, and added support for .tmp (so that we can dump things up to 4 dimensions).

Sander vocke trace dump

---

src/StorageFlattening.cpp
test/correctness/extern_producer.cpp

Jingpu align storage

---

src/RDom.cpp
test/error/rdom_undefined.cpp

https://github.com/halide/Halide/issues/2457

RDom ctor should assert-fail for undefined inputs (rather than segfault)

---

.travis.yml
test/scripts/build_travis.sh

https://github.com/halide/Halide/issues/2195 should be fixed by this Bazel version.

Update Travis Bazel minimum version to 0.6.1, re-enable testing

---

src/CodeGen_LLVM.cpp

Also pass stderr to the stream argument so we get an indication of what was wrong. Thanks @alinas for pointing this out.

Assert the success of module/function verification

---

src/AlignLoads.cpp
src/AllocationBoundsInference.cpp
src/Associativity.cpp
src/AutoScheduleUtils.h
src/Bounds.cpp
src/BoundsInference.cpp
src/CSE.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/DebugToFile.cpp

Grab bag of conversions (split into multiple PRs for ease of review)

IRMutator->IRMutator2, Part 2

---

src/Func.cpp
src/Func.h
src/Lower.cpp
src/Lower.h
src/Pipeline.cpp
src/Pipeline.h
test/correctness/custom_lowering_pass.cpp
test/correctness/gpu_thread_barrier.cpp
test/correctness/likely.cpp
test/correctness/predicated_store_load.cpp
test/correctness/specialize.cpp
test/correctness/tuple_undef.cpp
test/opengl/varying.cpp

Convert add_custom_lower_pass() and everything that uses it

IRMutator->IRMutator2, Part 1

---

src/Definition.cpp
src/Definition.h
src/Deinterleave.cpp
src/EarlyFree.cpp
src/EliminateBoolVectors.cpp
src/Function.cpp
src/Function.h
src/FuseGPUThreadLoops.cpp
src/FuzzFloatStores.cpp
src/HexagonOffload.cpp
src/HexagonOptimize.cpp
src/Inline.cpp
src/Schedule.cpp
src/Schedule.h

Grab bag of conversions (split into multiple PRs for ease of review)

IRMutator->IRMutator2, Part 3

---

src/Simplify.cpp

Simplifier. Complicated one. Review carefully.

IRMutator->IRMutator2, Part 12 (last one)

---

src/Reduction.cpp
src/Reduction.h

IRMutator->IRMutator2, Part 13

---

Makefile
src/runtime/device_interface.cpp

It appears to be unused and unreferenced.

Remove halide_weak_device_free()

---

src/Associativity.cpp
src/AutoSchedule.cpp
src/BoundsInference.cpp
src/Closure.cpp
src/Closure.h
src/CodeGen_C.cpp
src/CodeGen_C.h
src/Deinterleave.cpp
src/DeviceArgument.cpp
src/ExprUsesVar.h
src/Function.cpp
src/InlineReductions.cpp
src/LoopCarry.cpp
src/PartitionLoops.cpp
src/RemoveUndef.cpp
src/Scope.h
src/SkipStages.cpp
src/StorageFlattening.cpp
src/Substitute.cpp

Simplifies the code, and should be a minor perf boost.

Add support for Scope<void>

---

src/Prefetch.cpp

Large speedup in lowering for all pipelines (3x for local laplacian!).
I don't see why we need to expand prefetch bounds based on *outer* lets
and loops -- we're not lifting code outside of them. box_touched at the
right scope should do the right thing for us.
Along the way I discovered we have no correctness tests for prefetch?! Eyeballing the IR, it looks right, but I have no confidence.
@dsharletg @psuriana PTAL

Remove some code in prefetch that looked unnecessary

---

python_bindings/python/Image.cpp
python_bindings/python/Param.cpp

Seems to build. Not sure how to test this.
Hopefully fixes issue https://github.com/halide/Halide/issues/2560 .

Add 64-bit integer types for python bindings.

---

src/CodeGen_Hexagon.cpp

Pushed up for Suyog, previously reviewed on pranav-ca
this push should trigger buildbots.

Suyog vlut wrk

---

src/HexagonOptimize.cpp

This is a sync of @aankit-ca's PR #2702. I updated it to use IRMutator2, and simplified it a bit.

Hexagon: Expression Rearrangements for better instruction selection #2072 updated

---

src/AutoSchedule.cpp
src/AutoScheduleUtils.cpp
src/AutoScheduleUtils.h
src/Func.cpp
src/RegionCosts.cpp

This PR fixes the segfault bugs in auto-scheduler when dealing with extern functions due to the recent refactoring of extern func.

Fix segfault bugs in extern cost

---

src/Buffer.h

(Note that these is deliberately no testcase for this; the code in soon-to-land https://github.com/halide/Halide/pull/2618 will be more than adequate for testing)

Add initializer-list forwarding for crop() and translate() methods

---

apps/HelloHexagon/Makefile
apps/hexagon_benchmarks/Makefile
apps/hexagon_matmul/Makefile

This makes the Makefiles for the apps that cross-compile slightly more consistent.

Minor refactoring of app Makefiles that cross-compile

---

src/runtime/opencl.cpp

Clang Win32 code optimizer can get confused about whether padding is needed and generate inconsistent code within the same file. Reorder fields to avoid need for padding to circumvent this. Also add a validation-check immediately after allocation to ensure things aren't broken.

Reorder struct in opencl to avoid padding.

---

python_bindings/correctness/target.py
python_bindings/src/PyExpr.cpp
python_bindings/src/PyTarget.cpp

First attempt at bringing one of th Python bindings 100% up to date, with complete tests for all binding bits.

Update Python bindings for Target

---

src/Lower.cpp

Mostly to eliminate superfluous debug output which has been annoying me for a fair while.

Attempt to elide Hexagon offload passes if they are not enabled. 

---

src/CodeGen_X86.cpp
src/runtime/x86.ll
src/runtime/x86_avx2.ll
src/runtime/x86_sse41.ll
test/correctness/simd_op_check.cpp

Reopening #2680 so it gets tested by the build bots

X86: AVX2 improvements in codegen and runtime functions (by ZviRackover)

---

src/PartitionLoops.cpp

See previous line 454. Switched all usage to ScopedValue to avoid needing manual cleanup.

in_gpu_loop wasn't being restore

---

src/runtime/HalideBuffer.h

copy-paste error; several of the changes should have been <void> rather than <T>, since remove_const must match the type.

Fix error in commit c2fd18

---

src/Func.h
src/IROperator.cpp
src/IROperator.h
src/Tuple.h
test/correctness/tuple_select.cpp

-- move to IROperator.h, next to select(), for better discoverability
-- add multiway verison of tuple_select(), to match select()
-- add test

tuple_select cleanup

---

test/performance/thread_safe_jit.cpp

Also serves as documnetation on passing parameters to JITted routines
and avoiding recompilation for each realize.
Suggestions on further comments for documentation are particularly
welcome.

Add a test per issue https://github.com/halide/Halide/issues/2731 .

---

src/Generator.cpp
src/Generator.h

Also, some drive-by de-inlining of code.

Aggressively build ParamInfo when constructing Generators

---

src/AutoSchedule.cpp

It was promoting things from int32 to int64 by digging out the value of
an IntImm
Also some drive-by cleanups

Fix incorrect type in Autoscheduler

---

src/Func.cpp
test/correctness/split_by_non_factor.cpp
test/error/split_inner_wrong_tail_strategy.cpp

See the test for an example that was computing incorrect values.

Can't use TailStrategy::RoundUp on an inner var in an update def.

---

util/HalideTraceViz.cpp

- Labels that fade in could get rendering incompletely (or not at all) depending on ordering of trace packets due to threading; move all pending labels into a list and render as we go along to resolve this
- first_draw_time and first_packet_index should have default values be -1, as zero is a legal value; this could lead to duplicate entries

Fix rendering glitches in HTV

---

src/runtime/HalideRuntimeHexagonHost.h
src/runtime/hexagon_remote/halide_remote.cpp

Ensure backward compatibility too.

Support more hvx power levels

---

apps/local_laplacian/local_laplacian_generator.cpp
tools/halide_trace_config.h
util/HalideTraceViz.cpp

(This makes some subsequent auto-layout code easier to deal with)

Convert Label::pos to be an offset from Func's position (rather than absolute)

---

src/FuseGPUThreadLoops.cpp

Also use ScopedBinding and ScopeValue helpers as appropriate

Convert ExtractRegisterAllocations to IRMutator2

---

src/runtime/synchronization_common.h

ThreadSanitzer (TSan). It is probably possible to use the weaker
version and make sure the acquire fence is hit on all paths, but a few
quick tries did not work and it hardly seems worth it anyway.

Strengthen memory ordering in word_lock per errors reports from

---

test/performance/thread_safe_jit.cpp

Fix possible signed-integer-overflow

---

Makefile
apps/support/Makefile.inc

A more correct fix for my libtinfo hack, from #2940

Better fix for missing -ltinfo

---

util/HalideTraceViz.cpp

Previously we rendered labels after every packet; this is insanely slow for some traces, and totally unnecessary, since we really only need to render the labels once per frame (just before compositing) since they are the topmost layer.

Improve HTV rendering speed

---

src/CodeGen_C.cpp

Add std::flush to Codegen_C

---

src/Pipeline.cpp

Allow realizing into Halide::Buffer with a device allocation only

---

test/correctness/for_each_element.cpp
test/correctness/halide_buffer.cpp

Fix for https://github.com/halide/Halide/issues/3102.

Add stdio.h includes per https://github.com/halide/Halide/issues/3102 .

---

src/VectorizeLoops.cpp
test/correctness/predicated_store_load.cpp

Fix predicated store to use the new computed index

---

test/correctness/predicated_store_load.cpp

Only run predicated vector LUT test on X86 since it will fail on Hexagon as it is using larger than 16-bit LUT

Only run predicated vector LUT test on X86

---

src/AlignLoads.cpp
src/CodeGen_Hexagon.cpp
src/HexagonAlignment.h
src/HexagonOptimize.cpp
src/HexagonOptimize.h
test/correctness/widening_reduction.cpp

This PR is another incarnation of a previous PR. The previous PR broke the following tests on HVX
correctness_argmax
correctness_bool_compute_root_vectorize
correctness_fuse
correctness_in_place
correctness_multi_way_select
correctness_simd_op_check
correctness_undef
This PR fixes that.

Interleave bug

---

tools/halide_image_info.h

Replace buffer_t with halide_buffer_t and other
data structure.

Update image info API's for halide_buffer_t

---

src/runtime/HalideBuffer.h
test/correctness/halide_buffer.cpp

Declare it const, then add perfect-forwarding to some helper methods; this allows us to call it on `const Buffer<T>` (which are fine to mutate if T is not const) and also `Buffer<const T>` (which are now correctly prohibited from mutating the values via nonconst reference args to the lambda).

Make Buffer::for_each_value const-correct

---

src/Func.cpp
test/correctness/reorder_rvars.cpp

Support reordering RVar if a function is associative.

---

test/correctness/simplify.cpp

The simplification rule is already implemented in this branch, so the PR only adds the test.

Add a simplify test from #3229.

---

src/runtime/hexagon_remote/sim_host.cpp

Initialize HexagonWrapper with v65 instead of v60.

---

src/CodeGen_LLVM.cpp

that size is greater than 32.
We should consider weaker alignment for various items, such as string
constants, but I didn't want to decrease alignment without discussion.

Increase embedded buffer alignment to max vector size of target if

---

src/CodeGen_C.cpp
src/CodeGen_LLVM.cpp

Note: deliberately omitting any tests for this as tests for this intrinsics are missing in general (see Issue #3301)

Add quiet_div, quiet_mod to C backend (Issue #3300)

---

tools/RunGen.h
tools/RunGenMain.cpp

- Add utilities to calculate elements_out and bytes_out (in addition to pixels_out)
- Add an experimental feature to try to guess reasonable values for unspecified inputs. This needs more work to be generally useful (and the problem may be intractable), but is interesting enough that I'd like to check it in for further experimentation.

Add RunGen features

---

Makefile
halide.cmake
python_bindings/src/PyEnums.cpp
src/CMakeLists.txt
src/IRPrinter.cpp
src/RemoveExternLoops.cpp
src/Target.cpp

- Keep the list in Target.cpp in order, instead of inserting randomly
- add the new feature elsewhere, as directed in Target.cpp

Fix hexagon_dma enums

---

src/Bounds.cpp

Allocation bounds inference uses a crappy O(n^2) algorithm that repeats a bunch of pointless work redundantly for every Func. This PR is a simple partial fix. First some background:
boxes_touched gives you a map from Funcs to Boxes, telling you the domain over which each is accessed. It works from outside in, tracking the range over which each new letstmt's value could vary given the for loops in scope, and doing a lot of work to track the implications of an if stmt that constraints the range of one variable on its already-defined dependent variables. All of this work is done without knowing if those variables are even relevant, but for boxes_touched, you're finding the bounds of everything, so nearly all letstmts end up being relevant, and each letstmt may be relevant to the bounds of …

Filter down the stmt to the relevant substmts before box_touched

---

halide.cmake
python_bindings/src/PyEnums.cpp
src/runtime/hexagon_dma_pool.cpp
src/runtime/mini_hexagon_dma.h

Forgot to add embed_bitcode feature flag for Python and CMake support.

---

src/Bounds.cpp

This fixes an issue introduced via a change to reduce stack space by removing recursion in favor of a loop. Fixes an issue where async codegen can produce code that deadlocks deterministically due to bad bounds computations.

Have buffer_lets logic handle all Lets in a nested list.

---

src/Bounds.cpp

Adds support for recognizing the source argument if consider_calls is
true (computing box_required rather than box_touched) and for handling
halide_set_buffer_bounds calls wrapped around a crop.
Fixes a hang in one of the hexagon_dma tests after a proposed schedule
change.

Modify bounds inference to more generally recognize halide_buffer_copy operations.

---

src/runtime/HalideBuffer.h

This is a just convenience method for debugging with MSAN, to allow us to insert checks for memory initialization into user code.

Add Buffer::msan_check_mem_is_initialized()

---

src/Deinterleave.cpp

The Let visitor in Deinterleaver makes some bad assumptions about how the resulting variable is used. If it's used lane-wise it's correct (by far the most common case), but if it gets used inside an inner shuffle it's nonsense. This fixes the repro case in #3353

Remove buggy let visitor in Deinterleaver

---

src/BoundaryConditions.h

(I'm opening PRs for the trivial fixes in the autoscheduler branch to reduce the total diff size)

Add missing explicit include from BoundaryConditions.h

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h
src/runtime/HalideRuntime.h
test/generator/cxx_mangling_aottest.cpp
test/generator/metadata_tester_aottest.cpp
test/generator/metadata_tester_generator.cpp
tools/RunGen.h

Add auto-scheduling estimate values to metadata output

---

src/CostModelGenerator.cpp
tools/RunGen.h
tools/bench_cost_model.sh

Not sure if this is what you had in mind or not, but demonstrates putting all the values into estimates rather than command line. Includes fixes from https://github.com/halide/Halide/pull/3460 as well.

Set estimates for training in Generator

---

src/Generator.cpp

Adds a flag to gengen to ask it to dlopen something for us. Can be used to install a custom autoscheduler (by having a static constructor in the library call Pipeline::set_custom_autoscheduler). I imagine it could be used for other purposes in the future too.
Drive-by fix of line wrapping in the gengen usage message.

Add the ability for generators to load plugins

---

apps/autoscheduler/Makefile

Just some tersifying re: RunGen usage.

Minor makefile cleanup

---

src/runtime/HalideBuffer.h

assert_can_convert_from() was a complete no-op for builds that disable assertions, but there are meaningful compile-time checks that can (and should) be done even in these situations.

Improve Buffer conversion checks when assertions are disabled

---

src/VectorizeLoops.cpp
test/correctness/predicated_store_load.cpp

Temporary hack; someone needs to be assigned to investigate after the holidays.

Disable predicated store/load on x86 (Issue #3534)

---

src/Generator.h
test/generator/metadata_tester_aottest.cpp
test/generator/metadata_tester_generator.cpp

There wasn't a way to do this before. Oops.

Add a way to set estimates for Input<scalar[]>

---

src/Generator.cpp

Issue outlined in #3546 issue 1.

Fix bad stubs when generator has no inputs.

---

Makefile
src/CodeGen_LLVM.cpp
src/LLVM_Headers.h

Appaarently the change is back in trunk again.

Reapply https://github.com/halide/Halide/pull/3564

---

Makefile

Fix makefile comments on individual tests

---

test/performance/lots_of_inputs.cpp

This will help us justify future PRs.

Add test that measures how compile times scale with an increasing number of inputs

---

src/IROperator.h

Types of 32-bit float intrinsics must be a 32-bit float

---

src/Inline.cpp

Don't create unnecessary lets in Inlining

---

src/Simplify.cpp

Underlying issue fixed by #3632

Remove let stripping in can_prove

---

CMakeLists.txt
Makefile
src/CMakeLists.txt

We weren't including everything from the distrib/ folder in the tgz. Now we should be.

Fix Makefile building of halide.tgz

---

apps/camera_pipe/camera_pipe_generator.cpp
apps/camera_pipe/process.cpp

Add a reasonable GPU schedule for camera pipe.

Gpu camera pipe

---

Makefile
apps/resnet_50/Makefile
apps/resnet_50/Resnet50Generator.cpp
apps/resnet_50/load_weights.py
apps/resnet_50/process.cpp
apps/resnet_50/validate_resnet50_output.py

Add a manually scheduled resnet50 implementation to apps/resnet_50.
```
$ make benchmark_and_validate
Running Resnet50 for 10 iterations....
Execution time : 438.491ms
Class for random data of seed 123 is 783
Writing output layer to ./bin/res50gen_output.bin
python3 validate_resnet50_output.py ./bin/res50gen_output.bin 123
Success!
```

Add apps/resnet_50

---

README.md

Also fix README.md for deprecated HVX flags

---

src/Simplify.cpp

Use equality assertions for more than constants

---

src/LLVM_Runtime_Linker.cpp

See https://reviews.llvm.org/D57335

Update for LLVM DataLayout Change

---

src/Simplify_EQ.cpp

For both boolean and numeric values of x.  An attempt to address #3718 in the simplest manner possible.

Simplify x == x

---

src/Simplify_Stmts.cpp
test/correctness/simplify.cpp

Add a few missed simplifications of if stmts. Before, common statements were only pulled out of Blocks when both branches were Blocks. This PR handles the case where zero or one of the branches are a Block.

More simplification of IfThenElse stmts

---

test/correctness/math.cpp

- error output should go to stderr, not stdout
- fix nomenclature that misleadingly refers to GPU
- log all errors rather than aborting on the first one

Fixes to correctness_math

---

src/Generator.cpp

Prefer !empty() to size()>0

---

src/Bounds.cpp
src/Pipeline.cpp
src/Pipeline.h
src/Simplify_LT.cpp
src/Simplify_Mod.cpp
src/StorageFolding.cpp
test/correctness/simplify.cpp

The intent is to reduce the size of the diff with the new autoscheduler branch so that we can merge it soon. These are the main changes in that branch in the src/ folder. The bulk of the remaining changes are all to the apps.

Grab-bag of fixes from the autoscheduler branch

---

src/runtime/qurt_threads.cpp

...to match the pipeline context

Change the priority of QURT thread pool threads

---

src/Func.cpp

SImpler version of https://github.com/halide/Halide/pull/3783

Fix incorrect buffer allocation in Func::infer_input_bounds()

---

src/HexagonOffload.cpp
src/runtime/hexagon_host.cpp

Pipelines with a large number of buffers can generate closures with huge numbers of scalars (up to 3 per dimension of a buffer). This passes scalars in a buffer instead of as individual scalars, reducing the number of arguments to the closure function. This avoids some compile time issues in LLVM.

Pass scalars for Hexagon offload in a buffer

---

apps/onnx/Makefile
apps/onnx/onnx_converter.cc
apps/onnx/onnx_converter.h
apps/onnx/onnx_converter_test.cc

Also developed a regression test.
A more complete solution that autoschedule these pipelines and run them is next. This will also enable us to run the entire ONNX compliance testsuite.

Small c++ library that converts ONNX models into Halide pipelines

---

Makefile
src/CodeGen_LLVM.cpp
src/JITModule.cpp
src/Target.h
test/correctness/extern_error.cpp

Grab bag of minor fixes (formatting, etc) from the wasm branch to reduce irrelevant deltas.

Minor changes from wasm branch

---

Makefile
src/Generator.h
test/CMakeLists.txt
test/generator/string_param_aottest.cpp
test/generator/string_param_generator.cpp
test/generator/stubtest_generator.cpp
test/generator/stubuser_generator.cpp

This will allow us to pass and AOT arbitrary serialized objects (e.g onnx protobuffs).

Allow GeneratorParam<std::string>

---

src/Simplify_Max.cpp
src/Simplify_Min.cpp

Restrict some rules to no-overflow types

---

src/Bounds.cpp

When encountering let(name, value, body) in bounds, we use a symbolic .min/.max for the bounds of the value within the body. This misses a lot of simplifications that happen when the bounds are a single point. This PR changes things so that if the bounds of the value are a single point, we push .min/.min onto the scope instead of .min/.max. Fixes #3824 , though it wouldn't if a pure var were involved too.
Also adds an early-out in func value bounds inference for scalar funcs, which is another incidental fix for the same issue which again wouldn't help if a pure var were involved.

Handle bounds of lets where the value is a single point more concisely

---

apps/onnx/onnx_converter.cc
apps/onnx/onnx_converter.h
apps/onnx/onnx_converter_generator.cc
apps/onnx/onnx_converter_generator_test.cc
apps/onnx/onnx_converter_test.cc

Upstream onnx_converter library updates.

Onnx converter updates

---

src/Bounds.cpp

Propagating the value of zero-dim functions can result in references to inlined funcs remaining in the IR until codegen time, which makes everything fail. Backing this part out pending possible future investigation.

Remove part of https://github.com/halide/Halide/pull/3825

---

Makefile
src/LLVM_Headers.h

Change dependency on lld to be for WITH_V8 instead of WITH_WEBASSEMBLY.

---

Makefile
apps/onnx/Makefile

This will gracefully exit if protoc isn't installed on the Buildbot

Add apps/onnx/test to test_apps

---

src/runtime/HalideRuntime.h
src/runtime/msan.cpp
src/runtime/msan_stubs.cpp
src/runtime/posix_error_handler.cpp
src/runtime/printer.h
src/runtime/trace_helper.cpp
test/generator/msan_aottest.cpp

This allows Codegen_C to use msan cleanly.

Fix msan helper return types

---

src/Scope.h
src/SimplifyCorrelatedDifferences.cpp

It's causing segfaults in #3774

Use less stack space in simplify correlated differences visitor

---

src/runtime/cuda.cpp

Add threads-per-core configurations for newer shader models, and fix computation of total number of cores.

fix CUDA debug output

---

Makefile
apps/nn_ops/common.cpp

Fix apps/nn_ops (Issue #3897)

---

Makefile
apps/HelloMatlab/Makefile
apps/auto_viz/Makefile
apps/autoscheduler/Makefile
apps/bilateral_grid/Makefile
apps/blur/Makefile
apps/c_backend/Makefile
apps/camera_pipe/Makefile
apps/camera_pipe/viz.sh
apps/conv_layer/Makefile
apps/cuda_mat_mul/Makefile
apps/cuda_mat_mul/runner.cpp
apps/fft/Makefile
apps/glsl/Makefile
apps/hexagon_benchmarks/Makefile
apps/hexagon_dma/Makefile
apps/interpolate/Makefile
apps/lens_blur/Makefile
apps/linear_algebra/Makefile
apps/local_laplacian/Makefile
apps/local_laplacian/viz.sh
apps/nl_means/Makefile
apps/nn_ops/Makefile
apps/onnx/Makefile
apps/resize/Makefile
apps/resnet_50/Makefile
apps/stencil_chain/Makefile
apps/support/Makefile.inc
apps/wavelet/Makefile

Clean up apps makefiles

---

apps/support/Makefile.inc

This should address ongoing breakage of test_apps_3 on linux64

Add stub declarations to Makefile.inc for hvx128

---

src/ScheduleFunctions.cpp
test/correctness/issue_3926.cpp

Don't replicate the original stmt when doing specialize_fail()

---

Makefile
src/CodeGen_LLVM.cpp
src/LLVM_Headers.h

This is still in draft mode, but sending it out now to get feedback.
@chandlerc: comments welcome.

Switch to LLVM's NewPassManager.

---

src/runtime/hexagon_remote/halide_remote.cpp

Clone of https://github.com/halide/Halide/pull/3939 for testing

---

README.md

Delete what I believe is long-outdated and incorrect information.

Remove incorrect GCD reference from README

---

src/DebugArguments.cpp
src/DebugArguments.h
src/Lower.cpp

Print target when in debug mode

---

src/CodeGen_C.cpp

This fixes an implicit cast to 32-bit that seems unintentional. (Though
without a size_t type equivalent, choosing a single 32-bit or 64-bit
type for sizes seems to be guaranteed to be wrong in one C compilation
environment or another.)

Do not use frontend Var type in rewriting IR at codegen level.

---

src/runtime/HalideBuffer.h

Make it clearer that certain buffer methods are just metadata operations

---

src/Derivative.cpp
src/runtime/HalideBuffer.h

- typo in HalideBuffer.h
- always prefer .empty() to compareing .size() vs zero

Fix minor ClangTidy issues

---

src/CSE.cpp
src/Deinterleave.cpp
src/DerivativeUtils.cpp
src/HexagonOptimize.cpp
src/IRMutator.cpp
src/IRMutator.h
src/LoopCarry.cpp
src/Substitute.cpp

Rename IRGraphMutator2 -> IRGraphMutator

---

src/AutoSchedule.cpp
src/Bounds.cpp
src/Interval.cpp
src/Interval.h
src/Solve.cpp
test/correctness/interval.cpp

Experiment to see if we can remove the need for HALIDE_EXPORT for data members

Don't export Interval::pos_inf/neg_inf

---

src/Generator.cpp
src/Generator.h
src/Util.cpp
src/Util.h

Reverts halide/Halide#3524 -- see https://github.com/halide/Halide/pull/3524#issuecomment-513884622

Revert "Reset unique name counters before the compilation of each target."

---

src/runtime/HalideBuffer.h

Simpler alternative to https://github.com/halide/Halide/pull/4026, per @abadams suggestion

Smarten code expansion in Buffer::copy_from() (V2)

---

apps/autoscheduler/AutoSchedule.cpp
apps/autoscheduler/DefaultCostModel.cpp
apps/autoscheduler/test.cpp
apps/autoscheduler/train_cost_model.cpp
src/Generator.cpp

Added missing header files for compiling an Autoscheduler app using Visual Studio compiler.
Added printing of the error code value and the error message for a fault load of the DLL in the generator (-p option).

Autoscheduler app MSVC support

---

src/Simplify_Mod.cpp

Fixes #4047 
Same problem as the last div fix. We were simplifying 0 % 0 to 0.

Avoid simplifying mod-by-zero

---

src/runtime/HalideBuffer.h

Make a constexpr variant of make_shape_storage(), so that call sites that know at compiletime that dimensions <= D don't have to insert code to consider a dynamic allocation

Minor optimization to make_shape_storage

---

Makefile

See https://www.gnu.org/software/make/manual/make.html#Phony-Targets for
an explanation of this idea.

Build benchmark apps in parallel (run in serial)

---

apps/autoscheduler/CostModel.h
apps/autoscheduler/FunctionDAG.h
apps/autoscheduler/PerfectHashMap.h

also, drive-by sorting of includes

Add missing includes in apps/autoscheduler

---

src/Module.cpp

- avoid unnecessary blank lines
- avoid lines that are whitespace-only

Tweak schedule.h output

---

src/Module.cpp

Previous codegen was bogus and assert-fail-laden; it's not a useful case, but it shouldn't crater.

Generate legal .schedule.h file for non-auto-schedule code

---

src/CodeGen_LLVM.cpp
src/StorageFlattening.cpp

This works around the issue described in #4211.

Fix prefetching after bfloat16 changes

---

apps/support/cmdline.h

It uses C++ exceptions for some failure modes, which is (sadly) inconvenient for some downstream users who compile without exceptions enabled by default. Convert to build with cerr/exit error reporting by default.

Modify cmdline.h to not require exceptions

---

src/Bounds.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/CodeGen_Internal.h
src/CodeGen_LLVM.cpp
src/CodeGen_OpenCL_Dev.cpp
src/IROperator.cpp
src/IROperator.h
src/Simplify_Call.cpp
test/correctness/bitwise_ops.cpp
test/correctness/simd_op_check.cpp

A bit shift by a negative amount is now defined as a shift by a positive
amount in the opposite direction.

Enable bit shifts by negative amounts.

---

src/CodeGen_LLVM.cpp

See https://github.com/halide/Halide/issues/3957 for details.

Re-enable LLVM NewPassManager

---

CODE_OF_CONDUCT.md

Here's a proposed code of conduct. Comments/changes welcome.
It's important to note that this is not a reaction to anything. We haven't had any problems that would require this and I hope we never do, but better to have one and not need it than need one and not have it.
Fixes #4256

Add draft code of conduct

---

python_bindings/correctness/float_precision_test.py
python_bindings/src/PyConciseCasts.cpp
python_bindings/src/PyExpr.cpp

see https://github.com/halide/Halide/pull/4247#issuecomment-537322606

throw warning when detect lose precision

---

python_bindings/tutorial/lesson_03_debugging_1.py

(Change is from some automated Py2->3 migration tools inside Google)

Improve Python3 compatibility in lesson_03_debugging_1.py

---

src/Target.cpp

Remove repeated declaration of initial_features

---

README.md

The website now advertises Halide as an "image and array processing language". We should do the same for the readme.
In general we should make the readme friendlier, give some hints regarding what Halide can do, who are the target audiences, what does Halide code look like, etc. We should also mention the Python bindings. I'll draft something these days.

Update README description to match the website

---

src/Derivative.cpp

A cosmetic change in Derivative.cpp that replaces make_const with make_zero and make_one when possible.

make_const -> make_zero or make_one in Derivative.cpp

---

README.md

It should also be mentioned in the webpage. I am drafting a tutorial.

Mention Python bindings in README

---

test/correctness/cast.cpp

Properly test explicit floating point casting

---

apps/HelloPyTorch/.gitignore
apps/HelloPyTorch/README.md
apps/HelloPyTorch/modules.py
apps/HelloPyTorch/src/add_generator.cpp
src/CodeGen_PyTorch.cpp

- remove no-longer-needed .gitignore
- trim all trailing blank space
- add estimates to add_generator.cpp
- Codegen_PyTorch declares the `_th_` functions as `inline`
attn @mgharbi

Misc minor PyTorch cleanups

---

src/Argument.h
src/Generator.cpp

Fix dangling MinAndExtent

---

apps/autoscheduler/CMakeLists.txt
apps/autoscheduler/Featurization.h
apps/autoscheduler/FunctionDAG.cpp
apps/autoscheduler/FunctionDAG.h
apps/autoscheduler/Makefile
apps/autoscheduler/test_function_dag.cpp

Leverage the proxy (if any) to generate pipeline features for extern functions. There's still work to do to model the memory accesses, but we can already have a sense of how much computation is done by the black box (assuming that the proxy is accurate), which should help the auto-scheduler further down the road. Note that this PR doesn't address the generation of schedule features, which will be handled in a follow up PR.

Improved generation of Pipeline features for extern functions

---

src/Func.cpp
src/Function.cpp
src/Function.h

Made sure the arguments of extern functions are of type Var instead ofmstring immediates.

Fixed the types of the args of extern functions

---

src/CodeGen_C.cpp

We're playing pretty fast-and-loose with make_struct to generate halide_dimension_t arrays inline by making an array of ints and reinterpreting the pointer as a smaller array of halide_dimension_t. Newer gcc versions complain that the dimension array may be uninitialized if you do this. This PR specializes make_struct emission for the halide_dimension_t and prints a nicer array of initialized halide_dimension_t objects instead.

Avoid type punning in the generated C for buffer shapes

---

src/runtime/opencl.cpp

To address https://github.com/halide/Halide/issues/4459 .

Increase max device count to query in OpenCL runtime

---

src/FuseGPUThreadLoops.cpp

If unchecked it fails down the road with some obscure message. 
Related to https://github.com/halide/Halide/issues/4466

Check if shared memory allocation is bounded

---

tutorial/lesson_08_scheduling_2.cpp

Thanks for the great tutorials! I noticed some typos in the text/comments, so this pull request fixes them to the best of my understanding.

Fix typos in tutorial/lesson_08_scheduling_2.cpp

---

apps/autoscheduler/PerfectHashMap.h
apps/autoscheduler/included_schedule_file.schedule.h
apps/conv_layer/process.cpp

This subtree has stayed remarkably close to correct.

Reapply clang-format to apps/**

---

Makefile

Legacy from the LLVM changeover from svn -> git

Remove useless definition in Makefile

---

apps/linear_algebra/Makefile

Reinsert check for cblas.h

---

apps/nl_means/nl_means_generator.cpp
apps/nl_means/process.cpp

I am continuing to roll through the apps, making sure everything has a decent schedule and a benchmark on the same machine. This PR addresses the nl_means app.

Reschedule and benchmark nl_means app

---

apps/autoscheduler/AutoSchedule.cpp

 Take strides into account when figuring out which dimensions to

---

Makefile

FWIW, we use install_qc internally

Deprecate Hexagon v60 in the Makefile too

---

src/CodeGen_OpenCL_Dev.cpp

Sorry, I broke it in the previous PR.

Fix indentation in the OpenCL codegen

---

apps/support/cmdline.h

Poached from https://github.com/halide/Halide/pull/4556 to land ahead of that

Allow cmdline.h without RTTI

---

test/common/halide_test_dirs.h
test/correctness/image_io.cpp
tools/halide_image_io.h
tutorial/lesson_12_using_the_gpu.cpp

Fix of "jpeglib.h" vs. <windows.h> issue

---

src/runtime/HalideRuntimeCuda.h
src/runtime/HalideRuntimeD3D12Compute.h
src/runtime/HalideRuntimeHexagonDma.h
src/runtime/HalideRuntimeHexagonHost.h
src/runtime/HalideRuntimeMetal.h
src/runtime/HalideRuntimeOpenCL.h
src/runtime/HalideRuntimeOpenGL.h
src/runtime/HalideRuntimeOpenGLCompute.h
src/runtime/HalideRuntimeQurt.h

All in the title. Clang-format saw fit to change a line, too.

Fix #4624 by adding include guards around the actual includes in Runtime headers

---

src/Bounds.cpp
src/CodeGen_Hexagon.cpp
src/CodeGen_Internal.cpp
src/Introspection.cpp
src/PythonExtensionGen.cpp
src/ThreadPool.h

Follow-up to #4642 to catch asserts elsewhere in the compiler that should be internal_assert

assert -> internal_assert

---

src/CodeGen_ARM.cpp
src/CodeGen_ARM.h

simd_op_check fails on arm64 with newer llvms
See https://bugs.llvm.org/show_bug.cgi?id=45036

Work around llvm bug

---

test/CMakeLists.txt

Was recently added to Makefile

Support optional ARCH_FOR_TEST in CMake too

---

test/correctness/storage_folding.cpp

Bounds queries are supposed to nest. If a region O of the output
requires region I of the input, then a subset of O is supposed to
require a subset of I. Not sure what was going on with this extern
stage, but it didn't obey that property. I rewrote it.

Fix invalid extern stage in storage_folding test

---

python_bindings/correctness/compile_to.py
src/PythonExtensionGen.cpp

This PR fixes python bindings build and test issues on Windows.

Fix python binding build and test issues on Windows

---

CMakeLists.txt

-Wno-psabi only for GCC

---

.github/workflows/test.yml
test/auto_schedule/histogram.cpp
test/auto_schedule/mat_mul.cpp
test/auto_schedule/max_filter.cpp
test/auto_schedule/reorder.cpp
tutorial/lesson_16_rgb_run.cpp
tutorial/lesson_21_auto_scheduler_run.cpp

Even running serially, too much flakiness.

Don't even try to run test_performance on GHA VMs

---

src/Deinterleave.cpp

Bug was introduced by a recent PR

Fix incorrect deinterleave of a shuffle

---

src/ScheduleFunctions.cpp

More specific compute_with error message

---

apps/gradient_autoscheduler/CMakeLists.txt

Also, fix PATH for run_gradient_autoscheduler_test_cpp on Windows

Add run_gradient_autoschduler_test_py

---

python_bindings/apps/bilateral_grid.py

GPU fixes for python_bindings/apps/bilateral_grid.py

---

python_bindings/apps/bilateral_grid.py

Fix obsolete interface usage in GPU schedule.

Clone of https://github.com/halide/Halide/pull/4805 for testing

---

.github/workflows/presubmit.yml

edited and review_requested are irrelevant for the purposes of presubmit.yml

Remove unnecessary pull_request types

---

src/AddImageChecks.cpp
src/AddImageChecks.h
src/AllocationBoundsInference.cpp
src/ApplySplit.cpp
src/Bounds.cpp
src/BoundsInference.cpp
src/IR.cpp
src/IR.h
src/Lower.cpp
src/ScheduleFunctions.cpp
src/SimplifyCorrelatedDifferences.cpp
src/Simplify_Stmts.cpp
src/StorageFolding.cpp
src/StorageFolding.h
src/TrimNoOps.cpp
test/correctness/CMakeLists.txt
test/correctness/compute_inside_guard.cpp
test/correctness/dead_realization_in_specialization.cpp
test/correctness/extern_output_expansion.cpp
test/correctness/nested_tail_strategies.cpp

This seemingly minor change could have large consequences. I'll watch the buildbots. This would also need checking on Google pipelines.

Move add_image_checks after bounds inference (See #3036)

---

src/LICM.cpp

Revert "Keep constants outermost in LICM"

---

src/CodeGen_PyTorch.cpp

We often get lucky, but on some cuda-less systems (eg arm) we can crash inside the JIT because bits of Cuda-related stuff aren't present.

Only run PyTorch+CUDA test if host supports it

---

src/Function.cpp
src/IROperator.cpp
src/Pipeline.cpp
src/Util.cpp
test/correctness/assertion_failure_in_parallel_for.cpp
test/correctness/heap_cleanup.cpp
test/correctness/parallel_fork.cpp
test/generator/async_parallel_aottest.cpp
test/generator/multitarget_aottest.cpp
test/generator/user_context_insanity_aottest.cpp

Make sure all std::atomics are initialized

---

src/ScheduleFunctions.cpp

GuardWithIf on RVars seems to be producing conditions of the form
likely(likely(condition)).
The predicate is a mix of stuff from the user and stuff from splits, so
there's no single source of likelies for me to go fix instead.
This was causing an issue in the atomic_vectorization branch. It can be separately fixed though.

Don't wrap a likely around an RDom predicate if it's already got one.

---

apps/support/Makefile.inc

better error message if you try to build an app before libHalide

---

src/CodeGen_D3D12Compute_Dev.cpp
src/CodeGen_Metal_Dev.cpp
test/correctness/isnan.cpp

Apparently nobody's ever used is_nan_f32 from a metal pipeline yet.

Add is_nan_f32 for metal

---

.gitignore
src/Func.h
src/IRMatch.h
src/Pipeline.h
src/Schedule.h
src/Var.h

Also fix a bunch of doxygen warnings.

Better documentation for the contents of Schedule.h

---

src/CodeGen_ARM.cpp
test/correctness/simd_op_check.cpp

Work around LLVM 9 horizontal op issue

---

.github/workflows/test.yml

GHA now has a way to manually trigger runs (but it needs to be in master to take effect). Want to check this in to experiment with it some.

Try adding manual controls to GHA Builder

---

src/ScheduleFunctions.cpp
test/correctness/compute_with.cpp

Fix #5178: Fix the case when functions from the fused group have different store_levels

---

src/Func.cpp
test/error/CMakeLists.txt
test/error/bad_reorder.cpp
test/error/bad_reorder_storage.cpp

Check for duplicate vars in calls to reorder/reorder_storage

---

src/CodeGen_Internal.cpp
src/CodeGen_LLVM.cpp

get_vector_num_elements has changed again due to SVE-related stuff

Fix for llvm trunk

---

src/Func.cpp

Also makes them more similar to some of the other error messages in that file.

More detailed error messages for *_storage functions of Func

---

src/VectorizeLoops.cpp

Delete incorrect dead code and replace with unimplemented error

---

src/CodeGen_D3D12Compute_Dev.cpp

This enables scalarization for loads/stores from shared memory for D3D12Compute.
(Note that is a PR into a branch, not master).

Modify load/store codegen to support load/store from/to shared mem

---

README.md

Not Hacktober spam, I promise! Adding some info about package managers to the README including the new Homebrew install.

Add package manager info to README.md

---

src/CodeGen_LLVM.cpp

Fix for trunk LLVM

---

CMakeLists.txt
README.md

Should probably update the README in master, too.

Bump version number to 10.0.1

---

dependencies/llvm/CMakeLists.txt

As it says above. Simple to fix and we haven't released 10.0.1 yet.

Backport 5419 to 10.0.1

---

dependencies/llvm/CMakeLists.txt

Fix GCC -> GNU in generator expressions

---

src/Bounds.cpp

I think for this code we want a runtime check if it's zero or not.
@rootjalex

is_zero is a compile-time check if it's the constant zero

---

util/HalideTraceViz.cpp

- Handle 4D inputs more gracefully
- Improve horizontal squishing of long labels

Improvements to HalideTraceViz

---

src/HexagonOptimize.cpp
src/IROperator.cpp
src/IROperator.h

This simplifies some code, and some code in a WIP branch.

Replace is_negative_negatable_const and more logic with lossless_negate

---

apps/CMakeLists.txt
apps/fft/CMakeLists.txt
apps/fft/fft_aot_test.cpp

Works, but missing two features:
1. FFTW integration.
2. Small stacks on macOS.
Based on #5507

Adding CMake build for FFT

---

test/generator/gpu_multi_context_threaded_aottest.cpp

Revert "Fix broken destroy_context() in gpu_multi_context_threaded_aottest.cpp"

---

apps/interpret_nn/tflite/tflite_parser.cpp

The new shape can be specified in a 2nd input (instead of the ReshapeParams); we should handle this properly

TFLiteParser should handle the 2-input form of Reshape

---

src/CodeGen_OpenCL_Dev.cpp

Similar to CLHalf feature check for half type.

Add CLDoubles feature check for OpenCL double type

---

src/Generator.cpp
src/runtime/opengl_egl_context.cpp

We were ignoring the result from a couple of calls.

Check error results from all egl calls

---

CMakeLists.txt

Should have done this before creating the branch, but oops.

Fix version to 11.0.0

---

README.md

Testing a PR for the new webhooks infrastructure. Not getting merged to master. Please ignore.

Test PR please ignore

---

src/CodeGen_Hexagon.cpp
src/HexagonOptimize.cpp
test/correctness/simd_op_check_hvx.cpp

[Hexagon] Add rounding shift right instructions

---

src/Generator.cpp
src/Generator.h

More changes cherry-picked from a work-in-progress to simplify the surface area of the API a bit and make subsequent PRs easier to review. Should be no end-user-visible difference.

Simplify some Generator code

---

src/Argument.cpp
src/CodeGen_C.cpp
src/Profiling.cpp
src/runtime/device_interface.h

Notably, this would have caught all the issues fixed in #5716

Fix a few warnings from lgtm.com

---

src/CodeGen_Internal.cpp

(Might need to wait for new nightly builds of LLVM to land)

Fix for top-of-tree LLVM

---

src/Simplify.cpp
src/Simplify_Add.cpp
src/Simplify_Div.cpp
src/Simplify_Internal.h
src/Simplify_LT.cpp
src/Simplify_Let.cpp
src/Simplify_Max.cpp
src/Simplify_Min.cpp
src/Simplify_Mul.cpp
src/Simplify_Stmts.cpp
src/Simplify_Sub.cpp
test/correctness/simd_op_check_hvx.cpp
test/correctness/simplify.cpp

Forking some independent changes from #5755

Various simplifier improvements from dsharletg/sliding-window

---

Makefile
test/correctness/simd_op_check.cpp
test/error/metal_threads_too_large.cpp
test/performance/fast_inverse.cpp

Now that we actually have a buildbot testing thing, a few minor issues were discovered. The big one is #5786

Fixes for macos on arm

---

src/CodeGen_LLVM.cpp

#5784 had a bad bug in it, this fixes it.

Fix bug found by asan from #5784

---

cmake/toolchain.linux-arm32.cmake

Also add comments.
(Trying this as an alternative to https://github.com/halide/Halide/pull/5805)

Set CMAKE_CROSSCOMPILING_EMULATOR in toolchain.linux-arm32.cmake

---

src/LLVM_Runtime_Linker.cpp

move test for ARM + metal to AARCH64

support building for m1 with only AARCH64 target

---

apps/hannk/halide/convolution_generator.cpp
apps/hannk/interpreter/model.h
apps/hannk/interpreter/ops.cpp

Conv2D with small channels or width fell into pathological code. This makes the worst case much more reasonable.

Improve performance on some pathological cases

---

dependencies/wasm/CMakeLists.txt
src/CodeGen_WebAssembly.cpp
src/runtime/wasm_math.ll
test/correctness/simd_op_check.cpp

Add support for widening_mul in wasm

Add support for widening_mul in wasm

---

src/VectorizeLoops.cpp
test/correctness/vectorize_nested.cpp

For the IfThenElse node with 'likely' in the condition, vectorize_loops will create an else branch and scalarize it by wrapping it into serialized version of vectorized loops encountered so far, however, the inner statement of 'likely' still may contain other vectorized loops, which should be safe to vectorize.

Try to vectorize inner statement of else branch of likely

---

tutorial/lesson_08_scheduling_2.cpp

Fix typos in tutorial

---

src/BoundsInference.cpp

Producers scheduled innermost didn't always benefit from .guarded versions of vars (with a promise_clamped on them) because bounds inference just goes and gets the var by name in some circumstances. In those circumstances I made it check for a guarded version of the var in scope.

Use guarded versions of vars if they exist in bounds inference

---

src/runtime/HalideRuntime.h

Just a port of https://github.com/halide/Halide/pull/4389 to the equivalent methods in HalideRuntime.h, since offset-from-a-null-pointer is UB in C++.

Fix UB in halide_buffer_t::size_in_bytes

---

apps/cuda_mat_mul/Makefile
apps/cuda_mat_mul/mat_mul_generator.cpp
apps/cuda_mat_mul/runner.cpp

The schedule had rotted, and was no longer a good one on current cards.

Simplify and improve cuda_mat_mul schedule

---

src/InlineReductions.cpp
src/InlineReductions.h
test/correctness/inline_reduction.cpp

This makes them schedulable if necessary without having to rewrite parts of someone's pipeline.

Let the user pass the Func to use to the reduction helpers

---

src/CodeGen_Metal_Dev.cpp

Suppress Metal unused function warning

---

test/correctness/vector_reductions.cpp

Revert "Temporarily disable hanging test" (#5926)

---

tutorial/lesson_06_realizing_over_shifted_domains.cpp

Signed-off-by: xgupta <shivam98.tkg@rediffmail.com>

Small Typo fix in lesson 06

---

apps/CMakeLists.txt

...but with an option for disabling it, for the buildbots

Add apps/hannk to apps/CMakeLists.txt

---

apps/hannk/tflite/CMakeLists.txt

Apparently using SOURCE_SUBDIR + FetchContent_MakeAvailable() doesn't work on the buildbots. This is equivalent and does work. ¯\_(ツ)_/¯

Fix FetchContent for hannk

---

apps/hannk/CMakeLists.txt
apps/hannk/tflite/CMakeLists.txt

The local version might be too old for TFLite

Ensure our local flatbuffers.h is included in preference to system variants

---

tutorial/CMakeLists.txt

Peeling off of #5754 - fixes a bug in the tutorial 15 test. Seems this wasn't being tested in CI on Windows?

Fix tutorial 15 test

---

cmake/HalideGeneratorHelpers.cmake

When using the vcpkg toolchain (which we recommend on Windows), the `add_executable` command is overridden (on Windows) to scan the executable for dependent DLLs, find them in the vcpkg tree, and copy them into the same directory as the executable. When this is the case, the `PATH` variable is ignored. This means that setting the `PATH` variable like we do does _nothing_ for our vcpkg users on Windows. It also breaks certain cross-compiling scenarios by making CMake ignore the `CMAKE_CROSSCOMPILING_EMULATOR` variable on Windows, because the first argument is no longer the generator target, but an absolute path to the CMake executable.
Even worse, [prior to version 3.20.1](https://gitlab.kitware.com/cmake/cmake/-/issues/21973), CMake's Ninja Multi-Config generator could write invalid …

Don't add Halide DLL to PATH on Windows.

---

apps/hannk/interpreter/ops.cpp

Alternative to #5980 to fix OOB reads on AVX512.

Don't hardcode depthwise padding

---

apps/hannk/benchmark.cpp
apps/hannk/compare_vs_tflite.cpp
apps/hannk/delegate/hannk_delegate.cpp
apps/hannk/delegate/hannk_delegate.h
apps/hannk/delegate/hannk_delegate_adaptor.cpp
apps/hannk/delegate/hannk_delegate_provider.cpp
apps/hannk/interpreter/model.h
apps/hannk/interpreter/ops.cpp
apps/hannk/tflite/tflite_parser.cpp
apps/hannk/util/buffer_util.h
apps/hannk/util/error_util.h
apps/hannk/util/file_util.h

Quick-n-dirty rename to avoid conflicts with Abseil/google3. Longer term fix will be forthcoming.

Rename CHECK->HCHECK, LOG->HLOG in hannk

---

apps/bilateral_grid/Makefile

Remove duplicate -e argument in bilateral_grid

---

apps/hannk/interpreter/transforms.cpp

- Don't try to alias a tensor that already has been allocated
- Fix ridiculous bug

Fix tensor aliasing issues

---

CMakeLists.txt

No need for buildbots for this.

Bump Halide version to 13.0.0

---

src/CodeGen_LLVM.cpp
test/correctness/align_bounds.cpp

Don't emit aligned loads to unaligned addresses

---

src/CodeGen_LLVM.cpp
test/correctness/align_bounds.cpp

(cherry picked from commit 626c34a22f350a7d5ce430ff9c012cf45eb01645)

Backport #6047

---

tools/halide_benchmark.h

In the variant that tries to compute a good samples/iters value based on min_time, there's a pathological case if the environment's timer is relatively coarse, and the op being profiled is relatively fast; in this case, you can end up with timings that are very close to zero (or *literally* zero), and our attempt to calculate the number of iterations can explode into the billions, making the benchmark appear to hang (as it may take an absurd length of time to run). To fix this, add a maximum value for iters_per_sample, and smarten the calculation for when the measured time is tiny.

Avoid pathological cases in halide_benchmark()

---

.github/workflows/packaging.yml

Enable ubuntu packaging

---

apps/hannk/util/model_runner.cpp
apps/hannk/util/model_runner.h

Minor fixes to eliminate noise.

[hannk] Make compare_vs_tflite with --verbose 0 less noisy

---

src/HexagonOptimize.cpp
test/correctness/simd_op_check_hvx.cpp

I was searching for an issue, stumbled across this one, and it looked easy to fix.

Fix Hexagon vrmpy with 16-bit results (#4248)

---

apps/hannk/halide/common_halide.cpp
apps/hannk/halide/common_halide.h
apps/hannk/halide/conv_generator.cpp
apps/hannk/halide/depthwise_conv_generator.cpp

This enables customizing this bit of logic per-target more easily.

Move quantization to a helper function depending on the target

---

tutorial/todo.txt

This is based on our discussion in the dev meeting. Feel free to suggest changes.

Update tutorial todos

---

src/AddImageChecks.cpp
src/Bounds.cpp

I upgraded some debugging code in AddImageChecks and Bounds while tracking down a bug, and I think the upgrades are worth keeping for future use.

Augment debugging code

---

src/CodeGen_LLVM.cpp

(Note that this will break until the buildbots pick up the nightly LLVM change; getting it out there to be ready to land in the morning.)

Fix for upcoming LLVM API change

---

src/Generator.cpp

Make sure to join the generator watchdog timer when an exception is
thrown. Otherwise the error message gets swallowed entirely and you just
get "terminate called without an active exception"
Also rejiggered the watchdog to do a timed wait on a condition variable
instead of polling every 100ms.

Join generator watchdog timer if exception thrown

---

src/runtime/HalideRuntime.h
src/runtime/d3d12compute.cpp
src/runtime/metal.cpp
src/runtime/synchronization_common.h

Remove more obsolete MachO/COMDAT workarounds

---

src/CodeGen_LLVM.cpp

We must use use_global_gc = false to work properly with the JIT

One more ASAN fix

---

packaging/CMakeLists.txt

Include LICENSE.txt in package

---

apps/support/Makefile.inc

Minor hygiene to make it easy to build AOT apps with TSAN or ASAN.

Set up SANITIZER_FLAGS and OPTIMIZE for apps/Makefile.inc

---

dependencies/wasm/CMakeLists.txt
src/WasmExecutor.cpp

(cannot land until https://github.com/WebAssembly/wabt/pull/1788 lands)

Update WABT to 1.0.25

---

apps/hannk/halide/elementwise_generator.cpp

It's the only Generator in Halide that uses build() instead of generate() (aside from tests designed specifically to test build()); convert it to keep things nice and consistent.

Convert apps/hannk/Elementwise to use generate()

---

tutorial/lesson_08_scheduling_2.cpp

Remove incorrect not-multiple-of-16 claim

---

apps/hannk/util/buffer_util.h
python_bindings/src/PyBuffer.cpp
src/Buffer.h
src/Generator.h
src/runtime/HalideBuffer.h
test/correctness/halide_buffer.cpp
tools/halide_image_io.h

Existing name is kinda clunky, this seems terser and cleaner

Rename BufferDimsUnconstrained -> AnyDims

---

src/CodeGen_PTX_Dev.cpp

LLVM devs indicate that none of the passes in this usage actually do anything and it can be safely removed.

Remove legacy::FunctionPassManager usage in Codegen_PTX_Dev

---

apps/hannk/README.md

The current one is being sunsetted

Update hannk README link to hosted models page

---

src/Generator.cpp

The recent refactoring that added `execute_generator` accidentally nuked setting these two GeneratorParams. Oops. Fixed.

Fix auto_schedule/machine_params parsing

---

.gitignore
src/Func.cpp
src/ParallelRVar.cpp
test/correctness/CMakeLists.txt
test/correctness/reduction_predicate_racing.cpp
test/error/CMakeLists.txt
test/error/rdom_where_races.cpp

Check RDom::where predicates for race conditions

---

src/RegionCosts.cpp

Handle saturating_cast in compute_expr_cost()

---

python_bindings/CMakeLists.txt
python_bindings/setup.py
src/autoschedulers/common/CMakeLists.txt

Discovered while testing in manylinux

Two quick build fixes

---

README_cmake.md
README_python.md
cmake/HalideGeneratorHelpers.cmake
python_bindings/test/generators/CMakeLists.txt

Add `add_halide_runtime` rule

---

README_cmake.md

Bad syntax. I missed this in review.

Fix markdown links

---

src/PythonExtensionGen.cpp

This moves most of the interesting code into the common module block, so we don't risk duplicating code for extensions that contain multiple function definitions.

Refactor buffer-unpacking code in PythonExtensionGen

---

cmake/HalideGeneratorHelpers.cmake

(Not certain if this is the right fix, but seems plausible)

Apply _Halide_place_dll() to _Halide_gengen (#6999)

---

test/performance/fast_pow.cpp

Try to gather info to track down heisenbug

Log target info in performance_fast_pow (#6997)

---

apps/fft/CMakeLists.txt
apps/fft/Makefile

Want to avoid reporting this known bug while fix is investigated

Temporarily disable testing for apps/fft (#7033)

---

python_bindings/src/halide/_generator_helpers.py

It's really annoying to be using (e.g.) Colab/Jupyter/etc and get errors about "Generator already defined", so sniff for interactive mode and allow re-registration of the same name in that case.

Allow redefinition of Generators when in interactive mode

---

cmake/HalideTestHelpers.cmake
src/Error.cpp
src/Error.h
test/common/terminate_handler.cpp

Add a terminate_handler to try to report unhandled exceptions

---

.github/workflows/pip.yml

Newly released since this script was written

Update pip.yml to use LLVM 15.0.2

---

.github/workflows/pip.yml

Needed to avoid deprecation warnings

Upgrade some Actions in pip.yml

---

src/CodeGen_LLVM.cpp
test/correctness/CMakeLists.txt
test/correctness/simd_op_check_riscv.cpp

Add start of RISC V simd_op_check test.

Fix issue with vector predicated comparison and select instructions.

---

test/correctness/simd_op_check.h
test/correctness/simd_op_check_xtensa.cpp

This is the starting point. Now `HL_TARGET=arm-64-android-tune_generic-xtensa .//test/correctness/correctness_simd_op_check_xtensa "*" gen_tests/` returns ok.

[xtensa] Fixed xtensa simd correctness testing

---

src/runtime/xtensa_io.cpp

This is a better option than posix_io.cpp on Xtensa

[xtensa] Add xtensa_io.cpp

---

test/correctness/simd_op_check_wasm.cpp

Update test following LLVM WASM change https://github.com/llvm/llvm-project/commit/f841ad30d77eeb4c51663e68efefdb734c7a3d07

Update change following LLVM WASM change f841ad30d77eeb4c51663e68efefdb734c7a3d07

---

src/InjectDmaTransfer.cpp

* handle min/max expressions in strides calculations
* more robust check for nested loops

[xtensa] Minor DMA improvements

---

apps/hannk/interpreter/ops.h

This makes it easier for downstream code to experiment with adding ops

Make visit_leaf() public in hannk/ops.h

---

dependencies/llvm/CMakeLists.txt

Fix LLVM 17+ build integration on 32-bit systems

---

apps/hannk/interpreter/tensor.h

hannk: Add few methods for GPU memory interaction.

Add buffer sync methods hannk::Tensor class

---

src/CodeGen_C.h
src/CodeGen_Xtensa.cpp
src/CodeGen_Xtensa.h

(Followup to https://github.com/halide/Halide/pull/7341)

Remove unnecessary overrides in Codegen_Xtensa

---

src/CodeGen_LLVM.cpp
src/CodeGen_LLVM.h

instead of a raw owning pointer

Use a std::unique_ptr for the IR Builder

---

src/CodeGen_C.cpp

Slightly cleaner code.
Also, drive-by change of NULL -> nullptr

Use HalideFreeHelper for the register_destructor

---

apps/hannk/interpreter/model.cpp

You can add your own profiler with strong symbols.

hannk: Provide weak symbol functions to use op profiling

---

.github/workflows/pip.yml

A much-simpler alternative to #7394

Attempt to give proper labels to pip dev builds (v2)

---

src/runtime/HalideRuntime.h
src/runtime/webgpu.cpp

Mostly just using using halide_error_code_t values everywhere.
attn @jrprice

A few minor cleanups in WebGPU backend

---

test/performance/boundary_conditions.cpp

Disable performance_boundary_conditions under WebGPU pending #7420

---

apps/bilateral_grid/bilateral_grid_generator.cpp

The manual CPU bilateral grid schedule was a little compute-root heavy. It's possible to fuse it down into two parallel loop launches, saving some overhead and improving locality. This had a surprisingly large effect (2x speed-up).

Redo CPU schedule for bilateral grid

---

src/CodeGen_C.h
src/CodeGen_Xtensa.cpp
src/CodeGen_Xtensa.h
src/CodeGen_Xtensa_prologue.template.cpp

due to poor performance of xtensa compiler with the new one

[xtensa] Returned old free_helper

---

test/correctness/simd_op_check.h

Skip simd_op_check for disabled targets

---

tutorial/lesson_21_auto_scheduler_generate.cpp

Remove apparently pointless shift in autoscheduler tutorial

---

src/CodeGen_Xtensa.cpp
src/CodeGen_Xtensa_vectors.template.cpp
src/XtensaOptimize.cpp
test/correctness/simd_op_check_xtensa.cpp

also fixed few correctness issues, that were found using updated tests

[xtensa] fixed few correctness issues in codegen + added new correctness tests

---

CMakeLists.txt

We'll be doing a 15.0.1 release with a few fixes soon.

Bump version to 15.0.1

---

CMakePresets.json

Turn on WITH_UTILS in CMakePresets.json for 'package' preset (Fixes #7465)

---

python_bindings/src/halide/__init__.py
python_bindings/src/halide/halide_/PyImageParam.cpp

1. fix halide var `_0` export
2. fix ImageParam `.in` method export

fix python binding method export

---

src/Realization.h
test/error/CMakeLists.txt
test/error/tuple_realization_to_buffer.cpp

Add error message when casting multi-element Realization to Buffer

---

test/fuzz/cse.cpp

Fix fuzz/cse to avoid signed_integer_overflow() results

---

test/fuzz/simplify.cpp

Need to cast to a type that is bool-with-lanes, not scalar bool
attn @silvergasp

Followup to #7551 for bool vectors

---

src/runtime/vulkan_memory.h
test/performance/wrap.cpp

Tracking this under issue #7559

[vulkan] Disable performance_wrap test for Vulkan ... results don't match

---

test/fuzz/bounds.cpp

(Avoids infinite loop for some fuzzing inputs)

Apply fix from #7564 to fuzz/bounds

---

src/LLVM_Runtime_Linker.cpp

More guess based than test based but I'm 82% confident these are good choices. Data layout seems to be the same as well.

Add target triple setup for RISC V Android.

---

README_cmake.md
cmake/HalideGeneratorHelpers.cmake
cmake/toolchain.linux-x64-asan.cmake
python_bindings/CMakeLists.txt
test/autoschedulers/li2018/CMakeLists.txt

This is a PR-to-PR that implements the changes suggested in my review of #7604

Use Halide_PYTHON_LAUNCHER to implement ASAN toolchain fixes

---

Makefile
src/CodeGen_Xtensa.cpp
src/CodeGen_Xtensa_vectors.template.cpp
src/XtensaOptimize.cpp

[xtensa] widen ops, convert, division + abs, gather_load improvements

---

src/Generator.cpp

Accidentally checked in #7697 with the failure mode as error, not warning

Convert error to warning

---

dependencies/llvm/CMakeLists.txt
run-clang-format.sh
run-clang-tidy.sh

Keep it consistent with README

Fix clang and llvm versions in scripts

---

src/DebugToFile.cpp

Also convert a std::vector to a vector in a file that has using std::vector

Remove unused using decl

---

.github/workflows/presubmit.yml
src/Generator.cpp
test/autoschedulers/adams2019/CMakeLists.txt
test/autoschedulers/anderson2021/CMakeLists.txt
test/runtime/CMakeLists.txt

Several subcategories were missing -- let's add them and see if they should be there or not

Update 'Check CMake file lists' action

---

apps/simd_op_check/driver.cpp

Float16 and bfloat16 buffers were missing.

Update arguments in driver.cpp to match what correctness/simd_op_check has

---

src/Func.cpp
src/Func.h
test/correctness/simd_op_check_riscv.cpp
test/error/CMakeLists.txt
test/error/fuse_vectorized_var_with_rvar.cpp

Validate for types when fusing Vars with RVars

---

apps/onnx/Makefile
apps/onnx/onnx_converter_test.cc

Update onnx app to work with newer versions of protobuf

---

src/Module.cpp

https://github.com/halide/Halide/pull/7887#issuecomment-1778179864

Fix bug mentioned by @antonysigma.

---

src/ScheduleFunctions.cpp
test/error/CMakeLists.txt
test/error/hoist_storage_without_compute_at.cpp
test/error/store_at_without_compute_at.cpp

Improve the error message if you store_at without a compute_at

---

src/CodeGen_Xtensa_vectors.template.cpp

Fixed the correctness for native_vector_f32_x2 + added a version for native_vector_f32

[xtensa] Improved load_predicated for float

---

src/CodeGen_ARM.cpp

Fixes #7976
We should be adding these mattrs if those features are requested, for both arm-32 and arm-64

Add appropriate mattrs for arm-32 extensions

---

src/CodeGen_WebAssembly.cpp

Make narrowing float->int casts on wasm go via wider ints

---

python_bindings/src/halide/halide_/PyEnums.cpp
python_bindings/src/halide/halide_/PyFunc.cpp
python_bindings/src/halide/halide_/PyScheduleMethods.h
python_bindings/src/halide/halide_/PyStage.cpp
python_bindings/test/correctness/boundary_conditions.py
python_bindings/test/correctness/realize_warnings.py

We have been sloppy about maintaining these. Also added a bit of testing.

Add missing Python bindings for various recent additions to Func and Stage

---

test/correctness/simd_op_check.h

Broken out into separate PR for ease of review and isolated test/tracking.

Quick fix for crash that is occurring in SVE2 tests.

---

python_bindings/src/halide/halide_/PyIROperator.cpp

Hi. I use this feature a fair amount and I would like to be able to use it in the python bindings.

add unsafe_promise_clamped

---

cmake/HalideGeneratorHelpers.cmake
src/runtime/mini_webgpu.h
src/runtime/webgpu.cpp
test/common/gpu_context.h

Cherry-pick picks for recent WebGPU API changes for a Halide 17.0.1 release

---

tutorial/lesson_17_predicated_rdom.cpp

Hi, 
When I was going through the tutorials I noticed what I believe is a small typo in the documentation. This PR contains the correction.

Small Tutorial Fix

---

src/BoundsInference.cpp
src/Lower.cpp
src/StorageFlattening.cpp
src/autoschedulers/mullapudi2016/AutoSchedule.cpp

1) has_gpu_feature already includes Vulkan, so there's no need to check for it.
2) Use emplace(...) instead of insert(make_pair(...))
3) Fixed a place that should be using a ScopedValue

Fix three nits

---

src/EmulateFloat16Math.cpp
test/correctness/float16_t.cpp

Fix incorrect type in emulation of float16 is_inf/nan

---

packaging/CMakeLists.txt
src/CMakeLists.txt

Splitting this out so that the more important changes are easier to review later.

Clean up serialization build code

---

.github/workflows/pip.yml

Might want to revise the pip-packaging workflow trigger rules.

Upgrade LLVM to 19.1.0 in pip package

---

src/runtime/HalideBuffer.h

Fixes a downstream breakage in google

Add missing #include

---

src/Func.cpp
src/ScheduleFunctions.cpp

A few more comment typos I don't want distracting real code review later.

Fix typos in comments

---

.github/workflows/pip.yml

Because nothing on GitHub Actions works the first time!

Fix workflow for next release

---

.github/workflows/pip.yml
cmake/HalidePackageConfigHelpers.cmake
src/CMakeLists.txt

Fix a couple build issues for Debian introduced during the 18-19 build modernization.
Will need to backport to release/19.x ASAP
ATTN @LebedevRI 
Fixes #8521
Fixes #8522

Fix Debian packaging

---

test/correctness/saturating_casts.cpp

Skip test when code could be using x87

---

src/runtime/HalideBuffer.h

Fix check for Windows never having aligned_alloc available.

---

src/RemoveUndef.cpp
test/correctness/undef.cpp

Fix nested select handling in remove_undef

---

src/LLVM_Runtime_Linker.cpp
test/correctness/simd_op_check_wasm.cpp

Fix WASM splat op check test.

---

test/correctness/simd_op_check_arm.cpp

Should hopefully fix the current buildbot failures.

Make the vld2 pattern more obviously profitable

---

src/Bounds.cpp

This commit separates out the lowering of intrinsics to other expressions to facilitate bounds inference from the actual handling of call nodes. By getting the lowering code off the recursive path, it reduces the size of the stack frame for the call visitor. It also makes the logic a little less confusing (one fewer lambda).
The actual bounds logic is intended to be unchanged.

Refactor bounds of a Call node
